### ISSUE TITLE
Controle via teclado do Player de Video

### ISSUE THREAD

**Issue by peas** [caelum/alura-funcionalidades#1]
Teclas de atalho semelhantes ou melhores que a da versão passada:
- espaço para pausar/despausar
- F para Full Screen
- setas para voltar 10s e avancar 30s

**Comment by designernatan** [comment]
No ar! 

Alguns feitos:
Z e X - controle de 10s
F - fullscreen

Atividade com vídeo e quer dar fullscreen?
Aperta F e depois espaço.

Volume estamos vendo. :)

**Comment by carlosmuller** [comment]
@designernatan esse do Z e X não funcionam,

Entraram mais atalhos:

- Setas laterais +10s e -10s
- M mutar o video
- F para ir para tela cheia
- K ou espaço pausam o video
- X cicla entre as opções de velocidade de repodução do video
- Setas para cima e para baixo, aumentam e diminuem o volume mas para isso tem que estar focado no video

**Comment by maisonsouza** [comment]
@carlosmuller eu estava aguardando muito, 
X cicla entre as opções de velocidade de repodução do video
Setas arrow_up(cima) e para arrow_down(baixo), aumentam e diminuem o volume mas para isso tem que estar focado no video
Acredito que muita gente lá na plataforma ainda não sabe dos atalhos, seria interessante divulgar lá, talvez no proprio player pq na época do trello vi muita gente pedindo essas funcionalidades.
**Uma sugestão seria decrementar as opçoes de velocidade na tecla z**

**Comment by thdesous** [comment]
Senhores, acho que um dos atalhos conflitou com o `Crtl + f` dos navegadores.

Já registrei aqui no [Issues17](https://github.com/caelum/alura-funcionalidades/issues/17)

**Comment by FelipeIgansi** [comment]
Sugiro também adotar um modo de tala parcialmente cheia(nesse modo o menu poderia ser minimizado ;) ) como quando você clica na tecla "T" em algum vídeo do YouTube por exemplo, pois eu particularmente quando estou vendo uma vídeo-aula gosto de colocar a tela dividida(o vídeo e o editor) e quando faço isso atualmente o reprodutor fica minusculo, e acaba ficando um pouco desconfortável.

**Comment by zerinoid** [comment]
existe atalho pra decrementar a velocidade? Eu costumo aumentar e diminuir de acordo com o conteúdo do trecho.

Sugiro também divulgar os shortcuts através de algum botão no player. No udemy por exemplo, vc ve os shortcuts apertando "?", é bem útil

**Comment by designernatan** [comment]
> Sugiro também adotar um modo de tala parcialmente cheia(nesse modo o menu poderia ser minimizado ;) ) como quando você clica na tecla "T" em algum vídeo do YouTube por exemplo, pois eu particularmente quando estou vendo uma vídeo-aula gosto de colocar a tela dividida(o vídeo e o editor) e quando faço isso atualmente o reprodutor fica minusculo, e acaba ficando um pouco desconfortável.


o @xluisfabio [abriu essa issue que resolveria isso,](https://github.com/caelum/alura-funcionalidades/issues/40) o chamado modo teatro

---

@zerinoid hoje o **`X`** se vc apertar algumas vezes ele eventualmente volta para a velocidade menor

estamos vendo de colocar mais "na cara" os atalhos, vlw pela sugestao!
