### ISSUE TITLE
Legendas em videos 

### ISSUE THREAD

**Issue by MatheusNobrega** [caelum/alura-funcionalidades#10]
Entendo que as aulas possuem uma transcrição completa dos vídeos logo abaixo do player, mas  acredito que seria um diferencial se tivesse legendas nos videos caso eu queira assistir a aula e estiver sem um fone de ouvido ou em um ambiente que eu não posso usa-lo.

**Comment by peas** [comment]
Matheus, a gente considerou bastante a legenda, mas infelizmente precisavamos optar por uma das duas:
- legenda que encaixa dentro do video
- legenda/transcrição com foco em leitura, que pode se adaptar e nao ficar identica ao video, facilitando quem quer apenas ler ou rever

Focamos na segunda, mas a primeira pode vir, a longo prazo, com a melhoria de sistema de transcrição.
