### ISSUE TITLE
Um link direto para o alura lingua

### ISSUE THREAD

**Issue by DuplamenteH** [caelum/alura-funcionalidades#100]
No dashboard da pagina principal ter uma  botão(ou algo do tipo) que entre direto no alura lingua
sem precisar entrar na plataforma do alura lingua fazer login toda essa atividade trabalhosa

**Comment by designernatan** [comment]
oi @DuplamenteH valeu pela sugestao

pode elaborar mais essa? Um link simples no rodapé não resolveria em partes esse trabalho?

**Comment by DuplamenteH** [comment]
Sim, seria suficiente .
