### ISSUE TITLE
Player de vídeo maior

### ISSUE THREAD

**Issue by filipecunha** [caelum/alura-funcionalidades#101]
O tamanho máximo do player de vídeo é 985x503. Em telas com uma grande resolução como do Macbook pro (1650 x 1050), sobra  muita área onde eu poderia estar com o vídeo como o modo teatro do Youtube, que pega largura  total do browser e limita a altura do player de forma que todo o player fique visível na tela, mesmo com uma resolução grande.

No Mac, eu não gosto de ficar com o vídeo maximizado pois tenho que alterar entre vídeo do Alura no browser, editor de código e aplicação rodando no browser.

Toda aula eu tenho que dar uma "hackeada" no player de vídeo rodando no console os scripts :
```
document.querySelector('.task-body-main.container').style.maxWidth = 'initial'
document.querySelector('.container.theater-mode').style.maxWidth = 'initial'
document.querySelector('.task-body-main.container').style.width = '100%'
```
Dessa forma, eu fico com o vídeo grande na minha tela sem estar maximizado.

**Comment by designernatan** [comment]
@filipecunha valeu pela sugestao e pelo código já também!

aumentamos recentemente esses espaços laterais quando o menu fica recolhido, mas ainda tem espaço aqui (!) para melhorar mais

o modo teatro do youtube que pega a janela inteira é uma opção

aproveitando, quão resolvido fica seu problema hoje com o modo Picture in Picture que colocamos esse ano?

abcs!

**Comment by filipecunha** [comment]
@designernatan resolveria bem esse modo se eu conseguisse aumentar p/ tamanho que eu quisesse, mas está limitado à 940x529, que foi o máximo que consegui aumentar.
Não sei se vale outra issue, mas vocês poderiam colocar todas as mensagens do fórum em cada página da aula. Facilitaria demais buscar por problemas e soluções daquela aula apenas rolando a página e lendo as threads.

**Comment by filipecunha** [comment]
@designernatan Fiz algumas aulas hoje usando o pic-n-pic (que até então não tinha usado), e achei bem bom, o único problema é que as setas para avançar/voltar 10s não funcionam. Isso facilita muito quando preciso voltar em um vídeo que já vi para procurar algum conteúdo. 
Resumindo o que achei:

**Pontos positivos:**
- Fica por cima de todas as janelas

**Pontos negativos:**
- Não tem barra de progressão do vídeo
- Não pausa o vídeo quando clica uma vez dentro do vídeo (como o player dentro da janela)
- Não funcionam as setas de avança/voltar 10s
- Quando termina o vídeo de uma aula, ele não vai automaticamente para o próximo.

Esse último faz com que eu não queira usar esse modo, pois tenho mais trabalho de voltar na página da aula e clicar no botão "próxima aula". Vocês poderiam dar uns 5s após o vídeo terminar e ir para a próxima aula, como o Udemy faz.

**Comment by designernatan** [comment]
valeu filipe!

os atalhos nao funcionam pq em teoria vc nao está com a aba da alura ativa, isso acontece no youtube também

a barra de progresso e outros botões dependem do navegador e do sistema operacional, aqui em casa uso windows e opera e fica assim:
![image](https://user-images.githubusercontent.com/5431347/77321349-d6357580-6cf0-11ea-95d4-1871b37400b7.png)

sobre ir automaticamente para o proximo vídeo [tem uma issue aqui](https://github.com/caelum/alura-funcionalidades/issues/46) sobre o tema

valeu mesmo pelos feedbacks! 🙏🏽
