### ISSUE TITLE
Opção "Ver Mais Tarde!"

### ISSUE THREAD

**Issue by bruno-candia** [caelum/alura-funcionalidades#102]
Olá, me chamo Bruno Costa e sou fascinado pelo trabalho da Alura.

Bom, sou uma pessoa que acompanha muito as notificações da pagina da Alura, sempre quando aparece a bolinha vermelha no canto do ícone do sininho eu clico imediatamente. Mas como a quantidade de conteúdo é muito grande (e está crescendo cada vez mais), quando eu me interesso por um material que apareceu nas notificações, as vezes penso em ver somente mais tarde, por talvez estar fazendo já um outro curso e não quero parar, quando as notificações atualizam, eu não sei mais onde está o curso que eu tinha gostado, isso por conta da quantidade de conteúdo que possui na plataforma.

Então pensei, e se fosse possível ter um check-box ou algo do tipo para que eu possa "Ver mais tarde". Dessa forma, caso apareça algum conteúdo que me interesse, mas no momento não estou disponível para acompanhar, eu simplesmente marco "Ver mais tarde" e ele fica salvo na minha playlist dos conteúdos que gostaria de ver outra hora.

Espero que tenha ajudado de alguma forma!

**Comment by designernatan** [comment]
Oi @bruno-candia valeu pela sugestão e pela ajuda!

Hoje não temos algo assim pensado, mas faz bastante sentido!

Atualmente eu uso uma ferramenta chamada [Get Pocket](https://getpocket.com), com ela salvo links e vídeos para ver em outro momento. O problema que tenho com ela é que acabo nunca lendo o que salvo. ¯\_(ツ)_/¯

Abcs!

**Comment by designernatan** [comment]
@bruno-candia um colega me lembrou de algo: se o conteúdo que você quer ver depois for um **curso**, você pode favoritá-lo para iniciar em um segundo momento

uma vez na página do curso, basta clicar em 'outras ações' -> 'favoritar'

e onde ficam os favoritos? Em uma seção específica para eles lá no menu 'cursos' -> 'meus cursos'
