### ISSUE TITLE
Notificação/Metas semanais

### ISSUE THREAD

**Issue by DevCapu** [caelum/alura-funcionalidades#103]
Seria interessante se tivesse um lembrete de estudos, exemplo: desejo estudar 3 vezes por semana, das 14:30 as 15:00, assim ele adicionasse na sua agenda do google, para que o aluno não esquecesse de estudar ou se preparasse para isso.
![add](https://user-images.githubusercontent.com/19232807/77363077-d05f8480-6d30-11ea-9a8e-927ce7ec5f4d.png)

O exemplo acima é da plataforma Coursera

**Comment by designernatan** [comment]
oi @DevCapu valeu pela sugestao!
