### ISSUE TITLE
Download das aulas no site

### ISSUE THREAD

**Issue by DomingosPeres** [caelum/alura-funcionalidades#104]
Gostaria de fazer o download das aulas pelo site para assistir offline.

Motivo, só tenho internet móvel em casa.

Já faço isso pelo celular, mas a tela dele é muito pequena.

Grato.

**Comment by felipetorres** [comment]
Oi @DomingosPeres, não temos planos para suportar o download das aulas pelo site, justamente por termos os aplicativos. Será que o Chromecast/AirPlay não ajudariam no seu caso? Como os apps conversam bem com esses aparelhos, será que não vale a tentativa?

**Comment by macregio** [comment]
Olá, acho que uma opção interessante seria deixar a versão em "PDF" dos cursos. Juntar todo o curso em um documento único pode ser interessante para aqueles que queiram consultar o material após o término do curso.
