### ISSUE TITLE
Menu [Meus Planos de Estudo] - não tem a opção de excluir

### ISSUE THREAD

**Issue by alanbritodossantos** [caelum/alura-funcionalidades#105]
No menu "Meus Planos de Estudo", não tem a opção de excluir(plano de estudo) na hipótese do aluno criar mais de um plano de estudo como foi o meu caso.

**Comment by designernatan** [comment]
@alanbritodossantos valeu pela sugestao! Estamos considerando implementar isso no futuro

O que você poderia fazer por hora é renomear e colocar algo como 'plano futuro'

lembrando que não há limite de quantidade de PDEs

---

outro ponto, se não quer deixar o Plano de Estudos público, você pode deixá-lo privado indo em 'Editar', na página do plano e mudando o switch logo no começo do form

**Comment by designernatan** [comment]
Entrou ontem a opção de deletar um Plano de Estudos!

1. Clicar no Plano que vai ser exterminado
2. Editar (fica em cima na direita)
3. Agora lá em baixo perto do Salvar -> 'Deletar Plano'
4. Ler o aviso sobre o que acontece se deletar e confirmar
---

![meme de um cara suando frio com uma toalhinha no rosto com dois botoes vermelhos um é deletar plano de estudos e outro é não deletar](https://user-images.githubusercontent.com/5431347/83020201-8891fd80-9ffe-11ea-9c3a-dda2b0b65332.png)
