### ISSUE TITLE
Revisar os pré-requisitos de todos os cursos

### ISSUE THREAD

**Issue by Kulessa** [caelum/alura-funcionalidades#106]
Todos os cursos deveriam ter seus pré-requisitos revistos.
E poderia ser feita uma arvore hierárquica onde selecionando um curso é exibido todos os pré-requisitos em cadeia e também a sugestão do que pode ser feito depois.
E nas formações os cursos desativados não deveriam aparecer.

**Comment by designernatan** [comment]
@Kulessa quais cursos que você acha que estão mais críticos com relação aos pré-requisitos? Só para eu conseguir passar para o time de conteúdo com mais precisão

essa da árvore é uma boa mesmo, meio que uma skilltree só que focada nos cursos, valeu pela sugestão!

**Comment by Kulessa** [comment]
Na minha opinião todos, mas os meus maiores interesses são de Programação,
Front-end e Mobile.
Mas sugiro que vejam primeiro os cursos que estão sem nenhum pré-requisito
, indiferente da categoria
Creio que estes vocês tem como fazer uma busca pelo cadastro

Acho que esta "Skilltree" poderia começar com 1 nível
(pré-requisito/sugestão futura) depois incluindo 2 níveis e na sequencia 3
Poderia também inclui os Podcasts, Alura Live, e outros canais.


Atenciosamente,

Cristian R. Kulessa
Kultech Sistemas Informatizados Ltda-ME
email: kulessa@gmail.com
gtalk: kulessa@gmail.com
skype: cristian.kulessa
cel: +55 11 99601-3203
cel: +55 11 99018-5211
https://br.linkedin.com/in/cristian-richard-kulessa
plus.google.com/+CristianRichardKulessa


Em sex., 27 de mar. de 2020 às 11:31, Natan Souza <notifications@github.com>
escreveu:

**Comment by designernatan** [comment]
@Kulessa @132roldan srs obrigado pelas informações!

passei para o time de conteúdo para dar uma conferida nos pré-reqs
