### ISSUE TITLE
Marcar curso como concluído pelo aplicativo

### ISSUE THREAD

**Issue by davialexandre** [caelum/alura-funcionalidades#107]
Olá,

Na maior parte do tempo, costumo fazer os cursos pelo aplicativo. Contudo, nele não há a opção de concluir um curso. Mesmo atingindo 100%, não há opção de dar uma nota ou feedback para ao curso e marca-lo como concluído. Para isso sempre preciso acessar o site, o que é um pouco chato. Seria bem útil se fosse possível fazer isso pelo próprío aplicativo.

**Comment by taisbatuira** [comment]
Olá @davialexandre , sou Tais do time de desenvolvimento dos apps da Alura. 
Realmente, por enquanto não é possível finalizar os cursos pelo app. Essa feature está na lista de tarefas futuras, mas ainda não temos previsão de implementação. Estamos registrando sua solicitação!! 
Muito obrigada!!
