### ISSUE TITLE
Terminal Online com exercícios.

### ISSUE THREAD

**Issue by MichaeL-Ruppelt** [caelum/alura-funcionalidades#108]
Alguns sites tem um terminal onde você pode "rodar" o seu código (com suporte a diversas linguagens), e realizar exercícios/desafios onde  é necessário criar ou corrigir um código de acordo com um contexto, essa função junto com as aulas podem ser uma ferramente poderosa de aprendizado associada aos vídeos.

Referencia do site codewars: https://www.codewars.com/

**Comment by peas** [comment]
oi Michael! Fizemos uma epoca com java um terminal do repl/it transparente. no final a adoção foi muito pequena e causava barreira pra depois um setup e uso da linguagem. ai qualquer coisa com sistema web e setup mais complexo, por mais que existam opcoes, deixa o processo mais complicado do que simples

no momento nao vamos recoloca-lo, mas ele esta sempre na nossa lista pra ficar atento
