### ISSUE TITLE
Criar alguma utilização para os pontos

### ISSUE THREAD

**Issue by pedrowickert123** [caelum/alura-funcionalidades#109]
Não sei o que posso fazer com os pontos adquiridos. Legal seria se tivesse alguma funcionalidade como resgate de prêmios, descontos na renovação do curso e assim vai. Isso incentiva cada vez mais o aluno a realizar qualquer tipo de ação que gere pontos dentro da plataforma.

**Comment by designernatan** [comment]
@pedrowickert123 valeu pela sugestao, hoje os pontos te fazem subir [num ranking público](https://cursos.alura.com.br/user/natan-souza/rank/full) 

acho **bem** bacana algo assim, até parceria com smiles/multiplus da vida, infelizmente também pensei em algumas pedras nesse caminho:
- flood no fórum
- "fazer" cursos
- marcar o próprio reply no fórum como solução

---

precisamos pensar em todos os casos como os supracitados antes de fazer algo grande assim, também bolarmos uma forma de evitar esse tipo de comportamento, talvez até um departamento anti-fraude pois começaria a envolver recompensas financeiras, exatamente como smiles/multiplus

repensar toda a parte de gamification é algo que está no nosso radar, mas nada no curto/médio prazo

acreditamos fortemente na cooperação espontânea focada no aprendizado e troca de conhecimento que a Alura oferece hoje, por hora parece ser um caminho interessante :)
