### ISSUE TITLE
Resetar progresso nos cursos e formações

### ISSUE THREAD

**Issue by LucasSchiavo** [caelum/alura-funcionalidades#11]
Gostaria de ver a opção de resetar o progresso nos cursos. 

Eu havia parado de estudar na Alura depois do fim da assinatura há algum tempo. Voltei recentemente e gostaria de começar de novo alguns cursos que fiz lá atrás.

Ai vocês podem dizer : 'Ah, mas é só refazer os cursos, não precisa zerar tudo'.

Sim, mas a ideia é poder gravar o progresso depois, como acontece quando iniciamos um curso do zero. O que não ocorre quando refazemos um curso, o progresso não é salvo e temos que lembrar mentalmente onde paramos.

Resumindo : Minha sugestão é dar a opção para a pessoa poder zerar o progresso dela e refazer tudo.

**Comment by designernatan** [comment]
@LucasSchiavo estamos vendo de nessa situação de refazer um curso já finalizado a alura salvar a última interação, mesmo com o curso já finalizado, sem datas ainda infelizmente

valeu pela sugestão!

**Comment by lucasriechelmann** [comment]
Estou precisando disso, assinei a alura pela segunda vez, e é péssimo querer assistir o mesmo curso novamente e não poder resetar o progresso, não entendo porque não implementam isso, se o código estiver bem estruturado acredito não ser algo muito complicado

**Comment by paulokaome** [comment]
Algum progresso ?

**Comment by designernatan** [comment]
sem novidades, se implementarmos divulgaremos no /explore (sininho)

**Comment by dmitsuo** [comment]
Reforço o interesse nessa funcionalidade, com a ressalva de que a opção para zerar completamente o progresso do curso, ao meu ver, deveria estar disponível apenas caso o aluno ainda não tenha concluído o curso.
