### ISSUE TITLE
Favicon não aparece na página de Plano de Estudos

### ISSUE THREAD

**Issue by luciano-souza** [caelum/alura-funcionalidades#110]
Criei algumas páginas de planos de estudos e reparei que quando estou acessando uma página de um plano de estudos que eu criei o favicon da alura não aparece.

![image](https://user-images.githubusercontent.com/41630391/78028478-7749af00-7335-11ea-9767-4b50f83dd7de.png)

**Comment by designernatan** [comment]
@luciano-souza valeu pelo toque, comemos bola ai

**Comment by luciano-souza** [comment]
Estão ok pra mim.

**Comment by designernatan** [comment]
opa esse foi resolvido
