### ISSUE TITLE
Plano de Estudos

### ISSUE THREAD

**Issue by Moreira89** [caelum/alura-funcionalidades#111]
Movimentar os planos de estudos na tela afim de organizá-los por alguma ordem nossa (provavelmente grau de interesse/relevância) e não ordem da criação do plano de estudos.

**Comment by designernatan** [comment]
valeu pela sugestao @Moreira89 
essa nem estava no radar

pode elaborar um pouco mais? Me conta como você usa os planos de estudos no seu dia +- ?

**Comment by Moreira89** [comment]
@designernatan Bom dia!
Desculpe a demora.

Então, eu criei alguns planos de estudos baseado no que tenho interesse em estudar, alguns eu até gostaria de excluir (ia sugerir isso também, mas vi que já sugeriram...), e gostaria de poder organizar os planos de estudos por ordem interesse, de acordo com o que estou me focando no momento.

**Comment by designernatan** [comment]
excelente @Moreira89 valeu pela ajuda!
