### ISSUE TITLE
Copiar URL do vídeo no horário atual

### ISSUE THREAD

**Issue by thdesous** [caelum/alura-funcionalidades#112]
Olá, deixo aqui uma sugestão para adicionar a seguinte funcionalidade no player de vídeo:

- Copiar URL do vídeo no horário atual

Com essa funcionalidade, fica mais prático responder ou criar perguntas no fórum, adicionando a URL do vídeo do horário, estilo youtube. Não sei se no campos de respostas é possível inserir um vídeo para que seja executado, mas fica também aí mais uma dica, não se já é possível mas.

- Colocar opção de adicionar vídeo e executar o vídeo na resposta ou pergunta do fórum.

**Comment by designernatan** [comment]
valeu pela sugestao @thdesous !

antigamente o youtube era embedado direto lá no fórum só de colocar o link lá, fazer isso com as aulas acredito ser mais complexo

vamos levar em consideração isso quando pegarmos para melhorar a tela de aula

valeu!
