### ISSUE TITLE
Criar seção com "ferramentas utilizadas" e "sequência" na página inicial do curso

### ISSUE THREAD

**Issue by lucasmenezes** [caelum/alura-funcionalidades#113]
Alguns cursos necessitam de ferramentas instaladas (às vezes pagas), por isso seria útil já constar na página inicial em uma seção "ferramentas utilizadas". Também na página inicial do curso, assim como a seção "pré-requisitos", sugiro uma seção "sequência", quando o curso for dividido em partes. 

Exemplo: o curso Spring Boot - parte 1 possuiria em sua página inicial os pré-requisitos Java e JPA; ferramentas utilizadas Eclipse e Postman; e sequência Spring Boot - parte 2

**Comment by designernatan** [comment]
valeu pela sugestoes @lucasmenezes 

com relação as ferramentas necessárias para realização dos cursos, em via de regra elas constam nas atividades do curso, mesmo em cursos como os de photoshop ou 3dMax que já são de senso comum que são ferramentas pagas

do ponto sobre as sequencias, a seção "formações com esse curso" já suprem esse ponto que você levantou em partes, o curso de spring boot por exemplo não está em nenhuma formação mas possui uma segunda parte

de novo, valeu pelas sugestoes!
