### ISSUE TITLE
Pesquisa de Artigos

### ISSUE THREAD

**Issue by Moreira89** [caelum/alura-funcionalidades#114]
Boa tarde!

Hoje ao buscar por "ECMASCRIPT6" encontrei alguns artigos relacionados a Formação Front-End (como [Herança em JavaScript,](https://www.alura.com.br/artigos/heranca-em-javascript) por exemplo). Ao acessar a Formação, não encontrei link para este artigo e notei que não há nenhum link direto para [Artigos Alura](https://www.alura.com.br/artigos) nem a possibilidade de incluirmos artigos quando criamos nossos planos de estudos.

Minha sugestão seria incluir um link direto para a página de Artigos, talvez dentro de "Cursos' e possibilitar incluir Artigos no Plano de Estudos.

**Comment by designernatan** [comment]
valeu pela sugestao @Moreira89 !

vc consegue incluir o artigo em um Plano de Estudos colando sua URL na caixa de busca lá dentro:
![](https://user-images.githubusercontent.com/5431347/78587498-686e6b00-7813-11ea-96ec-86dc3f92ee20.png)

sobre o post nao estar na formacao, acredito que é para tentar deixá-la mais enxuta para quem está começando, time de conteúdo deve ter pensado dessa maneira

agora pq não tem link dentro da alura para os artigos... não sei! Vou ver com o pessoal a possibilidade :)

abração!

**Comment by Moreira89** [comment]
@designernatan 

Quanto a inclusão dos artigos, não sabia desta opção, mas ainda acho que seria um duplo trabalho, primeiro encontrar o artigo procurando na página de artigos, depois selecionar URL por URL para incluir, muito trabalhoso, nada prático.

Poderia incluir alguma opção na busca, dentro dos planos de estudos, algo como: Cursos, Artigos, Cursos & Artigos, algo do tipo.
