### ISSUE TITLE
DynamoDB

### ISSUE THREAD

**Issue by mauriciovilela** [caelum/alura-funcionalidades#115]
Descreva a funcionalidade que você gostaria que tivesse na plataforma. Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

**Comment by designernatan** [comment]
@mauriciovilela vc diz um curso disso?

no rodapé da alura tem um link de sugestão de curso ([esse link](https://docs.google.com/forms/d/e/1FAIpQLScwKyaSvuFXK9SmMJoLPuYAS2qD_XAAnZPxMZij9qVeflbhBg/viewform)) que aí cai direto para o time de conteúdo, ok?
