### ISSUE TITLE
Tema Escuro para o site

### ISSUE THREAD

**Issue by dougforger** [caelum/alura-funcionalidades#116]
Acho que seria interessante que o site tivesse uma alternativa pra um tema escuro. Eu gosto de estudar a noite e ajudaria bastante não ter a luz branca forte na hora de estudar.

**Comment by designernatan** [comment]
valeu pela sugestao @dougforger !

em qual parte da alura voce sente mais essa necessidade?
(uso dark mode no twitter, notion, opera, windows, feedly... )

se for na tela de aula mesmo, clicando no ícone de espetinho na parte superior direita, dentro da aula, vc consegue ativar o modo noturno, [aqui um tuite da Alura sobre como funciona](https://twitter.com/AluraOnline/status/1240291913443483651)

por hora esse dark mode está só na aula, ideia é expandir caso identifiquemos que a galera tem usado 

ah, e focamos no dark mode na tela de aula justamente pq a galera passa mais tempo ali

**Comment by Lucas3995** [comment]
Olá, @designernatan, como sugerido na issue #214 vim elaborar sobre a necessidade que senti, aqui nessa issue.
Acredito que assim como eu, e talvez o @dougforger, **MUITA** gente pode não saber do modo escuro na tela de aula.
O botão esta num submenu que fica fechado e muita gente acaba nem vendo oque tem ali dentro.
Talvez deixar esse botão em algum lugar sempre visível e mais destacado mude a quantidade de pessoas usando a funcionalidade.

Você falou também sobre a possibilidade de extender o modo escudo para outras areas do site.
Isso seria bem interessante também.
Imagina comigo: Você está lá fazendo o curso e o acaba. Então vai de uma tela escura para uma tela quase que inteira branca e se decidir pesquisar outro curso para fazer vai ficar com aquela branquidão no rosto até achar e iniciar o curso novo.

Para muita gente não vai fazer diferença, mas para quem como eu e o @dougforger que gostamos de estudar a noite melhoraria bastante a experiencia no site.

**Comment by guilherme2017rocha** [comment]
![image](https://user-images.githubusercontent.com/33121251/92602005-eda6f180-f283-11ea-8758-d0d6f37bc4b0.png)
![image](https://user-images.githubusercontent.com/33121251/92601693-85581000-f283-11ea-801e-c59cbea1ffeb.png)
O contraste entre cor de fundo e a cor dos links que ainda não foram clickados deixa um pouco complicado para ler o que está escrito.
P.s.: Não sei qual a cor padrão exatamente do link, então no contrast checker utilizei #0000FF.

**Comment by designernatan** [comment]
@guilherme2017rocha deveria ser mais claro para no mínimo chegar no AA ali mesmo, valeu pelo toque!

**Comment by jair-araujo** [comment]
Acho que assim como o Github hoje nos possibilita ter uma visão geral do site em um tema escuro, seria interessante o Aluno poder ter essa opção disponível nas suas configurações gerais, para ser aplicado ao site como um todo e não só em áreas especificas conforme a escolha do aluno, concordo plenamente com a colocação do @Lucas3995 você está em uma tela escura e depois ter que mudar para uma tela clara, agride muita a visão. Se puderem implementar isso acredito que muitos iriam aderir 
e gostar de ter essa funcionalidade no site. Obrigado pela atenção desde já.

**Comment by kalebzaki4** [comment]
Olá @designernatan! 

A sua ideia de colocar o modo dark no local de estudos foi muito boa, as cores ficaram fantasticas! mas infelizmente também sinto falta de terem cores escuras como o dark theme no dashboard da alura ou no forum, aonde passo mais tempo ajudando a galera! 

Isso poderia ser uma questão de ética também, pois se ficarmos no modo escuro no espaço de aulas, mas o site em si é branco atrapalha na beleza do site!

obrigado!

**Comment by designernatan** [comment]
@kalebzaki4 opa valeu, acho que nao foi minha :P

hoje to indicando o pessoal a usar a extensão "dark reader", que força o dark mode em tudo

descobri recentemente que o opera tem a mesma função, só que nativa:

abcs!

![image](https://user-images.githubusercontent.com/5431347/231207591-6631e6b0-ee20-4962-af85-34675793aa48.png)
