### ISSUE TITLE
Gráfico de desempenho

### ISSUE THREAD

**Issue by mxeliezer** [caelum/alura-funcionalidades#117]
Sabemos que é possível para cada aluno verificar seu desempenho na plataforma, bastando logar-se e clicar em 'perfil e certificados'. Entretanto algumas ferramentas de visualização de dados poderiam ser de grande ajuda na percepção da auto-avaliação do aluno.

Funcionalidade: **Gráfico de desempenho**

Objetivo: facilitar o processo de auto-avaliação do aluno. Para que cada aluno possa perceber melhor se o seu desempenho está de acordo com o que havia planejado.

Características sugeridas (exemplos de informação que poderiam ser de interesse):

1. Quantidade de cursos/mês ou ano; 
2. Quantidade de  horas/aula por mês;
3. Média de pontos mensal.

**Comment by designernatan** [comment]
@mxeliezer valeu pela sugestao!

uma dashboard com informações de desempenho me parece bem bacana mesmo, teria que pensar em como não acabar desestimulando um aluno que estuda esporadicamente pois ele acabaria vendo sempre tudo vazio/quase zerado

gosto do KPI atividades feitas

**Comment by mxeliezer** [comment]
Obrigado pela resposta Natan. Estou de acordo com o que disseste. Não sei qual a porcentagem de alunos 'estuda esporadicamente '. Posso até imaginar que é a minoria. Mas independente disto a solução seria um 'dashboard de desempenho' inteligente, ou sensível, capaz de identificar o grau de desempenho do aluno e de mostrar as ultimas atualizações em destaque, enquanto vai 'esquecendo' aquelas entradas passadas, mais antigas. Assim para o usuário ele traria sempre a sensação de progressão. Não sei se me fez entender quanto a isto. Força à todos os manso Alura.
