### ISSUE TITLE
Botão "proximo vídeo" ou "proxima ativiadade" em tela cheia

### ISSUE THREAD

**Issue by duducolares** [caelum/alura-funcionalidades#118]
Quando estou assitindo aos vídeos em tela cheia no desktop, e o vídeo acaba, preciso minimizar, ir para o próximo vídeo e então maximizar novamente.
Isso é frustrante em cursos cujos vídeos têm curta duração, pois preciso repetir o processo várias vezes.

A funcionalidade que gostaria é de um botão para ir ao próximo vídeo direto no player, ou uma opção de ver os vídeos em sequência sem ter que minimizar e maximizar o player todas as vezes.

**Comment by davialexandre** [comment]
SIM! É extremamente irritante ter que fazer esse processo para cada video. O mesmo problema existe no app para celular e quando fazemos cast para o chromecast

**Comment by designernatan** [comment]
@duducolares valeu pela sugestao!

da ultima vez que vc estudou na alura e teve que fazer esse fluxo, voce ia do Video1 para o Video2 ou ia para os exercicios?

@davialexandre se puder responder tbm por favor :)

**Comment by davialexandre** [comment]
@designernatan na maioria eu assisto todos os vídeos do curso e só faço os exercícios no final

**Comment by duducolares** [comment]
@designernatan no desktop faço na sequência que o curso entrega

Mas em muitos cursos há uma sequência de vários vídeos curtos para só então haver um exercício, nas áreas de mkt, ux por exemplo
em vídeos de 3 a 5 minutos, uma vez que assistimos na velocidade 2x ou superior, o intervalo entre o proceso de minimizar/maximizar é bem curto

**Comment by welingtondsv** [comment]
Faço a mesma coisa que o davi, assisto todos os videos e depois faço os exercios, só que as vezes tem curso que estou fazendo só para cosolidar o conhecimento no assunto, e acho que seria legal mesmo ele passar igual uma playlist de video
