### ISSUE TITLE
Quebra de linha

### ISSUE THREAD

**Issue by thdesous** [caelum/alura-funcionalidades#119]
Olá, não sei se é uma característica ou falha do editor de texto da plataforma, mas já tentei de diversas formas quebrar a linha com `<br>`, `<p>`, mas sem sucesso. 

Isso ajudaria muito na organização do texto, nas explicações. Não sei como fazer isso, mas seria legal que ao dar um "enter" como aqui no github, ao publicar ele respeitasse. 

Mas, caso tenha alguma forma de faze isso, talvez seja interessante, colocar uma guia de como usar o editor.

**Comment by designernatan** [comment]
oi @thdesous 

a gente quer melhorar esse editor aí num futuro de médio prazo, dar uma cara mais amigável para quem não é de programação por ex, algo mais proximo de um editor de texto de algum CSM normal

pra dar esse 'br' que vc fala lá no fórum ou no PDE, só dar dois enters que resolve, e se for uma lista só usar a marcação normal do markdown

abcs!

**Comment by thdesous** [comment]
Estranho que mesmo eu dando "dois enters", após salvar, eu não consigo visualizar esse espaçamento.

Talvez para quem crie o tópico, a visualização fique quebrada.
![v1](https://user-images.githubusercontent.com/53672557/80832083-643f2e80-8bc2-11ea-985b-cf6268e55605.png)

Editor:
![v2](https://user-images.githubusercontent.com/53672557/80832092-67d2b580-8bc2-11ea-8b59-bfe03fbb471c.png)
