### ISSUE TITLE
Congelamento de assinatura

### ISSUE THREAD

**Issue by felipepiresdejesus** [caelum/alura-funcionalidades#12]
Eu estou em um momento em que não consigo dar foco nos estudos, acho interessante uma funcionalidade em que é possível congelar a assinatura, não sendo possível acessar nenhum conteúdo dos cursos e descongelar novamente.

**Comment by designernatan** [comment]
@felipepiresdejesus sem previsao de algo assim por enquanto

vale mandar email no contato@alura.com.br e explicar a situacao, mas não sei dizer quão possível é :/

**Comment by peas** [comment]
é possivel :). a gente tem feito algumas vezes para um mes de ferias. mas ainda nao planejamos implementar como feature
