### ISSUE TITLE
Deletar planos de estudos individuais

### ISSUE THREAD

**Issue by fernandorolim** [caelum/alura-funcionalidades#120]
Olá. 

Sugiro a capacidade de poder deletar planos de estudos que nós mesmos criamos. 

Seria algo simples: se há algum curso ainda cadastrado neste plano de estudo, exigir que o usuário remova o curso antes de remover o plano de estudos inteiro. 

Abraços.

**Comment by designernatan** [comment]
oi @fernandorolim valeu pela sugestao!

[tem uma issue semelhante a essa aqui](https://github.com/caelum/alura-funcionalidades/issues/105)

interessante sua tratativa de evitar apagar um PDE sem querer, algo como no terminal qnd tentamos apagar uma pasta com conteudo o terminal fala 'opa, tem algo aqui ainda'

abração!

**Comment by designernatan** [comment]
Entrou ontem a opção de deletar um Plano de Estudos!

1. Clicar no Plano que vai ser exterminado
2. Editar (fica em cima na direita)
3. Agora lá em baixo perto do Salvar -> 'Deletar Plano'
4. Ler o aviso sobre o que acontece se deletar e confirmar
---

![meme de um cara suando frio com uma toalhinha no rosto com dois botoes vermelhos um é deletar plano de estudos e outro é não deletar](https://user-images.githubusercontent.com/5431347/83020201-8891fd80-9ffe-11ea-9c3a-dda2b0b65332.png)
