### ISSUE TITLE
Permitir senha no dado do perfil que inicie e termine com espaço.

### ISSUE THREAD

**Issue by henriquehrf** [caelum/alura-funcionalidades#121]
Olá,
Motivo dessa Issue é devido que, ao definir uma senha, sendo ela com espaços no final ou no inicio, o site deve manter o conteúdo que foi informado pelo usuário.

**Exemplo:** Se eu defino uma senha **[ minhaSenha123 ]**, com espaço no inicio e no fim, conforme a imagem abaixo:

![image](https://user-images.githubusercontent.com/16909725/79167340-36ca4680-7db5-11ea-872e-095511868cb1.png)

O site permite salvar com sucesso!
![image](https://user-images.githubusercontent.com/16909725/79166889-1fd72480-7db4-11ea-970b-ae23dc2d981c.png)

Porém, ao fazer login

![image](https://user-images.githubusercontent.com/16909725/79166977-557c0d80-7db4-11ea-8663-aae0bb8b4f4f.png)

A minha senha informada não corresponde, um pouco confuso ao usuário. Analisando o comportamento do site, aparentemente ele remove os espaços, ou aplica um 

> string.Trim()

A única maneira para fazer login, é redefinindo a senha, ou, informar a senha sem espaço, que no caso é **[minhaSenha123]**

Grato pela atenção :)

**Comment by sergiolopes** [comment]
Oi Henrique, realmente a gente faz trim na senha. Antes nao faziamos e tínhamos mais problemas com pessoal se confundindo.

Eu tbm preferiria nao ter o trim e permitir espaços no inicio e fim. Mas na pratica pra gente funcionou melhor dessa forma. Desculpa o inconveniente =)

Mas acho que podemos pelo menos avisar se a pessoa colocar espaço ne. Do jeito que ta, nem avisa. Vou colocar isso pro time de dev. Obrigado
