### ISSUE TITLE
Sugerir alteração nas alternativas de respostas

### ISSUE THREAD

**Issue by thdesous** [caelum/alura-funcionalidades#122]
Olá, gostaria de sugerir uma funcionalidade. 

Hoje nos exercícios só é possível sugerir alterações para correções no texto introdutório das perguntas/exercícios, mas não é possível sugerir uma alteração/correção nas alternativas das respostas.

Restando apenas abrir uma dúvida no fórum para uma eventual correção por parte do suporte da alura.

Existe um fluxo para isso, caso não seja possível implementar essa funcionalidade? Exemplo, abrir uma nova dúvida no fórum?

**Comment by designernatan** [comment]
@thdesous valeu pela sugestao!

nao sei te dizer pq está assim hoje, vou pingar o time de produto a respeito pois faz sentido para mim vc poder mandar sugestao nesse tipo de atividade tbm

abcs
