### ISSUE TITLE
Página dos Cursos (Alunos já logados)

### ISSUE THREAD

**Issue by william-takayama** [caelum/alura-funcionalidades#123]
Quando acessamos uma página de um curso no Desktop, sem estar logado, aparecem informações  que divergem de quando estamos logados, e, consigo entender completamente isso como proporcionar uma experiência de usuário para cada tipo de público-alvo que vocês possuem (alunos e possíveis novos clientes). Porém, acredito que seria interessante colocarem para os alunos já logados, algumas informações extras, como:

- As avaliações de outro alunos
- Cursos relacionados ou complementares

Vou citar um exemplo:
Curso: Jasmine: Testes automatizados em JavaScript
- URL curso sem login: https://www.alura.com.br/curso-online-testes-automatizados-em-javascript-com-jasmine
- URL curso com login: https://cursos.alura.com.br/course/testes-automatizados-em-javascript-com-jasmine

Quando os alunos (já matriculados na Alura) estão pesquisando algum curso para começar, acredito que a opinião de outros alunos é um fator relevante para decidir fazer o curso ou não, pois, apenas olhar a avaliação media do curso é um pouco vazio/cru. 
Também acredito que seria interessante acrescentar cursos relacionados, vou citar o meu caso:
Estava procurando um curso de testes em javascript para complementar o curso de Angular que acabara de realizar, e, procurando na barra de pesquisas encontrei o curso de Protractor que é uma continuação do projeto Alurapic, desenvolvido nos cursos de Angular 1, 2, 3 e 4. Acredito que nesse ponto poderia haver uma melhoria, ou de recomendação do curso, ou mesmo, de acrescentar o curso de Protractor na formação de Angular.

**Comment by designernatan** [comment]
@william-takayama valeu pela sugestao!

os depoimentos acho interessante colocarmos num futuro de médio prazo sim

o 'cursos relacionados' acredito que o breadcrumb da página de curso já supre, em partes, essa necessidade

![image](https://user-images.githubusercontent.com/5431347/80383135-90cd1080-8879-11ea-8fca-64e24d1d8bbd.png)
