### ISSUE TITLE
Adicionar comentários na linha do tempo do video

### ISSUE THREAD

**Issue by silverio-rafael** [caelum/alura-funcionalidades#125]
Gostaria de uma fature de adicionar comentários na linha do tempo dos videos, acho que surgiram discussões melhores das que tem no blog, o professor poderia tirar uma duvida de um aluno e a resposta ficaria gravada na linha do tempo. Essa funcionalidade existe no soundcloud.

**Comment by designernatan** [comment]
@silverio-rafael obrigado pela sugestão

o blog fechamos os comentários há um tempo, o canal mais indicado para discussões entre a comunidade Alura hoje é o fórum

ao criar uma dúvida nova no fórum, indo pela tela de aula, é apresentado algumas dúvidas que podem bater com a atividade específica
