### ISSUE TITLE
Excluir posts do fórum

### ISSUE THREAD

**Issue by KennedyRMenezes** [caelum/alura-funcionalidades#126]
Excluir post do fórum que feito por engano.

**Comment by designernatan** [comment]
@KennedyRMenezes valeu pela sugestao!

em geral é algo mais dos admins do fórum excluírem, mas o mais interessante é que o owner post (quem criou o tópico) dê um auto-reply falando qual era o problema e qual foi a solução, mesmo que tenha sido algo pequeno como falta de internet ou algum typo no código

abcs
