### ISSUE TITLE
Rankeamento de cursos por tempo de duração

### ISSUE THREAD

**Issue by mateustavares48** [caelum/alura-funcionalidades#127]
muitos cursos são rapidos de serem concluidos, mas nao existe um filtro de ver cursos por tempo de duração.Acredito que um filtro com essa funcionalidade seria interressante

**Comment by designernatan** [comment]
@mateustavares48 obrigado pela sugestao!

quando pegarmos a tela de cursos para melhorarmos vamos considerar esse e outros tipos de filtros

abcs
