### ISSUE TITLE
Likes nos posts do Fórum

### ISSUE THREAD

**Issue by KennedyRMenezes** [caelum/alura-funcionalidades#128]
Acabei de encontrar um post no fórum que complementa demais a aula e fiquei com vontade de dar um like pra indicar que aquilo funcionou para mim também. Acho uma boa...

**Comment by designernatan** [comment]
@KennedyRMenezes obrigado pela sugestao! O Paulo sugeriu [algo semelhante aqui](https://github.com/caelum/alura-funcionalidades/issues/2)

comenta lá depois o que você acha?

casa bem com a situação que você passou!
