### ISSUE TITLE
Caderno para cada carreira ou curso.

### ISSUE THREAD

**Issue by leonardolsilva** [caelum/alura-funcionalidades#129]
Acho que ajudaria bastante a se organizar melhor e não misturar as informações no caderno. A ideia de um caderno na vida real é separa-lo por matérias. Acho que nesse caso, se ficasse muito complexo fazer um caderno para cada curso, acho que é válido um caderno para cada formação. Assim se a gente muda a carreira, a gente não tem por exemplo informações de Java em curso de front-end que está preocupado com anotações de outras tecnologia.

**Comment by designernatan** [comment]
oi @leonardolsilva tranquilo?

hoje os cadernos funcionam exatamente assim como voce sugeriu: um caderno **por curso**

deu algum bug do nosso lado que misturo seus cadernos?
