### ISSUE TITLE
Comentar respostas no forum.

### ISSUE THREAD

**Issue by MaykiSantos** [caelum/alura-funcionalidades#13]
Ao utiliza o Fórum dei pela falta da opção de comentar uma resposta ou de marcar o usuário na resposta seguintes, como ocorre na maioria dos fóruns.

A forma atual não permite uma boa interação entre os usuários. o fórum parece mais uma conversa entre aluno e instrutor.

**Comment by designernatan** [comment]
@MaykiSantos excelente!

estamos vendo como melhorar isso (e outras coisas) do fórum de modo geral, também tenho essa sensação que você comentou

**Comment by peas** [comment]
@MaykiSantos voce diz nas mensagens antigas? as que ja esta fechadas?

**Comment by MaykiSantos** [comment]
@peas as que ainda não foram marcadas como solucionado.
Poderia ter um campo para comentar a pergunta que foi feita (para não publicar varias respostas que não são respostas) similar ao forum https://pt.stackoverflow.com/ e a opção de marcar um usuário igual ao @MaykiSantos.
