### ISSUE TITLE
Botão de reiniciar curso

### ISSUE THREAD

**Issue by felipeneves31** [caelum/alura-funcionalidades#130]
Seria interessante um botão onde pudessemos perder todo o progresso do curso e começar do inicio.

**Comment by designernatan** [comment]
valeu pela sugestao @felipeneves31 

tem uma [issue igual a essa aqui](https://github.com/caelum/alura-funcionalidades/issues/11)

vou fechar essa por conta disso, mas em suma estamos vendo de como melhorar a experiência de vocês na hora de refazer um curso

Pode me mandar o link do seu perfil da alura dps? Qual curso **hoje** você precisaria resetar (pergunto mais por pesquisa mesmo)

abcs!

**Comment by felipeneves31** [comment]
Bom dia, meu perfil https://cursos.alura.com.br/user/felipeneves07

O curso que eu gostaria de resetar é o **After Effects: Vídeos comerciais do zero até o render** que por sinal ainda nem terminei, mas como faz tempo que assisti queria resetar pra rever as coisas
