### ISSUE TITLE
GitHub Student Developer Pack

### ISSUE THREAD

**Issue by thiagocardosoba** [caelum/alura-funcionalidades#131]
Promover uma parceria com o GitHub para as assinaturas anuais, garantindo acesso aos estudantes ao GitHub Student Developer Pack.
Com ele diversas ferramentas estariam disponíveis gratuitamente aos estudantes, como as IDE`s da JetBrains.

**Comment by wandersonmaceds** [comment]
Oi @thiagocardosoba acho a ideia muito boa, já houve mais alunos pedindo, já tentamos procurar algo como essa parceria, mas infelizmente, sem muito sucesso. O Student Pack requer que você esteja em uma instituição de ensino formal, igual vale para os benefícios da própria JetBrains, onde você pode submeter a declaração da faculdade e obter acesso de forma educativa aos produtos.

A Adobe também tem seus planos para a educação, que seria bom também ser elegível como parceiro. 

Porém, vou marcar o @peas aqui para que fique sabendo.
