### ISSUE TITLE
Player similar ao Youtube

### ISSUE THREAD

**Issue by regismelo** [caelum/alura-funcionalidades#132]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

**Comment by designernatan** [comment]
oi @regismelo 

poderia elaborar mais?

hoje o controle de velocidade, atalhos e modo picture-in-picture por exemplo são features que tem no youtube e tem na Alura tbm

**Comment by AurelianoJr** [comment]
Acho que um ponto legal (que se encaixaria dentro do que o amigo propôs) seria aparecer a miniatura de exibição do vídeo quando queremos encontrar um trecho na aula e usamos o mouse para ir procurando o minuto correto no vídeo. Hoje, por exemplo, quando quero encontrar um trecho especifico acabo colocando a aula do inicio e na velocidade 3x ou fico testando aleatoriamente até encontrar o momento da aula que preciso.

**Comment by designernatan** [comment]
@AurelianoJr faz sentido sim! Me **parece** bem complicado tecnicamente, mas anotei aqui para investigarmos a viabilidade para num futuro de médio prazo, ok?

**Comment by fabiano-mallmann** [comment]
@designernatan seria interessante também aumentar um pouco o player,ter mais tamanhos além do modo picture-in-picture, como por exemplo o "Teatro" presente no youtube ou twitch. Ao menos em resoluções altas, o player atual fica muito pequeno.

**Comment by designernatan** [comment]
@fabiano-mallmann modo teatro é algo no roadmap, valeu!

uma solução de contorno que eu faço na tela de aula é dar zoom até a mediaquery bater no mobile

**Comment by Maidno** [comment]
olá não sei tem essa funcionalidade no player da Alura , opções de teclas de atalho como L no youtube que avança 10s no video e o J que volta 10s do video , essa teclas de atalho facilita bastante ainda mais quando se estar utilizando dois monitores .

**Comment by designernatan** [comment]
@Maidno fizemos no finalzinho do ano passado

[a issue referente aos atalhos é essa aqui](https://github.com/caelum/alura-funcionalidades/issues/1)
