### ISSUE TITLE
Melhor aproveitamento de espaco na pagina de exercicios

### ISSUE THREAD

**Issue by davialexandre** [caelum/alura-funcionalidades#133]
A coluna onde o conteúdo do exercício eh exibido possui uma largura máxima fixa que nao faz muito sentido em desktops. Nos exercícios com code snippets eh quase sempre impossível ler todo o código sem rolar o texto horizontalmente:

Acredito nao ter motivo para essa largura tao pequena, dado a quantidade enorme de espaço em branco na pagina:

![2020-04-23-214405_1501x793_scrot](https://user-images.githubusercontent.com/388373/80163449-95a97000-85ac-11ea-8156-91c1083aed51.png)

**Comment by designernatan** [comment]
@davialexandre valeu pela sugestao!

aumentamos recentemente esses espaços laterais quando o menu fica recolhido, mas ainda tem espaço aqui (!) para melhorar mais

o texto bate em +- 80 caracteres por convenção, padrão de plataformas como medium, paralelo a um livro para evitar que o usuário faça um movimento muito extenso com o olho da esquerda para a direita, cansando rapidamente a leitura

sobre o code, talvez um botão de copiar código ou um toggle de "quebrar linha" para evitar esse scroll horizontal?

**Comment by davialexandre** [comment]
Acredito que os exercícios, na maior parte do tempo, não tem tanto texto assim a ponto de cansar a leitura, mas entendo a razão por trás. De qualquer forma, se formos comparar com o medium, é interessante notar que, na maioria dos casos, um font-size menor é utilizado para snippets the código:

![2020-04-27-144048_913x1015_scrot](https://user-images.githubusercontent.com/388373/80429035-964e4900-88c1-11ea-8807-a813a0c3065d.png)

Acredito que essa seria uma opção melhor do que copiar código (copiar, abrir um editor, colar e ler lá? Muitos passos) ou quebrar a linha (Se não for feito com muito cuidado, pode prejudicar a legibilidade do código).

Outro ponto que acabei de lembrar é que, as vezes, também temos código dentro das alternativas. Como o espaço lá é ainda mais limitado, a situação fica bem pior. Exemplo:

![2020-04-27-200145_969x387_scrot](https://user-images.githubusercontent.com/388373/80429251-02c94800-88c2-11ea-8564-54db4d6b5b28.png)

E fica pior ainda quando visualizado no app:

![Screenshot_20200427-200611_Alura](https://user-images.githubusercontent.com/388373/80429557-cf3aed80-88c2-11ea-817d-189849bf5eab.jpg)
