### ISSUE TITLE
Remover cursos inacabados e que já existe uma nova versão.

### ISSUE THREAD

**Issue by AurelianoJr** [caelum/alura-funcionalidades#136]
Voltei a assinar a plataforma e fiquei muito feliz em ver que diversos cursos foram atualizados, no entanto, algo que incomoda é o fato de aparecerem os cursos inacabados e que já tem uma nova versão, porém não podem ser removidos da Dashboard e/ou da lista de cursos pausados.
 
Hoje é possível pausar o curso (e ele não aparecer diretamente na Dashboard,) porem acaba "poluindo" essa lista também.

Seria legal **_a opção do aluno optar por "excluir" ou só ocultar da Dash e dos cursos pausados os cursos inacabados e já ultrapassados, tendo em vista que esses acabam ficando só de enfeite_**. 

Deixaria o ambiente mais organizado e permitiria uma visualização mais limpa do que de fato é valido.

**Comment by designernatan** [comment]
@AurelianoJr Valeu pela sugestão e bem vindo de volta!

Tem uma [issue semelhante aqui.](https://github.com/caelum/alura-funcionalidades/issues/31)

A seção de cursos pausados fica bem separada (Cursos em pausa) ali em /meusCursos. Pode elaborar um pouco mais? Só para eu ter certeza se entendi e casa com outros casos.

Abração!

**Comment by AurelianoJr** [comment]
### **MEUS CURSOS**

//Aqui ficam os cursos que estão em andamento. 
### Cursos em andamento

- Curso de Git e Github: Estratégias de ramificação, Conflitos e Pull Requests

- Curso de Deploy no Amazon EC2: Alta disponibilidade e escalabilidade de uma aplicação

...

//Aqui ficam os cursos que por algum motivo precisei pausar por um tempo, mas pretendo retomar
### Cursos em pausa

- Curso de Git: Controle e compartilhe seu código (Este curso tem uma nova versão)

- Curso de Android I: Crie sua App fantástica no Eclipse (Este curso tem uma nova versão)

- Curso de Java 8: Tire proveito dos novos recursos da linguagem

- Curso de Java e JDBC: Trabalhando com um banco de dados (Este curso tem uma nova versão)

...

Explicando melhor, acontece que na minha lista de cursos em pausa as vezes fica poluída com cursos que já tem uma nova versão e que muitas vezes já estou estudando essa nova versão (a exemplo o curso de Git, que já estou cursando uma nova versão, mas a versão antiga ficará no limbo pausada para sempre na lista). 

Eu não tenho pretensão de fazer o curso "Curso de Git: Controle e compartilhe seu código (Este curso tem uma nova versão)" uma vez que já estou fazendo a nova versão do curso, mas não posso remover ou ocultar o antigo da lista de cursos pausados. 

O problema é que esse curso (versão antiga) fica junto com cursos que de fato estão pausados e que pretendo retomar (a exemplo o curso de Java 8).

Não é de fato um problema, mas as vezes tem uma lista com 10 curso pausados, mas tem apenas 2 ou 3 cursos que de fato estão pausados e que eu pretendo retomar, os outros são cursos que já tem uma versão nova e que muitas vezes já comecei ou até terminei essa nova versão. 

Dai visualmente fica difícil de mensurar a quantidade de cursos pausados que tenho de fato para concluir.

É basicamente isso, Prof. Natan :)

**Comment by designernatan** [comment]
@AurelianoJr sensacional, brigadao mesmo pelo textão, ajudou a esclarecer pra mim :)

quando pegarmos essa tela para melhorarmos vamos considerar, bastante, esse ponto sobre os cursos pausados e os 'não quero mais fazer'

abração!
abração!

**Comment by AurelianoJr** [comment]
Valeu pela atenção, Prof. Natan :)
