### ISSUE TITLE
Inserir scroll dentro do menu lateral

### ISSUE THREAD

**Issue by thdesous** [caelum/alura-funcionalidades#137]
Olá, 

Seria legal adicionar um scroll dentro do menu lateral, referência (dentro da `<nav class="task-menu-nav">`). 

As vezes preciso rolar apenas o menu, mas não queria perder o ponto onde estava na página do lado direito, referência (`<div class="task-body__wrapper">`).

**Comment by designernatan** [comment]
valeu pela sugestao @thdesous !

quando pegarmos a tela de aula para melhorarmos vamos considerar esse uso!

**Comment by thdesous** [comment]
🙏 Valeu! Vai ajudar e muito.
