### ISSUE TITLE
Vídeo preencher a janela sem precisar clicar no fullscreen "[  ]"

### ISSUE THREAD

**Issue by menezesmario** [caelum/alura-funcionalidades#138]
Acho que o vídeo poderia preencher o restante da janela ao lado da lista de aulas (recolhida ou aberta). Daria pra dividir a tela pra fazer exercícios em um notebook, o vídeo fica naturalmente maior, sem espaço desnecessário em branco na janela. Um modelo de ambiente que acho bacana é da pluralsight.

**Comment by designernatan** [comment]
@menezesmario valeu pela sugestão e pela referência!

não dá para preencher 100% o tempo todo pois as margens internas ajudam na leitura das transcrições, assim como um livro que tem aqueles "paddings" ali

um modo teatro no menu recolhido é algo que temos no radar quando formos melhorar a tela de aula

---

uma dúvida: o PiP (picture in picture) não resolve para você?

**Comment by joaolce** [comment]
Reabrindo o comentário do @menezesmario , pois tenho uma necessidade similar.

@designernatan, respondendo a sua pergunta mais acima. eu até tentei utilizar o PIP, mas gostaria de que ele ficasse maior. ou seja uso o pip (que é pequeno0, ou fullscreen, que não gosto.

**Comment by designernatan** [comment]
@joaolce valeu pelo reply!

o PiP é redimensionável, descobrimos por uns relatos aqui que ele varia de browser/OS também
