### ISSUE TITLE
Poupup para a tela de código

### ISSUE THREAD

**Issue by thdesous** [caelum/alura-funcionalidades#139]
Olá, gostaria de sugerir uma funcionalidade na tela de tarefas e de transcrição. 

Sei que vocês optam em utilizar um formato de tela para que não canse a vista do usuário, onde ele não precisa movimentar os olhos nas extremidades da pagina, mas veja que nesse caso, para visualizar o código, é impraticável, basicamente o usuário é obrigado a copiar o código para fora da página para conseguir entende-lo. 

![poupup1](https://user-images.githubusercontent.com/53672557/80875591-32e16400-8c91-11ea-8c7d-c9689a54ee4e.png)

Mas, acho que seria interessante adicionar algum tipo de *poup-up* para essa tela de código, não sei se é uma boa pratica em UI/UX, mas acho que deve ser fácil fazer e uma boa opção de melhoria para curto prazo, caso venham alterar o formato um um outro projeto de melhoria.

Vejam o exemplo:
 - Ao clicar em algum icone para visualizar em um poup-up, o usuário poderia até ter a opção de copiar todo o código, entre outros.

![poupup](https://user-images.githubusercontent.com/53672557/80877164-a4b9ad80-8c91-11ea-95c1-dd3c24a005c2.png)

Espero ter ajudado de alguma forma. 

Valeu!

**Comment by designernatan** [comment]
valeu pela sugestao @thdesous !

tem uns cursos que faria sentido ter a quebra de linha habilitada, talvez dar essa opcao para o(a) aluno(a) tb

vamos considerar um popup e o botão de copy quando formos melhorar essa tela!

**Comment by thdesous** [comment]
Maneiro, espero que seja em breve, pq tem muita gente pode não registrar aqui, mas que acha um saco ficar copiando, ainda mais quando faz várias aulas seguidas. 👍
