### ISSUE TITLE
Adicionar marcador no player

### ISSUE THREAD

**Issue by gabrielvf64** [caelum/alura-funcionalidades#14]
Funcionalidade para adicionar um marcador em determinado ponto da aula. 

Seria usado como um lembrete para poder voltar exatamente no ponto em que queremos entender melhor algo, revisar ou voltar depois nessa marcação sem precisar ficar procurando o ponto exato pelo vídeo. 

Ex: "Aqui termina a parte teórica e começa a prática"

**Comment by designernatan** [comment]
@gabrielvf64 estamos estudando algo assim, mto obrigado pela sugestão!
