### ISSUE TITLE
Correção: Funcionalidade - Adicionar ao perfil do linkedin, URL da credencial do linkedin

### ISSUE THREAD

**Issue by thdesous** [caelum/alura-funcionalidades#140]
Olá, tenho uma dúvida e também quero relatar um problema na funcionalidade **Adicionar ao perfil do linkedin**.

**Problema**
A funcionalidade Adicionar ao perfil do linkedin (https://www.linkedin.com/profile/add/), não funciona, ai clicar nela, os dados do certifica não são carregados na página do linkedin, logo o preenchimento tem de ser totalmente manual.

**Dúvida**
No campo **URL da credencial** no linkedin, o correto seria adicionar qual URL do certificado, a opção 1 ou 2?

1. A URL que fica disponível ao clicar em no botão [Certificado](https://cursos.alura.com.br/user/sthiago/course/python-3-intro-orientacao-objetos/certificate) do curso concluído?
https://cursos.alura.com.br/user/sthiago/course/python-3-intro-orientacao-objetos/certificate

2. A URL que fica impressa no certificado
https://cursos.alura.com.br/certificate/7e54630d-1695-4337-b74d-c00f8e6ff53e

![linkedin1](https://user-images.githubusercontent.com/53672557/80895104-89619900-8cb7-11ea-995a-e7199db0f320.png)

_________

**IMPORTANTE** 
Independente de qual URL é a correta, acho que a **2**, seria a mais segura, uma vez que não exiba o **userID** da plataforma. 

Essa informação não está tão clara para os usuários da plataforma, que podem estar, assim como eu estava fazendo, adicionado a URL que expõem o **userId** que utilizamos na plataforma Alura.

Então, acho que vale apenar dar uma atenção para a correção e adicionar uma funcionalidade que evidencie a URL correta, ou até mesmo a correção da **funcionalidade** que deveria estar ativa (desde que entrei na alura, essa funcionalidade nunca funcionou) **Adicionar ao perfil do linkedin**.

____________

Veja que mesmo utilizando a URL "segura" que não exibe o **userId**, ao clicar no botão **Certificado forma**, ele é direcionado para uma URL que exibe o **userId** do usuário utilizado na plataforma.

![certificado1](https://user-images.githubusercontent.com/53672557/80918657-75ac4600-8d3c-11ea-9f2a-1092351ea401.png)

**Comment by designernatan** [comment]
valeu pela feedback e sugestao thiago!

sobre o problema: há uns anos optamos por manter dessa forma pois a API do linkedin eventualmente mudava algo que nos quebrava

sobre a duvida: o ID não exibimos, apenas o userName, que é para ser público, assim como o perfil

o ponto sobre o hash na URL é mais para autenticidade do certificado e não para ocultar o userName

**Comment by thdesous** [comment]
Entendi. 

- Linkedin: Como existe esse problema, e pode não ser uma boa pra vocês, visto que exige sempre manutenção, então acho que o melhor cenário seria remover essa funcionalidade, isso pode acabando desmotivando a usabilidade dos usuários, que muitos vêem o problema e não reportam. E hoje já sabemos que deixar uma falha minima dessa, não é uma boa

- ID: Em relação ao ID entendo, então não o ID gerado que oculta o userId é apenas um default do sistema? 
Acho que em relação a autenticidade, a hash não influenciaria muito, visto que tem bastante informação do aluno, mas entendi. 
Se a missão é default hash "criptografada" pelo sistema, seria interessante remover, e substituí-la apenas para hash que contem o userId. Então quando imprimir o certificado em PDF, a has que seria exibida no rodapé seria a com userId, concodar?

**Comment by sergiolopes** [comment]
A versão com hash que fica na imagem é mais adequada. A versão com userid só vai funcionar quando aluno tem perfil público e aberto (é default mas nem todos tem). A versão hash funciona pra todos. Mas poderíamos deixar mais claro mesmo
