### ISSUE TITLE
Links do hispter ponto tech para abrir numa nova aba. 

### ISSUE THREAD

**Issue by Charles0014** [caelum/alura-funcionalidades#141]
Prezados boa tarde, 
Ouvindo meu Podcast favorito de tecnologia e ao acessar os links os sites não estão abrindo numa nova aba, não nenhum problema critico, porém se estiver escutando o podcast e clicar no link, abre o link na aba atual, interrmpendo o epsodio ouvido. 

Como aprendi na alura, podemos adicionar um target="blank" no link do html para redirecionar e abrir numa nova aba. 

Ps. Esse processo ocorre na maioria das paginas do portal da Alura, talvez seja possivel avaliar.

**Comment by designernatan** [comment]
@Charles0014 valeu pela sugestão!

já tivemos muitas ~~brigas~~ discussões aqui sobre o tema e mudamos de ideia de tempos em tempos

o ponto de abrir na mesma aba é dar o controle na mão do usuário para que caso ele opte (segurando ctrl ou clicando com scroll) ele abra numa aba nova, com um _blank não dá para ele optar abrir na mesma aba

tem estudos que falam sobre abrir em outra aba apenas quando é download, outros que precisa quando for link externo, eterna briga :)

**Comment by Charles0014** [comment]
Agradeço o retorno ágil pessoal .
E uma briga eterna mesmo.
