### ISSUE TITLE
Trailer do Curso

### ISSUE THREAD

**Issue by KennedyRMenezes** [caelum/alura-funcionalidades#142]
Navego bastante pelos curso da Alura e acho que seria interessante um trailer para ver o visual do curso e o que será desenvolvido no processo.

**Comment by designernatan** [comment]
@KennedyRMenezes valeu pela sugestao

hoje pode ser feito clicando em "Ver primeiro vídeo" na página do curso, dessa forma você não se matricula no curso e consegue ver essa prévia
