### ISSUE TITLE
Exportar para Linkedin como curso

### ISSUE THREAD

**Issue by vickgreek** [caelum/alura-funcionalidades#144]
Ao exportar a conclusão do curso para o LinkedIn (clicando no link para adicionar ao perfil) somos direcionados a preencher como um certificado, mas conforme o curso "LinkedIn: Como fazer o seu perfil trabalhar para você" os cursos devem ficar nas "conquistas" e não na parte de certificação.

**Comment by thiagoreboredo** [comment]
Bem colocado.

**Comment by designernatan** [comment]
@vickgreek vamos ver como melhorar isso quando pegarmos essa funcionalidade para melhorar

valeu pela sugestao!
