### ISSUE TITLE
Acelerador de vídeo no browser do PS4

### ISSUE THREAD

**Issue by renanfsvieira** [caelum/alura-funcionalidades#145]
Utilizo a plataforma Alura pelo navegador do playstation 4, porém percebi que a funcionalidade de acelerar o vídeo não funciona nele.

**Comment by designernatan** [comment]
@renanfsvieira por hora sem suporte mesmo em browsers tanto do PS quanto de smart tvs

se tiver muita demanda em um futuro reavaliamos isso, tudo bem?

valeu pela sugestao/dica!
