### ISSUE TITLE
Adicionar a porcentagem dos cursos concluídos

### ISSUE THREAD

**Issue by rfcaio** [caelum/alura-funcionalidades#147]
![sugestao](https://user-images.githubusercontent.com/7752001/82080218-8785d580-96ba-11ea-9951-a5e7d6d54ef1.png)

Que tal adicionar a porcentagem do que foi visto em cada curso concluído?

**Comment by designernatan** [comment]
@rfcaio valeu pela sugestao!

recebemos feedbacks parecidos ora por porcentagem ora por outros parâmetros também

é possível ver a porcentagem hoje do seu perfil clicando no curso e vendo o card de informações do curso na vitrine, mas é um passo a mais sem dúvida
