### ISSUE TITLE
PDF contendo um sumário de tudo que foi visto no curso

### ISSUE THREAD

**Issue by pedroomatoso** [caelum/alura-funcionalidades#148]
Em todos os cursos que assisto eu faço anotações de conceitos que foram passados pelo instrutor e dos comandos que foram ensinados, pra ter isso agrupado em um só lugar e facilitar minha vida futuramente quando eu for fazer a revisão. Seria muito mais trabalhoso pra mim buscar nos arquivos do projeto esses novos comandos quando eu quisesse rever rapidamente tudo que foi passado.
Seria interessante a plataforma disponibilizar um pdf desse tipo ao final do curso.
Alguns exemplos dos meus próprios resumos:
![image](https://user-images.githubusercontent.com/19629970/82104553-c1bc9a80-96ed-11ea-8ff1-b323d5474561.png)
![image](https://user-images.githubusercontent.com/19629970/82104580-d7ca5b00-96ed-11ea-90fd-bc462e5cb431.png)
![image](https://user-images.githubusercontent.com/19629970/82104587-e31d8680-96ed-11ea-8e2a-d1d1f7206dcc.png)

**Comment by designernatan** [comment]
@pedroomatoso muito obrigado pelos prints e pela sugestao!

em geral isso fica junto com o(a) instrutor(a) de fazer esse tipo de material

passei para o time de conteúdo para ficarem cientes, ok?

**Comment by designernatan** [comment]
@pedroomatoso aproveitando, essa ferramenta que vc usa é o evernote ou alguma outra?

lançamos o Caderno há uns meses (fica na tela de aula), chegou a dar uma testada?
