### ISSUE TITLE
Poder deletar um plano de estudos criado por engano.

### ISSUE THREAD

**Issue by jaysonbarretti** [caelum/alura-funcionalidades#149]
O plano de estudos é muito eficiente para nos direcionar aos cursos que devemos seguir de acordo com uma formação específica, mas poderia haver a opção de deletar um plano de estudos, caso tívessemos criado por engano ou mesmo desistido deste plano criado.
Na plataforma encontrei apenas a opção de editar o plano de estudos.

**Comment by brunaruppruela** [comment]
Boa! Essa opção  seria ótima. Estava separando alguns cursos, porém identifiquei que estavam em determinada formação, como consegui adicionar a formação inteira no plano, o que criei não precisava mais.

**Comment by GHardoim** [comment]
Concordo! Tive o mesmo problema. A solução poderia se estender aos cursos também, cancelar um curso que desistiu ou começou sem querer.

**Comment by designernatan** [comment]
oi pessoal,

estamos vendo isso :)
nao consigo passar datas infelizmente

obrigado!

**Comment by designernatan** [comment]
Entrou ontem a opção de deletar um Plano de Estudos!

1. Clicar no Plano que vai ser exterminado
2. Editar (fica em cima na direita)
3. Agora lá em baixo perto do Salvar -> 'Deletar Plano'
4. Ler o aviso sobre o que acontece se deletar e confirmar
---

![meme de um cara suando frio com uma toalhinha no rosto com dois botoes vermelhos um é deletar plano de estudos e outro é não deletar](https://user-images.githubusercontent.com/5431347/83020201-8891fd80-9ffe-11ea-9c3a-dda2b0b65332.png)

**Comment by jaysonbarretti** [comment]
Excelente Natan! Agora poderemos fazer uma ‘limpeza’ nos planos de estudos e nos concentrar nos planos em andamento. 

Show! Parabéns!!!

Abs.

Jayson

**Comment by jaysonbarretti** [comment]
Olá Nathan,

Excelente! Já fiz o teste e deletei um plano que havia criado por engano.

Parabéns em ouvir a voz do cliente ! Sao empresas de sucesso que sempre buscam a melhoria contínua e a satisfaçao dos clientes.

Forte abraço.

Jayson

**Comment by marisnner7** [comment]
Esperando ansiosa quando poder deletar cursos que estão pela metade. 
As vezes vc entra só pra ver um conceito e acaba se inscrevendo. Ai o dashboard fica cheio de cursos em andamento .

**Comment by jaysonbarretti** [comment]
Nada melhor que um dashboard “limpo”. Bora lá Alura nos ajudar :)
