### ISSUE TITLE
Fórum Alura - Upvotes - Guia de tópico eficiente - Notificações do fórum

### ISSUE THREAD

**Issue by joaobispo2077** [caelum/alura-funcionalidades#150]
### Fórum Alura - Experiência de Uso e Sugestões
Olá, tenho três sugestões que surgiram de uma necessidade que senti ao usar a plataforma, estou pensando estas ideias desde que assinei a plataforma, então tenho esses pensamentos um pouco elaborados e acredito que será um grande aprendizado pra mim discutir essas ideias e romper com as que não fazem sentido e ter apoio das que fazem sentido, enfim, vamos lá...

[
**Se quiser ir direto para um resumo nada detalhado dê search (ctrl + F ou command + F) em:
-> Dúvidas semelhantes - Resumo
-> Tópicos eficientes - Resumo
-> Notificação do fórum - Resumo
-> Considerações Finais.**
]

**Caso Geral de Uso**
Gosto de colocar meu conhecimento à prova, de sempre ter a dúvida do quanto eu sei desafiada para que assim eu posso sempre continuar aprendendo mais e mais. E, na plataforma a melhor forma de fazer isso após eu acabar algum curso ou formação não é re-assistindo as aulas ou refazendo os exercícios e sim, na verdade, é tentar responder o máximo de dúvidas que os outros alunos postam no fórum, e quando eu não sei responder, eu busco aprender mais para que consiga responder (ainda estou tentando aplicar isso diariamente).

**Eu mal comecei e notei 3 coisas:**

1. **_Alguns alunos possuem dúvidas semelhantes._**

2. **_Alguns outros alunos não sabem perguntar sobre as coisas que tem dúvida e fica difícil de ajudar._**

3. **_As notificações de quando você é respondido no fórum poderiam ser mais expressivas._**

**Sugestões**
(Com o fluxo do aluno que quer ajudar outros no fórum e do aluno com dúvida, em momentos alternados, eu costumo ser os dois).

**Dúvidas semelhantes**

- **Dúvidas semelhantes - Resumo**
**Questionamento:** 
Existem dúvidas em comum e tenho que abrir um novo tópico para que uma dúvida seja resolvida quando muito provavelmente alguém já pensou nela e outros já perguntaram e responderam sobre, teria como encontrar as dúvidas em comum e reunir elas em algum lugar para que as melhores perguntas e respostas envolvendo essa dúvida comum seja de fácil acesso?
**Sugestão:** 
Implementação de Upvotes dos posts e das respostas nos posts e uma aba que permita filtrar os posts mais votados da semana, do mês e do ano (contemplando categorias, cursos e aulas).

- **Dúvidas semelhantes - Caso**
Buscar dúvida semelhante | Publicar um dúvida/tópico | Buscar solucionar uma dúvida recorrente
Atualmente. ao entrar em qualquer categoria do fórum você se depara com os tópicos que são postados, do mais recente para o mais antigo e, algumas vezes ao ter uma dúvida genuína eu pensei: "Se essa dúvida pode ser comum e a categoria programação tem 2124 páginas (12:10, 16 de Maio de 2020) muito provavelmente essa dúvida que eu tenho, outro alguém já deve ter tido e, deve ter perguntado de forma muito mais eficiente/bem elaborada e ter sido solucionada também de maneira mais elaborada, mas como encontrar?", e tem sim como encontrar! Mas seria um trabalho que demandaria tempo de você procurar e vale muito mais a pena você abrir um novo tópico tentando se expressar da sua forma (que nem sempre possui uma ótima desenvoltura, e que torna mais trabalhoso o processo de ser ajudado). E com isso, _**seria mais interessante ter acesso a resposta na hora que pensei na dúvida**_ (sendo que muitos alunos tem dúvidas semelhantes), assim, tendo acesso ao post com a pergunta e resposta bem elaboradas, e também seria melhor do que esperar aparecer algum moderador ou outro aluno para te responder (diga-se de passagem que a  comunidade de pessoas que tentam ajudar no fórum é incrível, as coisas são respondidas muito rapidamente e somente posts muito abstratos, que, percebo que a galera não tem muita afeição por responder, mas é uma comunidade muito bacana).

![image](https://user-images.githubusercontent.com/43768058/82123175-4fd86580-976e-11ea-8c68-761a56b0ef10.png)

Claramente, não irei ignorar uma _possível_ "alternativa" que poderia servir como solução, como por exemplo, ir na caixa de buscas e procurar por algumas palavras chaves do que você tem dúvida, mas essa "alternativa" apresenta alguns "problemas" se você considerar a forma que os alunos usam a plataforma... Posso exemplificar com o printscreen abaixo, alguns alunos não tem uma noção intuitiva de "SEO da vida", logo, quando tem algum problema/dúvida/motivo para abrir algum tópico, utilizam dos seguintes assuntos: "Não entendi", "ERRO",  "Problema". Dessa forma, notando que existam alunos que não possuam esse senso de "SEO da vida" torna complexo você encontrar exatamente um tipo de problema que sabe que é comum, por uma dificuldade na comunicação das partes. Mas, também reconheço que pelo relacionamento entre os tópicos e as categorias/subcategorias/aulas é possível que você vá atrás e consiga postar dúvidas ou entender a dúvida do aluno e ir atrás de solucionar passando por vários "não entendi" e respondendo os que você entende.
![image](https://user-images.githubusercontent.com/43768058/82123234-a0e85980-976e-11ea-9fc4-7ba9754725a0.png)

Entretanto... um questionamento que tenho sobre a caixa de busca é que se estou na categoria "Programação"... e eu pesquisar os assuntos de tópicos recorrentes entre os alunos, como no prinscreen abaixo: "Erro problema", faz realmente sentido que os resultados sejam de todas categorias? Note que como resultado aparecem tópicos de "Data science" e "Front-end" quando eu estava na categoria "Programação", que, é  o caso do printscreen abaixo. Claro que ,vocês que definem se o escopo está correto ou não, apenas acho que vale instigar o questionamento, pois independente do escopo que você estiver, seja categoria/subcategoria/aula, o resultado da busca contempla todas elas (as categorais). Com isso, se eu entendo muito de front-end e quero buscar algum assunto de tópico genérico de front-end para ver como é alguma dúvida genérica e recorrente, para tentar ajudar, mais uma vez terei que passar pelas páginas até encontrar, não sendo de forma alguma um processo agradável. 

![image](https://user-images.githubusercontent.com/43768058/82123279-e4db5e80-976e-11ea-8b19-1edcaaf85e28.png)

- **Dúvidas semelhantes - Sugestão**

Upvote  | Filtro Upvote | Funcionalidade e visualizador

Acredito que uma funcionalidade de upvote (joinha) em posts e nas respostas dentro do posts do fórum de dúvidas com alguma área que exiba os posts com mais upvotes por semana, mês e ano pode ser interessante para solucionar o problema apresentado anteriormente. 

Pois, conforme os alunos forem utilizando tal funcionalidade, tendem a dar upvotes nos tópicos que lhe foram úteis (dúvidas recorrentes, que, sejam comum a maioria dos alunos), consequentemente, ascenderá essas dúvidas mais populares da semana, mês e ano. De forma, que, em algum ponto, muitos alunos não precisariam abrir tópicos, pois encontrariam facilmente os tópicos que podem sanar as dúvidas que eles tem naquele instante, e acredito que seria muito bom ter sua dúvida solucionada de forma instantânea, simplesmente, encontrando um tópico que contemple-a.
[Existe outra sugestão que relaciona a caixa de busca a isso, mas será explorada mais tarde quando eu estiver discorrendo sobre tópicos eficientes]

E também, utilizando de um caso mais específico, para elucidar melhor: se a Alura faz uma semana postando conteúdos gratuitos sobre Front-end (como ocorreu recentemente com a QuarentenaDev), muitas pessoas vão assinar a plataforma e fazer a carreira Front-end, e ignorando as exceções, as dúvidas comuns que atingem mais alunos, ira fazer com que eles votem nesses tópicos e conforme ascende um tópico recorrente, ele atinge mais alunos, principalmente se haver um filtro com os tópicos que possuem mais Upvotes da semana.

**Tópicos eficientes**
- **Tópicos eficientes - Resumo**
**Questionamento:** 
Em 7 das 8 categorias de curso da Alura, somente 1 possui um mini-guia de postar um tópico com maior eficiência, tendo em vista que muitos tópicos não são bem escritos, assim, dificultando a comunicação entre todos participantes... as outras categorias também poderiam ter seus mini guias, 
 não?
**Sugestão:** 
Pedir para instrutores que possuem grande entendimento de interações eficientes e daquela categoria, criarem um mini guia para elas e deixar esses mini guias fixados.
- **Tópicos eficientes - Caso**
Melhoria na escrita dos tópicos | Comunicação | Post fixado
Muitos alunos tem dificuldade em escrever um tópico que seja claro e atinja muito bem todos os pontos que ele pode ter dúvida em torno daquilo e acabam perguntando 1 ponto e depois vai aparecendo outros tornando o tópico uma conversa, tanto que sempre que eu respondo um tópico, embora eu tente evitar, eu tbm tento explicar o que significa cada termo mais técnico que eu utilizo para dar completa clareza ao aluno com dúvida. 
Atualmente em 7 das 8 categorias de curso da Alura, não possuem um "guia voltado a categoria"/boa prática de como abrir um tópico eficiente (Ao menos não que fique na aba mais importante que é a página daquela categoria).
![image](https://user-images.githubusercontent.com/43768058/82126454-57eed000-9783-11ea-97ea-6e7a3142cbfd.png)

- **Tópicos eficientes - Sugestão**

Post fixado| Post Guia | Instrutores Mestres

Então, a ideia de solução sobre tópicos eficientes não é originalmente minha e sim do professor que leciona os excelentes cursos sobre Performance Web (Sérgio), pois, ele mesmo deve ter pensado algo parecido no passado e criou um mini guia sobre como postar um tópico eficiente na categoria front-end que está fixado:
![image](https://user-images.githubusercontent.com/43768058/82126585-101c7880-9784-11ea-8cfc-fc0653db195c.png)
![image](https://user-images.githubusercontent.com/43768058/82126724-de57e180-9784-11ea-9b5a-13903f8a6cfc.png)

Seria interessante se os instrutores que possuem grande conhecimento de como escrever uma dúvida proveitosa voltada especificamente a cada categoria criassem um tópico desses e fosse deixado fixado esse mini guia em cada uma.

**Notificação do fórum**
- **Notificação do fórum - Resumo**
**Questionamento:** 
Acredito que o escopo adotado para o sininho de notificações sejam novidades da ALURA, mas acredito que seria interessante se notificações de quando você fosse respondido no fórum, também aparecessem no sininho, quero saber o que vocês acham também!
**Sugestão:** 
Implementar no sininho de novidades notificações de quando haver uma nova resposta em algum tópico que você participa do fórum.
- **Notificação do fórum - Caso**
É algo que acredito fazer sentido manter as notificações do fórum em um escopo separado na aba comunidade, mas eu gostaria de saber o que vocês acham dessa ideia mesmo, se ela seria heresia?
![image](https://user-images.githubusercontent.com/43768058/82127049-34c61f80-9787-11ea-88d2-24db26a91aa9.png)

- **Notificação do fórum - Sugestão**
Colocar tanto notificações do fórum na aba comunidade e no sininho de novidades.

**Considerações Finais:**
Entendo que o usuário padrão é o cara que dá 3 cliques e já está assistindo a aula e, utiliza com maior vigor essa função, que, é a principal. Mas, meus objetivos ao apresentar essas ideias é saber se concordam que elas fazem sentido ou se é uma "viagem na maionese minha", creio que isso pode agregar bastante para o meu crescimento como desenvolvedor.

É a primeira Issue que eu abro e sou bem novo na tecnologia... estou no primeiro semestre de ADS, assino a alura a alguns meses, não possuo qualquer experiência profissional na área e o conhecimento que obtenho nessa área sempre vai estar em aprimoramento. Então, caso eu esteja falando grandes bobagens acima, me desculpem, mas eu apenas estou buscando dividir a minha experiência(prática como usuário) e pensamentos para entender melhor as coisas e ver se faz sentido a minha compreensão.

**Comment by wandersonmaceds** [comment]
Oi @joaobispo2077 tudo bem? Wow, mandou bem e deixou bem rica a issue, obrigado pelas ideias. Hoje eu tenho cuidado do fórum e achei bem legal da sua parte sugerir tudo isso. Tentei separar minhas impressões sobre seus pontos do mesmo jeito que fez. 

1. Alguns alunos possuem dúvidas semelhantes.

- Gosto da ideia de agrupamento das perguntas semelhantes, já imaginamos algo parecido, FAQ da aula, mas no geral, aparentemente o recurso não era tão utilizado assim, talvez com algumas melhorias como sugeriu, possamos elaborar algo que faça mais sentido para os dias de hoje.

- UpVote já foi sugerido, estou agrupando as ideias para que possamos fazer uma melhoria bem pensada no fórum. Acredito que esteja nos planos para o futuro. Gostei das suas sugestões associadas a isso. Faz sentido para mim, não sei o quanto dos alunos usariam.

- A busca no fórum realmente não é da melhores, acredito que possamos melhorar muito nesse campo, justo usando ferramentas que além de filtrar bem os resultados, possa também agrupar pontos semelhantes, hoje, quando preciso buscar algo que imagino já ter resposta, uso o google da seguinte forma: site:forum.alura.com.br + termo da busca, como o fórum é indexado no google, conseguimos fazer esse truque para ter melhores resultados. Preferia que houvesse algo dentro do próprio fórum para isso. 

- Busca contextual, considerando o fórum da categoria poderia ajudar e atrapalhar ao mesmo tempo, um aluno pode postar uma dúvida de programação em data science, nada restringe ele disso e se a solução que estiver no data science for a melhor de todas? Você fica sem ela? (Aqui talvez a moderação ajude, mas o volume é muito grande pro time interno hoje).

2. Alguns outros alunos não sabem perguntar sobre as coisas que tem dúvida e fica difícil de ajudar.

- Topicos eficientes: Temos mais materiais além do post fixado, tem um vídeo alura+ do Paulo falando sobre e tem um post meu no blog dando dicas. Talvez o problema não seja de ter mais materiais explicando isso, mas sim a visibilidade deles. Aqui podemos reforçar algumas coisas
  - Ter esse material logo no onboarding do aluno.
  - Deixar sugestões direto no formulário da dúvida.
  - Enviar dicas por e-mail 
  - Os moderadores no momento de responder, dar dicas também.

3. As notificações de quando você é respondido no fórum poderiam ser mais expressivas.

- Sininho: Concordo, mas acredito que no sino seja o suficiente, até mesmo para não confundir e passar a ideia de que tem vários lugares com notificações. Divide a atenção, etc.

- Aqui imaginei que fosse falar dos e-mails que recebe ou mesmo da funcionalidade de receber por e-mail dúvidas dos cursos que você fez, você pode habilitar isso indo na página onde edita dados do seu perfil e clicar no checkbox abaixo da sua foto. (está em beta ainda)

Ainda tem muitas outras coisas que seriam legais de serem feitas no fórum. Por favor, se tiver mais ideias, pode ir comentando.

**Comment by joaobispo2077** [comment]
Opa beleza @wandersonmaceds ? fiquei muito contente por você ter comentado os meus pontos, muito obrigado! E suas impressões me deram alguns insights, vou comentá-los utilizando a mesma estrutura inicial.

1. Alguns alunos possuem dúvidas semelhantes.

- Curti demais saber que vocês já estejam pensando em formas eficientes de agrupar dúvidas semelhantes e também cogitam a função de UpVote; não tenho noção de quanto tempo anos/meses uma funcionalidade nova sai do papel para a implementação total, mas quando estiver disponível sei que eu utilizarei.

- Valeu mesmo pela dica de busca, por compartilhar como você utiliza o google para encontrar algo no fórum, fiz uns testes e funciona muito bem usar esse recurso.

- Essa questão da busca contextual, realmente, não havia passado pela minha mente essa implicação da situação que você comentou de poder tanto ajudar quanto atrapalhar... Acredito que culmina em um bendito "tradeoff" buscar mudar isso ou não.

2. Alguns outros alunos não sabem perguntar sobre as coisas que tem dúvida e fica difícil de ajudar.

- Outro insight valioso que tu me passou é sobre o guia de tópicos, eu realmente estava pensando que uma possível solução seria expor os "guias de tópicos" em mais lugares, mas como muito bem apontado por você, agora eu acredito também que não seja uma questão de quantidade dos locais que se encontram os guias e sim a qualidade dos lugares em que a informação está disponível. E simplesmente achei excepcional todas coisas que você reforçou, principalmente em apresentar esse material no onboarding do aluno. 

3. As notificações de quando você é respondido no fórum poderiam ser mais expressivas.

- Eu também não havia considerado essa questão da atenção divida em ter a notificação em mais de um local, mas por ela estar mais clara após você ter comentado; creio que o sininho seja ideal.

- Achei super bacana também que você me lembrou de citar a funcionalidade em beta de receber e-mails de dúvidas dos cursos já concluídos, que, se encaixa perfeitamente no meu uso da plataforma (eu acabei esquecendo de comentar). Então, eu tenho achado essa funcionalidade um sucesso na minha forma de utilizar, tento responder o mais rápido possível após receber esses e-mails, rola até uma "competição" por eu saber que outros alunos também vão receber.

Ainda sobre a funcionalidade em beta dos e-mails, tem algum local que eu possa ver como vocês estão planejando aprimora-lá (ideias)? Para eu não dar sugestão repetida, pois tenho algumas ideias em torno dessa funcionalidade, que, ainda colocarei nessa Issue, não estou colocando agora por causa que eu gostaria de tentar elucidar essas ideias com alguns protótipos de tela (farei no decorrer da próxima semana no Figma ou XD) para eu não acabar escrevendo mega textão e ficar maçante haha.

**Comment by wandersonmaceds** [comment]
Você pode criar uma nova issue para as notificações de dúvidas de cursos que fiz por e-mail e referenciar ela aqui para que mais pessoas possam acompanhar. Eu inclusive vou querer sim saber de tudo isso. Eu pessoalmente cuido dessa funcionalidade.
