### ISSUE TITLE
Opção para assistir apenas os videos em sequencia de cada aula.

### ISSUE THREAD

**Issue by jivago** [caelum/alura-funcionalidades#151]
Opção para selecionar assistir apenas os videos em sequencia de cada aula sem a necessidade de clicar em próxima atividade(Reprodução automática)  e excluindo as atividades de exercícios da aula.
Bom para quem prefere assistir todos os videos do curso primeiro e depois assistir novamente fazendo os exemplos da aula e respondendo os exercícios

**Comment by IcaroBorges** [comment]
Sim, por favor.. Já ia sugerir isso. Nossa as vezes eu quero deixar os videos rolando enquanto eu to deitado no sofá ou cama mas não tem condições. Alura, agiliza essa funcionalidade ai kkkk.

**Comment by designernatan** [comment]
@jivago @IcaroBorges valeu pela sugestao e feedbacks, mto bom pra mim como UX qnd vcs contam e dão detalhes como estudam na Alura!

[tem essa issue](https://github.com/caelum/alura-funcionalidades/issues/46) criada sobre esse auto-play, pode comentar lá depois?

inclusive um debate é se esse auto-play funcionaria apenas para vídeos ou exercício tbm, e como fazer isso para que a pessoa não apenas veja os cursos passivamente, mas estude com atenção focada no ensino ali

de qualquer forma quando pegarmos o fluxo de estudo dentro da tela de aula para melhorarmos um auto-play estará na pauta!

**Comment by sahslima** [comment]
@jivago @IcaroBorges 
Oi, pessoal! Tudo bem?

Não sei se já viram, mas finalmente **lançamos a reprodução automática**! Haha

[Este artigo](https://www.alura.com.br/artigos/novidades-de-janeiro-na-alura) explica rapidamente a funcionalidade.

Depois contem pra gente o que acharam. ;)

Um abraço!
