### ISSUE TITLE
Melhorias no player de video

### ISSUE THREAD

**Issue by AndersonTaborga** [caelum/alura-funcionalidades#152]
Eu gosto bastante do conteúdo, mas esse player é tenso. Então vai algumas sugestões.

- Barra **transparente** dificulta saber onde estou no progresso (carinha do **youtube** cairia muito bem).
- Eu uso monitor **2560x1080**, e então divido a tela com o editor ou IDE e mesmo assim o vídeo fica pequeno com espaçamentos enormes entre a margens da direta e da esquerda (não acompanha o navegador, da impressão que está fixo o limite máximo). 
- Qualidade do vídeo não é **Full HD**, as vezes a cabeça chega a doer com as letras dos textos borradas (não parece mas é perceptível).
- O vídeo quando está em 6 min no pause sofre com o retorno do player e precisa dar recarregar.
- Modo teatro suspenso só é bom quando há liberdade para expandir o tamanho a vontade.

Por enquanto é só isso!

**Comment by designernatan** [comment]
@AndersonTaborga 

1. Dei uma olhada aqui (nunca tinha reparado), o Youtube também deixa o progresso transparente. Aumentei a altura da linha:
![image](https://user-images.githubusercontent.com/5431347/82590047-679b5980-9b73-11ea-8e7c-5f6578525fe8.png)

---

2. Também uso um ultrawide aqui em casa (LG, parte de trás e fios brancos). Antes de colocarmos o modo PiP (teatro suspenso) eu dava zoom até chegar no tamanho de celular, aí a interface melhora um pouco isso.

2.1 Hoje a única opção além do PiP é esconder o menu naquele botão no canto superior esquerdo, mas precisamos de um modo teatro mais esperto mesmo!

---

3. Full HD se não me engano era bem custoso pra gente na época, em termos de produção no caso. Há um tempo os cursos saem sempre em HD (720p) pra cima. (Lembrando que no player clicando na engrenagem dá para trocar de SD para HD).

---

4. Depois me manda seu usuário da Alura (pode ser só o nome do perfil)? Preciso de um curso e o vídeo que deu isso também. Vamos dar uma investigada, primeira vez que pegamos algo assim. 

4.1 Aproveitando, possível ser alguma extensão ou mesmo sua máquina? 

---

5. Aqui depende muito do suporte browser+sistema operacional, infelizmente... No meu notebook (Samsung 15", nada demais) quando eu esticava muito o player suspenso sumia, aí tinha que recarregar a página. Já no meu desktop (mesmo tamanho do seu monitor) consigo aumentar sem limites.

Valeu **mesmo** pela lista de sugestões do player!
