### ISSUE TITLE
Organizar atividades do app conforme na web

### ISSUE THREAD

**Issue by liberatov13** [caelum/alura-funcionalidades#153]
Gostaria de sugerir que as atividades (videos e exercícios) dos curso no app fossem organizados da mesma forma que é atualmente na plataforma web.

Atualmente no app, a lista de atividades é organizada primeiro pelos videos, e no fim de cada capítulo os exercícios. Como estudo as vezes pelo app e as vezes pelo notebook, quando acesso no notebook tenho que voltar para fazer os exercícios que seriam feitos só depois no app.

O mesmo serve para as atividades de explicações, que só ficam disponíveis no fim do capítulo através do app.

**Comment by DevCapu** [comment]
@liberatov13, me chamo Felipe Moreno e sou um dos responsáveis pelo app da Alura, ficamos muito agradecidos de receber o seu feedback!!!

Outros alunos já solicitaram a alteração e ela está em nossos planos, mas não temos previsão de quando será implementada pois temos outras atividades prioritárias. Em todo caso, registramos sua solicitação! 

Muito obrigado pelo feedback e bons estudos!
