### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by jessicaguiot** [caelum/alura-funcionalidades#154]
A plataforma ter a opção de dark mode.

**Comment by designernatan** [comment]
valeu pela sugestão @jessicaguiot!

[falei mais sobre ela aqui nessa outra issue](https://github.com/caelum/alura-funcionalidades/issues/116)

depois vc pode dar um salve por lá? Perguntei umas coisas que podem ajudar a gente a priorizar uns pontos
