### ISSUE TITLE
Ver todas os comentários nas opções dos exercícios

### ISSUE THREAD

**Issue by fernandadias** [caelum/alura-funcionalidades#155]
Tem muita coisa bacada nos comentários das tasks.
Então, em geral, eu erro todas pra poder ler... Pq depois que acerto não consigo mais abrir as outras opções.

Mas as vezes eu "acerto querendo errar" rs e ele trava as outras opções. Nisso tenho avançar e voltar para o quiz.

**Comment by designernatan** [comment]
@fernandadias valeu pela sugestao!

Instrutores(as) colocam bastante info útil ali mesmo!
Hoje a gente tem a opção de mostrar essa informação clicando no ícone de olho nas alternativas, isso depois de responder (acertou ou erro):

![](https://i.imgur.com/K2dr3lz.gif)

Adiantaria isso para você nos seus estudos?

**Comment by fernandadias** [comment]
Nossa @designernatan desculpa. Eu NUNCA vi esse ícone antes.
É exatamente isso. Ta resolvido (:

**Comment by designernatan** [comment]
hhaahha desculpa nada, se vc nao viu a interface pecou ai!!

resolvido entao, vitória!
