### ISSUE TITLE
Dark Theme na Plataforma

### ISSUE THREAD

**Issue by HenriquePereiraRosa** [caelum/alura-funcionalidades#156]
Seria ótimo ter tema dark na plaforma e sempre possível orientar os profesores a utilizá-los nas IDEs tbm. Ha um desgaste bem menor aos olhos e gera economia na bateria dos mobiles.

**Comment by jotepauder** [comment]
Seria muito bom mesmo, já tem o modo noturno na interface dos videos. Na plataforma toda seria muito bom o/

**Comment by designernatan** [comment]
valeu pela sugestão galera!

[falei mais sobre ela aqui nessa outra issue](https://github.com/caelum/alura-funcionalidades/issues/116)

depois vcs podem dar um salve por lá? Perguntei umas coisas que podem ajudar a gente a priorizar uns pontos

**Comment by HenriquePereiraRosa** [comment]
Bom como paliativo eeu criei um tema alterando a propriedade das clase com o a extensão Stylus do chrome.

Segue o css:

.task-body__wrapper {
    /* display: -ms-flexbox;
    display: flex; */
    background-color: #131517 !important;
    color: lightgray !important;
}

.task-body-main {
    max-width: 100% !important;
    width: 100% !important;
    margin: 1px 1px 1px 1px !important;
    padding: 1px 1px 1px 1px !important;
    border: 1px !important;
}

.container {
    max-width: 100% !important;
    width: 100% !important;
    margin: 1px 1px 1px 1px !important;
    padding: 1px 3px 1px 3px !important;
    border: 1px !important;
    border-color: #4a4a4a !important;
}

.task-body-header {
    max-width: 100% !important;
    width: 100% !important;
    margin: 1px !important;
    padding: 1px !important;
    border: 1px !important;
    background-color: #343536 !important;
    color: lightgray !important;
}

/*
.task-menu {
    max-width: 250px !important;
    width: 364.5px !important;
}
*/

.task-body-header-title {
    color: white !important;
}

.task-body-header-title-text {
    color: lightgray !important;
}

.formattedText {
    color: gray !important;
}


INSTALAÇÃO:
1) Apos instalar o Stylus , clique em rite stile for 'alura.com.br' .
2) Na janela aberta cole as classes css acima e clique em salvar.

Boas aulas!

**Comment by designernatan** [comment]
@HenriquePereiraRosa valeu pelo CSS e pela dica do stylus!

legal que hoje as aulas já tem um dark mode: só clicar no ícone de espetinho (três pontinhos) lá em cima e ligar o modo noturno

**Comment by HenriquePereiraRosa** [comment]
Curti essa funcionalidade, apenas não desabilitei ainda meu css pq aproveitei para reitar os espaços na lateral do video e em mais alguns lugares. Assim eu consigo ver o video grande e coma barra lateral aberta. 

Então apenas coimplementando se fosse possivel diminur todos os espacos que não sao absolutamente necesspatio para deixcar o video o maior possível seria bem legal no meu ponto de vista.
Muito Obrigado pela atenção Natan!

**Comment by designernatan** [comment]
show henrique!
queremos melhorar essa parte

hoje o modo picture in picture resolve alguns problemas de tela, mas um modo teatro ou algo próximo disso seria o ideal
