### ISSUE TITLE
Exibição de uma maior quantidade de posições nos Rankings

### ISSUE THREAD

**Issue by luiscelestino** [caelum/alura-funcionalidades#157]
A listagem nos Rankings geral e mensal (quando se começa a estudar próximo do final do mês), a posição do aluno permanece inalterada, como ">10.000", por muito tempo. 

Isto dá uma ideia de que a pessoa não está evoluindo e, ao invés de estimular o estudo, acaba desestimulando. A ideia seria mudar este limite para um valor maior: ">50.000" ou ">100.000".

**Comment by designernatan** [comment]
faz sentido @luiscelestino, valeu pela sugestao

precisamos melhorar o ranking/gamefication, por hora sem previsão
