### ISSUE TITLE
Gostaria de uma arvore de especialização.

### ISSUE THREAD

**Issue by caicob** [caelum/alura-funcionalidades#158]
Gostaria de ver uma arvore de especialização, com o aluno no meio da arvore e mostrando como ele pode evoluir para chegar na especialização que ele quer com todos os cursos da alura e seus pre requisitos. Como se fosse uma arvore de skills.

**Comment by designernatan** [comment]
@caicob valeu pela sugestao!

uma skilltree (como alguns jogos tem) me parece interessante

me conta mais sobre a sua dor especificamente? Quais cursos que vc sente falta de algo assim?

**Comment by caicob** [comment]
Pensei em um skilltree geral com todos os cursos, Um centralizador da navegação mostrando todos os caminhos, pre requisitos, horas de dedicação e etc, acho que ficaria mais fácil de entender o que vem antes do que.
Queria entregar algo meio que pronto como exemplo, ate cheguei a fazer um crawler para extrair as informações que julgava necessário mas empaquei na parte dos pre requisitos.

**Comment by designernatan** [comment]
uma pagina que me lembra isso é o [mapa vagas de carreira](https://www.vagas.com.br/mapa-de-carreiras/cargos/desenvolvedor-php/0)

oloko, tá hackeando a gente!!

**Comment by caicob** [comment]
Não hackear, mas fazer um mapeamento de informações como o google faz!
Falando nisso seria mt interessante um curso de crawler na alura!
Sim a ideia seria mais ou menos isso mas a minha ideia era algo meio como grade curricular, mostrando como chegar num ponto pelo melhor caminho. 
![fluxorama](https://user-images.githubusercontent.com/30500958/82926516-b2dbb080-9f55-11ea-9c17-ac7776b6acbe.png)

**Comment by designernatan** [comment]
legal @caicob valeu mesmo pela sugestao e por ter tirado um tempo pra pensar e fazer tudo isso!

se crawler for scrapping (leigo aqui) temos dois hoje:

https://www.alura.com.br/curso-online-web-scraping-data-science-python

https://www.alura.com.br/curso-online-web-scraping-php

talvez ajude com algo

**Comment by caicob** [comment]
@designernatan Algum andamento sobre essa funcionalidade?

**Comment by designernatan** [comment]
@caicob vamos considerar uma skilltree quando formos melhorar essa experiencia de estudo no futuro, ok?

por hora sem previsão
