### ISSUE TITLE
Botão de próximo no player do vídeo

### ISSUE THREAD

**Issue by BrunnaMaiaradaSilva** [caelum/alura-funcionalidades#159]
Minimizar a tela toda vez pra dar next é bem chato

![image](https://user-images.githubusercontent.com/45864414/82766771-06d08300-9df8-11ea-9371-6bf826a53cf6.png)

**Comment by designernatan** [comment]
@BrunnaMaiaradaSilva valeu pela sugestao

tem uma [issue igual a essa aqui](https://github.com/caelum/alura-funcionalidades/issues/118)

vc tbm prefere estudar sem os exercícios? Como é seu fluxo de estudos?

**Comment by BrunnaMaiaradaSilva** [comment]
Eu acho os exercícios interessantes, não quebram meu fluxo de estudo, mas eu assisto os vídeos em 2.5x, então é bem chato ter que minimizar o player e dar next.
