### ISSUE TITLE
Correção Design Responsivo: Minimizar sidebar lateral em tela divida

### ISSUE THREAD

**Issue by thdesous** [caelum/alura-funcionalidades#16]
Olá, gostaria de sugerir uma correção do sidebar lateral (_nome da função: fechar menu_). Ao dividir a tela do navegador pela metade do monitor, não é possível minimizar ou fechar o menu lateral conforme print abaixo.

![sidebar](https://user-images.githubusercontent.com/53672557/70854065-513af480-1e95-11ea-812b-72c67daa5ee0.png)

**Comment by designernatan** [comment]
@thdesous ali no canto inferior direito tem o botão para fazer isso

sinal que devemos estudar mudar ele de lugar :)

**Comment by thdesous** [comment]
Nossa, nem vi ele ali, talvez deixar ele junto ao sidebar na parte superior.
