### ISSUE TITLE
Aprendendo a aprender

### ISSUE THREAD

**Issue by leoaragaop** [caelum/alura-funcionalidades#160]
Eu fiz o curso "Aprendendo a aprender" da Alura e fica a dica usar esse curso (que é realmente muito bom) para incrementar funções na usabilidade da plataforma.

Vou dar alguns exemplos abaixo, porém existem muitas possibilidades que podem ser pensadas melhor.

Exemplos: Notificar os alunos para fazerem revisões periódicas de algumas aulas (o Duolingo faz isso, poderia adaptar algo parecido); 

Disponibilizar alguns mentores que possamos marcar uma hora para conversarmos;

Criar alguma funcionalidade para os alunos dos cursos se conhecerem e compartilharem ideias (além do Fórum que é mais usado pra tirar dúvidas);

Incluir exercícios mais difíceis (sempre são muito simples e fáceis, não é necessário pensar muito para fazê-los) e alguns desafios que seriam revisados pela plataforma (Exemplo para os cursos de programação: CodeAcademy, FreeCodeCamp) ou pelo professor/mentor.

Enfim, pensar um pouco melhor na usabilidade e adaptar ela pra potencializar o aprendizado.

**Comment by designernatan** [comment]
@leoaragaop valeu pelas sugestoes!

Tem esses e outros pontos mesmo sobre como manter esse conhecimento adquirido mirando o longo prazo

uma maneira bacana também é tentar pegar contextos diferentes ajudando outros alunos e alunas no fórum, você pode ir no 'editar perfil' e ativar uma notificação que envolve isso: "Quero receber semanalmente por e-mail dúvidas...". Aí toda semana chega uma lista de dúvidas baseadas nos cursos que você finalizou

---

sobre mentoria fica bem complicado para escalar algo assim, alguns instrutores e instrutoras de cursos muito populares (lógica por ex) tem muitos alunos, muitos acabariam ficando frustrados pela demora na respostas, isso serve para algo parecido com um chat também, além de causarmos ansiedade aqui também

imagina algo como 4mil pessoas tentando falar com um instrutor, mesmo se tivesse +10 para fazer isso complicaria bastante, e estou falando de um único curso

para organizar melhor isso que chegamos no fórum, ainda um pouco afastado dessa experiencia mais "viva" mas com certeza mais bem estruturado, o forum tem funcionado de uma maneira incrível, graças à ajuda dos próprios alunos e em especial da nossa equipe de instrutores e desenvolvedores

---

essa falta de ter algo mais próximo do offline, uma sala com pessoas e esse senso de comunidade é algo que definitivamente queremos atacar, essa troca é comum em aulas presenciais (algo que sinto falta da época que lecionava tbm)

---

sobre os exercícios mesma coisa da mentoria: exercícios dissertativos (que não são mais padrão da Alura) ficavam sem um reply bacana e acabamos optando por ex. multiple-choice, tem vantagens e desvantagens aqui

---

sobre a dificuldade, me fala alguns cursos específicos que você sentiu falta de algo mais desafiador? Aí passo para o time de conteúdo ficar ciente

**Comment by vinnom** [comment]
@designernatan comentando sobre a questão de "exercícios mais desafiadores", eu ratifico o que o @leoaragaop comentou. Em muitos cursos, você tem o famoso "repita o que fiz no vídeo" e eu acho isso muito fraco pro aprendizado. Não que seja inútil, veja bem, mas deixar apenas isso como exercício, não ajuda a fortalecer o aprendizado (não do meu ponto de vista). Muitas vezes, acaba estimulando o *copypasta*, inclusive.
A minha sugestão, inclusive já até mandei pro SAC uma proposta de estrutura de exercícios, é que tenha pelo menos um exercício que estimule o aluno a fazer algo parecido, mas não igual. Me lembro que os cursos iniciais de Java faziam isso: o instrutor passava o conteúdo no vídeo e depois nos exercícios, cobrava esse conteúdo, porém com implementações de classes diferentes. Desse modo, você estimula a aplicação do entendimento do conceito, e não código por código. Eu sei o quanto isso daria de trabalho a mais para o instrutor (também já lecionei), mas bom, faz parte do planejamento de um curso. 

Sobre as notificações de revisão, talvez um bom approach seria o aluno receber notificações semanais, por exemplo, de exercícios (de múltipla escolha mesmo) de cursos que ele já fez. Dependendo de como a pontuação do aluno estiver, o prazo se estende para a cada mês, por exemplo (para não ficar repetitivo demais).

**PS**: tirando os cursos básicos da formação em Java, se não me engano, todos os outros contam com esse "faça o que eu fiz", como exemplo de exercícios que não apresentam desafio.

**PS2**: como faz pra colocar essa linha horizontal aqui? :thinking:  Achei maneiro pra fazer separação e organizar melhor o texto

**Comment by leoaragaop** [comment]
Cara, a respeito dos exercícios

> @leoaragaop valeu pelas sugestoes!
> 
> Tem esses e outros pontos mesmo sobre como manter esse conhecimento adquirido mirando o longo prazo
> 
> uma maneira bacana também é tentar pegar contextos diferentes ajudando outros alunos e alunas no fórum, você pode ir no 'editar perfil' e ativar uma notificação que envolve isso: "Quero receber semanalmente por e-mail dúvidas...". Aí toda semana chega uma lista de dúvidas baseadas nos cursos que você finalizou
> 
> sobre mentoria fica bem complicado para escalar algo assim, alguns instrutores e instrutoras de cursos muito populares (lógica por ex) tem muitos alunos, muitos acabariam ficando frustrados pela demora na respostas, isso serve para algo parecido com um chat também, além de causarmos ansiedade aqui também
> 
> imagina algo como 4mil pessoas tentando falar com um instrutor, mesmo se tivesse +10 para fazer isso complicaria bastante, e estou falando de um único curso
> 
> para organizar melhor isso que chegamos no fórum, ainda um pouco afastado dessa experiencia mais "viva" mas com certeza mais bem estruturado, o forum tem funcionado de uma maneira incrível, graças à ajuda dos próprios alunos e em especial da nossa equipe de instrutores e desenvolvedores
> 
> essa falta de ter algo mais próximo do offline, uma sala com pessoas e esse senso de comunidade é algo que definitivamente queremos atacar, essa troca é comum em aulas presenciais (algo que sinto falta da época que lecionava tbm)
> 
> sobre os exercícios mesma coisa da mentoria: exercícios dissertativos (que não são mais padrão da Alura) ficavam sem um reply bacana e acabamos optando por ex. multiple-choice, tem vantagens e desvantagens aqui
> 
> sobre a dificuldade, me fala alguns cursos específicos que você sentiu falta de algo mais desafiador? Aí passo para o time de conteúdo ficar ciente

**Comment by leoaragaop** [comment]
@designernatan 
Cara, primeiro vou insistir nos planos de revisões, que é um ponto que o curso "aprendendo a aprender" acaba pegando bem firme e que na plataforma da Alura ainda não tem solução.

A respeito dos exercícios, diversas plataformas tem exercícios desafiadores, em que o Aluno precisa pensar para responder, sem contar com um professor corrigindo.
Alguns exemplos CodeAcademy, DataQuest, Brilliant.org

Boa parte dos exercícios dos cursos que eu fiz, são perguntas sobre o que eu acabei de ver vídeo, exatamente da mesma forma do vídeo (não que o curso seja ruim, o conteúdo na maioria das vezes é MUITO bom, porém exercícios são importantes). Não vou falar de nenhum curso em específico, pois realmente foi algo que ocorreu na grande maioria.

Uma coisa que esqueci de comentar, é que a plataforma podia organizar outras formas de aprendizado da alura, como os artigos (nunca acho onde encontrá-los) e podcasts.

**Comment by leoaragaop** [comment]
Mesmo assim, agradeço o retorno!
Vou fechar a issue, pq era mais uma sugestão pro pessoal de ux dar uma olhada no curso "aprendendo a aprender" hahahaha

Mais uma vez, obrigado por me escutar (ou "me ler" hahaha)
