### ISSUE TITLE
Cursos atualizados dentro de uma Formação

### ISSUE THREAD

**Issue by vinnom** [caelum/alura-funcionalidades#161]
Quando um curso é atualizado dentro de uma formação pela qual eu já conclui, esse curso aparece como não realizado. Bom, dependendo da atualização, realmente talvez seja melhor o cursos ser refeito, mas será que sempre é necessário?

![Captura de tela de 2020-05-27 10-53-28](https://user-images.githubusercontent.com/11577103/83029107-a8c6ba00-a008-11ea-83ef-31a6a75b2aeb.png)

Por isso eu proponho um esquema:

- O instrutor deve marcar a atualização atualizado como **necessária** (para quem já tiver feito, refazer) ou **optativa** (não é necessário refazer). Sendo assim, o aluno sabe o que fazer com o conteúdo atualizado;
- O card de formação deve utilizar essa informação para preencher se eu estou com algum curso remanescente ou não. Da forma que tá agora, só dá uma leve irritada ficar com sem 15/15 como no exemplo da imagem.

OBS: a Formação Java da Alura realmente foi concluída por mim e não faltou nenhum curso. Nesse caso, o curso que me motivou escrever essa sugestão, foi o *Java e JPA: Persista seus objetos com a JPA2 e Hibernate*, atualizado em 09/04/2020.

**Comment by designernatan** [comment]
@vinnom valeu pela sugestao!

estamos vendo (fizemos pesquisas com usuários(as)) de melhorar esse fluxo de formações sendo atualizadas, já temos alguns caminhos traçados e deve ter novidades com relação a isso no começo do segundo semestre, mas é um chute de data mesmo
