### ISSUE TITLE
Melhoria no acesso ao cursos de uma formação

### ISSUE THREAD

**Issue by vinnom** [caelum/alura-funcionalidades#162]
Uma coisa interessante, seria o card de formação ter a opção de consultar a ementa toda da formação ou apenas os cursos que faltam a ser concluídos. Ter que ficar rolando a página pra baixo enquanto você tá avançando nos cursos, não é o melhor jeito, apesar daquele *quick jump* (não tenho o certeza de como é chamado aquele guia para acesso rápido para cada etapa do curso) ajudar. 
Outra coisa que talvez entre aqui, seria a possibilidade de marcar os conteúdos extras de cada formação como **já acessado** ou algo assim, para o aluno ser capaz de se organizar melhor nos conteúdos extras que ele já viu/ouviu. No caso, para evitar que "nossa, abri o link, mas nem tinha lido/escutado isso" que a gente faz direto, essa marcação teria que ser ativa, por meio de um checkbox por exemplo.

**Comment by designernatan** [comment]
@vinnom valeu pela sugestao (e por ter criado as outras em outras issues 🙏🏽)

1. a gente precisa pegar essa página da formacao para dar uma estudada de fato, scrollando infinito é bem chatinho mesmo
1.2 estamos preparando um teste que vai ajudar nisso, sem datas por hora
2. do 'marcar como visto' lembro que outro aluno sugeriu algo semelhante em um teste de usabilidade, está vindo uma atualização visual dessa parte mas vamos considerar algo assim no futuro, hoje esse 'check' é automático
