### ISSUE TITLE
Reposiocionamento do botão de "Próxima Atividade" em algumas telas

### ISSUE THREAD

**Issue by vinnom** [caelum/alura-funcionalidades#163]
Em algumas telas, o botão **PRÓXIMA ATIVIDADE** fica posicionado apenas na parte de cima, fazendo com que alguns rolamentos desnecessários ocorram, pois é necessário rolar para cima novamente.
*Exemplo de tela onde o botão de **PRÓXIMA ATIVIDADE** se encontra apenas na parte de cima*

![Captura de tela de 2020-05-27 12-43-06](https://user-images.githubusercontent.com/11577103/83042247-cea78b00-a017-11ea-9e28-8b0af96a6008.png)

Talvez um botão que se posicione na lateral direita da tela (já que a página tem um padding e o texto se localiza sempre no centro ou próximo do centro da tela) e que te acompanho junto com o rolamento ou uma barra lateral que sirva de botão de avanço para a próxima atividade melhore a experiência nesse caso.

EDIT: também evitaria a redundância do botão aparecer em cima e embaixo nas outras telas

**Comment by designernatan** [comment]
@vinnom valeu pela sugestao!

até achei que era bug quando vi seu print, mas isso foi pensado dessa maneira para que o(a) aluno(a) vejam a opinião do(a) instrutor(a)

de qualquer forma temos que melhorar a tela de aula com um todo no fututo

**Comment by vinnom** [comment]
Eu entendo muito o recurso da opinião, me ajudou muito em alguns exercícios que eu tinha que fazer e não tinha entendido bem (nos exercícios dissertativos, principalmente). Mas nesse caso era uma página de texto e aí a opinião do instrutor é só mais um pedaço de texto na tela, não sei se muda tanto ficar "escondido" pelo recurso de 'ver opinião do(a) instrutor(a)". Como você disse que a tela de aula precisa ser melhorada como um todo no futuro, imagino que já haja conversas quanto a esse tópico, de qualquer forma
