### ISSUE TITLE
SUPORTE AOS ALUNOS

### ISSUE THREAD

**Issue by gurugas** [caelum/alura-funcionalidades#164]
Implementar um sistema de esclarecimentos de dúvidas online uma vez por semana. Disponibilizar um serviço de atendimento personalizado com pagamento do serviço por fora da assinatura. Hoje a Alura é uma plataforma de conteúdo e não de educação. Um dúvida do aluno leva mais de 24 horas para ser respondida. Interação com o aluno é zero. Afinal de contas eu entendo que a Alura é uma plataforma de eduacação.

**Comment by sergiolopes** [comment]
Oi @gurugas 

Obrigado pela sugestão. Certamente existe um espaço para algo assim com um suporte mais dedicado e separado. Está no nosso radar de ideias, mas sem planos pro curto prazo ainda.

Abraço
