### ISSUE TITLE
Certificado por formação

### ISSUE THREAD

**Issue by DanielliUrbieta** [caelum/alura-funcionalidades#165]
Olá! Gostaria de sugerir a possibilidade de emissão de certificado por formação. 
Trabalho em uma instituição pública e preciso apresentar certificados com no mínimo 20h para progressão salarial, como, em geral, os cursos ofertados pela Alura possuem carga horária menor, seria bem útil poder gerar um certificado com vários cursos para uma formação. Sei que há a opção de certificado com todos os cursos, mas se pudesse ser apenas por formação seria ainda mais legal.

**Comment by designernatan** [comment]
@DanielliUrbieta 

indo lá no perfil, qnd vc conclui uma formação ele fica lá disponível, [dá uma olhada no meu perfil como exemplo](https://cursos.alura.com.br/user/natan-souza), lá na seção "Formações concluídas"

testa no seu e me dá um reply depois?:

**Comment by caicob** [comment]
@designernatan o meu certificado esta informando que "836 de 837 atividades concluídas.", como descobrir qual atividade esta faltando!

**Comment by designernatan** [comment]
@caicob manda um email no contato@alura.com.br ? Lá eles vão conseguir te direcionar melhor 

sua dúvida é uma boa dica tbm para pensarmos qnd situações assim, estamos vendo algo para o segundo semestre +-

**Comment by DanielliUrbieta** [comment]
Consegui ver aqui, obrigada!
