### ISSUE TITLE
Próximo vídeo automáticamente

### ISSUE THREAD

**Issue by dalissongabriel** [caelum/alura-funcionalidades#166]
Gostaria que os vídeos fossem reproduzidos automáticamente quando forem sequenciais. Se a atividade 1 e 2 forem vídeos, assim que a atividade 1 terminar, a atividade 2 começa.

Isso pode ser parametrizado no menu lateral. Com por exemplo, um check box dizendo: "Ativar reprodução automática."

Essa funcionalidade seria bacana tanto para o aplicativo como para o desktop.

**Comment by designernatan** [comment]
@dalissongabriel valeu pelas sugestoes!

tem [uma thread parecida aqui](https://github.com/caelum/alura-funcionalidades/issues/46), dps dá uma olhada e comente por lá oq vc acha sobre os pontos que a galera levantou?

**Comment by sahslima** [comment]
@dalissongabriel, tudo bem?

Não sei se já viu, mas finalmente **lançamos a reprodução automática**! Haha

[Este artigo](https://www.alura.com.br/artigos/novidades-de-janeiro-na-alura) explica rapidamente a funcionalidade.

Depois conta pra gente o que achou. ;)

Um abraço!

**Comment by dalissongabriel** [comment]
Gostei do lançamento!
Mas ainda, ao menos para mim,  no momento atual é um pouco estranho de usar. É o oposto do uso comum em outras plataformas de learning. Geralmente temos o autoplay ativado por default e a funcionalidade permite alterar esse comportamento.

Mas já é melhor que nada hahahaha. Para se acostumar é rapidinho.

Para fechar 100%, só falta ir para o mobile. :)
Ai sim!!!

**Comment by sahslima** [comment]
@dalissongabriel o autoplay já está disponível nos apps. 

Caso não esteja aparecendo no seu dispositivo, você consegue dar mais dados do aparelho e sistema operacional que está utilizando, por gentileza? (:

**Comment by dalissongabriel** [comment]
Acabei de encontrar !!
Achei que eles estariam dentro da reprodução do vídeo @~@

 Mas estão no menu de configurações, acessível pelo toque no botão com três pontinhos. Lá tem até outras opções bem bacanas. Que bom que achei, nunca tinha reparado nesse botão hehe.

Nunca mais sofrerei para lavar a louça e assistir as aulas ao mesmo tempo. 

Obrigado @sahslima
