### ISSUE TITLE
Melhorias na exclusão de um plano de estudo

### ISSUE THREAD

**Issue by dalissongabriel** [caelum/alura-funcionalidades#168]
Quando eu estiver excluindo cursos de um plano de estudo,  gostaria que ao excluir o último curso da lista, receber uma sugestão de exclusão do plano de estudo por completo.

Outra sugestão que eu gostaria que fosse implementado, é a possibilidade de excluir um plano de estudo diretamente da tela que lista estes planos de estudo. Atualmente é necessário entrar no plano que se deseja excluir, edita-lo e só então, tenho o distante botão de "Excluir". Por exemplo, eu estou sem mouse, só usando o touch pad enquanto estudo, o que me fez perceber a dificuldade que é ficar dando muitos cliques para remover algo indesejado.

**Comment by designernatan** [comment]
@dalissongabriel valeu pelas sugestoes!

da primeira, vamos dar uma pesquisada!

da segunda, ideia é dificultar a exclusão mesmo
além de ser uma ação destrutiva, outros alunos podem estar seguindo aquele plano específico, podendo impactar diretamente não só o(a) autor(a) como outras pessoas
