### ISSUE TITLE
Formacação antiga não pode ser retirada da Dashboard

### ISSUE THREAD

**Issue by felipebontempo** [caelum/alura-funcionalidades#169]
Acredito que isto seja um bug, Essa formação não tem cursos de REACT, 😅

![msedge_v8ENLTmpvm](https://user-images.githubusercontent.com/26803292/83943513-3f4a6680-a7d3-11ea-9c8f-9fa05c799493.png)

**Comment by felipebontempo** [comment]
O erro ocorre quando eu clico em desativar **exibindo na dashboard**

**Comment by designernatan** [comment]
@felipebontempo opa, valeu pelo toque!

os cursos de react nao aparecerem foi algo pensado no passado, estamos para mudar isso num futuro bem próximo

o que acontece hoje: se aluno nao se matrícula no curso X, e o curso X é desativado, esse curso nunca aparece para ele
o que vai acontecer no futuro: conteúdos removidos continuarão sendo acessados, mas de uma área específica

sobre o bug, passei para o dev team dar uma investigada!
