### ISSUE TITLE
Correção: Alterar atalho fullscreen

### ISSUE THREAD

**Issue by thdesous** [caelum/alura-funcionalidades#17]
Olá, gostaria de sugerir a correção do atalho fullscreen do novo player de vídeo, atualmente ele está configurado com as teclas de atalho `Ctrl + f`, ou seja, não é possível usar essa mesma tecla para localizar algum termo pelo **buscar** do navegador, então tenho que acessar o menu do navegador para localizar algum termo na transcrição. 

**Importante:** Esse problema só ocorre nas telas que possuem o vídeo, já nas telas de atividades e texto o atalho `Ctrl + f` funciona normalmente, abrindo o campo **buscar** do navegador.

**Comment by designernatan** [comment]
@thdesous opa falha nossa

o atalho que colocamos é só o "F", aí qnd dá buscar na página ele acha que é com ele

obrigado pelo toque!

**Comment by designernatan** [comment]
e já entrou o fix ✔

**Comment by peas** [comment]
@designernatan dando close aqui entao!
