### ISSUE TITLE
Planos de estudos: Total de horas

### ISSUE THREAD

**Issue by bvillamarim** [caelum/alura-funcionalidades#170]
Na página do plano de estudo poderia ter a informação do total de horas dos cursos do plano (ao lado do número de cursos, por exemplo). 

Saber o total de horas de um curso me ajuda a fazer uma estimativa de como me organizar. Como nos planos de estudos só aparece o número de cursos incluídos, preciso entrar na página de cada curso do plano que criei e e somar para saber o total.

**Comment by designernatan** [comment]
@bvillamarim valeu pela sugestao!

acho que essa aqui casa com a sua [sobre % de conclusão dos Planos](https://github.com/caelum/alura-funcionalidades/issues/171)

tbm faz sentido ter mais informações direto nos cards, toda essa parte dos Planos melhoraremos no futuro e vamos estudar bem como vocês utilizam essa funcionalidade!
