### ISSUE TITLE
Planos de estudos: % de conclusão

### ISSUE THREAD

**Issue by bvillamarim** [caelum/alura-funcionalidades#171]
Na página individual e na que mostra todos os planos de estudo seria legal ter algum tipo de acompanhamento do quanto eu já completei, da mesma forma que já existe para os cursos.

**Comment by designernatan** [comment]
@bvillamarim valeu pela sugestao (e por ter criado issues separadas 🙏🏽)

sim, faz todo sentido uma visibilidade maior do status do Plano! Vamos considerar isso quando formos melhorar essa parte
