### ISSUE TITLE
Bug: form login

### ISSUE THREAD

**Issue by Flaks009** [caelum/alura-funcionalidades#172]
Olá!
No form-login, se a senha for inválida e tentarmos logar imediatamente a div contendo o alert persiste mesmo após o login ser completado.
![Screenshot from 2020-06-11 12-15-46](https://user-images.githubusercontent.com/42192055/84405047-ff71ed80-abdd-11ea-91e8-355841538534.png)

![Screenshot from 2020-06-11 12-15-08](https://user-images.githubusercontent.com/42192055/84405311-5972b300-abde-11ea-9770-2307ba0c24be.png)

Testei no Chrome: Version 83.0.4103.97 (Official Build) (64-bit) e no Firefox: 77.0.1 (64-bit)
No Ubuntu 18.04.

**Comment by designernatan** [comment]
👮🏼‍♂️ 

passei para o dev team, valeu pelo toque @Flaks009 !

**Comment by Dreadlooks** [comment]
Foi resolvido!
