### ISSUE TITLE
Agrupamento dos resultados da busca

### ISSUE THREAD

**Issue by sylviot** [caelum/alura-funcionalidades#173]
Quando realiza a busca os resultados são listados e paginados, porém para a localização de um item isso se torna um pouco cansativo de ficar verificando, dessa forma poderia ser adicionado a possibilidade de ver apenas os resultados agrupados por exemplo:
* Artigo
* Curso
* Formação
* Fórum
* Podcast
* Outros

Com o agrupamento teríamos os resultados mais refinados, além de localizar com mais facilidade ao realizar uma busca, ideia:

Buscar por "Funcional":

Artigo
> O que é funcional?
> Linguagens funcional?

Curso
> Programação Funcional [Formação] > Primeiros passos com linguagem funcional [Curso]

Formação
> Programação Funcional [Formação]

Fórum
> Como instala aquela linguagem funcional XPTO?

Podcast
> Hipster - Vamos falar sobre Programação Funcional.

--------------------------

**Bug atualmente:**
- Ao realizar uma busca simples por "Funcional", encontramos uma paginação de 23 páginas, sendo que a "..." e a ultima página (23) estão com erro na construção da URI.

Página atual https://cursos.alura.com.br/search/3?query=funcional (precisa já acessa outra página)
Na paginação "... 23" se encontra https://cursos.alura.com.br/search/23?/search/=funcional , onde essa URI está com o **/search/** que causa erro no link.

**Comment by designernatan** [comment]
@sylviot valeu pela sugestao e por ter escrito como você chegou no bug!

a busca está no roadmap futuro uma forte melhoria, da paginação parece ser um bug, passei para o dev team

obrigado novamente!

**Comment by Maidno** [comment]
realmente essa busca refinada seria muito bom , ainda mais quando se está procurando por um termo bem especifico , um exemplo seria a busca do google:

![image](https://user-images.githubusercontent.com/40250606/84932664-03ed4900-b0ab-11ea-983f-2e0a46daeb54.png)

**Comment by sylviot** [comment]
@designernatan vai ser implementado?!?

**Comment by designernatan** [comment]
@sylviot provavelmente sim, sem datas ainda infelizmente...
