### ISSUE TITLE
Excluir planos de estudo

### ISSUE THREAD

**Issue by Borges360** [caelum/alura-funcionalidades#174]
Quando comecei a usar o portal não entendia muito bem como funcionava o plano de estudos, depois que entendi o funcionamento percebi que criei um monte de planos de estudos sem nome.

Não consigo excluir esses planos de estudos.

Seria legal implementar esse recurso para que eu possa organizar melhor os meus planos de estudos.

**Comment by designernatan** [comment]
@Borges360 valeu pela sugestao

tem uma [issue igual a essa aqui](https://github.com/caelum/alura-funcionalidades/issues/149) 

e aqui explico como [deletar um plano de estudos](https://github.com/caelum/alura-funcionalidades/issues/149#issuecomment-634636139)
