### ISSUE TITLE
NAVEGAÇÃO EM TELA CHEIA.

### ISSUE THREAD

**Issue by sergiobsilva2505** [caelum/alura-funcionalidades#175]
Olá amigos, tudo bem?

Acredito que não apenas eu, mas todos nós alunos assistimos aos videos no modo fullscreen e quando o vídeo termina, temos que sair do modo fullscreen, e pressionar o botão "próxima atividade" no topo da página ou abaixo da transcrição do vídeo em modo normal, para podermos   responder aos exercícios e ao chegar no próximo vídeo, colocarmos no modo fullscreen para assistirmos ao vídeo novamente, e quando terminar o vídeo esse mesmo ciclo se repete.

1. Assisti vídeo em modo fullscreen
2. ao final do vídeo clica para voltar ao modo normal
3. clica em próxima atividade
4. responde o exercício
5. clica em próxima atividade
6. responde ao novo exercício (se houver) ou chega ao próximo vídeo
7. e tudo se repete. 

Minha sugestão de funcionalidade:

Ao colocar o vídeo em modo de fullscreen, seja acrescentado nas bordas laterais do vídeo ao centro da tela, setas para avançar e retroceder nas "atividades" (pelo que entendo, os videos são uma atividade) e que desse modo, não seja necessária ficar sempre alternando entre o modo de fullscreen/normal do vídeo para avançarmos na atividade.
Quando digo atividades, incluo também a "opinião do instrutor", que também é muito importante e não pode ficar de fora desse avanço/retrocesso através das setas.

Caso seja necessário um maior esclarecimento, estou a disposição no email (sergio.bezerra@outlook.com)

Desde já agradeço.

At.te

**Comment by designernatan** [comment]
@sergiobsilva2505 valeu pela sugestao e pelo seu tempo em descrever tao bem o problema e a solucao!

tem uma [issue semelhante aqui](https://github.com/caelum/alura-funcionalidades/issues/118), mas anotei seu email aqui para te chamar para uma pesquisa para quando começarmos e melhorar essa tela no futuro
