### ISSUE TITLE
Parceria com Spotify

### ISSUE THREAD

**Issue by thdesous** [caelum/alura-funcionalidades#176]
Não sei se faz sentindo postar aqui essa sugestão, mas seria ótimo termos essa parceria com a Spotify e poder usufruir do plano estudante da Spotify. 

Não seria uma boa @peas ?

**Comment by designernatan** [comment]
tbm nao sei mas vai aqui mesmo hahha!

faz sentido algo assim sim, @thdesous vc ja tentou assinar como estudante lá? O que eles pedem? Certificados talvez?

**Comment by thdesous** [comment]
@designernatan já assinei uma vez, e na época eu enviei meu boletim de notas da faculdade. Acho válido a Alura criar algum plano nesse sentido também, visto que a assinatura normalmente é de 1 ano, e ao meu ver é um EAD. 😁

**Comment by designernatan** [comment]
faz sentido!

vc tentou mandar um certificado ou o link/pdf da sua pagina de perfil ou algo assim?

sei que na adobe já tivemos alunos(as) que conseguiram, mas não é regra infelizmente

**Comment by thdesous** [comment]
Então, dei uma olhada no site. https://www.spotify.com/br/student/ e eles utilizam agora o serviço SheerID, não sei como funciona.

- Como vocês confirmam que eu sou estudante?
- Verificamos a sua matrícula por meio de um serviço terceirizado chamado SheerID. [Saiba mais](https://www.sheerid.com/spotify-student-support/).
