### ISSUE TITLE
Curso de Spring Webflux

### ISSUE THREAD

**Issue by marciojava-prog** [caelum/alura-funcionalidades#177]
Procurei nos cursos da Alura algum conteúdo de Webflux para ajuda com uma nova demanda do trabalho e infelizmente não encontrei nada, fiquei meio chateado por ser uma tecnologia em franco crescimento e não ter nenhum conteúdo nos cursos.

**Comment by designernatan** [comment]
@marciojava-prog canal direto do time de conteúdo (que gerencia o backlog de cursos) é lá no rodapé da alura -> sugira um curso

eles sempre ficam de olho lá para ajudar nesse backlog
