### ISSUE TITLE
Certificados em inglês 

### ISSUE THREAD

**Issue by jaysonbarretti** [caelum/alura-funcionalidades#178]
Ter a possibilidade de emitir o certificados em inglês para poder enviar para recrutadores internacionais. Acredito que seja um botão tradutor. 
Obrigado

**Comment by designernatan** [comment]
@jaysonbarretti valeu pela sugestao!

tem uma [issue semelhante](https://github.com/caelum/alura-funcionalidades/issues/6) aqui

e o [reply do paulo sobre o assunto](https://github.com/caelum/alura-funcionalidades/issues/6#issuecomment-561853046) ainda se mantém para essa questão, ok?

acredito que daria para resolver só jogando no translate (do nosso lado que digo), mas hoje o processo para isso ainda é pingar no contato@alura.com.br
