### ISSUE TITLE
Plano família 

### ISSUE THREAD

**Issue by jaysonbarretti** [caelum/alura-funcionalidades#179]
Ter a possibilidade de criar um plano família para que seja possível emitir certificado para mais de uma pessoa. 
Obrigado

**Comment by sergiolopes** [comment]
Oi jayson, hoje a plataforma não suporta vários usuários numa mesma conta (limitação mesmo). Mas fazemos sim descontos para famílias ou grupos comprarem de uma vez mais de um acesso. Manda um email pro nosso atendimento pedindo informações?
Abraço

**Comment by jaysonbarretti** [comment]
Olá Sérgio, boa tarde!

Muito obrigado pela resposta.  Vou verificar com a equipe de atendimento.

Abraço.

Jayson
