### ISSUE TITLE
Sugestão: Discutir no forum

### ISSUE THREAD

**Issue by thdesous** [caelum/alura-funcionalidades#18]
Olá, gostaria de sugerir uma pequena correção que ao meu ver melhorá a usabilidade do site. 

**Problema 1:** Atualmente ao clica na opção **DISCUTIR NO FORUM**, não é aberto uma nova aba no navegador, ele simplesmente vai para a pagina na mesma aba.
**Solução:**  Seria bem útil ao clicar na opção, ela abrir uma nova aba, uma vez que ao voltar para o vídeo o player não retorna onde paramos.

**Problema 2:** Após **Enviar uma pergunta**, não é carregado a tela inicial daquele tópico ou exercício com a lista de perguntas relacionada aquela atividade. Após registrar é carregado uma pagina default genérica https://cursos.alura.com.br/forum/todos/1
**Solução:** Cara, isso é muito ruim, se eu cadastrar várias perguntas, tenho que dar esse role todo só para voltar, ou ver como ficou a pergunta, além disso isso fica massante devido ao problema anterior que mencionei.  O ideal era voltar para a mesma página inicial dos tópicos relacionados aquela atividade ou vídeo que abri a opção DISCUTIR NO FORUM.

**Comment by designernatan** [comment]
legal @thdesous 

estamos vendo como melhorar isso (e outras coisas) do fórum de modo geral

valeu pelas sugestões!

**Comment by designernatan** [comment]
feito! Time de produto fez as melhorias, marcando como 'done' aqui.
