### ISSUE TITLE
Plano empresa

### ISSUE THREAD

**Issue by sylviot** [caelum/alura-funcionalidades#180]
No plano empresa poderiam ter algumas áreas para os membros:

* Visualização da equipe no plano empresa
* Criação de plano de estudo (com cronograma)
* Progresso por membro dos planos de estudo (estipulado acima)

1) A visualização para o membro poderia ser simples, apenas apresentando uma listagem dos membros participantes do plano empresa.
2/3) O responsável (gestor) do plano empresa poder realizar a criação dos planos de estudo e definir algum cronograma de conclusão dos cursos... teríamos algo semelhante a uma timeline.

**Comment by designernatan** [comment]
@sylviot valeu pelas sugestões!

1 e 2 é algo que queremos atacar no futuro, o 3 somente gestores(as) conseguem ter esse tipo de acesso, decidimos isso para não forçar a pessoa a apenas querer aparecer lá na frente, mas estudar de fato e ajudar a empresa/time no que precisa ser feito

Sobre o 3 ainda, cronograma é algo bem bacana!
