### ISSUE TITLE
Acesso ao caderno sem entrar no curso.

### ISSUE THREAD

**Issue by luigiMinardi** [caelum/alura-funcionalidades#181]
Adicionar uma maneira de visualizar todas as anotações feitas sem precisar entrar diretamente no curso. ([Tipo como o google keep mostra](https://prnt.sc/t25xri)). 

Da pra fazer isso dentro da [parte que vocês já separaram pra mostrar as notas](https://cursos.alura.com.br/course/notes).

Seria útil para uma visualização mais rápida e fácil das notas.

**Comment by designernatan** [comment]
@luigiMinardi valeu pela sugestão, faz todo sentido algo assim!

inclusive talvez algo que permita deixar a anotação pública também, ajudando outros alunos e alunas

o que acha?

**Comment by luigiMinardi** [comment]
@designernatan Acho uma boa, se for feito da mesma forma que os Planos de Estudos, podendo dizer se quer ou não deixar publico, talvez até juntar os 2 tipo poder adicionar uma anotação do seu caderno dentro do Plano de Estudos.
