### ISSUE TITLE
Editar o link e nome dos Passos no Plano de Estudos.

### ISSUE THREAD

**Issue by luigiMinardi** [caelum/alura-funcionalidades#182]
Pode ser que algum link caia ou mude e você queira editar isso, e pode ser que o link que você adicionou veio com um nome de difícil entendimento do que tem no link olhando pelo "nome padrão" e você queira mudar esse nome. 

Ou então caso a feature seja adicionada, que você queira editar o nome de um link que você já adicionou.

Por isso eu acho que a funcionalidade de editar o link e nome dos passos (que não são cursos) é bem util e vai ajudar a deixar o Plano de Estudos bem mais organizado.

**Comment by designernatan** [comment]
@luigiMinardi valeu pela sugestão!

 
sobre mudar o link, faz todo sentido, vamos considerar isso quando melhorarmos a página dos PDEstudos

sobre mudar o nome de cada passo, o receito maior: se um link cair (blog morreu por ex), com nome antigo ou colocando um novo, o conteúdo caiu também, entao nao tem o que fazer

ideal é o(a) autor(a) do PDE sempre ir checando o conteúdo para evitar esse tipo de problema

**Comment by luigiMinardi** [comment]
@designernatan sim sim, o que eu quis dizer é poder mudar tanto o nome quanto o link dos links pra se precisar mudar o link do site que foi linkado pra um arquivo do mesmo que foi upado no Internet Archive ou um outro site com um conteúdo parecido. E a edição dos nomes pra manter tudo mais organizado e legível!
