### ISSUE TITLE
Data de início do curso no certificado, seria mesmo necessário?

### ISSUE THREAD

**Issue by cadukk** [caelum/alura-funcionalidades#183]
Olá pessoal, proponho muito mais uma discussão do que uma melhoria na verdade.

Quando começamos na Alura, alguns equívocos são normais como por exemplo, iniciarmos mais cursos do que o necessário. Além disso, por ser uma plataforma online self study, muitas vezes por N motivos o início de um curso ou formação e seu término ficam entre um timeframe longo, “sujando” o certificado com, por exemplo, 1 ano para uma conclusão se 40 horas e etc.

Tendo em vista que o que importa pro mercado de fato é a conclusão do módulo e sua data término, não seria interessante acabarmos com a data inicial do curso ou formação feito no certificado mantendo só um padrão, tipo:

Finalizou X cursos da formação
XPTO
Com carga horária estimada em 40 horas
Concluído em dd/mm/aaaa.
158 de 158 atividades concluídas.

Desde já agradeço aos que tirarem um pouco de seu tempo para apresentar prós e contras desta sugestão.

**Comment by designernatan** [comment]
@cadukk valeu pela sugestao!

acho que faz sentido, precisamos ver como os alunos e alunas que precisam dessa data de início no certificado

comprovação para faculdades e acordos com gestores(as)

---

quando pegarmos a parte dos certificados para melhorarmos vamos colocar isso em pauta, por hora sem previsão td bem?

**Comment by cadukk** [comment]
> @cadukk valeu pela sugestao!
> 
> 
> 
> acho que faz sentido, precisamos ver como os alunos e alunas que precisam dessa data de início no certificado
> 
> 
> 
> comprovação para faculdades e acordos com gestores(as)
> 
> 
> 
> ---
> 
> 
> 
> quando pegarmos a parte dos certificados para melhorarmos vamos colocar isso em pauta, por hora sem previsão td bem?

Tudo bem Nathan, valeu e obrigado pelo retorno!

**Comment by castrohs** [comment]
acho interessante manter, a data de inicio/fim, acredito que é de responsabilidade do aluno se pegou mais cursos que suportava, tentar conclui-los, afinal que nunca pegou cursos de mais.

**Comment by brunounion** [comment]
Acredito que o interesse dos alunos seja que o certificado seja visto por um recrutador e o mais interessante para isso é somente a data de conclusão do curso e não o seu início.

**Comment by cadukk** [comment]
> acho interessante manter, a data de inicio/fim, acredito que é de responsabilidade do aluno se pegou mais cursos que suportava, tentar conclui-los, afinal que nunca pegou cursos de mais.

Uma visão diferente é sempre uma  boa alternativa de discussão @castrohs mas deve ser sempre mais ampla do que "a responsabilidade é do aluno". A plataforma tem prós e contras e o foco **_é na conclusão dos cursos_** SEMPRE afinal, ninguém inicia um curso para deixar no meio do caminho. Vou te dar um exemplo, eu estava fazendo uma formação Front-End há alguns meses atrás e estava entrando nos dois últimos conteúdos para finalizá-la, quando a Alura fez uma atualização no conteúdo e agora tenho 3 outros itens a + para concluir, a responsabilidade foi minha de agora estender a conclusão da formação em uns 2 meses para concluir o conteúdo extra (que é super válido e útil)? Pense por este ângulo.

Como o @brunounion comentou e foi o foco da criação deste item por mim, o mercado de trabalho está interessado em sua conclusão e módulos estudados, querem saber se você concluiu e quando concluiu (a data de conclusão é importante pois mostra até que nível de atualização da tecnologia em questão você estudou). Mostrar que você gastou mais tempo do que o recrutador acredita que seja válido para um estudo específico só trás malefícios e nenhum benefício.

**Comment by edsoncosta2020** [comment]
Também acredito que a data da conclusão seja mais interessante. Tenho cursos (curto) que inicei há vários meses e por uma necessidade maior fui fazendo outros e voltando agora para aqueles que havia iniciado. Como mencionado, um curso de 6hs, 40 horas levando meses para sua conclusão fica um tanto "estranho". Data atual sempre é mais importante.
