### ISSUE TITLE
Legenda nos vídeos

### ISSUE THREAD

**Issue by paaarx** [caelum/alura-funcionalidades#184]
Legenda no formato do YouTube, onde pode ativar ou desativar.

Vocês já tem o trabalho de transcrever o que é dito mesmo, colocar a legenda seria só mais um pouco de esforço para sincronizar o texto.

Além do lance da inclusão, dá uma ajuda quando não se pode ouvir o áudio do vídeo, porém quer acompanhar o que está sendo feito, vendo o vídeo e lendo a legenda.

Enfim, antes de sair fazendo em tudo, faz um piloto, solta um curso mais curto e com bastante acesso, vê o que acham, se não fica o texto em cima dos códigos, etc, etc.

https://cursos.alura.com.br/user/paaarx

**Comment by designernatan** [comment]
@paaarx valeu pela sugestao!

tem [uma outra issue sobre legendas aqui](https://github.com/caelum/alura-funcionalidades/issues/10), com o reply do Paulo, vou fechar essa mas pode comentar lá em cima sem problemas!

fazer um piloto é um negócio legal, casa bem com o que a gente sempre tenta fazer aqui: testar antes de escalar :)
