### ISSUE TITLE
Opção de refazer curso já concluído (zerar o progresso)

### ISSUE THREAD

**Issue by adriano-coelho** [caelum/alura-funcionalidades#185]
Ao refazer um curso que já está com 100% de progresso ele não salva o ponto onde você parou, e não tem como refazer os exercícios. Sugiro uma opção de zerar o progresso de um curso já concluído para que ele possa ser refeito, como se estivesse fazendo pela primeira vez (começar de 0%).

**Comment by adriano-coelho** [comment]
Achei uma issue com essa mesma sugestão, desculpem não ter pesquisado melhor antes de abrir, primeira vez que uso o github. Vou fechar essa aqui. Valeu!

**Comment by designernatan** [comment]
@adriano-coelho fica 100% tranquilo!! 

a [issue igual seria essa aqui](https://github.com/caelum/alura-funcionalidades/issues/11), mas em suma estamos vendo de como melhorar a experiência de vocês na hora de refazer um curso

Pode me mandar o link do seu perfil da alura dps? Qual curso hoje você precisaria resetar (pergunto mais por pesquisa mesmo)

abração!

**Comment by adriano-coelho** [comment]
@designernatan segue: 

Perfil: adriano.coelho-852
Curso: Orientação a Objetos com PHP: Classes, métodos e atributos

Abraço e obrigado!
