### ISSUE TITLE
Cursos em full hd

### ISSUE THREAD

**Issue by Joao-amoedo** [caelum/alura-funcionalidades#186]
Gostaria que disponibilizassem os novos cursos em full hd, percebi que a maioria (senão todos) estão em hd, e as vezes gostaria de uma qualidade melhor para poder visualizar com mais facilidade o que está sendo passado, e também por ser mais satisfatório assistir conteúdos em full hd

**Comment by designernatan** [comment]
@Joao-amoedo valeu pela sugestao!

Hoje os vídeos não são full HD porque a maior parte dos instrutores grava em computadores acessiveis a alunos e alunas, que possuem uma resolução de 1368*768, também priorizamos a transmissão de dados com vídeos leves que não exigem uma internet muito rápida nem vão ocupar muito espaço no celular de quem faz download no aplicativo

**Comment by Joao-amoedo** [comment]
Mas gravar videos em Full HD não remove a opção de assistir em HD ou SD, apenas acrescenta a possibilidade para quem quer ver em uma resolução maior. Assim como no app tem a opção de escolher a qualidade do download para ocupar mais ou menos espaço

**Comment by designernatan** [comment]
@Joao-amoedo pedi auxílio do líder do time de vídeo mais detalhes sobre o tema! 

"A qualidade de captação é limitada pelo screen cast, a resolução dos computadores está diretamente ligada ao tamanho da disposição dos elementos nos sistemas operacionais, quando gravamos em uma tela fullhd os textos, icones e outros elementos da UI são dispostos no computador de forma mais espaçada com o tamanho menor, quando isso é editado e convertido para o tamanho HD ou SD ocorre uma grande perda de legibilidade e o acompanhamento dos vídeos fica prejudicado. Veja o exemplo nas imagens abaixo:
![image](https://user-images.githubusercontent.com/5431347/87175739-75d24000-c2af-11ea-91c8-43b8bdde83b5.png)

Diferente dos softwares que disponibilizam mudança de tamanho de fonte, os sistemas operacionais atrelam essa alteração a resolução do monitor, então para conseguirmos icones, fontes e outros detalhes em uma resolução alta precisamos utilizar a gravação do sistema com uma resolução reduzida. Poderiamos finalizar os vídeos em fullhd, pois as imagens da webcam do instrutor são gravadas nesta resolução, porém a parte principal da aula (a gravação da tela) ainda assim estaria em uma resolução mais baixa apenas esticada para fullhd.

importante dizer, não dá pra dar zoom em vídeo sem perder todos os detalhes da tela e sem fazer upscaling que de qualquer maneira vai diminuir a resolução apresentada já que está sendo feita uma ampliação digital durante a edição"
