### ISSUE TITLE
Acesso no plano corporativo

### ISSUE THREAD

**Issue by mxgmstz** [caelum/alura-funcionalidades#187]
Tenho acesso através do plano corporativo.. E esse acesso é por tempo limitado, dependendo do tempo necessário para realizar o curso. Depois disso, perco o acesso ao Alura. Ou seja, não consigo mais rever nenhum vídeo do curso que eu fiz.
Não há como o aluno permanecer com acesso aos cursos já realizados? Mesmo que seja em somente leitura? Sem acesso aos demais cursos. Existe essa opção para a corporação?
Do jeito que está, duas semanas após a realização do curso não posso mais ver nenhum material relacionado ao curso.

**Comment by designernatan** [comment]
@mxgmstz atualmente não temos essa possibilidade, pois a alura plano corporativo (e o não corporativo também) é baseado em licença para acessos, seja de cursos feitos ou não feitos

outras opções seria ter uma conta pessoal não vinculada à empresa ou mesmo conversar com sua gestão para ter sua licença liberada por mais um período
