### ISSUE TITLE
Sugestão de continuidade após terminar um curso

### ISSUE THREAD

**Issue by gregoriLima** [caelum/alura-funcionalidades#188]
Ao finalizar um curso poderia haver uma indicação de um próximo treinamento, como sugestão.

Por exemplo, terminei o curso de "Spring MVC I: Criando aplicações web", ao final do curso já poderia ser dada a sugestão de continuar com um novo curso como "Spring MVC II: Integração, cache, segurança e templates", caso o aluno esteja ou não seguindo uma formação.

Ou na própria pagina de apresentação do curso, onde aparecem os pré-requisitos e as formações das quais o curso faz parte, poderia mostar "após este curso você pode continuar com..."

**Comment by designernatan** [comment]
@gregoriLima valeu pela sugestao!

no futuro veremos como melhorar essas recomendacoes (principalmente em caso de curso parte 1 e 2 como vc mencionou)

spoiler: no segundo semestre teremos uma novidade que vai entrar em beta que vai ajudar bastante quem está cursando uma formação, fica tranquilo que só de logar você vai ver :)

abração!
