### ISSUE TITLE
Grupo da alura no discord

### ISSUE THREAD

**Issue by caicob** [caelum/alura-funcionalidades#189]
Criar um grupo no discord para a Alura e divulgar para alunos se conhecerem e resolverem problemas em conjunto.
.

**Comment by designernatan** [comment]
@caicob valeu pela sugestao!

vez ou outra alguem sugere algo assim, o ponto é que seria mais complicado: o chat passa a sensação que tudo precisa ser respondido imediatamente, sem contar as frases muito curtas, o que não conseguiríamos dar conta (estamos contratando mais para a equipe de suporte e instrutores(as) no forum tambem)

você chegou a participar de alguma imersao da Alura esses meses? Como foi a experiencia com o discord nelas ou em outras comunidades?

**Comment by caicob** [comment]
Não cheguei a participar de nenhuma imersão!

Poderia ser criado para debate entre alunos mesmo novos e antigos! entendo que vcs não possuem muios instrutores para da suporte e que os instrutores que tem estão preocupados em atualizar o conteúdo, mas mesmo assim acho importante o discord para conversas entre alunos.

Alem de ser uma plataforma que ate onde eu saiba é gratuita e de fácil acesso! podendo ter discussões em áudio e vide-o, entre alunos!

**Comment by luigiMinardi** [comment]
> @caicob valeu pela sugestao!
> 
> vez ou outra alguem sugere algo assim, o ponto é que seria mais complicado: o chat passa a sensação que tudo precisa ser respondido imediatamente, sem contar as frases muito curtas, o que não conseguiríamos dar conta (estamos contratando mais para a equipe de suporte e instrutores(as) no forum tambem)
> 
> você chegou a participar de alguma imersao da Alura esses meses? Como foi a experiencia com o discord nelas ou em outras comunidades?

@designernatan acho que seria util um grupo do discord pra comunidade da alura interagir melhor, não seria um grupo pra suporte, seria mais um grupo pra comunidade interagir entre si msm, e se ajudar tbm. Participei da imersão game-dev e da de Data Science. A de DS a comunidade foi no Slack e a Game-Dev foi no discord. Só o fato de poder compartilhar e discutir os projetos entre si ja me fez achar muito boa essa ideia.
