### ISSUE TITLE
Botão de pular X segundos para frente ou para trás

### ISSUE THREAD

**Issue by celsott** [caelum/alura-funcionalidades#19]
Olá,

Assim como na maioria dos players de cursos online, seria interessante que aqui também tivesse esse recurso de pular x segundos para frente ou para trás para facilitar a navegação.

**Comment by carlosmuller** [comment]
Olá @celsott colocamos recentemente alguns atalhos de teclado pode ver mais aqui https://github.com/caelum/alura-funcionalidades/issues/1#issuecomment-564010301.
