### ISSUE TITLE
Reiniciar curso

### ISSUE THREAD

**Issue by viniciusnicassio** [caelum/alura-funcionalidades#190]
Em algumas situações acabo querendo refazer um curso para me reciclar, porém como o curso já foi feito anteriormente as respostas das questões já são mostradas o que não ajuda na reciclagem.

**Comment by designernatan** [comment]
@viniciusnicassio valeu pela sugestao!

já vou fechar a issue pois tem uma [issue igual a essa aqui](https://github.com/caelum/alura-funcionalidades/issues/11), mas em suma estamos vendo de como melhorar a experiência de vocês na hora de refazer um curso

Pode me mandar o link do seu perfil da alura dps? Qual curso hoje você precisaria resetar (pergunto mais por pesquisa mesmo)

abcs!
