### ISSUE TITLE
Melhoria no fórum: não consigo responder tópicos com mais de duas semanas

### ISSUE THREAD

**Issue by razzolim** [caelum/alura-funcionalidades#191]
![topico](https://user-images.githubusercontent.com/59750843/86986833-fdfafd00-c16a-11ea-9f64-fbb7d74ff499.PNG)

Entendo como fórum um local em que se o tópico é aberto, até que ele não seja resolvido (ou mesmo depois de ser resolvido) é possível inserir respostas.

Conforme a imagem que está em anexo, havia um tópico aberto em 07/04/2020 sem resposta. Hoje (08/07/2020) eu vi o tópico e teria uma resposta para a dúvida do colega. O único problema é que não consigo responder... As vezes os próprios alunos têm as respostas, mas não conseguimos compartilhar.

**Comment by luigiMinardi** [comment]
Acho q seria massa colocar aquela ideia tipo oq o stackOverFlow faz com as perguntas, se voce tiver X pontos no forum você pode votar pra re-abrir o tópico.

**Comment by designernatan** [comment]
@razzolim @luigiMinardi valeu pelas sugestoes!!

o sergio comentou sobre esse isso aqui [nessa outra issue](https://github.com/caelum/alura-funcionalidades/issues/97) e por isso já vou fechar esta

nesses casos de querer contribuir atrapalha mesmo :/
