### ISSUE TITLE
Botão para ir para a próxima aula no final do vídeo em tela cheia

### ISSUE THREAD

**Issue by rosariotech** [caelum/alura-funcionalidades#192]
Realizando os cursos em tela cheia, sempre que termino um vídeo é necessário sair da tela cheia, clicar para prosseguir para a próxima aula e depois voltar pra tela cheia.

Se tivesse algum botão na própria tela cheia para que navegasse para o próximo curso seria algo que traria mais foco. Mesmo que o botão apenas redirecionasse e saísse da tela cheia. O ideal seria mesmo ele ir para o próximo vídeo sem sair da tela cheia.

**Comment by designernatan** [comment]
@rosariotech valeu pela sugestao!

tem uma [issue igual a essa aqui](https://github.com/caelum/alura-funcionalidades/issues/118) 

estamos vendo melhorias nessa tela de aula, e uma navegação desta forma está na pauta!
