### ISSUE TITLE
Encontrei um "erro" na plataforma

### ISSUE THREAD

**Issue by eduardopr14** [caelum/alura-funcionalidades#193]
Encontrei um pequeno "erro" na plataforma, um detalhe que quase passa desapercebido.

No perfil de usuário, especificamente na parte "ATIVIDADE NOS ÚLTIMOS 30 DIAS", o dia mais antigo (primeiro dia da lista) deleta os pontos e sempre marca como não ganhou pontos naquela data.
Pra quem marca as atividades realizadas em cada dia isso pode prejudicar um pouco a experiência.

Anexei duas imagens que demonstram o que acontece exatamente.

![Imagem01](https://user-images.githubusercontent.com/53017704/87189895-dc635800-c2c7-11ea-82c1-fa1c2af0e90b.png)
![Imagem02](https://user-images.githubusercontent.com/53017704/87189892-dbcac180-c2c7-11ea-9ccf-ab2a46ae4017.png)

Enfim, nada grave. Espero que ajude.
Observação: Não achei outro lugar para mandar esse tipo de mensagem, podiam inserir algo do tipo na plataforma também (com possibilidade de anexo de imagens).

Obrigado pela atenção. Ótima plataforma e cursos.

**Comment by designernatan** [comment]
@eduardopr14 valeu pelo toque!

parece um minor mesmo, pedi uma ajuda pro dev team para que no futuro deem uma olhada

estamos vendo melhorias dessas sugestoes de bug e outras, medio prazo

brigadao pelo seu tempo em ajudar a gente!

**Comment by GesleyElois** [comment]
Pessoal, já está no ar a correção, obrigado por nos avisar.
