### ISSUE TITLE
Efetuar Matrícula

### ISSUE THREAD

**Issue by mpequenovieira** [caelum/alura-funcionalidades#194]
Olá! 

Então, estou na frente do note, frustrado e chateado porque quero me matricular na Alura e não vou poder pq meu cartão não tem limite e no site de vcs não tem a opção de usar um segundo cartão. 

Se tivesse essa função eu poderia me matricular! Sugiro que pensem com carinho em disponilizar o recurso de usar mais de um cartão de crédito.

**Comment by designernatan** [comment]
@mpequenovieira pinga no contato@alura.com.br e comenta sobre seu caso?

time de atendimento vai fazer de tudo pra te ajudar
