### ISSUE TITLE
PDE não é excluído por completo

### ISSUE THREAD

**Issue by luizwhite** [caelum/alura-funcionalidades#195]
### Olá!
Notei há um tempo que corrigiram a exclusão dos PDE, obrigado! #105 #120 #149 #174  

#
**1.**  Porém, quando estamos visualizando algum curso e desejamos adicioná-lo a um de nossos PDEs, é possível visualizá-lo no menu *dropdown*. &#x1F632;
<img src="https://user-images.githubusercontent.com/4944479/87708624-66546a80-c779-11ea-9dcf-b5927e234b24.png" height="150">

# 
**2.**  Além disso, quando temos um PDE e resolvemos segui-lo, e depois deletá-lo, ele continua em nossa Dashboard. &#x1F632;
Só após eu abrir ele em minha Dashboard (com ele já deletado) e remover o *"Exibindo na Dashboard"*, ele sumiu.

Se meu caso é exceção, ou eu fiz algo de errado me avise &#x1F605;

**Comment by designernatan** [comment]
1. Poxa o time fez uma feature de backup moh bacana e falam que é bug! (╯°□°）╯︵ ┻━┻
Falando sério: é bug mesmo e acabei de pingar o time de produto! 

2. Outro bug! Passei para o time também, essa ia demorar p/alguém pegar.

Valeu mesmo meu caro!

**Comment by luizwhite** [comment]
>     1. Poxa o time fez uma feature de backup de PDE moh bacana e falam que é bug! (╯°□°）╯︵ ┻━┻
┬─┬ノ( º _ ºノ)
>        Falando sério: é bug mesmo e acabei de pingar o time de produto!
>
>     2. Outro bug! Passei para o time também, essa ia demorar p/alguém pegar.
> 
> 
> Valeu mesmo meu caro!

@designernatan, sem problemas! Quando tiver alguma atualização da *Issue* da um toque
Se achar mais alguma coisa mando aqui, mas acho que era só isso mesmo rs
&#x1F44D;

**Comment by designernatan** [comment]
corrigido!
