### ISSUE TITLE
Criar Projeto de Front-End

### ISSUE THREAD

**Issue by luizwhite** [caelum/alura-funcionalidades#196]
###  Olá!
Não me recordo de ter conferido a seção de Projetos quando iniciei na Alura, porém acreditava que já existia um projeto Front-End.
Fui acessar essa semana e notei que realmente não tem &#x1F62D;

Notei também que a formação Front-End foi atualizada recentemente, então estou com a esperança que esta *Issue* esteja com a equipe de Projetos &#x1F91E;
Mais estranho ainda foi vir aqui e ver que não há nenhuma solicitação disso..

Estão com essa ideia em andamento?? Ou projetos JS, React, HTML/CSS?

**Comment by designernatan** [comment]
@luizwhite olá!

Acabamos removendo pois o projeto original era baseado justamente na versão anterior da Formação Front-End, que tinha React em sua grade. Como a Formação Front-end evoluiu para a atual, não fez sentido deixarmos o projeto.

Estamos reformulando alguns cursos dessa e outras áreas.
Conforme sejam lançados aparecerão lá no /explore (sininho). 
Sem datas infelizmente.

Abcs!

**Comment by luizwhite** [comment]
> @luizwhite olá!
> 
> Acabamos removendo pois o projeto original era baseado justamente na versão anterior da Formação Front-End, que tinha React em sua grade. Como a Formação Front-end evoluiu para a atual, não fez sentido deixarmos o projeto.
> 
> Estamos reformulando alguns cursos dessa e outras áreas.
> Conforme sejam lançados aparecerão lá no /explore (sininho).
> Sem datas infelizmente.
 
Fiquei confuso.
Se o que entendi está correto, não tem nenhum Projeto Front-End sendo desenvolvido e não há planos para desenvolve-lo. 
É isso?

![image](https://user-images.githubusercontent.com/4944479/87722051-d10fa100-c78d-11ea-87fc-dc85bef606b1.png)

**Comment by designernatan** [comment]
oi luiz!

estamos vendo como melhorar mais ainda a parte de projetos, e um projeto front-end (e de outras áreas) está na pauta

abcs!
