### ISSUE TITLE
Mobile - Favoritar Cursos (Assistir + tarde)

### ISSUE THREAD

**Issue by luizwhite** [caelum/alura-funcionalidades#197]
### Olá!
Notei que no Android não é possível favoritar cursos. Acho que seria essencial, pois a forma de visualizar as novidades é bem melhor no celular, e conforme formos visualizando, podemos ir marcando os cursos que queremos conferir mais tarde. :)

Estou no aplicativo agora e terei que abrir um browser, logar, procurar o curso, para entao salvar (sem iniciar no curso)

Vou criar outra *Issue* com uma funcionalidade parecida,  mas achei melhor não misturar.

**Comment by felipetorres** [comment]
Olá! Já está nos nossos planos favoritar um curso no app, mas por hora estamos fazendo outras tarefas mais requisitadas. Abraço.
