### ISSUE TITLE
Instruções sobre ambiente de desenvolvimento do instrutor.

### ISSUE THREAD

**Issue by juceliohv** [caelum/alura-funcionalidades#199]
Sugestão........................:

> Quando o aluno iniciar um curso, que seja apresentada de alguma forma  (no video, no texto, ou alguma widget dentro do curso), quais as ferramentas, vendors e versões que o o instrutor utilizou para chegar àquele resultado.
Por exemplo: Eclipse versão xxxx, JDK Oracle versão xxxxxx, git versão xxxxxx, node versão xxxxx.

Motivação........................: 

> Em mais de curso, perdi um tempo precioso tentando arrumar o ambiente, por que estouraram os mais diversos erros. Não só perdi tempo, mas a paciência também. Acredito que o objetivo principal do curso é fazer o aluno aprender o conteúdo na prática, mas sem desvalorizar o pouco tempo que ele tem disponível.

> Em alguns cursos consegue-se descobrir estas coisas, mas somente quando já se está terminando o curso. Isso é ruim.

**Comment by designernatan** [comment]
@juceliohv valeu pela sugestao!

vou passar para o time de conteúdo, em geral ficamos de olho nisso, algumas vezes escapa (mas não deveria)
quais cursos exatamente vc sentiu isso? Aí já passo para o time

lembrando que vc pode passar feedback do curso direto no término ou no 'sugerir melhoria'
![image](https://user-images.githubusercontent.com/5431347/88174122-1d2d6c00-cbfa-11ea-87dc-1c637175cc75.png)


abcs!

**Comment by juceliohv** [comment]
Bom dia,

Senti muita falta disso no curso de kubernetes. Perdi algum tempo com
configuração.

Atenciosamente,

Jucélio Horácio Vieira
------------------------------------------
Joinville, SC - Brasil
+55 47 99784-1750 (whatsapp)
skype: jucelio.vieira


Em qua., 22 de jul. de 2020 às 09:03, Natan Souza <notifications@github.com>
escreveu:
