### ISSUE TITLE
Upvote (estrela?) em mensagens do fórum e mostrar as mais votadas

### ISSUE THREAD

**Issue by peas** [caelum/alura-funcionalidades#2]
Poder dar votos positivos, tanto em questões quanto em respostas. Vantagens:
- sabemos as perguntas mais comuns e importantes, podendo mostrá-las aos alunos em determinada aula, além de melhorar as aulas
- poder dar pontos para quem participa bem da comunidade

**Comment by peas** [comment]
Esse aqui vai ser algo maior:
- envolverá upvotes
- artigos relacionados
- uma forma de gamificar melhor
- poder fortalecer a comunidade

**Comment by designernatan** [comment]
fechando issue, mas bora discutir em cima disso!
