### ISSUE TITLE
Correção: Ícone de Antigas Carreiras

### ISSUE THREAD

**Issue by Marcel-Felipe** [caelum/alura-funcionalidades#20]
O link para os ícones da antiga carreira data science foi removido [aqui](https://www.alura.com.br/assets/api/carreiras/carreira-data-science.svg), logo nenhuma imagem é carregada na seção de formações no meu perfil.

![image](https://user-images.githubusercontent.com/24639770/71422630-69173300-2662-11ea-9397-8a9325ba6f57.png)

**Comment by designernatan** [comment]
opa, obrigado pelo toque @Marcel-Felipe
