### ISSUE TITLE
Mobile x Browser - Tratamento HTML na descrição do PDE - bug?

### ISSUE THREAD

**Issue by luizwhite** [caelum/alura-funcionalidades#202]
### Olá
Estava brincando um pouco com o código da descrição do PDE e vi que no Mobile o tratamento é diferente.
Ex.: `<li></li>` adiciona bullet no mobile, mas no browser não.
Ex2.: `<img />` adiciona imagem no browser,  mas no mobile não (até adiciona, mas fica um icone padrão)
Pode comparar usando PDE Front-End do meu usuario se quiser (não consegui copiar o link no celular)

Se vão deixar só MD, acho melhor desabilitar tags HTML nos 2.

**Comment by designernatan** [comment]
@luizwhite valeu pela sugestao!

estamos vendo como melhorar toda essa experiência com o MD, não só nos PDEs mas na Alura inteira
