### ISSUE TITLE
Mobile - Curso concluído porém barra de progresso não está completa - bug?

### ISSUE THREAD

**Issue by luizwhite** [caelum/alura-funcionalidades#203]
### Olá!
Notei que em minha formação HTML e CSS p.ex. que o total de cursos concluídos está certo. 
Porém rolando para baixo notei que a barra de progresso está incorreta (imagem abaixo). Até pensei que poderia demorar mais para sincronizar no mobile, nas nao fazia sentido sendo que finalizei o SASS antes do Flexbox.
Lembrando que já finalizei os dois.

<img src="https://user-images.githubusercontent.com/4944479/87843352-58423f00-c88a-11ea-8229-8bb130acf5d0.jpg" width="300">

**Comment by DevCapu** [comment]
@luizwhite Boa tarde! Meu nome é Felipe Moreno e sou um dos responsáveis pelo app.

Quando a barra está cinza assim, ela indica que é o nosso último progresso seu salvo no app, para atualizar e ficar com a medalha você precisa sincronizar o seu aplicativo, para isso você pode ir até a tela inicial, clicar nos três pontinhos no canto superior direito e tocar em "sincronizar", após isso você verá que seu progresso estará correto.

Espero ter ajudado e bons estudos!

**Comment by luizwhite** [comment]
> @luizwhite Boa tarde! Meu nome é Felipe Moreno e sou um dos responsáveis pelo app.
> 
> Quando a barra está cinza assim, ela indica que é o nosso último progresso seu salvo no app, para atualizar e ficar com a medalha você precisa sincronizar o seu aplicativo, para isso você pode ir até a tela inicial, clicar nos três pontinhos no canto superior direito e tocar em "sincronizar", após isso você verá que seu progresso estará correto.
> 
> Espero ter ajudado e bons estudos!

@DevCapu 
Funcionou aqui obg!
Se quiser posso abrir outra issue, mas acho essencial que essa sincronização seja **automática**. Entro no app frequentemente e não tem sido sincronizado automaticamente

![Cursos Front-End](https://user-images.githubusercontent.com/4944479/88198823-7c9b7400-cc1a-11ea-8212-597336d78753.jpg)

**Comment by DevCapu** [comment]
@luizwhite Boa tarde!

Não sincronizamos automaticamente por que alguns alunos muitas vezes possuem planos limitados, quem nunca estourou o pacote mensal né? Não queremos gastar internet desnecessária dos nossos alunos. 

Ainda assim, obrigado pela sugestão. Bons estudos!
