### ISSUE TITLE
Caderno em aba/janela separada

### ISSUE THREAD

**Issue by BidoOBido** [caelum/alura-funcionalidades#204]
Possibilitar o uso (visualização/edição) dos cadernos em uma aba ou janela separada à do curso.

Ao meu ver essa funcionalidade facilitaria muito para quem faz os cursos utilizando mais do que um monitor, mantendo o vídeo em tela cheia em um dos monitores e o caderno em outro.

**Comment by designernatan** [comment]
@BidoOBido valeu pela sugestao!

faz todo sentido, mesmo o caderno em beta, algo assim parece fazer sentido

**uma dúvida:** quão interessante seria o modo PiP no vídeo pra você nessa situação de uso do caderno e 2 monitores?

**Comment by BidoOBido** [comment]
@designernatan o modo PiP e bastante interessante. Eu não havia pensado ainda em  utilizá-lo desta maneira.

**Comment by designernatan** [comment]
@BidoOBido vc pode testar uns tempo (horas ou dias, oq fizer sentido) e dar um reply aqui depois por favor?

só pra ver se na prática o PiP já resolveria :)

posso te pingar por aqui algum dia se preferir tbm

**Comment by BidoOBido** [comment]
@designernatan, fiz algumas horas de aula usando o PiP e o mesmo me ajudou bastante. 
O único ponto que ainda me incomodou foi o fato do caderno ficar fixo em tamanho e posição, se houvesse a possibilidade de manipular o fragmento do [caderno](https://user-images.githubusercontent.com/18104744/88442569-6395ed00-cdeb-11ea-88dd-d7106b647b19.png) da mesma maneira que faço com a janela Pi, seria perfeito.
