### ISSUE TITLE
troca de ordem instalação do ruby

### ISSUE THREAD

**Issue by castrohs** [caelum/alura-funcionalidades#207]
Não é uma funcionalidade mas é um erro a forma que o curso se apresenta.
Já começa com o instrutor jogando como fazer isso, eu nem sei instalar o ruby no computador, ai eu descubro que no item 09 tem como fazer tipo eu perdi a vontade de fazer o curso quando eu verifiquei que o instrutor começou jogando conteúdo mas não tenho como aplicar... é tipo meio inútil 08 aulas que eu só assisti mas como é uma linguagem que eu não sei nada eu não tinha visto futuro nela.
Favor trocar a ordem, notei que existem outros pedindo a mesma coisa no fórum

**Comment by designernatan** [comment]
@castrohs pinguei o time de conteudo, obrigado pelo toque

**Comment by designernatan** [comment]
@luigiMinardi vc teve esse problema com o ruby também?

**Comment by luigiMinardi** [comment]
@designernatan ainda não cheguei a usar Ruby mas a respeito de instalação de linguagens eu instalo tudo pelo [asdf](https://asdf-vm.com/), bumpei porque parecia uma thread importante mesmo
