### ISSUE TITLE
Responder um tópico antigo

### ISSUE THREAD

**Issue by castrohs** [caelum/alura-funcionalidades#208]
Ainda não entendi por que a alura trava resposta para tópicos com mais de duas semanas, por que no stack, é possivel responder

**Comment by luigiMinardi** [comment]
https://github.com/caelum/alura-funcionalidades/issues/97

**Comment by castrohs** [comment]
> 
> 
> Confere esse topico [aqui](https://github.com/caelum/alura-funcionalidades/issues/97)

obrigado, mas é inutil na forma atual por que deixar 2 semanas é pouco tempo.
