### ISSUE TITLE
Fórum - Avaliação de tópico

### ISSUE THREAD

**Issue by AndersonChaves-SERPRO** [caelum/alura-funcionalidades#209]
No fórum ter opção de avaliar se o leitor achou o tópico útil ou não, com 2 contadores. Um contador para a quantidade de pessoas que acharam o tópico útil e outro para as que não gostaram. Além de externar a qualidade do tópico, também seria possível medir a quantidade de visitas pela Alura, inclusive inserindo alguma indicação de cursos relacionados.

**Comment by designernatan** [comment]
@AndersonChaves-SERPRO obrigado pela sugestao! O Paulo sugeriu [algo semelhante aqui](https://github.com/caelum/alura-funcionalidades/issues/2)

comenta lá depois o que você acha?

casa bem com a situação que você passou!
