### ISSUE TITLE
Video transcript

### ISSUE THREAD

**Issue by mxeliezer** [caelum/alura-funcionalidades#21]
Estou a concluir uma formação online em Peer Review, oferecida pela **Publons Academy**. O curso tem vídeos e outros materiais interessantes. O formato sugere uma possível nova funcionalidade para a Alura. Chama-se **Video transcript**. E é basicamente um botão onde posso descarregar em formato pdf o script de tópicos seguidos no vídeo que foi apresentado. Achei o formato interessante pois permite ao aluno organizar, se assim o desejar, conteúdos dos cursos em ficheiros para rápidas consultas offline. Segue uma captura de tela para melhor ilustrar. Nela, podemos ver ainda que eles dispunham também o botão para descarregar o vídeo em formato slides (PDF), com tópicos do mesmo vídeo. Links descritos no vídeo, listados logo abaixo. e ainda micro-vídeos com dicas especiais, de grandes especialistas na área.
![tela publons curso](https://user-images.githubusercontent.com/57819235/71579142-2edee300-2af3-11ea-9450-456f936a4676.png)

**Comment by designernatan** [comment]
valeu pela sugestão @mxeliezer !

estamos estudando e fazendo alguns testes sobre isso de organização de estudos dentro da Alura

**muito** obrigado!

**Comment by designernatan** [comment]
@mxeliezer 

uma curiosidade minha: você baixa esse PDF e salva onde exatamente?

se puder responder esse tópico aqui também agradeceria muito!
https://cursos.alura.com.br/forum/topico-como-voce-estuda-aqui-na-alura-93996

**Comment by mxeliezer** [comment]
Em meu caso, usei estes video transcripts para compor um único documento de consulta rápida que utilizo quase como um check list quando estou fazer a review de um artigo científico. Ou seja, para mim foi bastante útil.
