### ISSUE TITLE
Modo escuro no site

### ISSUE THREAD

**Issue by Lucas3995** [caelum/alura-funcionalidades#214]
Um DarkMode ajudaria muito na navegação do site.
As vezes estou estou programando ou vendo algo em outro lugar e quando volto para a aba do alura, parece que acenderam um farol na tela do computador.
Não sei como é o código do alura, então não sei o trabalho que isso daria.
Mas para quem fica bastante tempo no site faria uma boa diferença...

**Comment by designernatan** [comment]
@Lucas3995 valeu pela sugestão!

[falei mais sobre ela aqui nessa outra issue](https://github.com/caelum/alura-funcionalidades/issues/116)

depois vc pode dar um salve por lá? Perguntei umas coisas que podem ajudar a gente a priorizar uns pontos
