### ISSUE TITLE
Função "Reiniciar Curso"

### ISSUE THREAD

**Issue by geraldoao** [caelum/alura-funcionalidades#215]
Adicionar neste menu abaixo a opção "Reiniciar curso" para podermos retomar um curso a partir do zero.

![image](https://user-images.githubusercontent.com/522728/88801945-c76c3d00-d180-11ea-9238-5317c5722a24.png)

**Comment by designernatan** [comment]
@geraldoao valeu pela sugestao!

já vou fechar a issue pois tem uma [issue igual a essa aqui](https://github.com/caelum/alura-funcionalidades/issues/11), mas em suma estamos vendo de como melhorar a experiência de vocês na hora de refazer um curso

Pode me mandar o link do seu perfil da alura dps? Qual curso hoje você precisaria resetar (pergunto mais por pesquisa mesmo)

@thisudre vc tbm por favor

**Comment by geraldoao** [comment]
Olá,
Tranquilo. Como passei um tempo sem assinatura, desejo seria de resetar
todos que estão em andamento. Nesta situação, acho adequado reiniciar o
curso para revisar e obter possíveis atualizações, como também para que um
novo período seja definido para fins de certificado.
Grato.

Em qui., 30 de jul. de 2020 às 15:51, Natan Souza <notifications@github.com>
escreveu:
