### ISSUE TITLE
Reprodução de videoaulas sequenciais

### ISSUE THREAD

**Issue by pablocastrobarbosa** [caelum/alura-funcionalidades#218]
Poderia ter a opção de ao terminar uma videoaula automaticamente passar para a próxima videoaula.
As vezes estamos no mercado fazendo compras, no banho ou em alguma outra situação onde fica ruim manusear o celular e toda hora tem que ficar pegando o celular para dar o play na próxima videoaula.
Pelo menos até no próximo exercício já ajudaria muito.

**Comment by felipetorres** [comment]
Oi @pablocastrobarbosa, como vc disse sobre o celular, posso entender que é no app?

Estamos finalizando essa funcionalidade nos apps Android e iOS da Alura e já já vai pro ar.

**Comment by pablocastrobarbosa** [comment]
Exatamente! Pelo App.

Muito bom. Parabéns par a equipe de dev.
