### ISSUE TITLE
Correções Alura+

### ISSUE THREAD

**Issue by caiopapai** [caelum/alura-funcionalidades#22]
Dentro do Alura+ acredito que alguns videos estão com a Tag equivocada, seguem os casos:

Em Inovação & Gestão:
tem o video https://cursos.alura.com.br/hacker-rank-19-dificil-maximize-it-c71 que deveria estar em: Programação

Em Programação:
O video https://cursos.alura.com.br/git-ammend-editando-uma-mensagem-de-commit-c122 deveria estar em Infraestrutura (pois lá se encontram todos os videos relacionados a GIT).

o video https://cursos.alura.com.br/fronteiras-do-front-end-ep-06-testes-para-front-end-faz-sentido--c110 deveria estar em Front End

**Comment by bjverde** [comment]
Outro :bug: Bug é no vídeo "O que é Kubernetes? #AluraMais"
Que mando para o link https://www.youtube.com/watch?v=6VsUuyOpncQ que não está funcionando

**Comment by designernatan** [comment]
oi pessoal, achei que tinha respondido aqui já

passei para o time de conteúdo esses 🐛s 

obrigado pela ajuda!
