### ISSUE TITLE
Marcar o curso como finalizado pelo APP [Mobile]

### ISSUE THREAD

**Issue by pablocastrobarbosa** [caelum/alura-funcionalidades#220]
Só uso o alura pelo App no android. Estou fazendo uma formação e já passei da metade, mas não atualiza a informação cursos concluídos do total disponível na formação. Só fica 0/13 embora eu já esteja na etapa 7 tendo concluído todas as anteriores.
Resolvi acessar pela web e ví que ao finalizar um curso pela web sou direcionado à uma página de avaliação do curso onde após a avaliação o curso é marcado como concluído, e aí sim o progresso vai incrementando. 1/13 ....   2/13 ....   .....   7/13...

Esta avaliação só aparece pela web e não pelo app mobile, embora nos vídeos de conclusão do curso o instrutor fala que serei direcionado para uma página de avaliação.

**Comment by felipetorres** [comment]
Atualmente não é possível finalizar um curso pelo app justamente por ser necessária essa avaliação. Então, no app o curso fica em 100% de progresso; mas para ficar com a medalhinha de finalizado precisa acessar pela web, como vc fez.

Ainda não pensamos muito bem como faríamos isso nos apps, porém o que já vamos fazer é exibir um botão para finalizar um curso depois de um certo avanço (igual tem na web, sabe?) justamente por não envolver a tela de avaliação de curso.

**Comment by pablocastrobarbosa** [comment]
Obrigado pelo retorno.

Não daria para colocar a avaliação no app também?

Em sex, 31 de jul de 2020 09:39, Felipe Torres <notifications@github.com>
escreveu:

**Comment by felipetorres** [comment]
Dá pra colocar, sim; mas num primeiro momento preferimos colocar esse botão de "finalizar curso" por ser algo mais simples que implementar a avaliação e já agregar valor pros alunos e alunas.
