### ISSUE TITLE
Uma sessão parecida com a "Pre-Requisitos" para o que estudar a seguir

### ISSUE THREAD

**Issue by Lucas3995** [caelum/alura-funcionalidades#224]
Seria interessante ter em algum lugar dentro da tela do curso algo como a parte em que lista os cursos "Pré-Requisitos" para aquele, porém sugerindo qual curso fazer a seguir.
Dois exemplos do que ja existem no site:
1. O primeiro como ja mencionado acima: um curso com o nome "Entity Linq parte 2" vai dentro da pagina dele uma sessão "PRÉ-REQUISITOS" onde vai estar listando o curso "Entity Linq parte 1".
2. O segundo é uma sugestão que já existe na Dashboard chamado "Recomendados para você" que contem (acredito eu) cursos que o site te sugere baseado nos cursos que você fez e nos favoritos.

Agora um exemplo do que estou sugerindo:

- Imagine que você esta, como no exemplo citado acima, na pagina do curso "Entity Linq Parte 1". Aí logo abaixo da sessão "Pré-Requisitos", tem uma sessão "Estude a seguir" com uma lista contendo os cursos "Entity Linq Parte 2", "C# parte 8: List, lambda, linq" e "Certificação C# Programming parte 7: Eventos e LINQ".

Isso ajudaria a ver que existem mais cursos sobre o assunto que você nem teria conhecimento sem pesquisar.
Além de facilitar a navegação entre cursos relacionados, tendo o "Pré-Requisitos" para ir para os mais básicos e o "Estudar a seguir" para ir para os cursos mais avançados do mesmo assunto.

**Comment by designernatan** [comment]
@Lucas3995 valeu pela sugestao!

já vou fechar essa issue pq [tem uma semelhante aqui](https://github.com/caelum/alura-funcionalidades/issues/113)

quando pegarmos esta tela para melhorarmos no futuro puxaremos sua sugestao
