### ISSUE TITLE
Grupo no discord ou no telegram

### ISSUE THREAD

**Issue by Clans1** [caelum/alura-funcionalidades#225]
Sinto falta de uma plataforma pra interagir com outros alunos e com professores de forma mais dinamica.

**Comment by designernatan** [comment]
@Clans1 valeu pela sugestao!

vou fechar essa issue pois [tem uma semelhante aqui](https://github.com/caelum/alura-funcionalidades/issues/189)

você chegou a participar de alguma imersao da Alura esses meses? Como foi a experiencia com o discord nelas ou em outras comunidades? Já utilizou o fórum?
