### ISSUE TITLE
Mobile - Controle pelo usuário de sincronizar automaticamente

### ISSUE THREAD

**Issue by luizwhite** [caelum/alura-funcionalidades#229]
### Olá!
O assunto surgiu na Issue #203 , e utilizando o mobile percebi que apenas ao trocar de aplicativo (alternar tela) e voltar no aplicativo da Alura ele já perde a sincronização e tenho que ficar clicando toda hora para atualizar 😩
Considerando o que o @DevCapu comentou, já que não é possível deixar a sincronização automática por padrão, deixo como sugestão deixar este controle com o usuário, e, por default (caso não haja interação do usuário), deixe a sincronização automática desligada.

**Comment by felipetorres** [comment]
Oi Luiz, acho interessante entender direitinho como funciona a sincronização do app:

Quando o app é aberto, **todos os 5 cursos dessa tela são sincronizados automaticamente**.
Se o aluno ou aluna tiver matriculado em 15 cursos, esses 10 cursos restantes não serão sincronizados nesse momento, somente quando ele ou ela **tocar no botão MAIS ou tocar no menu Sincronizar**.
Um outro momento onde atualizamos o progresso de um curso é ao assistir um vídeo: nesse momento o app envia essa informação para a plataforma e recebemos o novo progresso.

Fazemos isso pois é bastante comum termos alunos e alunas com muitos cursos, passando de 100. Caso carregássemos as informações desses 100 cursos ao abrir o app, demoraria bastante tempo e seria desnecessário, pois geralmente os 5 cursos mais recentes já são suficientes para a maior parte dos usos.

Então, pensando no caso onde tenho 15 cursos, para diferenciar os cursos sincronizados daqueles que ainda não foram, mudamos a cor da barra de progresso como mostrado na issue #203:
- verde: curso sincronizado
- cinza: curso não sincronizado

Pronto! Com tudo isso dito, tocar em sincronizar já seria suficiente para atualizar o progresso de todos os cursos (por isso acho que não faz muito sentido uma opção na tela de configurações).

No entanto, ao sair e voltar pro app o progresso dos cursos não deveria ser perdido. Isso é algo estranho que merece ser investigado. Consegue mandar mais detalhes pra gente em aplicativos@alura.com.br?

**Comment by luizwhite** [comment]
Faz todo o sentido, nao tinha pensado por este lado.
Porém,  seria interessante acrescentar nesse algoritmo de sincronização automática, a formação destacada também não acha?
Mas enfim, não consegui replicar esse comportamento que perdia a sincronização, se eu consegui eu mando!

Obrigado pela atenção!

**Comment by felipetorres** [comment]
O que eu disse para os cursos também se aplica para as formações.

**Comment by luizwhite** [comment]
Preciso clicar em sincronizar para aparecer as medalhinhas verdes nos cursos da formação, mesmo na formação principal

**Comment by felipetorres** [comment]
Isso porque provavelmente nessa formação existem cursos que não estão entre os 5 mais recentes. Porém, mesmo sem a medalha nós cursos, a barra de progresso da formação é atualizada?

**Comment by luizwhite** [comment]
Não fica com barrinha verde não
Tentei explicar isso na Issue citada mas não sei se me expressei direito 
Segue print de como fica assim que abro a formação ( mesmo ela sendo a minha principal)

![Screenshot_20200807-103827_Alura.jpg](https://user-images.githubusercontent.com/4944479/89651079-bb2b6280-d899-11ea-9207-26e5aecdd20e.jpg)

**Comment by felipetorres** [comment]
> Isso porque provavelmente nessa formação existem cursos que não estão entre os 5 mais recentes. Porém, mesmo sem a medalha nos cursos, a barra de progresso da formação é atualizada?

**Comment by luizwhite** [comment]
?
Independente do que está acontecendo, o que eu quis dizer como sugestão é que todos os cursos da formação destacada (a principal, em 1º) sejam sincronizados automaticamente, já que é a formação que o aluno está acompanhando e não faz sentido não ser sincronizada na minha opinião..

**Comment by felipetorres** [comment]
Entendo. Vou deixar anotado aqui pra gente pensar mais pra frente. Valeu pela discussão.
