### ISSUE TITLE
Janela flutuante para vídeos

### ISSUE THREAD

**Issue by vagnerPG** [caelum/alura-funcionalidades#23]
Olá,

Gosto de escrever os códigos junto com o professor enquanto assisto os videos, porém as vezes isso se torna um pouco irritante porque tenho que ficar trocando de abas o tempo inteiro mesmo usando Alt+Tab. 
Sugiro então uma opção para assistir o vídeo em uma janela flutuante. Ela seria ativada com um botão na parte inferior esquerda, logo abaixo da barra de duração. Ao ser clicado uma pequena janela flutuante aparece reproduzindo o vídeo, clicar e segurar possibilitam move-la para qualquer posição na tela e colocar o mouse em suas bordas possibilitam redimensiona-la. Assim ela pode ficar na tela mesmo que outro aplicativo seja aberto (como os editores usados para trabalhar os códigos) evitando que seja preciso ficar trocando de abas o tempo inteiro. 

Obrigado.

**Comment by designernatan** [comment]
oi @vagnerPG 

enquanto nao temos algo nativo, sugiro fazer o que eu faço:

uso o recurso (picture in picture - PIP) no navegador [Opera](https://www.opera.com/pt-br)
funciona com a Alura e Youtube também

se nao curtir o opera (dê uma chance!) procuraria uma extensão para seu browser

valeu pela suggest!

**Comment by designernatan** [comment]
atualizando aqui: time de desenvolvimento da alura codou o PiP e já está no ar!

![print mostrando o player de video com um destaque circular para a funcionalidade nova de PIP](https://user-images.githubusercontent.com/5431347/74935212-a4b24d00-53c6-11ea-8f1a-5eda13d7f0c0.png)



**Disponível nos browsers mais recentes**
