### ISSUE TITLE
Links de cursos na Plataforma JAVA de cursos - redireciona para alura.com.br (e não cursos.alura.com.br)

### ISSUE THREAD

**Issue by luizwhite** [caelum/alura-funcionalidades#232]
### Olá!
Não sei se alguém já relatou este caso, mas a maioria (senão todos) dos links de cursos citados dentro de alguma aula, redirecionam para **https://alura.com.br/cursoX** e não para **https://cursos.alura.com.br/course/cursoX**.
A maioria dos cursos citados desta forma são interessantes, e normalmente adiciono como favorito. Porém, para fazer isso **hoje** preciso:
1. copiar o nome do curso
2. clicar em entrar
<img src="https://user-images.githubusercontent.com/4944479/89811485-20d75300-db15-11ea-82ce-2dea70acb992.png" height="30">

3. colar o nome e pesquisar
<img src="https://user-images.githubusercontent.com/4944479/89811756-7f043600-db15-11ea-999f-f328ff62b672.png" height="30">

4. finalmente favoritar o curso (já que estou no link do curso dentro de **cursos.alura**) 
😩😩

Seria interessante atualizar esses links o quanto antes para melhorar a experiência do aluno 😃, porque se não o aluno tem que ficar caçando o curso para favoritar e conferir depois.

👍

**Comment by designernatan** [comment]
@luizwhite valeu pela sugestao!

é o ideal mesmo, essa é mais complicada: hoje tem quase 1.5k de cursos, chutando que 1/5 cite um outro curso nas atividades, dá 300 cursos que mencionam cursos

manualmente, precisaríamos ir em cada um desses 300 cursos para alterar o link para o cursos.alura :/

---

uma solução? Quando pegar esses casos que vai pra alura.com, lá em baixo tem um "já é aluno?" que direciona para o cursos.alura
![image](https://user-images.githubusercontent.com/5431347/90255956-62207900-de1b-11ea-96aa-83d661f3317e.png)


---

agora falando daqui pra frente, comentei com o time de produção para passar essa recomendação para os instrutores e instrutoras, lembrando que se vc ver algum caso assim pode ir no ícone de kebab (3 pontinhos) e sugerir a melhoria mudando a URL

**Comment by luizwhite** [comment]
@designernatan Imagino o trabalho, mas se fizerem uma força-tarefa, em uma semana resolvem ein? kkkkk
Referente ao último curso que fiz [JavaScript: Conhecendo o Browser e padrões de projeto](https://cursos.alura.com.br/course/javascript-es6-orientacao-a-objetos-parte-1), enviei a sugestão de alteração, me confirme se chegou para vocês aí.
Obrigado pela dica, sempre que tiver um link antigo vou enviar a sugestão de alteração pro link novo.
Abs
👍

**Comment by luizwhite** [comment]
@designernatan Existe alguma forma de eu verificar as sugestões que já enviei na Alura?
Porque, digamos que eu esqueci de incluir algo, ou me equivoquei, poderia cancelar essa sugestão enviada, como se fosse um ticket seila rs. Estas sugestões que citei acima foram aceitas ( :D ), mas acabei de enviar uma referente a um outro assunto e me equivoquei, só que não consigo cancelar ( se ver uma aí referente ao curso de git pode deletar haha)
