### ISSUE TITLE
Ferramenta de busca

### ISSUE THREAD

**Issue by Clans1** [caelum/alura-funcionalidades#233]
Sinto falta de uma interface onde eu possa digitar alguma coisa que eu procuro e encontrar cursos relacionados a minha busca.

**Comment by designernatan** [comment]
@Clans1 valeu pela sugestao, hoje temos a página de busca (botão azul, lupinha branca, lá em cima na esquerda no menu)

[aqui por ex pesquisei github,](https://cursos.alura.com.br/search?query=github), e além dos cursos e formações, traz posts relevantes sobre o tema pesquisado

seria isso?

**Comment by Clans1** [comment]
Sim sim, eu ja tinha visto. Por isso fechei o issue, mas obrigado pela atenção.
