### ISSUE TITLE
Nova funcionalidade, muito boa.

### ISSUE THREAD

**Issue by Caio-medeiros** [caelum/alura-funcionalidades#235]
Existir um local, como, o Discord ou alguem crie  um local para os outros poderem se comunicar, madar menssagens e até se reunirem para fazer projetos, puplicar os trabalhos para pessoas terem inspirações

**Comment by designernatan** [comment]
@Caio-medeiros valeu pela sugestao!

vou fechar essa issue pois [tem uma semelhante aqui](https://github.com/caelum/alura-funcionalidades/issues/189)

você chegou a participar de alguma imersao da Alura esses meses? Como foi a experiencia com o discord nelas ou em outras comunidades? Já utilizou o fórum para publicar trabalhos e se conectar com a comunidade Alura?
