### ISSUE TITLE
Filtro de busca por nível do curso! 

### ISSUE THREAD

**Issue by matteus-henryk** [caelum/alura-funcionalidades#236]
pelo q percebi os cursos já possuem em suas descrições o nível, minha ideia é, na hora da pesquisa o usuário possa adicionar um filtro de nível e os resultados aparecerem de forma organizada, por exemplo: faço um abusca de JavaScript com um filtro de nível básico, os resultados devem ser de acordo e na sequencia de progressão.
Quando o usuário fizer um pesquisa sem filtro, os resultados poderiam aparecer divididos e ordenados por nível e progressão de aprendizagem, assim facilitando a personalização de trilhas de estudo.

**Comment by designernatan** [comment]
@matteus-henryk valeu pela sugestao!

faz todo sentido isso, estamos vendo como melhorar a UX na busca no futuro, filtros desse tipo estão na pauta
