### ISSUE TITLE
Apresentar o total de horas aula a relação dos planos de estudo

### ISSUE THREAD

**Issue by carlosromel** [caelum/alura-funcionalidades#237]
Prezados,

Seria bem prático visualizar a carga horária somada dos planos de estudo.

https://cursos.alura.com.br/user/carlos-romel0/planos-de-estudo

Dentro da relação do plano de estudo, que a carga horária do curso também seja apresentada.

Atenciosamente,

Carlos Romel

**Comment by designernatan** [comment]
@carlosromel valeu pela sugestao!

Faz sentido algo assim! Tem algum motivo para vc precisar ver a carga horária especificamente? Vi que hoje vc tem um PDE apenas
