### ISSUE TITLE
Local para divulgar trabalhos feito, achar parceiros para trabalho de um projeto, etc

### ISSUE THREAD

**Issue by Caio-medeiros** [caelum/alura-funcionalidades#238]
Haver um local para podermos divulgar os nossos trabalhos/projetos, conviver com outros desenvolvedores e poder achar alguém para fazer um trabalho/projeto.

Podem fazer isso criando um servidor de discord ou até mesmo criarem um site próprio.

**Comment by designernatan** [comment]
@Caio-medeiros valeu pela sugestão! [Um Discord/Slack mesmo como vc sugeriu](https://github.com/caelum/alura-funcionalidades/issues/235) já resolveria esse fator social, em partes pelo menos.

O que estamos pedindo para vocês há uns dias é quando matar alguma Formação, compartilhar nas redes sociais, mostrando o que aprendeu, o que melhorou, etc, marcar os professores(as) e a Alura já para servir para este fim de portfolio.

Você chegou a participar de alguma Imersão da Alura esses meses? Como foi a experiência com o Discord nelas ou em outras comunidades? Já utilizou o fórum para publicar trabalhos e se conectar com a comunidade Alura?

**Comment by Caio-medeiros** [comment]
Boa tarde,
Eu tenho sempre estado estar ativo no fórum, pois acabo por aprender junto.

Sobre o Discord, eu sei fazer o servidor caso precisem da minha ajuda, pois
ainda tenho 13 anos, antes eu jogava muitos jogos que necessitavam de
servidores do discord por isso já tenho alguma experiência. Sendo um local
muito bom para conviver, conhecer e até fazer amizades com outros. Sendo
mais um ótimo aprendizado pois as pessoas poderiam dar o feedback do
trabalho.

**Comment by designernatan** [comment]
caio fizemos apenas em algumas imersões, ele fica ativo só durante elas

se quiser ficar sabendo das proximas só cadastrar aqui: https://www.alura.com.br/imersao

**Comment by Caio-medeiros** [comment]
Uma ótima ideia de curso que poderia levar várias pessoas a pagarem a
Altura, seria o Forex trading ou o Stocks, seria muito bom.
