### ISSUE TITLE
Espelhamento TV

### ISSUE THREAD

**Issue by pedrolog61** [caelum/alura-funcionalidades#239]
Boa tarde, 

Atualmente o app da alura consegue espelhar o video no chromecast porem quando tento espelhar na tv da como incompatível. Seria útil poder adicionar esta funcionalidade. Pois uso a tv para assistir ao curso com o computador do lado.

**Comment by felipetorres** [comment]
Você diz espelhar diretamente numa Smart TV, sem o uso do Chromecast?

**Comment by pedrolog61** [comment]
Sim, não estou conseguindo espelhar pelo app na smart tv da lg sistema op
web os
Só consigo espelhar com o chromecast.

Obrigado,

Pedro Ivo

Em dom, 16 de ago de 2020 18:18, Felipe Torres <notifications@github.com>
escreveu:

**Comment by felipetorres** [comment]
Entendi. Por hora nós não temos planos de adicionar o suporte a Smart TVs. Só suportamos o Chromecast e Apple TV. Valeu pela sugestão.
