### ISSUE TITLE
Melhorias Transmissão para TV

### ISSUE THREAD

**Issue by TinsUX** [caelum/alura-funcionalidades#24]
Olá! Utilizo muito a função de transmitir os vídeos dos cursos para a minha TV Android, para estudar em casa é muito prático ver pela TV enquanto uso o notebook para fazer na prática as aulas dadas.

Algo que acho que agregaria neste modo é:
No smartphone na tela da barra do Player, se tivesse um iframe na parte superior com o conteúdo em do texto da aula, muitas vezes esquecido.

Em alguns cursos percebi que a parte escrita do curso tinha um detalhamento melhor sobre o mesmo.
Então eu teria que ler depois de ver o vídeo na TV pelo app.

**Comment by taisbatuira** [comment]
Olá!

Sou do time de desenvolvimento dos apps da Alura. 

Você está assistindo pelo Chromecast? A sua sugestão é que mostre as transcrições na tela do mini controler do player do Chromecast? 

Obrigada.

**Comment by TinsUX** [comment]
Tais boa tarde!

No caso é uma TV Sony que possui sistema Android e um chromecast integrado.

Na tela do smartphone enquanto vejo o curso na TV, fica:

Nome do curso
Barra de tempo do curso
Velocidade do vídeo

Minha sugestão é: nesta tela do APP  no smart dar acesso a parte teórica escrita, assim ajudando na melhor absorção do curso enquanto assiste o video.



Uma outra coisa que gostaria de comentar é: no iphone, quando concluido curso eu tenho que ir no pc para responder o questionário sobre o curso para que este termine em 100% e consiga o diploma.

Ainda assim no aplicativo mostra os cursos como não concluídos

Agradeço a atenção

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: taisbatuira<mailto:notifications@github.com>
Enviado:quarta-feira, 8 de janeiro de 2020 14:17
Para: caelum/alura-funcionalidades<mailto:alura-funcionalidades@noreply.github.com>
Cc:TinsUX<mailto:fabiox81@hotmail.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [caelum/alura-funcionalidades] Melhorias Transmissão para TV (#24)


Olá!

Sou do time de desenvolvimento dos apps da Alura.

Você está assistindo pelo Chromecast? A sua sugestão é que mostre as transcrições na tela do mini controler do player do Chromecast?

Obrigada.

**Comment by taisbatuira** [comment]
Olá!

Você diz na tela de controle do Chromecast no app ne? 

O controle permite que você acesse todo o app enquanto o vídeo está tocando, ficando um mini controle na base da tela. Então isso permite que você acesse as transcrições enquanto assiste o vídeo. 

Entretanto, achamos a idéia de acessar as transcrições diretamente do controller do Chromecast super válida! Colocamos aqui para dar uma olhada, mas ainda não temos uma previsão de quando implementar. 

Muito obrigada pelo Feedback, fica de olho e mantenha o app sempre atualizado ok? 

Bons estudos!!
