### ISSUE TITLE
Container de conteúdo da Plataforma de Aulas - Espremido

### ISSUE THREAD

**Issue by luizwhite** [caelum/alura-funcionalidades#243]
### Olá!
Uma coisa que me incomoda bastante é a largura máxima de conteúdo na plataforma de aulas online ("max-width: 895.5px" na mq "min-width: 691px")
Não sei se precisaria de mais uma media query (uso notebook 14' -> 1366px), mas está sobrando bastante espaço:
<img src="https://user-images.githubusercontent.com/4944479/90442118-834dc780-e0b0-11ea-9df1-d800ff3f08de.png" height="200"/>
Se isso for complicado, a curto prazo pode-se diminuir a fonte do código nos blocos de código, estão grandes forçando a criação de uma barra de rolagem horizontal praticamente sempre, e muitas vezes acabo até clicando em alternativas erradas em exercícios porque queria clicar na barra de rolagem e sem querer clico na alternativa.

Valeu!
Abs

**EDIT**: vi que tem outra mq "min-width: 900px", porém no "theater-mode" (que eu não sei onde ativa rs), então o container sem esse modo fica com a largura pequena que nem na foto.
![image](https://user-images.githubusercontent.com/4944479/90443658-fbb58800-e0b2-11ea-8551-0bf7828a09d7.png)
**EDIT2**: vi que esse theater-mode só funciona quando tem vídeo. Ou seja, em tópicos de explicação sem vídeo e exercícios a largura máxima fica limitada conforme explicado acima.

**Comment by luizwhite** [comment]
@designernatan natan?

**Comment by tadeubarbosa** [comment]
Sinto muito falta disso também!
Quando quero, por exemplo, dividir a tela com outro programa como um editor de código, eu acabo escondendo o menu lateral e dando zoom pro vídeo se encaixar na tela.
Se tivesse uma opção pro vídeo se esticar como no youtube seria maravilhoso!

**Comment by designernatan** [comment]
oi gente, vai ter modo teatro no futuro, estamso vendo

ideia é esticar mesmo e aproveitar melhor o espaço horizontal
