### ISSUE TITLE
Bug na duração do curso

### ISSUE THREAD

**Issue by henriquehrf** [caelum/alura-funcionalidades#245]
Olá, há um pequeno bug na duração do curso da plataforma.

![image](https://user-images.githubusercontent.com/16909725/90648093-1c8ef200-e207-11ea-93d1-38e1e55fce90.png)

**Comment by designernatan** [comment]
@henriquehrf valeu pelo toque, dev team tá vendo já, obrigado!

**Comment by GesleyElois** [comment]
Corrigido!

**Comment by designernatan** [comment]
tem que tirar a master do paulo

 ![troll face](https://img.icons8.com/color/2x/trollface.png)
