### ISSUE TITLE
Montar grade de estudos

### ISSUE THREAD

**Issue by DanielaMota96** [caelum/alura-funcionalidades#246]
Olá!
Seria muito interessante ter como montarmos uma grade personalizada, com o auxílio de um calendário, para organização do plano de estudos.
Exemplos:
1° em minha formação UX coloquei em meu plano de estudos todos os cursos dessa categoria. Mas, eu gostaria de ter um controle mais objetivo e efetivo do que já fiz (com contagem de carga horária executada), e o quanto falta fazer para aquela disciplina, para aquele curso e para completar meu plano de estudos naquela formação, em carga horária, não somente em %.

2° me ajudaria MUUUUITO se conseguisse organizar dentro da plataforma uma grade com distribuição de carga horária para eu realizar durante a semana, como uma grade personalizada, com um calendário, como em um curso presencial mesmo. Por exemplo:
Seg (dia xx/xx) programadas aulas a,b,c (tot carga horária x)
Ter (dia xx/xx) programadas aulas d,e,f (tot carga horária y)

Nisso, seria legal o sistema contar essas horas e ir atualizando conforme formos concluindo. Isso ajuda bastante para organização pessoal, por incrível que pareça rsrs. Facilitaria talvez até para fazer mais de um curso ao mesmo tempo, e termos uma média de quanto tempo falta para terminar a formação.
Pessoalmente, comigo funciona muito e contribui para minha organização de estudos e aprendizado

obrigada!

**Comment by designernatan** [comment]
@DanielaMota96 valeu pelas sugestoes!

1. Lembro que outra pessoa comentou aqui no alura funcs. que seria interessante mais informações em um PDE, gosto da ideia. Tem algum motivo para vc precisar ver a carga horária especificamente? Infos como qtde de cada conteúdo hoje exibimos na página do PDE em si. [Pegando esse de exemplo,](https://cursos.alura.com.br/plano-de-estudos-excell-lfbrienze-1578442665283-p11920) 8 cursos e 1 vídeo.

2. Esse é bem interessante também, hoje estamos longe de ter um calendário assim, casa bem inclusive com esse **excelente vídeo** do Gui Silveira onde ele mostra que se organiza exatamente assim. Uma solução de contorno por hora seria usar o Google Calendar, com os eventos recorrentes daria para fazer algo assim hoje! Claro que não tão integrado e bem manual.

Lembro de ter visto um aluno que se organizada com um Trello bem simples, algo como to do / doing / done, mas ele colocava deadline em cada card (curso), outra forma interessante tbm.

Abcs!
