### ISSUE TITLE
Correção menu do usuário visualizando as formações 

### ISSUE THREAD

**Issue by brunosilvadaniel** [caelum/alura-funcionalidades#25]
Quando acessando as formações do curso as opções de usuário ficam inacessíveis :

![image](https://user-images.githubusercontent.com/42727140/71987156-6b55c180-320c-11ea-8576-de1db3e13a9a.png)

**Comment by designernatan** [comment]
valeu @brunosilvadaniel ! Vamos ver aqui o que há com esses steps aí.

**Comment by designernatan** [comment]
Corrigido! Time de front matou!
