### ISSUE TITLE
Pequeno ajuste no texto.

### ISSUE THREAD

**Issue by Fellipe222** [caelum/alura-funcionalidades#250]
Fala pessoal, tudo certo?

Estou fazendo o curso de Consulta no SQL de vocês e encontrei uma falha da tradução bem simples, mas é importante ressaltar.

Ao invés de "view" está "visão".

Sei que é bem simples mesmo, o endereço é: [https://cursos.alura.com.br/course/oracle-database-consultas-sql/task/60357](url)

Abraço!

**Comment by designernatan** [comment]
@Fellipe222 valeu pelo toque! Corrigi aqui!

lembrando que sugestões de conteúdo vc pode mandar direto pela plataforma
![](https://puu.sh/Gliwo/0148b9d197.jpg)

**Comment by Fellipe222** [comment]
Não estava ciente deste recurso Natan, pode deixar brother!

**Comment by designernatan** [comment]
fica meio escondido mesmo, precisamos deixar mais encontrável!
