### ISSUE TITLE
API - Cursos concluídos

### ISSUE THREAD

**Issue by oquealan** [caelum/alura-funcionalidades#251]
**Descreva a funcionalidade que você gostaria que tivesse na plataforma.**
- Gostaria de sugerir a criação de uma nova API pública da Alura, efetuando a busca através do username dos alunos e retornando o mesmo conteúdo de seu perfil público (exemplo: nome, ranking, cursos concluídos, url do certificado, etc). 
Acho que essa funcionalidade seria interessante para incorporar ao site pessoal, aplicações dos alunos ou até mesmo como recurso para uma das semanas de imersão produzidas pelo time da Alura.

_Muito obrigado!_

**Comment by designernatan** [comment]
@oquealan valeu pela sugestao!

indo em 'editar' no seu perfil, lá em baixo, disponibilizamos uma api com algumas dessas informações

infelizmente sem planos ainda para a aprimorarmos
