### ISSUE TITLE
Forum topics antigos - bug

### ISSUE THREAD

**Issue by luizwhite** [caelum/alura-funcionalidades#252]
### Olá!
Em tópicos antigos aparece isso no final da página:

<img src="https://user-images.githubusercontent.com/4944479/91484850-46d45580-e880-11ea-916d-103905143846.png" height="100">

**forum.topic.alert.2.weeks.old**

obs.: até quantas semanas pode responder um tópico até ele ficar bloqueado? 2 semanas mesmo?

**Comment by designernatan** [comment]
opaaa bug alert!

valeu por relatar meu caro!

são 2 semanas, tava pra mudar pra 4 ou 6 (nao lembro de cabeça)
