### ISSUE TITLE
Lista de recursos necessários

### ISSUE THREAD

**Issue by rogumo** [caelum/alura-funcionalidades#253]
Assim como tem informações dos instrutores que ministrarão os cursos de determinada formação/curso, acredito ser interessante para o aluno saber quais os recursos serão necessários para determinado curso/formação.

Ex. hipotético:
Formação PHP
Recursos necessários:
- PHP (baixar do site www.urldownload.com)
- PHP Storm (baixar versão community do site www.urldownload.com)
- MySQL (baixar do site www.urldownload.com)
- etc.

Isso pode dar uma idéia se determinado curso o aluno poderá estudar no computador do trabalho (onde muitas vezes nao possui privilégios para instalar softwares), se poderá aprender no celular/tablet ou se deverá aprender somente no computador particular.

**Comment by designernatan** [comment]
@rogumo valeu pela sugestão!

via de regra, todo curso precisa e tem essas informações nas atividades de cada curso, quando por algum motivo não subiu só pingar no fórum se fizer sentido ou direto no contato@alura.com.br pois provavelmente esquecemos mesmo

lembrando que sugestões de conteúdo vc pode mandar direto pela plataforma também:
![](https://puu.sh/Gliwo/0148b9d197.jpg)
