### ISSUE TITLE
Opção de desativar a aceleração / desaceleração do vídeo com gestos

### ISSUE THREAD

**Issue by diegopthomas** [caelum/alura-funcionalidades#254]
Seria ótimo se tivesse como desativar a função de "passar" ou "retroceder" o vídeo ao passar o dedo na tela (no app da Alura).
Motivo: se eu preciso sair da tela do do vídeo para ir para outra tela, é necessário que eu deslize o dedo no canto da tela, pra aparecer o botão "voltar". O problema é que quando eu faço isso, o vídeo passa pra frente ou pra trás, e eu acabo perdendo a referência de onde estava.

**Comment by felipetorres** [comment]
Oi @diegopthomas, provavelmente vamos tirar essa funcionalidade no app Android. Como já temos o double tap pra avançar 10s e o controle deslizante na barra inferior, talvez deslizar o dedo para avançar/voltar esteja sobrando mesmo. Faz sentido?

Obs.: não sou muito adepto de colocar uma opção no menu para isso.

**Comment by diegopthomas** [comment]
Faz todo sentido do mundo :D hehe

**Comment by felipetorres** [comment]
Perfeito. Vou anotar aqui pra discutir melhor com o time.
