### ISSUE TITLE
Permitir Alterar E-mail

### ISSUE THREAD

**Issue by francopan** [caelum/alura-funcionalidades#255]
**Problema:** Pessoas podem querer mudar seu e-mail. Dentre os motivos, podem estar a mudança de um username (para facilitar a comunicação) ou até mesmo em virtude da crescente exploração de dados por governos, onde o usuário busque por alternativas localizadas em estados neutros e criptografadas E2E.
Possivelmente essa proibição de alterar o e-mail deve-se ao sistema vincular o e-mail como uma chave para aquele usuário.

**Solução**: Manter o e-mail como valor único para o usuário. No entanto, alterar sua identificação (caso seja realizado pelo e-mail) para um ID gerado randomicamente, possibilitando assim que o valor de e-mail seja alterado e que o usuário não precise redirecionar sua caixa de e-mails antiga para a nova. Possivelmente antes de possibilitar a modificação de e-mail será necessário validá-lo.

**Comment by designernatan** [comment]
@francopan valeu pela sugestao!

levei esse ponto para o dev team refletir sobre isso tudo, ótimo pontos!

se vc precisar mudar o e-mail tenta contatar direto no contato@alura.com.br ? Explica o contexto e a situação que o time de CS tenta ajudar!

**Comment by francopan** [comment]
Olá! Vi que foi fechado. Será feito ou foi descartado?

**Comment by francopan** [comment]
Alguma resposta para essa issue?
