### ISSUE TITLE
Mobile - Bug - Formações finalizadas mostram "0/* Cursos Finalizados"

### ISSUE THREAD

**Issue by luizwhite** [caelum/alura-funcionalidades#256]
### Olá!
Notei que as formações que **finalizei** (mesmo após clicar em *sincronizar*), mostra no cabeçalho que nenhum curso foi finalizado, e na mesma tela mostra as medalhas que os cursos foram finalizados.

<img src="https://user-images.githubusercontent.com/4944479/91614968-f1b84280-e958-11ea-90a5-05757e19ad00.jpg" height="500">

**Comment by felipetorres** [comment]
Valeu, @luizwhite, anotei aqui
