### ISSUE TITLE
Algumas Formações c/ botão certificado c/ estilo quebrado

### ISSUE THREAD

**Issue by luizwhite** [caelum/alura-funcionalidades#257]
### Olá!
Acredito que o *width* não seja suficiente, está quebrando para linha debaixo.
E não entendi porque esse botão só aparece em algumas formações, porque isso acontece?

<img src="https://user-images.githubusercontent.com/4944479/91616978-4fe72480-e95d-11ea-8874-facbd76a5f64.png" height="150">

Aumentando em 5px já corrige:

<img src="https://user-images.githubusercontent.com/4944479/91617038-72793d80-e95d-11ea-9bbf-5a1748707e4d.png" height="100">

**Comment by designernatan** [comment]
@luizwhite valeu meu caro!

passei para o dev team
