### ISSUE TITLE
Minor - fonte do número de "cursos finalizados" do card de formação

### ISSUE THREAD

**Issue by luizwhite** [caelum/alura-funcionalidades#258]
### Olá!
Provavelmente a ideia é a fonte estar em negrito, no número que representa a quantidade de cursos finalizados.
Porém, quando o número tem mais de um dígito, só o primeiro digito fica em negrito.
<img src="https://user-images.githubusercontent.com/4944479/91618798-c5ed8a80-e961-11ea-85d2-ae0d2368d7fd.png" height="150">

**Comment by designernatan** [comment]
@luizwhite valeu luiz, passei para o dev team esse também!
