### ISSUE TITLE
Avaliação do curso no app

### ISSUE THREAD

**Issue by fabioomachi** [caelum/alura-funcionalidades#259]
Não achei a avaliação do curso no aplicativo e achei estranho que eu já havia finalizado todos os passos do curso e ele não aparecia como concluído. Acho que isso é até um detalhe, mas quando eu termino um curso tenho um certo toc de não ver ele como concluído e só percebi que precisava avalia-lo em um dia que eu abri para ver ele pelo notebook.
Acredito que isso não deve acontecer normalmente, pois a maioria dos cursos de vocês são técnicos e que demanda ser feito vários passos em um notebook, porém como comecei por cursos mais de gestão e não havia a necessidade de codificação comecei minha jornada somente pelo aplicativo e isso acabou me gerando alguma confusão com a conclusão do curso.

Estou usando o app no android em um galaxy S7.

**Comment by felipetorres** [comment]
Oi @fabioomachi, já estamos liberando uma atualização dos apps com essa funcionalidade de finalizar curso. É só manter o app atualizado, beleza?
