### ISSUE TITLE
Opção de salvar os vídeos do cartão de memória do celular

### ISSUE THREAD

**Issue by luciodias** [caelum/alura-funcionalidades#26]
Opção de salvar os vídeos do cartão de memória do celular

**Comment by taisbatuira** [comment]
Olá Lucio, 

essa opção já existe mas só é exibida se o app conseguir detectar o SDCard. Caso o SD não puder ser encontrado, ou o app tiver qualquer problema para acessá-lo para salvar os vídeos, ocultamos essa opção.
