### ISSUE TITLE
Bug Questões abertas

### ISSUE THREAD

**Issue by RodrigoCury** [caelum/alura-funcionalidades#260]
Estou usando o Firefox, num sistema Ubuntu 20.04.

Ao escrever uma resposta qualquer na área designada e apertar próxima aula, antes de enviar uma resposta, o browser abre uma janela secundaria perguntando:
"Suas alterações ainda não foram salvas, clique em Responder para salvá-las. Deseja ir para a próxima aula?"

ao apertar "cancelar", e em seguida apertar "responder" a ação entra em um loop e nunca envia a resposta.

apenas ao recarregar a pagina saímos do loop e podemos enviar a resposta.

**Comment by designernatan** [comment]
@RodrigoCury valeu pelo report!

passei para o dev team tentar reproduzir (aqui usei firefox/windows e não deu loop)
