### ISSUE TITLE
Vídeo trava mas áudio prossegue no celular

### ISSUE THREAD

**Issue by frock81** [caelum/alura-funcionalidades#261]
O _player_ do vídeo trava durante a exibição no meu celular.

Tenho um Samsung Galaxy S9 e tenho tentado assistir as aulas no celular. Após algum tempo, maior ou menor (parece-me aleatório) o vídeo fica com a imagem congelada, mas o áudio continua correndo.

Percebo que o celular não chega a travar, porque se eu toco na tela e deslizo para baixo o menu de configurações do aparelho o _player_ volta a reproduzir o vídeo.

Tenho usado o navegador Chrome para Android.

Como resultado, frustrado com a experiência, eu desisto de usar o produto no celular, me restando apenas o computador.

**Comment by designernatan** [comment]
@frock81 valeu pelo report!

vc já testou se no [app da Alura](https://play.google.com/store/apps/details?id=br.com.alura.mobi&hl=pt_BR) acontece isso também?

Inclusive é até mais interessante preferir o app pois uma das principais features que ele tem é poder ver o conteúdo offline, então não dependeria de conexão

**Comment by frock81** [comment]
Obrigado, @designernatan , eu não conhecia o app. Vou testar. Eu fiz um teste usando o Firefox e do tempo que eu usei (foi apenas para uma aula) não travou.
