### ISSUE TITLE
Resumir vídeo a partir do último ponto parado

### ISSUE THREAD

**Issue by emersondevelops** [caelum/alura-funcionalidades#262]
Seria interessante essa funcionalidade pois, por mais que os vídeos não sejam muito longos, às vezes precisamos parar de assistir no meio de um vídeo. Dessa forma, quando voltamos à página num outro momento para assistir, ele reinicia.

Notei também que, se passar um certo tempo pausado, mesmo não tendo recarregado a página, o restante do vídeo não é baixado e temos que recarregar a página. Ao fazer isso, o vídeo não continua mais do mesmo ponto. Ele reinicia.

O YouTube tem essa função de continuar o vídeo de onde paramos da última vez e acho bastante útil.

**Comment by designernatan** [comment]
@emersondevelops valeu pela sugestao!

estamos analisando a possibilidade para um futuro próximo de colocar essa função de continuar de onde parou

sobre o ponto 2, vou comentar com o time de produto

**Comment by emersondevelops** [comment]
Atualmente estou usando o Windows 10 - Versão 2004 (Compilação 19041.450)
Para navegação, estou usando o Microsoft Edge - Versão 85.0.564.44 (Compilação oficial) (64 bits)

**Comment by luizwhite** [comment]
> Notei também que, se passar um certo tempo pausado, mesmo não tendo recarregado a página, o restante do vídeo não é baixado e temos que recarregar a página. Ao fazer isso, o vídeo não continua mais do mesmo ponto. Ele reinicia.

@designernatan Acontece isso comigo toda vez, pq pesquiso muitas coisas durante a aula e procuro entender tudo que está sendo feito. Então sempre pauso os vídeos, e, em torno de 5 min depois o vídeo para de baixar. É como se fosse um afk kick kkk, porque o caderno para de funcionar também se não me engano

**Comment by luigiMinardi** [comment]
> Notei também que, se passar um certo tempo pausado, mesmo não tendo recarregado a página, o restante do vídeo não é baixado e temos que recarregar a página. Ao fazer isso, o vídeo não continua mais do mesmo ponto. Ele reinicia.

``MacOS Catalina 10.15.7`` usando ``Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)`` tem o mesmo problema. Se eu saio do video por algum tempo, quando eu retorno e dou play ele fica em loading infinito e eu tenho q dar "f5" (cmd + R no caso do Mac) pra recarregar a pagina.

**Comment by gssj85** [comment]
Acontece o mesmo comigo, por precaução aperto F5 quando me ausento por algum tempo, o problema é que o vídeo volta para o início.

Talvez se cada vez que desse play no video fizesse um relogin por debaixo dos panos? Posso estar falando besteira mas tenho a impressão que é o login que expira e recarregando a página ele faz a validação do login novamente.

**Comment by luigiMinardi** [comment]
> Acontece o mesmo comigo, por precaução aperto F5 quando me ausento por algum tempo, o problema é que o vídeo volta para o início.
> 
> Talvez se cada vez que desse play no video fizesse um relogin por debaixo dos panos? Posso estar falando besteira mas tenho a impressão que é o login que expira e recarregando a página ele faz a validação do login novamente.

Não sei se é o login que expira nesse caso mas sei que se você ficar mtu tempo afk a alura te desloga msm e vc tem que re-logar no site e voltar pro curso, pelo menos aqui rola isso. Talvez seja algo do player mesmo, sla talvez ele te envie os dados 1x quando vc abre a página mas n salva no cache e não re-envia clicando no play entao ele buga

**Comment by wandersonmaceds** [comment]
Oi pessoal, tudo bem? disponibilizamos ontem uma versão inicial dessa funcionalidade de continuar o vídeo de onde parou. 

É importante mencionar que ela não tem nenhuma sincronização com o aplicativo (para quem costuma usar os dois). Testem um pouco e se acharem que algo pode ser melhorado, por favor, comentem.
