### ISSUE TITLE
Gamificar a plataforma

### ISSUE THREAD

**Issue by atilasantos** [caelum/alura-funcionalidades#263]
Fala galera, tudo bom!?

Como já utilizei diversas plataformas de cursos, tais como : KodeKloud, LinuxAcademy, Pluralsight e alura, sempre senti falta de desafios entre as aulas/módulos nos cursos da Alura, os exercícios existentes hoje na plataforma não são práticos e o chamado `mao na massa` trata-se de um copy - paste do que foi abordado na aula, sei que isso tem um valor enorme para quem esta começando e não estou criticando, mas os desafios e a gamificacao dos mesmos no meu ponto de vista trariam um requinte de incentivo a conseguir sanar os desafios!

Como prêmios oriundos das gamificacoes, deixo em aberto...pois o meu foco seria termos mais exercícios com níveis de exigência um pouco maiores do que os apresentados nas aulas :)

**Comment by designernatan** [comment]
@atilasantos valeu pela sugestao e por ter trazido essas exp. suas!

precisamos melhorar o ranking/gamefication, por hora sem previsão

---

vc chegou a fazer alguma formacao? Lembra das que vc não se sentiu muito desafiado?

**Comment by atilasantos** [comment]
Ola Natan!

Ainda não finalizei nenhuma formação, a de Java esta em andamento, contudo já finalizei diversos cursos e com uma certa frequência esse sentimento surge. Obs: Não e um sentimento de que as coisas são fáceis, mas de que caso tivéssemos alguns desafios em cenários distintos do apresentado em curso, fixaríamos o conteúdo de uma forma muito melhor :)
