### ISSUE TITLE
Permitir colocar nossos planos de ensino em Destaque na nova Dashboard

### ISSUE THREAD

**Issue by kbdemiranda** [caelum/alura-funcionalidades#264]
Na nova dashboard é possível colocar a **Formação em Destaque**, mostrando os próximos cursos da formação.

Apesar das formações serem excelentes, alguns alunos preferem criar um plano de estudo, para compartilhar ou até mesmo para ter um norte um pouco mais completo de por onde seguir.

Seria interessante se fosse possível selecionar o **plano de estudo** na opção de "formação em destaque".

## Configuração do plano em destaque

![Imagem de alteração de destaque](https://pbs.twimg.com/media/Eg9LoQdXgAAgD4o?format=jpg&name=4096x4096)

## Dashboard

![Imagem da Dashboard (Beta)](https://pbs.twimg.com/media/Eg9L2onXkAEREL_?format=jpg&name=4096x4096)

## Plano de ensino

![Imagem do plano de estudos](https://pbs.twimg.com/media/Eg9MlD2XgAEJdp1?format=jpg&name=4096x4096)

**Comment by designernatan** [comment]
@kbdemiranda valeu pela sugestao! :)

faz todo sentido

estamos constantemente melhorando a dashboard beta, discutiremos aqui sobre essa possibilidade!
