### ISSUE TITLE
Minor - Tamanho pequeno de ícones em "Recomendações" 

### ISSUE THREAD

**Issue by luizwhite** [caelum/alura-funcionalidades#265]
### Olá!
Vocês devem achar que eu fico caçando bug, mas não é verdade tá kkk
Eu sem querer acho essas coisas, e acho importante reportar porque às vezes um minor leva a um bug maior em outro lugar rs

Na página de "Recomendações" se você der F5 os ícones ficam pequenos!
Mas ao entrar na página pela primeira vez, os ícones ficam normais! (ou se clicar na barra de endereço da página e der ENTER)

Segue imagem com ícones pequenos quando clicamos em F5:

<img src="https://user-images.githubusercontent.com/4944479/92278618-00a87300-eecc-11ea-9082-3cd32962354f.png" height="200">

Imagem com os ícones de tamanho correto:

<img src="https://user-images.githubusercontent.com/4944479/92278696-259ce600-eecc-11ea-9e47-bd48e7549005.png" height="200">

**EDIT:** só no Firefox está acontecendo o problema!

**Comment by designernatan** [comment]
@luizwhite valeu pelo toque!

hahah fica tranquilo, esse por ex não é muito sensivel, mas é bacana que vai diminuindo as pontas soltas
