### ISSUE TITLE
Descrição de Curso diferente do título (corrigir) e minor nos bullets

### ISSUE THREAD

**Issue by luizwhite** [caelum/alura-funcionalidades#266]
### Olá!
O curso de [ECMAScript](https://cursos.alura.com.br/course/ecmascript-novidades) está com a descrição diferente do título.. 😒

Além disso, no vídeo de introdução do curso ele diz que é vai trabalhar as novidades desde o ES6 até o "atual momento", o que também é vago..

Desisti de fazer este curso porque não está claro se vai falar de todas as novidades, ou só de algumas 🤷‍♂️

**Comment by designernatan** [comment]
@luizwhite valeu pela sugestao!

como não é exatamente uma funcionalidade, pedi ajuda para o time de conteúdo aqui, em suma estamos vendo de descontinuar esse curso num futuro próximo, conforme lançamos novos cursos de JS

mais básicos por hora, Js intro, JS OO, e JS herança e Polimorfismo

**Comment by designernatan** [comment]
ah dos bullets, alguem do time já deve ter corrigido de quando vc criou a issue pra cá
