### ISSUE TITLE
Certificado de Plano de Estudo(PE), Formação(F) ou Certificação(C) mostrando os cursos que os formam

### ISSUE THREAD

**Issue by guguilharaujo** [caelum/alura-funcionalidades#267]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.
Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

Gostaria de sugerir uma alteração na geração do certificado emitido para um Plano de Ensino (PE), Formação (F) ou Certificação (C). Por exemplo, concluí a "Certificação ITIL Foundation" e foi gerado o certificado em "https://cursos.alura.com.br/user/gutemberg.araujo/degree-certificacao-itil-foundation-2434/certificate". Nele consta a informação de 4 cursos realizados com carga horário aproximada de 50 horas. 
Postei a url deste certificado no meu perfil no Linkedin e a primeira coisa que um dos entrevistadores me perguntou foi quais eram os 4 cursos e como as 50 hs estavam distribuídas. 
A sugestão é para constar de alguma forma no certificado (se é que é possível no espaço disponível) a relação dos cursos e carga horária aproximada para os certificados de (PE), (F) e (C). Um exemplo seria: Certificação ITIL Foundation
	Certificação ITIL Foundation 1: Introdução ao gerenciamento de TI	10hs
	Certificação ITIL Foundation 2: Estratégias e Desenho de Serviços	10hs
	Certificação ITIL Foundation 3: Transição e Operação de Serviço		10hs
	Certificação ITIL Foundation 4: Melhoria Contínua de Serviço		10hs
	Posts / Artigos / Vídeos relacionados							10hs

No mais, parabéns pela excelente qualidade dos cursos e pelo profissionais da Alura.

Att.

Gutemberg Araújo
61 98455 6305

**Comment by yodog** [comment]
ou no verso, semelhante aos certificados de pós-graduação?

![Screenshot from 2020-09-10 23-42-58](https://user-images.githubusercontent.com/2393347/92847334-71b1c400-f3bf-11ea-9cef-037f8c034e92.png)

**Comment by designernatan** [comment]
@guguilharaujo valeu pela sugestao!

faz todo sentido isso, e agradecemos o elogio! :)

por hora não temos planos para mexer a fundo nos certificados, mas puxaremos essa dor quando discutirmos no futuro

---

algo que pode ajudar hoje de bate pronto é o certificado completo, no seu perfil só descer toda a tela e pegar

se precisar de algo mais pontual com relação aos certificados, pode pingar direto no contato@alura.com.br também
