### ISSUE TITLE
Definição de metas 

### ISSUE THREAD

**Issue by carolinesilva115** [caelum/alura-funcionalidades#268]
Seria legal se o usuário fosse capaz de estipular uma meta para a conclusão de um curso ou formação. 
Por exemplo, seleciono que desejo terminar a formação em Java em 3 meses, estudando 6x/semana. 
Com isso, a plataforma informa quanto tempo eu deveria gastar diariamente para completar tal curso. 

Se fosse possível, seria interessante que a própria plataforma se reorganizasse caso eu não tenha cumprido as metas diárias para que eu consiga, necessariamente, terminar em 3 meses. Outra alternativa seria a plataforma informar "como você não atingiu a meta diária, você terminará o curso em 3 meses + x dias".

Não sei se deu pra entender haha
Espero que sim.

**Comment by designernatan** [comment]
@carolinesilva115 valeu pela sugestao!

deu pra entender sim, fica tranquila! :)

gosto bastante, já fizemos testes em volta disso e acabamos nao levando pra frente, mas ainda queremos insistir em pontos em torno disso no futuro
