### ISSUE TITLE
Gerar certificados em inglês 

### ISSUE THREAD

**Issue by babiifranchin** [caelum/alura-funcionalidades#269]
Sou brasileira, vivo no exterior e participo frequentemente os cursos da Alura. 
Sei que muitos que estão em busca de uma melhora na carreira, gostariam de deixar as portas abertas para vagas no exterior. 

Logo, gostaria de sugerir que os certificados pudessem ser gerados também em inglês. O texto dos certificados é padronizado e se houvesse uma possibilidade de mudar para inglês, pelo menos o texto padrão, a funcionalidade poderia ajudar vários dos estudantes.

**Comment by designernatan** [comment]
@babiifranchin  valeu pela sugestao!

tem uma [issue semelhante](https://github.com/caelum/alura-funcionalidades/issues/6) aqui

e o [reply do paulo sobre o assunto](https://github.com/caelum/alura-funcionalidades/issues/6#issuecomment-561853046) ainda se mantém para essa questão, ok?

acredito que daria para resolver só jogando no translate (do nosso lado que digo), mas hoje o processo para isso ainda é pingar no contato@alura.com.br
