### ISSUE TITLE
Mostrar e baixar o sumário do curso

### ISSUE THREAD

**Issue by danielbr27** [caelum/alura-funcionalidades#27]
Gostaria de poder salvar o sumário do curso abrangendo tanto o título qto o subtítulo das aulas. Seria muito útil no caso de querer voltar em um tópico que vc sabe que já assistiu, mas do jeito que está fica muito complicado achar.

Na apresentação do curso já poderia ter o sumário completo. Do jeito que está hoje vc tem que clicar na aula para só então saber os tópicos abordados naquele título da aula mais abrangente.

**Comment by designernatan** [comment]
@danielbr27 obrigado pelas suggests!

algumas dúvidas:

1. o que é o sumário do curso para você? Title de cada aula + title de cada exercício/vídeo dali de dentro?
2. para saber que você já assistiu um tópico, agora dentro da aula em si, você pode saber que já viu o conteúdo quando o ícone fica verde e a barra de progresso dá uma ajuda em saber quanto que falta também
![image](https://user-images.githubusercontent.com/5431347/72086059-19349f00-32e5-11ea-8985-a4fe5437f547.png)
3. ainda sobre o sumário para saber onde você parou no curso, clicando em 'continuar curso' você vai exatamente para o último ponto de contato com o curso, quão útil é isso para você?

abcs

**Comment by Noriller** [comment]
Vou adicionar e por: nos cursos... uma pequena explicação do que é o curso... as vezes só o título não é suficiente para saber do que ele se trata...

Normalmente acompanho o que vem de curso novo... vou pelo nome e funciona bastante... mas daí vem cursos tipo: [Integração Contínua: Mais qualidade e menos risco no desenvolvimento](https://cursos.alura.com.br/course/desenvolvimento-software-integracao-continua) e eu não faço a mínima ideia do que é e se seria interessante para mim ou não.

**Comment by designernatan** [comment]
@Noriller tá na fila uma melhoria para resolver essa questao, valeu!
