### ISSUE TITLE
Formação contendo cursos desabilitados. 

### ISSUE THREAD

**Issue by mahhmtra123** [caelum/alura-funcionalidades#270]
Olá, Estou fazendo curso de Formação de UX Designer e um dos cursos está desabilitado, porém ainda sim dando para fazer. 
Quando clico no curso, aparece uma mensagem escrita que o curso existe uma nova versão. 
Como possui uma nova versão comecei a fazer, e pensei que ele ia substituir, o curso presente na formação. 
o problema: terei que fazer um curso que já foi desabilitado e existe uma versão mais atualizada para conseguir concluir a formação. 
a solução: substituir o curso na parte de formação ou fazer a contagem independente se estou estudando no curso desabilitado ou no novo.

**Comment by designernatan** [comment]
@mahhmtra123 valeu pela sugestao!

pinguei o time de conteudo sobre, pode ir fazendo os cursos da formacao normalmente pois quando ela atualizar seu progresso ja vai estar adiantado nessa nova versão
