### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by JosimarBazilio** [caelum/alura-funcionalidades#271]
Todas as ferramentas de programação tem um tema escuro, ai quando estou desenvolvendo algo e retorno para a pagina da Alura a diferença de cor incomoda muito, entendo que exista todo um problema de design mas realmente ter uma opção dark ajudaria muito.

**Comment by designernatan** [comment]
@JosimarBazilio valeu pela sugestão!

[falei mais sobre ela aqui nessa outra issue](https://github.com/caelum/alura-funcionalidades/issues/116)

depois vc pode dar um salve por lá? Perguntei umas coisas que podem ajudar a gente a priorizar uns pontos
