### ISSUE TITLE
Certificado completo seleção de cursos 

### ISSUE THREAD

**Issue by RafaVolner** [caelum/alura-funcionalidades#272]
Na plataforma da Alura há uma área em que posso solicitar um certificado completo com todos os cursos que fiz, seria muito interessante se pudesse fazer uma seleção de quais cursos quero colocar na lista para poder criar certificados mais específicos para determinadas vagas de trabalho.

**Comment by designernatan** [comment]
@RafaVolner valeu pela sugestao!

quando pegarmos essa parte dos certificados para melhorarmos pontuaremos isso, sem previsão por hora

aproveitando: pode me dar um exemplo mais preciso de algo que você passou recentemente que algo assim ajudaria?
