### ISSUE TITLE
Combo de aula estar no topo e não embaixo

### ISSUE THREAD

**Issue by amanrodrigues87** [caelum/alura-funcionalidades#273]
Nos ambientes de curso, o combo que contém as aulas fica tão embaixo no menu da esquerda que é necessário dar um scroll para chegar nele. Essa usabilidade é bem ruim quando vc quer consultar algo específico do curso, dá até um desânimo para falar beeem a verdade. Essa imagem que anexei exemplifica: 

![image](https://user-images.githubusercontent.com/69588623/92808384-14534e00-f392-11ea-8488-f3d9ad7517b7.png)

Eu já concluí o curso e quero tirar dúvidas em algumas das aulas, mas para poder escolher as aulas eu preciso usar (através do teclado) o scrollbar CINCO VEZES. E isso seria muito mais prático e agradável se esse combo já estivesse em cima e eu n precisasse descer nada... na segunda imagem (circulada em azul) eu sugiro um local para este combo.

![image](https://user-images.githubusercontent.com/69588623/92808858-7a3fd580-f392-11ea-801a-84d272f9fb8f.png)

É isso, obrigada.

**Comment by designernatan** [comment]
@amanrodrigues87 valeu pela sugestao!

coincidentemente estamos fazendo isso nesse momemto, essa melhoria deve entrar num futuro próximo então ok?

**Comment by amanrodrigues87** [comment]
Ebaa!! Que maravilha!! Obrigada:)

Em seg, 14 de set de 2020 às 09:33, Natan Souza <notifications@github.com>
escreveu:

**Comment by designernatan** [comment]
@amanrodrigues87 já viu lá? :)

depois dá um feedback por favor?

**Comment by amanrodrigues87** [comment]
Ja vi sim! Antes de ver sua msg e adorei a surpresa rss ficou ótimo! Mto
obrigada!!

Em ter, 29 de set de 2020 às 15:24, Natan Souza <notifications@github.com>
escreveu:
