### ISSUE TITLE
Campo para pesquisar tópicos no fórum

### ISSUE THREAD

**Issue by carolinesilva115** [caelum/alura-funcionalidades#274]
Olá! 
Poderia haver um campo de pesquisa para encontrar tópicos dentro do fórum.
Isso tornaria a vida do aluno mais prática, pois encontrando uma dúvida que já foi respondida, não teríamos que esperar a resposta de alguém.
Além disso, evitaria perguntas repetitivas dentro  da plataforma.

**Comment by designernatan** [comment]
@carolinesilva115 valeu pela sugestao!

o forum já conta com uma busca com essa finalidade:
![image](https://user-images.githubusercontent.com/5431347/93087553-1a397f80-f66f-11ea-9c49-9aa8994d753a.png)

estamos melhorando a eficiencia dessa busca, sem prazos infelizmente
