### ISSUE TITLE
Modo escuro dentro de toda a plataforma

### ISSUE THREAD

**Issue by PHCMorais** [caelum/alura-funcionalidades#275]
Uma funcionalidade que eu gosto muito é o modo escuro enquanto estamos dentro do curso, mas eu acharia muito interessante se tivesse o modo escuro para todo o site. Para pessoas como eu que usam o computador em ambientes escuros, isso faz uma diferença gigante!

**Comment by designernatan** [comment]
@PHCMorais valeu pela sugestao!

enquanto não sai o dark mode na plataforma inteira [o henrique deu a sugestao de usar uma extensao para isso](https://github.com/caelum/alura-funcionalidades/issues/156#issuecomment-632410492), ideal é que a alura já tenha internamente, mas é uma solução de contorno para resolver o problema de imediato

tambem sou #TemDarkMode, uso em todo lugar que permite
