### ISSUE TITLE
Após marcar uma resposta como solução, é importante conseguir desmarcar e escolher outra resposta

### ISSUE THREAD

**Issue by nunesjessica44** [caelum/alura-funcionalidades#276]
marquei uma resposta como solução e percebi que era a resposta incorreta, porém não tem a funcionalidade de desmarcar e marcar novamente em outra resposta.

**Comment by designernatan** [comment]
@nunesjessica44 valeu pela sugestao!

faz todo sentido, quando pegarmos o forum para melhorar a UX discutiremos sobre isso
