### ISSUE TITLE
Exibir no aplicativo para celular quando houver uma nova versão de um curso

### ISSUE THREAD

**Issue by davialexandre** [caelum/alura-funcionalidades#277]
Iniciei o curso "React parte 1: Componentes reutilizáveis para sua webapp" no aplicativo para celular e, após concluir alguns capítulos, passei para o computador. Para minha surpresa, no computador existe uma mensagem na barra lateral informando que existe uma versão mais atualizada do mesmo curso!

Fiquei extremamente frustrado em ter gastado tempo em um curso desatualizado!!!!

Eu até entendo a razão para manter versões antigas disponíveis, mas acredito que elas não deveriam ser oferecidas para quem nunca iniciou o curso. No meu caso, eu pesquisei por "React" e esse foi o primeiro resultado.

Além disso, seria legal ter informações importantes como essa exibidas em todas as plataformas.

**Comment by designernatan** [comment]
@davialexandre valeu pela sugestao e pelo toque!

vou pontuar isso com o time de produto, falhamos em pegar esse tipo de informacao e colocar no ecossistema todo de fato

para entender melhor, vc fez a busca no app ou no site?

**Comment by davialexandre** [comment]
Fiz a busca pelo aplicativo. 

Acabei de testar novamente e reparei que o curso mais atualizado nem aparece nos resultados:

![Screenshot_20200914-142530_Alura.jpg](https://user-images.githubusercontent.com/388373/93118221-53391a80-f696-11ea-8dc5-0c08cb4b30c8.jpg)

**Comment by designernatan** [comment]
@davialexandre pode fazer um teste depois?

clica em 'sincronizar' e me fala se o curso mais novo aparece?

testando aqui aparece 10 cursos de react, entre novos e antigos

**Comment by davialexandre** [comment]
Acabei de testar aqui e após sincronizar aparecem só os novos ![Screenshot_20200914-185724_Alura.jpg](https://user-images.githubusercontent.com/388373/93142400-4fb88a00-f6bc-11ea-85f1-db15cc8d9ac8.jpg)
