### ISSUE TITLE
Resumo final de tudo ensinado no curso

### ISSUE THREAD

**Issue by lucasspra** [caelum/alura-funcionalidades#278]
Conforme avançamos nas aulas, é comum mostrar um resumo com tudo que foi ensinado na última atividade.

Seria interessante se ao final do curso ficasse disponível uma página que contém um resumão final com todo o conteúdo desses resumos para consulta posterior.

**Comment by designernatan** [comment]
@lucasspra valeu pela sugestao, passei para o time de conteúdo!
