### ISSUE TITLE
Tamanho do vídeo na tela

### ISSUE THREAD

**Issue by STEFANOVIVAS** [caelum/alura-funcionalidades#279]
Acho que seria interessante termos um tamanho intermediário do vídeo na tela de aula. Atualmente temos a opção de tela cheia e uma opção default. Acredito que seja comum em alguns momentos escutar/ ver as aulas enquanto executamos as linhas de código. Quando estamos em tela cheia, a alternância entre as janelas fica um pouco demorada. Talvez seja interessante termos uma tela default maior, para que seja possível enxergar as linhas digitadas pelo professor no vídeo, sem a necessidade de acionar a tela cheia.

**Comment by designernatan** [comment]
@STEFANOVIVAS valeu pela sugestao!

um modo teatro está nos planos futuros, pra resolver isso de ver a aula enquanto coda uma sugestão é usar o modo picture in picture, é o botão do lado do fullscreen

pode testar uns dias e me falar aqui depois se ele funciona pra você?
