### ISSUE TITLE
Poder refazer os exercícios

### ISSUE THREAD

**Issue by danielbr27** [caelum/alura-funcionalidades#28]
As vezes vc fica um tempo sem ver um curso e quer relembrar o que foi dado refazendo os exercícios. Porém, uma vez respondido, se vc voltar, as resolução (certo/errado) fica salvo.

A sugestão é que tenha uma forma de esconder a resposta para refazer ou gerar um caderno de exercícios separadamente. Algo semelhante ao que é feito no Qconcursos e no Tecconcursos.

**Comment by sergiolopes** [comment]
Oi Daniel, obrigado pela sugestão. Outras pessoas já citaram algo parecido. Estamos entendendo os cenários pra eventualmente atacar esse no futuro. Não temos planos de curto prazo para implementar, porém.
