### ISSUE TITLE
Adição ao plano de estudos

### ISSUE THREAD

**Issue by mknparreira** [caelum/alura-funcionalidades#280]
Olá, gostaria de sugerir uma nova funcionalidade ao **plano de estudos**. 

Vídeos do Alura+, podcasts do Hipsters e artidos da Caleum poderem ser salvos no meu **plano de estudo**. Acho que seria uma boa adição. Se possível vídeos do Alura+ como prioridade. 

Do mais, a plataforma é espetacular!

**Comment by designernatan** [comment]
@mknparreira valeu pela sugestao e elogio!

hoje nao tem um atalho igual na pg de curso, mas vc pode fazer isso copiando a URL do alura+/podcast/etc e colocando lá no seu PDE

![image](https://user-images.githubusercontent.com/5431347/93985281-374f0c00-fd5b-11ea-93fd-91fd9fd65c32.png)
