### ISSUE TITLE
Voltar para a pagina inicial do curso após a conclusão do mesmo

### ISSUE THREAD

**Issue by m4rc05-34t15t4** [caelum/alura-funcionalidades#281]
Voltar para a pagina inicial do curso após a conclusão do mesmo, pois, toda vez que concluirmos um curso, nos redireciona para o dashboard. Seria melhor ir para a pagina inicial do curso para podermos gerar o Certificado do mesmo. Ou já abrir a página do certificado

**Comment by designernatan** [comment]
@m4rc05-34t15t4 valeu pela sugestao

era para estar indo para a pg do curso mesmo viu, me passa o link do seu perfil da alura? Precisamos disso para investigar se é algo pontual ou outra coisa

**Comment by m4rc05-34t15t4** [comment]
https://cursos.alura.com.br/user/m4rc0534t15t4
________________________________
De: Natan Souza <notifications@github.com>
Enviado: quarta-feira, 23 de setembro de 2020 05:09
Para: caelum/alura-funcionalidades <alura-funcionalidades@noreply.github.com>
Cc: Marcos Batista <mbsj2007@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [caelum/alura-funcionalidades] Voltar para a pagina inicial do curso após a conclusão do mesmo (#281)


@m4rc05-34t15t4<https://github.com/m4rc05-34t15t4> valeu pela sugestao

era para estar indo para a pg do curso mesmo viu, me passa o link do seu perfil da alura? Precisamos disso para investigar se é algo pontual ou outra coisa
