### ISSUE TITLE
Melhorias no Plano de Estudo

### ISSUE THREAD

**Issue by clakrall** [caelum/alura-funcionalidades#282]
Ajudaria muito ter a opção de adicionar todos os cursos de uma formação, ou adicionar a própria formação. A idéia é montar um plano que engloba mais de uma formação;

Outra melhoria seria disponibilizar a quantidade de horas do plano de estudos. Ex: Total de horas, porcentagem de conclusão do plano de estudo etc

**Comment by designernatan** [comment]
@clakrall valeu pela sugestao!

hoje rola colocar uma formacao inteira no plano de estudos, ele inclui não só os cursos mas todo o conteúdo extra e curado como podcasts, lives, etc.

inclusive vc pode fazer um PDE só com formacoes

---

esses dados do PDE fazem sentido e estarão na pauta quando pegarmos para melhorar essas telas, por hora sem previsão
