### ISSUE TITLE
Sugestão do Caderno Alura

### ISSUE THREAD

**Issue by HenriqueMeza** [caelum/alura-funcionalidades#283]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

Poderia ter a opção de download do caderno, para que seja possível ler em pdf, word, etc. 
Opção de abrir em janela para facilitar a leitura/escrita
Opção de "sumario" para separar em capítulos, títulos, subtítulos e tópicos

**Comment by designernatan** [comment]
@HenriqueMeza valeu pelas sugestoes!

1. de fazer o download está no roadmap de feature, sem previsão por hora
2. janela separada é algo que outros alunos comentaram que seria uma boa, como o modo PiP do vídeo
3. sumário enquanto não estudamos algo assim, você pode ir usando markdown no caderno mesmo que manualmente para se suportarmos isso no futuro já ficar organizado

valeu mesmo pelas sugestoes!

**Comment by langaia** [comment]
@designernatan o Markdown não está funcionando no caderno. Acabei de testar.
Se o markdown funcionasse já seria uma mão na roda.
(mesmo sem download ou PiP).

**Comment by sahslima** [comment]
Pessoal, tudo bem?

Estamos revendo alguns pontos sobre o caderno (markdown, organização e download do conteúdo, etc...), vou fechar a issue por enquanto, mas assim que tiver novidades sobre essa parte, aviso por aqui.

Um abraço!
