### ISSUE TITLE
Pontos ao finalizar um vídeo

### ISSUE THREAD

**Issue by Rafa-Denlavor** [caelum/alura-funcionalidades#284]
Acho que seria mais interessante se a cada vídeo assistido ganhássemos 50 pontos, pois há poucos exercícios para gerar pontos e muitos vídeos para assistir (por mais que a maioria seja de curta duração).

**Comment by designernatan** [comment]
@Rafa-Denlavor valeu pela sugestao!

precisamos melhorar o ranking/gamefication, por hora sem previsão
