### ISSUE TITLE
Categoria exclusiva para Criação/Desenvolvimento de Games

### ISSUE THREAD

**Issue by Rafa-Denlavor** [caelum/alura-funcionalidades#285]
Seria interessante haver uma categoria especifica para o Desenvolvimento de Games, pois muitas pessoas ficam um pouco perdidas de como entrar no mundo de criação de games. Quem sabe adicionar cursos sobre o Pygame, CryEngine, Roblox e transferir cursos como o do Unity para essa categoria.

**Comment by designernatan** [comment]
@Rafa-Denlavor valeu pela sugestao!

passei para o time de conteúdo, por hora uma categoria focada em game dev não está nos planos de curto prazo
