### ISSUE TITLE
Novo posicionamento do caderno nas aulas e dark mode

### ISSUE THREAD

**Issue by luigiMinardi** [caelum/alura-funcionalidades#286]
Antes o caderno ficava aparecendo em cima em um lugar fácil de ver enquanto o botão de aula atual ficava no final pra vc mudar a aula que está vendo. No momento o caderno ta no finalzinho depois inclusive do botão de voltar pra dashboard.

Eu não gostei muito de ter o caderno no final visto que ele é bastante usado independente de se você está no primeiro video da aula ou no ultimo. Ter que fazer o scroll de tudo pra chegar nele pode fazer com que ele acabe esquecido por muitos fora que torna menos pratico o acesso a ele.

No mais eu gostei do dark mode apesar de ter estranhado um pouco já que ele redimensiona o tamanho das coisas pra um diferente do usado no light mode.

**Comment by designernatan** [comment]
@luigiMinardi valeu pelas sugestoes!

futuramente vamos melhorar ainda mais a tela e ver como tratar melhor o caderno

do dark mode, o que exatamente muda o tamanho? Como alteramos (em teoria) somente as cores não deveria ter batido em algum width/height/font-size

**Comment by luigiMinardi** [comment]
> do dark mode, o que exatamente muda o tamanho? Como alteramos (em teoria) somente as cores não deveria ter batido em algum width/height/font-size

A caixa de códigos tem quebra de linha no dark-mode (oq eu preferi inclusive) já no light-mode tem a barra de rolagem horizontal pra vc ir até o infinito ler aquela linha de código string com um parágrafo.

A caixa de códigos do dark-mode tem bordas arredondadas enquanto a do light-mode tem bordas pontudinhas

Se não me engano é a quebra de linha que faz as coisas ficarem parecendo maiores no dark-mode mas vou conferir melhor depois e te falo.
