### ISSUE TITLE
Dark mode, não está dando pra ler textos selecionados

### ISSUE THREAD

**Issue by luigiMinardi** [caelum/alura-funcionalidades#287]
Como da pra perceber no print abaixo não está dando pra ler os textos selecionados quando usamos o dark mode.
![Screenshot 2020-09-30 at 10 25 19](https://user-images.githubusercontent.com/53359163/94661483-66d7b880-0307-11eb-84a4-4c00097d6611.png)
mais especificamente não da pra ler o texto explicando o porque você marcou a resposta correta (ou errada)
![Screenshot 2020-09-30 at 10 33 04](https://user-images.githubusercontent.com/53359163/94662358-92a76e00-0308-11eb-88b6-0b34c815dabb.png)
(testei fora e parece q é só isso que ta difícil de ler msm, testei a resposta errada pra ver se daria o msm problema e o "olho" pra abrir as respostas que você não marcou e **todas as descrições estão com esse problema**)
texto sem nada selecionado abaixo:
![Screenshot 2020-09-30 at 10 32 17](https://user-images.githubusercontent.com/53359163/94662544-d4d0af80-0308-11eb-84ab-9f20f5fc6b58.png)

**Comment by designernatan** [comment]
@luigiMinardi valeu pelo report!

me fala seu OS, browser e versoes deles?

usando windows+opera (webkit) parece ok
![image](https://user-images.githubusercontent.com/5431347/95213049-c2e98380-07c4-11eb-95e5-15d830db0bb1.png)

**Comment by luigiMinardi** [comment]
> @luigiMinardi valeu pelo report!
> 
> me fala seu OS, browser e versoes deles?
> 
> usando windows+opera (webkit) parece ok
> ![image](https://user-images.githubusercontent.com/5431347/95213049-c2e98380-07c4-11eb-95e5-15d830db0bb1.png)
> 

MacOS Catalina 10.15.7

Google Chrome 85.0.4183.121 (Official Build) (64-bit)

Brave 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)

**Comment by sahslima** [comment]
Oi, @luigiMinardi! Tudo bem?

Realizamos a correção. ;)

Desculpe a demora no retorno. 

Qualquer outra dificuldade, avise-nos.

Um abraço!
