### ISSUE TITLE
Modo Noturno

### ISSUE THREAD

**Issue by lincolnjohn** [caelum/alura-funcionalidades#288]
Parabéns pela disponibilização da funcionalidade noturno nas aulas, acho que seria interessante também disponibilizar na página principal, melhorando a experiência do usuário.

**Comment by designernatan** [comment]
@lincolnjohn valeu pela sugestao! Estamos de olho para que no futuro tenha dark mode na alura inteira, como acontece nos aplicativos de Android e iOS também

[falei mais sobre ela aqui nessa outra issue](https://github.com/caelum/alura-funcionalidades/issues/116)

depois vc podem dar um salve por lá também
