### ISSUE TITLE
Definição de nomenclaturas

### ISSUE THREAD

**Issue by vinnom** [caelum/alura-funcionalidades#289]
Hoje, temos diversas "formações disponíveis". Oriento bastante meus estudos nessas formações, pois é mais simple definir um caminho a seguir.

O problema que vejo hoje em dia é que algumas formações não possuem projetos associados, sendo que uma das definições utilizadas (como [aqui no FAQ](https://suporte.alura.com.br/article/202-qual-e-a-diferenca-do-certificado-de-participacao-para-o-certificado-de-avaliacao-de-projeto)) é a possibilidade de submeter projetos para que os instrutores avaliem. 

Não sei se a meta é estabelecer projetos futuros para cada formação, mas se não for o caso, acredito que seria bacana distinguir o que é uma Formação (contém projeto associado) e o que é uma outra forma de agregar cursos sem possuir um projeto (exemplo  "Testes Automatizados no Android").

**Comment by designernatan** [comment]
@vinnom valeu pela sugestao!

arrumei o faq aqui, antigamente tinha umas 6 formações, um projeto para cada, hoje expandimos as formações

estamos vendo como melhorar ainda mais a parte de projetos, projetos de outras áreas estão na pauta, porém sem previsão por hora
