### ISSUE TITLE
Mostrar a classificação geral no ranking

### ISSUE THREAD

**Issue by danielbr27** [caelum/alura-funcionalidades#29]
Gostaria de ver minha classificação no ranking geral ao invés de >10.000. O ranking é um estímulo a mais para medir a evolução e a dedicação, principalmente para quem é competitivo, estimula estudar mais e resolver mais exercícios para ver o nome subindo no ranking.

**Comment by designernatan** [comment]
@danielbr27 

essa parte do ranking precisamos dar uma boa melhorada, não só no ranking em si mas todo o sistema de pontuação também

obrigado pela suggest!
