### ISSUE TITLE
Certificados de Formação faltando atividades

### ISSUE THREAD

**Issue by vinnom** [caelum/alura-funcionalidades#290]
Estou checando os meus certificados de Formação (nomeadamente Formação Java e Formação Android) e tenho algumas atividades faltando. O que é estranho, pois segui as formações certinho. 

Na Formação Android, falta apenas 1 atividade e na Formação Java, são 23! 

Bom, no caso, a minha sugestão seria de ter uma forma fácil de encontrar o que está faltando para concluir 100%. Talvez um botão no card de formação (seria bacana se o certificado fosse atualizado quando as atividades restantes forem concluídas, não sei se isso já acontece).

**Comment by designernatan** [comment]
@vinnom valeu pela sugestao!

hoje qnd vc conclui um **curso** e falta alguma atividade apontamos quais faltam, faz sentido o mesmo fluxo para as formações
