### ISSUE TITLE
Bug player de vídeo da plataforma

### ISSUE THREAD

**Issue by vinicius058** [caelum/alura-funcionalidades#291]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.
Ola, fui realizar minha aula hoje porém o player de vídeo está com um bug.
A tela fica piscando, como se estivesse pulando frames. Além de aparecer uma tela verde as vezes.

Isso ocorreu no Google Chrome, então testei no Mozilla Firefox e a mesma coisa aconteceu. No internet explorer o vídeo nem rodou (mas acredito que seja alguma limitação do navegador).

Não sei se ocorre em outros módulos, mas comigo ocorreu nas aulas 2 e 3 do módulo de Angular parte 1: fundamentos

**Comment by designernatan** [comment]
@vinicius058 valeu por já ter trazido as informações pra gente!

**talvez** seja o driver da placa de vídeo ou codec 🤔 do seu PC

tenta atualizá-los para ver se resolve, primeira vez que pegamos algo assim na alura

**Comment by designernatan** [comment]
perguntei para algumas pessoas aqui do time, outras coisas que **podem** ser:

- app relacionado a video instalado no windows/mac e está dando pau
- extensoes instaladas dos browsers (tentaria desativa-las e ver se rola)
