### ISSUE TITLE
Posicionamento do ícone do modo noturno

### ISSUE THREAD

**Issue by daniloherdy** [caelum/alura-funcionalidades#292]
Boa Dia

Uma coisa que percebi é que quando a barra lateral da página de aula  está minimizada, o ícone do botão do modo noturno, fica desalinhado. Não sei se isso é devido a resolução do meu monitor (2560 x  1080).
Sei que é um detalhe muito simples, mas resolvi reportar a questão.

![image](https://user-images.githubusercontent.com/6573254/95339193-30131c80-088a-11eb-868c-244ed93696cb.png)

**Comment by sahslima** [comment]
Bom dia, @daniloherdy. Tudo bem?

Obrigada pelo report, repassamos para o nosso time de desenvolvimento e aviso por aqui quando retornarem.

Um abraço e boa semana!

**Comment by sahslima** [comment]
Corrigimos, @daniloherdy! ;)
