### ISSUE TITLE
Implementar o descritivo no podcast web

### ISSUE THREAD

**Issue by leanpina** [caelum/alura-funcionalidades#293]
Normalmente ouço ao podcast do "Hipster Ponto Tech" pelo agrgador do Spotify. No entanto hoje como tive uma folga no trabalho e estava na frente do computador escolhi ouvir pela web entrando na Alura, no caso o episódio '#221 (https://cursos.alura.com.br/hipsterstech-guia-do-iniciante-em-data-science-hipsters-ponto-tech-221-a656?utm_source=gnarus&utm_medium=timeline).

Pra minha surpresa não encontrei o descritivo que normalmente fica disponível no spotify.

Acredito que facilitaria muito a presença do descritivo apontando para os contatos dos participantes e com os links sugeridos na mesma.

**Comment by sahslima** [comment]
Olá, @leanpina! Tudo bem?

Obrigada pela sugestão, já repassamos para o nosso time de Produto. ;)

Um abraço.

**Comment by yuriems** [comment]
Tenho esse mesmo problema. Toda vez que uma formação indica um podcast e você clica pra ouvir, não aparece a descrição e nem os links sugeridos. Você tem que abrir o site do Hipsters (https://hipsters.tech/) e procurar pelo episódio. Não é o método mais acessível.

**Comment by designernatan** [comment]
pessoal, está no backlog, sem datas por enquanto, mas é algo que vamos atacar num futuro próximo

falando como ouvinte aqui: escuto o layers-ponto-tech e sinto falta do texto também

assim que tivermos novidades atualizamos aqui
