### ISSUE TITLE
Opção de remover um curso do dashboard

### ISSUE THREAD

**Issue by cabralpriscila** [caelum/alura-funcionalidades#294]
Seria bacana ter como remover o curso do dashboard porque às vezes a gente só inicia pra ver como é o conteúdo, mas não quer continuar o curso e acaba "poluindo" o dashboard e faz a gente se perder e focar no que importa.

**Comment by sahslima** [comment]
Oi, @cabralpriscila! Tudo bem? 

Boa notícia: nós temos essa funcionalidade. :D

Para **remover um curso** do seu dashboard, você deve entrar no curso em questão, clicar em "**Outras ações**" > "**Sair do curso**".

Coloquei um print abaixo para mostrar:
![image](https://user-images.githubusercontent.com/59886589/97179583-be870980-1777-11eb-87d8-15b4259a3b38.png)

Qualquer outra sugestão, dúvida ou dificuldade, avise-nos! 

Um abraço.
