### ISSUE TITLE
Monte seu exemplo: "Let's Code". Programação Full Cycle, de ponta a ponta

### ISSUE THREAD

**Issue by Noriller** [caelum/alura-funcionalidades#295]
Uma coisa que eu acho que falta é a integração entre os vários cursos presentes.
Em qual sentido? Uma coisa é aprender os cursos em separado, e nisso a Alura é excelente.

O problema que eu comecei a encontrar agora é: 
- como integrar o front que eu quero com o back que eu quero?
- como integrar o back com o database escolhido?
- como é usar a linguagem se eu usasse testes (e/ou TDD)?
- opções mais específicas, por exemplo, usar ou não ORM?
- como eu faço o deploy (tomcat, imagem, docker... google, amazon, azure)?
- como settar uma entrega contínua?

Então a sugestão é:
Uma opção de "escolher" como você quer montar seu exemplo e então acompanhar os vários professores usando as linguagens para montar o projeto exemplo.

O projeto exemplo poderia ser um só (ou vários no futuro): bytebank? alurapic? uma mescla deles? outro?
Com certeza precisaria ter CRUD, talvez manipular arquivos... mostrar tabelas? campos de pesquisa?

Com certeza os vídeos deveriam ser feitos especialmente para isso... Mas no final, independente do que foi escolhido, o "produto final" seria o mesmo.

A interface poderia ser, por exemplo, algumas "caixinhas" onde você escolheria o que gostaria ou não de utilizar.
(E isso já ajudaria muito o aluno já que no começo sofre por não saber o que fazer com aquilo que normalmente faz só em localhost. E pessoalmente, eu ainda sofro um pouco com isso)
Conforme o que escolheu, seria montado uma playlist com uma ordem lógica que pularia de uma linguagem para outra conforme necessário.
Os cursos seriam, obviamente, requisitos, já que não necesariamente seria um curso a fundo com todos os exemplos como é normalmente, apenas a aplicação dos conhecimentos. (Podendo inclusive, entre as partes direcionar o aluno aos cursos/módulos relevantes) e como sempre, dando a opção de download do projeto a cada etapa.

Começando, se seguiria a ordem que, independente das linguagens selecionadas, teria os vídeos seguindo sempre "os mesmos passos" (ou os passos necessários, seja mais ou menos, que talvez variaria as linguagens e interações entre elas).

O que posso pensar de exemplo é: 

- Ex1: Node, React, mySQL Sass, Docker, Google. 

> Começaria criando uma api base que só retorna alguma coisa.
> No React se criaria uma página base que em algum lugar chama a api.
> Criaria um arquivo base no Sass.
> Criaria uma DB mySQL e chamaria no Node.
> No React se criaria as páginas e chamadas.
> Pularia pro node criando as api das chamadas.
> No meio disso pulando no mySQL criando as tabelas e o que fosse necessário.
> Depois de tudo terminado se começaria a ver para montar a imagem.
> Finalmente o deploy pelo Google.

- Ex2: Kotlin+SpringBoot, Angular, Mongo, kubernets, Azure.

> Começaria criando uma api base que só retorna alguma coisa.
> No Angular se criaria uma página base que em algum lugar chama a api.
> Criaria uma db no mongo e chamaria no Kotlin.
> No Angular se criaria as páginas e chamadas.
> Pularia pro Kotlin criando as api das chamadas.
> No meio disso pulando no mongo criando as coleções e o que fosse necessário.
> Depois de tudo terminado se começaria a ver para montar a imagem.
> Finalmente o deploy pelo Azure.

Dependendo do que fosse utilizado, com certeza precisaria de mais ou menos passos e isso poderia ficar bem dividido, mas de qualquer forma acredito que seria possível escolher o que quer e retornar uma lista da maneira que pediu.

Isso significaria que após realizar os cursos das linguagens, o aluno poderia então ir até o "Let's Code", ver, acompanhar e fazer junto um projeto do começo ao fim (se ele quiser do começo ao fim, ou então só partes disso) que completaria o aprendizado de ponta a ponta, completando o "full cycle".

**Comment by sahslima** [comment]
Oi, @Noriller. Tudo bem?

Atualmente possuímos a funcionalidade de **criação de planos de estudos**, onde você consegue criar uma trilha personalizada para guiar seu aprendizado. Para criar um guia com conteúdo personalizado e definido por você, basta clicar em **seu nome** > **Meus planos de estudo** > **Novo plano**:
![image](https://user-images.githubusercontent.com/59886589/97194572-0f532e00-1789-11eb-8c5b-0227a098f5ef.png)

Nesse mesmo local você consegue definir se será um plano **público** (onde mais pessoas podem visualizar e seguir como referência de estudo) ou **privado** (onde só você consegue visualizar a trilha).

De qualquer modo, essa função ainda não contempla esse viés de projeto/avaliação sugerido por você. 

Anotamos a sugestão e ficará no nosso radar para futuras melhorias da plataforma.

Obrigada por compartilhar! :D

Um abraço.
