### ISSUE TITLE
Tamanho do player de vídeo maior sem ser full screen

### ISSUE THREAD

**Issue by beckout** [caelum/alura-funcionalidades#296]
Sabe o modo teatro dos vídeos no YouTube, em que a gente pode deixar o vídeo ocupando 100% da largura do navegador, mas sem ser tela cheia? Sinto falta dessa funcionalidade nos vídeos do Alura.

**Comment by MateusAlberto** [comment]
Eu também sinto muita falta disso! Gosto colocar a tela dividida para assistir os vídeos enquanto programo, mas sem esse modo teatro fica muito pequeno.

**Comment by sahslima** [comment]
Oi, pessoal! Tudo bem?

A sugestão de vocês já foi encaminhada para nosso time de Produto e qualquer novidade nesse sentido, aviso por aqui. ;)

Um abraço.

**Comment by sahslima** [comment]
Oi, pessoal! Tudo bem?

Colocamos o **modo teatro** no ar! ;)

Um abraço.

**Comment by beckout** [comment]
Gente, que maravilha! Desculpa comentar numa issue já fechada, mas eu gostaria muito de falar meu feedback: Sou nova aluna e estou totalmente maravilhada, jamais iria esperar que uma sugestão despretensiosa minha fosse implementada tão rápido! Nossa, parabéns pra toda a equipe!

**Comment by peas** [comment]
É muito bom a gente implementar as features que fazem a diferença :). Parabéns aos alunos e alunas que sugeriram e parabéns à equipe de mergulhadores da Alura!
