### ISSUE TITLE
Remover a visibilidade de respostas dos exercícios

### ISSUE THREAD

**Issue by iagokrt** [caelum/alura-funcionalidades#297]
Atualmente, caso o usuário (estudante) acesse a ferramenta do desenvolvedor do navegador de internet, é possível observar claramente dentro do formulário quais são as alternativas para o exercício. E também **as alternativas assinaladas pelo servidor como corretas.** (**data-correct="true"**)

Exemplo de visibilidade dentro do devtools google chrome [F12]:
`html

      <form>

		<li class="alternativeList-item " data-alternative-id="20456" data-is-exam="false" data-correct="false">
		</li>

		<li class="alternativeList-item " data-alternative-id="20455" data-is-exam="false" data-correct="false">
		</li>

		<li class="alternativeList-item " data-alternative-id="20460" data-is-exam="false" data-correct="true">
		</li>

		<li class="alternativeList-item " data-alternative-id="20458" data-is-exam="false" data-correct="false">
		</li>

	</form>`

o Atributo **data-correct** exibe expressamente qual a alternativa correta para àquele exercício

**Comment by sergiolopes** [comment]
Oi @iagokrt, realmente deixamos assim. Os exercícios da Alura são para prática de cada aluno, não são uma prova, não têm nota nem nada do tipo. Então apesar de ser possível ver a resposta, não tem nenhum impacto prático. A ideia é o aluno usar o exercício para aprender, não tanto pra acertar e tirar uma nota ou algo assim.

Mas obrigado por levantar a questão, realmente é importante ficar claro o objetivo das atividades

Abraço
