### ISSUE TITLE
Imagens no forum de Discussão

### ISSUE THREAD

**Issue by langaia** [caelum/alura-funcionalidades#298]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

Entendo que existe toda uma questão de moderação em relação à incorporar imagens no forum de discussão. Mas creio que isso poderia enriquecer muito a discussão.
Especialmente quando se trata de incorporar gráficos ou questões que são inerentemente imageticas: analise swot, timelines, infograficos. etc.

**Comment by sahslima** [comment]
Oi, @langaia! Tudo bem?

Obrigada pela sugestão, já repassamos para o nosso time de Produto. ;)

Um abraço.
