### ISSUE TITLE
Exportar o caderno para arquivos markdown no Github

### ISSUE THREAD

**Issue by ezefranca** [caelum/alura-funcionalidades#299]
Imagine que todo seu caderno seja espelhado em um repositório no Github. 

1 - Associar conta do Github com conta da Alura
2 - Alura cria um repositório (ex: caderno-alura)
3 - Toda vez que você altera algo no caderno, tem a opção de commitar isso neste respositório

A plataforma Overleaf (editor online de latex) faz isso com projetos LateX.

TL;DR 

Usar o Github como espelho e/ou hospedagem do caderno alura, com suporte à Markdown.

**Comment by sahslima** [comment]
Obrigada pela sugestão, @ezefranca! 

Repassamos para o time de Produto. ;)

Um abraço.
