### ISSUE TITLE
Download dos conteúdos dos cursos - modo offline

### ISSUE THREAD

**Issue by rnd4web** [caelum/alura-funcionalidades#3]
Moro no Brasil e a qualidade do serviço de dados ainda é sofrível, fiz a assinatura do conteúdo pensando em estudar no transporte e nas horas vagas, mas sem a possibilidade de baixar os conteúdos previamente fica impossível.

Acredito que tem mais gente com essa ideia, e também com essa dificuldade.

**Comment by peas** [comment]
@rnd4web essa funcionalidade já existe :), mas precisa utilizar a app no celular/tablet. funciona tanto no android quanto no iphone!
