### ISSUE TITLE
Acessar cursos que baixei no meu ipad off-line

### ISSUE THREAD

**Issue by carlosofpersia** [caelum/alura-funcionalidades#30]
Oi, baixei as aulas do curso para assistir offline, mas a plataforma pede para ter internet, isso não faz sentido, pois baixei para assistir em locais onde não estou em minha wifi.

**Comment by felipetorres** [comment]
Verdade, Carlos, não faz sentido nenhum. Esse era um bug que foi resolvido na versão 2.0.8 do app. Confere se você está com a versão mais atual no seu iPad.

Qualquer coisa, manda msg pra gente em aplicativos@alura.com.br. Por lá dá pra pedir mais detalhes do problema, caso persista.

Abraço.

**Comment by carlosofpersia** [comment]
O problema continua no iPad. Consegui usar no Android . Tiver como olhar ;)

Em ter, 14 de jan de 2020 15:20, Felipe Torres <notifications@github.com>
escreveu:

**Comment by felipetorres** [comment]
Qual a versão do app que está no seu iPad? Dá uma olhada ;)
