### ISSUE TITLE
Reduzir as margens da área de exibição do vídeo

### ISSUE THREAD

**Issue by robsoncraftsman** [caelum/alura-funcionalidades#300]
Utilizo uma tela 15.4'' Full HD e nas aulas onde aparecem vídeos, a área do vídeo é muito pequena, dificultado a visualização do mesmo. A única opção é um modo Full Screen que também é desconfortável.

Tem uma issue para permitir a visualização do vídeo com largura 100%, mas independente disso, acredito que as margens laterais poderiam ser menores, permitindo um maior conforto na visualização do vídeo.

**Comment by sahslima** [comment]
Olá, @robsoncraftsman!

Obrigada por compartilhar, estamos trabalhando no desenvolvimento do "modo teatro" e aviso aqui quando estiver disponível. ;)

Um abraço.

**Comment by robsoncraftsman** [comment]
Olá @sahslima, tudo bem?

A implementação do modo teatro, quando o browser está maximizado, ficou ótima.

Mas ao reduzir a largura do browser, para por exemplo para 50% e desta forma poder colocar a janela da IDE e a janela do browser lado a lado, o vídeo fica muito pequeno devido as margens laterais. Isto dificulta a visualização do mesmo.

Se pudessem reduzir ou mesmo eliminar as margens nesta situação, para que o vídeo fique mais nítido e seja possível trabalhar com as janelas da IDE e do vídeo lado a lado, seria ótimo.

Muito obrigado.

**Comment by sahslima** [comment]
Oi, @robsoncraftsman! Tudo e você?

Passei sua observação para o nosso time de desenvolvimento! ;)

Retorno aqui.

**Comment by sahslima** [comment]
Bom dia, @robsoncraftsman!

Corrigimos. ;)

**Comment by robsoncraftsman** [comment]
Olá @sahslima,

O tamanho do vídeo ficou ótimo. 

Muito obrigado :)
