### ISSUE TITLE
DevContainers para cursos/formações

### ISSUE THREAD

**Issue by Noriller** [caelum/alura-funcionalidades#302]
Não sei outras IDE, mas o VSCode tem algo bem legal que são as DevContainer. 

Para poder "padronizar" melhor a área de trabalho durante os cursos, cada formação poderia disponibilizar uma imagem com um workspace já "formatado" para começar a codar.

Então: command prompt, versão da linguagem, extensões úteis... já estaria tudo pronto e configurado, é só abrir e começar a mexer.

O legal é que como tudo poderia fixar fixado na mesma versão acaba com o problema que "não funciona na minha maquina"

**Comment by sahslima** [comment]
Obrigada por compartilhar, @Noriller!

Direcionamos sua sugestão para nosso time de Produto. ;)

Um abraço.
