### ISSUE TITLE
Sessão de usuário para vídeo

### ISSUE THREAD

**Issue by matiasribeiro** [caelum/alura-funcionalidades#303]
Na tela de aula, os vídeos ficam em uma sessão separada. Quando estou vendo aula e deixo um tempo sem iteração, tenho que atualizar a página e consequentemente o vídeo volta para o início, isso não é usual.

A sessão do usuário não fecha, somente a do vídeo que estou assistindo.

**Comment by sahslima** [comment]
Obrigada pelo report, @matiasribeiro!

Passamos para o time de desenvolvimento e aviso por aqui quando retornarem. ;)

Um abraço.

**Comment by sergiolopes** [comment]
Oi matias, obrigado pela mensagem. Ainda não temos o recurso de retomar o vídeo de onde ele parou. É algo bem importante mesmo, muito pedido. Estamos trabalhando nisso pra esse ano ainda

**Comment by sahslima** [comment]
Oi, @matiasribeiro! Tudo bem?

Implementamos o recurso de retomada do vídeo no ponto pausado. ;)

Um abraço.
