### ISSUE TITLE
Reset do curso

### ISSUE THREAD

**Issue by thi-a-go** [caelum/alura-funcionalidades#304]
**OBS: Procurei e não achei! Se já existir, peço desculpa e que finalize a issue/melhoria.**

Imagina 2 situações:
1° - Comecei o curso e tive que parar, por causa de algum problema e por um "Tempo indeterminado". Daí entendo que estou descontextualizado ou o curso sofreu algumas melhorias e etc, quando volto! 
    Gostaria de verificar a possibilidade, na reinicialização das marcações do que já olhei e passei, que voltassem a um ponto onde eu possa determinar que deva continuar em um ponto. Como "SAVE" de um jogo que marca o ultimo ponto.

2° - Imagina que já conclui o curso e recebi o certificado, mas por vezes entendo que como ser humano... "esqueço como qualquer outro". Gostaria de ver a possibilidade, reiniciar ou de criar um **flag** de revisão de tópicos que eu marque ou reset a matéria a pontos estratégicos ou que eu consiga marcar um **checkpoint** de minha revisão. 
Esse **checkpoint** tira os _"verdinho"_, aquele ilustrado que já passei ou visitei e não perco o certificado. 
Por exemplo, analogia de um jogo:
Enfrentei o mestre de tela, ganhei os itens e tal. Mas, gostaria de poder batalhar contra ele novamente! Sem perder o que foi ganho. 
_Eu faço revisões, por não ter oportunidade de usar... sobre o docker e linux... a Matéria do professo Mauricio sobre: SOLID então..._

**Comment by sahslima** [comment]
Oi, @thi-a-go !

Estamos estudando como facilitar esse processo para os alunos que desejam rever conteúdos/cursos já realizados.

Qualquer novidade, avisamos por aqui.

Obrigada por compartilhar. ;)

Um abraço.
