### ISSUE TITLE
Resetar cursos concluidos

### ISSUE THREAD

**Issue by raphaelcordon** [caelum/alura-funcionalidades#305]
Alguns cursos são mais complexos e eventualmente nós precisamos re-visitá-los, por exemplo, eu re-iniciei a minha jornada nos cursos de Django, mas eu já havia anteriormente concluido dois deles.

Seria interessante ter a opção de marcar o curso com uma nova rodada de visitação, assim eu teria o beneficio do curso aparecendo no topo do meu dashboard cada vez que eu logasse no site da Alura, além de continuar da parte que eu pausei o curso, da mesma forma que acontece com os cursos novos.

**Comment by sahslima** [comment]
Oi, @raphaelcordon!

Estamos estudando como facilitar esse processo para os alunos que desejam rever cursos já realizados.

Qualquer novidade, avisamos por aqui.

Obrigada por compartilhar. ;)

Um abraço.
