### ISSUE TITLE
[UX] Vídeo maior na página da aula

### ISSUE THREAD

**Issue by isaquepereira** [caelum/alura-funcionalidades#306]
Amigos, uma sugestão simples, mas acho que pode ajudar todo mundo é deixar o vídeo como um elemento _full width_. Dá até pra pensar em um comportamento a lá YouTube com o modo normal, _theather_ e _fullscreen_.

Ex:
<img width="1680" alt="Screen Shot 2020-10-26 at 18 36 46" src="https://user-images.githubusercontent.com/26747447/97231913-0d09c780-17bb-11eb-9a31-046ff877e49f.png">

**Comment by sahslima** [comment]
Oi, @isaquepereira! Tudo bem?

Realmente, essa era uma função muito pedida por nossos alunos e implementamos o **modo teatro** no final da semana passada. Já chegou a ver? :D

Um abraço.
