### ISSUE TITLE
Ranking para Alura Empresarial

### ISSUE THREAD

**Issue by MendesVitor** [caelum/alura-funcionalidades#307]
Criar um ranking com todos os membros dentro de uma licença empresarial da Alura, de forma com que os funcionários possam competir entre si de forma saudável.

**Comment by sahslima** [comment]
Oi, @MendesVitor! Tudo bem?

Muito bacana sua sugestão, nosso time de Produto está avaliando e qualquer novidade nesse sentido, aviso por aqui. ;)

Um abraço!
