### ISSUE TITLE
Like nas perguntas e respostas do fórum

### ISSUE THREAD

**Issue by daianerangel** [caelum/alura-funcionalidades#308]
Gostaria de poder sinalizar que encontrei minha dúvida no fórum e que também utilizei a resposta.

Talvez essa informação seja útil para entender quais são os cursos que geram mais pessoas aos fóruns. 

Como usuário ia usar como forma de agradecimento pela ajuda que recebi.

**Comment by sahslima** [comment]
Olá, @daianerangel! Tudo bem?

Obrigada pela sugestão, qualquer novidade nesse sentido, aviso por aqui. ;)

Um abraço.

**Comment by daianerangel** [comment]
Ol[a @sahslima , de nada. Bjs
