### ISSUE TITLE
Indicador de conteúdo já iniciado no resultado da busca

### ISSUE THREAD

**Issue by danpermun** [caelum/alura-funcionalidades#309]
Seria interessante ter um indicador de conteúdo já visto (mesmo que menor que 100% no caso de curso) em cada linha do resultado da busca geral por conteúdo.

Com isso, o usuário somente iria incluir em um plano de estudo algum conteúdo já visto por ele caso desejasse de fato rever o conteúdo.

Também facilitaria entender se um determinado assunto (chave da busca), já foi totalmente visto pelo usuário.

**Comment by sahslima** [comment]
Oi, @danpermun!

Hoje mostramos o percentual de progresso no painel inicial:
![image](https://user-images.githubusercontent.com/59886589/98962440-69702500-24e5-11eb-91c6-e7d2bdfdbf65.png)

E também dentro do curso:
![image](https://user-images.githubusercontent.com/59886589/98962596-8dcc0180-24e5-11eb-9fe4-5e585ee53e18.png)

Porém, de fato, ainda nada específico no campo de busca. Vamos considerar sua sugestão para melhorias futuras na funcionalidade.

Sobre sinalizar que um conteúdo já foi visto, atualmente fica visível através desse ícone de medalha:
![image](https://user-images.githubusercontent.com/59886589/98963210-26fb1800-24e6-11eb-98ac-90818bb9ed68.png)

Tanto em planos de estudos criados pelo usuário (como é o caso desse acima, criado por mim), quanto nas formações já existentes na plataforma. Por exemplo, se eu iniciar uma formação que contém um curso que eu já conclui, isso será exibido e não precisarei realizá-lo novamente (apenas se eu quiser rever o conteúdo):
![image](https://user-images.githubusercontent.com/59886589/98963845-ddf79380-24e6-11eb-877a-6f1b574a0259.png)

Você já tinha notado esse ponto?

**Comment by danpermun** [comment]
Boa tarde Samantha,

Obrigado pelo retorno.

Quanto à medalha, acho que é exatamente o que pedi... mas a medalha aparece
no resultado da busca?

Abs

Em qui, 12 de nov de 2020 12:59, Samantha Lima <notifications@github.com>
escreveu:

**Comment by sahslima** [comment]
Ah, perfeito!

Ainda não, mas pode ser uma possibilidade.

Vamos discutir esse ponto internamente e qualquer novidade, te aviso. ;)

Um abraço!
