### ISSUE TITLE
Exclusão de cursos do dashboard

### ISSUE THREAD

**Issue by nicolas-santanna-campos** [caelum/alura-funcionalidades#31]
Pessoal, vi que temos tópicos relacionados ao assunto em 2017, 2018, mas a solução apresentada (pausar o curso) ainda não está completamente aderente aos anseios do corpo discente.

A Alura possui diversos cursos extraordinários, então as vezes, acabamos iniciando um curso que não está no escopo previsto de aprendizado, e não o seguimos.

Para proporcionar uma melhor organização, gostaria de poder excluir de forma definitiva do meu dashboard determinados cursos. Falando do APP então, essa funcionalidade torna-se ainda mais necessária.

Grato pela atenção.

**Comment by aleroxac** [comment]
Fala @nicolas-santanna-campos, tudo certo?
Na issue #7 cheguei a comentar uma maneira de remover os cursos do dashboard, fica como solução paliativa, caso queira, até que implementem a funcionalidade.

**Comment by designernatan** [comment]
@nicolas-santanna-campos , acho que o alex já te ajudou, mas pode me dar mais detalhes sobre o motivo que o pausar não mata o problema? Quero entender melhor o seu uso (do ponto de vista de UX).

Em 'Meus cursos' os cursos em pausa ficam **bem** isolados no fim da lista. E no perfil público do aluno somente estão os cursos concluídos.

abcs

**Comment by nicolas-santanna-campos** [comment]
Fala pessoal, tudo certo!?

Agradeço pelo rápido retorno.

Sobre o questionamento, os motivos pelos quais eu acho que pausar o curso não é uma solução definitiva:

- Por organização;
- Questão anímica, relacionada a ter um dashboard com um objetivo palpável, alcançável e coeso com a meta de cada estudante;
- Propiciar o uso correto do conceito pausado;

Muitas vezes iniciamos um curso por curiosidade, para se ter uma prévia do conteúdo. Por vezes podemos utilizar o conceito de pausado, pois a ideia é realmente voltar ao curso até a sua conclusão. 

Porém, em outros casos entendemos que não era exatamente o que procurávamos e gostaríamos de excluir o curso do dashboard, não apenas separa-lo.

Se considerarmos que essa situação pode ocorrer diversas vezes, mesmo que deixemos os cursos isolados, logo essa lista poderá tomar uma grande proporção.

Grato pela atenção.

**Comment by ch-rodrigopimenta** [comment]
Melhor funcionalidade (se for realmente implementada).
Acho que tem uns 5 cursos que, iniciei por curiosidade, não quero mais continuar a fazê-los, e eles ficam meio que misturados com os cursos que eu realmente pausei por questões pessoais.
