### ISSUE TITLE
Modo noturno na página além dos cursos

### ISSUE THREAD

**Issue by filipemelo** [caelum/alura-funcionalidades#310]
Assim como tem modo noturno nos cursos, gostaria que tivesse um local para ativar modo noturno para tudo, buscas, e cursos.

**Comment by sahslima** [comment]
Oi, @filipemelo! Tudo bem?

Obrigada por compartilhar, nosso time de Produto vai considerar sua sugestão no desenvolvimento de melhorias do **modo noturno**.

Qualquer novidade, aviso por aqui! ;)

Um abraço.
