### ISSUE TITLE
Plano Business - Empresa/Funcionarios/Times

### ISSUE THREAD

**Issue by stonestecnologia** [caelum/alura-funcionalidades#311]
Bom dia 
Existe o pacote ou plano para empresas ?
Gostaria de saber, pois tenho interesse de colocar meus funcionarios e times no grupo de estudos e usando a plataforma da alura.

Gladson
https://www.linkedin.com/in/gladsonreis/

**Comment by sahslima** [comment]
Oi, @stonestecnologia! Tudo bem?

Existe sim. Você pode entrar em contato com nosso time [por aqui](https://www.alura.com.br/empresas/comece-agora).

Se encontrar alguma dificuldade, me avise.

Um abraço.
