### ISSUE TITLE
Reprodução automática das aulas

### ISSUE THREAD

**Issue by liandro-wesley** [caelum/alura-funcionalidades#312]
## Reprodução automática das aulas

Gostaria que avaliassem a possibilidade de implementar o recurso de reprodução automática. Ao final de cada aula a próxima já seria carregada/iniciada, costumo reservar um horário para fazer algumas aulas e querendo ou não é um pouco custoso ter que minimizar a tela e apertar no botão <kbd>Próxima atividade</kbd>.

#### Apenas alguns detalhes que costumo ver em outros players de vídeos

- Timer iniciado ao final da aula indicando que outra será iniciada;
- Botão já no player que permite ir direto para aula ou reproduzi-la novamente;
- Para os usuários que não se sentirem confortáveis com essa funcionalidade, um toggle para habilitar e desabilitar essa funcionalidade.

**Comment by wandersonmaceds** [comment]
Oi @liandro-wesley pode me ajudar a entender melhor essa funcionalidade? 

Exemplo, se você está vendo um vídeo e o próximo passo da aula é um outro vídeo, nós carregamos esse próximo passo e damos play no vídeo (se tiver full-screen, recolocamos em full-screen no próximo vídeo).

Agora, se o próximo passo da aula for um exercício, o que você espera? Que carregue o exercício ou pule para o próximo vídeo?

**Comment by bondegar-den-keith** [comment]
Olá olha como aluno da Alura vindo aqui pela primeira vez eu não sei se posso comentar nesse issue de outra pessoa, mas na minha opinião seria mais interessante carregar o próximo exercício(caso seja um exercício o próximo ou até a uma opção que permite da pessoa personalizar o que quer fazer ao acabar o vídeo. E caso eu não possa comentar aqui eu peço desculpas não consegui achar onde tem isso(ou achei e não entendi) desculpas mesmo, mas caso eu tenha ajudado melhor.

**Comment by wandersonmaceds** [comment]
Oi @bondegar-den-keith pode comentar sim, se a sua sugestão tiver algo dentro do assunto, fique a vontade por favor. Acho que faz sentido o que você disse. Tem algo mais que gostaria de adicionar?

**Comment by bondegar-den-keith** [comment]
por agora não muito obrigado.

**Comment by thiagofloriano** [comment]
Algo que tem me incomodado muito é que os vídeos, em geral, são curtíssimos e não há reprodução automática do vídeo seguinte mesmo dentro de uma mesma aula. Isso faz com que tenhamos que parar o tempo todo para clicar em reproduzir, prejudicando muito a experiência.

Se a intenção é que o aluno não saia ouvindo tudo sem fazer as atividades, ainda assim daria pra passar para o próximo vídeo quando não há exercício entre eles e parar apenas quando há atividades ou quando termina uma determinada sessão.

**Comment by thiagofloriano** [comment]
Só como exemplo. Na minha rotina de estudos assisto às aulas no PC ou App Android, mas faço os exercícios somente no PC porque não gosto da experiência dos exercícios pelo smartphone.

Se houvesse a possibilidade de assistir tudo sequencialmente e sem pausas seria excelente.

**Comment by beckout** [comment]
Interessante, já eu gosto bastante de vídeos mais curtos e atividades entre os vídeos, porque me canso demais de ver vídeos longos. Porém, acho bem interessante essa funcionalidade de haver um botão para reproduzir automaticamente de um vídeo para o outro. No caso de a próxima tela ser um exercício, poderia reproduzir um som (discreto, pelo amor de Goku kkkk - algo assim: <https://www.epidemicsound.com/track/vncC9qtEyl>) pra gente saber que a reprodução automática não ocorreu, porque tem atividade pra fazer.

**Comment by sahslima** [comment]
Oi, pessoal! Tudo bem?

Muito rica a conversa que a sugestão do @liandro-wesley gerou por aqui. Não só na parte de reprodução automática, como também os comentários sobre a duração dos vídeos de aula.

Nosso time de Produto vai considerar esses pontos nas melhorias e desenvolvimento de novas funcionalidades na plataforma.

Qualquer novidade nesse sentido, aviso por aqui! ;)

Um abraço.

**Comment by liandro-silva** [comment]
> Oi, pessoal! Tudo bem?
> 
> Muito rica a conversa que a sugestão do @liandro-wesley gerou por aqui. Não só na parte de reprodução automática, como também os comentários sobre a duração dos vídeos de aula.
> 
> Nosso time de Produto vai considerar esses pontos nas melhorias e desenvolvimento de novas funcionalidades na plataforma.
> 
> Qualquer novidade nesse sentido, aviso por aqui! ;)
> 
> Um abraço.

Gratidão a equipe Alura @sahslima estive bastante ocupado e por este motivo motivo não pude participar do andamento da issue. Mas já está na plataforma esta funcionalidade. Fico muito satisfeito com o rápido retorno, com certeza foi um ótimo investimento que fiz.

Sucesso turma!
