### ISSUE TITLE
Scroll nas novidades

### ISSUE THREAD

**Issue by Noriller** [caelum/alura-funcionalidades#313]
O sininho das novidades poderia ter a possibilidade de ter um scroll.

Eu normalmente acompanho as novidades para saber se tem cursos novos que tenho interesse, mas mesmo de um dia para o outro as vezes a lista é gigante e tenho que entrar na página para poder ver.

Ou um scroll ou alguma forma de poder ter tipo uma lista de todos os coisas que não vi... talvez até mesmo opção para incluir em uma playlist?

**Comment by peas** [comment]
Talvez melhorar também a página principal de novidades e deixar mais itens e mais organizado?

**Comment by sahslima** [comment]
Obrigada por compartilhar, @Noriller!

Estamos trabalhando em melhorias para essa parte da plataforma e assim que entrarem no ar, avisamos aqui! ;)

Um abraço.
