### ISSUE TITLE
notificação do fórum

### ISSUE THREAD

**Issue by bondegar-den-keith** [caelum/alura-funcionalidades#314]
Olá tudo bem?
antes vamos contextualizar do porque eu estar dando está sugestão.
O motivo foi um "problema" que não é realmente um problema mas que vale a pena ser discutido, assim quando eu estou navegando no fórum (como o de programação) noto que para ver novas perguntas tem que atualizar a página(e serio quando se quer contribuir para a comunidade ter que ficar fazendo muito isso desanima) e além disso eu também faço curso e tenho certeza que existem outras pessoas que também querem contribuir e fazer o curso delas até mesmo paralelamente então vamos pensar como podemos melhorar ou resolver isso, uma ideia é criar uma funcionalidade que seria assim:

A funcionalidade seria algo como uma notificação do fórum, ela funcionaria assim(ou algo parecido) a pessoa que quer responder uma pergunta vai lá e habilita uma opção(a ser criada) por exemplo(no meu caso estou no navegador) e quando tiver uma nova pergunta que foi feita no fórum sobre o tópico que a pessoa escolheu vai aparecer uma notificação ou no desktop ou em outra área como no site, assim pessoas como eu que querem contribuir poderiam fazer isso de maneira mais fácil e ainda assim conseguindo fazer os cursos sem ter que ficar indo e voltando no fórum ajudando assim quem quer ajudar e quem precisa de ajuda.

A e também isso abre as portas para um programa para os alunos da Alura que querem ajudar, seria um programa que o aluno(a) pode se inscrever para ter acesso a essa funcionalidade, seja isso com ou sem benefícios(de preferência sem para que seja de livre e espontânea vontade do aluno(a)) mas pensem bem é algo possível e seria uma melhoria muito boa para a plataforma em geral.

Olha não sei se tem algo parecido ou se já deram uma ideia parecida eu estou aqui para dar minha ideia e para discutir com quem também faz parte disso e quer ajudar a melhorar cada vez mais e mais não só a Alura mas sim todo e qualquer programa, sistema ou causa que pode fazer a diferença no mundo. Enfim muito obrigado, espero que leiam isso e me digam o que acham e se possível até mesmo algo que pode melhorar no meu comentário para que essa ideia faça sentido e traga melhorias.

"Ideias não são criadas prontas, elas se tornam claras a medida que você trabalha nelas" Mark Zuckerberg - Discurso Harvard

**Comment by wandersonmaceds** [comment]
Oi @bondegar-den-keith eu confesso que fiquei um pouco perdido na sua sugestão. Deixa eu tentar descrever o que entendi e ai você me confirma se estou entendendo bem.

Você gostaria de em algum lugar, dizer que quer receber notificações sobre tópicos de um assunto, tipo "programação java", e ai então, em qualquer parte do site, você gostaria que houvesse um aviso: "nova dúvida de programaçao java" onde você clica e vai direto para a dúvida em questão. Entendi certo?

**Comment by bondegar-den-keith** [comment]
Sim isso mesmo

**Comment by wandersonmaceds** [comment]
O que a gente tem hoje é uma opção lá no seu perfil que é "receber notificações por e-mail dos cursos que fiz semanalmente)", você habilita e recebe toda semana, uma lista de tópicos sobre os cursos que fez direto no seu e-mail. O que acha dessa opção?

**Comment by bondegar-den-keith** [comment]
deixe me ver já retorno uma resposta

**Comment by bondegar-den-keith** [comment]
@wandersonmaceds eu não consegui encontrar, estou fazendo o curso pelo projeto que o governo criou e não sei se já vem habilitado essa opção mas eu não consegui encontra-la

**Comment by wandersonmaceds** [comment]
Oi @bondegar-den-keith acredito que você esteja associado a uma conta do tipo empresa dentro da Alura. Infelizmente, essa funcionalidade não está disponível pra esse tipo de conta. É uma funcionalidade ainda em testes, está em fase beta, se fizer sentido, talvez fique disponível para todos os alunos, porém, precisamos avaliar ainda. Sinto muito por isso.

**Comment by bondegar-den-keith** [comment]
A sim tudo bem obrigado
