### ISSUE TITLE
Reprodução sequencial dos vídeos

### ISSUE THREAD

**Issue by thiagofloriano** [caelum/alura-funcionalidades#315]
Algo que tem me incomodado muito é que os vídeos, em geral, são curtíssimos e não há reprodução automática do vídeo seguinte mesmo dentro de uma mesma aula. Isso faz com que tenhamos que parar o tempo todo para clicar em reproduzir, prejudicando muito a experiência.

Se a intenção é que o aluno não saia ouvindo tudo sem fazer as atividades, ainda assim daria pra passar para o próximo vídeo quando não há exercício entre eles e parar apenas quando há atividades ou quando termina uma determinada sessão.

**Comment by sahslima** [comment]
Oi, @thiagofloriano!

Vimos seu comentário na https://github.com/caelum/alura-funcionalidades/issues/312 também. ;)

Obrigada por compartilhar, a gente sempre considera esses pontos no desenvolvimento de melhorias da plataforma.

Qualquer novidade nesse sentido, aviso por aqui.

Um abraço!

**Comment by sahslima** [comment]
@thiagofloriano, tudo bem?

Não sei se já viu, mas finalmente **lançamos a reprodução automática**! Haha

[Este artigo](https://www.alura.com.br/artigos/novidades-de-janeiro-na-alura) explica rapidamente a funcionalidade.

Depois conta pra gente o que achou. ;)

Um abraço!

**Comment by thiagofloriano** [comment]
Boa noite.

Vi isso anteontem e já estou usando. Agilizou muuuuuito meu andamento nos cursos.

Muito obrigado!
