### ISSUE TITLE
A barra de progresso do vídeo é muito fina

### ISSUE THREAD

**Issue by bmansur** [caelum/alura-funcionalidades#316]
Olá, pessoal!
Gostaria de sugerir que aumentassem a barra de progresso do vídeo ou que colocassem um tumbnail ou outro feedback visual para que saiba que estaria indo para aquele ponto do vídeo e não pausando o vídeo quando clicar.
Sempre que quero voltar a algum ponto específico e recorro à barra de progresso do mesmo acabo clicando no vídeo o pausando ao invés de ir até o ponto do vídeo que quero navegar.
![Screenshot from 2020-11-13 16-24-13](https://user-images.githubusercontent.com/4333616/99112610-b24ed900-25cc-11eb-896e-a2c000e5d663.png)

**Comment by sahslima** [comment]
Oi, @bmansur!

Obrigada pela sugestão.

Já repassamos esse feedback para o time de desenvolvimento, qualquer novidade, te aviso por aqui! ;)
