### ISSUE TITLE
Biblioteca de vídeos Salvos

### ISSUE THREAD

**Issue by celinaleila** [caelum/alura-funcionalidades#317]
poder salvar as aulas favoritas. Facilita na hora de procurar e otimiza o aprendizado, alguns cursos, por exemplo, são feitos por conta de um aprendizado específico e seria interessante ter acesso a aula específica quando precisar.

**Comment by sahslima** [comment]
Obrigada pela sugestão, @celinaleila! :D

Vamos considerar nas melhorias da plataforma.

Qualquer novidade nesse sentido, te aviso por aqui!
