### ISSUE TITLE
Sugestão de sugerir alterar mais do que apenas erros ortográficos

### ISSUE THREAD

**Issue by Noriller** [caelum/alura-funcionalidades#318]
Basicamente só é possível sugerir erros muito simples...
Mas já peguei erros muito mais substanciais e não havia maneira de sugerir mudanças neles.

**Comment by sahslima** [comment]
Oi, @Noriller! Tudo bem?

Atualmente, nós temos essa parte de "**sugerir alteração**", que o aluno ou aluna pode acessar em cada atividade através desse ícone de 3 pontos:
![image](https://user-images.githubusercontent.com/59886589/100275726-27140280-2f3f-11eb-9d27-cb222cd61b68.png)

Seu ponto é sobre ter mais opções para seleção de report além dos itens abaixo, certo?

- Correção ortográfica;
- Problema com áudio e vídeo;
- Link quebrado;
- Correção técnica.

Além deles, quais outros assuntos você já sentiu necessidade de ter como tópico e não encontrou?

**Comment by Noriller** [comment]
Considerando as opções acima, acredito que seria o suficiente.

**Comment by sahslima** [comment]
Ah, bacana! Então já temos na plataforma.

Clicando em "**sugerir alterações**" você é direcionado para essa tela:
![image](https://user-images.githubusercontent.com/59886589/100289214-24bda280-2f57-11eb-8fcc-4f6dc8fadb09.png)

Nela conseguirá definir o tipo de problema encontrado e "**submeter a sugestão**". (:

Um abraço!
