### ISSUE TITLE
Atalhos de Teclado

### ISSUE THREAD

**Issue by wildener** [caelum/alura-funcionalidades#319]
A Alura poderia conter atalhos de teclado para facilitar a navegação do usuário. Exemplos e sugestões de atalhos, supondo que o usuário está dentro do curso:

- CTRL / ⌘ + SHIFT + P = Próxima atividade
- CTRL / ⌘ + SHIFT + C = Ir para a página do curso
- CTRL / ⌘ + SHIFT + F = Discutir no Fórum
- CTRL / ⌘ + SHIFT + I = Ver opinião do Instrutor
- CTRL / ⌘ + SHIFT + A = Abrir caderno
- CTRL / ⌘ + SHIFT + S = Salvar caderno
- CTRL / ⌘ + SHIFT + N = Modo noturno
- CTRL / ⌘ + SHIFT + D = Voltar para dashboard

Outra opção, para melhorar a experiência do usuário, é usar apenas uma tecla. É possível usá-las quando o foco do cursor não está um campo editável (textbox, textarea, etc.)
- P = Próxima atividade
- C = Ir para a página do curso
- F = Discutir no Fórum
- I = Ver opinião do Instrutor
- A = Abrir caderno
- CTRL / ⌘ + SHIFT + S = Salvar caderno (atalho não alterado porque o foco do cursor está em uma textarea).
- N = Modo noturno
- D = Voltar para dashboard

**Comment by sahslima** [comment]
Obrigada pela sugestão, @wildener!

Hoje possuímos os atalhos apenas para o player de vídeo, mas vamos considerar seus pontos para futuras melhorias na experiência de navegação.

Qualquer novidade nesse sentido, te aviso aqui. ;)
