### ISSUE TITLE
Criar Projeto de Marketing Digital e/ou Social Media

### ISSUE THREAD

**Issue by camposdebs** [caelum/alura-funcionalidades#32]
Seria muito bom existir um projeto de Marketing Digital ou Social Media, como os de Design Gráfico, UX, Front-end... É ótimo para quem está criando portfólio e currículo, ter um case avaliado e com certificado de conclusão.

**Comment by designernatan** [comment]
@camposdebs passei sua sugestão para o time que cuida dos projetos, apesar de achar complicado de ter um projeto dessas formações agora, faz total sentido
