### ISSUE TITLE
Mural Certificados 

### ISSUE THREAD

**Issue by wdiasvargas** [caelum/alura-funcionalidades#320]
Gostaria de sugerir um mural de Certificados mais informativo, estilo Dashboard, que pudesse ser impresso/publicado como Cv com os cursos concluidos que na parte do perfil, em cursos e certificados tivesse um **Grafico de Radar** pra ficar visivel qual areas do conhecimento estamos nos aperfeiçoando algo parecido com esse da imagem [https://cdn.dribbble.com/users/2501157/screenshots/13895840/media/a676adbc165098743d1de623afeb7690.png](https://cdn.dribbble.com/users/2501157/screenshots/13895840/media/a676adbc165098743d1de623afeb7690.png)

**Comment by sahslima** [comment]
@wdiasvargas, obrigada pela sugestão!

Estamos trabalhando em melhorias na área de perfil dos alunos e vamos considerar seus pontos. ;)

Qualquer novidade, te aviso aqui.
