### ISSUE TITLE
Bug entre modo noturno e theater mode 

### ISSUE THREAD

**Issue by Noriller** [caelum/alura-funcionalidades#321]
Pelo que percebi, as vezes abro um curso e ou theater ou o modo noturno estão habilitados, mesmo eu tendo habilitado ambos em um curso anterior. 
Então habilito de novo o outro e, embora as vezes persista, outras vezes preciso ficar habilitando um ou outro constantemente.

**Comment by sahslima** [comment]
Passamos para o nosso time de desenvolvimento, @Noriller.

Assim que estiver corrigido, te aviso aqui! ;)

**Comment by sahslima** [comment]
Corrigimos, @Noriller! (:

Pode testar e qualquer coisa, avise aqui. 

Um abraço.
