### ISSUE TITLE
AutoPlay dos videos

### ISSUE THREAD

**Issue by gabrielareia** [caelum/alura-funcionalidades#322]
Seria muito bom se tivesse a opção de escolher ver os videos de uma vez, e eles tocassem um após o outro, como na Netflix, e se a pessoa não quiser ela desativa e faz normalmente como já é hoje.

Eu normalmente assisto todos os videos primeiro e depois respondo os exercícios, eu boto pra passar na TV e gosto de sentar longe do PC mas meu mouse sem fio quebrou, então todo vídeo que acaba eu tenho que levantar e mudar, ou mudar pelo teclado apertando o TAB até acender a opção que eu quero e apertar o Enter.

**Comment by felipetorres** [comment]
Oi Gabriel, dá uma olhada no app da Alura para Android. Por lá dá pra fazer esse AutoPlay e você consegue jogar na TV via Chromecast. Será que rola pra você?

**Comment by sahslima** [comment]
Oi, @gabrielareia!

Complementando a resposta do Felipe, estamos buscando a melhor forma de tornar isso possível também no desktop.

Em breve teremos novidades e te avisamos por aqui! ;)

**Comment by athosfranco** [comment]
De fato é um recurso que está faltando. Foi uma das primeiras coisas que eu senti falta quando comecei a assistir as aulas da Alura.

**Comment by gabrielareia** [comment]
@felipetorres Infelizmente não, porque não tenho chromecast nessa TV que uso. Mas se desse pra fazer no desktop igual dá no app seria perfeito.

**Comment by wandersonmaceds** [comment]
Oi gente, já faz algumas semanas que está no ar o autoplay dos vídeos no desktop, neste artigo que saiu no blog, explica um pouco como funciona: https://www.alura.com.br/artigos/novidades-de-janeiro-na-alura?utm_source=gnarus&utm_medium=timeline
