### ISSUE TITLE
Algumas sugestões ao 'Caderno'

### ISSUE THREAD

**Issue by athosfranco** [caelum/alura-funcionalidades#323]
Olá.

Seria interessante se tivéssemos um caderno para cada curso, e uma página de anotação para cada aula. Exemplo: se estou assistindo a 4º aula do curso de HTML e CSS3, ao clicar em caderno, um espaço para eu fazer anotações será aberto, apenas sobre aquela aula, no caderno do curso de HTML e CSS3. Quando eu avançar para a próxima aula, o espaço de anotações do caderno estará em branco, para que eu escreva novas anotações referentes a aquela aula em específico. Aí poderia ter um botão de "Ver caderno completo" ou "Ver todas anotações do curso" e aí eu teria acesso a todo o conteúdo que eu escrevi no caderno, dividido por cursos e aulas. Acho que seria uma melhoria UX interessante, permitiria mais organização. 

Outra sugestão (que eu acredito que vcs já tenham pensado) é colocar algumas opções de edição de texto, como negrito, itálico, marcador de textos, etc.

Bom, é isso. Estou curtindo bastante os cursos e adoro a plataforma. Espero que tenha contribuído de alguma forma. Abraço a todos.

**Comment by luigiMinardi** [comment]
Não sei se já está no Roadmap mas tem bastante gente pedindo markdown então provavelmente eles devem adicionar em breve, com o markdown (se for tipo o do GitHub ou o do Google Colab) ja deve resolver praticamente todos esses problemas já que teria como dar "jump" nos topicos de cada aula e os negritos, italicos etc

**Comment by sahslima** [comment]
Oi, pessoal! Tudo bem?

Obrigada pelas sugestões.

Estamos revendo alguns pontos relacionados ao caderno, tanto de organização de tópicos quanto da edição de texto/markdown e, vamos considerá-las no desenvolvimento! Assim que tivermos novidades sobre esse ponto, eu aviso aqui. ;)

Um abraço.
