### ISSUE TITLE
Aluna no Discord/ Slack

### ISSUE THREAD

**Issue by diogotassara** [caelum/alura-funcionalidades#324]
Como forma de engajar mais os alunos e tornar o ambiente mais colaborativo, sugiro a criação de um servidor no Discord, e a criação de canais com os respectivos cursos, para que assim, os alunos localizem com mais facilidade outras pessoas da merma formação.

**Comment by sahslima** [comment]
Oi, @diogotassara. Tudo bem?

Obrigada pela sugestão.

Estamos em processo de revisão da nossa parte de comunidade/fórum e vamos considerar seus pontos. ;)

Qualquer novidade sobre esse tópico, eu aviso por aqui.

Um abraço!
