### ISSUE TITLE
Mural de Insights!

### ISSUE THREAD

**Issue by fabiocampanhol** [caelum/alura-funcionalidades#325]
Estou fazendo as aulas de UX Design, e notei uma função que seria bem bacana ter em cada uma das aulas: um mural de insights!

Sabe aquelas ideias que você tem junto com a aula? Ou aquela sugestão de programas ou ferramentas que você gostaria compartilhar na hora, sem ter que criar um post no fórum?

Seria um campo de insights mesmo, com caracteres limitados, como um tweet, apenas para postarmos insights. Aí esse mural poderia ficar disponível para todos que estiverem naquela aula.

O caderno seria para gente.
O mural de insights seria para todos.

Aí em "minha conta", poderia ter um link para eu ver todos os insights postados.

Já pensou um insight de uma pessoa ajudar no projeto de outra pessoa? ;)

**Comment by sahslima** [comment]
Ótima sugestão, @fabiocampanhol!

Estamos revendo nossa área de perfil do aluno, caderno e consequentemente comunidade, vamos considerar seu ponto no desenvolvimento dessa parte.

Qualquer novidade nesse sentido, aviso por aqui. ;)

Um abraço.
