### ISSUE TITLE
PDF - material das aulas

### ISSUE THREAD

**Issue by Golluns666** [caelum/alura-funcionalidades#326]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.
Oi Pessoal. 
Sugiro colocar o documento em texto disponibilizado na plataforma do curso para download no formato PDF.

Seria muito bom. 👍

**Comment by sahslima** [comment]
Oi, @Golluns666. Tudo bem?

Você consegue me contar um pouco mais de como esse documento em texto/pdf facilitaria seus estudos?

**Comment by dasilvaiuri** [comment]
Eu reescrevo o que aprendo em formato de tutorial no google docs, aí anoto dúvidas e algumas vezes, copio trechos do conteúdo para relembrar depois sem ter que procurar no curso, seria legal ter algo mais fácil nesse sentido.

**Comment by Golluns666** [comment]
> Oi, @Golluns666. Tudo bem?
> 
> Você consegue me contar um pouco mais de como esse documento em texto/pdf facilitaria seus estudos?

Oi Samantha.
Facilitaria para ter uma visão geral do curso e para revisar o conteúdo do mesmo, além de usar este mesmo documento para inserir comentários.

**Comment by sahslima** [comment]
Boa, pessoal!

Obrigada pelas especificações.

Estamos repensando os formatos de conteúdo e as sugestões vão contribuir bastante para a melhoria da experiência de estudo de vocês e outros alunos e alunas. 

Qualquer novidade nesse sentido, aviso por aqui. ;)
