### ISSUE TITLE
Ordenação no plano de estudo

### ISSUE THREAD

**Issue by deocir** [caelum/alura-funcionalidades#327]
Acho que seria interessante possibilitar a ordenação do plano de estudo conforme sequência de deseja-se estudar.
Seria útil na organização do plano de estudo.

**Comment by sahslima** [comment]
Oi, @deocir. Tudo bem?

Você se refere a organização de exibição dos planos de estudos criados por você (ou por outros alunos) na página inicial da plataforma ou a organização dos cursos dentro de um plano?

De qualquer forma, vou te contar outras opções que já possuímos hoje e talvez possam ajudá-lo na organização dos estudos:

**1.  Organização de formações na página inicial**

Você consegue deixar em destaque uma formação específica na sua tela inicial, é só clicar em "**_Mudar a Formação mostrada aqui_**", abaixo de "**_Progresso na Formação_**":

![image](https://user-images.githubusercontent.com/59886589/101086313-72599100-358f-11eb-9846-bcfe34621469.png)

Aí aparecerá uma nova página possibilitando a seleção da formação que deseja exibir no dashboard:
![image](https://user-images.githubusercontent.com/59886589/101086652-f1e76000-358f-11eb-943a-75ee7ea9e60a.png)


**2. Organização dos cursos em um plano de estudos próprio**

Dentro de um plano de estudos criado por você é possível modificar a ordem do conteúdo, clicando em "**_editar_**": 
![image](https://user-images.githubusercontent.com/59886589/101086970-5c000500-3590-11eb-8c75-ac4998de3897.png)

Na tela de edição do plano é possível segurar a "caixa" que representa o curso e movê-lo, colocando na ordem que desejar, antes ou depois de um determinado conteúdo.
![image](https://user-images.githubusercontent.com/59886589/101087218-ae412600-3590-11eb-9e30-f5502dd802b4.png)

Feito isso, é só finalizar clicando em "_**Salvar plano de estudos**_".


**3. Criar um plano de estudos próprio**

Nossa plataforma permite a criação de um plano de estudos personalizado, que pode ser público (visível para outros alunos) ou fechado (só você consegue visualizar).

Nele você pode adicionar o conteúdo que desejar e na sequência que mais fizer sentido para você. Basta acessar seu perfil no canto superior direito da tela > "_**Meus planos de estudo**_":
![image](https://user-images.githubusercontent.com/59886589/101088487-9074c080-3592-11eb-992e-ca36542d434d.png)

Isso abrirá uma nova página com o botão "**_Novo plano_**", é só clicar e iniciar a montagem do seu guia de aprendizagem. (:

![image](https://user-images.githubusercontent.com/59886589/101088632-be5a0500-3592-11eb-8dd8-29dc20f487ab.png)


**4. Favoritar cursos**

Você pode favoritar um determinado curso para iniciar seus estudos depois. É só clicar em "**_Outras ações_**" > "**_Favoritar_**", dentro do curso desejado:
![image](https://user-images.githubusercontent.com/59886589/101089052-6079ed00-3593-11eb-8e28-156fcef6b4a9.png)


Os cursos "favoritados" podem ser consultados clicando em "**_Aprenda_**" > "**_Meus cursos_**":
![image](https://user-images.githubusercontent.com/59886589/101089251-aafb6980-3593-11eb-8c65-9d29bedc9234.png)

Essa ação exibirá uma página com os cursos que salvou para ver depois.
![image](https://user-images.githubusercontent.com/59886589/101089327-c6ff0b00-3593-11eb-9341-1f3856393e5b.png)


Espero que esse conteúdo te ajude na organização dos estudos e aguardo sua resposta caso seu ponto seja uma melhoria ou modificação de algum deles. ;) 

Um abraço.

**Comment by deocir** [comment]
Eu precisava exatamente do item 2 que você explicou. Obrigado!
