### ISSUE TITLE
Cheatsheets

### ISSUE THREAD

**Issue by luissenko** [caelum/alura-funcionalidades#328]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

---
Uma boa adição aos cursos seria a criação de Cheatsheets que o aluno pudesse baixar e imprimir, como é possível ver [neste](https://www.codecademy.com/learn/introduction-to-javascript/modules/learn-javascript-introduction/cheatsheet) exemplo sobre JavaScript do pessoal do Codecademy. É uma ferramenta muito interessante para melhor absorção do que foi ensinado em aula, além de servir como ótimo recurso mnemônico.

**Comment by DorteCAS** [comment]
Adorei a ideia!
Seria um ótimo material para revisar o conteúdo no fim do curso. :)

**Comment by sahslima** [comment]
Oi, pessoal! Tudo bem? (:

Obrigada pela sugestão, @luissenko. 

Nós estamos revendo esse ponto e qualquer novidade nesse sentido, aviso por aqui! 

Um abraço!
