### ISSUE TITLE
Correção de erro em atividade + sugestão de opção pra corrigir problemas em atividades

### ISSUE THREAD

**Issue by luigiMinardi** [caelum/alura-funcionalidades#329]
No [curso "Python 3 parte 1: Introdução à nova versão da linguagem", Aula 5, Atividade 11](https://cursos.alura.com.br/course/python-3-introducao-a-nova-versao-da-linguagem/task/24573) tem a resposta correta (print abaixo) porém ela tem um erro.
![Screenshot 2020-11-29 at 10 52 39](https://user-images.githubusercontent.com/53359163/100538704-b6683100-3231-11eb-8f7b-11c21f64d029.png)
Testei no console pra ver se tinha mesmo esse erro e de fato tem, falta um espaço antes do "``1000.1``".
![Screenshot 2020-11-29 at 10 56 12](https://user-images.githubusercontent.com/53359163/100538699-a5b7bb00-3231-11eb-88ce-fba58afa5a9a.png)

Dai vem minha sugestão, atualmente quando clicamos no "``sugerir alteração``" de um exercício de múltipla escolha nós só podemos editar o enunciado do mesmo.

Sugiro então que coloquem algum outro botão de ``sugerir alteração`` pra cada resposta de múltipla escolha e um para o adendo do professor que aparece depois que você seleciona alguma resposta. (não me refiro a esse "``Correto.``" (da imagem acima) que tem professores que colocam uma explicação mais detalhada, mas sim ao texto adicionado depois das múltiplas escolhas)

Outra opção seria vocês colocarem para o ``sugerir alteração`` que aparece no topo da pagina ter "acesso" a todo o texto da página.

**Comment by steppat** [comment]
Oi Pessoal,

mexi na pergunta da atividade, ficou como:

```
"R$ {:6.1f}".format(1000.12)
```

**Comment by sahslima** [comment]
@luigiMinardi, além do erro corrigido, você sugeriu a possibilidade de alteração de todo o texto da atividade, incluindo o das respostas.

Compartilhei seu ponto com nosso time de desenvolvimento, mas enquanto não mudamos na plataforma, por gentileza, continue utilizando a "caixa de resposta" em `sugerir alteração` para sinalizar também os pontos das respostas e não só do enunciado.

Ao sugerir algo, essa possível "alteração" passa por revisão, então não há problemas em utilizar o mesmo campo por enquanto. Tudo bem? ;)

Qualquer novidade sobre esse tópico, aviso aqui. 

Um abraço!

**Comment by luigiMinardi** [comment]
> ... por gentileza, continue utilizando a "caixa de resposta" em `sugerir alteração` para sinalizar também os pontos das respostas e não só do enunciado.
> 
> Ao sugerir algo, essa possível "alteração" passa por revisão, então não há problemas em utilizar o mesmo campo por enquanto. Tudo bem? ;)

@sahslima então, eu tentei usar o 'sugerir alteração' normal mas como ele não mostra a parte das respostas/adendo o que eu fiz foi colocar o erro apenas no titulo do request e não mudar nada. Quando você faz isso a sugestão de alteração não é enviada por nenhuma alteração ter sido feita.

**Comment by sahslima** [comment]
Poxa, @luigiMinardi. Estamos com um bug nisso.

Vou repassar também e te aviso aqui quando a correção entrar no ar.

Obrigada pelo alerta novamente!

**Comment by luigiMinardi** [comment]
> Poxa, @luigiMinardi. Estamos com um bug nisso.
> 
> Vou repassar também e te aviso aqui quando a correção entrar no ar.
> 
> Obrigada pelo alerta novamente!

Bom dia @sahslima algum update sobre isso? Hoje encontrei novamente um erro de ortografia na plataforma e continua com o mesmo problema. Como já se passaram 6 meses e não recebi nenhum feedback vim perguntar aqui outra vez.

**Comment by designernatan** [comment]
oi @luigiMinardi 

por hora não puxamos essa por conta de outras frentes (challenges, cases, etc)

qualquer novidade você vai conseguir ver direto na plataforma, ok?

abracao!
