### ISSUE TITLE
Marcar como visualizado, "ouvido", lido ou assistido nas Formações

### ISSUE THREAD

**Issue by mautoz** [caelum/alura-funcionalidades#33]
Gosto bastante de seguir os cursos das "Formações", tem não apenas as disciplinas como postagens, podcast ou vídeos. Porém, como acompanho mais de uma formação, as vezes não lembro o que já "fiz". Os cursos mostram o andamento e finalização, o restante não! Seria interessante um "check" para dizer que já passamos por ali, como no "Exibindo na Dashboard".

**Comment by designernatan** [comment]
@mautoz valeu pela sugestão!

outra pessoa deu indícios em um teste de usabilidade que fizemos recentemente aqui que seria bacana algo assim

quão interessante para você seria se esse 'check' fosse de forma automática?

abcs!

**Comment by mautoz** [comment]
Muito bom! Assim seria mais fácil de visualizar posts já lidos ou podcasts já ouvidos!
