### ISSUE TITLE
Barra de Pesquisa nos planos de estudos publicos

### ISSUE THREAD

**Issue by Ana-Freitas** [caelum/alura-funcionalidades#330]
Nos planos de estudos públicos poderia ter uma barra de pesquisa para facilitar com que eu ache um plano adequado ao que estou procurando

**Comment by sahslima** [comment]
Oi, @Ana-Freitas! Tudo bem?

Estamos fazendo alguns ajustes nos mecanismos de pesquisa da plataforma e vamos considerar sua sugestão. Qualquer novidade, aviso por aqui. ;)

Obrigada por compartilhar!
