### ISSUE TITLE
Histórico de cursos

### ISSUE THREAD

**Issue by GabiGRamos** [caelum/alura-funcionalidades#332]
Fui procurar isso hoje no meu perfil e não tinha.
Meu objetivo era ver o ultimo curso que eu abri, que se não me engano foi sobre comunicação eficaz em apresentações, em um daqueles cursos que não tem dentro das formações, que aparecem somente nas atualizações de novos cursos. Porque eu queria recomendá-lo à uma pessoa que acho que faria bom proveito dele e que precisava de um conteúdo assim, mas não achei um histórico e nem lembro qual era o curso.

Seria bom se tivesse um histórico para os últimos cursos que acessamos (não só os que concluímos) com quantos dias fazem que acessamos e outras indicações talvez.

O que acham?

**Comment by DorteCAS** [comment]
Nessa página tem os seus cursos em andamento(lá embaixo):
https://cursos.alura.com.br/courses/mine

Esse curso não está lá?
(Acho que se você não iniciou, ele não aparece lá mesmo)

Se for esse caso, talvez dar uma procurada pelo histórico do chrome também te ajude.

**Comment by sahslima** [comment]
Oi, @GabiGRamos! Tudo bem?

Obrigada pela sugestão.

Por enquanto, uma opção para criar esse "histórico" é **favoritar** o curso.

Sempre que você entrar num curso, mesmo que não pretenda iniciar, mas achar interessante para olhar melhor depois, acesse `Outras ações` > `Favoritar`, dentro do curso desejado:
![image](https://user-images.githubusercontent.com/59886589/101790212-f906f480-3ae0-11eb-993a-446ce002ca94.png)

Esses cursos vão para [essa área](https://cursos.alura.com.br/courses/mine), que o @DorteCAS mencionou, e ficam sinalizados como "**Cursos salvos para mais tarde**":
![image](https://user-images.githubusercontent.com/59886589/101790925-bb569b80-3ae1-11eb-9177-9ce95d58fab8.png)

Para tirar o curso dali é só "desfavoritar". (:

Qualquer novidade na linha do que sugeriu, aviso por aqui.

Um abraço.
