### ISSUE TITLE
Barra de Busca na página de guia de estudos públicos

### ISSUE THREAD

**Issue by brunounion** [caelum/alura-funcionalidades#333]
Encontrar guias de estudo feitos por outros usuários é difícil na página de guia de estudos da comunidade:
https://cursos.alura.com.br/planos-estudos-publicos

**Comment by sahslima** [comment]
Oi, @brunounion! Tudo bem?

Estamos fazendo alguns ajustes nos mecanismos de pesquisa da plataforma e vamos considerar sua sugestão. Qualquer novidade, aviso por aqui. ;)

Obrigada por compartilhar!
