### ISSUE TITLE
Exercícios

### ISSUE THREAD

**Issue by MathiasOG** [caelum/alura-funcionalidades#334]
Gostaria que tivesse uma parte de exercícios, onde poderiam ter exercícios verificados e com respostas e/ou exercícios da comunidade, criado de um aluno pra outro, com a possibilidade de ser verificado por um professor.
Assim também seria possível os professores proporem atividades a serem feitas e deixar o link para uma atividade mais complexa ao invés das atividades de múltipla escolha.

desde já agradeço.

**Comment by sahslima** [comment]
Olá, @MathiasOG!

Obrigada pela sugestão.

Estamos revendo nossa área de relacionamento da comunidade e vamos considerar seu ponto ao desenvolver futuras melhorias.

Qualquer novidade nesse sentido, avisamos por aqui. ;)

Um abraço.
