### ISSUE TITLE
Permitir comentar tópicos já respondidos

### ISSUE THREAD

**Issue by DorteCAS** [caelum/alura-funcionalidades#335]
Mais de uma vez eu me senti motivado a comentar um tópico no fórum mas, como ele já estava respondido, eu não conseguia comentar (e como não era algo grande o suficiente para gerar um novo tópico, eu não criava um)
Além disso, permitir comentários posteriores permite quem gerou o tópico marcar como resolvido sem peso na consciência, além de deixar mais agrupado comentários que acabariam gerando novos tópicos mas está relacionado com o anterior.

**Comment by sahslima** [comment]
Oi, @DorteCAS! Tudo bem?

Obrigada pela sugestão.

Entendemos o seu ponto, faz sentido, porém inserimos essa "trava" nos tópicos marcados como solucionados para evitar reabertura muito tempo depois (meses ou até mesmo anos) e notificar usuários que faziam parte da discussão e já não tem mais interesse no assunto.

Essa é uma prática adotada não só na Alura, como em outros fóruns também. Uma opção para o cenário que descreveu seria iniciar um novo tópico _linkando_ o que já foi fechado. Mesmo que seja uma pequena reflexão, pode sim contribuir com o aprendizado de outros alunos e alunas. (: 

De qualquer modo, estamos trabalhando em mais formas de proporcionar essa interação e compartilhamento de insights entre a nossa comunidade. As futuras iniciativas nesse sentido devem ajudar com essa parte. 

Mensalmente a gente publica um artigo como [este](https://www.alura.com.br/artigos/confira-as-novidades-de-novembro), mostrando as novidades e qualquer melhoria nesse sentido, divulgaremos por lá.

Um abraço.
