### ISSUE TITLE
Novos projetos para quem tem o plano Premium Plus e Max

### ISSUE THREAD

**Issue by LucasFGomes** [caelum/alura-funcionalidades#336]
Deveria ter outros projetos que são avaliados pelos instrutores, atualmente só tem 7, e a maioria não é do meu interesse e acredito que é de vários que tem esse plano (Premium Plus e Max). 
Poderia ter projeto voltado para a galera de front-end.

**Comment by sahslima** [comment]
Oi, @LucasFGomes!

Obrigada pela sugestão.

Estamos revendo a área de projetos e qualquer novidade sobre esse assunto, aviso por aqui. ;)

Um abraço.
