### ISSUE TITLE
Sugestões para a página de perfil

### ISSUE THREAD

**Issue by klauskpm** [caelum/alura-funcionalidades#338]
## Sugestão
Mover as páginas `/points` e `/user/{USER}/actions` para dentro da página `/user/{USER}`, e mudar o link do gráfico de atividades para `/user/{USER}`.

A sessão de `/points` poderia até ser um tooltip/dialog, ou algo do tipo, dentro da página do perfil.

## Problemas que procuro resolver
1) Todo dia eu clico pelo menos uma vez no gráfico de atividades, pensando que vou ver minha página de perfil, só pra me lembrar que estou cometendo o mesmo erro novamente.
![image](https://user-images.githubusercontent.com/690945/101822837-b35e2200-3b08-11eb-8d29-fe3f8661ca8e.png)

2) As informações que importam pro gráfico de atividades (histórico e explicação), estão em páginas diferentes dele. Então eu preciso visitar duas ou três páginas para ter todas as informações que preciso.

**Comment by sahslima** [comment]
Oi, @klauskpm!

Obrigada pela sugestão.

Estamos discutindo melhorias para a página de perfil e vamos considerar seus pontos. ;) 

Qualquer novidade, aviso por aqui.

Um abraço.
