### ISSUE TITLE
Formações em plano de estudos

### ISSUE THREAD

**Issue by jashscript** [caelum/alura-funcionalidades#339]
Implementar a opção de adicionar formações nos planos de estudo criados.
Eu só não uso os planos de estudos porque eu teria que colocar um por um dos cursos das formações que pretendo completar.

**Comment by sahslima** [comment]
Oi, @jashscript! Tudo bem?

A boa notícia é que já existe essa possibilidade!

Para adicionar uma formação, você vai criar um plano de estudos normalmente e no momento de `Adicionar novo passo`, basta inserir o nome da formação desejada e `buscar` no campo de pesquisa.

![image](https://user-images.githubusercontent.com/59886589/102530847-473b6b00-4080-11eb-9ab6-9c0337849fd0.png)


Feito isso a busca vai retornar os resultados encontrados na plataforma e aí você clica em `adicionar`.

De qualquer forma, obrigada por levantar esse ponto, vamos melhorar a comunicação dessa área. ;)
