### ISSUE TITLE
Erro Gabarito Javascript

### ISSUE THREAD

**Issue by brunosilvadaniel** [caelum/alura-funcionalidades#34]
No curso de Javascript: Programando na Linguagem web, há um erro no gabarito da ativadade numero 6 da aula 5, onde a alternativa correta seria a letra D, mas está contando como letra B:
![image](https://user-images.githubusercontent.com/42727140/72255801-73d04280-35e6-11ea-848c-d6213dd36233.png)

**Comment by designernatan** [comment]
@brunosilvadaniel a D é a única incorreta? Não seria a "B" mesmo?
