### ISSUE TITLE
Dashboard de exercícios

### ISSUE THREAD

**Issue by fdrigui** [caelum/alura-funcionalidades#340]
*Notas: Talvez a palavra **Dashboard** não seja a mais adequada. Me refiro aqui a tela de exercícios do curso, principalmente de "Ciência de Dados", que são os que eu estou fazendo no momento.*

## Problema
Meu problema está com a perda de tempo em troca de janelas quando se usa o Google Colab para executar os exercícios que estão sendo propostos na aula, além de minimização de foco, uma vez que ao trocar entre janelas web aumenta-se o risco de dispersar para outra atividade.
1. Perda de tempo ao se trocar de janelas entre a da Aula na plataforma da Alura e a página do Google Colab onde se faz os exercícios.
2. Aumento da chance de perder o foco, uma vez que na troca de páginas existe o risco de mudar para outras páginas ou temas.
3. Otimizar o curso, tirando impedimentos relacionados com outras plataformas.

## Funcionalidade
Mudar a tela de atividades, ou exercícios que envolvem programação de maneira a ter 3 componentes na dentro da tela:
1. Exercício. Um componente onde se pode escrever o exercício e todos os detalhes necessários para a execução.
2. Arquivo de código/ plot/ etc. Um componente onde se permite escrever o trecho de código desejado, com algum tipo de linting. Esse componente ficaria lado a lado com os exercícios, minimizando troca de tela e embarcando toda a experiência de ensino num único lugar.
3. Shell. Uma janela com o shell rodando o Kernel do Ipython ou do R por traz de maneira que se pode executar o código e avaliar os resultados de saída.

Exemplo:
![Proposta](https://user-images.githubusercontent.com/13628484/101914708-6418ff80-3ba3-11eb-8424-fffc9c335322.jpg)

4. Um botão de "confirmar" roda o código e avalia se o output é esperado ou não e aprova ou não o exercício.
5. Um botão de "dica" poderia fornecer uma base para o aluno que errou ter mais informações para tentar novamente.
6. Quando tem-se a dica e mesmo assim não se resolve o exercício, um botão de "ver resposta" apresenta a resposta para o problema.
7. Poderia existir um sistema de *gamificação* quando se responde sem a dica ganha-se alguns pontos, quando usa a dica, menos e quando vê a resposta não ganha pontos.
8. Além de responder o exercício completo, alguns tipos de exercícios com pedaços de código faltando completar poderia existir, entre outros.
9. É possível assim contar uma história, ensinar alguns temas específicos e os exercícios estarem relacionados com a história e ter faltando no código somente a funcionalidade que se está aprendendo.

## Trade-off
Existe um tradeoff nessa situação: Quando eu faço o exercício pelo Google Colab por exemplo, eu tenho um item que pode de certa maneira ser adicionado em meu portifólio, então esse é um ponto positivo. Faz-se um projeto e esse projeto a medida que via sendo executado, vai servindo para provar o seu conhecimento. Por outro lado, eu acredito que os benefícios de de se ter uma plataforma mais facil de mexer e que me permite ficar mais tempo focado superam o de ter um portfólio, uma vez que normalmente os exercícios tem pouca profundidade.

**Comment by sahslima** [comment]
Oi, @fdrigui! Tudo bem?

Obrigada pelo detalhamento da sugestão, você levantou pontos importantes. Vamos considerá-los em futuras melhorias. ;)

Qualquer novidade nesse sentido, aviso por aqui.

Um abraço.
