### ISSUE TITLE
Botão de confirmar exercício de alternativa

### ISSUE THREAD

**Issue by fdrigui** [caelum/alura-funcionalidades#341]
## Problema
Particularmente eu me atrapalho um pouco com a responsividade da tela de exercícios com alternativas (principalmente com as de múltiplas alternativas)
1. Missclick na resposta errada, uma vez que o mouse normalmente fica próximo as respostas (normalmente eu coloco o mouse em cima da resposta que eu estou lendo)
2. Quando é múltipla escolha, eu acho que é interessante marcar e desmarcar a vontade antes de avaliar

Exemplo:
* Situação 1
* Situação 2
* Situação 3
Resposta:
(a) Situação 1 e 2 correta
(b) Situação 1 e 3 correta
(c) Situação 2  e 3 correta
(d) Todas as situações corretas
(e) Nenhuma situação correta

Como eu faço esse tipo de exercício:
* Primeiro eu leio a 1, imagine que esteja certo, então eu marco a alternativa (a), (b) e (d)
* Depois eu leio a 2, imagine que esteja errado, então eu desmarco a (b) e a (d) e chego na resposta

Esse exemplo não é de multipla escolha, mais mostra como eu costumo fazer.

## Funcionalidade
A funcionalidade consiste em permitir a marcação da resposta selecionada, mais somente avaliar se está correta ou não mediante a um clique em um botão de confirmação.

**Comment by sahslima** [comment]
@fdrigui, obrigada por compartilhar!

Tanto essa quanto [sua outra sugestão](https://github.com/caelum/alura-funcionalidades/issues/340) sobre exercícios, ficarão em nosso radar para futuras melhorias.

Um abraço.
