### ISSUE TITLE
Opção de refazer cursos

### ISSUE THREAD

**Issue by gabrielareia** [caelum/alura-funcionalidades#343]
Olá, recentemente comecei a fazer novamente um curso que fiz há um tempo atrás mas acabei esquecendo algumas coisas.

Mas aparentemente não existe opção de refazer o curso, então o curso não fica aparecendo na Dashboard, e nem salva a aula e o vídeo em que eu parei quando fecho o site e abro outro dia. Seria legal se ele se comportasse como na primeira vez que fazemos o curso.

**Comment by MarcoNasc** [comment]
Acho isso bem interessante também, já aconteceu de eu querer revisar alguns conteúdos por meio dos exercícios, mas não tem uma opção de "reset". Então já vejo a resposta certa de cara e nem exercito de fato, somente leio as perguntas e os textos do porque a resposta estar certa ou errada.

**Comment by sahslima** [comment]
Oi, pessoal!

Obrigada pelos pontos que levantaram, estamos discutindo formas de melhorar essa experiência para alunos e alunas que desejam rever algum conteúdo.

Qualquer novidade, aviso vocês. ;)

Um abraço.
