### ISSUE TITLE
Mostrar mais opções de redes sociais dos instrutores

### ISSUE THREAD

**Issue by maisonsouza** [caelum/alura-funcionalidades#344]
Eu gostaria que tivesse mais opções de contato por redes sociais dos instrutores acho essencial o linkedin, mas no caso de cursos de programação e de tecnologia seria interessante se tivéssemos por exemplo o Github, Discord, Twitter, Instagram, Facebook , Canal do Youtube do instrutor muitas vezes o instrutor comenta algo interessante na aula que não dá pra entender muito bem pela dicção, e nem está nas transcrições. E também gostaríamos de talvez saber um pouco mais do trabalho de alguns instrutores. Não seria algo obrigatório lógico nem todos tem e nem todos querem compartilham mas para os que tem e queiram seria excelente.

![image](https://user-images.githubusercontent.com/11163368/102131614-d8b0a000-3e28-11eb-94cd-01faeaabc576.png)
A mudança seria nessa área do curso

**Comment by sahslima** [comment]
Perfeito, @maisonsouza!

Como você pontuou, nem todos os instrutores querem compartilhar outros canais de contato (muitas vezes de uso pessoal), mas há sim outras plataformas que podem fazer sentido nesta área.

Vamos discutir sua sugestão internamente e qualquer novidade, te aviso por aqui. ;)

Obrigada por compartilhar.
