### ISSUE TITLE
Arquivar caderno

### ISSUE THREAD

**Issue by nicsmuller** [caelum/alura-funcionalidades#345]
Após a finalização do curso, o caderno de cada módulo poderia ficar salvo no perfil ou em algum outro lugar acessível.
Pois quando concluímos o curso o caderno se perde, fica apenas disponível se voltarmos à algum vídeo do curso para vê-lo.

**Comment by sahslima** [comment]
Oi, @nicsmuller!

Obrigada pela sugestão.

Estamos repensando alguns aspectos do caderno e ela vai contribuir para futuras melhorias.

Qualquer novidade nesse sentido, te aviso por aqui. ;)
