### ISSUE TITLE
Atalhos de teclado para as principais funcionalidades do Meu Caderno

### ISSUE THREAD

**Issue by italosiqueira** [caelum/alura-funcionalidades#346]
Implementar atalhos de teclado universais para o _Meu Caderno_. Alguns exemplos são:

- _hotkey_ para exibir o _Meu Caderno_ com o cursor já posicionado para uma nova anotação;
- _hotkey_ para exibir um componente sobreposto à tela para entrada de texto que, ao finalizarmos com _Enter_, adiciona o conteúdo ao final do caderno utilizado o conteúdo digitado.

**Comment by sahslima** [comment]
Obrigada pela sugestão, @italosiqueira!

Qualquer novidade nesse sentido, aviso por aqui. ;)

Um abraço.
