### ISSUE TITLE
Certificado em PDF

### ISSUE THREAD

**Issue by andreclaret** [caelum/alura-funcionalidades#347]
Os certificados poderiam ser disponibilizados em PDF. Isso facilita para armazenar e melhora bastante o que existe atualmente, que caso queira imprimir, fica como uma página da internet e perde bastante a qualidade que um certificado deva ter.

E o PDF deve ter na frente a parte gráfica e no verso, a parte formal (dos conteúdos estudados). 
Isso pode valer também para os certificados das formações.

**Comment by sahslima** [comment]
Oi, @andreclaret! Tudo bem?

Obrigada pela sugestão.

Devemos ter novidades sobre o certificado em breve, te aviso aqui quando sair. ;)

Um abraço.
