### ISSUE TITLE
Recursos externos do curso para download inicial

### ISSUE THREAD

**Issue by ThomasMoraes02** [caelum/alura-funcionalidades#349]
Seria interessante que ao iniciar o curso, o aluno(a) tivesse de cara o projeto final e inicial do curso para fazer download. Assim evitaria de ter algum problema durante o projeto e precisar avançar até o final para pegar o arquivo final.

**Comment by sahslima** [comment]
Oi, @ThomasMoraes02! Tudo bem?

Estamos discutindo internamente como melhorar a experiência dessa área de exercícios e vamos considerar seu ponto.

Qualquer novidade, te aviso aqui. ;)

Um abraço.
