### ISSUE TITLE
Decrementar as opçoes de velocidade na tecla z

### ISSUE THREAD

**Issue by maisonsouza** [caelum/alura-funcionalidades#35]
Atualmente temos o controle pelo teclado de incrementar as opções de velocidade dos vídeos na tecla X, seria excelente termos como **decrementar** as opções de velocidade na tecla Z, tornando o player mais funcional ainda.

**Comment by designernatan** [comment]
@maisonsouza valeu pela sugestão!

pessoalmente uso uma extensão que tem esse controle nas teclas 'a' e 's'

**Comment by designernatan** [comment]
colocando o link da thread falando mais disso aqui no Alura Funcionalidades e fechando essa

https://github.com/caelum/alura-funcionalidades/issues/1
