### ISSUE TITLE
Curso de Groovy/Grails no Intellij

### ISSUE THREAD

**Issue by regisds28** [caelum/alura-funcionalidades#350]
Há uma carência grande por profissionais experientes nesta linguagem, baseada em Java. Eu, atualmente, trabalho em uma empresa que utiliza esta linguagem juntamente com o Grails e o MongoDb e não acho nenhuma curso que eu possa me aprofundar.

**Comment by sahslima** [comment]
Oi, @regisds28! Tudo bem?

Temos um [formulário para sugestão de cursos](https://docs.google.com/forms/d/e/1FAIpQLScwKyaSvuFXK9SmMJoLPuYAS2qD_XAAnZPxMZij9qVeflbhBg/viewform). 

Fique à vontade para registrar não só essa, como todas as outras ideias sobre cursos que tiver. :D

Um abraço.
