### ISSUE TITLE
Botões avançar e voltar nos vídeos

### ISSUE THREAD

**Issue by brunosantanati** [caelum/alura-funcionalidades#351]
Poderia ter botões para avançar e voltar(em torno de 10 segundos por exemplo) nos vídeos. No Youtube no mobile eu consigo avançar e voltar dando dois cliques na tela, na Udemy tenho botões para isso.

**Comment by sahslima** [comment]
Oi, @brunosantanati! Tudo bem?

Obrigada pela sugestão, vamos considerar em futuras melhorias do player de vídeo. ;)

Um abraço.
