### ISSUE TITLE
Acesso a guia com links pros podcasts no app da alura

### ISSUE THREAD

**Issue by GPSchon** [caelum/alura-funcionalidades#352]
No site para encontrar os podcasts eu abro a aba aprenda é possuo um acesso rápido e sou direcionado para uma tela com Abas das temporadas e os links de cada episódio

Mas quando acesso pelo celular através do app não possuo essa mesma função o que dificulta escolher algum pra ouvir em algum pra um momento qualquer

**Comment by sahslima** [comment]
Oi, @GPSchon! Tudo bem?

Obrigada pela sugestão, vamos considerar seu ponto em futuras melhorias.

Um abraço.

**Comment by felipetorres** [comment]
Oi @GPSchon, na próxima atualização já teremos isso no app Android e assim que terminarmos no app iOS vamos mandar pra loja também, beleza?
