### ISSUE TITLE
"Grupo de estudos"

### ISSUE THREAD

**Issue by jeffersonAraujo2012** [caelum/alura-funcionalidades#353]
Olá Alura! Olá pessoal!

Minha sugestão é que houvesse a possibilidade dos usuários criarem pequenos grupos de estudos para poderem criar projetos e por em prática o que aprendeu, aumentando o portfólio. Sugiro isso porque não há projetos disponível para diversas formações, e seria interessante conseguir agrupar pessoas que passaram pela mesma formação, ou outras formações. A experiência seria muito boa pois os alunos poderiam formar internamente grupos multidisciplinares (front-end, back-end, ui/ux, documentação e projeto).

O projeto gerado não necessariamente deveria ser avaliado por um professor (afinal isso poderia ser inviável), mas ere poderia ser publicado (com uma referencia git) e alunos fora do grupo poderiam dar sugestões. Como se fosse um fórum. Bem... é isso. De qualquer forma vou tentar reunir esse grupo para criar projetos práticos e com foco em estudo mesmo sem essa funcionalidade da plataforma.

Grato pela atenção!

**Comment by vandersonlb** [comment]
Oi Jefferson, achei muito legal sua ideia, tem todo meu apoio.
Eu particularmente acho a questão de **exercícios** e **projetos** um ponto fraco da plataforma. 
Eu não sei se nos outros planos superiores ao Premium é melhor, mas eu duvido.

Falta uma ferramenta que coloque aquilo que foi ensinado a prova, seria legal colocar esses conhecimentos a prova antes de entrar no mercado de trabalho. E fazer um projeto em grupo seria uma boa ferramenta.

**Comment by sahslima** [comment]
Oi, pessoal! Tudo bem?

Obrigada pelo compartilhamento desses pontos.

No próximo semestre, devemos ter novidades na parte de **comunidade** e **projetos** que consideram essas sugestões. Aviso vocês por aqui. ;)
