### ISSUE TITLE
Apagar post no fórum

### ISSUE THREAD

**Issue by vandersonlb** [caelum/alura-funcionalidades#354]
Eu, como aluno, gostaria que fosse possível apagar um post depois de enviado. 
Hoje só é possível editar, mas, as vezes o aluno pode querer **apagar** o post por diversas razões, principalmente se ele não for nem respondido e/ou não foi concluído ainda.

**Comment by sahslima** [comment]
Oi, @vandersonlb. Tudo bem?

Estamos revendo essa área da plataforma e vamos considerar seu comentário. ;)

Qualquer novidade nesse sentido, aviso por aqui.

Um abraço.
