### ISSUE TITLE
Ocultar curso feito do perfil público Alura

### ISSUE THREAD

**Issue by vandersonlb** [caelum/alura-funcionalidades#355]
Eu, como aluno, gostaria de poder escolher quais cursos concluídos ficarão visíveis no meu perfil público da Alura, no **alura.com/user/USER**, do mesmo jeito que eu posso escolher se o _Plano de Estudos_ será público ou privado.

Ter esse perfil é muito bom, você pode compartilhar com outros seu progresso, mas bom algum motivo o aluno pode querer que determinados cursos apareçam ou não nesse perfil.

**Comment by sahslima** [comment]
Oi, @vandersonlb.

Obrigada pela sugestão.

Qualquer novidade nesse sentido, aviso por aqui. ;)

Um abraço.
