### ISSUE TITLE
Projetos - Melhor explicação e requisitos mínimos 

### ISSUE THREAD

**Issue by albertkeriks** [caelum/alura-funcionalidades#357]
A aba/página de Projetos (com atividades para testar conhecimento), deveria ter uma explicação mas detalhada em cada projeto  e na página inicial também.
Além de uma lista de conhecimentos mínimos que se deve ter para estar apto a fazer as atividades dos Projetos. Como quais cursos ou formações deve ter concluído antes.

**Comment by sahslima** [comment]
Oi, @albertkeriks!

Estamos revendo a área de **projetos** e devemos ter novidades no próximo semestre.

Quando elas entrarem, te aviso por aqui. ;)

Um abraço.
