### ISSUE TITLE
Carga horária do curso visível no app mobile

### ISSUE THREAD

**Issue by thiago-vieira** [caelum/alura-funcionalidades#358]
Seria interessante que a carga horária individual de um curso fosse apresentada no aplicativo. Hoje só é possível visualizar está informação pela versão web, no desktop.

**Comment by sahslima** [comment]
Oi, @thiago-vieira! Tudo bem?

Obrigada por compartilhar. 

Estamos realizando melhorias no app e aviso por aqui quando tivermos novidades nesse sentido.  ;)

Um abraço.
