### ISSUE TITLE
Modo noturno em todo o site ou dashboard

### ISSUE THREAD

**Issue by Aiam32** [caelum/alura-funcionalidades#359]
Só para relembrar....
Serie relevante e confortável a expansão do modo noturno além da plataforma de estudo.

Muito obrigado!

**Comment by MarcoNasc** [comment]
Nossa, tô querendo isso faz tempo hehe

**Comment by sahslima** [comment]
Oi, pessoal!

Essa possibilidade está no nosso radar, mas ainda não conseguimos citar datas.

Qualquer novidade, avisamos por aqui! ;) 

Um abraço.
