### ISSUE TITLE
Botão de baixar projeto do Curso

### ISSUE THREAD

**Issue by JoaoRuani** [caelum/alura-funcionalidades#36]
Todo ou quase todos os curso possuem um projeto, seria mais fácil se nesses cursos tivesse um botão de baixar projeto no menu lateral. Atualmente é necessário procurar em qual das lições o instrutor colocou o link.

**Comment by designernatan** [comment]
@JoaoRuani  Ter que ficar caçando o projeto quebra um pouco a experiência de estudo mesmo

Temos algo assim rabiscado aqui, sem datas mas está no roadmap :)

valeu pela sugestao!
