### ISSUE TITLE
Filtro na Busca

### ISSUE THREAD

**Issue by MarcoNasc** [caelum/alura-funcionalidades#360]
Gostaria que na barra de busca houvesse um filtro, já que ao procurar um termo aparecem tantos os cursos, como formações, podcasts e textos. Portanto, acho que seria bem interessante poder usar esse filtro se eu quisesse que aparecessem somente cursos, por exemplo.

**Comment by TiagoRR2** [comment]
Super válido! Acho que seria de grande ajuda

**Comment by sahslima** [comment]
Obrigada pela sugestão, @MarcoNasc!

Vamos considerar nas melhorias do campo de busca. ;)

Qualquer novidade nesse sentido, aviso por aqui. 

Um abraço.
