### ISSUE TITLE
Mais exercícios

### ISSUE THREAD

**Issue by MarcoNasc** [caelum/alura-funcionalidades#361]
Uma das coisas que sinto falta às vezes é em relação a quantidade de exercícios, que acho pouca. Creio que cada sessão deveria ter pelo menos umas 10 questões para podermos fixar melhor o conhecimento e os exercícios serem mais específicos e aprofundados.

**Comment by sahslima** [comment]
Oi, @MarcoNasc.

Obrigada pela sugestão.

Estamos elaborando mais formas de proporcionar essa fixação de conteúdo para nossa comunidade de alunos e alunas, além dos exercícios. No próximo semestre teremos novidades. ;)

Um abraço.
