### ISSUE TITLE
Certificado de Acordo com o guia

### ISSUE THREAD

**Issue by charlesrodrigo** [caelum/alura-funcionalidades#362]
Seria interessante criar um guia e pode emitir um certificado referente a esse guia, poderia ser algo parecido com o emitir todos os certificados, porem iria trazer apenas os cursos que eu quero e com o nome do meu guia.

**Comment by sahslima** [comment]
Oi, @charlesrodrigo! Tudo bem?

Obrigada pela sugestão. 

Por enquanto, ainda não temos essa opção na plataforma. Porém, caso necessite, é possível solicitar uma "declaração" personalizada com o nosso time de experiência do aluno, através dos nossos [canais de atendimento](https://www.alura.com.br/contato). 

Nela você pode definir quais dos cursos já concluídos devem constar. ;)

Um abraço.
