### ISSUE TITLE
Colocar legendas nos vídeos

### ISSUE THREAD

**Issue by fdnadler** [caelum/alura-funcionalidades#363]
Tenho uma pessoa na minha equipe que é surda. Para ela poder realizar os cursos é fundamental que o vídeo tenha legendas. O formato atual, com a transcrição em texto abaixo do vídeo é péssima, pois além de não ficar visível na mesma tela que o vídeo (ela teria que separar em dois monitores ou duas janelas do navegador) o texto não está sincronizado com o vídeo, dificultado demais o aprendizado. Uma legenda sincronizada com o vídeo possibilitaria que ela cursasse os conteúdos.

**Comment by sahslima** [comment]
Oi, @fdnadler.

Pedimos desculpas pela experiência que estamos entregando neste sentido. Sabemos que ainda precisamos evoluir em pontos como o que levantou para melhorar a acessibilidade da plataforma.

Sua sugestão ficará em nosso radar para futuras melhorias. 

Obrigada por compartilhar!
