### ISSUE TITLE
Interação entre modo noturno e adblockers

### ISSUE THREAD

**Issue by Noriller** [caelum/alura-funcionalidades#364]
Percebi que dependendo da quantidade de adblockers que se tem, quando muda a pagina enquanto em modo noturno, a página tem um "flash" entre uma página e outra.

Uso o Alura em diferentes computadores e mesmo profiles então é visível que usando vários adblockers há esse flash (acaba sendo literalmente um flash, já que pula de tela escura pra clarão de luz e de volta pra tela escura).

Estou com apenas 2 ligados neste e veja como está:
https://user-images.githubusercontent.com/54413263/103041690-e4514480-4555-11eb-93c7-d45f8db606a5.mp4

**Comment by luigiMinardi** [comment]
Isso é o load da pagina. A Alura não é uma SPA e n tem um placeholder pra fingir que ta carregando o conteúdo antes de ele aparecer então acontece isso ai.

**Comment by sergiolopes** [comment]
Oi pessoal, realmente o fato de não sermos uma SPA deixa esse efeito um pouco mais visivel. Mas o que o @Noriller falou tem razao, parece que tem algo no script do GTM que deixa esse efeito ainda mais evidente. Vamos tentar melhorar aqui!

(tecniquês: tem um tal script antioscilação do GTM mas que faz a pagina piscar, a gente vai remover ele https://support.google.com/optimize/answer/7100284?hl=pt-BR)
