### ISSUE TITLE
Sugestão: "Próximo curso" dentro da página de um curso concluido

### ISSUE THREAD

**Issue by Noriller** [caelum/alura-funcionalidades#365]
![image](https://user-images.githubusercontent.com/54413263/103139101-c26fd300-46b7-11eb-815e-0fecaa9e261a.png)

Já mostra quais são os "pré-requisitos" e as "formações" ao qual o curso pertence.

Desta maneira, seria interessante mostrar qual seria o "próximo curso" de cada formação que tem aquele curso:

FORMAÇÃO COM ESSE CURSO
____Python
________Python parte 3

Poderia ser com sanfonas, por exemplo.

**Comment by sahslima** [comment]
Obrigada pela sugestão, @Noriller!

Qualquer novidade nesse sentido, avisamos por aqui. ;)
