### ISSUE TITLE
Sinto falta de um glossário na alura

### ISSUE THREAD

**Issue by TiagoRR2** [caelum/alura-funcionalidades#366]
TL;DR: para quem está começando a estudar, existem vários termos que podem "sufocar" os alunos, então seria legal ter uma seção no site para explicar cada um.

Estou iniciando os meus estudos na área de programação, e às vezes ao ouvir alguns termo me sinto um pouco perdido. API, back-end, front-end, etc.
Podia existir uma área no site da alura para explicar de maneira rápida e simplificada (de preferência em vídeo) o que são esses termos.

Um exemplo: no próprio site da alura, na busca eu digitei front-end. Apareceram vários, cursos, artigos, etc. Um pouco confuso (um dos "problemas" da alura, que tem muita coisa boa mas às vezes não sabemos nos direcionar haha).
Ao procurar por back end, eu me deparei com o vídeo do professor Vinícius dias https://cursos.alura.com.br/qual-e-a-diferenca-entre-back-end-e-front-end--c174 , super didático, relativamente curto (14 min) e deu pra eu entender o que é back-end e front-end (e ele deu exemplos!) para não ficar confuso ao ler artigos ou ouvir podcasts.
Isso seria bem útil pra vários termos (API, por exemplo, ainda estou um pouco confuso sobre o que é e como se aplica). E as opções desse "glossário" poderiam aparecer no início da lista de sugestões ao fazer uma busca também.

**Comment by sahslima** [comment]
Oi, @TiagoRR2! Tudo bem?

Ótima sugestão.

Atualmente nós possuímos a área [Alura+](https://cursos.alura.com.br/alura-mais) dentro da plataforma, justamente com o objetivo de trazer conteúdo complementar aos cursos da Alura. Dá para acessá-la através do menu `APRENDA` > `ALURA+`:
![image](https://user-images.githubusercontent.com/59886589/103772689-b0235c80-5008-11eb-9cdf-7f3d1308a607.png)

Dentro dessa página você conseguirá visualizar conteúdos específicos de cada categoria da plataforma, como **Front-end**.

Porém, estamos trabalhando em melhorias na parte de busca de conteúdo do site e pretendemos dar aos alunos e alunas mais possibilidades de "filtro" ao procurar por determinado assunto. Assim que tivermos novidades sobre este ponto, avisamos aqui. ;)

Um abraço.
