### ISSUE TITLE
Pequeno erro na visualização do markdown do forum ao editar/enviar uma resposta

### ISSUE THREAD

**Issue by luigiMinardi** [caelum/alura-funcionalidades#367]
Quando você está editando/publicando uma resposta(não testei com perguntas) se você quiser fazer um "`*`" ficar highlighted (-> ``*`` <- assim) você deveria ter a visualização ja em highlight no preview porem ele apenas centraliza e deixa o "`*`" pequeno

![Screenshot 2020-12-28 at 17 30 29](https://user-images.githubusercontent.com/53359163/103229758-03741b80-4934-11eb-8909-42be62eedf26.png)

(Eu coloquei o "**" antes e depois por pensar que sairia igual o preview e tentei pelo menos colocar em itálico já que com "``" eu escaparia a formatação do "*" do meio)

![Screenshot 2020-12-28 at 17 31 05](https://user-images.githubusercontent.com/53359163/103229762-04a54880-4934-11eb-99a2-5200e302c6b9.png)

Quando você envia ele sai já com a formatação certa.

**Comment by sahslima** [comment]
Oi, @luigiMinardi! Tudo bem?

Na verdade não é um bug, por enquanto, a estilização do _preview_ ainda é um pouco diferente da que aparece na resposta.

De qualquer forma, obrigada por levantar este ponto, vamos manter no radar para futuros ajustes do fórum. ;)

Um abraço.
