### ISSUE TITLE
Chat em tempo real

### ISSUE THREAD

**Issue by lucaomartins** [caelum/alura-funcionalidades#368]
Sinto falta de um sistema para conversas em tempo real na Alura. Temos o fórum que ajuda muito pra ter uma interação com os outros alunos mas não é o mesmo que um bate papo em tempo real.

Minha susgestão seria o uso de ferramentas já conhecidas como slack e discord ou até mesmo na plataforma da Alura. Um espaço preferencialmente para os alunos conversarem e fazerem networking.

Uma funcionalidade de chat privado tambem seria interessante se não tiver algum impedimento.

Vi que já houveram algumas outras sugestões abertas parecidas, mas ainda acho que o sistema de comunicação entre os alunos na Alura ainda é muito fraco.

**Comment by sahslima** [comment]
Oi, @lucaomartins! Tudo bem?

Obrigada pela sugestão.

Estamos trabalhando em pontos da plataforma que proporcionem uma melhor experiência de comunicação e compartilhamento de conteúdo entre nossos alunos e alunas. 

Ainda esse semestre devemos ter novidades nesse sentido. Te avisamos por aqui. ;)

Um abraço.
