### ISSUE TITLE
Certificado de cursos por intervalo de datas.

### ISSUE THREAD

**Issue by oLuizGuilherme** [caelum/alura-funcionalidades#369]
Bom dia.

Gostaria de sugerir uma opção em que o usuário possa solicitar os certificados de cursos realizados entrem um intervalo de datas. A minha empresa tem um banco de horas que consta o tempo de cursos/treinamentos e especializações de cada colaborador. Se essa funcionalidade existisse, eu conseguiria listar todos os cursos do ano de 2020 facilmente.

Entendo que na listagem completa é especificada a data de início e fim do curso. Mas como vocês já tem essas datas na base de dados, julgo que não seria tão complexo implementar essa funcionalidade.

Atenciosamente,
Luiz Guilherme M. Zortéa.

**Comment by sahslima** [comment]
Oi, @oLuizGuilherme! Tudo bem?

Obrigada pela sugestão.

Enquanto não temos essa funcionalidade, nosso **time de Experiência do aluno** pode te ajudar com esse tipo de pedido. Entre em contato [por aqui](https://www.alura.com.br/contato) sempre que precisar. ;)

Um abraço.
