### ISSUE TITLE
Chat com o instrutor na área de fórum

### ISSUE THREAD

**Issue by thdesous** [caelum/alura-funcionalidades#37]
Olá, gostaria de sugerir um chat na **área de fórum**, onde seria possível o instrutor se comunicar de forma rápida e prática com o aluno em relação há uma pergunta ou erro reportado. 

Com o chat, a comunicação seria mais dinâmica, em algumas horas até instantânea e evitaria deixar a pergunta ou o tópico postado poluído cheio de registro de conversas, assim o tópico ficaria apenas com a resposta final, a solução do problema ou resposta da pergunta.

**Comment by CarlosEReis** [comment]
Thiago se estiver com problemas para instalar o php com o Ansible pode dar uma olhada:

**Comment by peas** [comment]
oi Thiago!

Queremos implementar votos nas respostas e assim só fica a melhor no meio! upvotes.

Sobre chat em si, seria mais complicado: o chat passa a sensacao que tudo precisa ser respondido imediatamente, sem contar as frases muito curtas, o que não conseguiríamos dar conta (estamos contratando mais para a equipe de suporte e instrutores no forum tambem).

**Comment by thdesous** [comment]
@CarlosEReis obrigado, consegui continuar o lab, depois da uma olhada lá no [fórum](https://cursos.alura.com.br/forum/topico-fatal-192-168-1-101-failed-changed-false-msg-no-package-matching-php5-is-available-98611).

@peas legal, faz mais sentido do que o chat. 
Seria legal colocar um botão (Back to top), isso ajuda e muito em tópicos extensos.

Sempre que tenho um problema e consigo resolver,  já posto o problema e a solução no fórum, assim ajuda a galera que talvez tenha a mesma dificuldade.

Deixo aqui uma observação, não sei como funciona a notificação quando alguém registra um problema no fórum, mas talvez seria interessante criar um página para expor em modo lista problemas que foram postados, para que todos os alunos (comunidade) possuam a visibilidade e possam interagir.   Da forma que é feita hoje, eu não sei de um problema até entrar em um fórum daquela aula ou exercício, logo só consigo ajudar se for coincidência. 

Seria legal criar um gamefication e linkar nessa tela, assim a galera ficaria engajada em ajudar os outros alunos e claro, ganhariam pontos para trocar por descontos, brindes, etc.

Espero ter ajudado te alguma forma. :)
