### ISSUE TITLE
Exercícios 

### ISSUE THREAD

**Issue by RafaelMassula** [caelum/alura-funcionalidades#370]
Estou sentindo falta de exercícios práticos, como imagino que devem ser os projetos mas para outras linguagens, pois os projetos atualmente só se tem para android, UX, redes, mas não tem para programação(back-end), front-end. Poderia ter os exercícios ate nos próprios cursos algo mão na massa mesmo só que sem vídeo do professor fazendo. Na verdade o aluno poderia ter acesso a resolução somente após a entrega do exercícios. Na minha opinião isso se tornaria um desafio, poderia ser colocado novos conceitos, e consolidaria um entendimento que talvez não tenha ficado muito claro. Exemplo disso estou atualmente com bastante dificuldade em entender a fundo injeção de dependência e inversão de dependência. Talvez realizando alguns exercícios propostos pelo professor sem ele esta ali fazendo poderia ajudar.

**Comment by 1henriq1** [comment]
Talvez adicionarem certos exercícios mais específicos fora do escopo dos vídeos para não virar um copia e cola?

**Comment by sahslima** [comment]
Oi, pessoal! Tudo bem?

Estamos revendo essa área de **Projetos** e teremos novidades em breve. 

Enquanto isso, uma forma interessante de reforçar o conhecimento que adquiriram nos cursos e aprender ainda mais é participando das nossas **Imersões gratuitas**.

A próxima é sobre **React Next.js** e as inscrições já estão abertas [neste link](https://www.alura.com.br/imersao-react-next-js). ;)

Um abraço.
