### ISSUE TITLE
Informação sobre data de criação e/ou atualização do curso

### ISSUE THREAD

**Issue by rodrigo-br** [caelum/alura-funcionalidades#371]
Sabemos a importância de se manter atualizado quanto às tecnologias e às necessidades do mercado, portanto, minha sugestão é que os cursos possuam pelo menos uma data de atualização, para que o aluno não precise, a cada aula, voltar na documentação e buscar se houveram mudanças significativas no assunto da aula ou não. A data de criação é realmente importante para que o aluno conheça melhor o curso que estuda e saiba buscar informações atualizadas, por exemplo, quando tenho uma dúvida e recorro ao stackoverflow e percebo que a data da postagem é a mesma da data da ultima atualização do curso do Alura, terei um pouco mais de confiança de que aquela solução apresentada será útil.

Love ya

**Comment by designernatan** [comment]
oi rodrigo, a gente tá sempre de olho pra nao deixar uma versão nova do framework ou atualização de ferramenta atrapalhar o andamento dos cursos que por ventura ainda não foram regravados

quando sentir que um curso está datado, seja por versão de ferramenta ou algo assim, vc pode sempre enviar qual curso e o que te incomodou direto no contato@alura.com.br, com isso o time de conteúdo já fica sabendo em algum momento

sobre a data de criação no curso, quando pegarmos a pagina de curso no futuro para melhorarmos consideraremos, sem datas por enquanto, um spoiler é que estamos com muita coisa boa planejada!

abração! :)
