### ISSUE TITLE
Shortcut para formatação de post e respostas no fórum

### ISSUE THREAD

**Issue by FalLying** [caelum/alura-funcionalidades#372]
| name        | about           | title| labels | assignees |
| ----------- |:-------------:| -----:| -----:| -----:|
| Shortcuts      | Algumas vezes tiro parte do meu tempo de estudo para contribuir um pouco no fórum da Alura, e um pequeno probleminha que sofro e na formatação dos textos. Gosto de deixar tudo organizado para que as pessoas entendam da melhor forma possível minha solução. Um exemplo é quando quero usar a tag `<code></code>`, se ouvesse um atalho como por exemplo shift-c ou uma barra como a que temos aqui mesmo no github, já seria incrível. | Shortcut para formatação de post e respostas no fórum | Fórum | Todos os membros do fórum 🙂 |

**Exemplo da barra que temos aqui no github:**
![image](https://user-images.githubusercontent.com/53955982/103355450-0d5d6200-4a8d-11eb-9eb5-4f4f21d7f891.png)

Gratíssimo desde já pela atenção ^^.

**Comment by sahslima** [comment]
Oi, @FalLying!

Obrigada pela sugestão.

Qualquer novidade nesse sentido, avisamos aqui. ;)

Um abraço.
