### ISSUE TITLE
Resetar um curso, zerar

### ISSUE THREAD

**Issue by weslley182** [caelum/alura-funcionalidades#373]
Quando um curso ja foi executado, e vou faze-lo denovo, gostaria da possibilidade de resetar, para que eu possa acompanhar de onde parei, como se fosse a primeira vez... e não que ficasse marcado tudo como lido, talvez até alterar a data do certificado.

**Comment by luigiMinardi** [comment]
Já faz uns bons anos que muita gente pede isso, da ultima vez que vi falaram que planejam fazer mas não tem data prevista ainda. Como na Issue #11 e em muitas outras.

**Comment by sahslima** [comment]
Oi, pessoal!

Como o @luigiMinardi citou, já faz algum tempo que alguns alunos e alunas pedem por algo assim, mas ainda estamos discutindo internamente como melhorar esse aspecto da experiência de estudo, sem impactar outros pontos da jornada na plataforma.

Qualquer novidade nesse sentido, avisamos por aqui! ;)

Um abraço.
