### ISSUE TITLE
Popup dos pontos

### ISSUE THREAD

**Issue by retatu** [caelum/alura-funcionalidades#374]
A página https://cursos.alura.com.br/points é muito estranha... Deveria abrir um popup e não uma página nova. As vezes clico por engano e vou parar nessa página

**Comment by luigiMinardi** [comment]
só voltar na setinha ue 🤔

**Comment by sahslima** [comment]
Oi, @retatu!

Nos próximos meses teremos alguns ajustes na parte de `Perfil` da plataforma e vamos considerar seu ponto nas melhorias. ;)

Um abraço.
