### ISSUE TITLE
Fórum fechar a solicitação automaticamente após 15 dias.

### ISSUE THREAD

**Issue by lucasmdpereira** [caelum/alura-funcionalidades#375]
Sugiro que o Fórum feche uma questão automaticamente quando obtiver resposta, e o autor da pergunta se ausentar por mais de 15 dias.

Parei de responder questões no fórum justamente por esse motivo. A pessoa faz a pergunta, eu elaboro uma boa resposta, mas nunca mais o usuário entra e marca como respondida. Podia fechar automaticamente ou ficar pública para qualquer um fechar a questão após 15 dias.

**Comment by luigiMinardi** [comment]
Da pra fazer igual o StackOverFlow faz e colocar para usuários com pontuação no forum maior que X poderem "administrar" perguntas e respostas.

**Comment by sahslima** [comment]
Obrigada pelas sugestões, pessoal!

Estamos trabalhando em melhorias dessa área e vamos considerá-las. 

Qualquer novidade, avisamos por aqui.

Um abraço!
