### ISSUE TITLE
Mover e alterar o tamanho do caderno

### ISSUE THREAD

**Issue by 1henriq1** [caelum/alura-funcionalidades#376]
Atualmente estou sentindo uma certa dificuldade na utilização do caderno pois o mesmo está ficando por cima da vídeo-aula, acredito que seria interessante poder mover ele livremente pela área da aula e poder alterar o tamanho dele para melhor encaixar em pontos onde não tem vídeo

**Comment by sahslima** [comment]
Obrigada pelo feedback, @1henriq1!

Vamos considerá-lo nas melhorias do caderno. ;)

Qualquer novidade, aviso por aqui.

Um abraço!
