### ISSUE TITLE
Permitir navegação usando numeros (1 a 9) como no YouTube

### ISSUE THREAD

**Issue by glaucocustodio** [caelum/alura-funcionalidades#377]
Olá, gostaria de poder navegar no video sendo tocado como no YouTube, usando as teclas de 1 a 9.

Obrigado.

**Comment by sahslima** [comment]
Oi, @glaucocustodio!

Obrigada pela sugestão.

Qualquer novidade nesse sentido, avisamos aqui. ;)

Um abraço.
