### ISSUE TITLE
Reação em postagens do fórum (incluindo fechadas)

### ISSUE THREAD

**Issue by dpaulino84** [caelum/alura-funcionalidades#378]
Olá,

Seria interessante viabilizar outras formas de interação no fórum, além da postagem direta, como as já consagradas reações de redes sociais e fóruns mais antigos, pelo menos o clássico like ; joinha, que faz falta. 

Fui achar a resposta para minha dúvida em uma postagem já fechada, entre tópicos mais embaixo na rolagem. Embora não tenha ajudado o aluno que postou a dúvida, ela me ajudou e resolveu o meu problema! Queria poder dar um like para aquela pessoa e  que isso fizesse talvez a postagem "subir" nos tópicos, sinalizando para os outros novatos que ali tinha ouro! xD

Uma vez, eu vi um fórum online (de um curso do laboratório de mídias da Universidade da California), em que os usuários recebiam emblemas como "1º like / Resposta com mais de 100 likes"  etc. Creio que no Coursera tb seja possível... Pode parecer bobinho e modinha, mas esse tipo de funcionalidade ajuda a localizar informação mais útil, além de valorizar membros e aumentar engajamento, materializando capital social / emocional nas funcionalidades de design. Era bem legal. 

é isso.
abraços!

**Comment by sahslima** [comment]
Obrigada pela sugestão, @dpaulino84! ;)

Qualquer novidade nesse sentido, avisamos por aqui.

Um abraço!

**Comment by jeanrobertt** [comment]
Show! Achei a ideia excelente também. 

Inclusive aconteceu algo parecido comigo. Achei a resposta a minha dúvida em uma postagem já fechada e que a pessoa que fez a pergunta não respondeu se aquela tinha sido a solução do problema dela. Mas foi a solução do meu problema e inclusive a resposta foi bem detalhada. E pensei que seria interessante de alguma forma mostrar que aquela resposta me ajudou. E logo em seguida fui procurar um lugar para dar essa sugestão.

Acho que seria interessante, talvez, algo como no stackoverflow, em que é possível dar um upvote quando te ajudar, e dar um downvote se aquela resposta não te ajudou. Mass sendo necessário, explicar o motivo do seu downvote. E as pessoas também podem reagir ao seu downvote, e também comentar no seu comentário.

Acredito que isso gera bastante engajamento no fórum, e ajuda a encontrar informações mais úteis, como dito pelo @dpaulino84
