### ISSUE TITLE
Pequeno problema com uso de Chromecast

### ISSUE THREAD

**Issue by CaioBordallo** [caelum/alura-funcionalidades#379]
Fiz o curso de "Scrum Parte 1". As aulas foram muito boas. Porém eu notei um pequeno defeito na aplicação. Assisti à alguns vídeos do curso usando o aplicativo do meu celular e Chromecast. O problema foi que os videos não fora reconhecidos como visualizados pela plataforma desta forma.
Acredito que seja um problema fácil de se corrigir, ligado ao flag de visualização do vídeo, que deve estar somente atrelado ao video player da Alura e não conta quando reproduzido externamente, como no chromecast.
Considero também a possibilidade de ser um problema pontual em meus dispositivos. Não realizei nenhum teste com diferentes dispositivos.

**Comment by felipetorres** [comment]
Oi @CaioBordallo, sou o líder do time de aplicativos do Grupo Alura, tudo bem?

Você consegue mandar mais detalhes pra mim em aplicativos@alura.com.br? Coisas como:
- Qual o seu aparelho
- Qual a versão do seu Android/iOS
- Qual a versão do app
- Qual o seu usuário na Alura

Abraço!

**Comment by sahslima** [comment]
Oi, @CaioBordallo! Tudo bem?

Vamos fechar a issue, mas quando você tiver os dados solicitados pelo @felipetorres no comentário acima, é só enviar por aqui e reabri-la, ok?

Um abraço!
