### ISSUE TITLE
Dicionario da programação

### ISSUE THREAD

**Issue by Duda-Funchal** [caelum/alura-funcionalidades#38]
Eu acho que seria muito legal se vocês disponibilizassem próximo ou até mesmo dentro do caderno um pequeno dicionario dos códigos que a gente tivesse aprendido até o momento, e que eles também fossem separados pelos mundos deles tipo Java ou Html daí dentro deles os códigos e a  sua função.

**Comment by designernatan** [comment]
@Duda-Funchal valeu pela sugestão!

tipo uma lista com os tipos do java ou propriedades do CSS? Se for isso, fica complicado pois a alura tem muitos cursos que não são exatamente de código

mas você pode sugerir uma melhoria em um exercício para o instrutor de um curso específico coloque esse dicionário
