### ISSUE TITLE
Possibilitar o relacionamento/vínculos de contas/perfis em uma só

### ISSUE THREAD

**Issue by bruno-zambotti** [caelum/alura-funcionalidades#380]
Atualmente tenho acesso a plataforma da Alura por meio de uma assinatura corporativa que minha empresa oferece como benefício. Porém imaginando uma situação onde por exemplo a minha empresa deixe de conceder este benefício e eu como aluno deseje criar uma conta pessoal e assinar a Alura, todo o histórico de cursos vai ficar atrelado a conta de e-mail disponibilizada pela minha empresa e ao criar uma nova conta, acabarei tendo dois perfis com cursos diferentes em cada um, não tendo a possibilidade de reunir todos os cursos já realizados em um único perfil associado a mim de forma única como aluno.

**Comment by bruno-zambotti** [comment]
Outras issues relacionadas:
https://github.com/caelum/alura-funcionalidades/issues/50

**Comment by sahslima** [comment]
Oi, @bruno-zambotti.

Por enquanto, isso ainda não pode ser feito direto na plataforma, mas dependendo do cenário, conseguimos "mesclar" os perfis internamente.

Para isso, nosso **time de Experiência do aluno** pode te ajudar. Entre em contato [por aqui](https://www.alura.com.br/contato) sempre que precisar. ;)

Um abraço.
