### ISSUE TITLE
Sugestão de retrospectiva 

### ISSUE THREAD

**Issue by CarolineChaves** [caelum/alura-funcionalidades#381]
Olá, boa tarde.

Estava pensando em como seria legal se tivéssemos a possibilidade de todo mês, recebermos um e-mail com as estatísticas obtidas pela plataforma. Algo bastante parecido com o e-mail recebido no final do ano "Seu ano na Alura!".

Com isso, poderíamos ter um breve quantitativo no que foi feito em cada mês, e ao final dessa "retrospectiva" poderiamos ter uma tabela ou um gráfico com a nossa evolução.

Poderia conter informações como:

> pontos acumulados
> cursos concluídos
> exercícios resolvidos
> tópicos resolvidos no fórum
> posts no fórum

Porém, seria algo mensal. Demonstrando como foi o nosso mês.

Poderia ser um e-mail mesmo, apenas para termos uma noção geral de algo como "hum... no mês de janeiro 2021, concluí 2 cursos, 14 exercícios..."

Acredito que seria uma forma legal de termos uma memória-resumo da nossa evolução e do que fizemos, aqui.

**Comment by luigiMinardi** [comment]
Email eu acho que ficaria muito escondido já que nem todos os alunos conferem o email sempre. Fora que seria um custo a mais pro envio dos emails. Porém adorei a ideia, acho que poderia ter um botão pra isso no site que analisa tudo bonitinho mostrando os gráficos e tudo mais.

Btw, vale conferir se eles disponibilizam o manuseio desses dados pela api deles, se tiver disponibilizado da pra nós mesmos (alunos) desenvolvermos um script ou aplicação que faça isso.

**Comment by CarolineChaves** [comment]
Bah, se fosse dentro da plataforma seria FANTÁSTICO! 

Ahhhh eu super usaria! E acho uma ideia bem incentivadora!

**Comment by sahslima** [comment]
Oi, @CarolineChaves!

Obrigada por compartilhar, adoramos a ideia.

Atualmente, na área de `Perfil` vocês conseguem ter acessos a essas informações, mas é um histórico desde o início dos estudos na plataforma e não mensal, como sugeriu:
![image](https://user-images.githubusercontent.com/59886589/104460758-4289aa00-558d-11eb-9f53-c497b9ca98b5.png)

Estamos planejando algumas mudanças para essa página e vamos considerar seu ponto. ;)

Qualquer novidade, avisamos por aqui.

Um abraço.

**Comment by luigiMinardi** [comment]
@sahslima o que é mostrado no perfil é algo muito genérico, a ideia dela é ter algo que mostra melhor os dados. 

Por exemplo esse app que eu uso pra minhas rotinas:

![exemplo de graficos](https://i.imgur.com/9LUTW9u_d.webp?maxwidth=640&shape=thumb&fidelity=medium)

**Comment by sahslima** [comment]
Obrigada pela referência, @luigiMinardi! ;)

**Comment by CarolineChaves** [comment]
@sahslima Sim, conheço e uso bastante essa funcionalidade. 

Porém, creio que não seria difícil rodar algo que já existe (como no exemplo que citei no inicio do post) para termos essas estatísticas com mais frequência. 

@luigiMinardi Isso é muito bacana! Se tivesse algo que juntasse nossas ideias ia ser muito massa!
