### ISSUE TITLE
Apagar andamento do curso

### ISSUE THREAD

**Issue by robertorcosta** [caelum/alura-funcionalidades#382]
Boa tarde!
Seria muito bom, se tivesse um jeito que ao desistir de fazer um curso, poder limpar o andamento do mesmo, para poder continuar em um outro momento.

**Comment by sahslima** [comment]
Oi, @robertorcosta! Tudo bem?

Há algum tempo, alguns alunos e alunas tem pedido por algo assim, mas ainda estamos discutindo internamente como melhorar esse aspecto da experiência de estudo, sem impactar outros pontos da jornada na plataforma.

Qualquer novidade nesse sentido, avisamos por aqui! ;)

Um abraço.
