### ISSUE TITLE
Localização do botão de acesso ao caderno e tamanho

### ISSUE THREAD

**Issue by MarcoNasc** [caelum/alura-funcionalidades#383]
Seria interessante se o botão de acesso ao caderno estivesse acima dos tópicas da seção da aula, pois se tiverem muitos vídeos e exercícios é preciso descer até o final para chegar ao exercício, às vezes aperta no botão de "continuar lendo" a transcrição para conseguir ver o botão. Creio que o ideal seja estar na mesma altura do vídeo, já que anotamos enquanto assistimos.

Outro pequeno ajuste seria o tamanho do caderno, talvez uma opção de tamanho maior ou até mesmo podermos ajustar o tamanho tal qual uma janela.

Por último ratifico a sugestão de ter suporte ao Markdown. :)

**Comment by sahslima** [comment]
Obrigada pela sugestão, @MarcoNasc! ;)

Qualquer novidade nesse sentido, avisamos por aqui.

Um abraço!
