### ISSUE TITLE
Criar uma área de comentários ou uma forma de marcar um post como duvida ou não

### ISSUE THREAD

**Issue by luigiMinardi** [caelum/alura-funcionalidades#384]
No caso da área de comentários, a ideia seria logo abaixo de algum exercício pedido pelo professor ter os comentários onde os alunos colocariam as suas versões do código pedido e poderiam conversar sobre esse código de maneira mais fácil.

Atualmente como o fórum só mostra o título do conteúdo não dá pra saber quando um post é uma pergunta ou uma publicação mostrando algum código ou compartilhando qualquer coisa que não uma dúvida. Por esse motivo eu já passei pela situação de entrar em varias perguntas achando que era uma dúvida e ser o post de uma resolução de conteúdo do curso (sem uma resposta para tal). 

Também já passei pelo problema de publicar a resolução de um desafio ou algo extra relativo ao curso que não tem uma "resposta certa" ou coisa do tipo então não teria como fechar o post e no caso de eu fechar não teria como ninguém mais comentar sobre e perderia visibilidade. Porem deixar todos os posts abertos acaba escondendo as perguntas de verdade que os alunos tem e quando você entra pra ajudar alguém você acaba em um flood de posts que não são duvidas abertos pra sempre.

Outro problema relacionado ao sistema atual é que os emails semanais relacionados ao fórum tem se tornado um spam de "não duvidas", o dessa semana por exemplo não teve uma única duvida de verdade sendo apenas pessoas publicando suas resoluções de conteúdo.

A ideia da área de comentários seria mais para agregar essas resoluções em um lugar de mais fácil acesso a quem também está buscando por ela e deixar o fórum mais limpo e relacionado as duvidas. Pois da forma como está quando você quer compartilhar algo novo relacionado diretamente a um curso ou a sua resolução do problema isso vai ficar escondido nas profundezas das publicações solucionadas ou vai ficar floodando as publicações sem solução que deveriam ser duvidas.

Se você aplica a ideia de marcar um post como duvida ou não (tipo uma labelling nos posts) quem está procurando ajudar alguém vai encontrar filtrando pela label "duvidas", quem estiver querendo comentar ou olhar algo relacionado ao código de um curso vai encontrar pela label "resolução" (ou qualquer outro nome melhor).

Essa label "resolução" não apareceria como "sem solução" ou "sem resposta" e poderia comentar dentro dela tranquilamente. Os emails semanais também passariam a indexar somente posts com o tipo "duvidas".

**Comment by sahslima** [comment]
Obrigada pela sugestão, @luigiMinardi.

Vamos considerar seus pontos para melhorar a interação e compartilhamento de aprendizados da comunidade na Alura.

Qualquer novidade, avisamos por aqui! ;)

Um abraço!
