### ISSUE TITLE
Recurso de legendas nas vídeo aulas

### ISSUE THREAD

**Issue by ajuliavictor** [caelum/alura-funcionalidades#385]
Observei que as vídeo aulas não possuem o recurso de legendas, e pensando na **acessibilidade** para pessoas com deficiência auditiva, vejo que essa seria uma feature importante a ser implementada na plataforma como um todo.

Pois mesmo não sendo uma pessoa com deficiência, as legendas em geral me ajudam a me concentrar e de fato absorver o que está sendo dito no vídeo. Sem a opção de legenda, preciso voltar consideráveis vezes alguns pontos da aula para reforçar o que foi passado.

**Comment by sahslima** [comment]
Oi, @juliasampaiovictor! Tudo bem?

Obrigada pelo feedback.

Atualmente possuímos a transcrição da maioria dos nossos cursos, mas sabemos que ainda não é a melhor experiência em termos de acessibilidade.

Estamos considerando esse ponto para futuras melhorias. Qualquer novidade, avisamos por aqui. ;)

Um abraço!
