### ISSUE TITLE
Reset no curso

### ISSUE THREAD

**Issue by g4brielpeixoto** [caelum/alura-funcionalidades#386]
Olá! Eu pesquisei por essa função e descobri que não é possível, até achei alguns tópicos no fórum sobre, mais não tinha essa sugestão aqui ainda. Uma opção de reinicar o curso, passei um tempo sem estudar e gostaria de refazer alguns cursos porém quando vou rever as aulas o andamento do curso não muda e os exercícios já estão respondidos.

**Comment by sahslima** [comment]
Oi, @bilpeixoto!

Obrigada pelos pontos que compartilhou, estamos discutindo formas de melhorar essa experiência para alunos e alunas que desejam rever algum conteúdo.

Qualquer novidade, avisamos aqui. ;)

Um abraço.
