### ISSUE TITLE
Questionário de Revisão e/ou vídeos de resumo dos tópicos

### ISSUE THREAD

**Issue by rafaelzt** [caelum/alura-funcionalidades#387]
Seria interessante uma forma de poder ver os principais tópicos abordados no curso em vídeo e/ou questionário, depois de concluído o curso para que possa ser feita uma revisão do conteúdo pelo aluno de tempos em tempos. (repetição espaçada)

**Comment by sahslima** [comment]
Obrigada pela sugestão, @rafaelzt!

Qualquer novidade nesse sentido, avisamos por aqui. ;)

Um abraço!
