### ISSUE TITLE
Separar o guia de estudos por categorias 

### ISSUE THREAD

**Issue by laridosanjos** [caelum/alura-funcionalidades#388]
Implementar no guia de estudos filtro ou forma de separar os cursos que estamos seguindo por categoria ou tópico definido pela pessoa, quase como uma pasta.

**Comment by sahslima** [comment]
Oi, @laridosanjos!

Obrigada pela sugestão.

Estamos trabalhando na melhoria dos filtros e categorização dessa área. 

Assim que tivermos novidades, avisamos por aqui. ;) 

Um abraço!
