### ISSUE TITLE
Formas de acompanhar o Fórum

### ISSUE THREAD

**Issue by FelipeCarvalhoLima** [caelum/alura-funcionalidades#389]
Seria interessante uma forma de acompanhar alguns fóruns específicos, tanto para alunos que estão naquela formação poderem ser avisados de duvidas que eles mesmos possam ter tido, quanto para alunos que já terminaram aquele curso ou formação poderem acompanhar e ajudar quem ainda está fazendo.
Ajudaria a ter respostas mais rápidas e aumentaria a movimentação nessa área tão pouco aproveitada em alguns cursos.

**Comment by wandersonmaceds** [comment]
Oi @FelipeCarvalhoLima tínhamos uma funcionalidade que no perfil do aluno ele poderia marcar que aceita receber dúvidas dos cursos que ele havia finalizado. Era uma forma de tentar fazer com que os alunos interagissem mais por meio das discussões no fórum, porém, essa funcionalidade será removida, não trouxe os resultados que a gente imaginava. 

Porém, eu gosto da sua ideia e anotei aqui, acho que vale a pena a gente tentar algo no sentido de acompanhar os conteúdos da alura, sem tópicos, cursos, posts, etc.

**Comment by DLucasBR** [comment]
@wandersonmaceds 
Acompanho a Alura há mais de 5 anos e uma das coisas que sempre me frustrou foi a experiência de localizar conteudo no fórum. Seria muito interessante ter uma forma de limitar a pesquisa de uma palavra chave para o fórum de um curso especifico. Na imagem abaixo por exemplo, a disposição dos elementos na tela sempre me leva a crer que a busca será realizada no fórum do curso selecionado, porém é feita de forma geral (em todos os cursos), usabilidade ruim.

![image](https://user-images.githubusercontent.com/19395178/112313271-6dc40000-8c86-11eb-828e-6c67696b4054.png)

Em adição a isso, a visualização dos resultados da busca é uma experiência pobre:
![image](https://user-images.githubusercontent.com/19395178/112314079-5cc7be80-8c87-11eb-8b7c-55bd2a9920f7.png)

No exemplo acima, não sei qual curso o tópico pertence, qual a data, se foi marcado como resolvido...

**Comment by wandersonmaceds** [comment]
Opa @DLucasBR, tudo bem? Existe uma análise sendo feita sobre essa pesquisa pra adicionar talvez filtros e outras opções nas buscas do fórum, só não consigo te informar quando a gente vai estar implementando isso.
