### ISSUE TITLE
Baixar o caderno ao fim do capítulo/curso

### ISSUE THREAD

**Issue by carvalholeo** [caelum/alura-funcionalidades#39]
Com a nova funcionalidade do Caderno, algo legal que poderia ter é a possibilidade de baixar, em PDF, TXT ou Markdown o conteúdo do mesmo, ao fim de um capítulo ou mesmo ao fim do curso. 

Assim, a pessoa não precisaria retornar para assistir parte do curso novamente, já que ela provavelmente terá anotado o conteúdo que é relevante para ela naquele momento.

**Comment by designernatan** [comment]
@carvalholeo valeu pela sugestao de melhoria na feature!

a ideia é que no futuro lá em `Perfil > Cadernos` você consiga além de baixar, apenas visualizar suas anotações (hoje você clica e vai pro curso)

quão sentido isso faz para você e seus estudos?

**Comment by carvalholeo** [comment]
Olá @designernatan , obrigado pela resposta!

A feature que você descreveu é ainda melhor do que eu pensei. Faz todo o sentido esse jeito que foi imaginado!
