### ISSUE TITLE
Filtros avançados na Busca

### ISSUE THREAD

**Issue by jhonnytuba** [caelum/alura-funcionalidades#390]
Ao realizar a busca, temos apenas a opção de uma descrição, porém, seria legal se pudéssemos direcionar a busca, por exemplo, Por título, Por descrição, Por linguagem, Por formação ou curso.
Acredito que iria agregar bastante na hora de encontrar o curso ideal.

**Comment by sahslima** [comment]
Oi, @jhonnytuba!

Obrigada por compartilhar.

Estamos trabalhando em melhorias nos campos de busca da plataforma e vamos considerar seus pontos. ;)

Um abraço!
