### ISSUE TITLE
Menu lateral fixo.

### ISSUE THREAD

**Issue by mrclrmrs** [caelum/alura-funcionalidades#391]
Utilizo bastante a funcionalidade do caderno para anotar informações relevantes sobre o curso. Acontece que, em tópicos onde há um número de aulas maior, o botão utilizado para abri-lo se situa no final, sendo necessário rolar até o fim da página para acioná-lo. Por exemplo: se estou no começo da aula e quero fazer uma anotação, preciso descer até o final para selecionar o caderno e depois novamente subir para retornar do ponto onde parei. Quando acho necessário fazer várias anotações, tal ação se torna maçante. 
Uma sugestão seria que a barra de rolagem fosse dividida. Enquanto o mouse estiver posicionado na parte dos textos/vídeos da aula, a função de rolagem se aplicaria somente nela. Já quando posicionarmos o mouse no menu, somente haveria movimento naquela opção não sendo necessário identificar onde parei para fazer minhas anotações.

**Comment by sahslima** [comment]
Oi, @mrclrmrs!

Obrigada pela sugestão.

Estamos discutindo alguns pontos sobre essa funcionalidade e vamos levar seu comentário em consideração no desenvolvimento das melhorias. ;)

Qualquer novidade, avisamos por aqui.

Um abraço.
