### ISSUE TITLE
[Melhoria] Marcar conteúdo extra como "resolvido" na lista de cada Formação

### ISSUE THREAD

**Issue by leosaldanha** [caelum/alura-funcionalidades#392]
Boa tarde!

Na lista de conteúdos a serem feitos em cada Formação, existem alguns que são extras aos cursos, como podcasts, artigos e etc. 

![image](https://user-images.githubusercontent.com/13903117/106041910-73212600-60ed-11eb-9569-f8fad0b5b622.png)

Seria ótimo se pudéssemos marcar cada um desses conteúdos com um status referente ao andamento do mesmo (To Do, In Progress, Done, por exemplo), para podermos acompanhar o progresso nesses itens também e não só nos cursos.

Assim, caso eu prefira, por exemplo, ouvir todos os podcasts e fazer os cursos primeiro, não correria o risco de me perder caso lesse algum dos posts durante o caminho.

**Comment by sahslima** [comment]
Obrigada pela sugestão, @leosaldanha!

Qualquer novidade nessa área, avisamos por aqui. ;)

Um abraço.
