### ISSUE TITLE
[Melhoria] Vincular preferências das aulas ao perfil do usuário

### ISSUE THREAD

**Issue by leosaldanha** [caelum/alura-funcionalidades#393]
Boa tarde! :)

Quando estou assistindo um curso, gosto de colocar no Modo Noturno, ajustar a velocidade de reprodução e setar o player para o modo Teatro. No caso da velocidade de reprodução e do tamanho do player, essas preferências são salvas e se propagam quando avanço de um curso para o outro.

Já no caso do Modo Noturno, percebi que todas as vezes preciso clicar novamente para ativá-lo. Seria muito bom se eu pudesse mantê-lo ativado como minha "preferência de usuário", mesmo quando trocasse de curso ou dispositivo.

**Comment by sahslima** [comment]
Oi, @leosaldanha!

Obrigada pelo feedback.

Essa funcionalidade foi implementada recentemente e com certeza vamos considerar seus pontos para futuras melhorias. ;)

Qualquer novidade, avisamos por aqui. ;)

Um abraço.
