### ISSUE TITLE
Sugestão: Meu Caderno

### ISSUE THREAD

**Issue by Fotkurz** [caelum/alura-funcionalidades#394]
Bom dia!

Gostaria de sugerir uma melhoria para o caderno de anotações.

Poderia ter um meio de salvar nossas anotações _offline_ assim poderiamos estudar nossas anotações fora de casa, mesmo sem internet.

Como não encontrei essa funcionalidade no app para Android, resolvi sugerir.

**Comment by sahslima** [comment]
Obrigada pela sugestão, @Fotkurz!

Qualquer novidade nesse sentido, avisamos por aqui. ;)
