### ISSUE TITLE
Verificação de email na matricula

### ISSUE THREAD

**Issue by brunobss1** [caelum/alura-funcionalidades#395]
No formulario da matricula percebi que é bem comum os usuarios errarem a escrita do email.Caso haja a confirmação do email antes de fechar a compra,havera menos problemas do tipo a ser resolvidos pela assistencia.

**Comment by sahslima** [comment]
Oi, @brunobss1!

Obrigada pelo feedback.

Vamos considerar na melhoria desse fluxo de matrícula. ;)

PS: isso ocorreu contigo, você já conseguiu apoio do nosso time de experiência do aluno?

Um abraço!

**Comment by brunobss1** [comment]
Oi,sim ocorreu, mas já consegui apoio e deu tudo certo,obrigado!
