### ISSUE TITLE
Sugestão em Meus cursos em andamento: botão "continuar onde parou" para todos os cursos listados

### ISSUE THREAD

**Issue by micalevisk** [caelum/alura-funcionalidades#396]
Na página do Dashboard (https://cursos.alura.com.br/dashboard), há a secção *Meus cursos em andamento* que lista alguns dos cursos que o usuário está fazendo. O único curso destacado nessa lista é o último visto por ele. Esse card de destaque tem os botões `VER CONTEÚDO DO CURSO` e `CONTINUAR DE ONDE PAROU`.

Minha sugestão é adicionar o botão `CONTINUAR DE ONDE PAROU` (ou com algum nome equivalente) também nos outros cursos listados para evitar que o usuário tenha que acessar a página do curso para só então _continuar o curso_.

Basicamente, isto:

![demo](https://user-images.githubusercontent.com/13461315/106781789-d21bf900-661f-11eb-96b8-d2391c6fbf51.png)

---

Pra quem quiser essa funcionalidade neste exato momento, basta injetar o seguinte código javascript na página usando extensões como o [Code Injector](https://chrome.google.com/webstore/detail/code-injector/jgcallaoodbhagkaoobenaabockcejmc) (aplicando pro host: `cursos\.alura\.com\.br/dashboard`):

<details>
<summary>código js</summary>

```js
{
    const createBtnCode = (link) => `
<div class="big-card__buttons" style="padding-left: 0px;padding-bottom: 0px;">
  <a class="big-card__right-button" style="width: calc((100% - 14px));height: 30px;background-color: #5ed97b;" href="${link}/continue">continuar onde parou</a>
</div>
    `;
    const $parents = document.querySelectorAll('.in-progress__smaller-cards > .course-card');
    for (const $parent of $parents) {
	      const $targetParent = $parent.querySelector('.course-card__content-wrapper');
	      const link = $parent.querySelector('.course-card__course-link').href;
	      $targetParent.insertAdjacentHTML('beforeend', createBtnCode(link));
    }
}
```

</details>

**Comment by micalevisk** [comment]
Aqui está a nova versão do código JS que implementa essa feature pra nova UI:

```js
{
    const createBtnCode = (link) => `
    <div class="big-card__buttons" style="margin-left: 0px;padding-left: 0px;padding-bottom: 0px;padding-right: 0px;">
        <a class="big-card__button" href="${link}/continue"></a>    
    </div>
    `
    const $parents = document.querySelectorAll('.newCourseCardSmall__course-wrapper')
    for (const $parent of $parents) {
        const link = $parent.href
        const $targetParent = $parent.querySelector('.newCourseCardSmall__course__progress')
        $targetParent.insertAdjacentHTML('afterbegin', createBtnCode(link))
    }
}
```

que resulta em:

![realidade](https://user-images.githubusercontent.com/13461315/107097759-0b04cb00-67e4-11eb-94b6-b8016639c059.png)

Mas acho que seria melhor se o botão estivesse abaixo da barra de progresso. Algo como (mas mais correto):

![expectativa](https://user-images.githubusercontent.com/13461315/107098461-a480ac80-67e5-11eb-8a32-707b300fc080.png)

**Comment by designernatan** [comment]
@micalevisk desculpa pela demora em um reply

poxa valeu mesmo por mandar as sugestões além das imagens até já com o código!

sobre o botão nos cursos com menos destaque, [quando fizemos os testes de usabilidade](https://www.alura.com.br/artigos/novidades-alura-2020-agosto-dashboard-formacao) além de não identificarmos essa necessidade do "play direto" no curso, é bacana direcionarmos mais a pessoa a acabar o último conteúdo que teve contato, aumentando a sensação de "acabativa"

enquanto a gente nao revisita essa tela, já ia te falar para usar o code injectector mas você já a conhece :)

novamente: brigadao mesmo pelo seu tempo dedicado na sugestão e em disponibilizar os códigos 🙏🏽

abcs!
