### ISSUE TITLE
Modo noturno é desativado sozinho sempre que um curso é concluído (100% de progresso)

### ISSUE THREAD

**Issue by micalevisk** [caelum/alura-funcionalidades#397]
Sempre que concluo qualquer curso com o modo noturno ativo e continuo/inicio outro, o modo noturno está desativado. Creio que seja um bug.

Isso só acontece quando eu clico no botão `próxima atividade` da última task de qualquer curso para ir para a página `/finish/congratulations`. Investigando rapidamente eu descobri que uma das requisições disparadas nessa página  é `GET https://cursos.alura.com.br/course/note/...` (retorna `204`) e envia um cookie com `darkmode=false`, o que desativa o modo noturno.

Testei apenas no Firefox.

**Comment by micalevisk** [comment]
Basicamente, a página `/finish/congratulations` (imagem abaixo) não considera o cookie `darkmode` que é enviado na requisição. Basta ir diretamente pra:  
`https://cursos.alura.com.br/course/<ALGUM-CURSO>/section/123/finish/congratulations`   
pra confirmar isso.

<details>

![página citada](https://user-images.githubusercontent.com/13461315/106832062-5e9dda00-6667-11eb-8ee2-02cf81429dc9.png)

</details>

Ou seja, essa requisição sempre retorna um HTML em que o `<body>` não tem o atributo `class="darkmode"`, logo, quando o `DarkModeToggler` (javascript) é avaliado, ele alimenta o `document.cookie` com `darkmode=false`

```javascript
// trecho do arquivo darkMode.js
document.cookie = "darkmode=" + this.$body.hasClass("darkmode") + ";expires=" + expires + ";path=/";
```

**Comment by sahslima** [comment]
Oi, @micalevisk!

Reportamos para o time de Desenvolvimento.

Avisamos aqui quando estiver corrigido. ;)

**Comment by gabrielronei** [comment]
@sahslima prontinho, está no ar a correção :)

**Comment by sahslima** [comment]
@micalevisk você testa e qualquer coisa nos avisa, por gentileza? (:

**Comment by micalevisk** [comment]
Foi resolvido! obg @sahslima e @gabrielronei
