### ISSUE TITLE
Filtro por área na aba plano de estudos publicos

### ISSUE THREAD

**Issue by brunobss1** [caelum/alura-funcionalidades#398]
Na aba plano de estudos publicos ficam organizados difrentes planos de estudos de diferentes áreas oque gera uma demora na procura de algo mais especifico.Seria bom se ouvesse a opção do criador do plano de estudos indicar qual área de formação do seu plano como "progamação" ou "ux desing". Assim, o usuario que estiver procurando um plano de estudos poderá encontrar um plano de seu interesse com mais facilidade.

**Comment by sahslima** [comment]
Oi, @brunobss1!

Concordamos contigo.

Estamos discutindo melhorias nos filtros de busca da plataforma como um todo, qualquer novidade nessa área, avisamos por aqui. ;)

Um abraço!
