### ISSUE TITLE
Opção de salvar/"favoritar" tópicos e poder organizá-los + barrinha de busca termos-chave

### ISSUE THREAD

**Issue by viniNascimento63** [caelum/alura-funcionalidades#399]
Gostaria que tivesse a opção de poder salvar tópicos que considero interessantes e que iriam me ajudar no futuro quando eu precisasse deles caso esquecesse alguma coisa básica ou simplesmente para quando eu estivesse empacado em um problema e eles me dariam uma luz. Mas, essa opção por si só, com o tempo,  não seria muito boa pois, imagine uma pessoa que sai salvando tudo quanto é tópico... Um dia, ela precisará achar algum desses tópicos e ficará difícil devido a quantidade dos mesmos. Por isso, poder organizar em pastas em uma área dentro da plataforma seria uma mão na roda para facilitar a busca dos tópicos de interesse outrora salvos. E, caso a pessoa tenha dentro das pastas muitos tópicos salvos, deveria haver uma barrinha de busca para pesquisar termos-chaves. Assim, mesmo que a pessoa tenha muitos tópicos salvos, uma hora ou outra ela conseguirá encontrar o que está buscando.

Sou iniciante no mundo da programação e estou aprendendo lógica de programação em JS e HTML. Por isso, a opção se salvar tópicos seria muito útil para um iniciante poder rever conteúdos em que mais cedo ou mais tarde vão surgir dúvidas.

**Comment by designernatan** [comment]
@Vinini só para conferir se estou no caminho certo do seu raciocinio:

quando vc diz 'topico', o que vc quer dizer exatamente?

---

hoje temos o 'favoritar', que funciona apenas em cursos (outras ações -> favoritar)
![image](https://user-images.githubusercontent.com/5431347/109969530-c67d2a00-7cd2-11eb-8b3c-b40b426ff5bd.png)

algo próximo disso é a [funcionalidade de criação de plano de estudos,](https://www.alura.com.br/artigos/novidades-na-alura-videos-alura-e-planos-de-estudo) que vc pode colocar não só cursos, mas também formações inteiras, links externos, videos, etc

inclusive há uma [lista de PDEs públicos aqui](https://cursos.alura.com.br/planos-estudos-publicos)

---

me fala se faz sentido isso tudo pra você no seu contexto atual?

abcs!

**Comment by viniNascimento63** [comment]
E aí @designernatan, tudo bem? 

Quando me refiro a "tópicos", falo dos tópicos presentes nos fóruns de cada atividade. Por exemplo, havia um tópico solucionado no fórum de lógica que programação I que perguntava como executar o programa ao clique da tecla Enter do teclado. Achei bem interessante essa dúvida levantada por um dos alunos, e, apesar de não ser a minha dúvida, gostaria de ter de alguma forma salvado aquele tópico para que quando eu ficasse em dúvida de como fazer isso,  já soubesse onde procurar.

Ficou mais claro? =)

**Comment by designernatan** [comment]
ooopa agora entendi meu caro, obrigado por responder

tópico tópico mesmo, de fórum!

sem planos pra algo assim por enquanto, mas seria legal ter isso atrelado a um plano de estudos tbm

o que faria hoje é pegar esses links e ir organizando num [notion](https://www.alura.com.br/artigos/organizando-estudos-portfolio-notion-linkedin)
