### ISSUE TITLE
Memorizar onde parei em um vídeo

### ISSUE THREAD

**Issue by mautoz** [caelum/alura-funcionalidades#4]
Algumas vezes, imprevistos aparecem, e não é possível terminar uma vídeo aula. Portanto, seria legal que o vídeo continuasse de onde paramos, igual na Netflix.

**Comment by designernatan** [comment]
Oi Mautoz,

Está no nosso radar essa! Como dev não tenho conhecimento técnico para julgar a complexidade disso, mas do ponto de vista de UX faz todo sentido. Puxando exatamente esse exemplo da Netflix que você deu.

YouTube faz o mesmo também.

Valeu pela sugestão,

Abcs!
