### ISSUE TITLE
Player com modo teatro

### ISSUE THREAD

**Issue by xluisfabio** [caelum/alura-funcionalidades#40]
Descreva a funcionalidade que você gostaria que tivesse na plataforma. Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

É muito mais prático estudar com vídeo aulas com a tela divida ao meio: metade para o vídeo e a outra metade para o desenvolvimento. Infelizmente o player do Alura não oferece essa opção, sendo apenas a tela do vídeo pequena (o que dificulta muito a visualização, já que o menu lateral mesmo fechado toma conta de boa parte da tela) ou no modo full screen. A única opção seria então ficar dando eternos alt+ tab nas janelas, o que irrita um pouco. 
Nos cursos do Udemy eles oferecem além da resolução 1x e full screen, o "modo teatro" onde a imagem do vídeo fica maior.
Gostaria de sugerir a inclusão do modo teatro no player dos vídeos para alunos que assim como eu, gostam de estudar "em uma tela só, mas dividida ao meio".

**Comment by designernatan** [comment]
@xluisfabio valeu pela sugestão! Estamos com planos de mexer mais ainda na tela de aula, um modo cinema é algo interessante

uma solução de contorno que faço quando estou no note é dar zoom até pegar na media query de celular, deixando o vídeo maior

**Comment by xluisfabio** [comment]
obrigado pela rápida resposta Natan!
sobre aplicar o zoom no vídeo para melhor visualização, eu já faço isso, o problema mesmo é o menu lateral esquerdo que também é ampliado, prejudicando a visualização.
Uma alternativa que encontrei é clicar com o botão direito no player e seleciono "picture-to-picture" ,eu consigo aumentar um pouco mais a tela, mas mesmo assim fica de difícil visualização se eu for trabalhar com a tela dividida ao meio (para não precisar ficando alt+tab nas janelas).
gostaria imensamente que vocês aceitassem a minha sugestão e aplicarem o modo teatro/cinema no player, pois garanto que muitas pessoas estudam da mesma forma que eu.

desde já agradeço a atenção Natan!
