### ISSUE TITLE
Data de atualização dos planos de estudos está incorreta

### ISSUE THREAD

**Issue by CViniciusSDias** [caelum/alura-funcionalidades#400]
Os guias de estudo possuem uma informação de "Última atualização". Essa informação está exibindo, na verdade, a data de criação do plano de estudo.

Ao atualizar um plano de estudo, essa data permanece inalterada. Exemplo:
https://cursos.alura.com.br/guia-do-programador-php-vinicius-dias-p2779

Cursos que foram inclusive lançados após a data exibida (15/07/2019) foram adicionados ao plano depois de sua criação, porém a data de última atualização não é alterada.

**Comment by sahslima** [comment]
Oi, @CViniciusSDias!

Reportamos para o time de desenvolvimento.

Avisamos aqui quando estiver corrigido. ;)

**Comment by sahslima** [comment]
Oi, @CViniciusSDias! Tudo bem?

Corrigimos, você pode testar alguma atualização no plano e nos posicionar se passou a exibir a data correta?

Um abraço!

**Comment by CViniciusSDias** [comment]
A data de atualização agora parece estar correta sim, mas os links do usuário não aparecem mais. Não sei se o problema foi causado por essa correção ou não.
Print do erro (repare no espaço em branco abaixo dos meus pontos):

![Links não aparecendo, causando espaço em branco](https://user-images.githubusercontent.com/6991415/112536881-c67dc080-8d8c-11eb-97dc-40508739d366.png)

**Comment by sahslima** [comment]
Vamos corrigir esse ponto, @CViniciusSDias!

Quando entrar no ar, te aviso. ;)

**Comment by sahslima** [comment]
Oi, @CViniciusSDias. Tudo bem?

Corrigimos. (:
