### ISSUE TITLE
Adição do modo noturno na Dashboard e nas demais páginas da plataforma

### ISSUE THREAD

**Issue by karpathos** [caelum/alura-funcionalidades#401]
Percebi a presença do modo noturno enquanto estudava nos cursos da Alura. Infeliz me frustei ao procurar o mesmo modo nas demais páginas que não fossem enquanto eu estivesse no estudo de um curso específico em si. Então sugiro que possamos fazer uma versão da dashboard com um tom semelhante ao modo noturno dos cursos, já que uma tela branca pode ser incômoda aos olhos (e esteticamente desagradável, em minha opinião).

**Comment by wandersonmaceds** [comment]
Oi @karpathos eu gosto da ideia, compartilho do seu gosto pelas interfaces dark, acredito que muita gente goste também.

**Comment by karpathos** [comment]
Oi @wandersonmaceds! Fico feliz em ver que mais gente se interessaria por essa adição. Afinal nossos olhos e nosso astigmatismo agradecem. Hahaha

**Comment by sahslima** [comment]
@karpathos, qualquer novidade sobre modo noturno em toda plataforma, avisamos por aqui. ;)
