### ISSUE TITLE
Exibir data de publicação ou produção do conteúdo

### ISSUE THREAD

**Issue by thiagofloriano** [caelum/alura-funcionalidades#402]
Seria interessante exibir a **data de publicação ou de produção** do conteúdo que estamos lendo/assistindo para saber se aquela informação está bem atualizada ou se precisamos checar as novidades em outras fontes como a própria documentação da linguagem. 

Por exemplo, estou em um curso sobre JS que o instrutor fala de algumas features que não são recomendadas para produção porque ainda não estão consolidadas ou perfeitamente implementadas na linguagem. Pelo conteúdo imagino que o vídeo tenha sido gravado há mais de um ano, mas se houvesse a data visível, seria mais simples.

**Comment by designernatan** [comment]
oi thiago!

a gente tá sempre de olho pra nao deixar uma versão nova do framework ou atualização de ferramenta atrapalhar o andamento dos cursos que por ventura ainda não foram regravados, ou de repente não tem algum alura+ para comentar essas atualizações

vale o que disse [nessa outra issue:](https://github.com/caelum/alura-funcionalidades/issues/371) sempre que você sentir que algum conteúdo está meio datado ou até exatamente nesse exemplo que você disse do JS, não hesite em pingar no contato@alura.com.br, com isso o time de conteúdo já fica sabendo em algum momento

e sobre a data de criação, no futuro quando pegarmos a pg de curso para melhorarmos consideraremos colocar essa informação sim, infelizmente não consigo te passar datas

se tiver dúvidas de conteúdo ("antes fazíamos assim no JS, agora fazemos como?") pode usar o fórum de dúvidas

teremos novidades chegando esse ano :)

abcs!
