### ISSUE TITLE
Discord da Alura

### ISSUE THREAD

**Issue by ricardo-cas** [caelum/alura-funcionalidades#403]
Olá pessoal, tudo bem?

Seria legal ter um grupo da Alura para as pessoas discutirem sobre o mundo da programação/ e afins.

**Comment by peas** [comment]
oi Ricardo!

Vamos ter muito em breve. Queremos fazer de uma maneira faseada com assuntos diferentes, assim nao fica muito espaço vazio e pequenos grupos isolados!
