### ISSUE TITLE
Indicar aulas com a tag ou flag de "retomar assunto" ou ter a possibilidade de marcar como não concluída.

### ISSUE THREAD

**Issue by gabmelloc** [caelum/alura-funcionalidades#404]
Inserir na "barra" de cada aula um botão que indique o domínio sobre àquela aula, ou um botão com ícone de lembrete, que ao ser selecionado mude a cor desta aula para um laranja/amarelo, para indicar que o aluno não sente que dominou os conceitos da aulas e gostaria de revisar posteriormente. Hoje a plataforma permite apenas que as aulas sejam concluídas. Pedagogicamente é uma boa estratégia deixar a critério do aluno se o mesmo concluiu ou se está OK ou não com o conteúdo.

Tela para implementar:

![image](https://user-images.githubusercontent.com/44449761/108005741-52573c80-6fd8-11eb-8dc9-28842e2626e2.png)

Sugestão de ícone:
![image](https://user-images.githubusercontent.com/44449761/108005752-5aaf7780-6fd8-11eb-876a-e0e760ffbf84.png)

**Comment by designernatan** [comment]
gabriel, gosto bastante disso de ideia de reforço, meio que um flash card para reforçar conteúdo que não está 100%, pessoal que estuda idiomas usa bastante isso para pegar vocabulário

sem planos por hora para algo assim, algo externo e bem legal para ajudar nisso seria colocar num [notion](https://www.alura.com.br/artigos/organizando-estudos-portfolio-notion-linkedin) os links das aulas numa tabela

sei que o ideal para você seria algo já interno, vamos considerar algo assim quando pegarmos a tela de aula para melhorarmos no futuro

**Comment by gabmelloc** [comment]
Show! Já pensei em utilizar o notion, mas não consigo me adaptar bem a ter que ficar descrevendo os passos de aprendizagem em outra ferramenta. Fico feliz que irão considerar no futuro. 

Abraços,
