### ISSUE TITLE
Sugestão Meu Caderno "Localização do Botão Abrir Caderno"

### ISSUE THREAD

**Issue by bruosorio** [caelum/alura-funcionalidades#405]
Olá,

A localização atual do botão "Abrir Caderno" é muito inconveninte pois fica no final do menu lateral do curso.
![image](https://user-images.githubusercontent.com/28766939/108221943-124aa380-7117-11eb-9c6d-fb72c5450b89.png)

Esse botão poderia ser alterado para barra de título superior para que o acesso seja mais rápido e que a barra ficasse fixada no topo.
![image](https://user-images.githubusercontent.com/28766939/108222261-5fc71080-7117-11eb-8edf-b277e3b0c4fa.png)

**Comment by sahslima** [comment]
Oi, @bruosorio!

Obrigada por compartilhar.

Estamos analisando alguns pontos de usabilidade do caderno e qualquer mudança, avisamos por aqui. ;)

Um abraço.
