### ISSUE TITLE
Nos exercícios de múltipla escolha, não enviar resposta automaticamente ao clicar

### ISSUE THREAD

**Issue by awvalenti** [caelum/alura-funcionalidades#406]
![image](https://user-images.githubusercontent.com/834921/108267484-07f5cd00-714a-11eb-891f-2c620f086397.png)

Em múltipla escolha, quando houver barra de rolagem (ver acima), a pessoa pode tentar clicar para rolar o texto e sem querer clicar um pouco fora da barra, selecionando a alternativa sem querer e enviando a resposta. Isso quase aconteceu comigo agora há pouco, e teria sido bem desagradável.

Sugiro que o envio de resposta seja feito por meio de um botão específico, e não automaticamente ao selecionar uma alternativa.

**Comment by sahslima** [comment]
Olá, @awvalenti!

Obrigada pela sugestão, vamos considerar nas melhorias dessa área.

Qualquer novidade, avisamos por aqui. ;)

Um abraço!
