### ISSUE TITLE
Arquivo de cursos

### ISSUE THREAD

**Issue by sdonijr** [caelum/alura-funcionalidades#407]
Uma página que contenha os cursos que já finalizei.

Quando eu quero rever um vídeo referente a curso que já fiz. Tenho que ir até a página principal, escolher o grupo, por exemplo, programação, localizar o curso para acessar novamente. 
Seria interessante também se abrir na última atividade visualizada (como acontece no curso em andamento).

**Comment by sahslima** [comment]
Oi, @sdonijr! Tudo bem?

Atualmente você consegue visualizar suas formações e cursos finalizados acessando seu nome no canto superior direito da página >` Perfil & Certificados`.

Porém, sabemos que essa informação fica um pouco "escondida" e estamos trabalhando para deixar essa visualização mais intuitiva na plataforma.

Qualquer novidade nesse sentido, avisamos por aqui. ;)

Um abraço!
