### ISSUE TITLE
Sugestão Meu Caderno - Manter o caderno aberto durante a transição das atividades

### ISSUE THREAD

**Issue by dunirvana** [caelum/alura-funcionalidades#408]
Olá a todos!

Minha sugestão é que o caderno permaneça aberto enquanto estivermos navegando entre as atividades de um curso, hoje ao ir para a próxima atividade o caderno é fechado obrigando o usuário a procurar o botão, abrir o caderno novamente e localizar o conteúdo que estava sendo editado.

**Comment by designernatan** [comment]
eduardo, de fato isso incomoda mesmo, o ponto é que a tela de aula não é uma SPA deve ter atrapalhado isso

vamos ver se rola fazer algo automático, igual o modo noturno

**Comment by designernatan** [comment]
eduardo, dev team implementou a melhoria :)

valeu pelo sugestão!

**Comment by dunirvana** [comment]
Show de bola! Obrigado aos envolvidos!
