### ISSUE TITLE
Discord para um melhor suport

### ISSUE THREAD

**Issue by danielvor** [caelum/alura-funcionalidades#409]
Olá Equipe Alura!

Nesse exato momento, estou estudando Django e tenho com um problema no meu codigo. 
Quero tirar minha duvida, que é muito simples, mas não quero esperar no forum.

Uma forma muito eficiente seria criar um Canal no discord para suporte aos alunos. No discord eu poderia transmitir o meu problema e receber um feed back rapido de poucos minutos do instrutor, caso ele estiver Online. E mais, poderia perguntar aos alunos do mesmo curso se eles sabem como fazer aquele problema.... Manteria a comunidade Alura(Professores e alunos) mais proximos.

**Comment by peas** [comment]
Daniel, estamos a caminho. Vamos começar com cada categoria da alura e canais especificos e melhor: trazendo um conteudo extra que vai fazer bastante sentido ser discutido no discord.

a gente nao faz isso de imediato porque ha alguns problemas: a chance do instrutor estar online na mesma hora que voce tem duvida em um dos 1200 cursos é pequena. entao estamos elaborando mecanismos para maximizar a chance que voce tenha de pergutnar/comentar algo e ter resposta do grupo, do professor, do monitor.

**Comment by peas** [comment]
Oi This e pessoal. Finalmente teremos nosso Discord oficial. Ele começa focado em um challenge, dessa vez em Front-end, e depois vamos adicionando espaço para outros assuntos e escola com o passar do tempo e com a medida que crescemos nosso time de suporte (vulgo mergulhadores Scuba Team):
https://www.alura.com.br/challenges/front-end
