### ISSUE TITLE
Mostrar barra de progresso no card dos meus planos de estudo

### ISSUE THREAD

**Issue by reremori** [caelum/alura-funcionalidades#410]
Quando eu criei meus planos de estudo, eu esperava que eles tivessem um comportamento semelhante das formações que me mostram uma barra de progresso considerando o todo dentro daquela formação. Mesmo que seja possível adicionar ou remover cursos dos planos, eu sinto muita falta de olhar para os meus planos e identificar o meu progresso em cada um deles. Acredito que com essa funcionalidade eu me sentiria mais motivada a realizar as atividades e ver a barrinha dos meus planos chegarem no 100%. Fora que além disso, eu poderia visualizar se ja finalizei aquele plano sem ter que entrar para ver.

**Comment by sahslima** [comment]
Obrigada pela sugestão, @reremori!

Vamos considerar em futuras melhorias dessa área. ;)

Qualquer novidade avisamos por aqui.

Um abraço.
