### ISSUE TITLE
Redução do Certificado Unificado

### ISSUE THREAD

**Issue by renanbuenom** [caelum/alura-funcionalidades#411]
Na seção "Perfil e Certificados" do usuário Alura (https://cursos.alura.com.br/user/*nome_do_perfil*), existe hoje a opção "Você pode encontrar um certificado completo **aqui**". Ao clicar, é gerado um certificado unificado de todos os cursos, separado por seções das formações que os cursos fazem parte.

Porém, é gerado um certificado muito **extenso**, com formações que não faço parte, com a lista muito **repetitiva**, pois os cursos estão presentes em diversas formações. Eu, por exemplo, estou fazendo apenas a **formação Front-end** e meu certificado apresenta as formações: **Iniciante em Programação, Front-end, HTML e CSS, React JS e Vue.js**.  Conclui, até o momento, 10 cursos, e na lista do certificado apresenta 24 cursos, repetindo diversos deles.

Por esses motivos, sugiro que seja gerado um certificado unificado apenas com as **formações em que o aluno está inscrito**, ou ainda, que seja perguntado **quais formações deseja listar** nesse currículo.

**Comment by sahslima** [comment]
Oi, @renanbuenom! Tudo bem?

Obrigada pelo feedback, vamos trabalhar para melhorar esse aspecto na plataforma.

Enquanto isso, caso precise, por gentileza, [entre em contato](https://www.alura.com.br/contato) com o nosso time de experiência do aluno para solicitar um certificado nos moldes que sugeriu. 

Um abraço.

**Comment by designernatan** [comment]
@renanbuenom fizemos uma alteração no sistema do Certificado Completo

mudamos a regra em geral e agora é possível ocultar uma formação para poder gerar o pdf

me fala depois o que achou?

abcs

**Comment by renanbuenom** [comment]
Olá, boa tarde.

Grato pelo retorno e por atender a sugestão!

Percebi que o certificado completo automaticamente está gerando uma versão
mais simplificada, o que ficou muito bom.
Porém, não encontrei a funcionalidade de ocultar a formação. Poderiam me
explicar como funciona?


Atenciosamente,
*Renan Bueno Machado*
(43) 9 9967-2052
***@***.***


Em seg., 19 de jul. de 2021 às 11:30, Natan Souza ***@***.***>
escreveu:

**Comment by designernatan** [comment]
oi renan, subimos agora mesmo um post mostrando essas e outras novidades
https://www.alura.com.br/artigos/escolha-os-planos-de-estudos-para-o-seu-dashboard

o ocultar formação fica no seu certificado completo

basta ir no perfil, descer a página e lá em baixo tem um link para ele!

abcs

**Comment by renanbuenom** [comment]
Olá,

Não encontrei a opção. Acessei o certificado completo pelo link:
[image: image.png]

Dentro da página, não há nenhuma opção de edição. A visualização parece de
um leitor de pdf:
[image: image.png]

Poderiam verificar ou me explicar novamente, por favor?

Obs.: testei a visualização no Microsoft Edge e no Google Chrome.

Atenciosamente,
*Renan Bueno Machado*
(43) 9 9967-2052
***@***.***


Em qui., 22 de jul. de 2021 às 13:37, Natan Souza ***@***.***>
escreveu:

**Comment by designernatan** [comment]
renan, você precisa ter completado alguma formação para poder ocultá-la

sobre os cursos serem separados por categorias/escolas (front-end, devops, data science, etc), é esperado que seja separado assim mesmo pois é justamente o intuito do certificado completo

se precisar de certificados de cursos específicos, o caminho é pegá-los individualmente mesmo

**Comment by renanbuenom** [comment]
Entendido, Natan!

Obrigado pela resposta.

Atenciosamente,
*Renan Bueno Machado*
(43) 9 9967-2052
***@***.***


Em ter., 3 de ago. de 2021 às 13:50, Natan Souza ***@***.***>
escreveu:

**Comment by Rodorush** [comment]
Vi que existe a funcionalidade de ocultar o que não queremos, isso resolve parcialmente a questão de enviar somente certificados desejados para o RH da empresa. Precisamos de um botão de ocultar tudo, pois assim vamos desmarcando somente os novos cursos para salvar no PDF. Sem um botão ocultar tudo fica muito trabalhoso ir ocultando tudo a cada envio sendo que a lista de certificados só vai aumentando. É muito mais fácil desmarcar apenas 3 novos certificados, por exemplo, após clicar em ocultar tudo, do que clicar em ocultar em dezenas de certificados para deixar somente 3 visíveis.

**Comment by designernatan** [comment]
@Rodorush seria bacana mesmo, principalmente se tem bastante curso pra ocultar

nao conseguimos priorizar alterações na página mas para não ficar te devendo fiz dois códigos com esse objetivo (esconde tudo). Espero que ajude:

## Esconde formações
```
// Seleciona todos os elementos com a classe 'toggle-printable-section'
var elements = document.querySelectorAll('.toggle-printable-section');

// Itera sobre cada elemento e simula um clique
elements.forEach(function(element) {
    element.click();
});
```

## Esconde todos os cursos
```
// Seleciona todos os elementos com a classe 'toggle-printable-course '
var elements = document.querySelectorAll('.toggle-printable-course ');

// Itera sobre cada elemento e simula um clique
elements.forEach(function(element) {
    element.click();
});
```
