### ISSUE TITLE
Não é possível mudar a formação exibida na dashboard

### ISSUE THREAD

**Issue by lhayana** [caelum/alura-funcionalidades#413]
Quando aperto em mudar formação, vai para a lista de formações e quando clico no item abre a formação ao invés de fazê-la aparecer na dashboard.

Além disso, não está atualizando a formação na dashboard, pois já finalizei e lá aparece que ainda tenho cursos não concluídos.
![erro-alura](https://user-images.githubusercontent.com/34015939/109022081-40416200-769a-11eb-8c86-c81a7c63c1b5.png)

**Comment by sahslima** [comment]
Oi, @lhayana!

Pedimos desculpas pela experiência enfrentada, estamos com um bug nesta área.

Já comunicamos o time de Desenvolvimento e retornamos aqui quando for solucionado, tudo bem?

Um abraço!

**Comment by sahslima** [comment]
Olá, @lhayana! Tudo bem?

Corrigimos, você pode testar, por gentileza?

Aguardo seu aviso por aqui, se deu tudo certo ou não. ;)

**Comment by sahslima** [comment]
Oi, @lhayana!

Espero que tenha dado tudo certo.

Vou fechar aqui, mas caso tenha enfrentado alguma dificuldade, me avise!

Um abraço.
