### ISSUE TITLE
Filtros no campo buscar por tipo de conteúdo

### ISSUE THREAD

**Issue by duducolares** [caelum/alura-funcionalidades#414]
Gostaria que o campo buscar tivesse um filtro por tipo de conteúdo, seja por Cursos, Formações, Podcasts, Artigos, e o que mais tiver.
Pensei nisso ao buscar artigos sobre Power Bi na plataforma, e o conteúdo estava misturado com outros cursos e a informação não estava concentrada em um lugar só. 
É isso, abs

**Comment by sahslima** [comment]
Oi, @duducolares!

A gente concorda e estamos trabalhando em melhorias nos filtros dos campos de busca da plataforma.

Qualquer novidade, te avisamos aqui. ;)

Um abraço.
