### ISSUE TITLE
Notificação de resposta do fórum

### ISSUE THREAD

**Issue by Joaovmir** [caelum/alura-funcionalidades#415]
Quando um tópico do fórum é respondido ou atualizado, há uma notificação que chega por e-mail. Poderia haver algo na plataforma que notifica os participantes daquele tópico, uma vez que chegando por e-mail muitas pessoas podem não ver, e não precisarem ir até a aba de "Minhas discussões" para ver se aquele tópico foi atualizado.

Pode ser um pop-up, ter um botão de notificação, aparecer alguma mensagem na próxima vez que entrar no site ou mudar de página ou mesmo mostrar no dashboard os últimos tópicos que foram atualizados.

Isso evitaria alguns tópicos que não têm retorno tanto para o aluno quanto para a pessoa que respondeu o tópico.

**Comment by sahslima** [comment]
Oi, @Joaovmir!

Obrigada pela sugestão.

Estamos discutindo melhorias para o fórum e vamos considerar seus pontos. ;)

Qualquer novidade, avisamos aqui.

Um abraço!
