### ISSUE TITLE
Baixar podcasts e leituras no celular!

### ISSUE THREAD

**Issue by jianLicio** [caelum/alura-funcionalidades#416]
Eu poderia ir fazer meus exercícios físicos escutando os podcasts, seria maravilhoso, mas não é possível baixar podcasts...

**Comment by sahslima** [comment]
Oi, @jianLicio!

Realmente, ainda não é possível fazer o download dos podcasts, mas estamos com essa funcionalidade no radar. Qualquer novidade, avisamos por aqui. ;)

Um abraço.
