### ISSUE TITLE
Transmissão via notebook

### ISSUE THREAD

**Issue by jianLicio** [caelum/alura-funcionalidades#417]
É possível hoje, entrar no app da alura pelo celular e transmitir o conteúdo para o Chromecast. O mesmo não ocorre quando entro pelo notebook. Não consigo fazer a transmissão para a tv.
Isso faz com que tenha que deixar o celular com internet ativada e consequentemente recebendo notificações de app, me atrapalhando...

**Comment by sahslima** [comment]
Oi, @jianLicio.

Qual navegador você está utilizando no notebook? Pois pelo Chrome, na opção `transmitir` você consegue mandar o conteúdo via Chromecast normalmente.

Consegue descrever um pouco mais ou compartilhar prints do problema com a gente, por gentileza?

Um abraço!

**Comment by jianLicio** [comment]
É possível sim, eu dei aquela sugestão pq um botãozinho ficaria mais agradável hehe. Tipo, foi apenas uma sugestão mesmo 🙃

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by sahslima** [comment]
Ah sim, agora entendi. 

Desculpe o equívoco, @jianLicio.

Vamos deixar a ideia desse "botão" no radar. ;)
