### ISSUE TITLE
Conteúdo completo no celular

### ISSUE THREAD

**Issue by jianLicio** [caelum/alura-funcionalidades#418]
Apenas os vídeos são disponibilizados no app da Alura, seria interessante se eu conseguisse tiver acesso total...

**Comment by sahslima** [comment]
Oi, @jianLicio! Tudo bem?

No app disponibilizamos os vídeos, exercícios, formações, planos de estudo, artigos, podcasts... Qual conteúdo você não conseguiu acessar? Assim podemos verificar por aqui. (:

**Comment by jianLicio** [comment]
Bom dia.
Então, acabei de descobrir q também posso acessar os exercícios pelo celular kkkkk.
Mas assim, eu acho q seria interessante colocar os exercícios em ordem com os vídeos (assim como é feito pelo site web). Pq como está agora, eu assistiria todos os vídeos pra então depois fazer todos os exercícios. Ou seja, colocar o vídeo e logo após os exercícios :)

Mas assim, os podcast eu não consigo fazer download... :/

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by sahslima** [comment]
Realmente, @jianLicio, os exercícios ainda não estão "intercalados" como aparecem na web, mas estamos trabalhando nisso.

Essa alteração deve entrar no app em breve, te avisamos por aqui. ;)

Sobre o download dos podcasts, vimos sua sugestão [aqui](https://github.com/caelum/alura-funcionalidades/issues/416). Respondi por lá.

Um abraço.
