### ISSUE TITLE
Colocar listas de exercícios (ou links) para prática do conteúdo aprendido

### ISSUE THREAD

**Issue by Lks8** [caelum/alura-funcionalidades#419]
Sinto muita falta de exercícios pra fixar o conteúdo aprendido depois de acabar um capítulo do curso. Em outras vezes que esta implementação foi sugerida, a resposta era que há várias listas de exercícios pela internet para praticar, mas nenhum link fornecido. Sinceramente, acho que só falta isso pra plataforma ficar 10/10

**Comment by sahslima** [comment]
Oi, @Lks8! Tudo bem?

Entendemos o seu ponto.

Neste semestre estamos planejando ter mais ações para reforçar e auxiliar na fixação do conteúdo de cursos e formações. Assim que tivermos novidades, te avisamos aqui. ;)

Um abraço.
