### ISSUE TITLE
Playback rate - Velocidade da reprodução do vídeo

### ISSUE THREAD

**Issue by thdesous** [caelum/alura-funcionalidades#42]
Olá, vocês poderiam adicionar a **velocidade de reprodução do vídeo 1.75x**. 
Hoje do 1.5x vai para 2x, é muita diferença, acho que **1.75x** é ideal.

**Comment by designernatan** [comment]
oi @thdesous depende muito do curso, do instrutor, do aluno, etc. Optamos por deixar assim mas é como disse, depende muito de várias variáveis

eu mesmo deixo em 1.8 (alura e youtube), mas uso uma extensao chamada "video speed controller"

**Comment by designernatan** [comment]
esqueci de comentar aqui:

enquanto não tem outras velocidades, rola colocar isso no console do navegador e personalizar de acordo com oq for mais confortavel

para deixar em 7.15x por exemplo:

`document.querySelector('video').playbackRate = 7.15`

**Comment by designernatan** [comment]
time de desenvolvimento da alura codou e agora tem outras opcoes de velocidade :)
