### ISSUE TITLE
Acessibilidade para pessoas surdas ou deficientes auditivas

### ISSUE THREAD

**Issue by bruno-zambotti** [caelum/alura-funcionalidades#420]
Gostaria de propor a adição de assistir os vídeos com legendas utilizando as transcrições que já são realizadas em muitos cursos da plataforma, a fim de possibilitar que pessoas que tenham algum tipo de deficiência auditiva total ou parcial possam passar a ter acesso a este conteúdo.

Outra ideia também, que seria um pouco mais complicada de executar, mas que acredito que seria muito interessante também, seria ter a opção de incluir um(a) interprete de libras (opcional assim como a ideia da legendas) nos vídeos onde ao clicar apareceria e ao desmarcar sumiria.

**Comment by sahslima** [comment]
Oi, @bruno-zambotti!

A gente concorda contigo, precisamos melhorar essa experiência para alunos e alunas com qualquer grau de deficiência auditiva. 

Obrigada por compartilhar suas sugestões, vamos considerá-las em futuras alterações da plataforma.

Um abraço!
