### ISSUE TITLE
certificadoCompletoPeriodo

### ISSUE THREAD

**Issue by ghost** [caelum/alura-funcionalidades#421]
A empresa onde trabalho solicita os cursos realizados dentro de um ano específico. Seria ótimo se a emissão do certificado completo pudesse ser filtrada por datas.

**Comment by sahslima** [comment]
Oi, @MarcosAurelioGIT! Tudo bem?

Isso está no nosso radar para futuras melhorias.

Enquanto isso, você pode contar com o apoio do nosso **Time de Experiência do Aluno** para entregar o certificado no formato que precisa em sua empresa.

Por gentileza, entre em contato [por aqui](https://www.alura.com.br/contato).

Um abraço!

**Comment by Rodorush** [comment]
Olá, gostaria de saber se há alguma novidade para esta sugestão pois o RH da minha empresa também pede para enviarmos os certificados novos que ainda não foram enviados pra eles. Pode ser um filtro por data para enviarmos somente os novos. Vi que existe uma funcionalidade de ocultar o que não queremos, isso resolveria se houvesse ao menos um botão de ocultar tudo, pois assim clicaríamos somente nos novos cursos para salvar no PDF. Sem um botão ocultar tudo fica muito trabalhoso ir desmarcando tudo a cada envio sendo que a lista de certificados só vai aumentando.
