### ISSUE TITLE
Fluxo de nivelamento para cursos

### ISSUE THREAD

**Issue by Giovancruz** [caelum/alura-funcionalidades#422]
Antes de mais nada, queria dizer que a plataforma e didática de vocês é sensacional!

Fiz essa sugestão no inicio da contratação do meu plano na Alura e acredito que seria muito bacana se tivéssemos um fluxo semelhante à isso na plataforma:
* No final do processo de contratação o usuário preencheria com checks, sinalizando seus principais interesses;
* Baseado nisso, a plataforma iria sugerir formações e cursos disponíveis para que ele selecione quais tem interesse;
* O usuário poderia escolher por ter total liberdade em navegar e escolher os cursos ou participar de um processo de nivelamento;
* Com as formações e interesses filtrados, o usuário preencheria o nível de conhecimento nas tecnologias abordadas ou necessárias para as formações/cursos que ele escolheu;
* Esses dados poderiam ser utilizados para gerar testes de nivelamento, para comprovar que o estudante está apto à iniciar a partir de um ponto mais avançado nos cursos

O ponto teria que ser definido pelos tutores por vídeo/conteúdo. Digamos que o usuário preencheu que é avançado/domina HTML: seria disponibilizado alguns exercícios ou prova, no final a pontuação e sugestão de início, com alguns conteúdos de revisão ou atualização da tecnologia.

Esse fluxo talvez até pudesse gerar um certificado ou declaração diferente mostrando que o usuário não participou das aulas, ou participou de x horas mas comprovou sua proficiência no teste e passou com a pontuação X.

Entendo que à nível de implantação seria uma feature enorme e um bigdata gigantesco pra ser gerenciado, mas agregaria muito ao produto de vocês.

;)

**Comment by sahslima** [comment]
Obrigada pela sugestão, @Giovancruz!

Vamos considerar seus pontos em futuras melhorias. ;)

Qualquer novidade, avisaremos por aqui. 

Um abraço.
