### ISSUE TITLE
Resultado de pesquisa, agrupamento

### ISSUE THREAD

**Issue by Micheltpd** [caelum/alura-funcionalidades#423]
Ao realizar uma pesquisa, lá de cima da barra de pesquisa:

Este resultado poderia vir com agrupamentos, por exemplo:
* Cursos
* Certificações
* Artigo
* Videos
* Podcast

E com mais informações para poder filtrar, ou ordenar, mais novos, melhor avaliados, ou mais alunos.

Poderia agora também filtrar por professores, pois com o volume que vcs já possúem, algumas pessoas tem preferencias por conteúdos aplicados por um outro instrutor.

_OBS: Fiz minha pesquisa por AWS, e com o resultado que me surgiu esta idéia._

Adicionalmente parabéns pelo trabalho de todos vocês.

**Comment by sahslima** [comment]
Obrigada pela sugestão, @Micheltpd!

Estamos trabalhando em melhorias dos campos de busca e filtros que eles possuem, para retornar resultados cada vez melhores nas pesquisas dos nossos alunos e alunas, como você.

Qualquer novidade nessa funcionalidade, avisamos por aqui. ;)

Um abraço.
