### ISSUE TITLE
Alterar a ordem dos planos de estudos

### ISSUE THREAD

**Issue by LeonardoSalmento** [caelum/alura-funcionalidades#424]
Olá pessoal da alura!

Minha sugestão, seria conseguir realizar alterações na ordem dos planos de estudo já cadastrados. 

![example](https://user-images.githubusercontent.com/29843724/110836053-5cd6c000-827e-11eb-83a5-98135e069bc1.PNG)

Este foi o meu caso, eu acabei não cadastrando na ordem certa, e queria apenas reordenar os planos de estudos.
Acredito que a forma mais legal seria um "drag and drop" para reordená-la, mas qualquer meio de reordená-los já seria bem interessante.

**Comment by sahslima** [comment]
Oi, @LeonardoSalmento! Tudo bem?

Ótima sugestão.

Vamos deixar no radar para as melhorias dessa área.

Qualquer novidade, avisamos aqui. ;)

Um abraço!
