### ISSUE TITLE
Sugestão referente ao nome de cursos com nova versão

### ISSUE THREAD

**Issue by zitelli** [caelum/alura-funcionalidades#425]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.
Quando um curso tem uma nova versão, sugiro fazer alguma diferenciação em seu nome com relação ao curso original.
Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.
A exemplo do curso "Java e JDBC: Trabalhando com um banco de dados" que teve uma nova versão, e manteve o mesmo nome que aquele do curso original. Isso prejudica aqueles alunos que concluiram ambos os cursos, pois em seu curriculo aparecem dois cursos iguais, quando na verdade houveram algumas modificações.
Outro ponto que sugiro revisão é com relação à relação de cursos completados pelo link em "certificado completo" em "lista "Perfil & Certificados" (a exemplo do meu caso: https://cursos.alura.com.br/user/fpzitellij/fullCertificate/d3adc3ad049ca0653f5c80d5445c8336)
Aparecem cursos repetidos em formações distintas, isso dificulta o entendimento quando compartilhamos este link em nosso curriculo para as empresas. Sugiro gerar outro certificado com a relação: "Cursos/Formações" e não "Formações/Cursos", para não haver repetições destes.

Obrigado.

**Comment by sahslima** [comment]
Oi, @zitelli! Tudo bem?

O cenário que descreveu faz sentido, vamos analisar como melhorar essa parte para cursos atualizados.

Sobre a sugestão de certificados, é algo que já tinham apontado por aqui e estamos considerando nas mudanças que planejamos para esse ambiente.

Assim que as novidades estiverem no ar, avisamos por aqui! ;)

Obrigada por compartilhar seus pontos.

Um abraço!
