### ISSUE TITLE
Adicionar certificação ao Linkedin na opção de "Outras ações".

### ISSUE THREAD

**Issue by Jeff-syscyber** [caelum/alura-funcionalidades#426]
Na minha opinião seria uma boa colocar o botão de adicionar a certificação ao linkedin em outras ações dos cursos após finalizá-lo 100%.

**Comment by sahslima** [comment]
Oi, @Jeff-syscyber!

Obrigada pela sugestão.

Estamos desenvolvendo algumas melhorias para a parte de certificados e vamos considerar seu ponto. ;)

Um abraço!
