### ISSUE TITLE
Modo Noturno

### ISSUE THREAD

**Issue by Jeff-syscyber** [caelum/alura-funcionalidades#427]
Função de modo noturno na plataforma além de ter dentro dos cursos, as vezes chega a incomodar os olhos ao decorrer do tempo vem me causando tonturas também, então acho que seria uma boa implementar isso na plataforma.

#397

**Comment by sahslima** [comment]
Oi, @Jeff-syscyber!

O modo noturno para toda plataforma é algo que está no nosso radar.

Assim que for implementado, te avisamos aqui. ;)

Um abraço!
