### ISSUE TITLE
Continuar de onde parou os cursos já concluídos

### ISSUE THREAD

**Issue by fabiofb** [caelum/alura-funcionalidades#428]
Poderia existir uma forma de acompanhar/gerenciar os cursos já concluídos dando a possibilidade de continuar de onde parou, como ocorre com os cursos em andamento não finalizados. 

Seria interessante uma marca/tag que sinalize com clareza que o curso foi finalizado e esta sendo reassistido mas que permita continuar de onde parou.

**Comment by sahslima** [comment]
Oi, @fabiofb!

Obrigada pelo feedback.

Vamos manter seu ponto no radar para futuras melhorias.

Qualquer novidade, avisaremos por aqui. ;)

Um abraço!
