### ISSUE TITLE
Alura Rewards 

### ISSUE THREAD

**Issue by Assumps** [caelum/alura-funcionalidades#429]
- Ideia inicial e que todos os seus esforços dentro da plataforma seja recompensada de alguma forma, como juntar pontos e trocarmos por itens, camisetas, ou ate mesmo descontos em bootcamps nem que seja algo em torno de 5 a 20% de desconto, tendo alguma funcionalidade além do que apenas mostrar o ranking

pontos importantes

- Dar mais dinâmica a funcionalidade de pontuações
- Aumentar ainda mais a vontade de aprender dos alunos além de conseguir o certificado ganhar itens físicos ou dar ainda mais continuidade nos estudos
- maiores aquisições a alguns bootcamps, onde alunos que não tem tanto potencial monetário possam adquirir por meios desses pontos conseguir trocar por conhecimento mais aprofundado

**Comment by sahslima** [comment]
Oi, @Assumps!

Obrigada pela sugestão.

Qualquer novidade nesse sentido, te avisaremos por aqui. ;)

Um abraço!
