### ISSUE TITLE
Notificações de perguntas nos fóruns

### ISSUE THREAD

**Issue by thdesous** [caelum/alura-funcionalidades#43]
Olá, hoje vejo que muitos alunos criam perguntas nos fóruns e as vezes, devido o time da resposta preferem partir para outro curso, ou pausar, ou até ignorar o problema para não perder o time das aulas. 

Vejo que um problema relacionado há isso já está sendo tradado @peas já mencionou em outro issue, no caso aumentar o quadro do time de suporte. 

Acho que dá para a comunidade ajudar neste caso, e ser recompensada de alguma forma (gamefication). Mas para isso acontecer, seria necessário reavaliar como a plataforma trata as notificações dos alunos, ou seja, hoje eu não recebo nenhuma notificação de novas perguntas que fizeram no curso/formação que estou inscrito. 

**Sugestão da funcionalidade:** Adicionar uma notificação para novas perguntas de alunos para outros alunos nos cursos/formações que estão inscritos, assim acho que o tempo de resposta e o engajamento dos alunos será massa! =)

**Comment by designernatan** [comment]
oi @thdesous 

um gamefication que envolva mais essa interação de alunos com alunos é algo que queremos atacar em breve

algo envolvendo formações feitas com perguntas no fórum, notificações, o ranking em geral

valeu pela sugestão! :)

**Comment by lcscastro** [comment]
Poderia habilitar para os alunos que concluíram o curso

**Comment by wandersonmaceds** [comment]
Oi @thdesous tudo bem? Acho que sua sugestão faz perfeito sentido, mas eu fiquei curioso pra ver essa outra issue que você comentou que o Paulo disse algo a respeito. Você poderia colocar o link dessa outra issue aqui?

**Comment by thdesous** [comment]
@wandersonmaceds ta na mão... [issue 37](https://github.com/caelum/alura-funcionalidades/issues/37#issuecomment-575269049)

**Comment by wandersonmaceds** [comment]
Oi @thdesous tudo bem? Voltando.

Entrou no ar algo parecido com o que você sugeriu, está em beta então pode ter problemas no funcionamento. Você pode ir até as opções do seu perfil e marcar a opção "receber dúvidas dos cursos que fiz semanalmente". Toda segunda pela manhã você receberá, em seu email, se houver, dúvidas abertas sobre os cursos que você estudou.

Pode ir direto por este link: https://cursos.alura.com.br/my_profile

A opção está logo acima dos seus dados pessoais (nome, sobrenome, etc).
