### ISSUE TITLE
Exportar o certificado com nome do curso

### ISSUE THREAD

**Issue by efcjunior** [caelum/alura-funcionalidades#430]
Prezados,

Todas vezes que salvo o certificado em PDF, preciso renomear o nome do arquivo. É interessante sugerir o nome do curso como sendo o nome do arquivo a ser exportado ou salvo.

**Comment by sahslima** [comment]
Oi, @efcjunior.

Obrigada pelo feedback, vamos deixar seu ponto no radar para futuras melhorias.

Um abraço!
