### ISSUE TITLE
Feedback do Curso

### ISSUE THREAD

**Issue by nipi800** [caelum/alura-funcionalidades#431]
Um botão dentro do curso que permita o envio de feedback para os instrutores ou para a plataforma Alura, ou ambos.
Para que possamos ter uma melhoria constante daquele curso.
E do outro lado alguma forma de disponibilizar essa informação às pessoas relevantes.

**Comment by sahslima** [comment]
Oi, @nipi800! Tudo bem?

Dentro do curso você consegue dar um feedback, ou sugerir alterações no conteúdo, clicando no ícone que fica acima do player de vídeo:
![image](https://user-images.githubusercontent.com/59886589/113791015-12c7e980-9719-11eb-990b-7f050ac92194.png)

Ao finalizar um curso você também consegue dar sua opinião sobre o que achar relevante, sejam aspectos positivos ou negativos, técnicos ou didáticos. (:

Você já conhecia ou tinha utilizado algum dos recursos mencionados acima? 

Caso sim, em quais pontos eles ainda não atendem ao que você sugeriu?

Sobre "_E do outro lado alguma forma de disponibilizar essa informação às pessoas relevantes._", por **pessoas relevantes** você quer dizer amigos, outros alunos e alunas da comunidade ou outras pessoas?

**Comment by nipi800** [comment]
Oi @sahslima, conhecia sim. Tentei utilizar o "Sugerir alteração", mas ele não me atendeu.
Porque ele pede que eu mude necessariamente algo do texto.
Acho que poderia ter mais categorias também além das apresentadas, e que o campo abaixo (transcript) fosse algo contextual, apenas se a pessoa quer mudar isso.

Ao finalizar o curso é tarde, muitos feedbacks podem se perder ao longo de se fazer, mt gnt n vai anotar um feedback de uma aula específica do começo pra falar só no final.

Pessoas relevantes digo aos instrutores, pessoas da comunidade e quem quer que seja que esteja interessado na melhoria contínua do conteúdo.

Abraços.

**Comment by designernatan** [comment]
@nipi800 parece uma boa mesmo, vamos dar uma pensada quando pegarmos a tela de aula para a melhorarmos

valeu pela sugestao!
