### ISSUE TITLE
Fluxo contínuo dos vídeos

### ISSUE THREAD

**Issue by nipi800** [caelum/alura-funcionalidades#432]
Um player integrado que permita a escolha de fluxo contínuo do vídeo.
Seja no mínimo um botão dentro do player que me permita passar para a próxima lição sem sair do full screen.
Ou a mesma que Youtube e Netflix que passa para o próximo vídeo da lista em alguns segundos após o término do atual.

**Comment by sahslima** [comment]
Oi, @nipi800!

O **autoplay** sempre foi uma funcionalidade muito pedida e lançamos em janeiro deste ano. [Neste artigo](https://www.alura.com.br/artigos/novidades-de-janeiro-na-alura) explicamos como funciona para ativá-lo. (: 

Caso esteja com alguma dúvida ou dificuldade para usar a função, avise pra gente!

Um abraço.

**Comment by nipi800** [comment]
![image](https://user-images.githubusercontent.com/42882917/115771501-6460ad00-a384-11eb-80ae-bcfd5c72c72a.png)
Então, vi o Guia e tentei utilizar, mas não aparece para mim essa opção.

**Comment by designernatan** [comment]
@nipi800 acredito que sua conta está com licença de empresa, correto?

autoplay por hora funciona apenas para alunos "diretos" que não há um contrato de empresa por cima

**Comment by JonatasAmaral** [comment]
Olá.

Existe alguma razão especifica para essa feature não estar disponível para planos de empresas?

O autoplay funciona no app (apenas nas videoaulas), porem é muito mais cômodo usar o computador com tela maior, podendo acompanhar o código/resulta, etc.

Alguma previsão para a adição disto?

**Comment by designernatan** [comment]
jonatas, é mais um direcionamento da maioria das empresas do que nosso, por hora só app mesmo :/
