### ISSUE TITLE
Flashcards

### ISSUE THREAD

**Issue by ghost** [caelum/alura-funcionalidades#433]
Olá. Fiz um curso na plataforma EAD do Senai e notei que, ao final de cada capítulo, você poderia acessar flashcards com os pontos mais importantes do capítulo. 

https://quizlet.com/294248075/i2cyber-v21-brpt-chapter-1-flash-cards/

Ver o conteúdo de forma interativa me ajudou muito no aprendizado e gostaria de ver isso na Alura.

**Comment by sahslima** [comment]
Oi, @taezord!

Obrigada por compartilhar.

Esse formato é bem interessante, vamos considerar para futuras melhorias na plataforma. ;)

Um abraço!
