### ISSUE TITLE
Poder salvar os vídeos do Alura+ para ver depois ou adicionar em um plano de estudos próprio

### ISSUE THREAD

**Issue by Amanda13B** [caelum/alura-funcionalidades#434]
Uma funcionalidade que acho que pode ser interessante é a possibilidade de salvar os Alura+ assim como podemos salvar os cursos (seja adicionando à dashboard ou a um plano de estudos que nós criamos). Seria interessante para que as pessoas possam ver novamente o conteúdo caso achem interessante ou caso só possam ver mais tarde e não querem perder o vídeo.

A ideia seria poder "salvar para ver mais tarde" ou poder adicionar aos nossos planos de estudo que nós criamos, justamente para que esse conteúdo fique à mão mais facilmente tanto para poder rever quanto para poder acessar posteriormente.

Obrigada pela atenção! :D

**Comment by sahslima** [comment]
Oi, @Amanda13B! Tudo bem?

Obrigada pela sugestão sobre o "salvar para ver mais tarde", vamos estudá-la com carinho!

A boa notícia é que dá sim para inserir Alura+ nos seus planos de estudo.

No momento de montar ou editar um plano, você vai clicar em `Adicionar novo passo`:
![image](https://user-images.githubusercontent.com/59886589/113792389-36d8fa00-971c-11eb-9bb6-593b268844b8.png)


No campo de busca que abrirá, é só **inserir o link do Alura+ desejado** > clicar em `Buscar` > clicar em `Adicionar` no conteúdo encontrado:
![image](https://user-images.githubusercontent.com/59886589/113792445-596b1300-971c-11eb-9120-7f22857b3e79.png)



Feito isso, você vai `Salvar plano de estudos`:
![image](https://user-images.githubusercontent.com/59886589/113792718-f5951a00-971c-11eb-822c-6b421545a8d0.png)



E o Alura+ passa a ser exibido:
![image](https://user-images.githubusercontent.com/59886589/113792765-1198bb80-971d-11eb-9d0a-6709eb842ade.png)


Depois testa por aí e qualquer dificuldade, avisa pra gente! ;)

Um abraço.
