### ISSUE TITLE
No plano de estudos, ter opção de substituir um curso quando desabilitado

### ISSUE THREAD

**Issue by julianlfs** [caelum/alura-funcionalidades#435]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

No plano de estudos, ter opção de substituir um curso pela sua nova versão, quando desabilitado.

Por exemplo, no meu plano de estudos havia adicionado o curso "Java e JPA: Persista seus objetos com a JPA2 e Hibernate", porém agora ele aparece como desabilitado, e ao entrar nele tem o link "nova versão' que redireciona para o curso "Persistência com JPA: Introdução ao Hibernate".
Para fazer a substiuição atualmente, preciso editar o plano, verificar qual o novo curso para adicionar e ainda exclui o curso desabilitado.

Poderia ter um botão, com uma mensagem de confirmação, se o usuário deseja substituir o curso pela nova versão do mesmo.

**Comment by sahslima** [comment]
Oi, @julianlfs. Tudo bem?

Obrigada por levantar esse ponto.

Vamos implementar essa correção e aviso quando estiver no ar. ;)

Um abraço!
