### ISSUE TITLE
Legendas no vídeo

### ISSUE THREAD

**Issue by asgunzi** [caelum/alura-funcionalidades#436]
Olá.

Os vídeos são muito bons, e vi que há uma transcrição do texto em alguns dos cursos.

A sugestão é permitir legendas nos vídeos, como no Youtube. Já ter a transcrição ajuda muito, é só colocar no tempo, e a plataforma de vídeos permitir.

A vantagem é facilitar o entendimento de quem pouco domina o português, ou tem dificuldade auditiva.

**Comment by sahslima** [comment]
Oi, @asgunzi! Tudo bem?

Estamos nos preparando para implementar essa melhoria, mas ainda não consigo compartilhar uma data de lançamento.

Qualquer novidade sobre o assunto, avisamos por aqui. ;)

Um abraço!
