### ISSUE TITLE
Cursos do qual este é um pré-requisito

### ISSUE THREAD

**Issue by miguel-pramos** [caelum/alura-funcionalidades#437]
Ao entrar na página de um curso podemos ver os pré-requisitos, ou seja, cursos com conhecimento necessário para começar o curso. Acho que seria interessante se houvesse também o contrário, que mostrasse os cursos que poderiam dar seguimento com a linha de estudo que o aluno deseja.

**Comment by sahslima** [comment]
Oi, @Pererote!

Obrigada pela sugestão.

Já tivemos um "recomendador" na plataforma, mas desabilitamos há algum tempo.

Estamos estudando outras formas de orientar esses próximos passos, enquanto isso uma das alternativas é guiar seu aprendizado através de um plano de estudos sobre o tema que deseja aprender. ;)
