### ISSUE TITLE
Visualização completa do Ranking

### ISSUE THREAD

**Issue by marcotvarau** [caelum/alura-funcionalidades#438]
Sempre fico ansioso para saber se estou próximo de chegar aos 10.000 primeiros colocados no ranking da plataforma. Então minhas sugestões são:
1 -  Colocar o meu ranking preciso (no momento só consigo ver que estou depois do 10.000º colocado)
2 - Permitir que o usuário realize um scroll up para ver as pontuações dos usuários mais bem colocados.

Espero que minha sugestão tenha sido válida e útil e obrigado pelo serviço de qualidade ímpar que vocês prestam à comunidade de desenvolvedores brasileira!

**Comment by sahslima** [comment]
Oi, @marcotvarau! Tudo bem?

Obrigada por compartilhar esses pontos, vamos considerá-los em futuras melhorias do ranking. ;)

Um abraço.
