### ISSUE TITLE
Remover pre-requisitos de cursos

### ISSUE THREAD

**Issue by jhionan** [caelum/alura-funcionalidades#44]
Entendo que Alura quer trazer um curso completo, mas assim só tem um público de iniciantes, alguém que tenha um conhecimento intermediário ou só quer melhorar em algum tópico por exemplo testes não consegue assistir só a essas aulas.

**Comment by designernatan** [comment]
oi jhionan vc pode sugerir em 'sugira um curso' lá no rodapé, que aí já cai direto para o time de conteúdo

sei que eles usam as sugestões de lá para ajudar na priorização do backlog

abcs
