### ISSUE TITLE
Canal de comunicação com seus clientes

### ISSUE THREAD

**Issue by marcondetre** [caelum/alura-funcionalidades#440]
Sou assinante hoje ao acessar o conteúdo me deparei com o bloqueio do conteúdo, sendo que o desconto é realizado mensalmente no meu cartão, por isso, um canal de comunicação ( chat on-line) seria essencial pra resolver esse tipo de coisa aos seus clientes.

**Comment by sahslima** [comment]
Oi, @marcondetre!

Apesar de não termos chat na plataforma, temos [outros canais como o WhatsApp](https://www.alura.com.br/contato), por exemplo.

Você já conseguiu apoio do nosso time de experiência do aluno?

Caso a questão ainda esteja sem solução, avise a gente!

Um abraço.
