### ISSUE TITLE
Adicionar marcação nos vídeos

### ISSUE THREAD

**Issue by vcrsantos** [caelum/alura-funcionalidades#441]
Ter a opção de adicionar um marcador nos vídeos. 
Por exemplo: 
Gostei de uma explicação em um dos vídeos, no inicio da explicação eu adiciono um marcador. Então sempre que eu quiser, eu acesso este marcador e o video se inicia exatamente no tempo em que eu marquei.

Sugestões de funcionalidades:
- Definir o tempo exato da marcação (pode ser direto no player do video);
- Adicionar um título;
- Organizar em pastas, listas ou por curso mesmo.

**Comment by sahslima** [comment]
Obrigada pela sugestão, @vcrsantos!

Vamos manter no radar para futuras melhorias. ;)

Um abraço.
