### ISSUE TITLE
Maior aproveitamento da tela

### ISSUE THREAD

**Issue by VanderleiDamasceno** [caelum/alura-funcionalidades#442]
Olá!

Vejo que no campo de exercícios consta a funcionalidade de rodar a tela para a direita para leitura das instruções. 
Imagino se houvesse maior aproveitamento da tela total, seria  desnecessário ao usuário "rolar" a tela para ler. 
Vejo, ainda,  que "sobra" espaço para o devop expandir a tela, minimizando o esforço do usuário (vide captura de tela anexa).

![aproveitamento_maior_tela](https://user-images.githubusercontent.com/77650121/114306598-a2232300-9ab2-11eb-8c39-59bc6d0d5ede.JPG)

Estou à disposição no celular,  caso não tenha sido claro.

Parabéns a todos da Alura pela excelente qualidade do que vi até aqui. 

Grande abraço,

**Comment by designernatan** [comment]
@VanderleiDamasceno valeu pela sugestão!

hoje se você habilita o modo teatro no player de vídeo da aula, essa área do código fica maior também

[lançamos o modo teatro ano passado](https://www.alura.com.br/artigos/novidades-de-novembro-na-alura) já pensando nesse caso :)

abração!

**Comment by VanderleiDamasceno** [comment]
Obrigado pelo retorno, Natan

vou testar.

Grande abraço

Em seg., 19 de abr. de 2021 às 18:25, Natan Souza ***@***.***>
escreveu:
