### ISSUE TITLE
Ordenar/Visualizar cursos por duração

### ISSUE THREAD

**Issue by felipebraga** [caelum/alura-funcionalidades#443]
Como aluno, gostaria de poder listar os cursos por duração ou uma outra forma de filtrar eles.

As vezes queremos fazer cursos rápidos, coisas de final de semana ou final do dia e no lugar de assistir um vídeo aleatório no Youtube, poder aprender algo, ou aprimorar alguma coisa.

**Comment by designernatan** [comment]
@felipebraga valeu pela sugestao!

tem uma [issue parecida com essa aqui](https://github.com/caelum/alura-funcionalidades/issues/423) 

estamos com a busca na mira para um futuro próximo, sem datas ainda, porém ordenar por tempo fica um pouco fora uma vez que os vídeos e aulas estão sempre sendo lançados com um tempo em baixo de duração, coisa de 7~10min

de qualquer forma, vamos discutir isso aqui mais pra frente, ok?

abcs!
