### ISSUE TITLE
Pesquisa de Cursos por nome do Instrutor

### ISSUE THREAD

**Issue by sagravena** [caelum/alura-funcionalidades#444]
Na pesquisa poderia ter opção de escolher buscar por nome do instrutor. Ao selecionar esse modo de pesquisa o usuário colona o nome completo ou parte do nome do instrutor e o sistema irá retornar todos os cursos daquele instrutor.

Vejo que essa possibilidade de filtragem é interessante porque gostamos da didática de certos instrutores e seria legal achar os demais cursos deles.

**Comment by designernatan** [comment]
@sagravena valeu pela sugestao!

tem uma [issue parecida com essa aqui](https://github.com/caelum/alura-funcionalidades/issues/423) 

estamos com a busca na mira para um futuro próximo, sem datas ainda, mas filtrar por professor(a) é algo bacana sim!

valeu! :)
