### ISSUE TITLE
Opção de Certificados em Ingles

### ISSUE THREAD

**Issue by kauantp** [caelum/alura-funcionalidades#445]
Seria Muito bom se tivesse a opção de gerar um Certificado em inglês, principalmente nessa epoca de pandemia, com o trabalho remoto se mostrando cada vez mais usado, há muitas possibilidades abertas em outros países, e seria muito bom poder ter o reconhecimento do certificado Sem precisar de uma tradução manual

**Comment by designernatan** [comment]
oi @kauantp, valeu pela sugestao!

tem uma [issue semelhante](https://github.com/caelum/alura-funcionalidades/issues/6) aqui

e o [reply do paulo sobre o assunto](https://github.com/caelum/alura-funcionalidades/issues/6#issuecomment-561853046) ainda se mantém para essa questão, ok?

acredito que daria para resolver só jogando no translate (do nosso lado que digo), mas hoje o processo para isso ainda é pingar no contato@alura.com.br

demanda ainda é consideravelmente pequena :/

**Comment by efcjunior** [comment]
Olá, @designernatan 

Iria fazer esta mesma sugestão. Creio que atualmente boa parte das seleções ou primeiro contato das entrevistas tem sido pelo LinkdIn. Ademais, a plataforma Upwork, umas mais conceituadas para se trabalhar como freelancer, orienta submeter o currículo baixado do LinkdIn. Para isso, no meu caso hoje por exemplo, preciso traduzir 13 certificados da Alura, que parece simples, mas um pouco trabalhoso. Dado que estamos cada vez mais imersos nos cursos da Alura, aumentam-se as certificações e consequentemente o tempo das traduções. Por isso, na minha opinião, a opção de geração de certificado em inglês trazeria um excelente benefício aos alunos / profissionais de TI.

Abraços,
Everson

**Comment by designernatan** [comment]
oi @efcjunior 

perfeito, seria bacana algo automatizado mesmo, o ponto é que pela demanda isso não está nos planos

precisando desses certificados, só pedir para para o time no contato@alura.com.br ok?

abcs!
