### ISSUE TITLE
Separar no forum dúvidas reais de respostas de exercícios.

### ISSUE THREAD

**Issue by Xaponeis** [caelum/alura-funcionalidades#446]
Ao procurar tópicos nos fóruns para ajudar na resolução de dúvidas frequentemente tópicos que não são dúvidas e sim apenas respostas de exercícios aparecem.

Ficam "poluindo" a lista de tópicos e dificultam encontrar aqueles em que o usuário realmente quer uma resposta.

Não sei se esses tópicos de respostas de exercícios são criados automaticamente ao responder alguns exercícios mas seria interessante que tivessem uma divisão no forum com posts de respostas de exercícios que não são dúvidas daqueles que o são, seja adaptando para que respostas de exercícios não caiam diretamente no forum ou dando a opção de escolher o tipo de tópico na hora de criá-los para poder filtrá-los posteriormente por esse tipo.

Fica desanimador ficar abrindo tópicos a todo momento que estão sem respostas e que não existe nenhum dúvida para responder.

**Comment by designernatan** [comment]
@Xaponeis valeu pela sugestao!

em termos geral o fórum é para ser um ambiente não somente focado em dúvidas, mas em troca de ideias, por isso incentivamos bastante exercícios que envolvam o fórum nos cursos

quando pegarmos o fórum para melhorá-lo vamos considerar essa sua sugestao, tudo bem?

uma duvida minha: como voce faz hoje exatamente pra responder duvidas de outras pessoas no fórum? 

abcs!

**Comment by Xaponeis** [comment]
Opa, basicamente eu entro no forum e fico alternando entre as categorias (programação, front-end, devops, data-science e off-topic) que desejo responder usando filtro "sem solução" ou "sem resposta".

O processo é meio chatinho na verdade pq vc tem q toda hora ficar alterando entre as categorias ou dando refresh.

A questão das resoluções de exercícios misturadas com as dúvidas agrava um pouco pq a interface (texto, espaçamento vertical, etc) do forum é muito grande tb. Vc precisa rolar mto a tela para navegar entre os tópicos e ficar mudando de página já q acabam ficando  na primeira página sem resolução os tópicos com as respostas de exercícios. Acho q ajudaria tb ter um modo compacto de visualização do tópicos.

O ideal para mim seria algo como vc poder se inscrever nas categorias/subcategorias e recebesse uma notificacao no browser qdo uma nova dúvida surgisse dessas categorias (email poluiria mto). Um botão de fácil acesso de ligar e desligar essas notificações. Isso pq daria para deixar essas notificações pelo período q estou no computador e disponível para responder dúvidas, evitaria de ter q ficar entrando a todo momento e atualizar a página.

**Comment by designernatan** [comment]
brigadao por esclarecer 🙏🏽

a gente tinha uma feature que a pessoa marcava no perfil, e recebia por email uma lista de duvidas por email 1x por semana, acabamos matando pois nao atingiu o resultado que esperávamos 

fazer algo como um sign in por categoria parece uma boa também, valeu pela ajuda!
