### ISSUE TITLE
Sistema de treinamento com questões e nota final.

### ISSUE THREAD

**Issue by TheMartinfer22** [caelum/alura-funcionalidades#447]
Um sistema semelhante com o Linkedin, onde você pode simular suas habilidades com as linguagens ou demais cursos, onde é apresentado as questões e você precisa faze-las com um cronometro para cada questão, você pode refaze-las todo mês e ficará em seu perfil como uma 'badge', juntamente um sistema para treinar porém, não há recompensas apenas as questões e o cronometro.

**Quem fará as questões frequentes?**  Para não exigir tanto dos profissionais que atuam na plataforma, poderiam deixar os próprios estudantes adicionarem as questões porém, elas são avaliadas e para cada questão 50 pontos de XP ou mais (Limite diário).

**O que isso mudaria aos alunos?** Bom, basicamente iria proporcionar segurança na linguagem ou demais cursos para saber quais tópicos a pessoa precisa voltar atrás e rever.

_A ideia surgiu como de começo eu disse do Linkedin, ela pode ser adaptada para a nossa plataforma.
O real problema do Linkedin é em relação a tradução das perguntas, então seria um grande benefício ter uma plataforma que poderia oferecer isso em PT/BR._

**Comment by designernatan** [comment]
oi pessoal, gosto bastante! Achei legal sua preocupação com o fator 'escalabilidade' @TheMartinfer22 <3

é algo bem novo e fora do radar, mas tem potencial bem forte

se tiver alguma novidade no futuro aviso aqui

**Comment by designernatan** [comment]
pessoal, fechando a issue mas podem comentar mesmo com ela fechada :)
