### ISSUE TITLE
Bug que, às vezes, acontece na aula de qualquer curso ao usar a tecla de espaço para dar play/pause num vídeo

### ISSUE THREAD

**Issue by micalevisk** [caelum/alura-funcionalidades#448]
> Testado apenas no Firefox.

Na página `https://cursos.alura.com.br/course/...` em alguma task com vídeo, às vezes ocorre um conflito de ações disparadas com a tecla de espaço: play/pause do vídeo e o menu lateral encolhe/abre.

Não consegui identificar como reproduzir esse bug :confused:  
A aula estava pausada e eu estava em outra aba do navegador. Ao voltar (<kbd>ctrl</kbd>+<kbd>tab</kbd>) para a aba da aula e apertar <kbd>space</kbd>, aconteceu isto:

https://user-images.githubusercontent.com/13461315/116092844-26a9a000-a674-11eb-8821-ac7af4b363e8.mp4

foi resolvido ao clicar no player do vídeo, como mostrado no final. É um bug bem bobo mas achei válido reportar xD

**Comment by designernatan** [comment]
@micalevisk youtube sobre disso um pouco tbm :)

pensando nisso que eles usam a tecla "K" pra controlar o play/pause do vídeo
testa na alura também que vai funcionar e não terá bug!

opa nao é bobo nao!! Quando subimos os atalhos esquecemos uns pontos importantes :P

valeu!
