### ISSUE TITLE
Links Extras de Cursos Concluídos

### ISSUE THREAD

**Issue by Heinrick-Senna** [caelum/alura-funcionalidades#449]
Poderiam ser disponibilizados na tela do curso os links extras (artigos, links externos, etc...) utilizados no curso.

Por exemplo, quando acabo um curso, as vezes quis compartilhar esse artigo ou reler, mas tenho que procurar por entre as aulas. Poderia haver uma indexação de links mais prática na tela apresentação do curso, seja para todos ou para quem concluiu.

**Comment by designernatan** [comment]
@Heinrick-Senna valeu pela sugestao!

gosto disso, hoje o que faço na alura é ir jogando o que acho interessante pra ler depois num notion, e os para ler tipo mais tarde no mesmo dia num [pocket](https://getpocket.com/my-list)

enquanto nao atacamos algo assim, fica a sugestao de ir montando algo assim

abracao!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
