### ISSUE TITLE
Reiniciar Curso

### ISSUE THREAD

**Issue by GuilhermeCesar** [caelum/alura-funcionalidades#45]
Criar a opção de reiniciar um curso já feito anteriormente, para que possa saber em qual parte você está estudando mais uma vez.

**Comment by designernatan** [comment]
valeu pela sugestao @GuilhermeCesar 

tem uma [issue igual a essa aqui](https://github.com/caelum/alura-funcionalidades/issues/11)

vou fechar essa por conta disso, mas em suma estamos vendo de como melhorar a experiência de vocês na hora de refazer um curso

Pode me mandar o link do seu perfil da alura dps? Qual curso **hoje** você precisaria resetar (pergunto mais por pesquisa mesmo)

abcs!

**Comment by GuilhermeCesar** [comment]
Os de vuejs https://cursos.alura.com.br/course/vue-parte1

**Comment by GuilhermeCesar** [comment]
https://cursos.alura.com.br/course/vue-parte1
