### ISSUE TITLE
Opção de download de texto

### ISSUE THREAD

**Issue by Daniell-Dantas** [caelum/alura-funcionalidades#450]
**Contextualização:**
Olá, estou fazendo algumas formações com horário certo por dia, já até fiz um calculo para saber quando vou terminar. Tomando como base esse contexto, percebo e analiso tudo que me retira ou ganha alguns minutos que seja, e é com base nisso que trago a sugestão:

Eu estudo escrevendo tudo que tem na parte de "Transcrição", em cada aula. Geralmente copio e colo direto no google colab (no meu caso em específico, falo da formação Data Science), mas percebi que isso está me tirando muito tempo, chegando ao ponto de decidi só copiar toda a página e colocar em um word (mesmo que desformatado).

**Minha sugestão é:** 
Disponibilizar um botão de download do conteúdo presente na Transcrição já em formato PDF, para poupar trabalho de muitos que, como eu, gostam de salvar o material para estudar depois.

**Comment by laisgalvaos** [comment]
Olá @Daniell-Dantas, obrigada pela sugestão.

Nós analisamos as demandas recorrentes dos alunos para incluirmos nas atualizações. A tela e funcionalidades das aulas está no radar para novas melhorias. Quando formos revisitá-la, vamos considerar essa sua sugestão, tudo bem?

Abcs!

**Comment by designernatan** [comment]
pessoal, fechando a issue mas podem comentar mesmo com ela fechada :)
