### ISSUE TITLE
Filtros e ordenação nas buscas

### ISSUE THREAD

**Issue by lucasdemoraesc** [caelum/alura-funcionalidades#451]
Seria interessante a possibilidade de filtrar os resultados de uma busca feita no dashboard.
Por exemplo: Se pesquiso por, "testes de aceitação", poderia ter a possibilidade de filtrar os resultados entre "Artigos", "Cursos", Poadcasts", "Formações", etc...
Também seria interessante poder ordenar os resultados, seja por ordem alfabética, ou selecionar qual categoria (curso, artigo...) quero ver no topo.

![image](https://user-images.githubusercontent.com/48826783/116690965-8f548d80-a990-11eb-98f3-e9998b880cd9.png)

**Comment by laisgalvaos** [comment]
Olá @lucasdemoraesc, sua sugestão está alinhada com outras sugestões que já verificamos no fórum e essa tela de busca com filtragem já está nos nossos planos para um futuro próximo ;)
Quando estiver pronto, voltamos aqui para te contar.

Abç

**Comment by ghost** [comment]
Olá @laisgalvaos!
Eu quando assisto um curso de um determinado professor e gosto da didática, costumo buscar na página do perfil dele quais os outros cursos que ele gravou. Só que eu percebi esses dias que os cursos que saíram da grade não aparecem mais na página. Então se nos filtros da página de pesquisa fosse adicionada a pesquisa por professor e uma opção de mostrar cursos que estão fora da grade seria de grande valia para mim.

**Comment by laisgalvaos** [comment]
Olá @daniel-dotnet,

sua sugestão faz sentido. sobretudo a busca pelos professores, vamos analisar, mas por hora não temos uma previsão.
qualquer novidade voltamos nesse issue contar.

Abrç

**Comment by designernatan** [comment]
pessoal, fechando a issue mas podem comentar mesmo com ela fechada :)

uma busca melhor está no forno para futuro próximo
