### ISSUE TITLE
Bug resposta do forum

### ISSUE THREAD

**Issue by Xaponeis** [caelum/alura-funcionalidades#452]
Alguns posts no forum tem "quebrado" após respondê-lo.
Algum caractere aparentemente tá fazendo com que a página renderize pela metade ou algo do tipo.
Aconteceu algumas vezes.

Exemplo:
https://cursos.alura.com.br/forum/topico-pega-saldo-nao-compila-154446

**Comment by designernatan** [comment]
@Xaponeis valeu pelo aviso!

aqui está carregando normal 🤔

talvez algo momentâneo na plataforma? Se puder pode enviar aqui esses outros posts?

abcs!

**Comment by Xaponeis** [comment]
Realmente, agora está funcionando =). Ficou acho q mais de um dia sem entrar. O que acontecia é que a página truncava no primeiro parênteses após meu nome (onde ficam as xps). Aconteceu umas 4 vezes eu acho.

Lembro q me desloguei, acho q tentei em aba anônima tb mas não funcionava. Se acontecer denovo dou to que.

Não consegui encontrar os posts q aconteceram, devem ter arrumado tb.

**Comment by designernatan** [comment]
o problema aparentemente foi resolvido, se aparecer de novo pode comentar aqui :)

abcs!
