### ISSUE TITLE
Bug certificado formação concluída com 2/6 cursos completos

### ISSUE THREAD

**Issue by Xaponeis** [caelum/alura-funcionalidades#453]
Certificado da formação de Vue está aparecendo como concluída pra mim apesar de ter feito apenas 2/6 dos cursos. Os outros estão corretos.

https://cursos.alura.com.br/user/rodrigodiniz0/degree-vuejs-128975/certificate

**Comment by designernatan** [comment]
opa esse parece bug mesmo

vamos dar uma olhada e depois retorno aqui

**Comment by designernatan** [comment]
@Xaponeis 

Depois de analisar aqui identificamos que foi um problema na publicação da formação!

A formação foi atualizada no dia 11/03/2021 e acabamos deixando-a pública quando ela só tinha 2 cursos, então se vc caiu no caso de já ter feito esse dois cursos automaticamente teve o certificado gerado, mesmo depois da gente adicionar os cursos restantes

se fizer sentido, dá um ping no contato@alura.com.br contando sobre seu caso, tudo bem? Pode mandar o link dessa issue pra nao ter q explicar tudo novamente!
