### ISSUE TITLE
Destaque plano de estudos

### ISSUE THREAD

**Issue by tidrums1709** [caelum/alura-funcionalidades#454]
Hoje é possível selecionar qual formação deve aparecer como destaque.
Seria bacana que essa funcionalidade fosse para formação e plano de estudos.

Hoje estou realizando um plano de 67 cursos, e sempre tenho que entrar na lista de formações e estudos para acompanhar.

![image](https://user-images.githubusercontent.com/71182522/116913728-3569f700-ac20-11eb-9215-07abe9e946b2.png)

**Comment by designernatan** [comment]
@tidrums1709 valeu pela sugestao!

faz sentido mesmo, vamos dar uma investigada e se fizermos retorno aqui no futuro

abracao!

**Comment by designernatan** [comment]
fechando a issue mas pode comentar mesmo com ela fechada :)

está no forno para um futuro próximo termos essa opção de destacar um PDE

**Comment by designernatan** [comment]
@tidrums1709 foi pro ar!

daqui uns dias comenta aqui o que tem achado?

abcs!

**Comment by tidrums1709** [comment]
Agora sim. Show de bola. Parabéns pessoal.
