### ISSUE TITLE
site com perfil escuro

### ISSUE THREAD

**Issue by wagnervivianii** [caelum/alura-funcionalidades#455]
Olá.

Gostaria de sugerir um modo escuro para o site

**Comment by laisgalvaos** [comment]
Olá @wagnervivianii, agradecemos a sugestão.
Essa questão já foi levantada algumas vezes por aqui e estamos avaliando.
Por hora você pode verificar essa sugestão [https://github.com/caelum/alura-funcionalidades/issues/275](aqui)

Abç

**Comment by laisgalvaos** [comment]
Olá @wagnervivianii, obrigada pela sugestão!
Essa sugestão já foi levantada algumas vezes por aqui e está sendo avaliada com carinho!
Por hora, dê uma olhada nessa discussão [aqui](https://github.com/caelum/alura-funcionalidades/issues/156#issuecomment-632410492), tem uma sugestão de como aplicar o darkmode enquanto o oficial não sai =)

Abrç

**Comment by designernatan** [comment]
pessoal, fechando a issue mas podem comentar mesmo com ela fechada :)

btw, ótimo workaround que puxaram com a extensão do chrome
