### ISSUE TITLE
Bootcamps

### ISSUE THREAD

**Issue by kakarotocad** [caelum/alura-funcionalidades#456]
Faço devenvolvimento de SOftware no Canadá há 2 anos. Estou formando agora e os Cursos da Alura me ajudaram mto devido a barreira da língua as vezes deixarem mtos GAPS entre a explicaçao do professor em Inglês de como ou o que deve ser feito. Porém o que sinto falta nos cursos da Alura as vezes são uma conexão entre todos os conteúdos. POr exemplo estou fazendo agora os cursos de React da Alura. O conteúdo é bacana e os exemplos tbm, mas sinto falta do que fazer com aquele conteúdo. Sendo mais específico (https://cursos.alura.com.br/course/react-function-components) ao terminar esse curso fiquei com as seguintes perguntas, como posso manipular esses dados agora? Como eu poderia aramzaenar os mesmos no Browser? como armazenar os mesmos em um BD? e se esse BD estivesse em Cloud, como eu faria pra isso acontecer? após isso como eu faria pra poder colocar esse formulário no ar pra qqr pessoa preenchê-lo? Ou seja, acho que deu pra entender meu ponto, porque nao criar BootCamps dos cursos mais procurados onde vcs peguem um projeto do 0 (html e CSS e passe por todas as etapas até a publicaçao do mesmo?). O site de vcs e o conteúdo já é mto bom... mas as vezes conectar tudo é meio complicado pra quem está começando e acredito eu que Bootcamps seria algo que vcs estariam levando a ALURA a um novo patamar onde vcs preparariam ainda melhor os profissionais pra já entrarem no mercado de trabalho sabendo tudo que ele precsa pra estar atuando naquela determinada formaçao. Minhas sugestões para os primeiros Bootcamps: React, Angular, Swift e Kotlin.... 

São apensa sugestões, o que eu mais queria é que vcs enxergassem o potencial da minha idéia e colocassem pra funcionar do jeito ALURA de fazer bem as coisas.

**Comment by designernatan** [comment]
@kakarotocad valeu pela sugestao e pelo tempo em escrever seus pontos

alguns pontos:

1. os challenges na alura acredito que vão matar esse gap  que você mencionou sobre conteúdo, bem focado em prática e portfolio, da uma olhada [nesta live que rolou ontem sobre os Alura Challenges](https://www.youtube.com/watch?v=V0vxjhBhAWg)
2. fica de olho nas nossas redes que sempre divulgamos os bootcamps lá, como o último foi de react acho que vai ter um tempinho pra ele voltar ainda

dá uma olhada nos challenges depois e me fala o que você achou?

abcs!

**Comment by kakarotocad** [comment]
@designernatan obrigado pelo feedback.... Sabaria me informar se o Bootcamp de react que teve ainda esta disponível para acesso? Se sim teria como vc me enviar o Link, estou imergindo em React e todo material que eu conseguir vai me ajudar mto....

**Comment by designernatan** [comment]
@kakarotocad imagina!

putz pior que não sergio, é um produto a parte também (fora alura) e não sabemos dos próximos ainda :(

sei que o de data science está com as matrículas abertas até semana q vem:
https://www.alura.com.br/bootcamp/data-science-aplicada/matriculas-abertas

abcs!

**Comment by designernatan** [comment]
sergio, fechando a issue mas pode comentar posteriormente mesmo com ela fechada 

qualquer novidade atualizo aqui

chegou a dar uma olhada nos challenges @kakarotocad ? O que achou?

abcs!
