### ISSUE TITLE
Modo reprodução 'apenas vídeos' nas atividades de um curso

### ISSUE THREAD

**Issue by diCaminha** [caelum/alura-funcionalidades#457]
Seria interessante se existisse uma funcionalidade de que pudéssemos configurar um modo reprodução de um curso para que 
execute apenas os vídeos daquele curso (dando skip nas atividades de exercícios e explicações de texto). 

Essa feature seria para um cenário em que eu já tenha respondido as atividades e quero apenas ver em modo reprodução de aulas. Ou no caso do aluno não estar interessado naquele momento de responder à exercícios.

**Comment by laisgalvaos** [comment]
Olá @diCaminha !
Já é possível fazer isso dentro do ambiente de aulas. Abrindo um vídeo qualquer do curso, você ativa o modo de reprodução automático e seleciona apenas os vídeos (ver imagem do print) Isso fará com apenas os vídeos sejam mostrados em sequência e essa opção ficará gravada ao longo do curso. Você pode alterar ou desativar quando quiser usando o mesmo caminho.
![image](https://user-images.githubusercontent.com/62618660/117461095-939a2100-af23-11eb-923b-592f8246b952.png)

Espero ter ajudado.
Abrç

**Comment by bigois** [comment]
Como ativa esse "ambiente aula"?

**Comment by laisgalvaos** [comment]
Olá @guilhermebigois , eu me refiro àquela tela quando você abre um curso para fazer. 
Chamei de ambiente aula, mas acho que acabei confundindo. Mas é na tela de assistir aula, como essa do print.
Se ainda tiver dúvidas, avise!

Abrç


![image](https://user-images.githubusercontent.com/62618660/118526315-7e3ca800-b716-11eb-8769-f84c2c0e9a4d.png)

**Comment by bigois** [comment]
Tem algum navegador específico para aparecer essa opção?

Estou usando a versão do Chrome porém essa opção não aparece pra mim:
![image](https://user-images.githubusercontent.com/22408258/118528051-47679180-b718-11eb-9ede-b3a67d90557d.png)
![image](https://user-images.githubusercontent.com/22408258/118528044-46366480-b718-11eb-9179-985e36f9ea71.png)

**Comment by laisgalvaos** [comment]
@guilhermebigois hmm, acho que você deve ser aluno de empresa, não?
por enquanto essa funcionalidade está habilitada apenas para pessoa física, alunos e alunas de empresas não possuem acesso a essa feature
caso isso mude no futuro, voltamos te avisar!

**Comment by bigois** [comment]
Sou sim, é plano corporativo.
Mas mesmo assim, obrigadão!

**Comment by designernatan** [comment]
pessoal, fechando a issue mas podem comentar depois mesmo com ela fechada :)

**Comment by JonatasAmaral** [comment]
Existe alguma razão especifica para essa feature não estar disponível para planos de empresas?

O autoplay funciona no app (apenas nas videoaulas), porem é muito mais cômodo usar o computador com tela maior, podendo acompanhar o código/resulta, etc.

Alguma previsão para a adição disto?

**Comment by designernatan** [comment]
jonatas, é mais um direcionamento da maioria das empresas do que nosso, por hora só app mesmo :/

**Comment by bigois** [comment]
@designernatan, mas se o recurso está disponível no player de pessoa física, porque no corporativo não existe?

Não entendi a parte do direcionamento das empresas... A maioria das empresas disse para tirar o recurso de apenas vídeos e vocês removeram?

**Comment by designernatan** [comment]
isso guilherme

qualquer coisa vale pingar direto a gestão da sua empresa para estudarem alguma forma tbm

**Comment by JonatasAmaral** [comment]
Olá @designernatan, obrigado por responder tão prontamente

Isso é uma configuração global da Alura em si, onde **todas** as contas de empresas não tem acesso à essa feature, independente do posicionamento individual de cada uma.
Ou trata-se de uma configuração que cada empresa tem controle sobre como isso para sua contas?

**Comment by designernatan** [comment]
oi jonatas, é global (confirmei aqui internamente)
