### ISSUE TITLE
Usabilidade da plataforma de exibição dos cursos

### ISSUE THREAD

**Issue by WAGNER-DS** [caelum/alura-funcionalidades#458]
Olá, sou usuário da plataforma alura e recomendo as funcionalidades abaixo:

1) Criar uma barra de rolagem na listas de vídeos que fica no menu lateral. 

2) Ter um botão para voltar ao dashboard de cursos. Pois quando acessamos um curso ele não abre numa página nova. Como geralmente assistimos vários vídeos sequenciais, se simplesmente voltar não vou acessar o dashboard, terei que ir no browser digitar o endereço ou clicar no ícones de meus favoritos.

Fiquem a vontade para tirarem dúvidas.

Ats
 
Wagner Mota

**Comment by itrio** [comment]
Na página de aulas do curso há um pequeno botão com a logo da Alura no rodapé do menu lateral com um link para o dashboard. Concordo com você que o botão é tão discreto que a gente demora a descobrir que ele existe.

**Comment by designernatan** [comment]
oi pessoal, obrigado pelas sugestões

queremos melhorar a tela de aula num futuro e esse ponto sobre poder voltar pra dashboard precisará ficar mais claro mesmo

sobre o scrollbar no sidebar consideraremos também

abcs!

**Comment by designernatan** [comment]
wagner, fechando a issue mas pode comentar mesmo com ela fechada :)
