### ISSUE TITLE
Plano de Estudo na deashboard.

### ISSUE THREAD

**Issue by alexmartinsgit** [caelum/alura-funcionalidades#459]
Exibir plano de estudo criado pelo usuário no deashbord por padrão.

1. Criei um plano de estudo e ele não apareceu no meu Dashboard de forma automática. 
2. Depois de muito procurar, percebi que tenho que "curtir" meu próprio plano de estudo para ele apareça na minha deashboard. Vale ressaltar que ele não aparece como meu plano de estudo e sim como um plano de estudo que sigo, isso é estranho. 
3. Sei que há um menu "meus planos de estudo", mas acredito que a deashboard é o local adequado para organizar todas as atividades dos alunos.
4. Além disso, a mensagem "Nenhuma Formação ou Plano de Estudos favorito... ainda..." continua de maneira indefinida. Não encontro onde dizer que um dado plano de estudo é meu favorito, acredito que esse controle está faltando. A não ser que ao pedir para que o plano de estudo apareça na deashboard automaticamente ele seja considerado favorito, nesse caso o erro continua.

Sem mais.
[]s

**Comment by laisgalvaos** [comment]
Olá @alexmartinsgit , tudo bem? Ótima sugestão! 
Essa questão que você levantou já foi mapeada por aqui e está em análise.
Quando tivermos novidades sobre isso voltamos para te contar.

**Comment by designernatan** [comment]
pessoal, fechando a issue mas podem comentar mesmo com ela fechada :)

inclusive um desses pontos será resolvido quando for possível colocar um PDE em destaque, [mais infos aqui](https://github.com/caelum/alura-funcionalidades/issues/454)
