### ISSUE TITLE
Reproduzir Vídeo Automaticamente

### ISSUE THREAD

**Issue by JulianaCristina** [caelum/alura-funcionalidades#46]
Ao terminar um vídeo, seria interessante que ele prosseguisse a reprodução, atualmente  e necessário sair do modo tela cheia e clicar em um botão para o próximo vídeo, automatizar essa tarefa seria interessante.

**Comment by vfbohn** [comment]
Não concordo 100% com essa ideia... seria fácil de burlar e conseguir certificações sem o minimo de esforço.

O que acredito ser válido é fazer isso com 3 aulas seguidas, no máximo... fazer algum sistema semelhante ao YouTube e Netflix para quando se fica muito tempo sem movimentar o cursor.

**Comment by johnrj** [comment]
> Não concordo 100% com essa ideia... seria fácil de burlar e conseguir certificações sem o minimo de esforço.
> 
> O que acredito ser válido é fazer isso com 3 aulas seguidas, no máximo... fazer algum sistema semelhante ao YouTube e Netflix para quando se fica muito tempo sem movimentar o cursor.

Bom, mas aí é problema de quem está "fazendo" o curso, não? Entretanto, para que está estudando de verdade, para de ter que ficar clicando no play toda vez, melhorando o flow da atividade. E como os cursos já têm pontos de parada definidos, para responder perguntas, etc, acho que é uma boa solução.

**Comment by Heitorcanolla** [comment]
@JulianaCristina Agradecemos a sugestão, podemos verificar com a nossa equipe de desenvolvimento a viabilidade de implementar essa melhoria na plataforma. Uma dúvida, quanto a falta dessa funcionalidade te incomoda, de 0 a 10? Além ausência da reprodução automática, existe algum problema que identificou quando estava estudando?

**Comment by JulianaCristina** [comment]
@Heitorcanolla, 8, fora isso, nenhum problema.

**Comment by KingNinhoCode** [comment]
Pode ser feito um meio termo entre todas essas questões, que tal adicionar um botão de "proxima aula" que apareça no final de um video em tela cheia? como um dos avisos de anuncio do youtube, mas que sirva para algo.
Desse jeito não teria necessidade de sair do modo de tela cheia, alem disso caso o botão tivesse a propriedade focus (ou seja la como se programaria) poderia ser ativado com o teclado e não apenas o mouse.
;)

**Comment by designernatan** [comment]
a possibilidade de ver um curso muito passivamente, do ponto de vista de real aprendizado, não seria um problema aqui? 

se a pessoa quiser ela faz isso de qualquer forma mesmo em uma aula presencial em uma graduação, mas acho a preocupação do @vfbohn interessante

**Comment by sergioduartedba** [comment]
Só vejo vantagens para o aluno na inclusão dessa funcionalidade, como poder espelhar o curso para uma TV e assistir o conteúdo de várias aulas na sequência, sem preocupar de ficar clicando no play sempre que termina um vídeo de 10, 15 minutos. Poderia ser criada uma opção, onde o aluno escolhe se quer ou não a reprodução automática

**Comment by ooncyber** [comment]
E então? Descartaram essa sugestão? Acredito que seria muito útil. Para quem possui dois monitores é horrível ter que remover do fullscreen, achar a próxima videoaula no meio dos exercícios, reproduzir e voltar para o fullscreen.

**Comment by designernatan** [comment]
@ooncyber não descartamos **nenhuma** sugestão

quando pegarmos o fluxo de estudo dentro da tela de aula para melhorarmos um auto-play estará na pauta

valeu pelo relato sobre estudar com 2 monitores!

**Comment by IcaroBorges** [comment]
Concordo plenamente com os comentários dizendo que é problema do aluno se ele vai realmente estudar ou não com essa funcionalidade. De nada vale o certificado se a pessoa não conseguir por em prática os conhecimentos passados no curso. 

Agora com relação ao comentário do @designernatan sobre assistir um curso muito passivamente. Natan acho que isso pode até ser um problema, mas também cai na questão da consciência e responsabilidade do Aluno.  

Agora um visão minha é que eu sinto mais falta dessa funcionalidade em cursos onde eu já conclui. As vezes eu apenas quero revisar o curso assistindo os vídeos na velocidade x2.0, e ai eu realmente acho um saco ter que ficar saindo da tela cheia, pra mudar de vídeo. Em primeira instância, poderiam adicionar essa funcionalidade em cursos já concluídos pelo aluno.

**Comment by BrunnaMaiaradaSilva** [comment]
Eu acho um problema bem incomodo esse, não ter autoplay ou um botão de next no próprio player quebra o fluxo de estudo, não é horrível, mas essa feature seria realmente melhor com esse botão.

**Comment by kleversonsc** [comment]
Também sinto muito falta de um _autoplay_ ao menos entre vídeos seguidos. Uma funcionalidade que poderiam acrescentar a plataforma e que acho que casaria bem com o **Plano de Estudos**, seria a possibilidade de criar _playlists_. Cada curso já poderia, por padrão, disponibilizar uma _playlist_ dos vídeos do curso. Além disso, o estudante poderia montar sua própria _playlist_ contendo vídeos de cursos diversos, potencializando o aprendizado e a integração entre as áreas.

**Comment by jgomes-dev** [comment]
Sinto muita falta do auto play, ainda mais no curso de bootstrap 4, os vídeos são de 5 minutos, já conheço sobre bootstrap 3 e estou assistindo a esse curso pra me atualizar das funcionalidades que lançaram no 4, e sério: cada vídeo da aula tem 5 minutos (sem desmerecer o conteúdo que é ótimo, mas apenas criticando a falta do autoplay).

**Comment by sahslima** [comment]
Oi, pessoal! Tudo bem?

Passando para avisar que finalmente **lançamos a reprodução automática**! Haha

[Este artigo](https://www.alura.com.br/artigos/novidades-de-janeiro-na-alura) explica rapidamente a funcionalidade.

Depois compartilhem com a gente o que acharam. ;)

Um abraço!
