### ISSUE TITLE
Ajustar a dimensão/layout nos certificados.

### ISSUE THREAD

**Issue by brunoliveiradev** [caelum/alura-funcionalidades#460]
Olá,

Hoje ao gerar um certificado, o nome por ser extenso termina ocupando parte do certificado de forma que sobrepõe o que está escrito no certificado. 

Poderia ajustar o layout ou colocar um tamanho que fosse um pouquinho menor.

![print](https://user-images.githubusercontent.com/58921482/117517749-53fb2580-af73-11eb-82fe-580672467442.png)

**Comment by designernatan** [comment]
@BRUNOOLIVEIRA13 opa falha nossa aí

hoje deve entrar uma correção que diminui "um cadin" o nome

uma solução de contorno que você pode fazer enquanto não sobe: inspect element no nome, diminuir o font-size (deve estar 3 ou 2.7em) e colocar para salvar o pdf

obrigado pelo toque

abcs!

**Comment by designernatan** [comment]
corrigido!
