### ISSUE TITLE
Ranking de cursos e professores

### ISSUE THREAD

**Issue by itrio** [caelum/alura-funcionalidades#461]
Sugiro a criação de um ranking de cursos, onde se possa acessar uma tabela com todos os cursos da plataforma. 

Nessa tabela haveria a opção de filtrar os cursos de acordo com a categoria ou a formação às quais pertencem, bem como a opção de ordená-los pela avaliação, quantidade de alunos ou carga horária.

Essa funcionalidade poderia se estender inclusive aos professores, em uma tabela a parte, onde se pudesse filtrar por áreas de atuação e ordená-los de acordo com a avaliação, com a quantidade de cursos que lecionaram ou mesmo pela soma das horas/aula lecionadas.

**Comment by designernatan** [comment]
@itrio valeu pela sugestao!

o 'order by' vou ficar te devendo por hora, mas vc consegue acessar todos os cursos [aqui nessa listona de cursos](https://www.alura.com.br/cursos-online-tecnologia)

inclusive num futuro próximo teremos filtros na busca normal da plataforma

abcs!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
