### ISSUE TITLE
Certificados agrupados

### ISSUE THREAD

**Issue by WAGNER-DS** [caelum/alura-funcionalidades#462]
Bom dia,

Na tela de certificados agrupados temos dois pontos de melhoria:

1) A sequencia de cursos listados por formação não está seguindo a sequencia original;

2) Quando o curso está em mais de uma formação ele se repete. Isso é ruim pois dá uma falsa impressão de que mais cursos foram feitos.

![image](https://user-images.githubusercontent.com/67823891/117643495-d85dcc00-b15e-11eb-8893-e503d5a96f68.png)

**Comment by designernatan** [comment]
@WAGNER-DS valeu pela sugestao!

estamos vendo de melhorar essa tela num futuro próximo, principalmente essas formacoes que ainda nao estao completas e sao exibidas como se estivessem

abcs!

**Comment by designernatan** [comment]
@WAGNER-DS fizemos uma alteração no sistema do Certificado Completo

mudamos a regra em geral e agora é possível ocultar uma formação para poder gerar o pdf

me fala depois o que achou?

abcs
