### ISSUE TITLE
Possibilidade de fixar vídeo (ou acrescentar) Rolagem específica para a transcrição

### ISSUE THREAD

**Issue by masbemcapaz** [caelum/alura-funcionalidades#463]
Olá, gostaria de sugerir uma funcionalidade que permitisse ao usuário a possibilidade de fixar o vídeo no topo da página para que pudesse acompanhar a aula gravada enquanto efetua a rolagem do texto da transcrição individualmente na página. Isso permitiria ler os textos sem que precisasse abrir mão de acompanhar o vídeo.

Atualmente ao rolar a página, o vídeo acaba ficando oculto e impossibilitando o acompanhamento de ambas as mídias.
![image](https://user-images.githubusercontent.com/83979542/117712229-6f9c4100-b1aa-11eb-9395-f95c684b5b3e.png)

Na sugestão, teríamos algo assim....
![image](https://user-images.githubusercontent.com/83979542/117713471-159c7b00-b1ac-11eb-969f-314fd4511643.png)

Grato

**Comment by designernatan** [comment]
@masbemcapaz valeu pela sugestao!

temos planos para melhorar a tela de aula num futuro, por hora sem datas

uma coisa que você pode fazer hoje para resolver (em partes) isso: **ligar o modo PiP**, é aquele ali do lado direito das configurações no próprio player de vídeo

depois me fala quão útil fica isso para você nesse caso?

abcs!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)

@masbemcapaz chegou a testar o PIP?
