### ISSUE TITLE
XP de formação concluída não se aplica a cursos atualizados

### ISSUE THREAD

**Issue by gilbertoalbino** [caelum/alura-funcionalidades#464]
Como é natural, os cursos são atualizados conforme se faça realmente necessário.

Todavia, como é o caso da formação "Formação Java EE" disponivel no link https://cursos.alura.com.br/formacao-java-ee, é informado que alguns cursos (4 mais especificamente) estão desabilitados e possuem uma versão atualizada.

O problema é que não há uma relação com esses cursos atualizados e a formação e, por este motivo, o progresso não é registrado na formação, impedindo assim que os 2000XP sejam adquiridos pela "Formação Concluída".

Seria interessante se a plataforma pudesse recuperar esse progresso a fim de não prejudicar a pontuação pelo esforço do aluno.

Eu sugeriria, o seguinte:

Na listagem deve aparecer o curso "Desabilitado" e logo abaixo o curso "Atualizado", o que atualmente está assim:

**CURSO** `DESABILITADO`
Java e JPA: Persista seus objetos com a JPA2 e Hibernate - `100%`

Ficaria assim:

**CURSO** `DESABILITADO`
Java e JPA: Persista seus objetos com a JPA2 e Hibernate -` 0%`
`Nova Versão`: Curso de Persistência com JPA: Introdução ao Hibernate - `100%`

E para validar se a formação foi concluída, verificaria se de 1 curso desabilitado, quantos de N atualizados estão concluídos a fim de bonificar o aluno com os 2000XP caso ele opte pela versão atualizada.

Creio que uma tabela pivot resolveria o problema.

Me fiz entender?

**Comment by designernatan** [comment]
@gilbertoalbino valeu pelas sugestões!

sobre a listagem faz bastante sentido isso, aproximar o novo curso do card do antigo, que seja outro card ou link

sobre a gamefication e o sistema de pontuação, não está no nosso radar por hora, qualquer novidade dessa de outras frentes a gente divulga no [/artigos](https://www.alura.com.br/artigos/novidades-de-maio-uma-surpresa-te-aguarda)

abcs e bom fim de semana!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
