### ISSUE TITLE
Botão "Concluído/Lido" para artigos nas Formações

### ISSUE THREAD

**Issue by bigois** [caelum/alura-funcionalidades#465]
Recentemente notei que uma das Formações que estou fazendo está marcando como concluído (aquela medalha), mesmo que eu não tenha lido de verdade o artigo.

![image](https://user-images.githubusercontent.com/22408258/118407845-f775c580-b658-11eb-8366-f7523a358362.png)

Isso acontece porque no corpo de alguns artigos, existem links que levam para outros artigos, porém por vezes eu apenas cliquei, mas não li de verdade.

Ou então, quando eu clico para começar a ler um artigo e não termino de ler ele porque tive que fazer outra coisa. Ainda sim ele é exibido como concluído.

**Seria possível criar um botão nas formações para marcar como lido ou alguma funcionalidade que me desse poder de dizer que eu li o artigo?**

Com todos os artigos ficando como marcado, eu acabo me perdendo no que eu li ou no que não 😅

**Comment by designernatan** [comment]
@guilhermebigois valeu pela sugestão!

[o mauricio sugeriu algo em volta desse problema também,](https://github.com/caelum/alura-funcionalidades/issues/33) por hora sem planos para mudar num futuro próximo esse 'check' automático

para nao ficar te devendo tanto, uma sugestão minha que faço quando estudo:

1. abro uma janela (não aba) nova focada no estudo, e vou deixando abas de links e pesquisas abertos
2. conforme vou avançando e lendo o que separei para ler, vou fechando as abas
3. se parei de estudar e nao quero perder a aba salvo no [pocket](https://getpocket.com/my-list) para ler em outro momento

Em resumo, faço esse controle na minha janela de estudo

abracao! :)

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)

**Comment by designernatan** [comment]
@guilhermebigois chegou a testar o pocket ou mesmo o notion? O que tem achado?

**Comment by bigois** [comment]
@designernatan, dei uma avaliada nos dois, contudo achei uma solução um pouquinho mais simples.
Pra evitar de ficar marcado como lido, ao invés de clicar com o botão direito, eu clico com o esquerdo e abro em outra aba (ou então uso o _scroll_ do mouse).
