### ISSUE TITLE
Link para perfil dos professores na página da formação

### ISSUE THREAD

**Issue by itrio** [caelum/alura-funcionalidades#466]
Na página de uma formação (ex: https://cursos.alura.com.br/formacao-desenvolvedor-php) é possível ver quem são os professores dos cursos que a compõem, mas não há um link para os perfis deles. Para isso, é necessário clicar em algum dos cursos que compõem a formação e aí sim clicar no perfil do professor.

**Comment by designernatan** [comment]
@itrio opa valeu pela sugestao!

faz todo sentido isso!

vamos dar uma conversada aqui e qualquer novidade retorno aqui, ok?

abcs!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)

colocamos no backlog essa, eventualmente entrará no ar e avisamos aqui!
