### ISSUE TITLE
Trascrição do podcast

### ISSUE THREAD

**Issue by kikiwitchu** [caelum/alura-funcionalidades#467]
O podcast é requirido em alguns cursos e precisa ter transcrição como já existe dos vídeos. O material é bem interessante e acrescenta, mas não comtempla todos que estão seguindo o curso.

**Comment by designernatan** [comment]
@kikiwitchu valeu pela sugestao!

na plataforma consumimos as informações direto dos sites dos podcasts do grupo, se houver transcricao em algum momento por lá puxaremos também! Recentemente incluímos a descrição e o controle de velocidade entrou acho que no final do ano passado

abcs

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
