### ISSUE TITLE
Organização dos cursos na área "PLANO DE ESTUDO"

### ISSUE THREAD

**Issue by rodrigodiaslima1** [caelum/alura-funcionalidades#468]
Olá pessoal da Alura, como vão?

Eu uso bastante a tela do Plano de Estudo. 
Gosto de organizar meus cursos por lá. Então, por ordem de importância para mim, vou encaixando eles em sequencia. 

por ex.:
Cursos de Java
Cursos de Python
Cursos de SQL
e assim por diante ...

Minha sugestão é, nessa tela (Plano de estudos) existir a possibilidade de colorir cada tipo de curso com uma cor. Assim posso entrar e já olhar para um determinado bloco (com uma cor) e saber que ali estão meus cursos de Java, na outra cor meus curso de Python e assim por diante.

Então, seguindo o print que anexei aqui, eu poderia, por exemplo, deixar todos os cursos de java com sua caixa de seleção vermelha, ou então deixa-los dentro de uma caixa com tom avermelhado. Os de outro curso com outra cor e assim indo. Isso, eu acredito, iria não só melhorar no visual e organização como ia dar uma ideia "visual" para o aluno sobre onde ele está se focando mais ...

Agradeço a atenção de vocês
Um grande parabéns para a Alura de maneira geral

E bora estudar!!!

Vlw, abraços

![sugestão para alura 1](https://user-images.githubusercontent.com/28333740/119093113-a877b980-b9e5-11eb-9ab4-10248e5320d1.JPG)

**Comment by designernatan** [comment]
@rodrigodiaslima1 brigadao pela sugestao!

uma separação por módulos, como nas formações, faz todo sentido sim!

por hora sem planos num futuro próximo de avaliarmos, mas sem dúvida numa possível revamp do PDE iremos considerar fortemente isso tudo bem?

abracao e bons estudos!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
