### ISSUE TITLE
Plano de estudo público

### ISSUE THREAD

**Issue by Daianee** [caelum/alura-funcionalidades#469]
Olá, gostaria de sugerir na página de plano de estudo público,um campo de pesquisa para facilitar a busca dos usuários.
Muito obrigada!

**Comment by designernatan** [comment]
@Daianee valeu pela sugestao!

precisamos dar uma melhorada nessa página de PDEs públicos mesmo, mas ainda não temos datas :(

inclusive numa busca nessa página, implicaria os títulos fazerem sentido com o conteúdo, por ex: hoje eu posso criar um PDE chamado 'design', mas com conteúdo de programação

pensar numa busca nessa página estará na pauta quando a pegarmos para melhorá-la

**Comment by Daianee** [comment]
> @Daianee valeu pela sugestao!
> 
> precisamos dar uma melhorada nessa página de PDEs públicos mesmo, mas ainda não temos datas :(
> 
> inclusive numa busca nessa página, implicaria os títulos fazerem sentido com o conteúdo, por ex: hoje eu posso criar um PDE chamado 'design', mas com conteúdo de programação
> 
> pensar numa busca nessa página estará na pauta quando a pegarmos para melhorá-la
> 
> 
> 
> 
> 
> 

Entendi, muito obrigada! 😀

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)

**Comment by designernatan** [comment]
opa, essa issue fez aniversario mas colocamos no ar a busca :)

ela funciona tanto por nome do PDE quanto do nome do(a) autor(a), vamos ver se engaja antes de fazer algo mais parrudo como a busca padrão de conteúdos da plataforma
