### ISSUE TITLE
Abrir fórum em outra guia!

### ISSUE THREAD

**Issue by Trainconductormg** [caelum/alura-funcionalidades#47]
Não sei se é possível ou viável. Eu gosto de assistir as aulas e ao mesmo tempo acessar o fórum durante o vídeo. Seria possível ao clicar no ícone do fórum, abrir outra página ao invés de carregar na mesma? Seria interessante, pois não precisaria voltar toda hora para o vídeo, e achar onde estava antes de dar pausar.
Sei da funcionalidade da clicar com o botão direito pra abrir outra página.
Minha intenção é, além de tentar colaborar com algo novo, é já me familiarizando com a simplificar as programações.
E conhecer o GITHUB!
Obrigado.

**Comment by designernatan** [comment]
legal @Trainconductormg , obrigado pela sugestão!

identificamos outros(as) alunos(as) com essa mesma issue e por ser algo rápido e com bastante valor já entrou no backlog

sem datas, mas fica tranquilo que estamos em cima disso


abcs!

**Comment by designernatan** [comment]
@Trainconductormg time de produto alterou isso hoje

agora durante seus estudos, clicando em 'discutir no fórum', ele abre em outra aba!

**Comment by Trainconductormg** [comment]
Ficou ótimo.
