### ISSUE TITLE
Integrar dois perfis 

### ISSUE THREAD

**Issue by CostallatP** [caelum/alura-funcionalidades#470]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Olá, seria interessante poder unir dois perfis diferentes, por exemplo já tive um Alura anteriormente (anos atrás) mas agora a empresa que trabalho criou um novo perfil, sendo assim juntar os cursos já feitos com o novo perfil seria perfeito e imagino como seja perfeito para as pessoas que mudam de perfil constantemente.

**Comment by designernatan** [comment]
@CostallatP consegue pingar no atendimento@alura.com.br ?

aí o time de customer success tenta te ajudar com isso :)

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada
