### ISSUE TITLE
Opção para concluir temas que ja temos conhecimento

### ISSUE THREAD

**Issue by Ptkqueiroz** [caelum/alura-funcionalidades#471]
Por exemplo: Eu já conheço o básico do SQL SERVER, para que não precise eu assistir as primeiras aulas explicando o que é um select, update...  poderia ter uma opção, onde responderíamos umas questões chaves sobre as aulas, caso o aluno **acerte uma quantidade x**, aquela aula já seria marcada como concluída.
Assim não precisaríamos darmos play em todos os vídeos e avançaríamos mais rápido para outros temas mais avançados.

**Comment by designernatan** [comment]
@Ptkqueiroz valeu pela sugestao!

meio que uma prova de nivelamento de conhecimento certo? Gosto bastante principalmente para formações. Por hora não temos planos para um futuro próximo de projetarmos algo assim, mas anotei sua sugestão para discutirmos.

lembrando que você pode pular os vídeos mais introdutórios (ou mesmo cursos) para estudar e pegar conhecimento dos temas mais avançados

abracos!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
