### ISSUE TITLE
Nova funcionalidade - Índice de termos

### ISSUE THREAD

**Issue by thiagohcc** [caelum/alura-funcionalidades#472]
Estou começando o curso de UX e normalmente me deparo com termos comuns do meio que não sei o que significa.
Seria interessante ter um índice de termos e significados nos cursos.

**Comment by designernatan** [comment]
@dzno23 valeu pela sugestao e espero que esteja curtindo os cursos de UX

o(a) duda [sugeriu algo semelhante aqui](https://github.com/caelum/alura-funcionalidades/issues/38) ano passado

isso é mais relacionado ao conteúdo do curso em si do que uma funcionalidade de fato, uma coisa que faço é ir jogando no meu notion para pesquisar depois com calma, principalmente nos cursos de marketing que têm uma terminologia bem vasta

lembrando que você pode sempre usar o fórum para perguntar na comunidade da Alura algo, tudo bem?

abracao e bons estudos

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
