### ISSUE TITLE
Icone apagado

### ISSUE THREAD

**Issue by moabe-br-2019** [caelum/alura-funcionalidades#473]
O ícone de curso concluído é muito apagado, isso prejudica na hora de ver o que já foi feito
![alura](https://user-images.githubusercontent.com/54943821/119808917-f5aecc00-beba-11eb-98aa-127226e1e67e.jpg)

**Comment by tommacedo** [comment]
Concordo totalmente, seria melhor um destaque para isso. Ajudaria muito pra verificar quando acessamos formações principalmente.

**Comment by andradeisadora** [comment]
@moabe-br-2019 obrigada pela sugestão!

Dar mais destaque para o ícone de cursos concluídos faz sentido sim. No momento não estamos com planos para mexer nisso mas num futuro se mexermos nos ícones iremos considerar sua sugestão.

Abraço e bons estudos!

**Comment by marcuscf** [comment]
Não só o ícone, mas todo o texto da interface está muito apagado e fininho, às vezes parece que os links estão desabilitados e não podem ser clicados. Ou então o texto parece dizer "este não é o conteúdo principal da página, continue rolando que o principal vem depois" (e nunca vem, porque é tudo cinza).

Sugestão: texto preto mesmo, deixa o cinza só para coisas realmente secundárias e não-clicáveis.  
Ou pelo menos seguir o Web Content Accessibility Guidelines sobre contraste de texto (ferramentas de desenvolvimento do navegador já avisam isso ao clicar na cor, testei no Firefox).

**Comment by marcuscf** [comment]
![image](https://user-images.githubusercontent.com/18555709/122280128-3e0c4900-cebf-11eb-9515-49e1e528f88a.png)

Outro ícone apagado é o indicador de progresso no canto superior direito. Eu realmente achei que estivesse bugado até perceber que alguns quadradinhos são ligeiramente mais azulados e outros mais acinzentados.

O pessoal aí está com monitores com um contraste muito bom ou tem uma visão sensacional :-)

**Comment by designernatan** [comment]
@marcuscf o texto preto #000000 no branco #FFF pode ter problema inverso: contraste demais é ruim para algumas pessoas, comento sobre isso aqui no [curso de acessibilidade focada em design](https://cursos.alura.com.br/course/acessibilidade-web-design-inclusivos)

do gráfico de colméia, percebi agora que até o github deixa com contraste muito baixo (1:17 pra ser exato), mínimo de bordas e ícones deveria ser 3:1

começamos a usar ferramentas no próprio Figma para verificar contraste de cor para evitar isso, fica tranquilo pois queremos atacar **no mínimo** nível AA em tudo na plataforma

---

fechando a issue mas podem comentar, caso necessário, mesmo com ela fechada :)

**Comment by designernatan** [comment]
atualizando aqui:

mudamos do cinza-quase-nao-da-para-ver para o verde-usamos-como-sucesso-na-alura :)

![image](https://user-images.githubusercontent.com/5431347/124490961-1a834280-dd89-11eb-8204-e3ea26c2e4d0.png)
