### ISSUE TITLE
Pré-visualização na barra de rolagem dos vídeos.

### ISSUE THREAD

**Issue by araujochavesjr** [caelum/alura-funcionalidades#474]
Gostaria que na rolagem de vídeo tivesse um preview, a exemplo dos vídeos do YouTube, isso melhoraria o aprendizado, pois muitas vezes queremos voltar a algum ponto do vídeo para esclarecer algum ponto na explicação do instrutor ou na visualização do código que está sendo feito por ele e temos que ficar adivinhando em qual ponto foi. Por outro lado, entendo também que depende da plataforma que vocês hospedam os vídeos, talvez não disponham dessa funcionalidade.

Acho que dá para entender melhor pelo arquivo que envio anexo.

![2021-05-31 (2)](https://user-images.githubusercontent.com/40725012/120143785-2cd0f600-c1b7-11eb-87f0-793dd21881f8.png)

**Comment by designernatan** [comment]
@araujochavesjr valeu pela sugestao!

de fato seria algo para se implementar do zero, eu mesmo uso bastante isso no youtube, já tínhamos anotado aqui para discutir se mexermos no player

ano passado fizemos várias melhorias como pip, modo teatro, atalhos (esse acho q foi 2019), ideia é melhorá-lo cada vez mais

abracao!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
