### ISSUE TITLE
Uma nova forma mais rápida de visualizar cursos concluídos para consultar informacões antigas do conteúdo

### ISSUE THREAD

**Issue by igormelao** [caelum/alura-funcionalidades#475]
Olá, tudo bem? Espero que sim.

Então, normalmente preciso voltar a um curso que já concluí para realizar alguma consulta técnica ou revisar alguns conhecimentos adquiridos há um tempo atrás que não me lembro mais.

Para isso, atualmente, preciso:

       -  Clicar no menu do usuário 
       -  Perfil e Certificados
       - Ordernar pela data de finalizacão para buscar os últimos curso que concluí (normalmente são esses que volto para consultar alguma documentação)
       - Depois preciso procurar pelo nome ou procurar um por um mesmo.
       
Minha sugestão seria que no meu Dashboard tivesse uma **Seção Últimos Cursos Finalizados** com um rank dos 5 e um  link que me levasse a uma página com todos meus cursos concluídos e por default ordernado por ordem decrescente na data de finalização.

Muito parecido com o que já existe para **Meus cursos em Andamentos**, **Novidades** e etc.

Espero que minha sugestão contribua para a comunidade e ajude meus outros colegas de estudo.

Cumprimentos,
Igor Melão

**Comment by designernatan** [comment]
@igormelao valeu pela sugestao!

hmm pq rank dos 5 especificamente? Qual seria o critério?

em ['meus cursos'](https://cursos.alura.com.br/courses/mine) há uma seção de 'cursos finalizados'

clicando em um deles, você cai na página do curso em questão, isso resolveria?

abração!

**Comment by designernatan** [comment]
@igormelao depois consegue ver essas minhas dúvidas?

fechando a issue mas pode comentar mesmo com ela fechada :)
