### ISSUE TITLE
Conclusão de tarefas para surdos.

### ISSUE THREAD

**Issue by xpcosmos** [caelum/alura-funcionalidades#476]
Prezados,

Atualmente inclusão é essencial principalmente no que diz respeito educação. Dentro dos cursos, você tem transcrições, porém, a aula só é dada com concluída depois que clicamos para a reprodução do vídeo.
Minha sugestão é que em alguma área, a plataforma do Alura pergunte se o aluno é surdo, caso seja, a aula em vídeo não aparecerá para ele, somente a transcrição. Quando o aluno rolar até o final da página, a atividade é dada como concluída.

if(aluno == fimDaPagina);{
      tarefaConcluida = true
}else{
     tarefaConcluida = false
}

**Comment by designernatan** [comment]
@xpcosmos valeu pela sugestao

vamos dar uma investigada em como podemos resolver esse ponto sobre pessoas que estudam sem os vídeos, estamos estudando de como melhorar a página do perfil e vamos discutir isso

talvez um botão de 'concluir atividade' no fim da transcrição resolveria e parece ser tranquilo de implementar

quão sentido algo assim faz no seu contexto?

abcs!

**Comment by designernatan** [comment]
@xpcosmos fechando a issue mas pode me responder mesmo com ela fechada :)
