### ISSUE TITLE
Legendas

### ISSUE THREAD

**Issue by Fernand0Devel0per** [caelum/alura-funcionalidades#477]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.
Legendas nos videos.
Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.
Os videos de vocês não tem opção de legenda, para uma pessoa com deficiencia auditiva ia ser excelente.

**Comment by designernatan** [comment]
@Fernand0Devel0per valeu pela sugestao!

Esse é um ponto de melhoria importante na nossa plataforma e estamos atentos e trabalhando nisso. Estamos vendo a melhor maneira de organizar e realizar esse trabalho, que não é trivial, dado o volume de cursos e minutos de vídeos existentes e não fazer de todos provavelmente entregue uma experiência ruim para os alunos e alunos com e sem essa necessidade

Assim que tivermos novidades, avisaremos ok?

abcs!

**Comment by Flamilani** [comment]
Opa pessoal! Eu também gostaria de ter esse recurso de legendas nos vídeos para facilitar acompanhamento da explicação dos instrutores o que estiver explicando cada passo a passo. Pois eu também sou pessoa com deficiência auditiva. Entendo que tive dito que estão vendo a possibilidade de organizar. Obrigado pela atenção.

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
