### ISSUE TITLE
As vezes, ao clicar numa alternativa dos desafios, não computa nem certo nem errado

### ISSUE THREAD

**Issue by Ramacciotti** [caelum/alura-funcionalidades#478]
No meio do curso temos desafios onde escolhemos uma ou mais alternativas. 

Entretanto notei algumas vezes que, ao selecionar uma alternativa, a mesma ficava 'apagada'. **Esta alternativa selecionada não fica nem verde nem vermelha, apenas com uma cor apagada.**

Mesmo recarregando a página e escolhendo aquela alternativa novamente, o bug procede. 

A única forma que encontrei de resolver foi selecionar uma alternativa errada. Ai automaticamente a alternativa que selecionei errada fica vermelha e a que era a certa fica verde.

**Comment by designernatan** [comment]
@Ramacciotti hmmm isso pode ser bug

me manda o link de uma dessas?
Esse comportamento (diminuir a opacidade) é padrão nos exercícios onde precisamos selecionar mais de uma alternativa

abcs!

**Comment by designernatan** [comment]
@Ramacciotti fechando a issue mas pode me responder mesmo com ela fechada :)
