### ISSUE TITLE
Gerador de CV com integração ao linkedin

### ISSUE THREAD

**Issue by dthiago** [caelum/alura-funcionalidades#479]
Um gerador de CV Alura com os cursos finalizados, mas atendendo as necessidades do aluno. Nas necessidades, entende-se, a escolha de determinados cursos irem para o cv ou não - assim, os currículos poderão ser mais efetivos.

Estilos poderão ser inseridos também , como: CV ao estilo storytelling, formais e assim vai...

As informações obtidas de fonte confiável como linkedin completarão o cv.

**Comment by designernatan** [comment]
@dthiago valeu pela sugestao!

está na nossa mira poder escolher quais formações entram no certificado completo e quais nao entram, mas mais focado no visual 

hoje o mais próximo disso que temos é os botões 'adicionar ao linkedin', já adianta um pouco o preenchimento das informações e fica tudo centralizado no linkedin para poder customizar até mesmo com cursos de outras escolas, experiencias profissionais, etc

**Comment by vitaoTM** [comment]
Com relação aos certificados e a integração no linkedIn reparei que parece haver um bug, onde (quando estou loggado na Alura) eu posso adicionar o certificado de outro usuário ao meu linkedIn, o que nao não acontece quando não estou loggado. Imagino que isso deveria ser individualizado. Acredito que não seja um problema muito sério... pois os certificados ainda ficam no nome do usuário original, mas sim uma questão de ética e segurança mesmo

Peguei um usuário aleatório no ranking mensal enquanto logado na minha conta Alura:
![Logged in](https://user-images.githubusercontent.com/60250422/122111981-b955f800-cdf6-11eb-9b67-b5e2f1e72859.PNG)

O mesmo usuario enquanto não estou loggado na Alura
![not logged](https://user-images.githubusercontent.com/60250422/122112342-1782db00-cdf7-11eb-9c15-d35534c97d6d.PNG)

Outro usuário aleatório no ranking geral
![other user](https://user-images.githubusercontent.com/60250422/122112902-c1626780-cdf7-11eb-9cbf-c52b10a5e1a5.PNG)

Perceba que nos dois usuários vejo o link de integração com o linkedIn.

**Comment by designernatan** [comment]
@vitaoTM nao vejo como um problema de segurança, pois além dos perfis serem públicos o nome no certificado (e o link de validação) batem com o nome da pessoa certinho :)

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
