### ISSUE TITLE
Função apenas vídeos

### ISSUE THREAD

**Issue by ooncyber** [caelum/alura-funcionalidades#48]
Olá, em todos os cursos eu estou barrando em um obstáculo, e acredito que não seja apenas eu: estou empolgado e acompanhando 100% do raciocínio do instrutor, e quando acaba a videoaula, chega exercícios do começo do capitulo. É decepcionante!
Gostaria de sugerir o seguinte: Uma opção que, ao acabar o vídeo, espere 3 segundos e já começasse o próximo vídeo.

**Comment by designernatan** [comment]
oi @ooncyber 

[algo semelhante está sendo discutido aqui nessa outra issue](https://github.com/caelum/alura-funcionalidades/issues/46), pode comentar o que voce acha da discussão por lá por favor?

valeu pela sugestao!
