### ISSUE TITLE
Integração ao linkedin

### ISSUE THREAD

**Issue by dthiago** [caelum/alura-funcionalidades#480]
Eu vi integração do avatar (O gravatar é algo beeem ultrapassado e limitante.
) com o  Github - o que faz todo sentido para a Alura com a sua essência dev. No entanto, todos estão empreendendo, seja com aquisição de cursos aprendendo sobre empreendedorismos e suas soft e hard skills.

A integração do linkedin não apenas poderá ocorrer com a obtenção do avatar. Eu sugeri o CV Alura https://github.com/caelum/alura-funcionalidades/issues/479 - desta forma, fica algo mais completo.

**Comment by designernatan** [comment]
@dthiago 

boa! O github foi um foco nosso nesses tempos mesmo

tínhamos algumas considerações com relação a engenharia mas conseguimos resolve-los, agora além do github e gravatar temos a opção do ulpload "normal"

sobre a outra issue te respondi por lá td bem?

abracao!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
