### ISSUE TITLE
Pesquisa Plano de Estudos Publicos

### ISSUE THREAD

**Issue by FlvAvsGit** [caelum/alura-funcionalidades#481]
Na seção Plano de Estudos Públicos, Incluir funcionalidade de Pesquisa de Planos de Estudos Públicos por Autor e/ou Nome do Plano de estudo.

**Comment by andradeisadora** [comment]
@FlvAvsGit obrigada pela sugestão!

Tem uma [issue semelhante aqui](https://github.com/caelum/alura-funcionalidades/issues/469) falando sobre a pesquisa dos planos de estudos públicos. Da uma olhadinha lá que explicamos sobre o assunto :)

Abraço e bons estudos

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)

**Comment by designernatan** [comment]
opa, essa issue fez aniversario mas colocamos no ar a busca :)

ela funciona tanto por nome do PDE quanto do nome do(a) autor(a), vamos ver se engaja antes de fazer algo mais parrudo como a busca padrão de conteúdos da plataforma
