### ISSUE TITLE
Pesquisar cursos por carga horaria.

### ISSUE THREAD

**Issue by geaprado** [caelum/alura-funcionalidades#482]
Gostaria de pesquisar cursos filtrando por carga horaria.

**Comment by designernatan** [comment]
@geaprado valeu pela sugestao!

estamos de olho para mexer na busca ha um tempo, futuro médio prazo teremos novidades

enquanto isso, qual o ponto de filtrar pela carga horária que seria interessante para você?

abracao!

**Comment by geaprado** [comment]
Seria legal filtrar a carga horária das formações e cursos dentro das
formações.

Em sex, 11 de jun de 2021 16:47, Natan Souza ***@***.***>
escreveu:

**Comment by designernatan** [comment]
@geaprado bacana! Qual ponto especificamente que esse filtro resolveria no seu cotidiano?

pode me contextualizar com um ou dois exemplos?

abracos

**Comment by geaprado** [comment]
Então, as vezes não tenho muito tempo pra engatar uma formação ou curso
livre e facilitaria muito se eu pudesse entrar na plataforma e dentro das
áreas, por exemplo programação/desenvolvimento e pudesse buscar todos os
cursos, e dentro de todos os cursos filtrar por carga horária.

Tem muito curso na plataforma e às vezes tenho pouco tempo disponível e
gostaria de fazer um curso dentro do tempo que tenho e conseguir inciar e
concluir nesse periodo.

Por exemplo, fiz a busca por javascript e me retornou uma infinidade de
cursos, seria legal ter uma barra de filtragem por data de atualização,
carga horaria, professor, nivel(Basico, intermediario, avançado), do jeito
que está preciso entrar em curso por curso pra ver qual é o que mais
preciso, no caso se tivesse um filtro por carga horaria eu poderia começar
fazendo um curso mais rápido pra pegar um conceito, depois pegaria um curso
mais intermediario...

[image: image.png]


Veja no caso da udemy, fiz uma busca por javascript e veja quantas opções
de filtro eu tenho:

[image: image.png]

Acho que é isso, qq coisa é só chamar.

Abs.

Em seg., 14 de jun. de 2021 às 11:59, Natan Souza ***@***.***>
escreveu:

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)

geaprado muito obrigado pelo tempo que vc dedicou em passar essas infos pra gente
