### ISSUE TITLE
Certificação Fomal para os cursos da Alura ""Formação"

### ISSUE THREAD

**Issue by marcello222** [caelum/alura-funcionalidades#483]
Gostaria de solicitar nos Certificados de "Formação" dos cursos da Alura. o Certificado Formal com as matérias abordadas no diploma. Conforme tem a opção em cursos avulsos. Assim o diploma sairia com o descritivo do que foi estudado em Formaçao. 

 Exemplo:

FORMAÇÃO SPRING FRAMEWORK 
Ao invés de ter apenas   a carga horaria de 130 horas la conforme o diploma normal, colocar tambem o diploma Certificação Formal com as matérias que foram estudadas.

**Comment by designernatan** [comment]
@marcello222 valeu pela sugestao!

acabamos de alterar alguns pontos no certificado (uma alteracao inclusive está no forno)

para nao ficar te devendo, manda um email no atendimento@alura.com.br com seu user e o certificado que você precisa em detalhes? A gente te ajuda por ali, ok?

abração

**Comment by marcello222** [comment]
Obrigado!
Enviei a solicitação por email.
