### ISSUE TITLE
Opção de voltar ao Drashboard

### ISSUE THREAD

**Issue by BarbaraFe** [caelum/alura-funcionalidades#484]
Quando eu inicio um curso na plataforma web, é aberto um menu lateral e a informação para voltar a tela de Drashboard é apresentada ao final. Não sei se é só comigo que ocorreu, mas eu senti falta dessa opção no início e até perceber que a funcionalidade estava no final do menu, eu passei a utilizar os atalhos do próprio navegador para retornar ao Drashboard. Acho que seria interessante colocar um destaque nessa funcionalidade, deixando ela no início desse menu pois é um ponto de costume quando tentamos voltar a página anterior.

**Comment by designernatan** [comment]
@BarbaraFe valeu pela sugestao!

hoje fica bem escondido mesmo, erramos lá atrás na hora de projetar a interface

queremos melhorar a tela de aula num futuro e esse ponto sobre poder voltar pra página anterior precisará ficar mais claro mesmo

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
