### ISSUE TITLE
Guias de estudo / formações

### ISSUE THREAD

**Issue by BarbaraFe** [caelum/alura-funcionalidades#485]
No acesso do aplicativo vocês possuem uma funcionalidade show de bola, que permite a visualização das guias de estudo e quis cursos estão vinculados a ela logo na primeira tela do meu acesso. No acesso Web, não encontrei fácil essa funcionalidade e fico um pouco perdida para localizar quais o próximo curso que é recomendado eu realizar dentro daquela formação que eu desejo.

**Comment by designernatan** [comment]
@BarbaraFe valeu pela sugestao!

tentamos deixar a experiencia alura bem similar em todas as plataformas (app, web, etc), falhamos no onboarding 

de qualquer forma, queremos atacar mais o onboarding no futuro

abraços!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
