### ISSUE TITLE
Dark Mode no Dashboard, por favor

### ISSUE THREAD

**Issue by RockFall** [caelum/alura-funcionalidades#486]
Quando estamos assistindo a aula ta tudo ok mas é voltar pro Dashboard que a cegueira vem junto

**Comment by laisgalvaos** [comment]
rs eu te entendo @CaioRocha-UFV 
O pedido de darkmode para toda a plataforma é uma das coisas mais pedidas por aqui! Nós estamos trabalhando para atender essa demanda, só não consigo te dar uma prazo, tudo bem? Quando estiver pronto, avisamos, ou, você mesmo saberá! ;)
Por hora, você pode fazer isso manualmente conforme ensinaram nesse tutorial [aqui](https://github.com/caelum/alura-funcionalidades/issues/156#issuecomment-632410492)

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
