### ISSUE TITLE
Mostrar a quantidade total de horas dentro dos planos de estudo

### ISSUE THREAD

**Issue by andre6293** [caelum/alura-funcionalidades#487]
Dentro dos planos de estudo seria interessante inserir o tamanho total e dos cursos individualmente.

Segue uma imagem exemplo:
<img width="1235" alt="Screen Shot 2021-06-16 at 15 37 46" src="https://user-images.githubusercontent.com/61568351/122274731-46fa1c00-ceb9-11eb-8e37-9eccef4b3f75.png">

**Comment by designernatan** [comment]
@andre6293 valeu pela sugestão!

legal essa, quando pegarmos a tela de PDE para melhorarmos vamos considerar ok?

uma curiosidade minha: qual o valor que você enxerga em exibir essas infos?

abraços!

**Comment by andre6293** [comment]
Acho interessante para o aluno perceber os avanços. Além disso, criei alguns guias para amigos meus e com esse recurso seria mais fácil eles avaliarem qual/quais dos planos de estudo seguir com o tempo que eles têm.

> @andre6293 valeu pela sugestão!
> 
> legal essa, quando pegarmos a tela de PDE para melhorarmos vamos considerar ok?
> 
> uma curiosidade minha: qual o valor que você enxerga em exibir essas infos?
> 
> abraços!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)

se tivermos novidades no futuro avisamos aqui
