### ISSUE TITLE
Projetos

### ISSUE THREAD

**Issue by tiagogb21** [caelum/alura-funcionalidades#488]
Eu sinto falta de exercícios, os exercícios são geralmente resolvidos pelos professores, gostaria de um lugar onde fossem disponibilizados desafios toda semana, quem sabe todo dia, não custa sonhar. 

Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

Projetos que os alunos poderiam fazer para aperfeiçoar suas habilidades, como, por exemplo, "desafios":

 "Crie a nossa página da alura": aí colocar um site de uma grande empresa, como, por exemplo, o facebook ou o instagram. O objetivo seria reproduzir aquele site.

 Poderia, além de criar a página, ter um espaço para criatividade, no qual o aluno seria livre para criar uma página de perfil para o Alura. Um espaço livre para implementar as ideias dos alunos e, com isso, treinar os conhecimentos que já foram aprendidos. Como um botão diferente, ou, até mesmo, um recurso para facilitar a vida de pessoas com deficiência (seja visual, auditiva, ou qualquer outra). Nesse caso, o aluno não seria obrigado a colocar seu nome, apenas se quisesse, para incentivar aqueles que são mais tímidos. Poderia ter um lugar para que os alunos pudessem compartilhar os projetos e nesse local ter um espaço para sugestões e críticas. É claro que antes de tudo isso acontecer, iria passar por algum tipo de filtro, para evitar alguma coisa que foge do esperado.

**Comment by laisgalvaos** [comment]
Olá @tiagogb21. Ótima sugestão! 
Por hora não temos como comportar uma estrutura desse porte de desafios diários, mas já estamos dando nossos primeiros passos. Você conhece o Alura Challenges? Recentemente lançamos a edição de Front-End. Ela já terminou mas você, como aluno, pode desenvolver os desafios que propusemos e participar e acompanhar nossa comunidade no Discord. A ideia é manter essa comunidade ativa para que alunos, alunas e instrutores troquem ideias, se ajudem mutuamente e compartilhem seus projetos. E já estamos trabalhando para lançarmos mais edições em outras áreas/cursos!

Segue o link da edição, caso se interesse: https://www.alura.com.br/challenges/front-end

Também vamos levar em consideração suas sugestões para aprimorarmos nossas próximas edições.

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)

em tempo, agora está rolando outro challenge: de back-end! Vale dar uma conferida
https://www.alura.com.br/challenges/back-end
