### ISSUE TITLE
Ordernar/Filtrar as novidades

### ISSUE THREAD

**Issue by rafaelswitek** [caelum/alura-funcionalidades#489]
Gostaria que na [tela de novidades](https://cursos.alura.com.br/explore) tivesse a possibilidade de ordenar e filtrar, pois quando fico muito tempo sem entrar quero ver quais foram os cursos lançados nesse período de uma determinada categoria

**Comment by laisgalvaos** [comment]
Olá @rafaelswitek. Ótima sugestão! Nós estamos em fase de estudos e vamos revisitar essa parte de novidades juntamente com as recomendações para entregarmos uma experiência bem legal para os alunos e alunas. Por hora não consigo te dar um prazo sobre quando isso vai ser implementado, mas está no nosso radar de melhorias.
Obrigada pela participação. Assim que tivermos novidades nós avisamos por aqui!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
