### ISSUE TITLE
Desabilitar botão de Finalizar Curso até que indicação seja inserido

### ISSUE THREAD

**Issue by mcabeceira** [caelum/alura-funcionalidades#490]
Recentemente eu finalizei um curso e quando cheguei na tela para dar feedback da indicação do curso para um amigo, o botão `Finalizar Curso` estava verde, indicando que estava disponível para clicar. Porém eu não tinha inserido a opção de recomendar o curso e isso bloqueia o botão, o que levou um tempinho para descobrir

**Comment by andradeisadora** [comment]
oi @Foxtrot40 
estamos querendo melhorar algumas experiências no futuro e faz sentido esse apontamento.
obrigada pela sugestão!
abraço e bons estudos :)

**Comment by designernatan** [comment]
fechando a issue mas podem comentar depois mesmo com ela fechada :)
