### ISSUE TITLE
Botões de navegação para trocar de vídeo sem sair da tela cheia

### ISSUE THREAD

**Issue by ArthurDeCastroRibeiro** [caelum/alura-funcionalidades#491]
Percebi que no modo cinema existe um botão de avançar azul, o que permite pular para o próximo vídeo. No entanto, a mesma funcionalidade não está disponível no modo tela cheia. Isso faz com que sempre tenhamos que minimizar o vídeo, avançar para o próximo na lista e colocá-lo de novo em tela cheia. Seria interessante se existissem botões flutuantes de navegação nas laterais do vídeo que aparecessem com hover e pudéssemos usá-los para avançar para o próximo vídeo ou voltar para o anterior sem sair do modo tela cheia. De forma mais simples, esses botões poderiam até mesmo estarem na barra de controle do vídeo no canto inferior da tela.

**Comment by designernatan** [comment]
@ArthurDeCastroRibeiro  valeu pela sugestao!

tem uma [issue semelhante a essa aqui](https://github.com/caelum/alura-funcionalidades/issues/118) 

fizemos algumas boas melhorias nos ultimos meses na tela de aula, discutimos bastante sobre ter algo assim no modo tela cheia

optamos por nao atacar isso pois precisaria de uma grande refatoração, mas colocamos além do modo teatro o [autoplay](https://github.com/caelum/alura-funcionalidades/issues/457#issuecomment-834427828) para resolver (em partes) essa dor

abração!

**Comment by andradeisadora** [comment]
Fechando a issue, qualquer coisa pode comentar com ela fechada :)
