### ISSUE TITLE
API para consulta de desempenho na plataforma

### ISSUE THREAD

**Issue by thedatascientistichub** [caelum/alura-funcionalidades#492]
Olá,

Sou aluno Alura e acho excelente!

Gostaria de saber se existe intenção ou projeto em andamento de API para que eu possa analisar meus dados na plataforma. 

Gostaria de poder analisar meu desempenho nos estudos, estatísticas de acesso, segmentação por professor, por formação, etc.

**Comment by designernatan** [comment]
@thedatascientistichub valeu pela sugestão e elogio :)

sobre API, indo em 'editar' no seu perfil, lá em baixo, disponibilizamos uma api com algumas dessas informações

infelizmente sem planos ainda para a aprimorarmos, mas depois você pode me ajudar voltando aqui e me falando como tem usado? Alguns pontos de melhoria, etc? Ajuda demais esses feedbacks

abração!

**Comment by luigiMinardi** [comment]
@thedatascientistichub A alura tem 2 API's, A publica, que vai te dar informações sobre cursos, categorias e formações e a API para alunos onde você vai pegar um token na pagina que o Natan disse e com isso você consegue pegar informações sobre os cursos que você tem feito e guias de estudo. 

Esses 2 links podem te ajudar um pouco mais:

https://suporte.alura.com.br/article/315-como-funciona-a-api-publica-da-alura

https://suporte.alura.com.br/article/314-beta-api-do-dashboard-para-alunos

**Comment by designernatan** [comment]
@thedatascientistichub fechando a issue mas pode me responder mesmo com ela fechada :)
