### ISSUE TITLE
Fórum - Aumentando as possibilidades

### ISSUE THREAD

**Issue by Matheus-Pazinati** [caelum/alura-funcionalidades#493]
Quando vou criar um tópico no fórum, a plataforma já encara este tópico como uma dúvida que eu tenho em algum curso, porém nem sempre este tópico é uma dúvida, as vezes, eu só quero complementar algo que o professor disse, ou então postar o meu código para consolidar o "Faça você mesmo", que existe ao final de cada módulo. Porém como eu disse, a plataforma encara tudo isso como uma dúvida. Então se eu posto meu projeto ao final do módulo, eu posso abrir o campo de comentários, para as pessoas perguntarem algo, ou elogiarem, mas não faz sentido eu marcar a resposta dela como solução. A minha sugestão seria, quando o usuário quiser inserir um novo tópico, a plataforma dar a opção: Dúvida, Sugestão, Complementar o curso, Postar o meu projeto, onde para cada um desses, eu ter um comportamento diferente. Grande parte dos tópicos sem resposta ou sem solução do fórum ocorre por conta das pessoas postarem sugestões ou projetos, e alguém apenas visualizar, mas como não há o que comentar, a tópico fica aberto.

**Comment by designernatan** [comment]
@Matheus-Pazinati valeu pela sugestao!

dar essa opção no começo parece uma boa sim!

[recentemente outro aluno sugeriu uma maneira de separar os tipos de dúvida](https://github.com/caelum/alura-funcionalidades/issues/446) tambem!

quando pegarmos o fórum para melhorá-lo vamos discutir essa sua sugestão

aproveitando aqui também, como é exatamente seu uso do fórum hoje? 

abração!

**Comment by Matheus-Pazinati** [comment]
Eae Natan, tudo bom ? Então, pra você ter uma ideia, faz 40 dias que
assinei a Alura, e já tenho mais de 50 posts no fórum, com 13 tópicos
resolvidos. Faço isso como forma de consolidar os conhecimentos vistos no
curso, além de ser gratificante quando você responde uma dúvida e tem a
sensação de que está contribuindo com o aprendizado de outra pessoa. E o
legal é que você acaba ficando dependente do fórum, eu mesmo as vezes me
pego atualizando a página várias vezes, para ver se alguem postou mais
alguma dúvida de algum assunto que já vi aqui na Alura (no momento, fico
monitorando o fórum dos cursos de HTML CSS, Git e github, e me arrisco as
vezes em Javascript, e agora também nos cursos de Acessibilidade Web, que é
o curso que estou fazendo no momento, inclusive parabéns pela didática
professor, estou curtindo muito o conteúdo do curso e a profundidade que
você trouxe ao tema.) Hoje, indo para o trabalho e pensando sobre o Fórum
lembrei de mais um detalhe que esqueci de colocar la na sugestão, que é a
questão da pessoa que abriu o tópico conseguir excluir o mesmo. Fico feliz
pelo feedback, e em saber que vocês realmente estão interessados em
melhorar a plataforma, assim como dão ouvidos aos alunos. Obrigado.

Em qua., 23 de jun. de 2021 às 08:31, Natan Souza ***@***.***>
escreveu:

**Comment by designernatan** [comment]
opa brigadao pelo seu tempo em escrever matheus!

há um ano +- tínhamos uma feature que avisava sobre dúvidas no fórum, com base no que a pessoa já terminou, mas dropamos pois nao atingiu os resultados que queríamos na época 

e brigadao pelo feedback, mãe alura que me ensinou(ensina) essas coisas :)

sempre estamos melhorando a alura como um todo, em geral avisamos [aqui sobre as novidades](https://www.alura.com.br/artigos/design-ux) 

abracao e bons estudos!

**Comment by designernatan** [comment]
issue fechada, mas podem comentar depois mesmo com ela assim :)
