### ISSUE TITLE
Certificado Completo

### ISSUE THREAD

**Issue by brmachado18** [caelum/alura-funcionalidades#494]
As vezes é necessário acompanhar um curso pré-requisitos para outro. E com esse curso completo ele mostra todas a Formações que possuem esse curso no meu "fullCertificate", é algo que eu não acho interessante já que as vezes aparece uma formação que não tenho interesse em faze-la por completo, então a sugestão é para montar o certificado completo mostrar apenas a formação quando eu tiver realizada ela por completo e o restante ficar em outros cursos.

Exemplo: 
Completei o curso:
HTTP: Entendendo a web por baixo dos panos (de 25/06/2021 a 26/06/2021) 14hrs

e apareceu no meu certificado completo:
Formação: Django ( que no momento eu não tenho interesse em completa-la).
Formação: HTML e CSS ( que completarei futuramente). 

Mas no momento realizei o curso apenas por ser pré-requisito para o curso "Asp.NET Core: Uma webapp usando o padrão MVC". Então acho que esse curso poderia ficar em "outros cursos" ate eu completar uma formação que contenha ele, como a Formação: HTML e CSS que planejo completar futuramente.

Acho que isso possa deixar um certificado mais "clean" para que eu possa compartilhar com terceiros. Pois tipo a formação Django no momento foge um pouco da minha linha de estudos.

**Comment by andradeisadora** [comment]
Oi @brmachado18 :)
Queremos melhorar o certificado no futuro e faz sentido esses apontamentos. Obrigada pela sugestão!
Abraço e bons estudos

**Comment by designernatan** [comment]
@brmachado18 fizemos uma alteração no sistema do Certificado Completo

mudamos a regra em geral e agora é possível ocultar uma formação para poder gerar o pdf

me fala depois o que achou?

abcs

**Comment by brmachado18** [comment]
Muito bom, gostei. Aparece a formação somente quando esta completa e os cursos aparecendo na parte inferior. 
Parabéns!

**Comment by designernatan** [comment]
show, valeu meu caro! :)
