### ISSUE TITLE
Curso é "requisito para"

### ISSUE THREAD

**Issue by Noriller** [caelum/alura-funcionalidades#495]
assim como existe: 
![image](https://user-images.githubusercontent.com/54413263/123522590-86342400-d694-11eb-8674-5dad45b8ab49.png)

poderia haver algo do tipo "requisito para:"

há muitos cursos que estão fora de uma formação, mas eu preciso ficar caçando todos ou achar qual é o último.

exemplo: 
![image](https://user-images.githubusercontent.com/54413263/123522639-d8754500-d694-11eb-9212-c8435ea2bb0b.png)

procurando um curso recomendado, o algoritmos 2 está lá em baixo... será que tem um 3? Será que uma possível "continuação" não está com outro nome?

poder saber quais cursos dependem de um ajudaria a seguir para os casos que não estão dentro de uma formação

**Comment by designernatan** [comment]
@Noriller obrigado pela sugestao!

nesse caso especificamente como algoritmos é uma skill que casa com diversos outros cursos o nosso algoritmo(!) de busca deve ter priorizado os conteúdos com algum outro critério

fica tranquilo pois estamos de olho para mexer na busca ha um tempo, no futuro teremos novidades


abracao!

**Comment by Noriller** [comment]
Olá,

Deixei a busca mais como um exemplo... a sugestão mesmo seria ter na barra lateral os cursos que tem esse como requisito...

Nessa de buscar, para tras o que são requisitos, achei vários cursos bacanas... poder fazer o "caminho inverso" e olhar os cursos que tem "a frente" seria muito legal.

**Comment by andradeisadora** [comment]
fechando a issue mas pode voltar a comentar se quiser :)
