### ISSUE TITLE
Uma parte na plataforma onde fosse posto os videos dos botcamps rapidos gratuitos que são feitos periodicamente

### ISSUE THREAD

**Issue by TiagoHeld** [caelum/alura-funcionalidades#496]
Gostaria que fosse colocado em uma parte da plataforma os videos dos bootcamps gratuitos que são feitos periodicamente. Assim como foi feito no challenge, acho interessante, pq as vezes não conseguimos participar durante o periodo que é aberto o bootcamp, e pondo na plataforma depois do fim do bootcamp acho interessante, eu vi essa funcionalidade numa plataforma concorrente.

**Comment by designernatan** [comment]
@TiagoHeld valeu pela sugestao!

atualmente as imersões realmente acabam quando passa seu período, entendo que é complicado a questão de conseguir priorizar (eu mesmo tenho alguns pontos com isso)

como sempre tá tendo imersão, você pode ficar mais por dentro das próximas se inscrevendo aqui: https://www.alura.com.br/imersao

abraços!

**Comment by designernatan** [comment]
issue fechada, mas podem comentar depois mesmo com ela assim :)
