### ISSUE TITLE
Rede Social

### ISSUE THREAD

**Issue by Fernand0Devel0per** [caelum/alura-funcionalidades#497]
O forum é uma otima ferramenta para discutirmos novas ideias e postar nosso progresso, porem sinto a falta de a possibilidade de ter uma lista de amigos que eu possa ter mais proximidade e realizar discuções em chat, voz ou mesmo até meet dentro da plataforma como em uma escola.

**Comment by designernatan** [comment]
@Fernand0Devel0per valeu pela sugestao!

sem planos por hora para algo assim nativamente, mas com os Challenges você pode ter mais esse senso de comunidade, pedir opinião em projetos, compartilhar ideias, etc

o de front-end recentemente foi um sucesso, muita gente no Discord se adicionando, compartilhando github/linkedin/etc

fica de olho nas nossas comunicações que o próximo tá no forno :)

abração!

**Comment by designernatan** [comment]
issue fechada, mas podem comentar depois mesmo com ela assim :)
