### ISSUE TITLE
Link com desconto no perfil

### ISSUE THREAD

**Issue by EmilioModenez** [caelum/alura-funcionalidades#498]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Estou em um grupo de DEVs e neste momento alguém perguntou se tinha um link para desconto, eu fui procurar e não encontrei, seria interessante para então conseguirmos ajudar mais gente na plataforma... outra seria algo para apresentação para empresas, estou em uma pequena empresa de desenvolvimento com 160 funcionários e gostaria de indicar a plataforma e com incentivo ficaria melhor ainda!

**Comment by designernatan** [comment]
@EmilioModenez valeu pela sugestao!

1. em geral pra descontos o canal mais rápido que enxergo é pingar a Alura nas redes sociais, recomendo [o Twitter](https://twitter.com/aluraonline) 
2. sem planos ainda para ter um sistema de indicação/desconto perene, mas é algo que discutimos eventualmente
3. de empresas, recomendo pedir um [trial corporativo aqui](https://www.alura.com.br/empresas/experimente-gratis), aí o time focado em clientes corporativos consegue direcionar melhor

abração e bom fim de semana!

**Comment by designernatan** [comment]
issue fechada, mas podem comentar depois mesmo com ela assim :)
