### ISSUE TITLE
Respostas e gamefication

### ISSUE THREAD

**Issue by luissenko** [caelum/alura-funcionalidades#499]
Olá, pessoal! 😃

Ao erramos uma questão nas atividades dos cursos é nos dada a opção de tentar novamente, além da explicação do erro. Isso é muito bom, mas eu tive um insight de que alguns usuários podem ir clicando aleatoriamente até acertar só pra passar e seguir em frente. No final das contas é uma decisão do usuário, mas acho que em termos de aprendizagem pode ser interessante limitá-lo um pouco.

Pensando nisso, eu acredito que poderia ser adotado junto ao atual sistema de gamification a possibilidade do usuário perder uma determinada quantidade dos pontos que ele já possui na plataforma ao errar as questões. Algo similar é feito em uma plataforma concorrente que não vou citar o nome (apenas dizer que é o mesmo nome do vocalista do Black Sabbath entre os anos de 1980 e 1982 😂😂😂).

Por fim, para que a perda de pontos seja algo relevante para o usuário, seguindo a ideia do Michel [aqui](https://cursos.alura.com.br/forum/topico-sobre-os-pontos-acumulados-58538), penso que os pontos podem ser convertidos em dinheiro para uso na matrícula dos Bootcamps, uma vez que usá-los para desconto na mensalidade - como sugerido - seria muito oneroso para a receita da empresa.

**Comment by designernatan** [comment]
@luissenko valeu pela sugestao!

Legal, bom ponto, concordamos aqui totalmente contigo sobre esse primeiro ponto: é uma decisão da pessoa! 
E valeu pela dica do black sabbath, precisei googlar mas... mensagem passada! :P

Sobre o gamification como um todo, precisamos melhorar o ranking/gamefication, por hora sem previsão, ok?

Abração!

**Comment by designernatan** [comment]
issue fechada, mas podem comentar depois mesmo com ela assim :)
