### ISSUE TITLE
Sugestão de erros em outros lugares

### ISSUE THREAD

**Issue by mautoz** [caelum/alura-funcionalidades#5]
Não é possível sugerir correções em soluções de exercícios ("Opinião do Instrutor"). Seria legal mandar correção nessas partes também.

**Comment by designernatan** [comment]
Oi @mautoz , tranquilo?

Faz todo sentido. Vou ver com o lead team aqui a complexidade de colocar essa opção nas alternativas também.

Obrigado pela sugestão!

Abcs!

**Comment by mautoz** [comment]
Percebi que já está funcionado! Ficou melhor!
Obrigado!

**Comment by designernatan** [comment]
fechando entao, valeu mautoz!
