### ISSUE TITLE
Fórum - Exibição de limite de caracteres e manter conteúdo na página em caso de erro

### ISSUE THREAD

**Issue by JuniorRodrigues** [caelum/alura-funcionalidades#500]
Hoje passei por uma decepção realmente frustrante no fórum da Alura. Ao tentar ajudar uma pessoa escrevi um pequeno artigo sobre o assunto para esclarecer. Enviei a mensagem e para minha surpresa:
"O post só pode ter no máximo 5.000 caracteres. Caso deseje colocar uma mensagem muito grande, talvez interesse usar o gist"

Se soubesse disso enquanto escrevia a mensagem com um limitador de caracteres que já mostrasse a sugestão do gist não teria perdido tanto tempo, ainda mais porque a página é atualizada e tudo que escrevi foi perdido... E não tenho a intenção de escrever, adicionar links de referencia e formatar tudo novamente.

**Comment by andradeisadora** [comment]
oi @JuniorRodrigues peço desculpas pelo erro :(
Já estamos nos organizando para fazer essa correção num futuro de médio prazo e agradeço por nos avisar!

Abraço e bons estudos

**Comment by gabrielareia** [comment]
Aconteceu a mesma coisa comigo hoje, sorte que eu sou paranoico com essas coisas e sabia que seria um texto grande e fui salvando no Sublime enquanto escrevia, então perdi só uma parte do que eu tinha escrito, mesmo assim demorou pra reescrever e lembrar tudo o que eu não tinha salvado.

Depois disso eu escrevi o resto no Sublime fazendo o meu melhor pra resumir tudo, e consegui chegar em 4999 caracteres, tentei novamente e tomei o mesmo erro. Entrei no modo desenvolvedor do navegador e vi o que estava sendo enviado quando eu apertava o botão, e vi que o que é enviado é um pequeno html formatado, com todas as tags meu texto estava dando mais de 5200 caracteres. Então o limite de caracteres não é nem 5000, é bem menos, porque tem que levar em consideração as tags do html escondidas.

Podia pelo menos checar isso antes de tentar enviar os dados, ou de algum jeito pelo menos salvar o texto. 

Na faculdade que estou fazendo eles usam o Moodle, e tem um sistema de forum bem parecido, mas lá eles salvam o texto na sua conta automaticamente e periodicamente. Isso ja me salvou varias vezes, pode ser interessante também, embora isso seja muito mais complicado de implementar do que simplesmente checar o tamanho do texto antes de postar.

**Comment by andradeisadora** [comment]
Oi @JuniorRodrigues @gabrielareia 
Já está no nosso radar pra fazer esse ajuste, assim que tiver novidades volto aqui pra avisar vocês :)

Vou fechar a issue por enquanto mas podem continuar comentando se quiserem
