### ISSUE TITLE
A altura maxima da logo de empresas

### ISSUE THREAD

**Issue by Kretik** [caelum/alura-funcionalidades#501]
**Mexer na altura maxima da logo da empresa que fica no cabeçalho do alura, para q não fique achatado.**

_obs: sou aluno e iniciante no css ;-;_

**Comment by designernatan** [comment]
@Kretik consegue mandar um print como está e como ficaria colocando esse max-height?

será que a imagem foi colocada errada também? (pode acontecer)

`<off>`
  legal que está aprendendo CSS e já vai vendo onde uma declaração pode ajudar no front, isso é mto bom :)
`</off>`

**Comment by Kretik** [comment]
@designernatan 
Antes
![achatado](https://user-images.githubusercontent.com/87046352/127507381-2022b95a-b2c2-4d15-93fa-0661869c11de.png)

Depois
![altura normal](https://user-images.githubusercontent.com/87046352/127507431-1cf2e0a0-173e-42c9-acf6-1810bc567a5a.png)

eu alterei pra 50 (n sei se estou fazendo certo, mas funcionou >->)
![onde_alterei](https://user-images.githubusercontent.com/87046352/127507560-907ad170-6cdd-45c6-8aa8-bded8a44361c.png)

**Comment by Kretik** [comment]
mas acho que foi colocado errado como vc falou.

**Comment by Kretik** [comment]
Não mudou muita coisa, mas estava meio estranho ele achatado.

**Comment by designernatan** [comment]
estamos vendo de dar um jeito nisso, ficar achatado realmente não dá pois perde a identidade do logo

qualquer novidade quando subir a melhoria vai aparecer aí :)

abcs!

edit:
essa foi mais rapida: atualizamos o logo aqui kretik :) valeu!
