### ISSUE TITLE
Pagamento mensal

### ISSUE THREAD

**Issue by ViniciusGRBarbosa** [caelum/alura-funcionalidades#502]
Vocês poderiam colocar uma opção de pagamento mensal, por exemplo, se a pessoa se inscreveu no dia 12/07 ela teria 30 dias para renovar o pagamento para o mês seguinte. A opção de cobrança anual fica puxado para algumas realidades, creio que teriam mais alunos se colocassem uma opção de pagamento nesse estilo.

**Comment by designernatan** [comment]
oi @ViniG78 

ja fizemos alguns testes e o preço saia caro e nao funcionava na retenção e forma que as pessoas usam a plataforma. mas se precisar de um semestral manda um email no atendimento@alura.com.br e tentamos ajudar, ok?

abcs!

**Comment by designernatan** [comment]
issue fechada, mas podem comentar depois mesmo com ela assim :)
