### ISSUE TITLE
Medidor de nível de dificuldade

### ISSUE THREAD

**Issue by joaovalv** [caelum/alura-funcionalidades#503]
Entrei hoje na plataforma e estou gostando bastante da experiência no geral. No entanto demorei um tempo para encontrar o que eu queria.

Entrei na Alura para mudar de área, sempre gostei de programar, e gostaria de começar na Alura aprendendo Java.

Quando entrei na página de formações (principalmente "Formações em programação") me deparei com várias formações com Java, entrei no primeiro que apareceu: Certificação Java. Já nos primeiros segundos me assustei, não estava entendendo nada e teoricamente aquele curso começava pelo básico, como dizia a descrição:
_"Aqui você vai se preparar para encarar o desafio da certificação Java OCJP I, mergulhando fundo na linguagem, do básico ao avançado."_

Depois de um tempo vi que existia um pré-requisito para a primeira aula, então fui indo de pré-requisito em pré-requisito até chegar no "Java JRE e JDK" que descobri fazer parte de outra formação "Java e orientação a objetos" que era uma das últimas opções dentro de "Formações em programação".

Achei esse processo de encontrar o ponto de partida bem confuso e se houvesse uma forma de ordenar por nível de proficiência ou então algum indicador de nível de dificuldade ajudaria muito aos iniciantes.

Melhor ainda seria ter outra página dentro de "Formações em programação" e nessa nova página se abrissem árvores de cursos, mostrando qual é pré-requisito de qual.

Penso que dessa forma o iniciante sabe por onde começar e também o intermediário consegue filtrar até onde já sabe e onde ele deve entrar.

Indo mais além, seria muito legal no primeiro acesso na plataforma o sistema perguntar qual o nível de conhecimento do aluno e qual o objetivo, depois em seguida sugerir um caminho. Caso a pessoa ainda não saiba seu objetivo final, o sistema poderia sugerir um curso que ajude a escolher esse objetivo.

Até o momento estou gostando muito da experiência e esse foi o único problema que tive na plataforma!

**Comment by joaovalv** [comment]
Encontrei a página [Programação](https://cursos.alura.com.br/category/programacao), que é muito parecida com a página que havia comentado.

Seria muito bom se ela abrisse a partir da página Formação.

**Comment by laisgalvaos** [comment]
Olá @joaovalv 
Que ótimo que está gostando da plataforma. Ficamos felizes em poder ajudar você nesse processo.
Você levantou um ótimo ponto de melhoria, inclusive é algo que está no radar na nossa equipe. Estamos sempre trabalhando para melhorar a plataforma e já  trouxe aqui seu pra pensarmos como um todo nessa questão. Por hora não temos uma previsão, mas queremos melhorar esse fluxo.
Desejo ótimos estudos para você!
Abraços
