### ISSUE TITLE
Meta diária por pontos de XP

### ISSUE THREAD

**Issue by joaovscorreia** [caelum/alura-funcionalidades#504]
Acho que seria interessante ter alguma forma de meta diária exibida no Dashboard. A maneira mais fácil em minha opinião de implementar isso, e o que eu acho que poderia ser bem interessante seria através de pontos de XP, já que é uma métrica que abrange conclusão de cursos/carreiras e exercícios resolvidos.
Assim, o usuário poderia definir nas configurações o tanto de XP que almeja conseguir por dia (ou por semana, mês, poderiam haver opções mais flexíveis), e na Dashboard seria exibida a barra de progresso relacionada.

**Comment by laisgalvaos** [comment]
Olá @castanhocorreia 
Muito legal essa sua sugestão! Acho que faz bastante sentido. Vou levar para nossa equipe para discutirmos. A plataforma está sempre em evolução, mas por hora não temos previsão de implementação dessa feature, tudo bem? Se tivermos alguma novidade nesse sentido passamos para contar.

Abraços e bons estudos!
