### ISSUE TITLE
Plano de Estudos - Permitir adicionar artigos e vídeos do Alura+

### ISSUE THREAD

**Issue by renatoviegas** [caelum/alura-funcionalidades#505]
Assim como nas formações, permitir associar os artigos existentes e vídeos do alura+ no plano de estudos, será bem interessante.

**Comment by laisgalvaos** [comment]
Olá @renatoviegas,
Você sabia que isso já é possível? As páginas do Alura+ já aparecem na filtragem da busca. E você ainda pode colar o link direto na barra da busca e clicar no botão buscar.
Mas agradeço a sugestão, vamos tentar deixar isso mais claro na página.
Abraços e bons estudos.

**Comment by renatoviegas** [comment]
Ah verdade, mas a opção só existe dentro da edição do plano de estudos, entendido.

Muito obrigado!

**Comment by laisgalvaos** [comment]
Oi @renatoviegas, só para entender melhor, onde você gostaria que isso fosse possível?

**Comment by renatoviegas** [comment]
Quando entramos em um curso, existe a opção "Adicionar a um plano de Estudos"
Esta mesma opção poderia estar disponível nos resultados de artigos e vídeos do Alura+

Pode olhar um exemplo aqui: https://hackmd.io/7EjomMfaSa6VNG5lIH91jQ

**Comment by laisgalvaos** [comment]
Interessante @renatoviegas. Estamos desenvolvendo algumas ideias de melhoria na exibição dos nossos conteúdos o que inclui uma forma de adicionar mais rápida. Vou levar sua sugestão para a equipe mas por hora não temos previsão de quando vamos implementar, tudo bem?

Obrigada pela sua contribuição! =)
