### ISSUE TITLE
Plano de Estudos - Permitir criar seções no plano de estudo

### ISSUE THREAD

**Issue by renatoviegas** [caelum/alura-funcionalidades#506]
Assim como nas formações, poder permitir criar seções no plano de estudos irá auxiliar no progresso dos objetivos desejados.

**Comment by laisgalvaos** [comment]
Olá @renatoviegas, agradecemos sua sugestão, vamos analisar a possibilidade, mas por enquanto sem previsão, tudo bem?
Enquanto não temos nada parecido, uma sugestão é criar mais planos de estudos mais curtos e nomeá-los sequencialmente ou por temática, algo faça sentido para você. Sei que não é exatamente o que você espera, mas é algo que eu mesma acabei fazendo para me organizar.

Ótimos estudos
Abrçs

**Comment by andradeisadora** [comment]
fechando a issue mas podem voltar a comentar se quiserem :)
