### ISSUE TITLE
Teclas de atalho

### ISSUE THREAD

**Issue by maisondev** [caelum/alura-funcionalidades#507]
Bom eu estudo online já faz uma década e vejo a evolução de algumas plataformas semelhantes a Alura de perto, e com relação a vídeos tivemos várias melhorias recentes com o Youtube e também alguns insights do Netflix, uma funcionalidade que me faz bastante falta na alura e que vejo em outros players é a possibilidade de controlar o vídeo pelo teclado, já existem alguns atalhos de teclado mas o modo que eles foram implementados não facilita o uso por parte do usuário, eu mesmo tive que testar tecla por tecla o que cada uma fazia em relação ao vídeo, uma melhoria seria colocar um guia para os atalhos do teclado no player e também organizá-los de uma maneira que facilite você fazer coisas básicas tipo: acelerar e em seguida desacelerar quem estuda sabe que as vezes voltamos numa parte do vídeo para entender melhor um assunto então como estamos tentando entender passamos com mais calma já em outros estamos somente revisando ou revendo algo que já sabemos então queremos passar em 1.75x e ir controlando pelo teclado, eu só consigo assistir tudo em 1.25x em diante e atualmente para você acelerar você tem o X ai não consegue desacelerar somente indo pra frente até chegar na última velocidade e voltar para a mais lenta, seria interessante ainda que os comandos de aumentar a velocidade tivesse um atalho semelhante ao de avançar 10 segundos o que facilita muito na hora de controla exemplo: aumentar velocidade SHIFT + SETA PRA FRENTE e avançar 10 segundos SETA PARA FRENTE. Em anexo vou postar uma imagem de como seria mas a implementação não precisa ser idêntica apenas seguir essa considerações que postei como usuário.

![image](https://user-images.githubusercontent.com/87338019/125977611-900f88e2-78a5-440a-8c57-943c58fcf738.png)

**Comment by laisgalvaos** [comment]
Olá @maisondev. Obrigada pela sua sugestão, acho que faz sentido mesmo. Agradeço a descrição detalhada da sua experiência. Esses relatos são muito valiosos para entendermos como as pessoas usam a Alura e como elas esperam que a Alura evolua, assim analisamos o que é possível fazer. Uma evolução para todas essas funcionalidades que você citou deve demorar um pouco mais. Vou levar para nosso time analisar. Mas com certeza um guia explicando os atalhos que já temos é algo muito importante e vamos tentar priorizar. Se tiver alguma novidade, contamos para você.
Ótimos estudos!
Abrçs

**Comment by marisnner7** [comment]
Eu tava procurando justamente essa sugestao, senao ia fazê-la. Olhem com carinho @laisgalvaos por favor. 
E como uma v2: proximo video e full screen

**Comment by laisgalvaos** [comment]
Olá @marisnner7 e @maisondev . Por hora ainda não teremos o avançar vídeo, mas mapeamos o que já existe e a lista é o seguinte:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-9ecf9c13-7fff-a593-ffef-fd479b55d6d5"><div dir="ltr" style="margin-left:0pt;" align="left">

Barra de espaço | Toca (Play)/Pausa o vídeo quando nenhum botão estiver em foco (selecionado). / Ativa ou desativa a função do botão que estiver em foco.
-- | --
Teclado de mídia: Play / Pause / Stop | Ações de Tocar / Pausar / Parar o vídeo
k | Pausar/Tocar o vídeo.
m | Mutar/desmutar o vídeo.
← (seta esquerda) | Volta 10 segundos a reprodução do vídeo.
→ (seta direita) | Avança 10 segundos a reprodução do vídeo.
↑ (seta acima) | Aumenta o volume em 5%.
↓ (seta abaixo) | Diminui o volume em 5%.
f | Ativa/Desativa a tela cheia (full screen).

</div><br /></b>
</body>
</html>

Já vai entrar no nosso roadmap para ser implementado, mas não tenho uma data ainda, tudo bem?
Abrçs

**Comment by andradeisadora** [comment]
Fechando a issue mas podem voltar a comentar se quiserem :)
