### ISSUE TITLE
Sugestões personalizadas de trilhas de estudo de acordo com os interesses do usuário

### ISSUE THREAD

**Issue by marceldamico** [caelum/alura-funcionalidades#508]
Pessoal, 
Sugiro a criação de um formulário para que os novos assinantes possam informar seus principais interesses e o nível de conhecimento que eles tem sobre os assuntos. Com isso a plataforma poderá sugerir trilhas de aprendizagem focadas nos interesses do usuário e direciona-los da melhor forma possível para obter seus objetivos.
Essa feature poderia ser evoluída posteriormente, permitindo que os usuários possam revisar seus interesses ao longo do tempo e assim obter novas sugestões de trilhas de aprendizagem.

**Comment by laisgalvaos** [comment]
Olá @marceldamico. Sua sugestão faz todo sentido e já estamos estudando como melhorar esse processo.
Por hora, estamos para lançar uma atualização nos perfis dos alunos em que eles podem selecionar ali quais as áreas de interesse. Ainda não tenho uma data específica, mas vai ser em breve. Esse é o nosso primeiro passo para começarmos a ter um banco de dados nesse sentido para melhorar a experiência da personalização e a partir daí irmos evoluindo. 
Agradeço sua contribuição! Ótimos estudos!
Abraço

**Comment by andradeisadora** [comment]
Fechando a issue mas podem voltar a comentar se quiserem :)
