### ISSUE TITLE
Acompanhamento do nível de senioridade dos usuários em cada tema

### ISSUE THREAD

**Issue by marceldamico** [caelum/alura-funcionalidades#509]
Pessoal,
Gostaria de sugerir o desenvolvimento de uma funcionalidade de acompanhamento do nível de senioridade dos usuários em cada tema de estudo. Por exemplo, para um usuário que está aprendendo sobre Agile seria interessantes ter um conjunto de trilhas de aprendizagem relacionadas ao tema e, ao passo que o usuário vai completando cada uma das trilhas ele vai "ganhando" pontos de senioridade. 
Poderia ser algo do tipo: trilhas A, B C e D são relacionadas com o tema 1. Quando o usuário completa a trilha A ele ganha 1 ponto de senioridade sobre o tema, quando completar a trilha B ganha mais 1 ponto e assim por diante. 
Isso também pode ser evoluído para futuramente para a geração de certificados de senioridade nos temas estudados. Imagino que possa ser algo similar aos certificados de trilhas. Se só conclui uma trilha sou níveis 1 de senioridade sobre aquele assunto e só consigo gerar o certificado da própria trilha. Se já conclui 3 trilhas sou nível 3 e consigo gerar um certificado que consolidando tudo que já aprendi sobre aquele tema.

**Comment by designernatan** [comment]
@marceldamico valeu pela sugestao e me desculpa pelo delay

estamos vendo algo relacionado a isso para um futuro próximo, não muito atrelado a nível de conhecimento técnico (jr, pl, senior) mas focando principalmente em criar conexões com base no que faz sentido pra todo mundo!

ex: sou front-end'er e quero estudar juntamente com outros alunos(as) que estão estudando angular

digamos que conheço bem react, deixar claro pra todos que conheço esse framework

---

sobre o certificado o que temos hoje mais próximo disso:

1. o certificado completo, que inclui todas as formações e cursos que você fez
2. a própria página de perfil com todos os meus highlights (posts, cursos e formacoes feitas, etc)

abcs!

**Comment by andradeisadora** [comment]
Fechando a issue mas podem voltar a comentar se quiserem :)
