### ISSUE TITLE
Sistema de pontos mais robusto.

### ISSUE THREAD

**Issue by KingNinhoCode** [caelum/alura-funcionalidades#51]
O sistema de pontos atual é muito simples, apenas mostrando com pequenos quadrados coloridos a sua pontuação diária e o ranking. Acredito que caso fossem adicionado um sistema de metas de pontos por dia ou uma visualização em grafico de barras ou linhas os alunos poderiam acompanhar muito melhor a sua atividade e se organizar melhor.

**Comment by designernatan** [comment]
oi @KingNinhoCode obrigado pela sugestão!

precisamos melhorar toda essa parte relacionada aos pontos e gamification em geral

um sistema de **metas de pontos** parece bem interessante, uma dashboard analítica bem bacana também!
