### ISSUE TITLE
Caderno de anotações

### ISSUE THREAD

**Issue by Fernand0Devel0per** [caelum/alura-funcionalidades#510]
Ola Equipe Alura, gostei muito da ideia de um caderno de anotações, porem o caderno que vocês disponibilizaram é muito simples, não da opção de editar o texto, não consigo nem o basico que seria negrito italico e sublinhado, sei que a funcionalidade é beta mas não esta atendendo a necessidade de fazer anotações que depois eu possa considerar relevante, sem contar que a janela é presa ao menu lateral da esquerda isso é horrivel, por que não posso movimenta-la e por exemplo assistir o video em tela cheia e colocar ela sobreposta no video para ir fazendo anotações durante o decorrer do video, um sistema de notas também seria muito util como em programas como o nixnote2. Esses são os pontos que achei relevante.

**Comment by andradeisadora** [comment]
@Fernand0Devel0per obrigada pelas dicas! 
Estamos com planos a longo prazo de melhoria pro caderno mas sem data prevista. Pra não ficar te devendo indico usar o Notion, lá você consegue todas essas features e algumas mais :)

Abraço e bons estudos!

**Comment by Fernand0Devel0per** [comment]
Obrigado pela indicação Isadora, ja dei uma olhada no notion, e gostei bastante facil de usar e fica como plugin facilitando o acesso pra pequenas notas, Vou tentar usar no futuro, minha dificuldade é largar o caderno fisico rsrs,

**Comment by andradeisadora** [comment]
@Fernand0Devel0per hahaha eu também tinha! Depois que comecei a usar o Notion comecei a largar. 
Dá uma olhada nesse [post](https://www.alura.com.br/artigos/organizando-estudos-portfolio-notion-linkedin), ele fala como organizar os estudos com o notion.

Vou fechar a issue, qualquer dúvida só reabrir :)
