### ISSUE TITLE
Canal no Discord

### ISSUE THREAD

**Issue by leeomarques** [caelum/alura-funcionalidades#511]
Seria uma ótima oportunidade de engajar mais os alunos e criar um ambiente mais colaborativo.

**Comment by andradeisadora** [comment]
@leeomarques obrigada pela dica!
Estamos querendo melhorar a área da comunidade mas são planos para o futuro. Quando fizemos isso levaremos em consideração essa sua dica :)

Abraço e bons estudos!

**Comment by laisgalvaos** [comment]
Olá @leeomarques, nossa ideia é essa mesma, inclusive o canal já está no ar, porém, ainda mais focado nos Challenges atualmente. Se quiser, acompanhe essa [thread](https://github.com/caelum/alura-funcionalidades/issues/409#issuecomment-790601105) em que contamos um pouco mais como ele está funcionando e como vai evoluir. 
Obrigada por contribuir!

**Comment by phmiranda** [comment]
@leeomarques essa é uma ótima ideia que tinha colocado uma vez. Acho que acaba ficando um fórum de dúvidas mais dinâmico e a tendência é dar mais visibilidade aos alunos, no sentido de tempo de resposta, e os fórum poderiam ser também populadores com soluções dos alunos enquanto estiverem abertos e não só pelos moderadores.

**Comment by andradeisadora** [comment]
Fechando a issue mas podem voltar a comentar se quiserem :)
