### ISSUE TITLE
Check dos podcasts já ouvidos

### ISSUE THREAD

**Issue by fabricioguidine** [caelum/alura-funcionalidades#512]
Seria bacana implementar um checkzinho, algum símbolo verde ou outra coisa similar que mostre que você já ouviu o podcast. 
Eu por exemplo gosto de consumir tudo que está disponível e ficar lembrando de cabeça o que já ouvi eu prefiro nem ouvir nenhum, seria melhor ainda se tivesse um indicador de até onde o podcast foi ouvido para continuar depois, mas se implementassem só a primeira função já seria ótimo.

Poderia ser algo até manual, eu marco o check se eu já ouvi pra saber.

**Comment by laisgalvaos** [comment]
Olá @fabricioguidine. ótimo ponto levantado, acho que faz bastante sentido.  Já levei para discussão com nossa equipe.
Se você puder me contar mais sobre sua experiência, pode nos ajudar nesse processo.
Como você costuma acessar os podcasts? Você entra pela Dashboard e busca pelo podcast preferido, ou já entra direto na pagina do podcast, ou algum caminho diferente? Ouve no desktop ou celular? ;)

Obrigada pela contribuição
Abraços

**Comment by fabricioguidine** [comment]
Eu costumo ouvir quando tô trabalhando em algo no meu desktop.
Normalmente vou pelo menu "Aprenda" e vou no podcast, mas gosto de consumir tudo que tem lá né, e como não tem como lembrar qual eu já ouvi até eu dar play e ficar lembrando, um check de que eu já ouvi, eu passaria a consumir mais.
Obrigado pelo retorno.

**Comment by laisgalvaos** [comment]
Obrigada pela resposta @fabricioguidine 
Eu já vou estudar a possibilidade de implementação disso, mas claro, não posso te prometer nada por hora!
Nós queremos sempre melhorar a experiência das pessoas que estudam na Alura, então todas essas sugestões são muito bem vindas.
Ótimos estudos pra você!

**Comment by fabricioguidine** [comment]
Tá certo!

**Comment by wandersonmaceds** [comment]
Oi @fabricioguidine tudo bem? Queria só passar e dizer que este seu pedido já está sendo implementado, tá bom? Logo mais passo pra avisar que está disponível quando colocarmos isso no ar. 

Obrigado pela sua sugestão e caso tenha mais dessas, por favor, mande pra gente via issue como fez aqui. :)

**Comment by andradeisadora** [comment]
oi pessoal, estou fechando a issue mas se precisarem podem voltar a comentar :)
