### ISSUE TITLE
Uma maneira mais simples de ver todos os cursos

### ISSUE THREAD

**Issue by MatheusAssisM** [caelum/alura-funcionalidades#513]
A ideia é que tivesse um botão no menu pra ver todos os cursos. Eu só descobri que dava pra ver todos os cursos bem depois de já ter feito algumas formações. 

Eu procurei mas não sabia que era apenas rolar pra baixo no dashboard.

A tela de todos os cursos é muita boa, mas a maneira de chegar até ela é ruim. Um botão "Cursos"  no menu ou algo do tipo seria o ideal pra quem não quer estudar por formação e sim por categoria de cursos. 

Chegar até essa tela (abaixo) de uma maneira mais simples.

![image](https://user-images.githubusercontent.com/65235458/126652300-23b00187-7972-4b00-8af9-943a152272da.png)

**Comment by designernatan** [comment]
@MatheusAssisM valeu pela sugestao!

estamos com alguns estudos em cima desta parte de discovery de conteúdos

aguarde novidades para esse semestre :)

**Comment by andradeisadora** [comment]
Fechando a issue mas podem voltar a comentar se quiserem :)
