### ISSUE TITLE
Opção para criação de documento PDF com as informações da vídeo aula.

### ISSUE THREAD

**Issue by phmiranda** [caelum/alura-funcionalidades#514]
Elaboração de uma funcionalidade que faça a exportação em PDF da transcrição da aula, incluindo os passos e também imagens formatadas dentro do PDF. Servindo como uma espécie de tutorial para acompanhar a aula.

**Comment by andradeisadora** [comment]
oi @phmiranda obrigada pela sugestão!
Você pode explicar um pouco melhor o que você pensou? 

Abraço :)

**Comment by designernatan** [comment]
oi pessoa, fechando a issue pra controle nosso mas podem comentar mesmo com ela fechada ok?

**Comment by phmiranda** [comment]
@andradeisadora eu estou tentando pesquisar modelos, mas é chato ter que ficar voltando a aula e tentando acompanhar os textos das aulas. Com um PDF ficaria mais fácil, ainda mais um PDF bem formatado e um template da Alura, isso facilitaria para colocar inclusive mais detalhamento sobre a aula com prints, imagens e print do código para exemplificação.
