### ISSUE TITLE
Plano Duo/Família

### ISSUE THREAD

**Issue by fiauxthales** [caelum/alura-funcionalidades#515]
Vocês poderiam incluir opções de plano para duas ou mais pessoas.

Uma das coisas que dificulta a assinatura da Alura é o alto custo individual. Um plano para duo ou família que desse um desconto interessante permitiria que mais pessoas conseguissem acessar por um valor mais acessível.

**Comment by designernatan** [comment]
@fiauxthales valeu pela sugestao!

o jayson [sugeriu algo semelhante aqui](https://github.com/caelum/alura-funcionalidades/issues/179)

vale ver o reply do sergio sobre a possibilidade do desconto nessas situações, ok?

abcs

**Comment by KenadAraujo** [comment]
Além disso, poderia ter uma opção de mensal (tipo uma Netflix de cursos de tecnologia kkkkkk)

**Comment by designernatan** [comment]
fala @KenadAraujo , valeu pela sugestao! :)

ja fizemos alguns testes e o preço saia caro e nao funcionava na retenção e forma que as pessoas usam a plataforma

---

fechando a issue mas podem comentar de boas depois ok
