### ISSUE TITLE
Mais opções de velocidade de reprodução dos vídeos

### ISSUE THREAD

**Issue by eduardo-penido** [caelum/alura-funcionalidades#516]
Olá.

Acho que seria muito interessante podermos escolher outras velocidades de reprodução dos vídeos, para que cada aluno encontre a sincronia ideal com cada instrutor.

Por exemplo: Alguns instrutores falam bem rápido, mas a primeira opção de redução de velocidade é 0,75x, o que, quase sempre, faz a fala do instrutor ficar arrastada e distorcida.

Penso que seria legal podermos definir exatamente a velocidade que mais nos agrada, como no YouTube.

Att,
Eduardo.

**Comment by designernatan** [comment]
@eduardobyte valeu pela sugestao!

[uma issue igual foi aberta aqui](https://github.com/caelum/alura-funcionalidades/issues/42)
como você disse depende muito do instrutor, do curso, do nosso momento no dia, etc

fazer o custom seria bem bacana, mas sem planos ainda

pra nao ficar te devendo: eu uso uma extensao chamada "video speed controller" (alura e youtube) e controlo com os atalhos dela

abcs

**Comment by eduardo-penido** [comment]
Opa, que legal.  
Já vou testar a extensão aqui.
Obrigado pela dica!!!

**Comment by eduardo-penido** [comment]
@designernatan, a extensão funcionou direitinho.
Mais uma vez, obrigado pela dica!!!

**Comment by andradeisadora** [comment]
Fechando a issue mas podem voltar a comentar se quiserem :)
