### ISSUE TITLE
Na busca, ter a opção de buscar por curso, formação, post, etc

### ISSUE THREAD

**Issue by brunhc** [caelum/alura-funcionalidades#517]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.
Sou funcionário do BB, então não sei se é só na versão unibb.alura.com.br, mas quando vamos pesquisar alguma coisa, mistura as formações com os cursos, podcasts, então seria legal um filtro na busca

**Comment by andradeisadora** [comment]
oi @brunhc obrigada pela sugestão!
Hoje mesmo entrou essa feature na busca, da uma olhadinha lá :)

Abraço e bons estudos!

**Comment by andradeisadora** [comment]
Fechando a issue mas pode voltar a comentar se quiser :)
