### ISSUE TITLE
Certificado Geral de cursos concluídos

### ISSUE THREAD

**Issue by RafaelMatthes** [caelum/alura-funcionalidades#518]
ps:. eu vi que existe um local especifico para reportar bugs... achei que seria bom uma issue já que tenho uma sugestão junto.

O certificado geral de cursos concluídos está com a contagem de horas errada, se você ocultar as formações, a contagem de horas dos cursos "avulsos" não bate.

Quando o aluno faz a atualização de uma formação, a formação nova e a velha aparecem juntas no certificado como se fossem duas formações diferentes (a duas juntas no certificado geral passam uma ideia de "encher linguiça" ) acredito que a formação antiga deveria ser substituída pela formação nova, para sair essa sensação de duplicidade.

segue meu certificado como exemplo:
https://cursos.alura.com.br/user/rafaelmatthes/fullCertificate/8bf06970c61c2fb09e077a41b7e840ac

**Comment by andradeisadora** [comment]
Oi @RafaelMatthes obrigada por avisar!
Fizemos recentemente essa atualização no certificado e deve ter ficado algum bug, vou passar para o time responsável.

Abraço e bons estudos :)

**Comment by wandersonmaceds** [comment]
Oi @RafaelMatthes tudo bem? Você está certo de que realmente passa a impressão de "encher linguiça", mas não entendi a parte sobre a contagem não bater (pode explicar melhor?). Digo isso por que testamos vários casos e a contagem batia por que a gente subtrai ou soma a carga horária total da formação. Claro, pode ser um caso específico, ai queria entender melhor.

O certificado completo considera o certificado da formação, então, se você observar no seu perfil, você possui dois certificados da formação python com carga horárias diferentes apesar haver cursos repetidos. Outro item que confere a unicidade do certificado é a url única que valida o certificado (aquela url no final do certificado). 

Concordo com você, tá estranho e a gente precisa ajustar e sinalizar a formação antiga de alguma forma... Obrigado pela mensagem...

Bons estudos! :)

**Comment by RafaelMatthes** [comment]
> Oi @RafaelMatthes tudo bem? Você está certo de que realmente passa a impressão de "encher linguiça", mas não entendi a parte sobre a contagem não bater (pode explicar melhor?). Digo isso por que testamos vários casos e a contagem batia por que a gente subtrai ou soma a carga horária total da formação. Claro, pode ser um caso específico, ai queria entender melhor.
> 
> O certificado completo considera o certificado da formação, então, se você observar no seu perfil, você possui dois certificados da formação python com carga horárias diferentes apesar haver cursos repetidos. Outro item que confere a unicidade do certificado é a url única que valida o certificado (aquela url no final do certificado). 
> 
> Concordo com você, tá estranho e a gente precisa ajustar e sinalizar a formação antiga de alguma forma... Obrigado pela mensagem...
> 
> Bons estudos! :) 

Oi wanderson.

Se você ocultar todas as formações ( cada formação subtrai a carga horária lá do somatório ) a carga horária  dos cursos avulsos fica errada... acho que as formações "duplicadas" estão impactando nessa subtração.

Esse certificado geral é legal para usar no currículo, mas acho que pode acabar passando uma ideia confusa ao recrutador que acessar esse link.

**Comment by wandersonmaceds** [comment]
> > Oi @RafaelMatthes tudo bem? Você está certo de que realmente passa a impressão de "encher linguiça", mas não entendi a parte sobre a contagem não bater (pode explicar melhor?). Digo isso por que testamos vários casos e a contagem batia por que a gente subtrai ou soma a carga horária total da formação. Claro, pode ser um caso específico, ai queria entender melhor.
> > O certificado completo considera o certificado da formação, então, se você observar no seu perfil, você possui dois certificados da formação python com carga horárias diferentes apesar haver cursos repetidos. Outro item que confere a unicidade do certificado é a url única que valida o certificado (aquela url no final do certificado).
> > Concordo com você, tá estranho e a gente precisa ajustar e sinalizar a formação antiga de alguma forma... Obrigado pela mensagem...
> > Bons estudos! :)
> 
> Oi wanderson.
> 
> Se você ocultar todas as formações ( cada formação subtrai a carga horária lá do somatório ) a carga horária dos cursos avulsos fica errada... acho que as formações "duplicadas" estão impactando nessa subtração.
> 
> Esse certificado geral é legal para usar no currículo, mas acho que pode acabar passando uma ideia confusa ao recrutador que acessar esse link.

Entendi, vou tentar replicar aqui com outros casos também. Obrigado.

**Comment by RafaelMatthes** [comment]
fiz um print 👍  nete caso, todas as formações estão "ocultas"

![image](https://user-images.githubusercontent.com/42219515/127907470-f239398b-d33d-4c14-8bef-f6d9024c46ca.png)

**Comment by wandersonmaceds** [comment]
Oi @RafaelMatthes, tudo bem? Demorei um pouco, mas já temos uma correção implementada que resolve esse problema, nas nossas investigações, descobrimos que havia outro problema que acontece com outro grupo específico de alunos, nossa correção acabou resolvendo as duas questões. 

Obrigado por nos apontar o problema aqui, caso encontre algo mais, por favor, nos avise :) 
Eu, ou outra pessoa avisará aqui quando a correção for lançada.

**Comment by RafaelMatthes** [comment]
@wandersonmaceds  Show ! Pode deixa, se eu encontrar algo, eu aviso.

**Comment by andradeisadora** [comment]
Fechando a issue mas podem voltar a comentar se quiserem :)
