### ISSUE TITLE
Redirecionamento errado, notificação

### ISSUE THREAD

**Issue by felipeyamane** [caelum/alura-funcionalidades#519]
Acabei de me matricular na Alura e me deparei com um pequeno bug na notificação de sobre atualização de dados para nota fiscal. Ao clicar na notificação foi redirecionado para a  tela de [Editar Perfil](https://cursos.alura.com.br/my_profile), sendo que os dados que precisam sofre atualização estão na tela de [Minha Matrícula.](https://cursos.alura.com.br/user/payments)

**Comment by laisgalvaos** [comment]
Olá @felipeyamane !
Obrigada por nos sinalizar! Ajustamos essa página recentemente e acho que foi colocado o link antigo, vou sinalizar já nossa equipe!

Ótimos estudos!

**Comment by designernatan** [comment]
corrigido, valeu felipe!

fechando aqui mas podem comentar depois mesmo com ela fechada
