### ISSUE TITLE
Codigo Fonte para estudo

### ISSUE THREAD

**Issue by KingNinhoCode** [caelum/alura-funcionalidades#52]

**Comment by designernatan** [comment]
oi @KingNinhoCode 

pode explicar mais ou a issue 'certa' é [essa outra aqui](https://github.com/caelum/alura-funcionalidades/issues/53)?

**Comment by KingNinhoCode** [comment]
hey @designernatan 

eu me atrapalhei e mandei essa sem querer, isso mesmo

**Comment by designernatan** [comment]
[issue original](https://github.com/caelum/alura-funcionalidades/issues/53)
