### ISSUE TITLE
Modificar modo para gerar certificados

### ISSUE THREAD

**Issue by lorrannecas** [caelum/alura-funcionalidades#520]
---
Certificados com cursos pré-selecionados

Resumo: Acrescentar algum outro modo para gerar certificado.

title: 'Certificado com cursos pré-selecionados'
---

- Acrescentar algum outro modo para gerar certificado, onde o usuário possa **selecionar quais cursos concluídos** ele quer que apareça no certificado, para melhorar a integração de postagem no Linkedin. 
- Um modo de gerar certificado por formação e não apenas por curso. 
Por exemplo: 1 - Gerar um certificado apenas de formação de ADM de redes, contendo todos os cursos dentro dessa categoria;

O modo gerar certificado completo as vezes vem com alguns cursos que **não quero que apareça naquele momento**.

**Comment by andradeisadora** [comment]
oi @lorrannecas, recentemente entrou uma melhoria no certificado completo e agora você pode ocultar formações inteiras que não quer que apareçam no certificado completo. Dá uma olhadinha lá :)

abraço e bons estudos!

**Comment by andradeisadora** [comment]
Fechando a issue mas pode voltar a comentar se quiser :)
