### ISSUE TITLE
Favoritar uma seção específica de um curso

### ISSUE THREAD

**Issue by duarch** [caelum/alura-funcionalidades#521]
Seria interessante se pudéssemos favoritar em seções específicas de um curso, isso facilitaria encontramos algo que gostaríamos de revisitar mais tarde, ou algum conhecimento que achamos relevante levar gravar. 

Poderia ser um simples icone 🔖 or ❤️ e uma opção para navegarmos por eles.

Obs. O caderno poderia ser usado pra isso se ele marcasse uma tag na sessão que estivermos incluindo o conteúdo. Semelhante as tags que tem nos fóruns `task/number`
`https://unibb.alura.com.br/course/web-scraping-data-science-python/task/61711`

**Comment by laisgalvaos** [comment]
Olá @duarch, acho sua sugestão super válida e entendo que facilita o acompanhamento de conteúdo, no entanto, numa avaliação prévia em termos de desenvolvimento e banco de dados é uma funcionalidade que exige bastante. Vamos continuar acompanhando se essa demanda surge mais entre os alunos, mas por hora não está no radar.

Bons estudos para você!

**Comment by andradeisadora** [comment]
Fechando a issue mas podem voltar a comentar se quiserem :)
