### ISSUE TITLE
Alert de "voce quer mesmo sair da pagina" no forum

### ISSUE THREAD

**Issue by luigiMinardi** [caelum/alura-funcionalidades#522]
Tava escrevendo uma resposta no forum, dei miss-click e entrei no perfil do usuario que estava perguntando, obviamente ao voltar pra minha mensagem ela não estava mais lá.

Por isso peço pra de duas uma, ou colocar um alertzinho simples pra impedir a pessoa de sair da pagina se ela tiver escrito algo ou então salvar a mensagem que você estava escrevendo em cache pra você não perder ela e se frustrar.

**Comment by andradeisadora** [comment]
Oi @luigiMinardi 
A primeira sugestao parece ser mais rapida de conseguirmos resolver num futuro próximo. Obrigada por nos avisar!

Abraço e bons estudos :)

**Comment by designernatan** [comment]
simples e eficaz, vamos tentar puxar daqui umas semanas junto com outra melhoria no forum

valeu luigi!

**Comment by designernatan** [comment]
luigi, acabei de ver que o time subiu a melhoria (fui responder no fórum e fechei sem querer mas fui salvo hahha)

bons estudos!
