### ISSUE TITLE
Teste de nível de conhecimento nas Formações

### ISSUE THREAD

**Issue by KenadAraujo** [caelum/alura-funcionalidades#523]
Recentemente assumi um novo cargo em uma empresa que tem a assinatura da Alura para funcionários, apesar de já ter uma certa experiência em Java, meu gerente me indicou fazer uma trilha padrão para ambientação na Stack da empresa, por ser genérica e obrigatória, eu tive que fazer os cursos básicos de conhecimento que já tinha para completar a tarefa. 

A minha sugestão é que houvesse uma prova nas formações, para identificar o nível de conhecimento do usuário e concluir os cursos para o qual o aluno já tem o conhecimento, como se fosse uma avaliação de nivelamento, para que poupe tempo dos devs que já tem alguma experiência

**Comment by laisgalvaos** [comment]
Olá @KenadAraujo, sua sugestão é bem relevante e já temos muitas discussões acontecendo nesse sentido na Alura. Como é um projeto de porte grande que vai impactar vários fluxos na plataforma toda, não tenho uma previsão de quando ele vai sair do papel, mas com certeza estamos olhando para isso. Vou tagear sua sugestão aqui para acompanharmos. Se tiver alguma novidade nesse sentido, volto para contar. 
Por hora a sugestão é você dar uma olhada nos exercícios antes mesmo de ver as aulas, assim você já sabe se é um conhecimento que você já sabe ou não e aí acelerar o vídeos vídeos daqueles que você já sabe. Pelo menos agiliza esse começo que você já domina.

Bons estudos!

**Comment by karlgama** [comment]
legal que vocês tenham essa ideia, se vale de algo a plataforma pluralsight, faz algo nesse sentido no começo dos paths deles, pode dar uma ideia para vocês de como implementar

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
