### ISSUE TITLE
Usar tema do dispositivo

### ISSUE THREAD

**Issue by rafael-b-g** [caelum/alura-funcionalidades#524]
Quando estiver nas página dos cursos, pegar o tema do dispositivo do usuário. Isso poderia evitar bastante aquele 'choque' quando se alterna de uma janela no tema escuro para uma janela no tema claro.

**Comment by laisgalvaos** [comment]
Olá @rafael-b-g ótima pontuação! A configuração de tema escuro/claro é uma das issues mais pedidas por aqui e inclusive já está no nosso radar, só não tenho ainda uma previsão de quando será implementada.
Por enquanto, você pode aplicar você mesmo seguindo esse [tutorial](https://github.com/caelum/alura-funcionalidades/issues/156#issuecomment-632410492)

**Comment by rafael-b-g** [comment]
@laisgalvaos Ah, que ótimo, Obrigado.

**Comment by laisgalvaos** [comment]
Espero que ajude até chegar a novidade na Alura! 
Bons estudos!@rafael-b-g

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
