### ISSUE TITLE
Ação do botão do meio do mouse

### ISSUE THREAD

**Issue by brunortoniolo** [caelum/alura-funcionalidades#525]
Ao clicar com o botão do meio do mouse em algum post, podcast, ou outra mídia a mesma não fica marcada como "finalizada". Apenas quando clicado com o botão esquerdo.

**Comment by andradeisadora** [comment]
oi @brunortoniolo pode explicar melhor o que está acontecendo? o botão do meio você está falando o scroll do mouse?

**Comment by brunortoniolo** [comment]
Isso, com o scroll do mouse que acontece isso.

**Comment by andradeisadora** [comment]
@brunortoniolo assim que conseguirmos vamos dar uma olhada, não consigo te prometer prazo ta?
enquanto isso tu pode usar o 'ctrl' + botão esquerdo do mouse, assim abre uma nova aba e a atividade marca como concluída.

abraço e bons estudos!

**Comment by designernatan** [comment]
oi pessoal, fechando a issue mas podem comentar mesmo com ela fechada :)
