### ISSUE TITLE
Possibilidade de marcar um vídeo como favorito.

### ISSUE THREAD

**Issue by raloliver** [caelum/alura-funcionalidades#526]
Eu como assinante, gostaria que cada vídeo tivesse a opção de favoritar.

Os vídeos favoritados poderiam ser acessados atráves da página do curso, ao lado do botão "Outras Ações". 
Ao clicar para ver o curso, é realizado um filtro e na página onde são listadas as aulas do curso, devem ser exibidos apenas os vídeos favoritados daquele curso.

**Comment by laisgalvaos** [comment]
Olá @raloliver interessante sua sugestão. Precisamos investigar se há outros alunos com essa demanda para avaliar.
Por hora, se desejar, poderia me explicar mais sobre sua motivação para favoritar esses vídeos? Apenas para entender seu processo e o que você espera.

Ótimos estudos!

**Comment by raloliver** [comment]
@laisgalvaos a motivação maior é para quando quiser revisar o conteúdo. Com as aulas salvas, consigo apenas ver o que de fato eu marquei na primeira vez que assisti como mais importante.

**Comment by raloliver** [comment]
@laisgalvaos a motivação maior é para quando quiser rever o conteúdo. Com as aulas salvas, consigo apenas ver o que de fato eu marquei como mais importante na primeira vez que assisti.

**Comment by LeonardoWons** [comment]
achei uma ideia boa e faz bastante sentido, pra nao perder tempo procurando algo, daria pra favoritar o video e colocar tipo uma marcação de tempo com um titulo
EX: video fav: loop / void de uma programação, 3:20(Loop) 10:40(void) ou algo assim

**Comment by raloliver** [comment]
@Le0nard0W0ns da um joinha que vai que eles colocam isso mais acima nos cards?

**Comment by designernatan** [comment]
oi pessoal, fechando a issue mas podem comentar mesmo com ela fechada :)

essa é bem puxada mas vamos discutir isso quando pegarmos a tela de aula para a melhorarmos
