### ISSUE TITLE
Problema de carregamento no Vídeo

### ISSUE THREAD

**Issue by Spaceliel** [caelum/alura-funcionalidades#527]
Faz mais ou menos um mês que vejo um problema que ocorre todos os dias quando eu estou assistindo as aulas, se ficar 10 min com a aba aberta do vídeo da aula, ele trava e não  volta mais, ai tenho que dar reload na página para continua o vídeo.

**Comment by andradeisadora** [comment]
oi @Spaceliel obrigada por avisar!
passei pro time responsável e assim que possível vão ver o que está acontecendo

abraço e bons estudos :)

**Comment by designernatan** [comment]
oi pessoal, fechando a issue mas podem comentar mesmo com ela fechada :)
