### ISSUE TITLE
Manter os vídeos em fullscreen quando a funcionalidade a autoplay estiver ativa e ocorrer mudança de página

### ISSUE THREAD

**Issue by luizcesaralmeida** [caelum/alura-funcionalidades#528]
---
name: Manter os vídeos em fullscreen quando a funcionalidade a autoplay estiver ativada e ocorrer mudança de página para o próximo vídeo.
about: Hoje quando ocorre uma mudança de página para o próximo vídeo (função de autoplay ativada) a reprodução sai do modo fullscreen.
title: ''
labels: 'autoplay '
assignees: ''

---

**Comment by laisgalvaos** [comment]
Olá @luizcesaralmeida, sua sugestão é bem pertinente e está no radar pois essa questão já surgiu algumas vezes, mas mais pra um futuro a longo prazo, tudo bem?

Abrç
Ótimos estudos!

**Comment by designernatan** [comment]
oi pessoal, fechando a issue mas podem comentar mesmo com ela fechada :)
