### ISSUE TITLE
Integração automatica com o git da mesma forma que com o linkedin

### ISSUE THREAD

**Issue by karlgama** [caelum/alura-funcionalidades#529]
Para terem uma ideia do que estou falando deem uma olhada no meu REAME de perfil https://github.com/karlgama, nele eu adiciono os certificados que tenho vocês já implantaram isso no linkedin o que é ótimo, se tivesse uma forma de fazer algo similar com o git ou mesmo se vocês fornecessem algum script pra fazer isso ia ser show, porque é legal colocar isso no github também, não se em actions seria implementar isso mas enfim e uma ideia interessante tendo em vista que muitos recrutadores gostam de olhar o git e para não poluir tanto o currículo é interessante não deixar muitos certificados com link no currículo. Mas fazer isso no giuthub é tranquilo porque dá para "esconder" o endereço todo kkk.

**Comment by laisgalvaos** [comment]
Olá @karlgama, obrigada pela sugestão. por enquanto não temos previsão para essa questão, mas você pode tentar aproveitar nossa API para dashboard que fica dentro do "Editar perfil" rolando a tela até o fim.
Olha, tem uma outra [issue](https://github.com/caelum/alura-funcionalidades/issues/492) que explica o funcionamento da API, não é exatamente o mesmo caso, mas para você ter uma ideia das possibilidades.
Ótimos estudos!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
