### ISSUE TITLE
Código de exemplo para estudo

### ISSUE THREAD

**Issue by KingNinhoCode** [caelum/alura-funcionalidades#53]
Caso fosse disponibilizado uma parte do site onde houvessem códigos fontes de paginas ou apps fictícios iria ajudar muito no aprendizado.
Acontece que ler código é uma parte fundamental de aprender, mas pesquisando na internet só se acha implementações muito simples ou complexas demais. Dessa forma os alunos tendem a se sentir ilhados entre o mundo real da programação e o que aprendem no curso.

**Comment by designernatan** [comment]
oi @KingNinhoCode valeu pela sugestao

a ideia é que todos os cursos da alura já tenham esses projetos, inclusive no final dos cursos é disponibilizado o projeto versão final, me fala mais do que voce sente falta nessa abordagem?

pegando de exemplo meu curso de sass onde fazemos uma refatoração de CSS do zero e ao mesmo vou ensinando a ferramenta

talvez algo maior como o [HackerRank](https://www.hackerrank.com) com desafios? Muitos cursos possuem desafios tbm

**Comment by KingNinhoCode** [comment]
E ai @designernatan 

sim, o alura tem esses projetos de curso que são otimos na minha opinião, é muito bom ver ele avançando até alcançar o final do curso, o problema não é com essa mecânica

estou sugerindo algo separado do curso em si, uma biblioteca com codigos de exemplo para podermos melhorar nossa leitura numa linguagem nova, lendo um codigo que não fomos nos que escrevemos, ao contrario do projeto de curso.

Explicando melhor, busquei usar a estratégia de ler a fonte de algumas paginas web para treinar, mas infelizmente uma pagina real não é um bom lugar para um iniciante. A quantidade de links, meta tags e complexibilidade geral do site torna essa tarefa confusa e ineficiente sabe?

(sou novo aqui então perdão por qualquer erro na formatação disso)

**Comment by designernatan** [comment]
oi @KingNinhoCode 

peguei agora!

passei para o time de conteúdo dos cursos para ver com os(as) instrutores(as) de tentar colocar mais "para saber mais" mais exemplos de código como voce mencionou

faz sentido ao meu ver para cursos mais avancados, pois nos basicos ja é tanta informacao nova que pode assustar quem ta vendo aquilo pela primeira vez

valeu pela sugestao meu caro!
