### ISSUE TITLE
Bug na inclusão de certificado no LinkedIn

### ISSUE THREAD

**Issue by felipeyamane** [caelum/alura-funcionalidades#530]
A plataforma está permitindo a inclusão de certificados a partir do perfil de outros usuários. Então ao acessar o perfil, seja pelo fórum, seja pelo ranking...etc. é possível clicar em adicionar ao linkedIn os certificados referentes aos cursos concluídos pelos outros usuários, já sendo até mesmo direcionado para o linkedIn para a adição no perfil. Ponto positivo, o link e o token do certificado permanecem as do usuário original que concluiu o curso. O gif abaixo demonstra o bug.

![Demonstração de Bug
![certificado](https://user-images.githubusercontent.com/19255532/129639843-3322a6b5-573f-4534-a6ac-3e73076db96b.gif)
](https://media.giphy.com/media/uHaQHxADCpSyngRRwM/giphy.gif)

**Comment by designernatan** [comment]
@felipeyamane valeu pelo toque!

comentei sobre isso aqui [nesse reply dessa thread](https://github.com/caelum/alura-funcionalidades/issues/479#issuecomment-861823026)

em suma, não é bug ou problema de segurança justamente pelos pontos que você puxou, ok?

abcs e bons estudos!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
