### ISSUE TITLE
checagem de Progresso 

### ISSUE THREAD

**Issue by LeonardoWons** [caelum/alura-funcionalidades#531]
Para melhorar o controle de desempenho diario, acho uma boa ideia colocar um ponto de onde voce começou o dia e de onde terminou. 

Uma coisa simples mas que pode funcionar muito bem, pode ser um button(começar o dia, exemplo de nome) que quando você clica, grava tudo  oque o usuario fez no dia( X aulas, X atividades, X tempo no conteudo, X podcasts, X perguntas no forum feitas e/ou respondidas e pra mim o mais importante, quantos % o curso tava e quantos ficou no final do dia)

Tendo isso, cada usuario pode settar uma "meta" diaria de conteudo, ou ate mesmo pra descanso(ex, dps de X % do curso quero que de um aviso). 

Acredito que o mesmo botão de iniciar pode finalizar e mostras as informaçoes que o usuario achar relevante em uma tabelinha ou grafico bem simples.

Espero ter ajudado e que de pra enteder 😅

**Comment by andradeisadora** [comment]
Oi @Le0nard0W0ns obrigada pela dica!
No momento estamos com outras tarefas com maior prioridade então estamos sem planos para implementação de um controle de desempenho. 
O que você pode fazer enquanto é ir documentando no notion o seu progresso e atividades feitas durante os dias, também pode ir acompanhando sua pontuação na plataforma pra ver que dias estudou ou não. Sobre as pausas de estudo, você conhece o pomodoro? da uma pesquisada, tem apps e até videos no youtube pra estudar junto com outras pessoas.

Abraço e bons estudos :)

**Comment by wandersonmaceds** [comment]
oi @Le0nard0W0ns não sei se ajudaria ter um botão que faz isso, me parece que você ainda teria que se comprometer a usar essa funcionalidade todos os dias. Algo que pode chegar perto de causar o mesmo impacto e ser um pouco mais simples é uma opção no seu perfil que indique que você quer receber estatísticas sobre seus estudos. Nesse caso, a plataforma poderia enviar pra você um e-mail com essas informações dentro de um período de tempo, semanal, mensal, etc...

É algo que o Duolingo faz, pra tentar fazer a pessoa equilibrar o tempo que tem estudado. 

Na prática, eu não sei se ajuda muito, mas eu pessoalmente gosto. Acho que é algo que podemos pensar pro futuro, estudar se faz sentido, se mais pessoas tem interesse nesse tipo de funcionalidade, etc... 

Faz sentido pra você?

**Comment by designernatan** [comment]
oi pessoal, fechando a issue mas podem comentar mesmo com ela fechada :)
