### ISSUE TITLE
Botão para reportar/denunciar tópicos no fórum

### ISSUE THREAD

**Issue by qualvalordex** [caelum/alura-funcionalidades#532]
Estava rodando alguns tópicos no fórum e me deparei com um tópico que tinha um conteúdo não apropriado pro contexto do fórum. Seria interessante que a plataforma disponibilizasse um botão para reportar/denunciar um tópico, para que a equipe possa agir rapidamente na remoção desse tipo de conteúdo.

**Comment by wandersonmaceds** [comment]
Olá @qualvalordex, acho que faz bastante sentido o que você sugere. Inclusive, não sei se tomou essa atitude de reportar diretamente por e-mail, isso chegou a ser feito? Acredito que por hora, seja a melhor alternativa para não gerar constrangimento público a pessoa em si. 

Faz sentido?

**Comment by andradeisadora** [comment]
Oi @qualvalordex você pode sempre reportar no atendimento@alura.com.br 
São raros os casos de comentários inapropriados nesses anos do fórum e enviando por email evitamos o que o @wandersonmaceds falou sobre gerar constrangimento.

Abraço e bons estudos!

**Comment by qualvalordex** [comment]
@wandersonmaceds não reportei por e-mail pois não sabia que existia esse canal. Acho que precisa ficar mais evidente que existe um canal pra esse tipo de report. A ideia do botão pode ser uma via para isso, inclusive. Podem existir ações silenciosas quanto a isso também, como já existe em outros fóruns. Por exemplo, ao clicar no botão de report, eu preencho algumas informações básicas para facilitar a investigação e aquele comentário/postagem fica oculto apenas para mim. Quando for feita a investigação e tomada a decisão, o comentário é removido e o usuário notificado.

Vou reportar o tópico por e-mail @andradeisadora, obrigado por avisar.

PS: aparentemente o tópico já foi encerrado.

**Comment by wandersonmaceds** [comment]
@qualvalordex na dúvida, pode sempre mandar um e-mail pro pessoal do atendimento ou mesmo o de contato, eles podem direcionar pra equipe correta internamente.

**Comment by designernatan** [comment]
oi pessoal, fechando a issue mas podem comentar mesmo com ela fechada :)

edit:
apenas complementando: temos um time grande em cima das nossas comunidades no forum e discords (challenges), eventualmente alguem pega esse tipo de coisa tbm
