### ISSUE TITLE
Cursos "Atômicos"

### ISSUE THREAD

**Issue by Noriller** [caelum/alura-funcionalidades#533]
Queria aprender sobre streams no JS e achei um: "NodeJS: Streaming de dados e Repositório", ótimo. Mas qual não foi minha decepção quando só o primeiro "capítulo" era do assunto e o resto era outra coisa...

Assim como quando a gente faz um código mais limpo... assuntos separados deveriam estar em lugares separados, mesmo que seja uma linha de código, ou no caso... um capítulo.

O Alura+ já resolve isso... em partes, porque é só uma pasta "outros" onde jogam tudo o que não se encaixa ou foi feito depois.

Formações são ótimos lugares pra começar, porque são uma grande pasta de cursos, videos, artigos e outros.
Acho que seria o caso de haver uma nova "pasta" pra colocar as coisas, tipo um curso, só que diferente.

Dentro das formações que englobariam o "todo", já tem o "passo a passo", mas poderiam ser quebrados e/ou então adicionado subitens para que haja detalhamento melhor (o próprio conteúdo de cursos no nível de capítulos poderia ser espalhado neles). 
Então, estes subitens poderiam inclusive ser mostrados dentro de pesquisas, porque ao invés de ter que ir dentro do curso e passar por ele inteiro pra saber que era "só aquilo" mesmo... se já houvesse esse tipo de organização já seria possível ver só o que interessa no momento.

**Comment by designernatan** [comment]
@Noriller valeu pela sugestao!

ideia do alura+ é resolver isso mesmo: muita assunto é curto demais pra fazer um curso

essa 'pasta' pessoal hoje vc pode criar um plano de estudos (apenas conteudos e cursos inteiros, aulas e videos soltos de cursos nao)

inclusive estamos vendo algo nesse momento pra ajudar um pouco nessa parte de discovery de conteudo, alem dos filtros na busca que foi feito ha poucas semanas

abracao!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
