### ISSUE TITLE
Barra de progresso do vídeo no player Picture-in-Picture

### ISSUE THREAD

**Issue by Vitormartins12** [caelum/alura-funcionalidades#534]
**Funcionalidade**
Quando usamos aquele botão "Picture-in-Picture" do player das aulas, o "quadro" torna-se uma telinha que pode ser movida ao longo da tela, o que é muito bom para quem usa diversas janelas abertas ao mesmo tempo.

**Problema** 
O player é muito simples, só tendo a função de Play/Pause e o botão para voltar a janela para o modo "acoplado". Me vejo fazendo essa troca algumas vezes, quando preciso "voltar um pouco" no vídeo para pegar novamente alguma explicação, tendo que voltar depois para o modo "Picture-in-Picture".

**Sugestão**
Colocar ali também os controles da barra de progresso, para que a gente consiga clicar e ir para qualquer posição do vídeo.

**Print da tela**
![image](https://user-images.githubusercontent.com/14200647/131127932-c3a479e6-4e3c-4575-b30f-f6f410457ee9.png)

**Comment by designernatan** [comment]
@Vitormartins12 valeu pela sugestao!

o PiP depende do browser e sistema operacional, estou usando windows+opera e ele fica desse jeito
![image](https://user-images.githubusercontent.com/5431347/131134336-583d1fc6-6867-4fa3-948f-b1f55734077d.png)

**Comment by marco-filho** [comment]
Tem essa extensão pra chrome que pode ajudar com atalhos. Não conheço outras opções, mas devem existir.

- [x] https://chrome.google.com/webstore/detail/global-speed/jpbjcnkcffbooppibceonlgknpkniiff?hl=en

**Comment by Vitormartins12** [comment]
@designernatan no meu caso foi usando o PopOs 20.04 e o Chrome.

Vou buscar outras alternativas de navegador, obrigado pela dica!

**Comment by Vitormartins12** [comment]
> Tem essa extensão pra chrome que pode ajudar com atalhos. Não conheço outras opções, mas devem existir.
> 
> * [x]  https://chrome.google.com/webstore/detail/global-speed/jpbjcnkcffbooppibceonlgknpkniiff?hl=en

bem legal a extensão, mas ainda não traz a barra de progresso. obrigado pela dica!

**Comment by designernatan** [comment]
oi pessoal, fechando a issue mas podem comentar depois mesmo com ela fechada :)
