### ISSUE TITLE
Possibilidade de adicionar Alura+, Posts e Podcasts pros planos de estudos

### ISSUE THREAD

**Issue by marco-filho** [caelum/alura-funcionalidades#535]
Se possível até uma divisão de módulos, semelhante às formações. Talvez até ajudaria a entender melhor o que a comunidade quer e, consequentemente, aprimorar a manutenção/criação das formações.

Entendo que adicionar links pro YouTube seria problemático, então disso nem faço questão.

**Comment by designernatan** [comment]
@marco-filho valeu pela sugestao!

mapeamos um update pro PDEs e modulos (igual formacoes) está na pauta

de curiosidade, qual dos seus planos que voce sentiu essa necessidade e pq?

---

opa, hoje vc consegue adicionar videos e qualquer link, soh colar a URL lá

abracao!

**Comment by marco-filho** [comment]
> hoje vc consegue adicionar videos e qualquer link

Sabia não, muito obrigado!

> qual dos seus planos que voce sentiu essa necessidade e pq?

Nenhum específico, só gosto de poder organizar bem minha área de estudo 😄

**Comment by andradeisadora** [comment]
oi pessoal! estou fechando a issue mas podem voltar a comentar se quiserem :)
