### ISSUE TITLE
Progresso dos planos de estudo em tempo/horas

### ISSUE THREAD

**Issue by viniciustsantos** [caelum/alura-funcionalidades#536]
Ao consultar a lista de planos de estudos, já temos uma visão geral do andamento dos planos com relação à quantidade de cursos já realizados, conforme a imagem:
![image](https://user-images.githubusercontent.com/12686202/131747245-e6ce51c1-1a35-47e6-9886-4a2078410f22.png)

Podem incluir também nesta visão o valor de horas já realizadas e horas a realizar, assim para quem tem diversas formações no seu dashboard pode dar prioridade para aquela que está faltando menos horas de dedicação.

Ao consultar o plano é possível visualizar o total de horas do plano, ali também pode apresentar a quantidade de horas já realizadas ou as que faltam, ao lado do total, nessa parte:
![image](https://user-images.githubusercontent.com/12686202/131747564-d0a38292-d7b4-4fa5-b6ef-dea6f037bcf3.png)

Já estava esquecendo, poderiam também incluir no cálculo de horas o tempo gasto nos itens que não são os cursos, como podcasts, leituras, etc.

Espero que gostem da sugestão de funcionalidade.

Abraço,

Vinicius

**Comment by designernatan** [comment]
@viniciustsantos valeu pela sugestao!

lembro que alguem sugeriu algo parecido ha uns tempos, quando pegarmos os cards e paginas relacionadas aos planos de estudos vamos discutir em cima

uma pergunta ja pra ir "matutando" aqui: por qual motivo a qtde de horas (gastas e restantes) é interessante pra voce?

abração!

**Comment by viniciustsantos** [comment]
> 
> 
> @viniciustsantos valeu pela sugestao!
> 
> lembro que alguem sugeriu algo parecido ha uns tempos, quando pegarmos os cards e paginas relacionadas aos planos de estudos vamos discutir em cima
> 
> uma pergunta ja pra ir "matutando" aqui: por qual motivo a qtde de horas (gastas e restantes) é interessante pra voce?
> 
> abração!

A quantidade de horas é interessante para avaliar dentre os diversos planos quais necessitam de menos tempo para concluir e que por vezes não estamos reparando, uma vez que a quantidade de horas pode variar bastante de curso para curso. Por exemplo, se tenho duas formações em andamento, supondo que as duas tenham a mesma relevância para mim, em uma delas tem apenas 3 cursos que totalizam 36 horas e outra tem 6 cursos, mas estes 6 cursos totalizam 12 horas, o fator tempo pode ser mais prático para decidir qual concluir do que a quantidade de cursos apresentada.

Espero que tenha contribuído, abraços!

**Comment by andradeisadora** [comment]
oi pessoal! estou fechando a issue mas podem voltar a comentar se quiserem :)
