### ISSUE TITLE
Ampliar opção de tópicos no Fórum (dúvidas e contribuições ou reflexões)

### ISSUE THREAD

**Issue by SaraSantedicola** [caelum/alura-funcionalidades#537]
Galera, pela segunda vez me sinto impelida a fazer uma postagem no Fórum e travo pela abundância de referência a DÚVIDA. 

Sei que é importante que o Fórum seja um espaço para acolher dúvidas e elas devem ser tratadas especialmente, mas será que rola do autor poder designar o tipo de postagem, se é dúvida ou reflexão, por exemplo, de modo a facilitar contribuições que não visam a obter maior esclarecimento mas sim compartilhar algo que o aluno considere relevante? 

Por exemplo, as duas vezes em que travei, queria comentar sobre um livro/artigo interessante que já li sobre o curso/tema mas fiquei intimidada com o vocabulário no Fórum ser tão direcionador a dúvida.

Vale sinalizar que os professores em sua maioria verbalizam o estímulo ao uso do Fórum de maneira ampla, não só ligada a dúvidas.

Acredito que isso pode aumentar o engajamento/riqueza no Fórum. Tks!

**Comment by designernatan** [comment]
@SaraSantedicola obrigado pela sugestão

está no radar para discutirmos no futuro algo que ajude nisso

não consigo te passar nenhuma data, mas qualquer novidade aparecerá no fórum ou avisamos por aqui tudo bem

abracos!

**Comment by andradeisadora** [comment]
oi pessoal! estou fechando a issue mas podem voltar a comentar se quiserem :)
