### ISSUE TITLE
Ter uma sessão somente com exercícios 

### ISSUE THREAD

**Issue by sammartins2** [caelum/alura-funcionalidades#538]
Seria muito interessante e ajudaria bem mais a praticar, na parte de meu aprendizado,ter uma parte só de exercícios, , de acordo com o que você esta estudando iria abrindo novos exercícios .

Eu poderia escolher exercícios de acordo com  o que eu já tinha estudado, vocês poderiam colocar no próprio Alura, uma plataforma como se fosse o VS code.

acredito eu que para você se tornar um programador, exige pratica, então com uma sessão só de exercícios, iria deixar a gente com menos medo do mercado de trabalho, menos inseguro.

**Comment by designernatan** [comment]
@sammartins2 valeu pela sugestao!

essa eu pessoalmente gosto bastante, mas é bem grande

pra nao te deixar na mao, pedi ajuda pro time de dev aqui e recomendaram esses sites para praticar:

- [Hacker Rank](https://www.hackerrank.com)
- [LeetCode](https://leetcode.com/)
- [URI](https://www.urionlinejudge.com.br/judge/en/login)

**Comment by andradeisadora** [comment]
oi pessoal! estou fechando a issue mas podem voltar a comentar se quiserem :)
