### ISSUE TITLE
Um compilador para acompanhamento das atividades e execícios  .

### ISSUE THREAD

**Issue by lucasricardo28** [caelum/alura-funcionalidades#539]
Quem sabe, ao invés de "perder tempo" instalando, poderíamos ter compiladores na plataforma.
Quem sabe poderia existir uma opção de **tenho instalado** ou quero **instalar**. 
Estou estudando JAVA e tenho os requisitos necessários para rodar o teste. Toda hora o instrutor pede para fazer testes para melhor aprendizado.
Mas se eu tivesse um compilador e que eu já de cara pudesse testar meu códigos ali, seria muito bom. 
Lembrando que é apenas um compilador, não uma IDE ... O intuito seria poder executar meus códigos e praticar .
Poderia quem sabe ter uma área de mais teste, testes avançados e prática de outros exercícios .

**Comment by designernatan** [comment]
@lucasricardo28 valeu pela sugestao!

a gente sempre tenta aproximar o ensino do mundo real, ainda vale o que [o paulo comentou aqui nessa outra issue](https://github.com/caelum/alura-funcionalidades/issues/108) tudo bem?


abracao!

**Comment by andradeisadora** [comment]
oi pessoal! estou fechando a issue mas podem voltar a comentar se quiserem :)
