### ISSUE TITLE
Certificados por carreira concluía ou por cursos concluídos na carreira

### ISSUE THREAD

**Issue by hvivox** [caelum/alura-funcionalidades#54]
Olá, atualmente me candidatei a tenente das forças armadas, no edital da vaga que concorri solicitava a apresentação de certificados com carga horária de 40, 60, 80, 100 e 120 horas para pontuação, além disso o certificado apresentado deveria ter a descrição dos tópicos ministrados durante o curso. Os certificados com Carga Horária inferior a mencionada não seriam considerados.

Não pode apresentar os cursos ministrados na alura pois tem até 12H de duração. Dessa forma solicito a implementação de funcionalidade para impressão de Certificado por Carreira para somar a C.H de cada Curso finalizado em determinada carreira, esse certificado deverá apresentar no verso os tópicos ministrados no curso. 

Qualquer esclarecimento estou a disposição basta me encaminhar um email: hvivox@hotmail.com

**Comment by designernatan** [comment]
oi @hvivox, você precisa de um certificado da formação que conste não só os cursos mas seus respectivos tópicos, é isso mesmo?

como sao casos bem pontuais dessa necessidade num curto/médio prazo complica para fazermos disso uma funcionalidade na plataforma

**porém** é possível pedir algo assim no contato@alura.com.br e o pessoal de customer success consegue isso para você

no email contando seu caso, cite da necessidade de uma **declaração de conclusão** e comente que precisa dos tópicos de cada curso nessa declaração também, ok?
