### ISSUE TITLE
Guia de profundidade/dificuldade da leitura

### ISSUE THREAD

**Issue by ElDuduardo** [caelum/alura-funcionalidades#540]
Uma coisa que pensei enquanto estava lendo um post.

Dentro das formações existe texto de blogs para serem lidos, uma coisa que poderia ajudar bastante a orientar e preparar para leitura é uma etiqueta dizendo a dificuldade da leitura daquele texto ao lado no nome.

Digo isso pois estou fazendo a formação de "Front-end" e vários textos ali são BEM densos e não há indicativo nenhum disso, seria interessante uma informação de "Introdutório", "Intermediário", "Avançado", "Experiente" pois quando eu fosse ler iria mais preparado e quando fosse procurar por fora já saberia se o texto tende a atender ou não minha expectativa.

Me inspiro Academy Binance, pois quando comecei a estudar criptomoedas esses indicativos me ajudaram bastante.

**Comment by designernatan** [comment]
@ElDuduardo valeu pela sugestao!

fazíamos algo assim até no cursos, mas como avançado e básico é extremamente subjetivo pra cada um tínhamos muitos problemas com isso

e lembrando que vc pode sempre tirar dúvida no fórum quando achar que o post/video tá muito avançado/jedi/ninja :)

**Comment by andradeisadora** [comment]
oi pessoal! estou fechando a issue mas podem voltar a comentar se quiserem :)
