### ISSUE TITLE
Buscar cursos pelo nome do instrutor

### ISSUE THREAD

**Issue by FlavioAndre** [caelum/alura-funcionalidades#541]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

Ter uma opção na busca de cursos por instrutor, muitas vezes gostaria de ver todos os cursos que um determinado instrutor, pois normalmente um bom instrutor tem bons cursos, logo seria muito interessante ter essa funcionalidade na busca.

**Comment by designernatan** [comment]
@FlavioAndre valeu pela sugestao!

faz sentido algo assim sim! Vamos discutir em cima aqui!

de bate pronto oq vc pode fazer hoje é entrar no perfil do instrutor(a) na alura, descer um pouco, e ver todos os cursos dele ou dela ok?

abracos!

**Comment by designernatan** [comment]
@FlavioAndre pinguei o time aqui, tem outra forma direto na busca também:

https://cursos.alura.com.br/search?query=guilherme%20silveira&typeFilters=COURSE

**Comment by andradeisadora** [comment]
oi pessoal! estou fechando a issue mas podem voltar a comentar se quiserem :)
