### ISSUE TITLE
Bug de Tamanho de texto na tela de formações

### ISSUE THREAD

**Issue by Ivo-loop** [caelum/alura-funcionalidades#542]
ta olhando as formações e tem algumas com um titulo um pouco grande gerando um pequeno bug de sobre escrito no texto algo bem simples. segue a imagem:

![image](https://user-images.githubusercontent.com/53790303/132911031-aa31753c-6aa7-4b05-af94-fbb575e70665.png)

link da tela: https://cursos.alura.com.br/formacoes

Browser: Chrome Default 

zoom de tela: 100%

**Comment by designernatan** [comment]
@Ivo-loop opa valeu ivo, vamos dar uma olhada num futuro próximo!
