### ISSUE TITLE
Possibilidade de emissão de Certificado Completo personalizado

### ISSUE THREAD

**Issue by mauricio-zanatta** [caelum/alura-funcionalidades#543]
Olá pessoal da Alura.
Gostaria de sugerir uma funcionalidade no site, se possível.

Na página de "Perfil e Certificados" existe somente as opções de emitir o certificado dos cursos concluídos de forma individual (clicando no link "Certificado" de cada curso concluído) ou de forma geral (clicando no link "Você pode encontrar um certificado completo aqui" no final da página).

Seria interessante que tivesse a opção de emitir um certificado completo filtrando alguns cursos, seja por data de início ou data de finalização, permitindo emitir um certificado completo personalizado.

Motivo desta sugestão é que utilizo os cursos da Alura para Progressão por Capacitação no local onde trabalho (na esfera pública, talvez seja a situação de muitos outros alunos também), e temos uma regra que somente cursos acima de 20hs são considerados para a progressão.

Desta forma os certificados individuais de cada curso não me servem, pois na maioria deles a carga horário é abaixo de 20hs.
E como eu já apresentei a 1 ano atrás um certificado completo contendo os cursos feitos naquela época, hoje não consigo apresentar um novo certificado completo contendo somente os cursos que fiz desde então.

Seria muito útil se tivesse essa funcionalidade.
Se não for possível, gostaria de saber se existe outra forma que eu possa solicitar um certificado completo somente dos cursos concluídos este ano.

Obrigado pessoal, qualquer dúvida estou à disposição.
Atenciosamente,
Maurício Zanatta.

**Comment by designernatan** [comment]
@mauricio-zanatta valeu pela sugestao!

essa feature de ocultar formações é algo relativamente novo que ainda estamos entendendo o impacto e comportamentos esperados, legal que você trouxe essa dor específica sobre os cursos soltos

de bate-pronto, pinga direto no contato@alura.com.br que o time de CS vai poder te ajudar com isso, tudo bem?

abracao!

**Comment by mauricio-zanatta** [comment]
Ok Natan, pode deixar que quando concluir meus cursos vou solicitar via e-mail os certificados somente dos concluídos este ano.
Obrigado pela resposta, fica aí a sugestão.
Abraço.
