### ISSUE TITLE
Bug ao adicionar certificado de curso a partir do perfil de outro aluno

### ISSUE THREAD

**Issue by Mr-Saxobeat** [caelum/alura-funcionalidades#544]
Olá,

Verifiquei que, ao entrar no perfil de algum aluno e ver os cursos que a pessoa terminou, o botão de adicionar o certificado ao perfil no LinkedIn fica visível mesmo que eu não seja o "dono" do certificado. Ao clicar no botão, é aberta uma guia com meu perfil do LinkedIn pronto para adicionar o certificado ao meu perfil.

Este botão não deveria ficar visível apenas para o dono do perfil?

**Comment by designernatan** [comment]
@Mr-Saxobeat valeu pelo toque!

comentei sobre isso aqui [nesse reply dessa thread](https://github.com/caelum/alura-funcionalidades/issues/479#issuecomment-861823026)

em suma, não é bug ou problema de segurança justamente pois há uma autenticação mesmo se eu adicionar o certificado de outra pessoa

quando pegarmos a pg de perfil para a melhorarmos vamos discutir em cima pois assusta mesmo

abcs e bons estudos!

**Comment by Mr-Saxobeat** [comment]
Ah sim. Beleza então. 
Obrigado!
Abraço!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
