### ISSUE TITLE
Opção de mudança de plano do alura

### ISSUE THREAD

**Issue by ngemir** [caelum/alura-funcionalidades#545]
Penso que será uma boa opção poder renovar a assinatura com outro plano. Para poder ter mais liberdade para os estudantes de acordo com suas necessidades.

**Comment by designernatan** [comment]
@SwaveNg valeu pela sugestao!

estamos para discutir em cima disso, hoje rola você pingar no atendimento@alura.com.br e pedir essa mudança (tem algumas considerações, time vai saber falar melhor que eu sobre isso)

pode me resumir mesmo que por cima aqui do seu caso? Mais pra entender e ajudar a discussão aqui :)

abracao!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
