### ISSUE TITLE
Pesquisa por texto no fórum da Alura não contempla filtros selecionados

### ISSUE THREAD

**Issue by nivaldocavalcanti** [caelum/alura-funcionalidades#546]
Olá pessoal, tudo bem?

Caros, a pesquisa pelo campo de texto no forum do Alura não contempla os filtros por Categoria, Linguagem, Curso.

Por exemplo, estou no forum do curso de API REST com Spring Boot, os filtros para perguntas do fórum estão aplicados, a URL está montada corretamente (https://cursos.alura.com.br/forum/curso-spring-boot-api-rest/todos/1), porém ao realizar uma pesquisa utilizando o campo de texto (Ex.: validação) os filtros são removidos, sou redirecionado para outra URL (https://cursos.alura.com.br/forum/search?term=valida%C3%A7%C3%A3o) e o resultado da pesquisa é em todo o fórum da Alura e não no fórum da Categoria/Linguagem/Curso que eu já estava, misturando os assuntos e dificultando localizar com mais precisão o que estava tentando encontrar.

Sugiro que ao enviar o campo de texto/input text para a pesquisa, enviar também os filtros/select fileds da pesquisa. Agradeço se isso puder ser implementado/corrigido o quanto antes.

### Capturas de Tela
**No fórum do curso, digitei meu termo de pesquisa e cliquei no botão pesquisar**
![bug-no-forum-1](https://user-images.githubusercontent.com/26503469/134332266-fc63ed0f-9dde-4356-bfc1-f92e1df15cc2.png)

**Fui redirecionado para uma página diferente e sem os filtros e informações relevantes que haviam na página anterior**
![bug-no-forum-2](https://user-images.githubusercontent.com/26503469/134332275-113020c9-252c-43aa-9883-fb49b36ad951.png)

**Comment by designernatan** [comment]
@nivaldocavalcanti valeu pela sugestao!

está no nosso roadmap melhorarmos essa parte de busca no fórum no futuro, ok? 

há algumas semanas subimos os filtros somente na busca principal da plataforma

abcs e bons estudos!

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
