### ISSUE TITLE
Não tem certificados para Formação completa abrangendo tudo

### ISSUE THREAD

**Issue by Maksuedson** [caelum/alura-funcionalidades#547]
Boa noite!

Eu terminei a formação java de 130 horas, e não vi o certificado que abrange tudo, apenas certificados para cursos isolados.
esta seria a minha sugestão.

meu email é **maksuedson.silva@mirante.net.br**

**Comment by nirlan** [comment]
Na parte de 'Meus certificados', logo abaixo da seção que lista eles, tem uma link pra gerar um certificado completo único.

**Comment by designernatan** [comment]
maksuedson, como o nirlan disse tem essa opcao do certificado completo lá no seu perfil

inclusive tem a opcao de vc ocultar algumas formacoes ali tbm

---

fechando a issue mas podem comentar mesmo com ela fechada :)
