### ISSUE TITLE
Botão visível para cancelar ou pausar a inscrição de um curso

### ISSUE THREAD

**Issue by nirlan** [caelum/alura-funcionalidades#548]
Acharia interessante ter um botão mais claro e visível de cancelar ou pausar a inscrição de um curso. Eu demorei um tempo para descobrir que ele estava em outras ações rs :)

**Comment by designernatan** [comment]
@nirlan valeu pela sugestao!

em geral priorizamos a visiblidade desses elementos com o uso

certificado, cancelar e favoritar eram menos usados antes de mudarmos esta tela

**Comment by designernatan** [comment]
aproveitando nirian

qual curso você sentiu essa necessidade? Pausou ou saiu do curso?

abcs!

**Comment by nirlan** [comment]
Tranquilo :) eu entrei no curso de UX para mostrar pra minha esposa o conteúdo, se ela teria interesse em fazer.
Eu entrei no de email marketing também, mas preferi seguir a formação Front-end para ter uma base completa.

**Comment by designernatan** [comment]
show, valeu nirlan!

---

fechando a issue mas podem comentar mesmo com ela fechada :)
