### ISSUE TITLE
Barra de busca para podcasts

### ISSUE THREAD

**Issue by Victor-P-Martins** [caelum/alura-funcionalidades#549]
Seria interessante ter uma barra de pesquisa filtrada apenas para os podcasts. Eu entro pela plataforma>conteúdo>podcasts e quero pesquisar um podcast por determinado assunto por exemplo back end. Para isso eu preciso ir na pesquisa geral adicionar um filtro avançado selecionar o nome do podcast e ai ter os resultados.
Se tivesse uma barra de pesquisa já filtrada na página de cada podcast seria muito interessante.

**Comment by andradeisadora** [comment]
oi @Victor-P-Martins obrigada pela sugestão!
fizemos esse filtro na busca para filtrar melhor o tipo de conteúdo que os alunos buscam encontrar e dessa forma temos uma busca só com todo o conteúdo centralizado, ficando mais fácil de encontrar ela quando precisar.
se tivermos uma busca para cada conteúdo diferente pode ficar confuso para os alunos e complexo do nosso lado para implementar.

abraço e bons estudos! :)

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada :)
