### ISSUE TITLE
Erro ao ver as aulas

### ISSUE THREAD

**Issue by ooncyber** [caelum/alura-funcionalidades#55]
Olá, gostaria de informar que está tendo um problema com o scroll nas páginas do curso, é algo totalmente pequeno mas é bem desconfortável rsrs.
Quando se clica em qualquer lugar da aba do curso, ele se expande porém ao dar o scroll para baixo, ele barra em um certo ponto.
![image](https://user-images.githubusercontent.com/45808300/73542581-c8135900-4413-11ea-8cbb-053a7021ee94.png)
O scroll fica normal após clicar no botão correto para expandir a aba.
![image](https://user-images.githubusercontent.com/45808300/73542607-d792a200-4413-11ea-8814-082622c68412.png)

Scroll 1:
![image](https://user-images.githubusercontent.com/45808300/73542642-f09b5300-4413-11ea-8c8b-2fa8e9cd3167.png)

Scroll 2 (click no botão):
![image](https://user-images.githubusercontent.com/45808300/73542676-01e45f80-4414-11ea-92f5-e078bfdc4c5e.png)

**Comment by designernatan** [comment]
oi @ooncyber, valeu!

pelo que entendi nao tem muito o que fazer pois tem aula com **muitas** atividades :/
essa "sambada" que o sidebar dá deve ser por isso, se é isso que entendi

se nao for vc pode gravar um gif (gifcam é uma boa pra isso) ou um vídeo mostrando esse bug?
