### ISSUE TITLE
Adicionar funcionalidades para criar um roteiro de estudos mais completo

### ISSUE THREAD

**Issue by muriloarelhano** [caelum/alura-funcionalidades#550]
A criação de roteiros de estudo é uma das ferramentas mais uteis em minha opinião, porem está de certa forma restrita apenas a conteúdos Alura. Entendo a importância da exclusividade porém para melhor aproveitamento dos alunos e sabem que o roteiro pode ficar publico, seria interessando duas ferramenta simples.

### Adicionar links e conteúdos externos
Adicionar links e conteúdos externos como artigos, videos e outras coisas, apesar de ter muito conteúdo na Alura ainda não tem tudo, não estou falando em uma integração complexa, apenas uma ferramenta para criação mais customizável.

### Criar um PDF exportável com os cursos
Seria bom para as pessoas compartilharem mais conhecimento, com os outros montando roteiros mais completos com os cursos presentes na plataforma e que pudessem compartilhar com as pessoas. Dessa forma atraindo ainda mais pessoas pra dentro da Alura pelos roteiros compartilhados em PDF. Alem disso empresas poderiam colocar como um "Roadmap" interno para os funcionários estudarem.

**Comment by andradeisadora** [comment]
oi @MuriloArelhano obrigada pela sugestão!
atualizando o comentário de antes:
fui verificar e hoje você já pode colar links externos quando criar um plano de estudos.
![image](https://user-images.githubusercontent.com/84100505/135859441-75c17df8-b9a4-4c41-914a-244f6fab264b.png)


sobre o pdf exportável sem planos no momento, o notion pode te ajudar também nessa questão. você pode fazer todas as anotações dos seus estudos lá :)

abraço e bons estudos!
