### ISSUE TITLE
Botão de like ou upvote no forum

### ISSUE THREAD

**Issue by Calliope-tb** [caelum/alura-funcionalidades#551]
Ola, assim como em qualquer forum inclusive nesse do github, sinto falta de um upvote ou like no forum da Alura.
Muitas vezes quero comentar com um "obrigada pela dica" mas o post ja esta fechado. Se pudesse dar um like ia ser bem interessante.

**Comment by andradeisadora** [comment]
oi @AneCristi obrigada pela sugestão!
fizemos melhorias no fórum recentemente por isso está fora do radar pegar ele de novo por enquanto, no futuro quando revisitarmos essa área vamos considerar sua sugestão.
teremos outras novidades com o discord em breve que podem ajustar nessas questões que você apontou :)

**Comment by xpcosmos** [comment]
Amei a sugestão!

**Comment by andradeisadora** [comment]
vou fechar a issue, se quiserem podem voltar a comentar :)
