### ISSUE TITLE
Videos favoritos

### ISSUE THREAD

**Issue by Calliope-tb** [caelum/alura-funcionalidades#552]
Ola, poderia ter uma opção de adicionar videos das aulas ou textos em favoritos.
Aconteceu de eu gostar bastante de um conteudo, atualmente estou fazendo os cursos de habitos e carreira e ter um video com uma mensagem que impactou, e que gostaria de assistir mais tarde novamente.
Ou algum video mais técnico que eu achei super importante para revisitar mais tarde.

Se tivesse uma opção favoritos ia ser mais facil encontrar esses videos novamente mais tarde.

Ou uma forma de salvar em uma lista separada sem ter que necessariamente baixar os videos.

Obrigada!

**Comment by andradeisadora** [comment]
oi @AneCristi obrigada pela sugestão! 
no momento estamos sem planos para melhorar as telas de aula mas no futuro quando fizermos isso vamos considerar tua sugestão :)
uma dica para te ajudar nessa questão: você pode criar um plano de estudos privado chamado 'favoritos' e colocar todos esses conteúdos lá

**Comment by andradeisadora** [comment]
fechando a issue, se precisar pode voltar a comentar :)
