### ISSUE TITLE
Pré visualização do vídeo pela barra de progresso.

### ISSUE THREAD

**Issue by ghost** [caelum/alura-funcionalidades#553]
Igual no YouTube que conseguimos ver as partes do vídeo pela barra do tempo, para facilitar quando queremos ir para um ponto específico.

![image](https://user-images.githubusercontent.com/69422198/135657029-eeeb439f-d98b-4ca7-9b80-d07bcd5a0fbb.png)

**Comment by andradeisadora** [comment]
oi @marianadasilva, obrigada pela sugestão!
no momento estamos sem planos para isso mas quando melhorarmos as telas de aula vamos considerar sua sugestão :)
uma sugestão: nesses casos que não quiser ver o vídeo todo você pode olhar a transcrição da aula onde tem os minutos certinhos e avançar até eles.

abraço e bons estudos!
