### ISSUE TITLE
Certificado por Formações ou Plano de Estudos

### ISSUE THREAD

**Issue by luclourenco** [caelum/alura-funcionalidades#554]
Na opção dos cetificados, temos as possibilidades de emissão **por curso** ou **certificado completo**. Minha sugestão é refente ao certificado completo.

Nesta opção, o certificado apresenta todos os cursos por _certificações_ quando emitido. Fica mais flexível e até para atender necessidades mais específicas para o currículo, o aluno poder escolher a **formação** ou **plano de estudos** que vai ser impresso no certificado completo.

Assim, quando escolhemos, por exemplo, **Programação**, o certificado completo vai conter _todos os cursos de programação_. Da mesma forma, podemos montar nosso **plano de estudos** para área desejada e quando escolhermos este plano de estudos, o certificado vai conter _todos os cursos daquele plano_.

**Comment by andradeisadora** [comment]
oi @luclourenco, fizemos uma atualização no certificado completo que você pode ocultar formações inteiras para não aparecer nele. Assim você pode deixar só com as formações de programação ou da escola que tiver preferência :)

abraço e bons estudos!

**Comment by luclourenco** [comment]
oi @andradeisadora, legal! Já foi implantado?

O outro ponto que citei com a emissão do certificado completo com base no plano de estudos, seria possível? Tenho separado meus planos de estudos por grupos, por exemplo, MySQL, Python, Git, ..., e assim, conseguiria emitir o certificado com uma formação mais específica.

abraço e boa semana!!!

**Comment by andradeisadora** [comment]
oi @luclourenco já foi sim :) você consegue ver quando acessar no certificado completo. Ele está assim hoje:
![image](https://user-images.githubusercontent.com/84100505/136555509-807e874b-b39d-4ec4-b9d4-17a27e292535.png)
um detalhe importante dessa mudança é que os cursos das formações só irão aparecer na seção de formações quando a formação estiver concluída. Até lá eles ficam embaixo na seção 'outros cursos', então quando você não pretende fazer uma formação inteira, somente um curso, ele vai se manter lá embaixo.

sobre a sua outra sugestão, no momento não estamos com planos de mexer novamente no certificado completo mas no futuro quando voltarmos a fazer melhorias iremos considerar sua ideia. Estamos com algumas melhorias de outros certificados pra um momento mais próximo, em breve chegarão novidades :)

**Comment by luclourenco** [comment]
olá @andradeisadora obrigado pelo retorno ;). Perguntei sobre a implantação porque ainda não tenho a opção de visualizar ou não quando abro a página do certificado completo. bom fds!!!

![image](https://user-images.githubusercontent.com/91038239/136621676-62c12ee1-c9d9-43ea-9e6d-97de22b9df23.png)

**Comment by andradeisadora** [comment]
oi @luclourenco você já concluiu alguma formação? você consegue ocultar a formação inteira mas enquanto ela não estiver completa os cursos ficam agrupados abaixo separado por escolas exatamente como no print que você mandou. A feature para ocultar o conteúdo está funcionando somente para formações por enquanto, para cursos não está habilitado.

**Comment by luclourenco** [comment]
olá @andradeisadora ainda não concluí, desculpe a vergonha, rsrsrs. Obrigado pelo retorno. abs!
