### ISSUE TITLE
Bug no link Sugerir melhorias (GitHub)

### ISSUE THREAD

**Issue by francislopes** [caelum/alura-funcionalidades#555]
Gostaria de comentar sobre o corte que acontece nos segundos iniciais de cada vídeo, entretanto ao clicar no link [Sugerir melhoria](https://user-images.githubusercontent.com/5431347/88174122-1d2d6c00-cbfa-11ea-87dc-1c637175cc75.png), aparece uma página desconfigurada.

Sendo assim, tenho as seguintes sugestões:
1 - Verificar o link "Sugerir melhorias";
2 - Dentro do possível ajustar os vídeos para que não aconteça o corte.

**Comment by andradeisadora** [comment]
oi @francislopes fiz o teste aqui e o botão 'sugerir alteração' funcionou corretamente. Qual aula e curso que está acontecendo esse problema?
sobre a sugestão 2, você pode me explicar melhor o que está acontecendo?

**Comment by francislopes** [comment]
Oi Isadora!
Não se trata de uma aula em especifico, tentei a partir de outra aula e de outro navegador tb e continua dando o mesmo erro.  

<img width="922" alt="image" src="https://user-images.githubusercontent.com/84687024/136689763-fbb83cb9-01cc-48a5-b7c9-ab7912cfd506.png">

<img width="879" alt="image" src="https://user-images.githubusercontent.com/84687024/136689824-1328e68c-8a6e-4cd3-9471-86d1ba508b7e.png">


Quanto aos videos, não se trata de um grande problema, so reparei que em alguns deles, a fala do professor ja vinha acontecendo alguns segundos antes de iniciar o video. As vezes fica difícil de entender a primeira frase. Acredito que nos casos que isso ocorre é porque a aula foi gravada por inteiro e depois cortada em videos menores. Mais uma vez, não é algo que atrapalhe o curso, mas de qq forma acho que é algo que pode ser melhorado.

**Comment by andradeisadora** [comment]
oi @francislopes esse botão 'sugerir melhoria' está levando a um print para mostrar onde o aluno tem que clicar para sugerir a melhoria dentro do ambiente de aula. Talvez tenha ficado meio confuso mesmo, obrigada por avisar! Vou ver como podemos fazer esse ajuste mas sem prazo pra pegarmos isso ta?

abraço e bons estudos! :)

**Comment by francislopes** [comment]
Ok.
Obrigado pelo retorno.

Att,

*Francis Lopes*
+34 623 133 807 (mobile)
***@***.***
https://www.linkedin.com/in/francis-lopes/
https://github.com/francislopes


***@***.***>


Em qua., 13 de out. de 2021 às 15:34, andradeisadora <
***@***.***> escreveu:

**Comment by andradeisadora** [comment]
fechando a issue mas pode voltar a comentar se quiser :)
