### ISSUE TITLE
Possibilidade de adicionar blocos de texto em planos de estudo.

### ISSUE THREAD

**Issue by brunomiranda-hotmart** [caelum/alura-funcionalidades#556]
Não é exatamente uma nova funcionalidade, entretanto, acho que seria algo válido.

Nas formações da alura existem blocos de textos entre os cursos.
Como por exemplo:
![image](https://user-images.githubusercontent.com/84582602/136204958-8f4ad51e-b4ba-4ce2-939c-b0a9b70a15d4.png)
(Retirado de https://cursos.alura.com.br/category/devops)

Nos planos de estudo criado por outros alunos poderia ter algo similar, algumas vezes é bom poder comunicar sobre os próximos pontos do plano de estudo.
Isso pensando em planos de estudos para serem compartilhados.

**Comment by designernatan** [comment]
@brunomiranda-hotmart valeu pela sugestao!

temos planos para dar uma turbinada legal nos PDEs e blocos de texto estão na pauta :)

no seu caso especificamente, divisões como as formações ou apenas blocos de texto fazem mais sentido e resolveriam?

**Comment by brunomiranda-hotmart** [comment]
> no seu caso especificamente, divisões como as formações ou apenas blocos de texto fazem mais sentido e resolveriam?

@designernatan no meu caso apenas blocos de texto fazem mais sentido e resolveriam.

Pra te dar um detalhe mais a fundo do que eu estava tentando fazer, foi criar um PDE pra mostrar pra alguns devs do meu trabalho uma introdução à devops, mais focado nas ferramentas que a gente usa aqui.
Só que em alguns casos eu gostaria de dar mais detalhes sobre uma parte dos cursos que eu selecionei.

**Comment by designernatan** [comment]
perfeito, brigadao pelo contexto bruno!

**Comment by andradeisadora** [comment]
fechando a issue, mas podem voltar a comentar se quiserem :)

**Comment by paulorodrigues07** [comment]
Triste ver que essa issue foi fechada mais não foi implementado nada mais ou menos parecido até hoje.
Isso era exatamente o que eu estava precisando também
