### ISSUE TITLE
Seguimento do curso pelo aplicativo não passa pela resolução de exercícios

### ISSUE THREAD

**Issue by victorcaricatti** [caelum/alura-funcionalidades#557]
oi, notei que durante o seguimento do curso pelo navegador (do desktop, ao menos), as atividades são exibidas sequencialmente, alternando entre aulas, resolução de exercícios, leituras, etc. Enquanto no aplicativo (do android, ao menos), quando inicia o vídeo da aula, o seguimento das atividades passam somente pelos vídeos (não que isso seja necessariamente ruim), de modo que uma aula é exibida sequencialmente à outra e os exercícios não são sugeridos, como descrito na experiência pelo navegador.

isto traz um leve empecilho porque no modelo em que a atividade é sugerida, tenho a motivação de responder o questionário e concluir o curso com êxito, enquanto no modelo que as aulas são exibidas sequencialmente, por estar entretido no conteúdo, o usuário não tem a motivação de responder o questionário - e responder posteriormente parece mais dificultoso porque algumas perguntas são extremamente vinculadas ao conteúdo da aula.

seria viável ter uma opção em ambas plataformas para exibir ou as atividades sequencialmente ou apenas as aulas? daria mais flexibilidade ao usuário para adotar o modelo que mais satisfaça.

**Comment by designernatan** [comment]
@victorcaricatti valeu pela sugestao!

no mobile o autoplay foi sugerido por alunos que queriam ouvir as aulas sequencialmente, justamente por ja ter visto os exercícios ou deixa-los para depois

se vc n quer que isso funcione, pode desligar o autoplay (hoje ele é autoplay de vídeos somente), acho que isso ajudaria pois acabado um video, nao iria direto para o próximo

se fizer sentido dá uma testada e me fala dps?

**Comment by victorcaricatti** [comment]
@designernatan faz total sentido e atende ao meu problema, só não tinha conseguido assimilar antes. Obrigado!

**Comment by designernatan** [comment]
tranquilo victor, sucesso total e bons estudos :)

**Comment by designernatan** [comment]
fechando a issue mas podem comentar mesmo com ela fechada!
