### ISSUE TITLE
Textos ilegíveis (acessibilidade)

### ISSUE THREAD

**Issue by marcuscf** [caelum/alura-funcionalidades#558]
Diversas partes do site, como por exemplo o dashboard e o certificado completo, contêm textos bem “apagadinhos”, quase ilegíveis, com texto ciza sobre branco ou branco sobre cinza.

Isso causa a impressão que o site está “desabilitado”, ou que o conteúdo foi excluído e há apenas um “placeholder” do que estava ali antes. Por vezes hesitei em clicar nos cursos ou no meu histórico achando que eles estavam indisponíveis ou que simplesmente não se tratavam de elementos clicáveis.

Para ver se era só impressão minha ou se havia algo de errado no meu monitor ou sistema operacional (às vezes as fontes ficam bem diferentes em Linux, Windows e Mac), conferi nas ferramentas do Firefox e confirmei que os textos não atingem a legibilidade mínima desejável. Por exemplo, na figura anexada eu selecionei o texto “Elastic Search”. Considerem também que escolhi um dos trechos “em destaque”, os textos menores e sem destaque são ainda mais difíceis de ler, tem que espremer os olhos para enxergar. O único trecho que passa no teste do Firefox nessa tela é o “Cursos concluídos”, que é um pouco mais escuro e tem letra maior.

Já as telas de conteúdo dos cursos não têm esse problema. Então se puderem usar pelo menos o contraste do texto "Cursos concluídos" no dashboard todo ou o contraste usado nas telas com o conteúdo de cursos, já seria de grande ajuda (e mesmo assim, acho que poderia ter um pouco mais de contraste para garantir a visibilidade para mais pessoas e sistemas diferentes).

![alura_acessibilidade](https://user-images.githubusercontent.com/18555709/137528620-43bfa6a9-d1b0-4386-b0f6-9eee3681ae88.png)
.

**Comment by designernatan** [comment]
@marcuscf valeu pelo toque/sugestão!

começamos a usar ferramentas no próprio Figma para verificar contraste de cor para evitar isso, fica tranquilo pois queremos atacar no mínimo nível AA em tudo na plataforma inteira

inclusive uma novidade bem bacana que sai ainda este mês na alura

**Comment by designernatan** [comment]
fechando a issue, mas podem voltar a comentar se quiserem :)
