### ISSUE TITLE
Renovação <LINK>

### ISSUE THREAD

**Issue by thi-a-go** [caelum/alura-funcionalidades#559]
Haveria a possibilidade de colocar um link, mais "exposto/intuitivo", para renovar? Nesse ponto, direcionar para o whatsapp ou o local de interesse da empresa. 
Esse link, poderia ficar próximo ao "sugira curso/funcionalidade" no rodapé,  na area logada. 
Saindo do espaço logado, tenho que ficar me perguntando, o matricule-se engloba a renovação? Meio que uma dúvida besta? Não sei dizer, se é para uma nova matricula? Tipo, poderia dizer com um link abaixo do <matricule-se> algo como <é renovação>. 
E talvez se for de interesse da instituição, fomentar uma venda casada? Ganhe 1 semana no music dot, ou um desconto por renovar e/ou se pagar a vista... , ou melhor, passe para o time de vendas e já demonstre as inúmeras possibilidades de livros da casa do código, por exemplo.
Tudo que descrevi é uma sugestão, não quero me intrometer no modelo de negócio da empresa e etc. O objetivo é saber e poder ter um canal para renovar, e receber da escola algo como talvez um "bônus", pela lealdade com a renovação de uma pessoa física executando esse processo de 3 anos seguidos.

**Comment by designernatan** [comment]
@thi-a-go valeu pela sugestao e pelo tempo dedicado em escrever tudo isso!

a gente tava para ver algumas melhorias nesse processo, depois pode me passar seu usuario da alura? Pode ser por aqui mesmo ou se preferir no natan.souza@alura.com.br

já dando uma adiantada, algumas perguntas:
1. direcionando para o whatsapp, o que exatamente você esperaria a partir daí? (imaginando aqui um link 'renove por whatsapp' em algum lugar
2. ainda nesse quesito, qual lugar você esperaria encontrar esse link? Talvez no 'minha matrícula'? 
3. e pensando que num futuro vamos fazer uma nova tela pro 'minha matricula', o que vc esperaria encontrar por lá?

abração!

**Comment by thi-a-go** [comment]
Usuario: thi-a-go

1- Aqui, se fosse sugerir algo. Penso, que poderia antes de direcionar, oferecer outras opções. Exemplo:

link, com o >Renove<, conheça/veja as opções para contato!

Então, redireciona para um page view com as opções:
- link 1: >Renove por WhatsAapp<, já abre um redirecionamento para o chat-bot. Só para filtrar, na questão do horário de atendimento e para o cara não ficar sem resposta, com as infos preenshidas etc. manda para um atendente!
- link 2: >Renove por E-mail<, Já abre uma area para entrar em contato com o usuário e oferece o plano.
- link 3: >Renove por XXX < onde: XXX é algum outro canal que a equipe alura possui e faz algum tipo de iteração com o usuário.

2 - >Minha matricula< é um lugar bem intuitivo, não é uma má escolha ou também um link na area de drop dos menus que contem outras opções:
![image](https://user-images.githubusercontent.com/4229271/137812470-14fab9d7-da76-48c3-92f5-eb6d70c7527d.png)

3 - acredito que talvez sugestões para o usuário, tipo o que você poderia melhorar, ganhar, ensinar, estimular no crescimento de carreira... 
Desde que o mesmo de consentimento para isso. exemplo: 

- há um checkbox que o cara permite sugestões!?  > sobre um plano de estudo, que a Alura recomenda?
- Livros que se relacionam com seu interesses;
- Faça parte de um projeto da Alura, onde aqui você apoia em algumas melhorias/criação, para algum projeto de algumas da instituições beneficentes, onde você aprende e ainda ajuda alguém;
- Concorra a prêmios! 
      Você tem uma ideia que contribui com a alura!? 
      > Aqui, você ganha uma camiseta do time, 
      > uma chance de conhecer o time, falar com Nico/Paulo/Guilherme/Natan 
      > uma passagem VIP para Qcon.

Espero ter contribuído de alguma forma, obrigado pelo estimulo!

**Comment by designernatan** [comment]
perfeito, brigadao pelo tempo novamente, vai ajudar bastante o time aqui

abracao! :)

**Comment by andradeisadora** [comment]
fechando a issue, mas podem voltar a comentar se quiserem :)
