### ISSUE TITLE
Pontuação do ranking

### ISSUE THREAD

**Issue by heron03** [caelum/alura-funcionalidades#56]
No Ranking geral mostrar a possição exata ou mostrar com uma possição melhor, não como >10.000.

**Comment by designernatan** [comment]
@heron03 valeu pela sugestao

outro aluno sugeriu **exatamente** a mesma coisa [aqui nessa outra issue](https://github.com/caelum/alura-funcionalidades/issues/29)

precisamos melhorar toda essa experiencia em volta do ranking, sem prazos por enquanto mas está no roadmap sim
