### ISSUE TITLE
Opção de alterar o idioma do certificado

### ISSUE THREAD

**Issue by ChristianNagata** [caelum/alura-funcionalidades#560]
O mercado de tecnologia não tem fronteiras, a aplicabilidade para vagas de emprego nessa área é multinacional. Por isso, uma opção de escolher o idioma dos certificados seria muito bem vinda.

**Comment by designernatan** [comment]
@ChristianNagata valeu pela sugestao!

estamos vendo melhorias no certificado e com certeza vai ter algo assim na versão nova :)

tem um "hack" que fizemos pra conseguir isso no modelo atual: só adiciona o parâmetro lang=en (ou es) na URL do certificado que ele gera!

um exemplo aqui:
https://cursos.alura.com.br/certificate/natan-souza/acessibilidade-web-front-end?lang=en
