### ISSUE TITLE
Widget Caderno Alura e integração

### ISSUE THREAD

**Issue by lcsmr** [caelum/alura-funcionalidades#561]
Olá! Me chamo Lucas! 

Vi que o caderno da Alura é novo e provavelmente já até já estejam planejando essa funcionalidade. De qualquer maneira, acredito valer a pena pois são duas as sugestões.

Um botão flutuante do caderno, podendo alternar a transparência seria uma ótima ideia. Em alguns cursos eu gostaria de fazer anotações rápidas sem precisar pausar o vídeo e sair da tela. 

Outra sugestão é integrar o caderno com aplicativos de tarefas para que as anotações pudessem ser integradas a tarefas criadas.

Essas eram as duas.

Obrigado pelo seu tempo!

Ps. Eu não faço muita ideia da dimensão de trabalho ou complexidade para a execução dessas sugestões, aceito sugestões de estudos!

**Comment by andradeisadora** [comment]
oi @lcsmr obrigada pelas sugestões!
no momento não temos planos de melhoria pro caderno.. uma ferramenta muito boa que você pode usar é o notion. Com ele você não vai precisar trocar de tela, pode abrir a janela num cantinho e adicionar tuas anotações. Ele também tem muitas features interessantes, da uma olhadinha :)

Abraço e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, mas podem voltar a comentar se quiserem :)
