### ISSUE TITLE
Melhorar a usabilidade do label "Acompanhar tópico"

### ISSUE THREAD

**Issue by B-Schmitz** [caelum/alura-funcionalidades#562]
Essa função quando clicamos só troca a cor do ícone do olho, talvez seria mais visível identificar se estou acompanhando o tópico trocando o nome do label também ou mudando o ícone por exemplo.

Entrei agora e não sei se quando está verde estou acompanhando ou quando está azul.

**Comment by andradeisadora** [comment]
oi @B-Schmitz ta meio ruinzinho mesmo. Assim que conseguirmos vamos fazer um ajuste (sem prazo ta?)
obrigada por avisar!

abraço e bons estudos :)

**Comment by designernatan** [comment]
fechando a issue, mas podem voltar a comentar se quiserem :)
