### ISSUE TITLE
Sugestão de qual formação/curso iniciar

### ISSUE THREAD

**Issue by ghost** [caelum/alura-funcionalidades#563]
A plataforma possui muitos cursos e me sinto um pouco perdida por onde começar.  Por exemplo, estava afim de começar a estudar UX/UI Design e lá possui bastante formações, por onde inicio? Pensei que se houvesse algo como "Comece por aqui" ajudaria muito. Acho que a organização dos cursos por formação ainda não é suficiente.

**Comment by andradeisadora** [comment]
oi @marianadasilva obrigada pela sugestão!
você pode dar uma olhada nos planos de estudos públicos de outros alunos, eles podem te ajudar. Dá uma olhadinha nesse [aqui](https://cursos.alura.com.br/avancando-com-ux-em-design-de-produto-natan-de-souza-fonseca-p1774)

em breve teremos novidades na plataforma para o discovery de conteúdos novos 👀 você vai poder encontrar algumas dicas por lá também :)
abraço e bons estudos!

**Comment by designernatan** [comment]
oi @marianadasilva!

como a isa comentou acima, lançamos há uns dias o [Aluraflix](https://cursos.alura.com.br/aluraflix), nosso hub de conteúdo da plataforma inteira!

quero muito ouvir suas ideias e insights sobre essa feature 

depois de usar uns dias pode dar um reply pra gente aqui?

abração!

**Comment by designernatan** [comment]
fechando a issue, mas pode comentar depois mesmo com ela fechada pessoal

abcs!
