### ISSUE TITLE
Sujestão de mini projetos.

### ISSUE THREAD

**Issue by xpcosmos** [caelum/alura-funcionalidades#564]
Olá queridos amigos da Alura,

Não sei vocês, mas eu acho (quase certeza) que a maioria esmagadora dos alunos da alura buscam um oportunidade de ingressar no mercado de trabalho dentro das área de estudos.
Eu por exemplo busco ingressar em Data Science e tenho estudado (muito) para isso, mas o que ocorre é que precisamos de um portifólio para isso, coisa que vim descobrir recentemente, e desenvolver esse portifólio quase no fim do 13th curso é bem puxado...

Minha sugestão é que ao fim de cada curso haja uma sugestão de projeto para desenvolver e realizar upload no github.

Imagine o seguinte, estou fazendo um curso de Python e seria interessante ter um portifólio que demonstrasse que sei a lógica, como por exemplo, um jogo de par ou ímpar, etc. 
No final do curso apareceria umas três sugestões de projetos e como utilizar o github.

Isso seria muito bom para o aluno (que desenvolveria um portfólio e conseguiria uma vaga quanto para vocês que aumentariam a quantidade de alunos empregados através da plataforma.

**Comment by designernatan** [comment]
@xpcosmos valeu pela sugestao!

a gente ouviu feedbacks em volta dessa temática e fizemos o alura challenges! Bem voltado pra prática!

o atual que está correndo é focado em UX, mas os próximos já estão engatilhados e muita chance de ser algo voltado para code!

**Comment by andradeisadora** [comment]
oi pessoal, vou fechar a issue mas podem voltar a comentar se quiserem :)
