### ISSUE TITLE
Certificado de Participação unificado em PDF

### ISSUE THREAD

**Issue by WillianBR** [caelum/alura-funcionalidades#565]
Senhoras e Senhores do ALURA, sua plataforma é muito boa e nós aqui do [BB](https://www.unibb.com.br/alura) a utilizamos muitos.  Porém, ao concluir o curso, costumamos emitir o Certificado para controle interno.  

Algo que desejo ver na funcionalidade de emissão de Certificado é o seguinte:

 - Ao expandir o menu do perfil (foto), ter uma opção de Lista de Certificados, a qual exibiria uma tela, com todos os cursos e sua data de conclusão.    Além de ter em cada linha da lista, três botões por curso, com as seguintes funcionalidades cada um.
 
   1. Emitir certificado normal;
   2. Emitir certificado formal;
   3. Emitir certificado unificado;

Obviamente os dois primeiros itens seriam links para o que vocês já tem.  Já o terceiro e mais importante item, seria para emitir um documento em PDF (_Quem sabe até assinado digitalmente! [PKI ou GPG]_), contendo tanto o **Certificado Normal**, quanto o **Formal**.
Tudo em um único documento e formatado para que se possa imprimir (caso desejado) frente e verso o documento ou como vejo muito, anexar ao currículo do LinkedIn.

Também seria de grande utilidade um QR-Code com o link para o Portal Alura, já com o UID do certificado, para realizar a validação do documento.  E sendo um PDF, um link para o mesmo URL.

> Três ícones significativos e um hint bem esclarecedor, seriam o bastante!

**Comment by designernatan** [comment]
@WillianBR obrigado pela sugestao!

estamos vendo algumas melhorias para um futuro próximo com relação ao certificado

---

um ponto importante é que hoje mesmo você consegue um compilado com todos os certificados em um único arquivo, só ir no seu perfil, descer tudo e clicar em 'certificado completo', já com link de validação no rodapé do mesmo

abcs!

**Comment by WillianBR** [comment]
> 
> 
> @WillianBR obrigado pela sugestao!
> 
> estamos vendo algumas melhorias para um futuro próximo com relação ao certificado
> 
> um ponto importante é que hoje mesmo você consegue um compilado com todos os certificados em um único arquivo, só ir no seu perfil, descer tudo e clicar em 'certificado completo', já com link de validação no rodapé do mesmo
> 
> abcs!

@designernatan  Grato pela dica!  Achei o link https://unibb.alura.com.br/user/willianbr/fullCertificate/<UID>!

Vou aguardar a emissão de certificado em PDF, quem sabe até assinado digitalmente!

**Comment by giovanacgois** [comment]
Gostei muito da sugestão do @WillianBR. Pegando "um gancho" nisso, gostaria de acrescentar uma sugestão: ter opção de **baixar todos os certificados  de uma só vez** - um arquivo `.zip` com todos os certificados normais/formais de todos os cursos já concluídos. (Sei que já existe a opção do certificado completo no site, mas ele gera um modelo diferente de certificado).

**Comment by andradeisadora** [comment]
oi @giovanacgois obrigada pela sugestão :)
começamos a fazer melhorias nos certificados e em breve vai entrar a primeira novidade
num futuro voltaremos a fazer outras melhorias e levaremos em consideração sua sugestão

abraço e bons estudos!

**Comment by designernatan** [comment]
pessoal, fechando a issue, mas podem voltar a comentar se quiserem :)

**Comment by WillianBR** [comment]
> Gostei muito da sugestão do @WillianBR. Pegando "um gancho" nisso, gostaria de acrescentar uma sugestão: ter opção de **baixar todos os certificados de uma só vez** - um arquivo `.zip` com todos os certificados normais/formais de todos os cursos já concluídos. (Sei que já existe a opção do certificado completo no site, mas ele gera um modelo diferente de certificado).

Basicamente o recurso que sugeri, com opção de download de tudo em um arquivo ZIP!

Gostei! (y)
