### ISSUE TITLE
Legendas nos videos

### ISSUE THREAD

**Issue by luismercon** [caelum/alura-funcionalidades#566]
Apesar de existir a transcrição, acho que seria muito útil a possibilidade de habilitar legendas nos vídeos. No YouTube eu sempre habilito essa opção (quando há legendas), pois sinto que é mais fácil eu manter a atenção no conteúdo com dois estímulos (leitura e escrita).

**Comment by andradeisadora** [comment]
oi @luismercon obrigada pela sugestão!
estamos priorizando outras tarefas no momento por isso sem planos para mexermos na tela de aula tão breve. Quando rolar, vamos levar em consideração sua sugestão :)

abraço e bons estudos!

**Comment by andradeisadora** [comment]
Vou fechar a issue mas pode voltar a comentar se quiser :)
