### ISSUE TITLE
Migração dos dados de cursos realizados entre contas

### ISSUE THREAD

**Issue by klauscavalcante** [caelum/alura-funcionalidades#567]
Gostaria que a plataforma tivesse uma funcionalidade para migrar os dados dos cursos realizados entre contas.

Motivo: Recebi temporariamente uma licença da empresa para realizar alguns cursos específicos durante um período. Porém possuo uma conta pessoa da Alura na qual venho estudando há mais tempo e gostaria que os cursos realizados naquele período pela conta corporativa fossem espelhados/incluídos na minha conta pessoal, para que não seja necessário que eu faça manualmente a matrícula em cada um dos cursos e uma quantidade de clicks desnecessários para avançar em cada um deles até que ele sejam concluídos, uma a um. Uma desvantagem nessa abordagem inclusive, é que a data de conclusão do curso não fica igual àquela do curso realizado originalmente.

**Comment by andradeisadora** [comment]
oi @klauscavalcante você pode entrar em contato no e-mail atendimento@alura.com.br pra ver se o pessoal consegue te ajudar nisso :)

abraço e bons estudos

**Comment by klauscavalcante** [comment]
Oi @andradeisadora,
 
Liguei pra vocês semana passada mas a pessoa que me atendeu disse que não poderia ajudar, e que inclusive foi resposta vinda da equipe de TI.

Fiquei meio chateado com o atendimento, pois sendo eu desenvolvedor, sei muito bem que meus cursos poderiam ser recuperados do banco de dados e copiados para a outra conta. Acredito que a questão foi falta de vontade da empresa em ser mais assertiva à minha necessidade. Desculpe pelo desabafo.

P.S.: Fiz os cursos neste período de out/21 com a conta corporativa pois depois minha empresa faz o levantamento dos cursos realizados para lançamento interno em sistemas de controle.

Abraços
Klaus

**Comment by designernatan** [comment]
oi klaus, dando reply aqui tbm (e não precisa se desculpar por desabafar não!)

já tivemos situações assim outrora, problema aqui é que inserções de forma manual no banco acarretam em alguns problemas internos

hoje entendemos que duas contas diferentes são dois perfis diferentes (comparando com netflix por ex, email diferente é conta nova, progresso da antiga fica na antiga) e realmente não é possível migrar de uma conta para outra

agora para nao ficar te devendo: uma possibilidade bacana seria se a sua empresa colocasse seu email pessoal no time da empresa, dando acesso à esta conta, então vc continuaria de onde parou!

---

lembrando que mesmo sem acesso aos cursos na sua conta da firma, os certificados ficam disponíveis para sempre. Então você pode acessar a qualquer momento e vincular o certificado onde ele achar necessário, ok?

---

desculpa mesmo por essa impossibilidade nossa, mas imagino que desta forma talvez adiante algo

abraços!

**Comment by andradeisadora** [comment]
oi pessoal, vou fechar a issue mas podem voltar a comentar se quiserem :)
