### ISSUE TITLE
Colocar a velocidade 1.2x no Ipad

### ISSUE THREAD

**Issue by Rushiano** [caelum/alura-funcionalidades#568]
É basicamente isso. No android já existe a funcionalidade. Também tem acontecido algo estranho na versão de iPad: Em alguns momentos nos quizes um vídeo aleatório dá play do nada.

**Comment by designernatan** [comment]
@Rushiano valeu pela sugestao! Veremos algo aqui

---

dessa parada estranha, consegue passar essas infos aqui pra gente?
- Modelo do aparelho
- Versão do Android/iOS
- Versão da app


abcs!

**Comment by designernatan** [comment]
fechando a issue apenas para controle interno nosso, mas pode passar as infos depois viu luciano

abcs

**Comment by Rushiano** [comment]
Olá. É a geração 7 do iPad com o ios 15. Essa velocidade 1.2x seria muito interessante (até mesmo pra padronizar porque no android tem e no iPad não).
