### ISSUE TITLE
"Full Screen" nos textos

### ISSUE THREAD

**Issue by luigiMinardi** [caelum/alura-funcionalidades#57]
Os textos/códigos muitas vezes ficam pequenos e com uma scroll bar gigante impossível de controlar ficando difícil de visualizar o que está sendo dito. Ao adicionar um botão que abrisse o código em um modal maior ou algo assim poderia facilitar a visualização. Fiz um rapidinho só pra dar uma base +-

![aluramodalclose](https://user-images.githubusercontent.com/53359163/73739668-fca25000-4746-11ea-8f59-f2621f6e4fb8.jpg)
![aluramodalopen](https://user-images.githubusercontent.com/53359163/73739674-fdd37d00-4746-11ea-9151-e57d1156cb80.jpg)

**Comment by designernatan** [comment]
oi @luigiMinardi valeu pela sugestao!

estamos com planos para melhorar toda a experiencia de aula, e feedbacks assim nos dao mais pano para isso
