### ISSUE TITLE
Vídeos interrompidos à noite. Favor mudar de plataforma de vídeo

### ISSUE THREAD

**Issue by mkanada** [caelum/alura-funcionalidades#570]
Não sei a plataforma de vídeos que vocês estão usando, mas à noite, os vídeos ficam parando com muita frequência. No momento que estou escrevendo isto, meu teste de velocidade bateu 80mbps, os outros sites (netflix, youtube, etc) carregam rapidamente, mas o vídeo do curso que estou assistindo fica parando a cada 2 ou 3 segundos.

**Comment by designernatan** [comment]
@mkanada da uma olhada na pagina de diagnostico pfv?

![image](https://user-images.githubusercontent.com/5431347/140255803-752e0513-cf25-40ae-a25f-ee9cb72db603.png)

ai pra nao deixar publico aqui manda no atendimento@alura.com.br com as informacoes do passo-a-passo dessa pagina?

**Comment by andradeisadora** [comment]
oi pessoal, vou fechar a issue mas podem voltar a comentar se quiserem :)
