### ISSUE TITLE
Adicionar soma de pontos ao assistir as aulas ou ao ler qualquer artigo dentro do curso que não seja uma atividade de exercício.

### ISSUE THREAD

**Issue by Marcos-Vitor123** [caelum/alura-funcionalidades#571]
Pois notei que é somado pontos somente ao fazer as atividades de exercícios propostos. Pois na minha visão seria interessante ter essa soma de pontos também ao assistir as aulas, ler qualquer artigo relacionado a aula dentro do curso e quando clicarmos em algum link que nos direciona para artigos fora da plataforma. Pois acho um pouco desmotivador ao assistirmos a aula, não ganharmos nenhum ponto, pois se no mesmo dia por algum motivo não podermos fazer algum dos exercícios proposto, dá uma sensação de que não estudamos nada. Não importa a quantidade de pontos que vamos ganhar. Mas sim que estamos progredindo nos estudos. Pode ser até 100 xp por ler artigos dentro e fora da plataforma do curso ou ao assistir uma video aula. Pensem nisso com carinho.

**Comment by andradeisadora** [comment]
oi @Marcos-Vitor123 obrigada pela sugestão!
faz sentido sim, a plataforma foi crescendo e acabamos não ajustando a gamificação junto. Vou levar a sua sugestão pra melhorarmos no futuro, atualmente estamos com tarefas grandes por isso não posso te prometer prazo ta?

enquanto isso você pode seguir ganhando pontos nessas ações:

![image](https://user-images.githubusercontent.com/84100505/140977784-c31f06ef-1ff3-421b-b67b-28479aa42c4d.png)

abraço e bons estudos!

**Comment by Marcos-Vitor123** [comment]
De nada! Sim! Compreendo. Mas não esqueçam de adicionar isso lá.

Em ter., 9 de nov. de 2021 às 14:53, andradeisadora <
***@***.***> escreveu:

**Comment by andradeisadora** [comment]
vou fechar a issue, qualquer coisa pode voltar a comentar :)
