### ISSUE TITLE
Melhoria na visualização das "atividades nos últimos 30 dias" no header

### ISSUE THREAD

**Issue by fredericobimachine** [caelum/alura-funcionalidades#572]
Ao utilizar a plataforma da Alura, reparei que o item "atividades nos últimos 30 dias" localizado no header da página tem uma dificil visualização e entendimento, o cinza está forte de mais, com este azul fraquinho fica dificil eu ver os dias que eu tive atividade. O mesmo não acontece na página "meu perfil".

![image](https://user-images.githubusercontent.com/88671408/140062878-7fccdbb4-db77-404b-924f-2cb8bbd9c90d.png)
Meu perfil:
![image](https://user-images.githubusercontent.com/88671408/140063174-fca8d4f2-131b-48b7-bf65-099b2b6a1821.png)

**Comment by andradeisadora** [comment]
oi @fredericobimachine faz sentido mesmo, ta com pouco contraste.
estamos com planos de melhorar a dashboard para os alunos de empresa num futuro breve. Não tenho prazo pra te passar mas tenho um spoiler de como pode ficar esse grid :)

![image](https://user-images.githubusercontent.com/84100505/140401300-27f27e31-845f-4c26-a8a7-e60db473801c.png)

abraço e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue mas pode voltar a comentar se quiser :)
