### ISSUE TITLE
Compartilhar progresso entre contas

### ISSUE THREAD

**Issue by Jean1dev** [caelum/alura-funcionalidades#573]
Gostaria que tivesse uma funcionalidade de exportar/compartilhar dados entre contas do mesmo dono.
Situação
  Tenho minha conta alura pessoal e minha conta alura empresarial, os cursos que eu tenho concluido da conta pessoal queria passar para a conta empresarial e vice-versa

**Comment by designernatan** [comment]
@Jean1dev dá um ping no atendimento@alura.com.br?

talvez role algo assim, mas depende muito do caso, da empresa etc
