### ISSUE TITLE
Sugestão de curso backend

### ISSUE THREAD

**Issue by henriquehrf** [caelum/alura-funcionalidades#574]
Olá,
Tenho explorado bastante cursos de backend  .NET do alura, porém já faz um tempo que tenho sentido falta de alguns cursos voltados a frameworks de messageria tais com o RabbitMQ (utilizando o MassTransit por exemplo) em uma web API, demonstrando boas práticas e pattens e abstrações bacana.

**Comment by designernatan** [comment]
@henriquehrf opa vc pode sempre usar o forms de [sugestão de cursos](https://docs.google.com/forms/d/e/1FAIpQLScwKyaSvuFXK9SmMJoLPuYAS2qD_XAAnZPxMZij9qVeflbhBg/viewform) (fica no rodapé da plataforma), que aí a sugestão já cai direto no time de conteúdo

com isso ajuda o time aqui a entender e priorizar as demandas

abracao!
