### ISSUE TITLE
Possibilidade de incorporar certificados ao meu site

### ISSUE THREAD

**Issue by MdeirosRubens** [caelum/alura-funcionalidades#575]
Estou aplicando meus conhecimentos da plataforma para meu proprio projeto que é tornar meu cv, uma pagina web.

Abaixo deixo as maneiras que encontrei para incorporar o certificado ao meu site mas que não obtive sucesso, se vocês tiverem alguma outra sugestão, eu ficaria muito feliz de saber e aplica-la. 
Por enquanto estou trabalhando nesse projeto local, então continuarei criando minha pagina e antes de publica-la volto pra ver se foi possivel aplicar a funcionalidade.

Só tenho a agradecer a todos vocês <3

Maneiras que encontrei de adicionar:

Utilizando tag <iframe>:
A conexão foi recusada.

<iframe src=https://cursos.alura.com.br/user/mdeirosrubens/fullCertificate/e758a07897f1a6b431a0710d81c23a43></iframe>

Erro: Refused to display 'https://cursos.alura.com.br/' in a frame because it set 'X-Frame-Options' to 'deny'.

Salvando o arquivo como imagem:
Não é possível por que o conteudo impresso como nome, nome do curso, carga horaria, etc... são textos e não imagem, logo quando baixo só vem o template do certificado.

Nesse momento a unica forma possível de fazer isso seria printando a tela, salvando a imagem e utilizando assim a tag <img>
Mas isso alem de prejudicar a qualidade da imagem, é trabalhoso e vou perder muito tempo. lembrando que atualizarei a pagina conforme for concluindo mais cursos.

**Comment by designernatan** [comment]
@MdeirosRubens valeu pela sugestao!

a gente ta vendo algumas melhorias no certificado e até pensamos em habilitar esse x-frame-options, mas tivemos problemas com relação a segurança indo por esse caminho 

quando vc clica em imprimir, tenta colocar para salvar em PDF, aí os dados vão juntos com a imagem de fundo de boas!

me fala aqui depois se rolou?

**Comment by designernatan** [comment]
ah outro ponto:

uma outra coisa q vc poderia fazer hoje como solução de contorno: no source procura pela og:image que já vai ser o PNG com os dados do certificado, ai rolaria embedar pq é só um png

![image](https://user-images.githubusercontent.com/5431347/141309522-4dd53cf7-b61f-4dd5-b6ce-2d686a2e7339.png)

a gente fez isso pra compartilhar nas redes direto pela pagina, mas talvez te ajude com isso :)

**Comment by designernatan** [comment]
fechando a issue, mas pode voltar a comentar se rolou ou nao rubens

abcs!
