### ISSUE TITLE
Marcar e desmarcar aulas

### ISSUE THREAD

**Issue by AnedinodSantos** [caelum/alura-funcionalidades#576]
Seria legal, após terminar alguma aula de qualquer curso, aparecer ao lado da mesma um checkbox, marcando que aquela aula foi concluída. Se desmarcássemos esse checkbox, ela apareceria como não concluída.

Qual o objetivo dessa funcionalidade?

As vezes eu acabo voltando nos cursos e nas trilhas para refaze-los. Para identificar em qual aula eu parei, eu acabo anotando em algum lugar, caderno ou notepad. Havendo essa funcionalidade, basta desmarcar a checkbox das aulas que eu quero refazer e marca-las novamente assim que terminar.

**Comment by designernatan** [comment]
@AnedinodSantos valeu pela sugestao!

a gente quer num futuro de longo prazo melhorar a tela de aula, pontos assim com crtz vao surgir nas discussoes!

uma coisa que pode te ajudar hoje com isso: salvar as URLs com o [GetPocket](https://getpocket.com/my-list) colocando uma tag "rever-alura"

outra opcao seria pegar as URLs dessas atividades manualmente e colocar numa tabela no Notion, mas com o Pocket me parece mais tranquilo esse caminho

**Comment by designernatan** [comment]
fechando a issue, mas pode voltar a comentar se rolou ou nao anedino 

abcs!
