### ISSUE TITLE
Projetos

### ISSUE THREAD

**Issue by rodrigobcunha** [caelum/alura-funcionalidades#577]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.
A aba de projetos está meio que abandonada. seria uma boa pegar os challenges passados e colocar nos projetos para que quem perdeu ou não era aluno Alura possam refazer em algum outro momento.
eu acho a parte de projetos muito importante porque mostra se a gente realmente aprendeu nos cursos.

**Comment by designernatan** [comment]
@rodrigobcunha valeu pelas sugestões!

os projetos evoluiram 500% quando fomos caminhando para os challenges, mais mao na massa e criando conexão com a comunidade alura

ainda estamos azeitando toda a parte de 'mao na massa' deles, aguarde novidades para um futuro de médio prazo (não consigo te passar datas infelizmente)

abcs!

**Comment by andradeisadora** [comment]
oi pessoal, vou fechar a issue mas podem voltar a comentar se quiserem :)
