### ISSUE TITLE
Opção de Acesso Corporativo

### ISSUE THREAD

**Issue by DaltonSoffiatti** [caelum/alura-funcionalidades#578]
![Acesso Corporativo](https://user-images.githubusercontent.com/80929502/141655718-53d64d56-1d52-4780-a0bf-86ab07c76c95.png)
![Login Corporativo](https://user-images.githubusercontent.com/80929502/141655757-5f6217e0-e652-4eed-9eac-33c2fe8afd03.png)

Quando nosso acesso aos Cursos Alura são feitos através do login na UniBB tudo corre bem, mas quando já estamos logados na Alura e surge um link que direciona para um outro curso, na tela aparece "Matricule-se" -  "Login".
Logo abaixo, nos campos de login é solicitado o "e-mail" e a "senha",  e mais abaixo as opções "Entrar com Facebook" ou "Entrar com Google".  Meu acesso a Unibb é feito com minha matrícula (alfanumérico) e uma senha criada por mim.
Poderia ser adicionada uma opção de "Login Corporativo" por exemplo, ou, estando o aluno já logado, redirecionar automaticamente para a página a que se refere o link.

**Comment by DaltonSoffiatti** [comment]
O parágrafo abaixo está como o original, porém, quando envio o comentário o parágrafo é alterado...
Poderia ser adicionada uma opção de "Login Corporativo" por exemplo, ou, estando o aluno já logado, redirecionar automaticamente para a página a que se refere o link.

**Comment by designernatan** [comment]
@DaltonSoffiatti obrigado pela sugestao!

por hora o que é possível de ser feito é quando tiver um link que comece com "cursos.alura...." substituir por "unibb.alura..."

de qualquer forma vamos ver algo para melhorar essa experiencia no futuro ok?

**Comment by andradeisadora** [comment]
oi pessoal! estou fechando a issue mas podem voltar a comentar se precisar :)
