### ISSUE TITLE
Black Theme em todo o site

### ISSUE THREAD

**Issue by jefersondsgomes** [caelum/alura-funcionalidades#58]
Gostaria de sugerir a possibilidade de implementar a opção de black theme / modo noturno no site, assim como existe no menu de cursos.

**Comment by designernatan** [comment]
oi @jefersondsgomes obrigado pela sugestao
ideia do dark mode atual era testarmos tração e acompanhar o uso

sem prazos aqui, mas objetivo é ter dark mode no site inteiro sim
