### ISSUE TITLE
vídeos legendados

### ISSUE THREAD

**Issue by danieomundo** [caelum/alura-funcionalidades#580]
Nova funcionalidade: Acessibilidade para deficientes auditivos, disponibilizando vídeos com legendas. Ou se não for possível, disponibilizar pelo menos a transcrição automática, como já existe em plataformas concorrentes.

**Comment by andradeisadora** [comment]
oi @danieomundo obrigada pela sugestão!
hoje em dia transcrevemos todas as falas da aula na transcrição abaixo do video, junto tem os minutos em que elas acontecem.
exemplo no print abaixo:

![image](https://user-images.githubusercontent.com/84100505/144230079-f840756d-cf4d-404a-9799-a11fc29e895d.png)

você pode me explicar melhor sobre essa sugestão? vc está usando a transcrição que temos?

**Comment by danieomundo** [comment]
Oi, Isadora, boa tarde!

Então, quando eu mandei a sugestão, eu estava vendo uns vídeos de boas
vindas que não tinham legendas. Mas quando eu entrei nas AULAS, eu percebi
a transcrição e fiquei muito feliz!

Só que eu notei dificuldade na forma como ela funciona porque o vídeo fica
parado fixamente, aí conforme você vai descendo a página para continuar a
leitura da transcrição, você já não consegue ver mais o vídeo, porque o
vídeo não desce.

Então, fica a minha sugestão:

A ideia da transcrição é MARAVILHOSA! Mas gostaria que pensassem na minha
sugestão de mudar a transcrição de posição para ficar lado-a-lado com o
vídeo, assim é a forma mais confortável de acompanhar as aulas!

Pois da forma atual eu estou tendo que ler toda a transcrição para DEPOIS
dar play no vídeo e tentar pegar as informações, sabe?

Ou para não ficar muito poluído, vocês poderiam implementar opções que
pudéssemos escolher como a gente deseja assistir, opções como: transcrição
lado-a-lado, transcrição embaixo, transcrição em cima, ocultar transcrição
etc.

Espero que considerem a sugestão.

Agradeço muito pelo contato!


Att,
Dani.





Em qua., 1 de dez. de 2021 às 09:00, andradeisadora <
***@***.***> escreveu:

**Comment by andradeisadora** [comment]
oi @danieomundo pra ajudar nessa questão do vídeo você pode usar o modo picture in picture, ele fica no canto inferior direito do vídeo

![image](https://user-images.githubusercontent.com/84100505/144848844-a43959ea-2f40-4d18-b003-b2b36ecd1ed6.png)

assim o vídeo vai descendo junto conforme vc for acompanhando a descrição

![image](https://user-images.githubusercontent.com/84100505/144849088-e0e2a2b5-e79e-4587-8436-a5b3b084063c.png)

sobre o vídeo de boas vindas peço desculpas, nos passamos mas já vamos ir atrás pra resolver. Obrigada por avisar!

abraço e bons estudos :)

**Comment by andradeisadora** [comment]
Fechando a issue mas pode voltar a comentar se precisar :)
