### ISSUE TITLE
Upgrade de Plano

### ISSUE THREAD

**Issue by PedroHumberto** [caelum/alura-funcionalidades#581]
Uma opção para dar upgrade no plano caso queira trocar do simples para o completo.

**Comment by andradeisadora** [comment]
oi @PedroHumberto hoje em dia você consegue renovar seu plano antes dele expirar, nessa renovação você pode fazer upgrade do plano também.

você pode entrar em contato no atendimento@alura.com.br para falar com o pessoal sobre o upgrade

abraço e bons estudos!

**Comment by andradeisadora** [comment]
Fechando a issue mas pode voltar a comentar se precisar :)
