### ISSUE TITLE
Musica de fundo

### ISSUE THREAD

**Issue by ElDuduardo** [caelum/alura-funcionalidades#582]
Não sei se esse isso se enquadra aqui (caso não eu deleto o post)

Por mais superficial que pareça eu acharia muito interessante se houvesse uma playlist para ouvir de fundo das aulas.

Eu digo isso porque eu tenho problema de atenção, então muitas vezes tenho que rever a aula porque me distraí, a musica me ajuda muito a focar.

Fica a ideia de um dia fazer uma playlist no Spotify ou Deezer de estudo. Com um Lo-Fi mesmo, mas só para ter um som de fundo quanto o professor fala.

Caso for rolar recomendo pesquisar sobre ondas binaurais, são comprimentos de ondas que ajudam no foco, pode ser trabalhado com musicas nesse comprimento de onda.

**Comment by andradeisadora** [comment]
oi @ElDuduardo obrigada pela sugestão!

não temos planos pra criar uma feature de player de música mas se isso surgir no nosso radar no futuro levaremos em consideração sua sugestão.
enquanto isso, no youtube tem muitas playlists e você pode deixar tocando no momento que estiver estudando.

abraço e bons estudos :)

**Comment by andradeisadora** [comment]
Fechando a issue mas pode voltar a comentar se precisar :)
