### ISSUE TITLE
Sugestão de exercicios de código

### ISSUE THREAD

**Issue by PriscilaPanzuto** [caelum/alura-funcionalidades#583]
Adoro o ensino da Alura, mas sinto falta de exercícios de código, no qual enviamos o código e ele é corrigido automaticamente.
Isso ajuda a fixar o conteúdo.

**Comment by nathan-luz** [comment]
Concordo, Acho que um campo simples contendo listas de exercicio relacionados ao curso(ou apenas links para elas) resolveria. Estas listas poderiam ter sidas escolhidas pelo instrutor do curso ou pela comunidade. 

Eu por exemplo sinto que aprendo muito mais quando pego o que foi ensinado e aplico em um momento sozinho fazendo exercicios do que fazendo questões de multipla escolha entre as aulas ou replicando o codigo dos professores.

**Comment by duartebianca** [comment]
Sim, exercícios com um juiz online como ocorrem em vários sites seria ótimo! Agora lembrando que o código para esse juiz a saída tem que ser exatamente como pedida, se não, sai errado. Então tira um pouco da liberdade criativa, mas seria ótimo para testar conceitos :)

**Comment by designernatan** [comment]
Oi pessoal! Valeu pela sugestao! 

Um dos principais diferenciais da Alura é que a gente sempre tenta aproximar o ensino do **mundo real,** ainda vale o que [o Paulo comentou aqui nessa outra issue](https://github.com/caelum/alura-funcionalidades/issues/108) tudo bem?

Pensando em treinar MAIS ainda, colocando bastante a mão na massa mesmo, elaboramos os Challenges e as Imersões! Inclusive temos novidades bacanas no forno para ano que vem em volta desses dois pra vocês, mas não vou dar spoiler...

Abcs!

**Comment by PriscilaPanzuto** [comment]
Oi Natan, obrigada pelo retorno.
Acho legal os Challenges, lógico, mas como eu por exemplo que estou no inicio dos estudos acaba sendo complexo demais as vezes tanto isso quanto os projetos.
Com certeza chego la, mas enquanto isso poderia ter outros desafios menores então por exemplo.
Enfim, só uma sugestao, aprendo muito com a Alura mesmo só nos vídeos.
Abco

**Comment by designernatan** [comment]
tenta dar uma chance pros challenges depois, em geral no começo é um conteúdo mais básico também até para todo mundo aprender junto

inclusive sempre que há um challenge no discord da alura a galera se ajuda bastante

abracao!

**Comment by andradeisadora** [comment]
oi pessoal! estou fechando a issue mas podem voltar a comentar se precisar :)
