### ISSUE TITLE
Checkbox "Avançar automaticamente para o próximo vídeo"

### ISSUE THREAD

**Issue by johnylab** [caelum/alura-funcionalidades#584]
Os cursos deveriam ter uma opção de avançar os vídeos automaticamente. Sugiro como controle um checkbox ao lado do botão "Próxima atividade", que aparece tanto acima quanto abaixo de cada vídeo. Associado a isso, os vídeos poderiam iniciar automaticamente também. As atividades sem vídeo podem funcionar como uma espécie de pausa automática, eliminando o risco de avançar demais no conteúdo por distração do aluno.

**Comment by designernatan** [comment]
@Johnylab valeu pela sugestao!

hoje temos essa opcao apenas para alunos com planos pessoa física, fica no player mesmo:
![image](https://user-images.githubusercontent.com/5431347/144865839-465c9264-8726-4583-813d-6c2de5f23804.png)

**Comment by andradeisadora** [comment]
oi pessoal, estou fechando a issue mas podem voltar a comentar se quiserem :)
