### ISSUE TITLE
Lista de desejos de cursos ou formações

### ISSUE THREAD

**Issue by SuianeSM** [caelum/alura-funcionalidades#585]
Eu acho que seria importante ter uma lista de desejos de cursos ou formações mais vísivel, porque quando eu encontro um curso que achei interessante já queria salvar em algum lugar para que quando eu termine o que eu tô fazendo eu volte lá na lista e faça o próximo que estava na lista. Isso é porque eu sou ruim pra gravar nomes de cursos, então salvar o que eu gostei facilitaria minha vida de ficar procurando cursos na plataforma. 

Não tá muito visível o favoritar, eu vim escrever aqui porque eu não tinha achado de primeira.

**Comment by designernatan** [comment]
@SuianeSM valeu pela sugestao!

já ia te falar que o favoritar é o caminho, e a gente deixou ele mais "guardadinho" pq tinha pouco uso, diferente do Plano de Estudos

duas coisas que você pode fazer hoje pra eu nao ficar te devendo tanto:

1. usar um site chamado get pocket para ir salvando (e tagueando!) não só cursos como vídeos e atividades específicas
2. criar um Plano de Estudos chamado "ver mais tarde" e ir salvando os cursos lá para ver num segundo momento

se testar uma dessas me fala depois como tem (ou nao tem) funcionado por favor?

abcs!

**Comment by SuianeSM** [comment]
Legal, vou testar sim. Mas agora que descobri onde está o botão de favoritos estou usando sim.

**Comment by callmerockett** [comment]
Oi galera, eu tava pesquisando os cursos e formações, e embora tenha como adicionar cursos num plano de estudos, não vi como adicionar formações num plano de estudos. Acho que seria interessante poder fazer isso, ou pelo menos poder favoritar as formações.

**Comment by designernatan** [comment]
fala felipe, hoje rola add formacoes direto sim
![image](https://user-images.githubusercontent.com/5431347/160263915-23cb5c3f-b523-4a65-b13e-002b65fe5370.png)

precisa ver os termos pra ver se devolve certinho na busca tb

**Comment by callmerockett** [comment]
Fala Natan. Mano, tu podes me dizer por onde tu achou esse formulário aí? Não achei o caminho dele aqui, só acho esse da imagem abaixo. Na página da formação também não tem como adicionar :/ 

![image](https://user-images.githubusercontent.com/27767899/160300058-64273ece-98d6-431e-b316-cb53e6b56891.png)

**Comment by designernatan** [comment]
ali em meu aprendizado -> planos de estudo

aí só criar ou editar algum e adicionar a formação :)

**Comment by callmerockett** [comment]
Ah, agora eu vi, muito obrigado!

Acho que seria legal poder fazer isso direto da página da formação, igual como é nos cursos. Algumas formações são bem grandes, mas outras são mais voltadas pra uma tecnologia específica dentro de uma grande área. Só não sei se faria sentido pra Alura xD

**Comment by designernatan** [comment]
faz todo sentido!

a gente ta querendo dar uma ajeitada ali na pg de formacao no futuro, vamos considerar isso com crtz

valeu felipe!!
