### ISSUE TITLE
favoritar vídeos

### ISSUE THREAD

**Issue by amanrodrigues87** [caelum/alura-funcionalidades#586]
a sugestão é que seja possível favoritar vídeos dentro de um curso. motivo: eu faço um curso inteiro e acho ele todo interessante, mas pode haver um (ou mais) vídeo específico que acho MUITO instrutivo e que posso inclusive precisar voltar nele depois para consultar certas informações. se eu tiver um sistema de meus vídeos favoritos, esse atalho fica beeem fácil.
e o interessante seria que esses vídeos favoritos fossem vistos tanto de dentro do curso que eu estou (tipo tendo um link lá dentro para "meus vídeos favoritos deste curso") como também do meu perfil tendo lá um link "meus vídeos favoritos" que reúna meus favoritos de todos os cursos.

**Comment by designernatan** [comment]
@amanrodrigues87 valeu pela sugestão!

Hoje não temos algo assim pensado, mas faz bastante sentido! Queremos melhorar a tela de aula no futuro e uma feature assim estará nas discussões.

---

Atualmente eu uso uma ferramenta chamada [Get Pocket,](https://getpocket.com/pt/my-list) com ela salvo links e vídeos para ver mais tarde. É bacana que dá para colocar tags em cada link, facilitando estudar depois. Acho que pode te ajudar hoje!

Meu problema com ela é que acabo nunca lendo o que salvo. ¯\_(ツ)_/¯

**Comment by andradeisadora** [comment]
oi pessoal, estou fechando a issue mas podem voltar a comentar se quiserem :)
