### ISSUE TITLE
Reorganizar cards de Formação no Guias de estudos que estou seguindo

### ISSUE THREAD

**Issue by biancapb** [caelum/alura-funcionalidades#587]
Como usuária da Alura, gostaria de ter a opção de organizar livremente os cards de Formações/Guias.

![image](https://user-images.githubusercontent.com/48135342/145510120-fc8cfd1c-f2e9-4d49-8989-2b2ece113814.png)

Usando como exemplo a imagem acima, se porventura o usuário optar por colocar na frente como prioridade visual a Formação de Produtividade, ter a opção de arrastá-lo para a posição desejada.
Sendo possível essa organização por parte do usuário, ele poderá destacar no Dashboard (figura abaixo) as Formações desejadas, como no exemplo usado anteriormente, o card da Formação "Líder de Si" seria rearranjado dando lugar para o card da Formação "Produtividade".

![image](https://user-images.githubusercontent.com/48135342/145510463-2c336a99-23ee-4568-be1b-32c1963d2a02.png)

![image](https://user-images.githubusercontent.com/48135342/145510887-43f5447c-72d9-4ca6-8e80-ef1e13884374.png)

Detalhe: atualmente para o usuário dar destaque para as Formações que deseja, é necessário desmarcar e marcar novamente a opção de "Exibir na Dashboard".

**Comment by designernatan** [comment]
@biancapb valeu pela sugestao!

lembro que quando fizemos essa tela pensamos em algo assim, algo mais draggable mesmo (estilo o que acontece na criação de um Plano de Estudo por exemplo), mas nos testes com usuário não se mostrou algo com muito valor e se nao me engano complicaria um pouco (tecnicamente falando) para o lançamento 

quando pegarmos essa tela para a melhorarmos vamos discutir em cima da sua sugestao, ok?

e já tentando entender mais: hoje vc sente essa necessidade de reordenar os guias por qual motivo exatamente? Qual a dor exatamente?

valeu!

**Comment by biancapb** [comment]
oi @designernatan! eu que agradeço pelo retorno!

entendi, seria realmente como uma forma de melhoria
o motivo, é pela tela do dashboard dar destaque para as quatro últimas formações salvas, não necessariamente as formações que o usuário realmente quer destacar
como observei que isso estava ligado à tela das guias, pensei que tendo a liberdade de reorganizá-la poderia fazer com que pudéssemos escolher as formações de destaques, porém acredito que ter a opção na própria formação de destacá-la no dashboard já meio que resolveria

espero ter explicado bem hehe
muito obrigada!

**Comment by andradeisadora** [comment]
oi pessoal! estou fechando a issue mas podem voltar a comentar se precisar :)

**Comment by biancapb** [comment]
Beleza, @andradeisadora ! 
Muito obrigada pela consideração da minha sugestão, galera.
Bom trabalho e boas festas para vocês nesse fim de ano! :)
