### ISSUE TITLE
Modo noturno sendo desativado ao sugerir uma alteração

### ISSUE THREAD

**Issue by gabrielnov** [caelum/alura-funcionalidades#588]
Olá, notei que o modo noturno/dark mode está sendo automaticamente desativado ao sugerir uma alteração.

Exemplo:

Antes de ser redirecionado à página de sugerir alteração:
![image](https://user-images.githubusercontent.com/82888043/145681236-8269d15a-3477-4dce-98fe-4702ba7189e4.png)

Após o redirecionamento:
![image](https://user-images.githubusercontent.com/82888043/145681245-2d52081c-c1a7-46c2-b8bd-e41d10f98640.png)

Após sair da página de sugestão de alterações, o modo noturno permanece desativado:

![image](https://user-images.githubusercontent.com/82888043/145681251-0af9d13f-d25f-4b9e-a85c-04d144933dac.png)

Notei que o modo noturno permanece desativado em todas as páginas do site, não só no curso em que o problema ocorreu.

**Comment by andradeisadora** [comment]
oi @gabrielnov vou passar pro pessoal dar uma olhada no que ta acontecendo. Obrigada por avisar! :)
não consigo te dar um prazo pra ajuste, ta?

abraço e bons estudos!
