### ISSUE TITLE
Detalhes sobre o Plano de estudos

### ISSUE THREAD

**Issue by MuriloRodriguesXpto** [caelum/alura-funcionalidades#589]
1. Ao criar/visualizar um plano de estudos poderia ter uma informação sobre a quantidade de horas (somadas) de todos os cursos vinculados ao Plano de Estudos.
2. Ao criar um plano de estudos poderia informar os cursos repetidos neste plano de estudos, encontro esse "problema" quando insiro uma formação sobre "NodeJS Express" (por exemplo), mas essa formação já tem um curso que eu inseri "avulso" no Plano de estudos, aí eu poderia tirar esse curso avulso do plano.

**Comment by andradeisadora** [comment]
oi @MuriloRodriguesXpto obrigada pela sugestão!
não estamos com planos pra mexer nos planos de estudos no momento, mas no futuro quando revisitarmos essa feature levaremos em consideração suas sugestões :)

abraço e bons estudos!

**Comment by jehrestello** [comment]
Oiee, tudo beleza?
Também notei uma melhoria para o plano de estudos:
- Tenho problemas em adicionar links externos aos meus planos de estudos, poucos são aceitos, seria mais útil e eficaz se houvesse essa flexibilidade de aceitar mais opções de sites externos.
- Quando vc coloca um link externo no plano de estudos, não necessariamente fica claro o que é aquele item, se fosse possível adicionar algum comentário manual, ou renomear aquele tópico para algo que faça mais sentido, diferentemente do link de acesso mas mantendo o mesmo vinculado, também ajudaria a deixar clara a intenção de estudo, qual assunto se refere.
- Outra ponto é inserir outros formatos além de links, por exemplo arquivos ou até palavras que remetam uma necessidade de estudo (talvez vc precise fazer uma pesquisa para encontrar informações sobre aquele tópico, mas sabendo que tem necessidade de estudar dentro do escopo daquele plano já seria um lembrete útil).

@designernatan gosto do seu formato de interação aqui... se puder visualizar as sugestões e inserir num backlog da ferramenta :D - o recurso de montar planos de estudos é realmente muito útil e pode ser ainda melhor! 

valeuu :D

**Comment by andradeisadora** [comment]
oi pessoal, estou fechando a issue mas podem voltar a comentar se quiserem :)
