### ISSUE TITLE
Velocidade 1.75x

### ISSUE THREAD

**Issue by gean01** [caelum/alura-funcionalidades#59]
No Alura temos (dentre outras) as velocidades 1.5 e 2.0x. Para alguns vídeos, enquanto 1.5 é muito "devagar", 2.0 acaba sendo muito rápido. Assim como é feito no Youtube, por favor adicionem a velocidade 1.75x. Provavelmente será muito mais útil que a velocidade 3.0x, ofecerida atualmente.

**Comment by designernatan** [comment]
oi @gean01 obrigado pela sugestao

[uma issue igual foi aberta aqui](https://github.com/caelum/alura-funcionalidades/issues/42)
como disse lá, depende muito do instrutor, do curso, etc

3x eu vejo mais cursos de research e agile, mas em geral deixo 1.8 como vc sugeriu

a gente vai ver da possibilidade de deixar igual o youtube, ai casa mais com o que nós (usuários) estamos acostumados

abcs!

**Comment by designernatan** [comment]
time de desenvolvimento da alura codou e agora tem outras opcoes de velocidade :)
