### ISSUE TITLE
Disponibilizar os materiais (e criar mais materiais) de um curso em um unico link. 

### ISSUE THREAD

**Issue by Rimandias** [caelum/alura-funcionalidades#590]
Eu estudo muito no celular (no pc também) porém quando estou no celular eu não baixo os materiais do curso por dois motivos;
1 - Quando vejo os cursos não aparece a parte transcrita, para isso eu devo clicar na opção de ver o curso transcrito e ver se tem algum link
2 - Se mesmo assim eu optar por baixar os materiais no celular, depois eu tenho todo um trabalho pra enviar esses arquivos pro pc

Quando finalizo um curso pelo celular, eu tenho que entrar no pc, procurar o curso, e entrar em aula por aula que disponibiliza material para baixa-los, uma solução que vejo ideal para isso, é na pagina principal do curso, um botão para download de todos os materiais de uma vez ou separa-los por módulos (pra não precisar baixar o mesmo arquivo caso eu já tenha baixado algum modulo)

No mesmo tópico eu acredito que um material de apoio para cada módulo seria muito interessante, um pdf com tópicos e alguns detalhes para consolidar o conhecimento caso o aluno queira revisitar o conteúdo sem precisar acessar os vídeos novamente, principalmente em relação aos cursos mais teóricos, como por exemplo os de UX que eu estou estudando, passei por uns 3 cursos que são somente teoria, (muito bacanas e completos) mas pra que eu possa revisitar algo novamente eu preciso lembrar o tópico e reassistir o vídeo.

**Comment by andradeisadora** [comment]
oi @Rimandias obrigada pelas sugestões! Faz sentido esse botão de download de todos os conteúdos juntos.
não estamos com planos de mexer nas telas de aula no momento, mas no futuro quando revisitarmos essa feature levaremos em consideração suas sugestões :)

Sobre a última parte que você falou do pdf com tópicos, você pode usar o Notion pra ir fazendo anotações dos pontos que achar interessantes pro seu estudo. Lá você pode criar páginas, colocando os links dos cursos e abaixo as anotações, assim pode te ajudar quando precisar relembrar algum assunto.

abraço e bons estudos!

**Comment by andradeisadora** [comment]
Estou fechando a issue mas pode voltar a comentar se quiser :)
