### ISSUE TITLE
Rankeamento geral com posições

### ISSUE THREAD

**Issue by mdx153** [caelum/alura-funcionalidades#591]
Seria interessante criar ou alterar o ranking geral, para deixar igual a um rank de jogo mostrando o 1º até o ultimo colocado. creio que isso seria uma forma de fazer varias pessoas se esforçar para ficar em uma posição boa(entre os primeiros), por natureza nois seres humanos somos competitivos. poderia ter um lugar na pagina mostrando os top 5 geral,do mês e da semana.

**Comment by andradeisadora** [comment]
oi @mdx153 obrigada pela sugestão! Faz sentido sim melhorar o ranking e gamification
Estamos com outras tarefas com prioridade maior no momento por isso não temos planos pra ajustar por agora. No futuro quando revisitarmos a feature levaremos em consideração suas sugestões :)

abraço e bons estudos!

**Comment by andradeisadora** [comment]
Estou fechando a issue mas pode voltar a comentar se quiser :)
