### ISSUE TITLE
Certificados em inglês

### ISSUE THREAD

**Issue by jorgecardosorabello** [caelum/alura-funcionalidades#592]
Com os certificados divulgamos nossos conhecimentos adquiridos durante os cursos no LinkedIn.
Mas como podemos divulga-los se são emitidos apenas em português?
A Alura tem alcance internacional agora precisa internacionalizar os certificados! 
Por isso sugiro um pequeno checkout antes de emitir o certificado, podendo escolher entre português e inglês.

**Comment by designernatan** [comment]
oi jorge, valeu pela sugestao!

uma [issue semelhante foi feita aqui](https://github.com/caelum/alura-funcionalidades/issues/560)

em suma: estamos para melhorar a experiência relacionada aos certificados no futuro, por hora você consegue traduzir colocando o ?en no final :)

**Comment by jorgecardosorabello** [comment]
Obrigado pela atenção Natan, mas no meu caso, e da turma que está participando do programa da Oracle ONE, o certificado fica com erro. Ele traduz o nome do curso, as horas tudo, mas a imagem de fundo não aparece

https://cursos.alura.com.br/user/jorgecardosorabello/course/business-model-canvas/certificate?lang=en

**Comment by designernatan** [comment]
opa aí é bug mesmo, vamos dar uma olhada, valeu jorge!

edit:
algo rapido para resolver de imediato seria usar o certificado formal tbm:
https://cursos.alura.com.br/user/jorgecardosorabello/course/business-model-canvas/formalCertificate

de qlq forma, foi pro backlog para darmos uma olhada!

**Comment by designernatan** [comment]
@jorgecardosorabello galera corrigiu, tanto lang=en quanto espanhol

valeu1
