### ISSUE TITLE
Boa tarde, apenas uma sugestão, seria muito interessante se ao terminar uma formação o site oferecesse um certificado completo da formação em si, com todos os cursos concluídos, é meio decepcionante terminar uma formação inteira e ter apenas aquela mensagem padrão que já fica disponível para todos verem antes mesmo de terminar qualquer formação.

### ISSUE THREAD

**Issue by Dahlindsg** [caelum/alura-funcionalidades#593]
Boa tarde, apenas uma sugestão, seria muito interessante se ao terminar uma formação o site oferecesse um certificado completo da formação em si, com todos os cursos concluídos, é meio decepcionante terminar uma formação inteira(de mais de 100 horas)e ter apenas aquela mensagem padrão que já fica disponível para todos verem antes mesmo de terminar qualquer formação.

**Comment by andradeisadora** [comment]
oi @Dahlindsg obrigada pela sugestão!
A conclusão de formação é uma etapa que precisa ser melhorada mesmo, mas infelizmente não está no nosso radar no momento. 

Você pode pegar o certificado de todos os cursos da formação no certificado completo. Lá você tem o certificado separado pelas formações e se quiser salvar somente com uma é possível ocultar as outras:
![image](https://user-images.githubusercontent.com/84100505/147276356-9e429fd0-c7c2-4f3a-a131-b9220fbe3d02.png)

Enquanto você não completar a formação, os cursos que você ir concluindo ficam embaixo:
![image](https://user-images.githubusercontent.com/84100505/147276487-913f8f5c-e7a5-4672-b795-ee8df0da3d44.png)

Spoiler: logo teremos novidades nos outros certificados, fica de olho :)

abraço e bons estudos!

**Comment by andradeisadora** [comment]
estou fechando a issue mas pode voltar a comentar se quiser :)
