### ISSUE TITLE
Conseguir visualizar nas novidades apenas cursos ou alura+, posts, etc.

### ISSUE THREAD

**Issue by devthiart** [caelum/alura-funcionalidades#594]
Acredito que seria bacana na página de novidades conseguir visualizar apenas alguns tipos de novidades, como só cursos ou cursos e alura+. Não necessariamente na notificação, mas na página https://cursos.alura.com.br/explore.

**Comment by andradeisadora** [comment]
oi @devthiart obrigada pela sugestão!
Nas novidades divulgamos os conteúdos que entram novos na plataforma para todos os alunos. Se tirarmos conteúdos além de cursos e alura+ das novidades, vai acabar não atingindo mais os alunos que consomem esses conteúdos.

Você pode filtrar esses conteúdos no aluraflix, lá tem seções de alura+ e cursos recomendados conforme o que você anda estudando:
![image](https://user-images.githubusercontent.com/84100505/147277718-e9aa7428-9587-4991-aaf3-b7f9a707983c.png)
![image](https://user-images.githubusercontent.com/84100505/147277761-b278c9da-9e03-478b-8ad1-06cdfdf2bf5a.png)

abraço e bons estudos!

**Comment by andradeisadora** [comment]
estou fechando a issue mas pode voltar a comentar se quiser :)
