### ISSUE TITLE
Alura retrô 2021

### ISSUE THREAD

**Issue by Lucimar10** [caelum/alura-funcionalidades#595]
Vocês apresentaram um resumo de todas as nossas atividades executadas neste ano de 2021, como a escola mais explorada, quantos artigos lidos, cursos concluídos, etc. 
Gostei bastante, isso permite observar o nosso desenvolvimento e até pensar em estratégias de estudo. Minha sugestão é para a ideia ser fixa na plataforma Alura. Talvez mostrar um resumo desse a cada mês ou a cada trimestre. 
Exemplo: o Duolingo, plataforma de ensino de idiomas, fornece resumos da evolução dos seus estudantes a cada mês por e-mail, algo semelhante com o Retrô 2021 criada pela equipe Alura. 
Ter esse resumo da produtividade é ótimo!
Bem, essa é a minha sugestão. Será que há pessoas aqui que pensam igual a mim?

**Comment by andradeisadora** [comment]
oi @Lucimar10 obrigada pela sugestão!
A retrospectiva é uma ação do final do ano, assim como você mencionou, para o aluno visualizar o próprio desenvolvimento. Não estamos com planos pra fazer a retrô com mais frequencia durante o ano mas atualmente você consegue ver preenchido abaixo da sua pontuação os dias que você estudou:
![image](https://user-images.githubusercontent.com/84100505/147280361-7e15d193-cac3-4457-bdb7-1375bc3b833a.png)

cada cor é referente a uma pontuação diferente, aqui está da mais baixa (esquerda) pra mais alta (direita):
![image](https://user-images.githubusercontent.com/84100505/147280495-fa354e57-7e3b-4b6c-b99f-7f7b548f8e62.png)

Você pode ir marcando no notion ou no excel os dias de estudo e o que você estudou também.

No futuro quando revisitarmos a feature de gamificação e engajamento do aluno levaremos em consideração suas sugestões :)

abraço e bons estudos!

**Comment by andradeisadora** [comment]
estou fechando a issue mas pode voltar a comentar se quiser :)
