### ISSUE TITLE
Dar reset em uma formação

### ISSUE THREAD

**Issue by bettercallvithor** [caelum/alura-funcionalidades#596]
Poderia ter uma funcionalidade em dar reset em alguma formação já completa.
Como por exemplo a Formação Certificação Java, onde se estuda o que precisa para retirar a certificação Java OCA.
Talvez alguém venha a fazer essa formação e completa-la, mas não irá fazer a prova. O certificado desta formação em si não irá valer muito, sem a certificação do Java OCA.
Poderia ter uma função no qual resete a formação, e caso haja um interesse de refazer futuramente, começar do zero de novo.
E antes de alguém for deletar/resetar alguma formação, adicionar alguma forma de segurança para ser seguida, para não ser resetada sem querer.

**Comment by designernatan** [comment]
@otinti valeu pela sugestao!

tem uma [issue igual a essa aqui](https://github.com/caelum/alura-funcionalidades/issues/11)

vou fechar esta por conta disso, mas em suma estamos vendo de como melhorar a experiência de vocês na hora de refazer um curso/formação

ainda é bem nebuloso pra gente a solução, uma vez que quando você estuda uma formação mais de uma vez basta refazer os cursos (e os cursos sempre voltam onde vc parou, completado ou não)

Pode me mandar o link do seu perfil da alura dps? (pergunto mais por pesquisa mesmo)

abcs!

**Comment by bettercallvithor** [comment]
Aqui está o perfil: https://cursos.alura.com.br/user/vithortinti

A formação que eu justamente queria resetar é a **Formação Certificação Java**

**Comment by designernatan** [comment]
valeu vithor!

e continuando com a micro-pesquisa aqui hahah

com relação a forma de como funciona hoje, ela não é o ideal por qual motivo exatamente?

abcs!

**Comment by bettercallvithor** [comment]
Não digo que não é uma forma ideal, o jeito de como funcionam os cursos e formações da Alura são ótimos e fico feliz de poder estudar dentro dessa plataforma.

Mas creio que tendo uma função dessas poderá melhorar os estudos das pessoas que por algum motivo pararam no meio daquela formação ou curso _( 1 )_, e também manter o progresso e data correta da pessoa registrado nos certificados _( 2 )_.

Exemplos:
- Vamos supor que alguém pare no meio de uma formação, fica um bom tempo sem estudar aquele conteúdo e volta com o objetivo de completa-lo, não lembrando do que foi passado e refazendo desde o zero. Os exercícios no qual ela já passou dentro do formação, já estarão resolvidos e já irá ter as respostas marcada imediatamente, com consequência de já os terem feitos anteriormente, e agora sem um desafio para ser resolvido sobre o que foi visto naquela aula/curso _( 1 )_. 

- E também registre o progresso da pessoa no tempo certo dela de aprendizado: se ela parou tal formação no meio e voltou depois de um longo período e não lembra do que foi passado, pode refazer formação do zero, resetando toda a formação, e mostrando nos certificados o tempo desde que foi resetado até o tempo terminado_( 2 )_.

E caso ela não queira mais ter aquele certificado na mão, apenas possa remove-lo.

Os cursos eu sei que podemos sair deles antes de completa-los, e voltar a fazer com a data marcando desde quando voltamos. Mas o progresso ainda fica marcado, e como eu disse, pode tirar um pouco de desafio nos exercícios por estar refazendo.

Apenas podendo ter a possibilidade de começar tudo de novo desde o zero, sem nenhum registro do que foi feito antes.
