### ISSUE TITLE
Certificado em inglês

### ISSUE THREAD

**Issue by luigiMinardi** [caelum/alura-funcionalidades#598]
Como alguém que vive no exterior eu acho necessário que exista a opção dos certificados em inglês. E acho que é uma feature necessária para todos, visto que o mercado de programação é muito globalizado e trabalhar a distância é algo comum.

**Comment by designernatan** [comment]
fala luigi, valeu pela sugestao!

uma [issue semelhante foi feita aqui](https://github.com/caelum/alura-funcionalidades/issues/560)

em suma: estamos para melhorar a experiência relacionada aos certificados no futuro, por hora você consegue traduzir colocando o ?en no final :)

**Comment by luigiMinardi** [comment]
Então fica a sugestão de enquanto ainda não tem esse "grande update" relacionado as línguas, colocar um botão de "traduzir para" e você clica "ingles" ou "espanhol" e redireciona pro "?lang=en" ou "?lang=es"

**Comment by designernatan** [comment]
opa algo assim tá nos planos sim!!

**Comment by andradeisadora** [comment]
oi pessoal, estou fechando a issue mas podem voltar a comentar se quiserem :)
