### ISSUE TITLE
Exercicios após cada aula

### ISSUE THREAD

**Issue by camposl** [caelum/alura-funcionalidades#599]
Eu sei que vocês podem dizer ja existem exercicios mas fazer o mesmo exericio que acabamos de ver é simples, na maioria das vezes faço junto com o professor enquanto vou passando porque fixa melhor mas o mais interessante mesmo seria um exercicio após cada aula ,com correção ,diferente do que foi passado durante a mesma para conseguirmos nos desafiar e aprender mais. Esses exercicios não precisam ser obrigatorios para concluir o curso mas quem se interessar vai conseguir consolidar melhor o conhecimento, e como a maioria das aulas são rapidas não ficaria um exercicio tão longo.
Acridto que isso se encaixe principalmente em cursos basicos.
Muito obrigado.

**Comment by designernatan** [comment]
@camposl valeu pela sugestao lucas!

temos esse desafio de deixar os exercicios mais mão na massa e empolgantes tbm, por isso criamos o Alura Challenges

tá quase acabando o de front-end e tá para começar o de back-end, vale dar uma olhada ali e interagir no discord tbm

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
