### ISSUE TITLE
Certificados em língua inglesa

### ISSUE THREAD

**Issue by mxeliezer** [caelum/alura-funcionalidades#6]
Vivemos em um **mundo global** e nossas fronterias estão para além do território nacional e, portanto, da língua portuguesa. É muito importante que a Alura reflita isto e possamos agregar valor aos nossos cerficados junto ao mercado estrangeiro. Portanto a ideia é passarem a oferecer no link '**certificado**' um em **língua portuguesa**, mas também o mesmo em versão em **língua inglesa**. Em termos de projeção do documento e da escola Alura, o ganho será incomparável.

Para reforçar: estima-se que o português tem entre 215 e 220 milhões de falantes nativos e 260 milhões no total. Enquanto o inglês tem 1,5 bilhão de falantes, cerca de 20% da população da Terra. Fonte:<https://www.babbel.com/en/magazine/how-many-people-speak-english-and-where-is-it-spoken>

**Comment by peas** [comment]
@mxeliezer valeu! a gente realmente nao tem isso automatizado, mas os alunos que precisam do certificado para enfrentar um processo de migração nós temos como fazer enviando um email! esse aqui vai ficar on hold por enquanto mas se tivermos uma necessidade forte de automação voltaremos

**Comment by mxeliezer** [comment]
Entendido. Como eu resido em Portugal, há pouco mais de 4 anos, tenho especial interesse em certificados em inglês. Mas isto não é para agora. Agora o que preciso é aprender cada vez mais. Quando concluir uma formação por completo, aí sim vai ser importante. Valeu pela resposta. Alura / Caelum tem mostrado um diferencial quando o assunto é relacionamento com o cliente final. Valeu!

**Comment by rffontenelle** [comment]
Desculpe-me desenterrar esse tópico, mas entre neste repositório exatamente por essa mesma demanda.  Pergunta: @peas falou em deixar isso "on hold", mas o OP finalizou o pedido. Porém eu tenho interesse. Deveria este *issue* ser reaberto, abro outro ou "deixa quieto"?

**Comment by designernatan** [comment]
@rffontenelle desculpa pelo delay, só dar um upvote na issue do OP já ajuda a gente

a gente fecha a issue mais para não poluir muito aqui na repo

**Comment by babiifranchin** [comment]
Olá, acho muito válido desenterrar esse tópico. 
Eu vivo na Alemanha fazem mais de 2 anos, e tive que solicitar traduções juramentadas meus certificados de faculdade para o alemão para garantir o entendimento, e isso custa bem caro. Caso eles estivessem em inglês, não precisaria ter gasto essa grana.

Como ainda não consegui um emprego na minha área por aqui, tenho bastante tempo para fazer os cursos da Alura. 
Sendo assim, faço cursos diariamente e conquisto certificados como uma certa rapidez. 

Já solicitei uma vez o certificado completo e demorou pouco menos de 1 mês. Tendo isso automatizado (talvez com as traduções inseridas diretamente no curso, quando ele fosse "lançado"), seria mais rápido para gerar os certificados e pouparia um trabalho redobrado dos funcionários da Alura. 

Sempre que vou enviar uma candidatura para alguma vaga de emprego, preciso mandar meus documentos (currículo, certificados, entre outros) o mais atualizados possíveis. E essa funcionalidade seria um extra, não só para mim, como para todos os outros alunos que estão fora ou pretendem sair do país.

Obrigada :)

**Comment by designernatan** [comment]
@babiifranchin faz todo sentido pra mim se tivéssemos isso automático no futuro

por hora e pela demanda desses casos, solução ainda é entrar em contato no contato@alura.com.br solicitando :)

**Comment by gacostafilho** [comment]
Acho que seria muuito boa essa funcionalidade. Eu me inscrevi em um processo seletivo fora do Brasil há uns dias atrás e coloquei o link do meu currículo da Alura, Porém como estava em português acho que nem vão considerar direito, se estivesse inglês teria ajudado muito mais.

**Comment by pablomuro** [comment]
Estou aqui pelo mesmo motivo, como planejo ir pro exterior futuramente, o certificados em inglês seriam perfeitos
não sei como é estruturado o projeto da alura, mas não daria pra fazer um i18n pelo menos na parte de certificados?
muito da estrutura é fixa, e o que muda são os tópicos do curso do certificado

**Comment by Miltonr87** [comment]
Entendo que o processo de automatização não é fácil, mas só reforçando o pedido de tantos outros alunos. Isso aqui não é uma crítica negativa, somente uma chamada de atenção! Infelizmente área tecnológica não há como fugir disso, além do que a própria Alura oferece um pacote de cursos especializado que inclui reforço da língua inglesa, então, essa feature é mais do que necessária.

**Comment by peas** [comment]
Milton, Pablo, voces tem toda razao. Mas é sempre uma questao de priorizacao e tambem dos titulos dos cursos em ingles, alem da ementa as vezes. Será bem dificil mante-los sincronizados.

O que conseguimos oferecer ja agora é, entrando em contato, geramos manualmente esses certificados. O que acha?

**Comment by Miltonr87** [comment]
> Milton, Pablo, voces tem toda razao. Mas é sempre uma questao de priorizacao e tambem dos titulos dos cursos em ingles, alem da ementa as vezes. Será bem dificil mante-los sincronizados.
> 
> O que conseguimos oferecer ja agora é, entrando em contato, geramos manualmente esses certificados. O que acha?

Obrigado pela rápida resposta! Claro, sem problema.

**Comment by babiifranchin** [comment]
Entrei em contato hoje, pelo email contato@alura.com.br, solicitando dois certificados em inglês (gerados manualmente), como anteriormente já solicitei.
E me foi dito que foi aberta uma exceção para mim, naquela época e hoje não é mais possível realizar o procedimento. 
Como devo proceder agora?

**Comment by sahslima** [comment]
Oi, @babiifranchin. 

Vou verificar internamente e retornamos em breve!

**Comment by babiifranchin** [comment]
Obrigada @sahslima

**Comment by priscilaoliveira1** [comment]
Oi @babiifranchin  tudo bem?
Desculpa a confusão, o pessoal de Student Experience já vai entrar em contato com você para ajudar com os certificados, combinado?

**Comment by babiifranchin** [comment]
Sem problemas @priscilaoliveira1, muito obrigada pela atenção :)

**Comment by DKRC** [comment]
Pessoal, 

Um quebra galho que fiz foi usar o [Google Translate. ](https://translate.google.com.br)
Peguei o link do certificado e joguei na ferramenta, depois peguei o link traduzido e coloquei no Linkedin.

O gestor que acessar pode ver o original e tradução.  

@designernatan , um ajuste que pode ser feito no certificado utilizando essa técnica é deixar nenhum texto como imagem.

**Comment by femalves** [comment]
Desenterrando mais uma vez o assunto... 
Eu pedi para a tradução dos meus certificados da Alura para o inglês. O processo foi feito manualmente. 
Veio tudo certinho, mas os nomes do cursos vêm em português, o que na minha opinião não faz sentido. Estou me mudando pros Estados Unidos e o pessoal da imigração não vai entender nada. Vou ter que traduzir de outra forma.

**Comment by leticiavascmachado** [comment]
Também precisarei desenterrar este tópico. Moro na Alemanha e faço mestrado em IA, utilizo bastante o Alura para aprender alguns tópicos de programação, mas cada dia mais estou repensando se não vale a pena investir em outra plataforma, porque os meus certificados precisam estar em inglês e sempre preciso gastar muito dinheiro com tradução juramentada. Sei que devem haver muitas features no backlog e tudo é uma questão de prioridade, complexidade e impacto de negócio, mas inglês é uma língua amplamente falada, além de ser tão **básico** como saber excel hoje em dia. Por isso, ter a possibilidade de emitir certificados em inglês (com o título do curso também em inglês) é uma feature básica para grande parte dos profissionais que estudam TI (sendo esse o público alvo do Alura, acredito eu).

**Comment by designernatan** [comment]
oi @leticiavascmachado 

hoje muitos cursos já estão com a tradução liberada

se os cursos que você estiver concluindo nao tiver, dá uma pingada direto no [contato da alura](https://www.alura.com.br/contato) pfv?

aí o time já consegue direcionar a solução de forma mais eficiente pra vc 

abcs!

**Comment by leticiavascmachado** [comment]
Muito obrigada pela resposta rápida! Vou verificar novamente agora. A
tradução para o inglês, o título do curso também fica em inglês?

Em seg., 17 de jul. de 2023 às 22:00, Natan Souza ***@***.***>
escreveu:

**Comment by designernatan** [comment]
imagina :)

fica sim!
