### ISSUE TITLE
Horas concluídas

### ISSUE THREAD

**Issue by minafrajr** [caelum/alura-funcionalidades#60]
Notei que os cursos possuem a informação de horas. Seria bom exibir as horas concluídas de cada curso ou formação baseada na porcentagem restante de conclusão. Assim ficaria fácil prever o número de horas restantes para conclusão.

**Comment by designernatan** [comment]
oi @minafrajr 

pode elaborar mais com algum exemplo por favor? Só para eu ter certeza que entendi

abcs!
