### ISSUE TITLE
Miniatura ao passar mouse nos vídeos para ter uma prévia do conteúdo, isso ajuda a localizar momentos na aula em que uma ferramenta está sendo usada momento de uma instalação...

### ISSUE THREAD

**Issue by f-mtz** [caelum/alura-funcionalidades#600]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

**Comment by giovana-armidoro** [comment]
oi felipe, valeu pela sugestão!

faz muito sentido, a miniatura pode ajudar bastante nesses casos.
a gente quer num futuro de longo prazo melhorar a tela de aula e quando formos trabalhar nisso vamos levar em consideração suas sugestões, mas sem uma data prevista, ok? 😊

Abraços e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
