### ISSUE TITLE
Formatação do texto dos cadernos e inserção de prints e imagens

### ISSUE THREAD

**Issue by f-mtz** [caelum/alura-funcionalidades#601]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

**Comment by giovana-armidoro** [comment]
oi felipe, mt obrigada pelas sugestões!

no momento não temos planos de melhoria pro caderno... mas você pode organizar seus estudos pelo Notion, a ferramenta funciona muito bem para isso. Inclusive, esse artigo pode te ajudar: [Organizando estudo e portfolio na Alura com Notion](https://www.alura.com.br/artigos/organizando-estudos-portfolio-notion-linkedin) 
eu uso o Notion pra me organizar e recomendo bastante

abraço e bons estudos! :)

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!

---

lembrando que o caderno será desativado em alguns dias, mais informações aqui:
https://suporte.alura.com.br/article/308-meu-caderno
