### ISSUE TITLE
Download dos cardenos em PDF

### ISSUE THREAD

**Issue by f-mtz** [caelum/alura-funcionalidades#602]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

**Comment by giovana-armidoro** [comment]
oi felipe, mt obrigada pelas sugestões!

no momento não temos planos de melhoria pro caderno, mas vc pode ir migrando suas anotações para plataformas de notas como o Notion, Evernote ou mesmo o Google Docs, todas essas ferramentas tem muitas features interessantes e podem fazer o que vc precisa.

Caso queira usar o Notion, esse [artigo](https://www.alura.com.br/artigos/organizando-estudos-portfolio-notion-linkedin) pode te ajudar ;)

abraço e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
