### ISSUE TITLE
Tempo de Estudo por plano & Indicadores de Desafios de Perfomance

### ISSUE THREAD

**Issue by anapaulaxaves** [caelum/alura-funcionalidades#603]
Os cursos são fascinantes e como tem muito conteúdo disponível dentro da plataforma é fácil perder o foco. Minha sugestão é:

### INDICADOR DE TEMPO DE PLANO DE ESTUDO E DESAFIOS DE PERFOMANCE

1. **Criar um indicador que some os tempos STANDARD de conteúdo por plano de curso.**

- No campo "plano de Estudos" o tempo standard (tempo de vídeo, tempo de leitura, etc) apareceria a cada curso  ou conteúdo de leitura selecionado. Ao final d tela, apareceria um indicador com o Tempo total de curso" proveniente da soma de tempos de todos os cursos planejados pelo usuário.

- No Dashboard, na seção "Progresso em Plano de Estudo", poderia ter um indicador com o tempo total Standard somados de todos os planos e um por plano de estudo também.

2. **Criar um indicador que some os tempos PREVISTOS PELO USUÁRIO de conteúdo por plano de curso.**

- Nem sempre o "tempo standard" é o tempo que o usuário quer usar como referência. Ele pode ser mais rápido, por já saber parte do conteúdo selecionado, ou ele pode ser mais lento (gostar de anotar, revisar, etc). Por isso, sugiro a possibilidade de o usuário colocar o tempo que ele quer para realizar o Plano de Estudos ao invés de usar o tempo standard.

- Da mesma forma que os indicadores de "tempo standard", teria um por plano de estudos e um totalizando todos os planos de estudos.

Nota: O tempo standard e o tempo personalizado podem ser opções do usuário. Não recomendo colocar os dois para serem monitorados porque pode ficar confuso.

3. Funcionalidade de "Desafio" ao Planejado
Combinado a esse recurso de tempo, poderia ter no Dashboard, um indicador de desafio pessoal, onde o usuário poderia colocar uma data de coclusão por plano de Estudos. Essa é uma forma de gerar motivação aos estudos e alcance das metas.

- O indicador levaria em conta o progresso do usuário e o prazo estabelecido com zonas em amarelo, verde e vermelho, para ficar bem visual onde o usuário está em relação ao seu objetivo de tempo.

**Exemplo da praticidade desse recurso:** Eu ingressei na Allura porque quero aprender Data Science com foco em Agile. Eu estou usando o plano sugerido para Data Science pela Alura, mas sei que deverei incluir algumas coisas que já vejo como necessidade no meu dia-a-dia. Meu plano seria fazer o curso em 6 meses, para no segundo semestre começar uma pós-graduação e o curso de Pyton, pois tenho um projeto importante dentro do meu trabalho que demandará conhecimento desses recursos para 2023. Ao montar um plano é necessário planejamento, não somente do conteúdo como também do tempo para conclusão essas funcionalidade que estou sugerindo seriam bastante úteis para alcançar meus objetivos.

**Comment by designernatan** [comment]
@anapaulaxaves desculpa pela demora em dar um reply, e obrigado pelos detalhes! Vou tentar comentar tudo:

# Sobre horas no PDE
1. Acho bacana termos algo assim sim. Como a Isa aqui do time comentou [nessa outra issue](https://github.com/caelum/alura-funcionalidades/issues/589), pelo menos **por enquanto,** não estamos com melhorias futuras planejadas nessa parte da Alura, mas gosto bastante da ideia!
2. Tanto a qtde de horas individual por PDE quando a somatória de tudo faz sentido sim.
3. Aproveitando: hoje como você estuda? As horas do último curso ou da última Formação que você fez impactaram nos seus estudos de qual forma exatamente?

# Customizar as horas
1. Bacana isso também e concordo contigo. Uma coisa é o sistema somar tudo e falar que dá 100h para concluir algo, outra coisa é eu ver um curso em 1.5x, não ler artigos, ouvi 2x os podcasts etc.

# Deadline
1. Pessoalmente gosto quando tenho datas para concluir algo pois me deixa com o foco maior. Algo que quero fazer inclusive é uma sugestão de deadline para várias tasks (diárias e trimestrais). Por ex: um Notion que me mostre % de um curso/livro e quão próximo da realidade é isso se eu me dedicar X horas/semana. 
2. Um receio que temos de puxar algo assim na Alura é acabar desmotivando mais do que motivando, pois algumas pessoas trabalham bem com prazos, outras nem tanto, e outras tem o efeito contrário: já que não consegui até agora, então vou deixar pra lá. Talvez algo que ative/desative isso ajude, mas ainda assim é algo sensível pra muita gente.
3. Opa valeu por compartilhar esse seu planejamento! Pode me explicar (mesmo que por cima) como hoje você tem se organizado em cima desse plano? Quais ferramentas, estímulos, rotina, etc?

Valeu :)

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
