### ISSUE TITLE
Apostila

### ISSUE THREAD

**Issue by jeff-n-g** [caelum/alura-funcionalidades#604]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

Seria legal se os cursos tivessem apostilas, mesmo que fossem apenas a transcrição das palavras do professor (como já tem) mas agrupadas em um único documento pra facilitar a consulta. Porque as vezes você quer rever uma coisa bem específica que esta perdida no meio de um aula, e encontrar isso leva muito tempo.

**Comment by designernatan** [comment]
@NewJeff2022 valeu pela sugestao!

essa é uma boa e bem desafiadora também, quando pegarmos a tela de aula para melhorarmos vamos discutir a possibilidade de algo assim ok?

de bate-pronto, você pode usar a busca que fica na tela de aula (já disponível hoje) para encontrar o que precisa

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
