### ISSUE TITLE
Challenges antigos

### ISSUE THREAD

**Issue by rodrigobcunha** [caelum/alura-funcionalidades#605]
Os challenges são uma ótima forma de por em prática o que aprendemos nos cursos, porém poderia ter uma opção de acessar os challenges anteriores. 
Sei que pelo discord tem como acessar os cards do trello dos challenges antigos, mas seria uma boa ter essa opção por dentro da plataforma.

**Comment by designernatan** [comment]
@rodrigobcunha valeu pela sugestao!

estamos vendo algo para ajudar nisso, espere novidades esse semestre :)

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!

---

edit:
elaboramos uma página com todos os challenges passados! Só acessar direto pelo menu da plataforma Conteúdo -> Challenges

depois me conta o que achou @rodrigobcunha ?
