### ISSUE TITLE
Emitir certificados personalizados

### ISSUE THREAD

**Issue by guilhermevictorlima** [caelum/alura-funcionalidades#606]
Seria extremamente interessante a possibilidade de emitirmos certificados personalizados com os cursos que queremos. A principal vantagem nisso seria mostrar o certificado em outras plataformas (como Linkedin), sem precisar exibir o certificado completo.

**Comment by andradeisadora** [comment]
oi @zsGuil obrigada pela sugestão!
hoje você consegue emitir o certificado de cada curso e formação assim que concluídos.

na tela do curso você vai ações e certificado:
![image](https://user-images.githubusercontent.com/84100505/151814568-a2660ca1-0887-4a00-b358-747b8c8a9bd8.png)

ou no seu perfil você encontra os seus cursos concluídos, lá vc pode clicar em certificado que ele gera na hora pra vc:
![image](https://user-images.githubusercontent.com/84100505/151814911-6640ad4e-2cf3-4d29-85bd-b71d9bd9bbe5.png)

abraço e bons estudos!

**Comment by lordeLeo** [comment]
Seria muito interessante a possibilidade de termos a opcao do certificado em outras linguas( especialmente em ingles).
Uso a Alura fora do Brasil e aplicando para a vaga de emprego ou adcionando no LinkedIn ajudaria muito.

**Comment by designernatan** [comment]
@lordeLeo 
uma [sugestão semelhante foi feita aqui](https://github.com/caelum/alura-funcionalidades/issues/560)

em suma: estamos para melhorar a experiência relacionada aos certificados no futuro, por hora você consegue traduzir colocando o ?en no final :)

**Comment by lordeLeo** [comment]
desculpa,colocar ?en aonde?On Mar. 2, 2022, at 10:44 a.m., Natan Souza ***@***.***> ***@***.*** uma sugestão semelhante foi feita aquiem suma: estamos para melhorar a experiência relacionada aos certificados no futuro, por hora você consegue traduzir colocando o ?en no final :)—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by designernatan** [comment]
@lordeLeo 
expliquei certinho [aqui](https://github.com/caelum/alura-funcionalidades/issues/560#issuecomment-948091459), mas é só colocar o ?lang=en no fim da URL do seu certificado

ex:
https://cursos.alura.com.br/user/paulo-silveira/course/design-patterns/certificate?lang=en

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
