### ISSUE TITLE
Clarear texto da resposta

### ISSUE THREAD

**Issue by Elailson** [caelum/alura-funcionalidades#607]
Quando utilizando o modo noturno, o texto de explicação da resposta fica com uma cor que dificulta um pouco a leitura, como mostrado na imagem abaixo:

![image](https://user-images.githubusercontent.com/7353269/150866700-7065f305-ce44-4834-addc-82024425150f.png)

Acredito que colocando a cor branca ajude, como mostrado na imagem abaixo (alterei através do CSS do navegador):

![image](https://user-images.githubusercontent.com/7353269/150867502-a3e733e8-5cbd-4d3e-ab50-a8715e233bd3.png)

**Comment by andradeisadora** [comment]
oi @Elailson faz total sentido ajustarmos esse contraste, obrigada pela sugestão! :)

estamos com planos pra no futuro melhorarmos o dark mode da plataforma mas sem prazo por enquanto

abraço e bons estudos!

**Comment by designernatan** [comment]
oi pessoal,

corrigimos a contraste desse texto para casar com a wcag:

![image](https://user-images.githubusercontent.com/5431347/164527143-b2bc6f64-57e1-44ce-a605-a830af75f856.png)

o branco apesar de resolver bem pode cansar a vista pq tem brilho demais, colocamos o cinza #767e85 conforme print e o fix deve subir nos próximos dias

abcs!
