### ISSUE TITLE
Melhoria na busca por cursos no dashboard

### ISSUE THREAD

**Issue by eduardosramos** [caelum/alura-funcionalidades#608]
Salve, pessoal.

Minha dica de melhoria seria no campo de busca por cursos no **já no dashboard**. A lupa fica lá em cima e eu fiquei quase uns 30 seg para achar; minha esposa ficou um tempão tbm pra encontrar, isso pq eu falei que ela precisava achar uma lupa. Ou seja, não é intuitivo. 

A dica é que fique numa barra semelhante ao da Microsoft learn, é uma barra maior, quase no meio da página, já na index do dashboard. Depois que vc acha a lupa e manda buscar há uma estrutura semelhante a que descrevi, mas o lance é no início, entendem?

Espero ter contribuído.

Abraços.

**Comment by giovana-armidoro** [comment]
oi, Eduardo! muito obrigada pela sugestão! :) 

concordo que podemos melhorar, temos planos futuros pra fazer melhorias na busca e quando formos fazer isso vamos levar sua sugestão em consideração. 

abraços bons estudos!

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
