### ISSUE TITLE
Legenda no vídeo

### ISSUE THREAD

**Issue by emanuelhm** [caelum/alura-funcionalidades#609]
Estou cursando a "Formação React JS" e uma coisa que eu prestei atenção foi a diferença entre o curso "JavaScript: Programando a Orientação a Objetos" e o curso "JavaScript: Interfaces e Herança em Orientação a Objetos".

No primeiro curso da formação o áudio e claro e a Transcrição da aula é diferente, tem mais dados, exemplos de código etc. Isso fazia com que após cada aula eu desse uma lida nos códigos e nos outros dados para absorver melhor a matéria.

Já no segundo curso o áudio tem problemas e por isso a Transcrição é uma legenda direta do que é dito pelo professor, o que gera uma grande dificuldade ao seguir a aula (ver os códigos) e ler a transcrição (pois tive dificuldade de ouvir o que o professor dizia sem um fone de ouvido). Isso não seria problema se eu tivesse um fone de ouvido de prontidão ou dois monitores (o que não era o caso no momento).

Esse problema seria facilmente resolvido se ao invés de colocar na transcrição a legenda da aula fosse colocado na tela, facilitando o entendimento do aluno enquanto visualiza a aula, deixando claro todas as palavras do professor e ainda permitindo que a Transcrição tenha dados como snipets do código, comentários, atualizações sobre a linguagem/framework etc.

**Comment by designernatan** [comment]
@emanuelhm obrigado pela sugestão

tem [uma outra issue sobre legendas aqui](https://github.com/caelum/alura-funcionalidades/issues/10), com o reply do Paulo

hoje realmente temos esses dois modelos, mas estamos estudando como esses modelos de transcrição podem ser mais eficientes

**Comment by ghost** [comment]
A legenda no vídeo ajuda pessoas que possuem perda auditiva a terem uma melhor compreensão, e isso nos dias de hoje se chama inclusão.

Mesmo tendo a transcrição do vídeo em forma de texto, como está hoje, logo abaixo do vídeo, na minha experiência, isso não ajuda muito quando você não compreende o áudio, porque preciso pausar o vídeo, e procurar aonde está o texto referente ao momento do vídeo.

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
