### ISSUE TITLE
Bug menu das aulas - ALURA

### ISSUE THREAD

**Issue by thalesgarcia** [caelum/alura-funcionalidades#61]
No menu, ao clicar fora do ícone para expandir e depois clica no ícone para recolher o menu, o ícone fica invertido. 
Imagens explicando como fica
![tela2](https://user-images.githubusercontent.com/46924829/74170673-0f67c980-4c0c-11ea-82d7-a4d817e27791.png)
![tela1](https://user-images.githubusercontent.com/46924829/74170676-11318d00-4c0c-11ea-871e-3bfe2df98685.png)

**Comment by designernatan** [comment]
oi @thalesgarcia 

obrigado pelo feedback!

nao consegui reproduzir aqui esse bug, vc ta usando qual browser/versao/sistemaOperacional

sempre dá isso em qualquer curso com você? Recarregando a página fica normal?

abcs!

**Comment by thalesgarcia** [comment]
Boa tarde Natan, tudo bem ?
Eu uso o firefox, na ultima versão e esse bug da de vez em quando,
atualizando a pagina, tudo volta ao normal.
Já aconteceu algumas vezes comigo, não é sempre.
Mandei para vocês porque vai que isso acontece com mais alguém.
De resto, tudo perfeito.

Eu clico no icone para "recolher o menu", depois clico em atividades ou no
aula XX de xx para expandir o menu, e depois clico para recolher o menu de
novo para o player ficar maior. As vezes da esse bug.

Atenciosamente

Thales Garcia

Em seg., 10 de fev. de 2020 às 14:51, Natan Souza <notifications@github.com>
escreveu:

**Comment by designernatan** [comment]
beleza thales, mto obrigado pelo report!
