### ISSUE TITLE
Acompanhamento pedagógico com os alunos.

### ISSUE THREAD

**Issue by mathrpcdev** [caelum/alura-funcionalidades#610]
O grupo Alura poderia selecionar instrutores que acompanhem grupos de alunos mais de perto para que as dúvidas desses alunos sejam sanadas de forma mais rápida e o ensino seja de maior qualidade.
Ex: Enquanto um aluno passa a tarde toda tentando indentificar um erro simples em um código,  com aulas em horário fixo ou com instrutores dedicados, isto é,  disponíveis para dar aula ou tirar dúvidas,  o ensino-aprendizagem desde aluno será qualitativamente melhor.
O ideal seria ter intrutores divididos em horários da manhã, tarde e noite pois muitos de nós trabalhamos e estudamos em horários diversos.

Assim, com o acompanhamento dedicado desses instrutores com esses alunos o ensino-aprendizagem alcançaria outros níveis. O aluno não desmotivaria com mais facilidade e os instrutores/Alura identificaria os problemas pedagógicos de ensinar e aprender à distância, tal como melhorar a qualidade do produto que a Alura dispõem. 
Inclusive, concorrentes já fazem isso, além de disponibilizar as aulas previamente gravadas.

Tenho certeza que toda a comunidade aprovaria e todos sairiam ganhando! 
Avante! ❤

**Comment by designernatan** [comment]
@rodriguesmatpc valeu pela sugestão!

O encontro síncrono é algo mais pessoal pois tem um envolvimento maior face-to-face, a Alura nasceu do síncrono na Caelum. Fizemos o Bootcamps Alura pensando nisso, tentando aproximar aquele contato dos alunos e alunas com a pessoa instrutora.

Na Alura em si, esse modelo não escala como produto pois temos muitas pessoas instrutoras com dezenas de cursos, o que tomaria 100% do tempo dela e pior ainda: ela não conseguiria gravar mais aulas e melhorar os cursos que já estão lá.

Pensando nisso que temos o Scuba Team, um time focado e em um esquema leve de turno, que fica a postos para ajudar com as dúvidas dos cursos e até de carreira. A ferramenta hoje mais direta hoje para isso além do fórum é o Discord exclusivo da plataforma, onde fica todo mundo lá (as vezes até alguns instrutores respondem lá).

Desculpa o textão e qualquer dúvida só falar :)

Abcs!

**Comment by designernatan** [comment]
Um vídeo legal sobre o Scuba Team:
https://www.youtube.com/watch?v=aJPSfbxiC_g

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
