### ISSUE TITLE
download

### ISSUE THREAD

**Issue by lordplentz** [caelum/alura-funcionalidades#611]
Estava navegando nas formações e verifiquei que não tem a função de baixar o conteúdo das formações e se não for possível baixar somente os episódios dos podcast e que depois que ouvido de maneira off-line eles terem a sincronia com o online assim que pega a internet

**Comment by giovana-armidoro** [comment]
oii @lordplentz muito obrigada pela sugestão!

Você conhece o app da Alura? Por lá você consegue fazer download dos cursos e assistir off-line.

É só vc instalar o app da Alura, ir na página do curso e clicar no ícone para fazer download (1), aí é só baixar todos os vídeos (2) e você já pode assistir off-line. Os cursos que você baixar vão aparecer na Dashboard na seção "Meus downloads" (3).

![image](https://user-images.githubusercontent.com/92942899/152346073-740bc36b-4ef1-46b2-879a-63fc9feb2b0f.png)

qualquer dúvida é só falar,
abraços e bons estudos!

**Comment by lordplentz** [comment]
Bom dia Giovana, sim eu fui informado sobre essa funcionalidade mas por
exemplo os podcast não tem a opção de download somente os curso.
E se você está fazendo uma trilha de formação aparecerá não somente cursos
como vídeos do Alura+ e episódios de podcast.

**Comment by giovana-armidoro** [comment]
oii, faz sentido mesmo, hoje ainda não temos essa funcionalidade mas é uma ótima observação
quando formos fazer melhorias relacionadas a isso vamos discutir em cima da sua sugestão
muito obrigada!!

abraços e bons estudos :)

**Comment by lordplentz** [comment]
Muito obrigado de nada

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
