### ISSUE TITLE
Possibilidade de fazer uma prova de conhecimentos e concluir o curso sem a necessidade de ver todas as aulas.

### ISSUE THREAD

**Issue by johngna** [caelum/alura-funcionalidades#612]
Seria muito interessante poder concluir toda uma formação fazendo provas que validassem o conhecimento do aluno em cada curso que compõe uma formação sem a necessidade dele assistir todo o conteúdo.

**Comment by designernatan** [comment]
@johngna valeu pela sugestão!

antigamente tínhamos os projetos na alura que envolvia um teste rápido, mas adesão era extremamente baixa mas não tinha essa compensação como você sugeriu

uma dúvida: não assistindo todo o conteúdo de uma Formação e fazendo uma prova que a compense, qual seria o objetivo no fim? 

por hora não temos planos de puxar algo assim no futuro, mas se puder me contar um pouco mais seria muito bacana!

abração!

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
