### ISSUE TITLE
Criação de um serviço de indicação 

### ISSUE THREAD

**Issue by alvesskaio** [caelum/alura-funcionalidades#613]
Essa funcionalidade geraria um link do usuario, assim ele poderia enviar para os amigos e os dois  ganhariam algum benéficio, tipo, se você for indicado ganha 10% de desconto e tals e o usuario que envio receberia algum bonus.

**Comment by designernatan** [comment]
@alvesskaio valeu pela sugestao!

desconto voce sempre pode negociar com o time de vendas, só explicar a situacao, tamanho do grupo, etc. Caminho mais direto é pelo [contato normal](https://www.alura.com.br/contato) mesmo, blz?

sobre a feature em si, normalmente fazemos na época da black friday, inclusive com prêmios para quem indica mais (primeiro lugar ano passado foi um switch oled por ex)

---

**por hora** nao temos planos de fazer isso full time, mas eventualmente puxamos essa discussao

abcs!

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
