### ISSUE TITLE
não sair do modo tela cheia ao avançar as aulas

### ISSUE THREAD

**Issue by Ariiaimee** [caelum/alura-funcionalidades#614]
Ao inicializar cada aula, o reprodutor de vídeo sai automaticamente do modo tela cheia, acredito que salvo a exceção da sequência aula -> atividade/comentário do instrutor -> aula, seria fácil de resolver e manter as sequencias de aula todas no modo tela cheia. Não é algo que exija muita mudança e fica mais confortável pra quem assiste nao ter a necessidade de ficar mudando o modo toda aula que inicia. É como se resetasse a velocidade de reprodução das aulas, que no caso não ocorre e é ótimo não ficar personalizando isso a cada aula que começa (imagina nos casos de aulas curtas, a cada 5min ter que colocar em tela cheia) 
vcs são ótimos, agradeço desde já  <3

**Comment by designernatan** [comment]
@Ariiaimee valeu pela sugestao!

Tem uma [issue semelhante aqui](https://github.com/caelum/alura-funcionalidades/issues/528) e ainda vale o comentário da Laís na época: queremos e gostamos de algo assim, mas por hora sem planos para puxarmos uma melhoria dessas na tela de aula pois provavelmente envolveria refazer a tela como um todo.

Algo que pode te ajudar hoje é ligar o modo teatro (botão do lado do de fullscreen) ou ir dando fullscreen com o atalho F. [Aqui você tem outros atalhos que temos hoje.](https://suporte.alura.com.br/article/324-quais-sao-os-atalhos-de-teclado-nos-videos) Também tem o modo automático que pode dar uma força.

Aproveitando, hoje você estuda na Alura com quantos monitores? Como foi sua rotina de estudos em volta dessa temática da tela de aula em si?

Abração!

ps; time aqui é bão mesmo! :))

**Comment by Ariiaimee** [comment]
Hoje eu uso só um monitor e a minha rotina é tipo maratona, eu deixo tudo
pronto o que preciso pra acompanhar a aula e sento pra fazer *só* isso,
vejo várias aulas em sequência e depois que vejo todo o curso, faço as
atividades e retorno em tempos específicos das aulas pra rever algum passo
a passo ou tirar uma dúvida. Mas só me atrapalha por esse motivo de
maratonar as aulas, o modo teatro é o que eu mais uso, mas os miopes
preferem fullscreen sempre kk

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
