### ISSUE TITLE
Poder filtrar por cursos concluídos quando pesquisar um curso na lupa

### ISSUE THREAD

**Issue by ibsenriou** [caelum/alura-funcionalidades#615]
Por exemplo: há algum tempo concluí todos os cursos da formação de Django e Django Rest; mas gostaria de ver se teria mais alguma coisa relacionada a Django na plataforma que eu possa não ter visto. Hoje, para ter certeza, teria que ir pesquisando os cursos retornados na busca um por um.
Seria legal se fosse possível realizar uma busca e poder escolher ocultar cursos já concluídos.

**Comment by andradeisadora** [comment]
@ibsenriou obrigada pela sugestão :)
Faz sentido mesmo ter o progresso dos conteúdos no momento da busca. Estamos com planos pra essa feature mas no futuro, sem prazo ainda ta?

abraço e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
