### ISSUE TITLE
Favoritar aula

### ISSUE THREAD

**Issue by jpfigueredo** [caelum/alura-funcionalidades#616]
Acredito que se houvesse um meio de favoritar aulas para que pudesse achar com mais rapidez o que procura, pode acelerar o aprendizado proativo por parte do aluno.
Ao invés de precisar lembrar o curso, procurar a seção na qual a aula que ele procura foi colocada, poderia ter uma lista de favoritos com essas 3 informações já disponibilizadas.

**Comment by giovana-armidoro** [comment]
oii João, muito obrigada pela sugestão!

faz sentido mesmo, ajudaria muito a consultar conteúdos específicos que podem ser usados com mais frequência. 
inclusive, tivemos uma outra [sugestão](https://github.com/caelum/alura-funcionalidades/issues/552) bem parecida com essa. 
temos planos futuros para trabalhar em melhorias na dashboard/aula e quando formos fazer isso vamos discutir em cima desse tema.

algo que você pode fazer por enquanto é criar um plano de estudos na plataforma com seus cursos favoritos, ou organizar um plano de estudos por fora da plataforma, que pode ser uma página no Notion, Google Docs (ou outra ferramenta que preferir) com o link das suas aulas favoritas e uma descrição do tema da aula pra facilitar quando for procurar.

abraços e bons estudos :)

**Comment by guilhermebap** [comment]
Gostei muito desse ideia, já passei vários minutos procurando uma aula especifica de um curso para revisar. Espero que adicionem futuramente!

Obrigado

**Comment by kimtiago** [comment]
tambem quero. +1

**Comment by andradeisadora** [comment]
oi pessoal, vou fechar a issue mas podem voltar a comentar se quiserem :)

**Comment by JeffMDA** [comment]
Excelente ideia, pensei nela hoje.
