### ISSUE TITLE
Marcador 

### ISSUE THREAD

**Issue by joaovitorroriz** [caelum/alura-funcionalidades#617]
na pagina  https://cursos.alura.com.br/formacoes
As formações já concluídas poderiam ficar marcadas
Assim como a pagina https://cursos.alura.com.br/alura-mais

**Comment by designernatan** [comment]
@joaovitorroriz valeu pela sugestao!

para eu entender melhor seu cenário: hoje você sente essa necessidade com algum motivo específico? Muitas formações concluídas?

abração!

**Comment by joaovitorroriz** [comment]
Ainda não tenho muitas formações.  
Foi só uma dica como experiência de usuário mesmo.
Entrei na pagina e me perguntei cadê a formação que fiz!
Deixando marcado o usuário pode ver os que não estão marcados e talvez resolver faze-las.

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
