### ISSUE TITLE
Funcionalidade na API Dashboard

### ISSUE THREAD

**Issue by thiagomeneguzzi** [caelum/alura-funcionalidades#618]
A API dashboard é incrível, acredito que seria possível adicionar a ela um outro campo, além de "CourseProgress" e "guides", ter tem cursos já concluídos. Ajudaria bastante na hora de criar um portfólio com esta API. 

Desde já agradeço pela API!

**Comment by designernatan** [comment]
@thiagomeneguzzi valeu pela sugestao meu caro!

vamos dar uma olhada aqui se rolaria :)

inclusive, me conta mais sobre como você tem usado a api? Fico muito curioso em ver como vocês a utilizam

Se tiver print ou algo assim fico te devendo um abraço virtual :)

**Comment by thiagomeneguzzi** [comment]
Beleza! Ainda não desenvolvi nada usando a api, mas vou refazer meu portfólio e nele irei usar a api! Quando estiver pronto mandarei hahah! Abraço virtual ;D

**Comment by thiagomeneguzzi** [comment]
@designernatan Beleza! Ainda não construi nada utilizando a API, mas irei reestruturar meu portfólio e utilizar a API de vocês tbm!! Assim que pronto manda para você. Abraços virtuais ;D

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
