### ISSUE TITLE
Download de cadernos

### ISSUE THREAD

**Issue by DavidSouza99** [caelum/alura-funcionalidades#619]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

Gostaria que fosse possível baixar apenas um cadernos em vez de todos os cadernos que eu já escrevi.

**Comment by designernatan** [comment]
@davidmindinho valeu pela sugestao!

vamos dar uma investigada se rolaria fazer algo assim em tempo hábil e te pingo aqui novamente

edit:
aproveitando, qual seu perfil na alura? Ex: https://cursos.alura.com.br/user/natan-souza

**Comment by designernatan** [comment]
@davidmindinho rolou!

agora você consegue baixar um zip com tudo separado

time de dev da alura é bão d+...

**Comment by DavidSouza99** [comment]
Muito obrigado, até comentei hoje sobre o serviço de vocês durante uma aula
de UX. Gostei bastante, estão de parabéns.

Em sex., 18 de fev. de 2022 às 15:33, Natan Souza ***@***.***>
escreveu:
