### ISSUE TITLE
Pagamento por débito automático

### ISSUE THREAD

**Issue by ffelicio** [caelum/alura-funcionalidades#62]
Gostaria da possibilidade de realizar os pagamentos por débito automático.
Como não tenho cartão de crédito, fico impossibilitado de fazer a assinatura.
Seria legal se vocês colocassem essa funcionalidade, debitando mensalmente o valor para continuar a assinatura.

**Comment by designernatan** [comment]
oi @ffelicio, algumas pessoas também pedem algo assim, obrigado pela sugestão!

ja fizemos alguns testes e o preço saia caro e nao funcionava na retenção e forma que as pessoas usam a plataforma. mas se precisar de um semestral manda um email no contato@alura.com.br que o time do comercial tenta dar um jeito!

abcs!
