### ISSUE TITLE
Mostrar quais cursos o curso selecionado é um pré-requisito

### ISSUE THREAD

**Issue by gmarquesandre** [caelum/alura-funcionalidades#620]
Hoje, ao selecionar um curso que está em uma formação, é fácil localizar qual seria a próxima etapa. Porém, caso não esteja em uma formação, pode não ser tão fácil encontrar qual trilha seguir.

Quando abrimos o curso, é exibido os "pré-requisitos" do curso selecionado, mas não quais cujo o curso selecionado é um pré-requisito. Acredito que seria bem legal ter isto para definir qual o próximo passo.

Exemplo, os cursos de TypeScript:

![image](https://user-images.githubusercontent.com/63166456/154173416-17e7828a-974d-4e31-b079-850e5d285dc7.png)

![image](https://user-images.githubusercontent.com/63166456/154173686-64468f8d-f396-48ec-aaef-6d315d93c515.png)

É um exemplo intuitivo pelo nome ser o mesmo, mas pode haver algum curso que não seja fácil de localizar e seja interessante.

**Comment by designernatan** [comment]
@gmarquesandre valeu pela sugestao!

estamos de olho nisso, espere novidades no futuro de médio prazo :)

abração!

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
