### ISSUE TITLE
Auxilio no plano de carreira - Recomeço de dinossauros

### ISSUE THREAD

**Issue by FlaviaPontoglio** [caelum/alura-funcionalidades#621]
Auxilio na criação do plano de carreira pra velhos profissionais que já estão no mercado a muitos anos e estão estagnados nos conhecimentos por falta de estudo e foco, por estarem em empresas pequenas que ficam paradas no tempo em relação a tecnologias e novas metodologias.

**Comment by designernatan** [comment]
@FlaviaPontoglio obrigado pela sugestão!

## Sobre auxilio na criação de plano de carreira
o que você entende, seria plano de estudos? ou plano de carreira mais geral?

Se for plano de carreira mais geral:
- Aprender sobre "Metodologias Ágeis" - https://cursos.alura.com.br/formacao-business-agility
- Dada a velocidade com que as coisas mudam, é importante "Aprender a aprender" https://cursos.alura.com.br/course/aprender-a-aprender-tecnicas-para-seu-autodesenvolvimento
- Se está buscando recolocação, turbinar seu Linkedin é muito importante,  https://cursos.alura.com.br/course/linkedin-perfil-profissional

---

Agora a questão técnica, uma boa pedida é ficar de olho nas Imersoes que fazemos, a próxima é a [Imersão Dev e está com as inscrições abertas aqui.](https://imersao.dev)

Outro ponto que seria interessante é interagir mais com a comunidade da Alura lá no nosso Discord. Link está dentro da plataforma, no menu de navegação `Comunidade > Discord`

Abraços!

**Comment by FlaviaPontoglio** [comment]
Boa tarde Natan.

Desculpa a demora em responder, esse email não acesso diariamente.
Acho q auxilio de carreira no geral, direcionamento mesmo para onde seguir,
muito tempo na zona de conforto sem estudo ou foco de crescimento, alias
focada na familia.
Vou ler os itens que destacou no email acima.

Obrigada pelas dicas.

Att.

Flavia Pontoglio


Em seg., 21 de fev. de 2022 às 13:25, Natan Souza ***@***.***>
escreveu:

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
