### ISSUE TITLE
Tema escuro Dashboard

### ISSUE THREAD

**Issue by VitorEscher** [caelum/alura-funcionalidades#622]
Olá,

Sou aluno e sou fã da instituição que comecei meus estudos há 1 ano em TI. A Alura me deu suporte para migrar de área compras para TI e inclusive conquistar job como trainee utilizando logica e sql server para consegui-lo.

Contudo, utilizo a plataforma 2-3 horas diariamente e quando entro no meu dashboard sofro bastante com o tema claro pré definido.
Acredito que um otimo recurso que agregaria valor para todos que entram no site seria opçao de escolha entre o tema claro e escuro para que independente de tudo o usário se sinta confortavel visualmente falando.

![alura-darkmode](https://user-images.githubusercontent.com/86751831/154381366-daa460ab-5305-4d60-af23-6bdaffc31745.png)

obs: exemplo simples de como seria invertendo as cores.

Agradeço esse espaço de ideias incrivel, e tenho certeza e a Alura cada vez mais é responsavel por uma geração mais preparada no ramo de tecnologia. Forte abraço.

**Comment by designernatan** [comment]
@VitorEscher valeu pela sugestao!

Essa sugestão já foi levantada algumas vezes por aqui e está sendo avaliada com carinho!

Depois dá uma olhada [nesta discussão aqui](https://github.com/caelum/alura-funcionalidades/issues/156#issuecomment-632410492), tem uma sugestão de como aplicar o darkmode enquanto o oficial não sai

abcs w bons estudos!

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
