### ISSUE TITLE
Desenvolvimento T

### ISSUE THREAD

**Issue by VitorEscher** [caelum/alura-funcionalidades#623]
olá, 

Sou aluno e sou fã da instituição que comecei meus estudos há 1 ano em TI. A Alura me deu suporte para migrar de área compras para TI e inclusive conquistar job como trainee utilizando logica e sql server para consegui-lo.

Adorei a ideia de concretizar o conceito de desenvolvimento em T na Retrospectiva de final de ano, contudo estudando sobre conceito de agil e scrum aqui mesmo neste mês, acredito que uma possivel melhoria seria implementar uma área onde seja acessivel para o usuario ter um feedback em um tempo menor e com isso pode tomar determinadas decisões sobre caminho a trilhar na carreira e na Alura também.

Um menu Alurafeed de repente em um delta de 1 mês seria muito bacana e assim ao comparar o mês a mês com o Anual seria uma otima maneira de ver nosso crescimento em T e evolução.

Agradeço pelo espaço. Forte abraço.

**Comment by designernatan** [comment]
@VitorEscher valeu pela sugestao!

acho que nao peguei bem, vc diz um reply de alguém, fórum por ex? Se for isso hoje tem o Discord que **geralmente** é um pouco mais vivo e orgânico

depois me explica melhor esse lance da comparação MoM YoY? Nao peguei bem

abracao!

**Comment by VitorEscher** [comment]
oi natan

na verdade não tem relçao com o forum ou reply, somente a ideia que sugeri foi usar a retrospectiva que fizem no final de ano mas algo que o aluno possa fazer mensalmente. Assim ele pode ir acompanhando a evolução mes a mes do T dele e no final do ano compara com anual.

se voce procurar a retro alura 2021 fica mais claro de entender o grafico T que tanto compatilhamos nas redes sobre como foi nosso ano de estudos, e seria interessante poder analisar mensalmente ou ate on time como esta nosso progresso.

acredito que pesquisando sobre a retro 2021 alura fica mais tranquilo entender a ideia. somente disponibilizar isso ao aluno para mensal ou diariamente acessar essa retro.

qualquer coisa estou a disposição. abracao

**Comment by designernatan** [comment]
oi vitor, entendi agora, obrigado!

lembro que já sugeriram algo assim aqui e pessoalmente gosto bastante

os gráficos amigáveis da retrô não temos ainda, mas no seu perfil há algumas estatísticas interessantes sobre o uso

---

por hora sem planos de puxarmos algo assim, mas com certeza vamos discutir em cima 

abcs!

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!

**Comment by erikenascimento** [comment]
Também sinto falta desse gráfico, ele poderia estar disponível o tempo inteiro na sessão: Aprofundar > Tech Guide. E você  poderia filtrar entre uma retrospectiva do último ano (da forma que já é) ou ver um overall de todo seu tempo na Alura. Toda vez que comento dessa feature com amigos eles mostram interesse em ver mas quase nunca eu posso motrar pois só está disponível uma vez por ano.
