### ISSUE TITLE
Assinatura compartilhada(plano de amigos/casais/familia)

### ISSUE THREAD

**Issue by followmedoug** [caelum/alura-funcionalidades#624]
Sou Aluno da alura de anos! Sempre gostei muito da plataforma e da forma como vocês ensinam.
Recentemente fui mudar meu plano no spotify para aquele plano de duas pessoas e pensei: nossa, seria legal se a alura tivesse um plano assim.
Já trabalhei em uma empresa que solicitei uma ajuda pra pagar um curso da alura e a empresa fez a assinatura no nome dela e só me passou o acesso, mas e o certificado? fica no nome da empresa?
Seria interessante ter um plano onde pessoas possam dividir a assinatura e cada um ter o seu próprio login, assim ao fazer o curso o certificado ficaria no nome da pessoa que fez!
Essa é a minha ideia, espero ter contribuído de alguma forma, continuem com o trabalho exelente de vocês!

**Comment by designernatan** [comment]
@followmedoug valeu pela sugestao!

o jayson [sugeriu algo semelhante aqui](https://github.com/caelum/alura-funcionalidades/issues/179)

ainda vale o reply do sergio sobre a possibilidade do desconto nessas situações, ok?

---

sobre os certificados: em geral quando a empresa assina ela compra licenças para cada funcionário(a), então você teria seu certificado com seu nome e tudo mais

conversaria com sua chefia se rolaria puxar algo assim

abracao!

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
