### ISSUE TITLE
Filtro na área de "novidades"

### ISSUE THREAD

**Issue by wendeoo** [caelum/alura-funcionalidades#625]
A parte completa de "Novidades" (https://cursos.alura.com.br/explore) apresenta todos os novos cursos, formações, posts, etc em uma lista. Sugiro a implementação de um filtro. Por exemplo, quero filtrar tudo que há de novidades somente em Formações, ou somente Posts, etc.

**Comment by designernatan** [comment]
@wendeoo valeu pela sugestao!

hoje vc sente mais falta disso em qual cenário exatamente? Da ultima vez q vc sentiu falta de um filtro ali, qual era a situação?

estamos vendo umas melhorias no [Aluraflix](https://cursos.alura.com.br/aluraflix) no futuro que talvez vai ajudar nisso :)

abcs

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
