### ISSUE TITLE
um botão de visualizar tópicos que acompanho

### ISSUE THREAD

**Issue by AureoDantax** [caelum/alura-funcionalidades#626]
![image](https://user-images.githubusercontent.com/73717109/156247994-913a9e39-2847-4981-ad77-518427f49cbf.png)

Eu não consigo olhar um tópico que acompanho, quando ele não tem resposta, ou ja foi solucionado, não existe maneira de visualizar o tópico marcado se ninguem responder ele,m e procurar ele no forum novamente, é muito desgastante, então sugiro que criem uma área ou botão que leve aos tópicos que acompanho, assim posso ler novamente ( no caso todo mundo) ou deixar de acompanhar por ali mesmo, sem entrar no tópico novamente
![image](https://user-images.githubusercontent.com/73717109/156248758-750897e6-b817-411c-bbc3-d1a1760d6932.png)

**Comment by designernatan** [comment]
@AureoDantax valeu pela sugestao!

a página com suas interações nao resolve?
![image](https://user-images.githubusercontent.com/5431347/157039184-1cd8a036-d58d-499e-aa8c-5cb16eb0c0bc.png)

hoje você consegue habilitar o 'acompanhar topico' em um topico que ja foi solucionado normalmente

**Comment by AureoDantax** [comment]
a pagina minhas Interações só mostra tópicos criados por mim, até na parte
discussões que participo, se eu coloco pra acompanhar um tópico que nao fui
eu que criei, não aparece

Em seg., 7 de mar. de 2022 10:00, Natan Souza ***@***.***>
escreveu:

**Comment by designernatan** [comment]
opa talvez seja bug entao, me passa seu user pfv?

o link (exemplo):
https://cursos.alura.com.br/user/natan-souza

**Comment by AureoDantax** [comment]
https://cursos.alura.com.br/user/dantasaureo19

**Comment by designernatan** [comment]
aureo, é bug mesmo

não conseguimos encontrar o problema ainda mas está na nossa fila ok?

vou fechar a issue mais por controle interno, mas quando corrigimos pingamos aqui novamente
