### ISSUE TITLE
Decepçao relacionada aos cadernos

### ISSUE THREAD

**Issue by luigiMinardi** [caelum/alura-funcionalidades#627]
Uso a alura desde antes dos cadernos existirem, usei os cadernos durante seu tempo de vida, e fui um dos que pediram para adicionar markdown nos cadernos para melhorar a funcionalidade. Vi o caderno sendo mudado de posiçao na aba dos cursos, vi o caderno ser abandonado em relaçao a updates e agora estou vendo ser descartado.

Ter a capacidade de escrever anotaçoes dentro ta plataforma é algo muito util e que agrega um grande valor a plataforma. Eu sei que existe o Notion, sei que posso publicar gists aqui no github, sei que posso instalar ou criar minha propria extensao de anotacoes no meu browser, no meu caso eu uso o Vivaldi que ja vem com um bloco de notas embutido no navegador. Também sei que tem como fazer bookmarks de tudo que você achar importante, e usar uma extensao de highlight para salvar na bookmark o texto importante colorido.

Porém nada disso está dentro da alura, e portanto é indiferente relativa a propria alura. Sei das complicaçoes por tras de criar seu proprio markdown e dos problemas de segurança que isso pode implicar. Mas nao ter nenhuma opçao de anotar as coisas ja de cara enquanto voce ta vendo seu curso, sem precisar abrir outra guia, abrir outro app, site ou sair da alura de qualquer maneira, esa simples facilidade de poder clicar em "abrir caderno" e colocar ali o que você achou importante na hora. Tambem a vantagem de poder, por cada caderno estar associado a um curso, saber onde encontrar suas informacoes de maneira organizada e sem dificuldade. Isso era muito bom nos cadernos.

O fato de eles terem sido abandonados provavelmente foi o fator para muitos que usavam ou tiveram vontade de usar deixarem de usar. Porque eu imagino que vocês estejam removendo essa feature pelo simples motivo de quase ninguem utilizar.

---

Uma opçao, visto que ja vi pessoas falando do notion em outros comentarios relativo aos cadernos, é utilizar a API do notion pra colocar ele dentro da alura, nao sei se seria viavel porque nao cheguei a trabalhar com a api deles. Mas olhando rapidamente por cima parece algo possivel de ser feito.

**Comment by designernatan** [comment]
oi luigi, o 'meus cadernos' realmente não atingiu nossa expectativa (não só em engajamento como em outros pontos) o que esperávamos quando lançamos o MVP em 2018/19

entendo sua frustração, também uso serviços que as vezes a galera "capa" algo que eu usava

por hora a opção que temos ali é baixar o zip dos cadernos individuais, concordo que o ideal seria uma API, mas como te disse a feature realmente não atingiu nossa expectativa

abcs!
