### ISSUE TITLE
função de pesquisar

### ISSUE THREAD

**Issue by Murillonb** [caelum/alura-funcionalidades#628]
Bom dia!

Gostaria de sugerir um campo de pesquisa nas páginas da [aluraflix](https://cursos.alura.com.br/aluraflix), [carreira sem fronteiras](https://cursos.alura.com.br/carreirasemfronteiras/episodios), [alura case](https://cursos.alura.com.br/cases) (esse pode ser mais pra frente, pois por enquanto está apenas na 2º temporada então é fácil dar uma olhada nos assuntos), [scuba dev](https://cursos.alura.com.br/scubadev/episodios), [layers tech](https://cursos.alura.com.br/layerstech/episodios), [like a boss](https://cursos.alura.com.br/likeaboss/episodios) e [hipster](https://cursos.alura.com.br/hipsterstech/episodios).

Tem um botão de pesquisar no topo das páginas mas ele faz a pesquisa no site todo.

**Comment by designernatan** [comment]
@Murillonb valeu pela sugestao!

do aluraflix, a busca normal do site traz o mesmo conteúdo dali :)

dos outros, você pode usar o filtro (também da busca normal) para pegar o que precisa:
![image](https://user-images.githubusercontent.com/5431347/157037566-68e706c1-caa0-4497-9693-4c47fe127e10.png)

abcs!

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
