### ISSUE TITLE
Transcrição em pdf

### ISSUE THREAD

**Issue by gemerson74** [caelum/alura-funcionalidades#629]
Olá time da Alura.

A Alura tem muitos  cursos e quanto mais fazermos cursos e absorvemos o que foi estudado é melhor. Mas, por exemplo, gosto de ter algum material para consulta posterior e de fato se no dia-a-dia não utilizo o que aprendi, com o tempo esqueço. E acho que um pdf com a transcrição do que é passado nos vídeos, seria muito bom, para rever conceitos. Sei que é necessário proteger o material e tal. Mas , uma opção que tem em cursos  online para concursos, é colocar o cpf e nome do aluno nos arquivos em pdf, em todas as folhas. Assim, se um dia, tal material for compartilhado, tem como saber a origem. Enfim. essa é uma forma de tentar se evitar o compartilhamento pago, mas deve outras formas.

**Comment by giovana-armidoro** [comment]
oii @gemerson74 valeu pela sugestão!

essa é uma sugestão bem legal, temos planos futuros de melhorar a tela de aula e quando a gente pegar isso vamos discutir a possibilidade de implementar algo assim, beleza?

por hora, você pode usar a busca que fica na tela de aula para encontrar e rever os conceitos com mais facilidade

abraços e bons estudos! :)

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
