### ISSUE TITLE
Modo teatro nos vídeos 

### ISSUE THREAD

**Issue by conradoov** [caelum/alura-funcionalidades#63]
Eu tenho um monitor ultra wide e uso a tela dividida para fazer os cursos e, com isso, existe uma grande área de exibição que é desperdiçada pelo player.
Uma sugestão para otimizar o espaço do curso é fazer um modo teatro de exibição, semelhante ao YouTube. 

Uma tentativa de exemplo powered by Paint:

![image](https://user-images.githubusercontent.com/60919056/74224084-dde81000-4c96-11ea-98c2-5c483764c71a.png)
![image](https://user-images.githubusercontent.com/60919056/74224146-fd7f3880-4c96-11ea-863a-4c6441ea401d.png)

**Comment by designernatan** [comment]
oi @conradoov valeu pela sugestão e pela montagem!

estamos vendo de melhorar essa tela de aula, algo como modo teatro incluso

uma solução de contorno que faço aqui em casa (tbm tenho um monitor uw) é dar zoom no site, outra opção é usar o Picture-in-Picture nativo do Chrome/Opera

abcs!
