### ISSUE TITLE
Obstrução da tela com o pause do vídeo

### ISSUE THREAD

**Issue by JoaoCoimbra2018** [caelum/alura-funcionalidades#630]
Toda vez que aperto Pause no vídeo um controle/linha etc. se sobrepõe exatamente sobre a linha comando que quero ver!!

**Comment by designernatan** [comment]
@JoaoCoimbra2018 foi mal pelo delay e valeu pela sugestao!

a gente se baseia muito na [jakobs law](https://lawsofux.com/jakobs-law/) para definir alguns padrões na experiencia da tela de aula, o youtube no caso tem exatamente esse comportamento

para dar uma driblada nisso, uma sugestão é dar fullscreen para conseguir ver a linha exata

outro ponto é que idealmente os comandos deveriam ficar mais "no meio" do vídeo e não muito lá em baixo, erro nosso na gravação, mas pode ser algo bem pontual também

abcs e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
