### ISSUE TITLE
Mudança de player de vídeo

### ISSUE THREAD

**Issue by ghost** [caelum/alura-funcionalidades#631]
O atual player de vídeo reproduz os vídeos muito bem, porém tem umas coisas muito irritantes. É muito fácil esbarrar o mouse em um botão sem querer e o mouse hover exibir alguma coisa por cima da barra de tempo e impedir de avançar ou retroceder o vídeo, aí tem q tirar o mouse e ir com cuidado pra não esbarrar de novo. Minha sugestão é colocar um player o mais parecido como a do youtube.

**Comment by jorge-rabello** [comment]
Aproveitando a issue outra coisa bem chata é ter de ficar saindo do full screen para passar pro próximo vídeo - podia ter no player mesmo um botão que avança pro próximo vídeo mais ou menos como é na Udemy.

**Comment by designernatan** [comment]
@matheusvalezin valeu pela sugestao!

a gente se baseia muito na [jakobs law](https://lawsofux.com/jakobs-law/) para definir alguns padrões na experiencia da tela de aula, o youtube no caso tem exatamente esse comportamento

uma alternativa aqui seria usar as setas do teclado para avançar/retroceder o video

---

jorge, tem essa [issue semelhante aqui](https://github.com/caelum/alura-funcionalidades/issues/528) e ainda vale o comentário da Laís na época: queremos e gostamos de algo assim, mas por hora sem planos para puxarmos uma melhoria dessas na tela de aula pois provavelmente envolveria refazer a tela como um todo.

Algo que pode te ajudar hoje é ligar o modo teatro (botão do lado do de fullscreen) ou ir dando fullscreen com o atalho F. [Aqui você tem outros atalhos que temos hoje.](https://suporte.alura.com.br/article/324-quais-sao-os-atalhos-de-teclado-nos-videos) Também tem o modo automático (se for pessoa física) que pode dar uma força.

abcs!

**Comment by andradeisadora** [comment]
oi pessoal, vou fechar a issue mas podem voltar a comentar se quiserem :)
