### ISSUE TITLE
Prova no final de cada Curso, Formação ou Capítulo.

### ISSUE THREAD

**Issue by lucashtw** [caelum/alura-funcionalidades#632]
Acredito que uma pequena prova no final de cada capítulo, curso e formação, possa ajudar as pessoas tanto a fixar melhor o conteúdo que viu, assim como aumenta a pratica no conteúdo que o aluno está querendo aprender, dando mais confiança no conteúdo e domínio da linguagem.

um exemplo que posso incluir na ideia: eu mesmo fiz os 4 cursos de html e css, fiz todos os exercicios e no fim resolvi criar um site proprio partindo do codigo que ja tinha e me deparei com algumas situações ou que não lembrava, ou que não que não tinha na aula.

**Comment by designernatan** [comment]
@lucashtw  valeu pela sugestao!

temos esse desafio de deixar os exercicios mais mão na massa (menos testes/provas) e empolgantes tbm, por isso criamos o Alura Challenges

comecou a 3ª edição semana passada mas vale super você fazer e discutir o desafio no discord do challenge tbm
https://www.alura.com.br/challenges/front-end-3

abcs!

**Comment by lucashtw** [comment]
interessante, hoje a noite vou dar uma olhada
