### ISSUE TITLE
Filtrar Cursos por Linguagem de Programação

### ISSUE THREAD

**Issue by GabrielSlPires** [caelum/alura-funcionalidades#633]
Acho que seria interessante uma opção de filtrar os cursos por uma ou mais linguagens.
Digo isso por que utilizo bastante a linguagem R, e sempre quando vou pesquisar cursos em R acabam aparecendo várias sugestões não relacionadas a linguagem.

**Comment by designernatan** [comment]
@GabrielSlPires valeu pela sugestao!

R caiu num limbo parecido com C: pela string ser soh uma letra a busca nao retorna o que é esperado

fiz uns filtros mais especificos e acho q consegui retornar oq vc precisa, da uma conferida dps
https://cursos.alura.com.br/search?query=com+r&typeFilters=COURSE%2CDEGREE&categoryFilters=data-science

abcs!

**Comment by GabrielSlPires** [comment]
@designernatan muito obrigado!

Sim, essas liguagens de apenas uma letra não ajudam muito na hora de pesquisar kk.
Obrigado pela dica, eu tinha feito algo do tipo por aqui tbm.

abcs!

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
