### ISSUE TITLE
Largura dos vídeos 

### ISSUE THREAD

**Issue by andr-silva** [caelum/alura-funcionalidades#634]
Olá, tenho um monitor ultrawide e notei que não consigo ajustar a tela do video evitando deixar com a borda preta desnecessária, em janela cheia o video ultrapassa o limite.

![Captura de tela 2022-03-16 073744](https://user-images.githubusercontent.com/101710047/158572177-2e3f909b-edb7-42b5-a789-56065ba6b1aa.png)
![Captura de tela 2022-03-16 073914](https://user-images.githubusercontent.com/101710047/158572182-b7fd27d3-9003-49ce-bf7c-8ba96b8432d2.png)
![Captura de tela 2022-03-16 073931](https://user-images.githubusercontent.com/101710047/158572188-b97db0fa-0e0b-4724-8f0e-2e292b5ed544.png)

**Comment by designernatan** [comment]
@andr-silva opa essa é pra evitar o video ter a altura prejudicada

tenho um UW aqui também e antes da gente corrigir isso ficava "comendo" 1/5 do vídeo ali

oq rola é que pra dar um fullscreen num UW a proporção do vídeo deveria ser 21:9, mas como o padrão é 16:9 ele nunca vai ficar certinho, igual um filme 4:3 que fica estranho em 16:9 :)
