### ISSUE TITLE
Ação para zerar a porcentagem de progresso de um curso

### ISSUE THREAD

**Issue by rsferreirawork** [caelum/alura-funcionalidades#635]
### Esta funcionalidade tem como incentivo essas duas dificuldades:

> Quando comecei um curso porém não terminei e o mesmo recebe uma nova versão, mesmo indo até o dashboard deste curso e através do menu **Outras ações** e usando a ação **Sair do Curso** este curso "antigo" continua tomando o lugar do novo na tela de busca por categoria.
> 
> ![image](https://user-images.githubusercontent.com/53823404/159124589-9ac2a889-163a-4577-984d-75d8261eb486.png)

> Uma outra situação é quando você começa o curso mas deixa ele sem terminar e quando volta depois de algum tempo agostaria de refazer o curso para entender o mesmo e também marcar esse novo progresso para saber de um dia para o outro onde você parou.

### Possível solução

Adicionar uma nova ação (Reiniciar Progresso) dentro do menu **Outras ações** disponível no dashboard de cada curso.

**Comment by ghost** [comment]
Acredito que essa issue possa ser mesclada com a [Issue 646](https://github.com/caelum/alura-funcionalidades/issues/646)

**Comment by designernatan** [comment]
@rsferreirawork valeu pela sugestao, victor valeu pela força!

casa bem com a issue 646 mesmo: por hora sem planos de zerar o progresso dos cursos

**Comment by andradeisadora** [comment]
oi pessoal, vou fechar a issue mas podem voltar a comentar se quiserem :)
