### ISSUE TITLE
Autenticação de dois fatores

### ISSUE THREAD

**Issue by juliocesar249** [caelum/alura-funcionalidades#636]
Olá, algo que notei desde que me matriculei na Alura, no final do ano passado, foi a possibilidade de ativar a autenticação de dois fatores na hora do log-in. Por mais que muitas vezes eu acho um saco ficar pegando códigos no Google, ou Microsoft, Authenticator, acho que seria uma boa ideia para aumentar a segurança de as contas  daqueles que quiserem. Bom dia, tarde ou noite  a todos :)

**Comment by designernatan** [comment]
@juliocesar249 opa valeu pela sugestao! Boa tarde (agora é tarde)

era uma boa algo assim sim, aumentar a segurança é excelente. Se tivermos alguma novi no futuro pingamos aqui

de curiosidade, algum motivo específico para o 2step na alura em si?
Imagino que é 100% diferente de um banco ou algo com dados mais sensíveis tbm

abcs!

**Comment by juliocesar249** [comment]
Olá Natan,

Nenhum motivo em específico, apenas achei interessante algo do tipo pois
nunca se sabe quando algo pode acontecer, então é melhor previnir do que
remediar, né?

Em seg, 21 de mar de 2022 16:18, Natan Souza ***@***.***>
escreveu:

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
