### ISSUE TITLE
Legenda no video

### ISSUE THREAD

**Issue by kimalextst** [caelum/alura-funcionalidades#637]
Seria interessante ter a opção de habilitar legenda junto ao video, como o YouTube por exemplo, para melhor inclusão a pessoas surdas ou que tenha dificuldade de processamento ao apenas escutar. É diferente da transcrição, já que há algumas diferenças da transcrição para o que é realmente dito no video e não dá pra acompanhar ao mesmo tempo

**Comment by mateuscsco** [comment]
Acho interessante algo nesse sentido também, em alguns momentos não consigo acessar aos vídeos ou conteúdos com áudio e a legenda ajudaria a acompanhar melhor os vídeos em silêncio, ou ainda algum tipo de conteúdo escrito com as imagens e tal, pois a transcrição não permite muito bem a visualização da aula simultaneamente o que dificulta um pouco o entendimento.

**Comment by designernatan** [comment]
oi pessoal, obrigado pela sugestao e pontos

tem [uma outra issue sobre legendas aqui](https://github.com/caelum/alura-funcionalidades/issues/10) e ainda vale o reply do Paulo

o chrome está começando a fazer legendas automaticas em videos, mas por hora somente conteúdos em inglês

abcs

**Comment by andradeisadora** [comment]
oi pessoal, vou fechar a issue mas podem voltar a comentar se quiserem :)
