### ISSUE TITLE
Autoplay para contas de empresa

### ISSUE THREAD

**Issue by JonatasAmaral** [caelum/alura-funcionalidades#638]
Olá.

Vi em algumas issues aqui, que a função de autoplay não está habilitada para contas vinculadas a empresas.
Existe alguma razão especifica para essa feature não estar disponível?

O autoplay funciona no app (apenas nas videoaulas)
Porem é muito mais cômodo usar o computador, com tela maior, podendo acompanhar o código/resultado lado a lado, etc.

Existe alguma previsão para expandir essa funcionalidade para os planos corporativos?

**Comment by designernatan** [comment]
Oi Jonatas,

É um recurso apenas para alunos e alunas pessoa física. Te contei mais [aqui](https://github.com/caelum/alura-funcionalidades/issues/457#issuecomment-1077956598) e [aqui.](https://github.com/caelum/alura-funcionalidades/issues/432#issuecomment-1077958189)

Não temos planos de colocar essa feature para planos corporativos por hora.
