### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by SamuelCarreraAntunesDosSantos** [caelum/alura-funcionalidades#639]
Minha ideia é de que como eu e muitas pessoas não gostam de mostrar o rosto, e não mostram um foto deles, pensei em criar um avatar, que a cada nível de xp ganha-se  um novo avatar, missões para ganha-los.

**Comment by designernatan** [comment]
@samuel2602SCAS valeu pela sugestao!

isso me lembrou um jogo que eu jogava antigamente (gunbound), [funcionava assim](https://twitter.com/foioguto/status/1410708352343158784)

de qlq forma, não está no nosso radar montar um sistema similar gameficado dessa forma, qualquer novidade dessa de outras frentes a gente divulga no [/artigos](https://www.alura.com.br/artigos/)

sei que existem algumas badges para quem participa (e finaliza) os [challenges da alura](https://www.alura.com.br/challenges), em geral galera manda via discord, aí pessoal usa no github por ex

abcs!

**Comment by andradeisadora** [comment]
oi pessoal, vou fechar a issue mas podem voltar a comentar se quiserem :)
