### ISSUE TITLE
Possibilidade de ver os cursos em desenvolvimento

### ISSUE THREAD

**Issue by azumamagus** [caelum/alura-funcionalidades#64]
Uma feature bacana seria poder visualizar os cursos que estão no forno e que serão lançado em breve

**Comment by designernatan** [comment]
oi @azumamagus valeu pela sugestao!

Esse é um ponto importante pra gente. Aqui já tentamos de muitas formas deixar mais transparente algumas coisas para os alunos. Algumas conseguimos, outras nao.

Essa de desenvolvimento de cursos é a mais complicada. No instante temos mais de N cursos sendo desenvolvidos ou editados. o problema é que um curso sendo desenvolvido pode ser lancado em 1 mês ou demorar 4 meses depois das revisões, edições, regravações ou até cancelamento. Bem no começo da Alura testamos isso e gerava uma ansiedade ainda maior entre os alunos e alunas.

Acho que uma outra ideia seria mostrar, no geral, que áreas/categorias estamos atacando mais no trimestre, quão sentido isso faz pra você? Como se fosse a meta do que gostaríamos de lançar a cada trimestre.

abcs!
