### ISSUE TITLE
Flexibilidade no pagamento

### ISSUE THREAD

**Issue by mmmanito** [caelum/alura-funcionalidades#640]
Prezados, sou um apaixonado pela plataforma e gostaria muuuuito de estudar os cursos da Alura, porem a forma de pagamento atual, que me permite fazer o pagamento avista, ou ter um cartao de credito com limite de 1000 reais acaba impossibilitando. 

Estou empolgadissimo pra aprender principalmente no tema DevOps. Escuto falar muito bem do trabalho de vcs. Parabens!!

**Comment by designernatan** [comment]
@mmmanito valeu pela sugestao!

tenta dar uma pingada direto no [contato](https://www.alura.com.br/contato) e tenta explicar sua situacao sobre o pagamento

a gente soh nao ta aceitando bitcoin ainda, mas o time sempre tenta ajudar :)

abracao e boa sorte lá!

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
