### ISSUE TITLE
Certificado da Formação

### ISSUE THREAD

**Issue by jorge-rabello** [caelum/alura-funcionalidades#641]
Desculpem se fui eu que não encontrei essa funcionalidade, mas seria bem legal ter um certificado da formação.

Exemplo: terminei a formação python poderia ter um certificado de conclusão das formação que certifica que o fulano concluir x horas de estudo daquele assunto.

Vlw

**Comment by ghost** [comment]
Mas tem sim, você encontra no seu perfil, na opção "ver certificado" das formações concluídas
![seta1](https://user-images.githubusercontent.com/101565638/163605339-81c5d1d4-fcab-4662-9784-7e646f11b852.jpg)
e
![seta2](https://github.com/victormdsts/victormdsts/blob/main/seta2.jpg?raw=true)

**Comment by designernatan** [comment]
Valeu Victor! É isso mesmo!

jorge, conseguiu pegar os certificados?

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, podem voltar a comentar se quiserem :)
