### ISSUE TITLE
Notificações No Celular

### ISSUE THREAD

**Issue by TheDevick** [caelum/alura-funcionalidades#642]
Trazer Notificações do Celular Quando Um Novo Curso, Artigo, Vídeo, Etc For Lançado.

As Vezes Me Esqueço De Olhar A Plataforma, Então Não Vejo As Notficações...

*Contexto*: Estou Falando Das [Novidades](https://cursos.alura.com.br/explore)

**Comment by designernatan** [comment]
@DinosDev valeu pela sugestao!

hoje temos a aba 'Novidades' no app (igual a /explore da plataforma)

não seria isso?

**Comment by TheDevick** [comment]
> @DinosDev valeu pela sugestao!
> 
> hoje temos a aba 'Novidades' no app (igual a /explore da plataforma)
> 
> não seria isso?

Bom, de certa forma

Estava me referindo às notificações do celular (Sabe quando você recebe uma mensagem no WhatsApp, e aparece na barra de notificações? É isso)

No caso, ao invés de ser mensagens do WhatsApp, seria novos cursos, artigos e tudo que aparece  na aba de novidades

**Comment by TheDevick** [comment]
> > @DinosDev valeu pela sugestao!
> > hoje temos a aba 'Novidades' no app (igual a /explore da plataforma)
> > não seria isso?
> 
> Bom, de certa forma
> 
> Estava me referindo às notificações do celular (Sabe quando você recebe uma mensagem no WhatsApp, e aparece na barra de notificações? É isso)
> 
> No caso, ao invés de ser mensagens do WhatsApp, seria novos cursos, artigos e tudo que aparece na aba de novidades

Acho que isso está mais focado no User Experience, pois atualmente, para você ver novos cursos, apenas entrando na plataforma e checando manualmente

**Comment by designernatan** [comment]
opa agora entendi! Notificação que vem de cima tipo "olha esses cupons aqui 👀"

temos uma iniciativa interna sobre isso para um futuro distante, com muita preocupação para não virarmos aqueles apps que mandam 235x por dia para falar algo inútil ou ficam mandando spam

sobre o lance de ver cursos novos, por hora só pelo sininho ali mesmo, mas estamos com algo mais no forno para facilitar um pouco esse ponto :)

valeu pela sugestao dino!

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
