### ISSUE TITLE
Ao sair do vídeo de uma aula, armazenar o timestamp.

### ISSUE THREAD

**Issue by gustavo-sm** [caelum/alura-funcionalidades#643]
Acredito que sería útil, porque quando voltássemos para o vídeo em questão, ele seria retomado no tempo onde paramos.

**Comment by designernatan** [comment]
@gus-sm opa, temos isso há um tempinho

talvez rolou algum bug momentâneo? Pode ser alguma extensão dando um block nisso ou pode ser algum vídeo específico com esse problema?

**Comment by gustavo-sm** [comment]
Talvez pode ter acontecido por conta de extensões que possuo no browser, hoje efetuarei mais um teste sobre isso.

**Comment by gustavo-sm** [comment]
Olá, voltando nessa thread aqui para relatar o que testei.

No site da alura, se estou assistindo um vídeo e então saio da página da aula (e.g./course/<curso>/task/<num_task>), ao retornar para o mesmo o vídeo é iniciado novamente do início.
Já no app mobile da Alura, o timestamp de um vídeo é conservado corretamente.

**Comment by designernatan** [comment]
hmmm parece bug isso, testei aqui com alguns vídeos num curso aleatório assim:

1. video tocando
2. clico no nome do curso la em cima na barra preta da esquerda
3. caiu na pg do curso
4. clico em continuar curso
5. depois de alguns segundos volta para o tempo que parei


de qlq forma era legal investigar com calma, me passa o link do seu perfil da alura dps?

**Comment by designernatan** [comment]
ah, e dá uma testada dessa forma que te falei tbm para ver se vai?

**Comment by gustavo-sm** [comment]
Opa, executei os passos descritos, com o vídeo tocando ele realmente volta pro tempo onde parei. 
Se executo os mesmos passos porém pausando o vídeo, o mesmo não volta pro timestamp onde parei, mas acredito que isso ja era um comportamento esperado da aplicação.

De qualquer forma, obrigado pela atenção!

**Comment by designernatan** [comment]
ahhhh sucesso entao gustavo! Valeu vc e bons estudos!
