### ISSUE TITLE
Night Mode Eclipse IDE

### ISSUE THREAD

**Issue by juniorvas** [caelum/alura-funcionalidades#644]
Ola, 

Estou fazendo o curso de Java e uma pequena dica que me ajudou bastante em questão da visão seria o Night mode no Eclipse - Eu apenas procurei no google e sem problema o encontrei mas para iniciantes talves nao saberiam que esta opção exista.

Abraço,
Junior

![Night mode](https://user-images.githubusercontent.com/102182232/162101694-2546a9d5-2c9d-42c0-bfdc-5f69f5beb0ce.jpg)

**Comment by designernatan** [comment]
@juniorvas opa valeu pela dica!

acho que vale compartilhar isso no discord da alura, mais precisamente ali no canal de Programação

pessoal sempre fica feliz com dicas felizes assim

abcs e bons estudos!
