### ISSUE TITLE
Contador

### ISSUE THREAD

**Issue by gabrielavillagran** [caelum/alura-funcionalidades#645]
Contagem do número de dias seguidos em que foi completada alguma atividade na plataforma.
Parece algo bobo mas acho que seria bacana ter um contador pois isso motiva a manter uma rotina de estudos, o Duolingo e o Khan Academy possuem esse sistema e eu acho bem legal.

**Comment by ghost** [comment]
@gabrielavillagran Como alternativa existe uma extensão que faz isso, é a Code Time, tem pra o VS Code [aqui](https://marketplace.visualstudio.com/items?itemName=softwaredotcom.swdc-vscode) mas tem pra outras IDEs também [aqui](https://www.software.com/code-editors)

**Comment by designernatan** [comment]
@gabrielavillagran valeu pela sugestao, victor valeu pelas alternativas (adoro esse tipo de solucao inclusive)

algo pra reforçar o hábito de estudar é algo bem bacana mesmo, por hora nao temos planos para implementar algo assim, mas fiquei muito curioso de como é na khan academy, consegue me falar mesmo que +- como funciona lá?

o do duolingo eu conheço bem pq nao queria perder aqueles X dias que tava estudando :)

abcs!

**Comment by andradeisadora** [comment]
oi pessoal, vou fechar a issue mas podem voltar a comentar se quiserem :)
