### ISSUE TITLE
Ao selecionar a opção "sair do curso" resetar o progresso do mesmo.

### ISSUE THREAD

**Issue by gustavo-sm** [caelum/alura-funcionalidades#646]
Na tela do curso, caso o aluno selecione "sair do curso", creio que faria sentido o progresso do mesmo ser reiniciado.
Sei que essa issue não é uma novidade, porém acredito fazer sentido, uma vez que, caso o usuário queira preservar seu progresso a função "pausar curso" já existe.

**Comment by designernatan** [comment]
@gus-sm valeu pela sugestao!

sem planos por hora para reset de cursos, na verdade desenvolvemos o 'sair do curso' a fim de melhorar a organização da dashboard do aluno, mas o progresso é para continuar ali mesmo

**Comment by andradeisadora** [comment]
oi pessoal, vou fechar a issue mas podem voltar a comentar se quiserem :)
