### ISSUE TITLE
Chat interativo nos videos das aulas

### ISSUE THREAD

**Issue by KassandraSouza** [caelum/alura-funcionalidades#647]
Sou aluna do Alura a poucos meses e estou adorando a didática e acessibilidade que propoem. 
As aulas que tenho assistido até agora são tão boas que me estigam a expandir o meu raciocinio sobre os conteúdos, por isso em muitos momentos, ao assistir as aulas, me vinha a vontade de expor as minhas reflexões com alguém. Por isso me veio a ideia de sugeria funcionalidade adicional no acesso às aulas:
- Um **Chat Interativo** onde os alunos podessem compartilhar suas reflexões, tirar dúvidas e expor seus raciocinios como se estivessem um uma sala de aula ao vivo, quando você interege com o professor e os colegas instantaneamente.
- **Uma sala virtual** que podessemos entrar em simutaneo com outros colegas que estivessem assistindo a mesma aula, juntamente com um mentor ou professor.
- Poderia funcionar em horario especifico, provocando assim um comprometimento dos alunos a organizarem seus horarios de estudo para participarem também do chat.
- Os videos das aulas permanecesseriam acessiveis a qualquer horario, como já estão, só teria o horario para participarem do Chat, quem quisesse e pudesse.

Espero que eu tenha ajudado de alguma forma e estou a disposição para ajudar com mais informações caso seja necessario.

**Comment by designernatan** [comment]
@KassandraSouza valeu pela sugestao!

essa era uma dor bem frequente que aparecia, resolvemos isso criando uma comunidade exclusiva para estudantes Alura no Discord

lá além dos canais de texto separados por cada escola (programação, front-end, etc) ainda tem os canais de voz!

---

o discord da alura fica disponível se logando na plataforma, Comunidade -> Discord Alura

**Comment by KassandraSouza** [comment]
Entendi Natan.

Só dei essa sugestão pq entrei no discord e achei a navegação muito confusa para quem entra pela primeira vez. Até encontrar o q precisa... leva muuuuito tempo.
Mas estou falado de mim, é claro q pra quem já trabalha e tem mais intimidade com o Discord não sinta o mesmo que eu.

Já nos videos das aulas, ficaria mais fácil integir de forma instantanea.

De qualquer maneira, obrigada pelo retorno.

**Comment by designernatan** [comment]
opa tranquilo kassandra! Eu mesmo demorei **bastante** para me acostumar (usamos internamente aqui), mas hoje me viro bem

uma dica é esse alura+ que mostra a comunidade alura lá dentro:
https://cursos.alura.com.br/extra/alura-mais/discord-como-usar-essa-ferramenta-de-comunicacao-c1428

**Comment by andradeisadora** [comment]
oi pessoal, vou fechar a issue mas podem voltar a comentar se quiserem :)
