### ISSUE TITLE
Adicionar opensearch no cursos.alura.com.br

### ISSUE THREAD

**Issue by ghost** [caelum/alura-funcionalidades#648]
## Seria útil para os alunos se a Alura tivesse o [opensearch](https://opensearch.org/) nativamente na plataforma.

Desse jeito quando alguém quisesse pesquisar no site de vocês bastaria usar a pŕopria omnibox do chrome, digitar as primeiras letras do nome Alura, dar um tab e então fazer a pesquisa que iria redirecionar para a página de resultados de cursos

Resumndo, o opensearch é a opção de pesquisar dentro de um site usando a caixa de pesquisa do navegador
No MDN fala sobre isso [aqui](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) e para a pessoa habilitar no navegador basta seguir esse artigo [aqui](https://support.google.com/chrome/answer/95426?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cuse-shortcuts-to-search-from-your-address-bar).

Não é dificil habilitar essa opção bastando que o site tenha criado esse XML para informar ao navegador que tem um sistema de buscas habilitado, e o usuário só precisa habilitar, o que também não é dificil de fazer nas configurações do navegador.

É possível um usuário habilitar sozinho essa opção ainda que o site não tenha, coisa que eu fiz inclusive no site da Alura conforme a imagem abaixo: 

![opensearch Alura](https://user-images.githubusercontent.com/101565638/163607677-27193f81-fd3d-484d-a19b-b9b68261ac7b.png)

Dessa forma eu consigo pesquisar no cursos.alura.com.br mesmo sem precisar primeiro abrir o site, conforme a imagem abaixo:

![exemplo](https://user-images.githubusercontent.com/101565638/163607845-414002df-91b4-484f-a762-de274dc7a852.png)

Seria uma opção bem legal para ser implementada e é bem fácil de fazer, eu acredito que implementando e criando um post para que os alunos aprendam a habilitar isso ajudaria muito a encontrar conteúdo na Alura de uma forma mais rápida.

**Comment by designernatan** [comment]
@victormdsts valeu pela sugestao, tempo e dedicacao em trazer tudo assim! <3

parece BEM bacana isso, tudo pra facilitar é sempre uma boa, bem específico ao mesmo tempo

como parece de boas para implementar (mas ao mesmo tempo é algo externo), precisamos conversar aqui internamente e investigar um pouco mais fundo essa opensearch

sem prazos infelizmente, mas qualquer novidade pingamos aqui!

**Comment by andradeisadora** [comment]
oi pessoal, vou fechar a issue mas podem voltar a comentar se quiserem :)
