### ISSUE TITLE
Informar quando um link está redirecionando para fora da Alura.

### ISSUE THREAD

**Issue by mateusberger** [caelum/alura-funcionalidades#649]
Percebi que é possível inserir links no corpo dos planos de estudos da Alura, sendo possível redirecionar para fora da página.
Esse recurso, poderia ser utilizado para golpes, uma vez que um aluno poderia criar um plano de ensino e redirecionar para links maliciosos.
Sugiro que seja emitida uma mensagem quando o redirecionamento for acontecer, para que a pessoa entenda que dali para frente a plataforma não tem mais responsabilidade.
Esse recurso pode estar disponível em toda a plataforma, afinal é impossível garantir que paginas externas não sejam maliciosas.

**Comment by designernatan** [comment]
@mateusberger valeu pela sugestao!

hoje a gente resolve isso marcando qualquer site externo como "site", diferente de conteúdos da alura que são exibidos e nomeados de uma forma diferente (por ex: formacao e podcast)

de qualquer forma vamos conversar aqui internamente no futuro a fim de ver alguma solução (lembrando que até hoje tivemos zero problemas com algo assim) 

abcs!

**Comment by andradeisadora** [comment]
oi pessoal, vou fechar a issue mas podem voltar a comentar se quiserem :)
