### ISSUE TITLE
Excluir curso da dashboard

### ISSUE THREAD

**Issue by marianadasilva** [caelum/alura-funcionalidades#65]
Existe a opção de pausar um curso, mas, seria legal uma opção de excluir também. Apagaria todo o histórico daquele curso, como as aulas que a pessoa já assistiu e etc. Tem curso que clicamos só para testar, não vamos continuar e, a opção pausar ainda deixa o curso por lá, dá uma aflição.

**Comment by designernatan** [comment]
oi @marianadasilva valeu pela sugestao!

tem algumas threads sobre isso, [essa aqui é a maior](https://github.com/caelum/alura-funcionalidades/issues/31)

um ponto que não fica claro pra mim é pq o 'pausar curso' não funciona uma vez que ele isola (e bem) dos cursos em andamento lá no "meus cursos", vc pode elaborar mais por favor?

hoje a gente consegue ver algumas aulas do curso sem se matricular nele de fato, só clicar diretamente em uma das aulas lá em baixo (aparece um banner lembrando que nenhum progresso seria salvo quando faz isso)

de qualquer forma, estamos vendo algumas melhorias na página de curso para deixar mais claro que rola espiar o curso sem se matricular nele :)

abcs!
