### ISSUE TITLE
Video Fixo na Rolagem da página

### ISSUE THREAD

**Issue by diegoaferreira82** [caelum/alura-funcionalidades#650]
Fixa vídeo no topo da tela enquanto faz rolagem da página para copiar/acompanhar texto.

**Comment by designernatan** [comment]
@diegoaferreira82 valeu pela sugestao!

o modo picture in picture hoje nao resolveria pra vc enquanto estuda?

a isa aqui do time fez um post nesta outra issue explicando sobre ele:
https://github.com/caelum/alura-funcionalidades/issues/580#issuecomment-986747441

**Comment by andradeisadora** [comment]
oi pessoal, vou fechar a issue mas podem voltar a comentar se quiserem :)
