### ISSUE TITLE
Seleção aleatória de cursos 

### ISSUE THREAD

**Issue by TogaHimiu** [caelum/alura-funcionalidades#651]
Bom... queria uma função que me desse uma recomendação aleatória de curso para min fazer ou gerar um curso dos mais recomendados.

**Comment by designernatan** [comment]
@TogaHimiu valeu pela sugestao!

acho que nossa [área de descoberta de conteúdo](https://cursos.alura.com.br/aluraflix) vai te ajudar

**Comment by andradeisadora** [comment]
oi pessoal, vou fechar a issue mas podem voltar a comentar se quiserem :)
