### ISSUE TITLE
Registro de visualização de Podcasts

### ISSUE THREAD

**Issue by mbaliu** [caelum/alura-funcionalidades#652]
No aplicativo Mobile, quando assistimos um dos diversos episódios de um dos Podcasts, não fica registrado qual assistimos e onde paramos de assistir.
Seria interessante uma funcionalidade de **registro** do que já fora assistido, se interrompemos o episódio. Isso ajudaria os usuários a gerir quais episódios já passamos e quais ainda restam.

De forma complementar a esta funcionalidade, seria interessante uma opção de **favoritar** episódio (nos casos de encontrarmos um tema legal e quisermos assistir posteriormente); opção de **visualizar somente os episódios não assistidos** (pois diversos podcasts possuem inúmeros episódios e encontrar onde paramos pode ser desafiados); ou também a opção de inverter a ordem dos episódios (pois alguns, como eu, temos que ir até o último item porque ele é o mais antigo e queremos seguir a ordem cronológica.).

Também uma opção de colocar os podcasts que seguimos no Dashboard. 

Bem estas foram algumas dicas que incremento nas funcionalidades.

**Comment by giovana-armidoro** [comment]
oi @mbaliu valeu pelas sugestões!
são ótimos pontos pra gente trabalhar no app, já temos em nosso radar essa melhoria do registro dos episódios assistidos e também vou levar essas outras sugestões pra discutir com a equipe!

aproveitando, poderia me contar um pouco mais sobre sua experiência com os podcasts no app hoje? com que frequência você ouve e como você faz para controlar onde parou e seus favoritos para ouvir depois?

abraços e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, podem voltar a comentar se quiserem :)
