### ISSUE TITLE
Dificuldade em encontrar o conteúdo de apoio

### ISSUE THREAD

**Issue by ghost** [caelum/alura-funcionalidades#653]
Estava acompanhando as aulas de Protopie e até agora não achei o bendito do material de apoio do Figma. Ou ele não existe na página, ou tá muito bem escondido. Eu sugiro criar uma seção para downloads que seja fácil de ser encontrada.

**Comment by giovana-armidoro** [comment]
oie, valeu pela sugestão! vou levar esse ponto para discutir com a equipe
pode me indicar qual o curso e a aula que está fazendo para eu poder te ajudar a encontrar esse material?

e vc pode tentar usar a busca para encontrar algo no curso também, fica logo abaixo do título do curso:
![image](https://user-images.githubusercontent.com/92942899/166936233-3d6f9e3d-6db8-4a10-986f-8b971b9ccb33.png)

qualquer dúvida me avisa
obrigada e bons estudos :)

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, podem voltar a comentar se quiserem :)
