### ISSUE TITLE
Alteração do Título dos Certificados Normais

### ISSUE THREAD

**Issue by samuelcasaril** [caelum/alura-funcionalidades#654]
Sugiro a troca do título dos certificados normais de **"Certificado de Participação"** para **Certificado** apenas, como era antes, ou até mesmo **"Certificado de Conquista"** como usado por outras certificações importantes.

Uma empresa me perguntou se era uma palestra ou realmente um curso, por causa da palavra **"Participação"**.  
Minha universidade e demais usam "certificado de participão" apenas para palestras.

Nenhum modelo de referência nacional ou estrangeiro usa este título. Usam "certificado de conquista" (certificate of achievement),  ou apenas "certificado" e não usam a palavra "participação". Não gostaria de ser indagado por outra empresa referente a mesma questão. Isso afeta até os certificados de formação. 

Obrigado.

**Comment by giovana-armidoro** [comment]
oi Samuel, valeu pela sugestão!

bem legal essa questão que você levantou, vou levar isso pro time. acho que dá pra ser feito sim, mas ainda não posso prometer nada blz? 

assim que tiver alguma atualização te aviso por aqui.

abraços e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, podem voltar a comentar se quiserem :)
