### ISSUE TITLE
Separação e correção das Formações de Python

### ISSUE THREAD

**Issue by samuelcasaril** [caelum/alura-funcionalidades#655]
Para visualizar melhor o erro em questão, primeiramente acesse esse link:
https://www.alura.com.br/cursos-online-programacao/python-web

[itens-da-formação-web-atual.pdf](https://github.com/caelum/alura-funcionalidades/files/8567253/itens-da-formacao-web-atual.pdf)
[erro.jpg](https://user-images.githubusercontent.com/18563109/165402126-6745c355-32a3-4a42-acf3-ad381c3fd977.jpg)

Note que temos duas categorias: Python e Python Web.

O curso de formação Python Web, não abordam os conteudos de Django e Flask, apenas posterior em outros cursos separados!
E seu nome consta como Python Web, o que eu acho extremamente incorreto. A formação é a base apenas para a linguagem Python.
1--> Sugiro aqui a alteração do nome de "Formação Python Web" para "Formação Python", como já era antes... (Sim, antigamente estava correto, mas foi alterado). Até porque Python não é usado somente para Web.

Porem temos outros cursos de Flask e Django que são relativos ao Python Web.
2--> Neste caso sugiro também a criação da Formação Python para Web, em que se aproveite os cursos realizados da Formação Python.

Ou seja, teremos:

- Formação Python (Apenas a linguagem como já é hoje, aonde se remove o termo "Web". que é um equivoco estar ali) .
- Formação Python para Web. (Aqui se aproveita os cursos da formação anterior da linguagem Python somados aos novos cursos de Flask, Django e demais ligados a linguagem Python usado para Web). 

Acredito que outros cursos apresentam a mesma falha. Isso fica de sugestão para uma nova ISSUE.
Mas a principio este é para correção da formação python. 

Obrigado.

**Comment by designernatan** [comment]
@samuelcasaril valeu pela sugestao!

sei que não é uma feature, mas foi um erro nosso de qualquer forma

já vamos nos movimentar no futuro para arrumar isso, ok?

abcs e bom fds!
