### ISSUE TITLE
IDE integrada para desafios durante o curso

### ISSUE THREAD

**Issue by cinthiafontoura** [caelum/alura-funcionalidades#656]
Seria muito legal se ao inves de apenas questoes multipla escolha tivesse uns desafios com o que esta sendo ensinado durante o curso, como se fosse uma prova de conclusao de modulo ou algo do tipo. Estou cursando um bootcamp que tem esta funcionalidade e acho que ajuda muito a compreender o e fixar o conteudo.

Exemplo da IDE

![capture_20220428114124251](https://user-images.githubusercontent.com/80278757/165738809-6d3b2aeb-7daf-4f00-beb6-e58fecaae36c.png)

Quando a solucao nao passa no teste

![capture_20220428120041248](https://user-images.githubusercontent.com/80278757/165738805-4e42c8b0-e963-4cb2-8277-65ce4648abb2.png)

Exemplo em tela cheia com a descricao do desafio completo

![capture_20220428114508432](https://user-images.githubusercontent.com/80278757/165738807-a1c46881-76dd-4349-860e-4b270b48fc82.png)

**Comment by designernatan** [comment]
@cinthiafontoura valeu pela sugestao e pelo tempo em mandar esses prints pra gente :))

a gente sempre tenta aproximar o ensino nos cursos do mundo real, ainda vale o que [o paulo comentou aqui nessa outra issue](https://github.com/caelum/alura-funcionalidades/issues/108) tudo bem?

boa semana!

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, podem voltar a comentar se quiserem :)
