### ISSUE TITLE
Design para Certificado Formal e opção para compartilha-lo.

### ISSUE THREAD

**Issue by samuelcasaril** [caelum/alura-funcionalidades#657]
- Recomendo a criação de um design para o certificado formal no layout A4, pois hoje está em html "blank".

- Sugestão de título: 
<h1>Certificate of Achievement</h1> //se for deixar em inglês (conceito americano)
<h1>Certificado</h1> //se for deixar português (conceito brasileiro)

- Segue modelos interessantes:
https://pbs.twimg.com/media/EXvHqKkWoAI9lat.jpg
https://filestore.community.support.microsoft.com/api/images/f571059b-ae4c-4f80-9c81-3bcf63789966?upload=true

- Não deixar as bordas brancas ao redor do certificado, fazer com que o design toque o fim da página para impressão.
Motivo: Hoje o certificado normal (não formal) apresenta problemas ao imprimir em página inteira.

- Inclusão de QR code com o link do certificado para validação na url da Alura.

- Recomendo também, se possível, um botão pra fazer o download do certificado em PDF, para evitar configurações incorretas de impressão e para compartilhar no linkedin como Licença e Certificado (Hoje ele só gera do certificado normal, que inclusive consta um termo incorreto de "Certificado de Participação" o que tira o descrebidilita o certificado. Aparenta ser apenas uma palestra sem prática. Inclusive já abri a ISSUE #654 para correção deste.

- Acho interessante uma contra página (verso), para o caso de formações, onde a lista dos conteúdos é grande. O normal é a listagem dos mesmos no verso do certificado, com as horas aulas, acho interessante incluir além das horas, adicionar o icone do curso, número de atividades feitas para cada etapa, exp adquirida, tudo bem gráfico, tentar evitar somentes textos, para causar uma aparencia melhor ao certificado.

-  Interessante incluir a assinatura e um selo de autenticidade da alura, tanto na frente como também ao verso.  

Obrigado.

**Comment by andradeisadora** [comment]
oi @samuelcasaril obrigada pelas sugestões!
Faz sentido sim melhorar o certificado formal, estamos com planos pra isso pro futuro :)
Sobre o outro certificado, recentemente entramos com o revamp dele e aos poucos estamos fazendo pequenas melhorias, já está no radar uma tela melhorada pra baixar o certificado e algumas outras melhorias. 

Não tenho um prazo pra te dar sobre essas melhorias ta? elas ja tão no radar pro futuro e qualquer coisa te retornamos aqui :)
abraço e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue, pode voltar a comentar se quiser :)
