### ISSUE TITLE
Indicações de Formações com cursos já realizados

### ISSUE THREAD

**Issue by VanessaSantos03** [caelum/alura-funcionalidades#658]
Sou aluna novata na Alura, e minha sugestão é com base nos cursos que fiz por aqui, mas também em relação a utilização de outras plataformas de estudos online, é a seguinte:

Estava fazendo a trilha de **RH 4.0: Digital Agile & Transforming Business Partner** e ao realizar pesquisas de novas trilhas para fazer percebi que tinha 50% da trilha da formação de **Aprendizagem** cumprida, daí aproveitei e finalizei os outros 50% que faltavam.

Que tal se o sistema verificassem quais trilhas possuem cursos comuns e informassem aquelas que temos pelo menos já 50%. Daria a possibilidade de ampliar conhecimento em outras áreas, ou mesmo acessá-las como curiosidade.

**Comment by giovana-armidoro** [comment]
oi Vanessa, valeu pela sugestão!
faz muito sentido, iria facilitar bastante e dá até mais motivação de terminar uma formação quando já tem várias atividades concluídas né?
temos planos futuros de fazer melhorias na dashboard e nas formações, quando formos fazer isso vou levar essa questão para discutir com a equipe.

enquanto isso, você pode ficar de olho nas seção “**Formações com esse curso**” que fica na página do curso
nessa seção são listadas todas as formações que esse curso faz parte, assim já da pra você dar uma olhadinha se já está avançada em alguma outra formação

![image](https://user-images.githubusercontent.com/92942899/166986497-dff2fc16-0a16-4081-a038-04a913eb98d5.png)


abraços e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, podem voltar a comentar se quiserem :)
