### ISSUE TITLE
Busca por tópico no fórum

### ISSUE THREAD

**Issue by lucash-barbosa** [caelum/alura-funcionalidades#659]
Seria muito mais prático que, quando pesquisa-se algo na caixa de pesquisa do fórum,  as opções de tópico se mantivessem. Sendo bastante útil, para quando, por exemplo, estou buscando por uma pergunta bem específica.
Ou seja, quando digitar algo na pesquisa no fórum, as opções de categorias se mantivessem.

**Comment by andradeisadora** [comment]
oi @Lucas-Henrique-Barbosa 
obrigada pela sugestão!

Faz sentido sim mantermos as categorias na busca, mas infelizmente não temos planos no momento pra mexer no fórum :(
Vou salvar tua sugestão pro futuro mas sem prazo ta?

abraço e bons estudos :)

**Comment by andradeisadora** [comment]
vou fechar a issue, pode voltar a comentar se quiser :)
