### ISSUE TITLE
Android - Opção de Salvar Local para baixar as Aulas

### ISSUE THREAD

**Issue by Mactropolis** [caelum/alura-funcionalidades#66]
Desde que comecei a assinar a Alura me deparo com a impossibilidade de, no meu Tablet (Galaxy TAB A 2016), salvar as aulas no seu cartão de memória me impedindo, assim, de salvar as aulas apesar muito espaço no meu cartão de memória. 

No meu celular (Galaxy Note 10 Plus), apesar de não ter cartão de memória disponível, essa opção fica habilitada. 

A idéia é habilitar que o usuário tenha a possibilidade de alterar o local de salvamento das aulas de forma manual pois, pelo que parece, a detecção de cartão de memória do aplicativo não é muito confiável.

**Comment by felipetorres** [comment]
Oi! Sou do time de desenvolvimento dos apps, tudo bem com vc?

Para exibirmos o botão de salvamento no SD card, buscamos por algumas pastas no sistema de arquivos do aparelho que frequentemente representam o SD card. Tudo isso pois o Android não tem uma forma infalível de devolver o caminho do cartão de memória. =/

No entanto, as fabricantes podem bagunçar isso e colocar o SD card em qualquer lugar que elas quiserem. E é aí que a gente não consegue encontrar o cartão, mesmo existindo um.

E o pior: isso pode variar entre modelos da mesma fabricante.

Sempre que a gente encontra um modelo que não conseguimos detectar o SD card, procuramos mais infos sobre ele e adicionamos esse conhecimento ao nosso código. Vamos fazer isso com esse modelo que nos passou.

Abraço.
