### ISSUE TITLE
Maior tempo para resposta em fórum

### ISSUE THREAD

**Issue by MarcoGarbeto** [caelum/alura-funcionalidades#660]
Estava olhando o fórum da Alura e encontrei uma dúvida de outro aluno com 4 semanas que já havia sido postado, porém não havia sido respondido de forma correta.
Procurei me informar para ter como responder a dúvida dele, pois eu havia sanado esta mesma dúvida de forma clara enquanto assistia as aulas, mas não pude responder.

**Comment by designernatan** [comment]
@MarcoGarbeto valeu pela sugestao!

a gente tranca o tópico nesse tempo pois puxamos alguns números e era +- o tempo ideal

---

algo q vc poderia fazer hoje (mesmo que meio solto) é criar um tópico, linkando o tópico original no post e comentar

outra forma tbm é pegar essa pergunta e mandar no Discord da Alura com a sua resposta

abcs!

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, podem voltar a comentar se quiserem :)

**Comment by chipbb** [comment]
@designernatan , boa noite!

Qual seria o motivo de bloquear? 

Deixando liberado vocês permitem que a pessoa que originou o post tenha acesso à resposta (o que não ocorre se for criado um novo post), além de permitir que outras pessoas com a mesma dúvida tenham a resposta em um só lugar (imagina um tópico recriado duas ou três vezes porque outras pessoas em momentos distintos lembraram de algum detalhe que foi omitido nas outras respostas). Sem contar que pode aumentar o consumo de espaço se a pessoa fizer "quote" do tópico original.

Em alguns sistemas de comentários existe uma configuração de passar o comentário pela aprovação do dono da página/blog. Se existe a necessidade de bloquear vocês poderiam colocar um sistema parecido (idêntico ao que vocês já tem com o "sugerir alteração" nas páginas das aulas) para os posts com mais de 4 semanas.

**Comment by designernatan** [comment]
opa, tranquilo? 

em suma: evitar revive de posts muito antigos, inclusive é algo que alguns fóruns fazem tbm, mas sempre podemos rever essas regras de alguma forma no futuro

legal esses feedbacks que vcs dão sobre como as coisas funcionam (e principalmente as que não funcionam) pra gente sempre ir melhorando a plataforma como um todo :)
