### ISSUE TITLE
Ranking mais realista

### ISSUE THREAD

**Issue by gemerson74** [caelum/alura-funcionalidades#661]
Vendo o ranking através do meu perfil em https://cursos.alura.com.br/user/gemerson/rank/monthly, percebi, que nunca aparece alguém com a minha mesma numeração. Por exemplo, se num determinado momento eu apareço com 100 pontos, e tiver outras alunos com  100 pontos, eles não aparecem no ranking. Se eu passar para 200, os alunos com 100 pontos reaparecem e somente eu com 200 pontos fico visível. Ou seja o número do ranking não é informa o número real do ranking.
Vou tentar explicar com imagens, em anexos: Por exemplo, na figura alura 001, eu to com 269.100 pontos e tem um outro aluno com 269.200 pontos. Depois que fiz uma atividade, passei a ter 269.200 pontos e o aluno que tinha essa mesma pontuação, sumiu do ranking (figura alura 002). Em seguida, fiz mais outra atividade e passei para 269.300 pontos, e o aluno com 269.200 pontos voltou aparecer (figura alura 003).

![alura 001](https://user-images.githubusercontent.com/34105729/166523203-b322a17b-11f7-4fe6-a807-cbc9ad76dca5.PNG)
![alura 002](https://user-images.githubusercontent.com/34105729/166523232-9baaac38-e9ed-4b67-9914-72d136f91b7c.PNG)
![alura 003](https://user-images.githubusercontent.com/34105729/166523293-1efde716-f772-4f81-b17f-b21da26371be.PNG)

**Comment by andradeisadora** [comment]
oi @gemerson74 

Pois é, faz sentido dar uma melhorada e fazer alguns ajustes no ranking sim. Obrigada por avisar!
Infelizmente no momento não temos planos pra revisitar essa feature :(

Vou deixar anotado aqui vermos num futuro mas sem prazo ta?
Abraço e bons estudos :)

**Comment by andradeisadora** [comment]
vou fechar a issue, pode voltar a comentar se quiser :)
