### ISSUE TITLE
Chat de dúvidas

### ISSUE THREAD

**Issue by douglasdacosta** [caelum/alura-funcionalidades#662]
Gostaria de solicitar a implementação de um Chat para facilitar a comunicação em caso de algum problema.
O atendimento via email se torna demorado em uma época em que o tempo é algo tão precioso.

**Comment by designernatan** [comment]
@douglasdacosta valeu pela sugestao!

essa era uma dor bem frequente que aparecia, resolvemos isso criando uma comunidade exclusiva para estudantes Alura no Discord

lá além dos canais de texto separados por cada escola (programação, front-end, etc) ainda tem os canais de voz!

---

o discord da alura fica disponível se logando na plataforma, Comunidade -> Discord Alura
