### ISSUE TITLE
Opção de reiniciar curso

### ISSUE THREAD

**Issue by Schon98** [caelum/alura-funcionalidades#663]
Atualmente não há opção de reiniciar o curso, por exemplo, comecei uma formação, contudo, parei por tempo, é possível que não lembre com detalhes do que já aprendi. Como faço para voltar desde do inicio? Posso ir manualemene, mas ao fechar a página, a ultima aula vista será o ultimo conteúdo acessado lá na primeira tentativa de fazer o curso. É facil de se perder.

**Comment by andradeisadora** [comment]
Oi @Schon98 
obrigada pela sugestão :)

Falamos sobre isso nessa [issue aqui](https://github.com/caelum/alura-funcionalidades/issues/635)
Abraço e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue, pode voltar a comentar se quiser :)
