### ISSUE TITLE
Adicionar/Seguir usuários

### ISSUE THREAD

**Issue by zecaivano** [caelum/alura-funcionalidades#664]
Acho que seria bacana seguir outros usuários na plataforma, além do plano de estudos públicos que publicar... Se eu tenho um amigo e quiser visualizar o progresso dele nos estudos, ou somente o perfil, até mesmo para um ir estimulando o outro... Porém atualmente a plataforma não possui sequer um sistema de busca de usuários, sinto falta disso, porque na prática eu gosto bastante do sistema de ranking e sempre dou uma olhada nos usuários próximos a mim, o que eles andam estudando etc. Certa vez vi um usuário que tinha um site pessoal superbacana e depois nunca mais consegui acessar o perfil dele.
Sei que esse não é o foco principal da plataforma, mas acho que isso estimularia um pouco mais os alunos a preencherem o perfil pessoal, já que a maioria não altera nem a foto. Até mesmo dar a opção de seguir um instrutor já seria bacana.

**Comment by andradeisadora** [comment]
oi @zecaivano 
obrigada pela sugestão!

não temos planos pra uma feature de seguir perfis dentro da plataforma mas você pode trocar ideia com o pessoal na comunidade do discord e adicionar os seus amigos da Alura por lá :)

abraço e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue,, pode voltar a comentar se quiser :)
