### ISSUE TITLE
Unificar Perfis (Pessoal / Corporativo)

### ISSUE THREAD

**Issue by ivanclay** [caelum/alura-funcionalidades#665]
Possibilidade de Transportar o conteúdo entre perfis de um mesmo aluno (pessoal / corporativo).

Quando o aluno possui um perfil pessoal na Alura e recebe um acesso corporativo, os treinamentos já realizados não ficam disponíveis (óbvio) e os treinamentos realizados em perfis corporativos também não são disponibilizados para o perfil pessoal.

Sugiro, uma funcionalidade, de vinculação, entre perfis de um mesmo Aluno.  Para que, a medida que o aluno troque de empresa e ganhe um novo perfil corporativo, seus treinamentos realizados possam acompanhá-lo.

**Comment by designernatan** [comment]
@ivanclay valeu pela sugestão!

faz um tempo que paramos de dar essa unificada (mesmo manualmente) pois acabava dando alguns problemas internos

ideal é entrar em contato direto por e-mail com a gente no [contato](https://www.alura.com.br/contato), explicar a situacao (empresa, perfil, etc) e ver se há essa possibilidade por lá

só reforçando aqui que é uma possibilidade, não consigo garantir que consigam, infelizmente

abcs e boa semana!
