### ISSUE TITLE
Aulas menos cansativas

### ISSUE THREAD

**Issue by LaraNatale** [caelum/alura-funcionalidades#666]
Nao é uma funcionalidade, mas uma opiniao a respeito das aulas do Nico Steppat. Os vídeos sao MUITO longos e cansativos. É uma pessoa que tem muito conhecimento, mas na hora de passar isso por vezes acaba se enrolando e deixando os vídeos do curso muito longos. Quando vejo que o curso é dele, logo desanimo.

**Comment by designernatan** [comment]
@LaraNatale opa lara, desculpe por isso

o time de conteúdo está sempre de olho nesses feedbacks que chegam pra gente, principalmente via depoimento de finalização de curso

inclusive, estamos regravando diversos cursos para ficarem mais próximos dessa cara nova da alura

**Comment by LaraNatale** [comment]
Muito obrigada Natan!

Inclusive parei de fazer curso de java por causa das aulas cansativas e
decidi que nao renovarei minha assinatura em decorrência disso. Quem mais
dá aula de java é o Nico e cheguei Ao ponto de me sentir desmotivada com as
aulas dele.

**Comment by designernatan** [comment]
Oi Lara,

É uma pena que essa experiência esteja fazendo você dar uma pausa nos estudos :/

Já levei esse feedback para o time e em breve vamos lançar novos cursos e atualizações! Vamos fazer assim, envia um e-mail para [contato@alura.com.br](mailto:contato@alura.com.br) que o time de Student Experience pode auxiliar a encontrar cursos que façam sentido com o seu plano de estudo e que tenham outros instrutores(as).

E se até a época da renovação não tiver surgido nada novo, eles podem verificar uma condição especial para você continuar se desenvolvendo com a gente :)

Abcs!

**Comment by LaraNatale** [comment]
Então Natan, nao adianta eu fazer um outro curso sendo que no momento não é
o que estou precisando, entende?

Não adianta eu assinar com condições especiais sendo que vocês não poderão
me oferecer o curso que eu preciso, por isso que não entrarei em contato
com o Student Experience. Estou muito desapontada com a qualidade desses
cursos, de verdade.

Mas não vou parar de estudar não, eu somente irei procurar uma outra fonte
porque a alura não consegue mais me oferecer o que eu preciso.

**Comment by designernatan** [comment]
Oi Lara,

Tranquilo, de qualquer forma acolhemos seu feedback por aqui e já repassamos internamente.

Abcs!
