### ISSUE TITLE
Certificados com nome do curso em Ingles e a ementa no certificado em Ingles

### ISSUE THREAD

**Issue by oswaldomaxado** [caelum/alura-funcionalidades#667]
Olá gostaria que tivesse a opção dos certificados em inglês e a ementa do curso no certificado (em inglês também) para facilitar a interação com gestores que não falam português.
Nota: A importância da ementa (ou no mínimo o nome da disciplina) seria importante para explicar melhor o que foi estudado.

Obrigado

**Comment by designernatan** [comment]
@oswaldomaxado valeu pela sugestao!

uma [issue semelhante foi feita aqui](https://github.com/caelum/alura-funcionalidades/issues/560)

em suma: estamos para melhorar a experiência relacionada aos certificados no futuro, por hora você consegue traduzir colocando o ?en no final :)

---

uma solução de contorno com relação ao conteúdo e nome do curso é pegar o link compartilhável do certificado e [jogar no Google Translate como neste exemplo](https://cursos-alura-com-br.translate.goog/degree/certificate/f7b83d7c-b1f9-44ca-87ad-e6865e77b8a7?_x_tr_sl=pt&_x_tr_tl=en&_x_tr_hl=pt-BR&_x_tr_pto=wapp)

longe do ideal com certeza, mas acredito que já adiante algo

abcs!

**Comment by oswaldomaxado** [comment]
Oi @designernatan , obrigado pelo rápido retorno! Vou usar esta dica.
Fico no aguardo para esta atualização caso seja possível. Se não for sem problemas.
Não sugiro somente jogar no Google translator porque as vezes (não sei te falar a freqüência) sai coisas muito traduzidas ao "pé da letra" que perdem o sentido. Meu gestor é americanos e nas vezes que fiz isso não deu muito certo. Expliquei para ele o contexto dos curso, ele entendeu e achou uma terminologia mais adequada hahah. 

Por exemplo: 
 - SISTEMA DE INFORMAÇÃO PARA APOIO À DECISÃO
 - Google translator: INFORMATION SYSTEM FOR DECISION SUPPORT
 - Melhor tradução: Information Systems for Supporting Decision Making

Abraços

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, podem voltar a comentar se quiserem :)
