### ISSUE TITLE
Certificado formal para Formações

### ISSUE THREAD

**Issue by wagnerFaria** [caelum/alura-funcionalidades#668]
Atualmente o sistema gera certificado formal apenas para cursos mas não para as formações. No certificado formal de formação deveria constar as mesmas informações disponíveis para certificado formal para cursos.

**Comment by andradeisadora** [comment]
oi @wagnerFaria 
faz sentido sim termos um certificado formal pras formações, obrigada pela sugestão! 
vou puxar a ideia pro nosso backlog pro futuro mas sem prazo, ta?

abraço e bons estudos

**Comment by giovana-armidoro** [comment]
oi pessoal, vou fechar a issue, mas podem voltar a comentar se quiserem :)
