### ISSUE TITLE
Hora de imprimir o certificado.

### ISSUE THREAD

**Issue by lucasheverton** [caelum/alura-funcionalidades#669]
Notei uma expêriencia bem ruim na hora que fui "imprimir" o certificado para converter pra PDF. Na hora de imprimir ele vem com texto no rodapé e em cima no header, isso poderia ser facilmente resolvido com o @print seria interessante tirar isso e deixar apenas o certificado.

Um outro detalhe muito importante é que na hora da impressão ou visualização da impressão só mostra uma página do certificado, sendo que os certificados tem frente e verso que mostra a quantidade de exercícios resolvidos e etc. Seria interessante juntar os dois pdfs em um só.

![Screenshot from 2022-05-26 13-06-22](https://user-images.githubusercontent.com/56878243/170528753-62969fb4-ba2f-4d8a-a48a-326633256f82.png)
![Screenshot from 2022-05-26 13-06-25](https://user-images.githubusercontent.com/56878243/170528761-22d9532d-fe7c-4073-bbcb-589eb0adfc82.png)
![Screenshot from 2022-05-26 13-06-31](https://user-images.githubusercontent.com/56878243/170528764-cee7a787-f221-439f-ac4a-1e0c000866aa.png)
![Screenshot from 2022-05-26 13-06-40](https://user-images.githubusercontent.com/56878243/170528766-368eee6d-be9e-4658-a342-1c575e05ee6c.png)
![Screenshot from 2022-05-26 13-06-44](https://user-images.githubusercontent.com/56878243/170528768-792c5d5b-e17a-4dae-ad91-3ca47660d617.png)

**Comment by andradeisadora** [comment]
oi @lucasheverton 
pra remover os textos você pode tirar essa opção aqui na hora da impressão:
![image](https://user-images.githubusercontent.com/84100505/171275849-2237e73a-0432-4f5e-9f03-0870d4c34cb9.png)
assim você consegue salvar somente o certificado :)

sobre salvar frente e verso no pdf:
estamos trazendo melhorias aos poucos pros certificados, já está no nosso radar uma tela melhor pra download e compartilhamento do certificado mas são planos pro futuro, sem prazo ainda :(

abraço e bons estudos!

**Comment by lucasheverton** [comment]
@andradeisadora obrigado pelo retorno.

**Comment by andradeisadora** [comment]
vou fechar a issue mas pode voltar a comentar se quiser :)
