### ISSUE TITLE
Login no Aplicativo mobile Alura através da conta Google

### ISSUE THREAD

**Issue by hmarquesfernando** [caelum/alura-funcionalidades#67]
Olá! Notei uma condição de travamento no aplicativo mobile Alura: como eu me cadastrei no portal através da conta Google, e não preenchendo um formulário próprio, estou impedido de utilizar o app da Alura, pois lá não há a função "Entrar com o Google". Só é possível "Entrar com o Google" no desktop. Essa possibilidade de utilizarmos o app poderia ser implementada?

**Comment by felipetorres** [comment]
Oi! Sou do time de desenvolvimento dos apps, tudo bem com vc?

Já implementamos essa funcionalidade nos apps Android e iOS e estamos em processo de liberação pra vocês. Nosso processo de release é feito aos poucos: liberamos pra 10% dos alunos, depois 20%, 50%... E por aí vai. Então em alguns dias vc terá essa atualização.

No entanto, você deve conseguir logar nos apps mesmo sem o login com Google. No e-mail de boas vindas não tem uma senha para ser usada na plataforma? Se tiver, pode usar essa senha nos apps também.

**Comment by hmarquesfernando** [comment]
Oi, Felipe. Muito Obrigado pelo retorno. De fato não havia visto a possibilidade de alterar a senha, criando uma senha independente da conta Google e, com isso, liberando o acesso ao aplicativo. Com isso já resolveu o meu problema e a função logar com o Google agora seria apenas um plus. Até mais!
