### ISSUE TITLE
Melhoria em migração de perfil

### ISSUE THREAD

**Issue by fernandodevel** [caelum/alura-funcionalidades#670]
Problema: Atualmente estou com um perfil de acesso onde o plano é da empresa, mas agora queria aderir ao meu próprio plano sem perder os cursos que já concluir.
Deveria existir uma opção de alterar o email de acesso. Logo estou saindo da empresa e queria continuar com os cursos, mas não do zero e perder tudo que ja concluir.

**Comment by andradeisadora** [comment]
oi @fernandodevel 
no momento não temos planos pra uma feature assim :( mas você pode falar com o pessoal no email atendimento@alura.com.br pra ver se podem te ajudar

abraço e bons estudos!

**Comment by giovana-armidoro** [comment]
oi pessoal, vou fechar a issue, mas podem voltar a comentar se quiserem :)
