### ISSUE TITLE
Avanço, retrocesso de video e a barra de volume

### ISSUE THREAD

**Issue by MichaelLecter** [caelum/alura-funcionalidades#671]
Acredito que seria muito funcional ter um botão que tivesse a função de retrocesso de 10 segundos ou (10,20,30 segundos), visto que 
uma hora ou outra durante o curso a pessoa possa se distrair e desfocar um pouco por um leve momento, ter essa opção de retrocesso (ou avanço também) seria algo mais confortável de usar do que arrastar a barra de fluxo do video, outra coisa que poderia sugerir é um circulo no final da barra de fluxo do video, para ter um melhor manuseio da barra de fluxo. Aumentar a distancia entre a barra de volume e a barra de fluxo do video também seria útil, visto que estando muito perto, por vezes é possível clicar acidentalmente na barra de fluxo enquanto se regula o volume.

**Comment by andradeisadora** [comment]
oi @MichaelLecter 
hoje em dia já é possível avançar e voltar 10s pelo teclado, só clicar na → (seta direita) e ← (seta esquerda) respectivamente.
você pode conferir mais atalhos pra tela de aula [nessa issue aqui](https://github.com/caelum/alura-funcionalidades/issues/507#issuecomment-891210545)

obrigada pelas outras sugestões! 
no momento estamos sem planos pra mexer na tela de aula :(

abraço e bons estudos!

**Comment by giovana-armidoro** [comment]
oi pessoal, vou fechar a issue, mas podem voltar a comentar se quiserem :)
