### ISSUE TITLE
Não consigo submeter minha resposta (App Mobile - iOS)

### ISSUE THREAD

**Issue by bumerangue** [caelum/alura-funcionalidades#672]
Estou fazendo o curso pelo celular, utilizando o App Mobile para iOS da Alura, mas encontrei alguns problemas:

No primeiro quiz deste curso "Adaptação aos novos cenários", seleciono minha resposta e ao clicar no botão "Próxima atividade", nada acontece.

**Curso: Inovação & Gestão / Liderança e Gestão de Equipes / Tomada de decisão: pensar, analisar e agir**

![IMG_7885](https://user-images.githubusercontent.com/91338680/170869161-20a449e4-5cc1-4cec-aca3-e062476cebaa.PNG)

**Comment by bumerangue** [comment]
Descobri que nesta quiz em específico precisaria de mais uma resposta (eram duas respostas). O problema é que a mensagem que continuava aparecendo (como pode ser visto na imagem), era "selecione 1 alternativa". Como eu já tinha selecionado uma, pensei ser um bug. Na verdade, quando tivermos mais de uma alternativa, a mensagem deveria ser "selecione mais uma alternativa" ou "você deve selecionar duas alternativas".

**Comment by andradeisadora** [comment]
oi @bumerangue :)
obrigada pela sugestão!
faz sentido mesmo deixar mais clara essa mensagem. Puxei a melhoria pro nosso backlog pro futuro mas sem prazo pra te passar ta?

abraço e bons estudos!

**Comment by 1Baldasso** [comment]
Oi @bumerangue se não me engano a mensagem que aparece quando são mais de uma alternativa é o número de alternativas que faltam, nesse caso iniciou como "selecione 2 alternativas", mas ao você selecionar uma, ele desceu para "selecione 1 alternativa" gerando assim a confusão. Pelo menos essa é a usabilidade que eu percebi nos cursos que fiz, apesar de poder sim ser um bug

**Comment by andradeisadora** [comment]
pessoal vou fechar a issue mas podem voltar a comentar se quiserem :)
