### ISSUE TITLE
Post do Forum não aceita espaço entre palavras (App Mobile iOS)

### ISSUE THREAD

**Issue by bumerangue** [caelum/alura-funcionalidades#673]
Tentei escrever no Forum do curso, utilizando o App Mobile para iOS da Alura, mas quando começo a escrever e quero dar um espaço para a próxima palavra ele me joga para o final da tela. Tentei escrever o texto em um e-mail novo e colar, mas também não consigo colar textos no box de textos. 

Desta forma, a utilização do Forum, direto do App Mobile para iOS não funciona.

O problema aconteceu no quando tentei criar uma thread no curso:

**Inovação & Gestão / Liderança e Gestão de Equipes / Tomada de decisão: pensar, analisar e agir**

**Comment by andradeisadora** [comment]
oi @bumerangue 
Fiz o teste aqui e realmente não ta funcionando.. Obrigada por avisar!
Vou passar pro time responsável dar uma olhadinha, mas não tenho prazo pra te passar ta?

Abraço e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
