### ISSUE TITLE
Forum - opção de acompanhar tópico não é intuitiva

### ISSUE THREAD

**Issue by bumerangue** [caelum/alura-funcionalidades#674]
Fiz um post no Forum e a opção de "Acompanhar tópico" não é muito clara. A única mudança que acontece ao clicarmos é o "olho" ficar verde ou azul, mas qual cor seria a de que estou acompanhando? Acho que poderia ser algo mais intuitivo ou claro. 

Como:
"um olho aberto ou fechado"
"um texto para cada status: "Acompanhando tópico" ou "Acompanhar tópico".

![Screen Shot 2022-05-29 at 09 56 14](https://user-images.githubusercontent.com/91338680/170869715-9956e1a7-3eea-4791-a758-29875a56b1e9.png)

**Comment by andradeisadora** [comment]
oi @bumerangue :)
pois é, faz sentido sim ajustar dessa forma. Obrigada pela sugestão!
Vou puxar aqui pro backlog mas não tenho como te passar um prazo ta bem?

abraço e bons estudos!

**Comment by andradeoromulo** [comment]
Olá, pessoal. Implementamos a sugestão e por isso vou fechar a issue, ok? Obrigadão :)
