### ISSUE TITLE
Melhoria na função de busca do site

### ISSUE THREAD

**Issue by MaykiSantos** [caelum/alura-funcionalidades#675]
Olá, gotaria de fazer uma sugestão de melhoria.

**Situação:** Um amigo precisava fazer uma manutenção em um sistema antigo que usava JSF (Coisas mais antigas), mas ele não estava encontrando muita coisa. Lembrei que a algum tempo atraz eu tinha feito um curso que tratava justamente do assunto que ele precisava.
![tela de buscar](https://user-images.githubusercontent.com/58126683/171058601-edf642be-ec55-426d-b5a9-c432194b5ed2.png)
Ao procurar utilizando o sistema de busca do site não encontrei mais o curso. Mas ao procurar pelos cursos que conclui no meu perfil, consegui encontrar o link para o curso. 
![image](https://user-images.githubusercontent.com/58126683/171060539-e1b7c24d-a474-471c-aafe-0e6406e6e34e.png)

**Sugestão:** aparentemente o sistema de busca não traz cursos que foram descontinuados e cursos desatualizados. Seria interesante ter nos filtros a opção de buscar por conteudos desatualizados. Mesmo desatualizados esses cursos podem servir como base para alguem que tem que dar manutenção em um sistema antigo.

**Comment by giovana-armidoro** [comment]
oi Mayki, valeu por trazer essa sugestão!
faz muito sentido, mesmo conteúdos antigos podem ajudar muito nos estudos
por hora não estamos com planos para mexer na busca, mas futuramente, quando formos implementar melhorias nisso, vamos adicionar essa sugestão nas discussões

se precisar de algum conteúdo que foi descontinuado vc pode dar uma olhada nessa página [aqui](https://cursos.alura.com.br/conteudos-descontinuados/cursos), ela tem a listagem de todos os cursos e formações da plataforma que foram descontinuados
esse link também está disponível na página de formações (bem lá no finalzinho da página)

abraços e bons estudos :)

**Comment by edu4ardo** [comment]
Apoio fortemente a sugestão do colega, inclusive abri uma issue com uma sugestão semelhante.

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
