### ISSUE TITLE
Tela escura em todas as paginas da Alura

### ISSUE THREAD

**Issue by MvFelix001** [caelum/alura-funcionalidades#676]
Procurei como deixar a tela escura na deashboard e em toda a pagina da Alura e nao encontrei.
Caso não tiver eu sugiro q seria interessante colocar pois por exemplo no meu caso eu tenho a visão bem sensivel.

**Comment by andradeisadora** [comment]
oi @MastigaBroculis 
infelizmente ainda não temos o dark mode na Alura :( mas está no nosso radar e aos poucos estamos trazendo algumas telas nesse formato

enquanto não chega, você pode fazer o seu dark mode conforme [nessa issue](https://github.com/caelum/alura-funcionalidades/issues/156#issuecomment-632410492)

abraço e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue mas pode voltar a comentar se quiser :)
