### ISSUE TITLE
Ordenação por Data e Hora Log de acesso ordena pelo dia mas não pelo mês.

### ISSUE THREAD

**Issue by 1Baldasso** [caelum/alura-funcionalidades#677]
Ao escolher a opção Data e Horário no Log de acesso, o dia 01/06 vem antes de 31/05, está ordenando a lista apenas pelo dia, mas não pelo mês
![Capturar](https://user-images.githubusercontent.com/82400557/172293980-644bede1-2cf3-4f72-8f6f-02e49cf07bfe.PNG)

**Comment by giovana-armidoro** [comment]
oi Lucas, valeu por reportar isso!
realmente é um bug na ordenação dessas datas, já levamos isso para o time de dev
mas como o time está com alta demanda não tenho previsão de data, ok? 

abraços e bons estudos!

**Comment by dudusumeck** [comment]
Oi @giovana-armidoro, a correção está no ar.

**Comment by giovana-armidoro** [comment]
oi pessoal, vou fechar a issue, mas podem voltar a comentar se quiserem :)
