### ISSUE TITLE
Poder gravar o minuto e segundo de algum video, com anotações

### ISSUE THREAD

**Issue by anselmo-rcoelho** [caelum/alura-funcionalidades#678]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.
Gostaria que fosse adicionado uma ferramenta que permitisse que, durante o vídeo, eu adicionasse uma anotação e que nela ficasse gravado também o minuto e segundo do vídeo que eu estava assistindo, no momento da criação da nota.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.
Assim, no curso do .NET5 API, em determinado momento, foi explicado como faço a configuração para que, ao compilar, não abrisse o browser. Cheguei a fazer a anotação num papel, mas eu perdi o papel e tive que voltar e assistir praticamente uns 4 vídeos até encontrar como faz.
Ai, seria o ideal deixar essas anotações em algum lugar para que eu possa ver todas e ter um link que abrisse o vídeo no minuto que esta na anotação.

**Comment by designernatan** [comment]
@anselmo-rcoelho valeu pela sugestao e desculpa o delay

nós tínhamos planos para algo assim, um combo com o caderno do aluno, mas acabamos abortando pois não atingiu nossa expectativa (não só em engajamento como em outros pontos) o que esperávamos quando lançamos o MVP em 2018/19

se algo mudar pingamos aqui de qualquer forma para explorar mais e papear contigo!
