### ISSUE TITLE
Classificação de cursos com base na experiência prévia

### ISSUE THREAD

**Issue by ofelipe-s** [caelum/alura-funcionalidades#679]
Seria legal se tivesse uma classificação de acordo com a experiência que o usuário já tem naquela área. Por exemplo, se o usuário estiver navegando pelos cursos de programação, mas não sabe nada sobre, qual o curso que ele deve fazer primeiro? Seria interessante uma classificação padrão da plataforma dizendo qual o nível de "dificuldade" ou de experiência necessária para fazer aquele curso.

**Comment by giovana-armidoro** [comment]
oi Felipe, valeu pela sugestão
essa é uma questão super válida, temos pensado em várias estratégias e soluções que poderiam ajudar nisso
em breve lançaremos algumas atualizações que poderão ajudar nessa questão, fica de olho 👀

enquanto isso você pode conferir alguns planos de estudos públicos disponibilizados pela comunidade Alura [aqui](https://cursos.alura.com.br/planos-estudos-publicos)

quando tiver alguma novidade te atualizo por aqui

abraços e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue mas podem voltar a comentar se quiserem :)
