### ISSUE TITLE
Modo Escuro

### ISSUE THREAD

**Issue by breno2012** [caelum/alura-funcionalidades#68]
Gostaria muito que fosse implementada a opção de modo escuro na plataforma, pois o fundo branco acaba agredindo a visão após certo tempo de uso.

**Comment by designernatan** [comment]
@breno2012 valeu pela sugestao!

em qual parte da alura voce sente mais essa necessidade? 

(sou usuario de dark mode em tudo também)

abcs!

**Comment by breno2012** [comment]
Sinto necessidade principalmente nas aulas. Costumo sempre ler as transcrições dos vídeos e com o passar do tempo o fundo branco acaba agredindo minha visão.

**Comment by designernatan** [comment]
show @breno2012 ! tenho uma noticia boa entao!

clicando no ícone de espetinho na parte superior direita, dentro da aula, vc consegue ativar o modo noturno (tá meio escondido né?)

por hora esse dark mode está só na aula, ideia é expandir caso identifiquemos que a galera tem usado

**Comment by designernatan** [comment]
fechando a issue, mas pode comentar mesmo com ela fechada, ok?

abração!
