### ISSUE TITLE
Informação aparece antes de terminar o curso

### ISSUE THREAD

**Issue by wellington197** [caelum/alura-funcionalidades#680]
Quando efetuamos os estudos da formação, fica aparecendo sempre como se curso estivesse finalizado. Mesmo ainda com os módulos em andamento.

Fiquei até em dúvida de o porquê que aparecia a informação.

Seria interessante se aparecesse a informação de " Você está próximo de finalizar a sua formação" ou algo assim, para que ficasse mais intuitivo.

E ao finalizar o curso a imagem do certificado ficasse verde e informasse que realmente ele finalizou o curso. E link para certificado.

Segue link da imagem.

![Capturar](https://user-images.githubusercontent.com/98292924/173411322-338ee6fd-cf2c-4424-9624-34ab6e99c37a.JPG)

Detalhe. Foi na formação de QA, que percebi..kkkkkkk

**Comment by designernatan** [comment]
@wellington197 opa valeu pela sugestao!

acho que isso deve ser aqueles bugs que fazem aniversário :P

vamos dar uma conferida e qualquer novi pingamos aqui!

boa semana!

**Comment by wellington197** [comment]
De nada Natan. Obrigado.

Em seg., 4 de jul. de 2022 às 08:50, Natan Souza ***@***.***>
escreveu:

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!

**Comment by wellington197** [comment]
Thank you!

Em qua., 24 de ago. de 2022 às 16:07, Natan Souza ***@***.***>
escreveu:

**Comment by joaovitormarcilio** [comment]
Passando rapidinho aqui para avisar que issue foi corrigida. Caso precisem de mais alguma coisa é só abrir uma nova.
