### ISSUE TITLE
Certificado em Ingles

### ISSUE THREAD

**Issue by AzeredoLola** [caelum/alura-funcionalidades#681]
Como sabemos, ingles é fundamental para a area de tecnologia. Portanto, por que nao a possibilidade de emissao do Certficado dos Cursos em Ingles?
Principalmente pra que quem ta buscando emprego fora do  BR, o certificado em ingles ajuda bastante na visibilidade dos "buscantes" para quem ta recrutando.

**Comment by giovana-armidoro** [comment]
oiee, valeu pela sugestão!
algumas issues parecidas já foram feitas, [como essa](https://github.com/caelum/alura-funcionalidades/issues/560)

temos planos para melhorar a experiência relacionada aos certificados no futuro, por hora temos um "hack" feito para conseguir isso no modelo atual: é só  você adicionar o parâmetro lang=en (ou es) ao final da URL do certificado que ele gera o certificado traduzido em inglês!

com certeza não é a solução ideal, mas já pode te ajudar no momento

exemplo de URL com esse parâmetro:
https://cursos.alura.com.br/certificate/giovanaarmidoro/comunicacao?lang=en

abraços e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue mas podem voltar a comentar se quiserem :)
