### ISSUE TITLE
Certificado Normal - pdf gerado não imprime a segunda folha

### ISSUE THREAD

**Issue by gemerson74** [caelum/alura-funcionalidades#682]
Na visualização do certificado normal aparecem duas folhas. Mas quando salvo o pdf, só vem a primeira folha.

**Comment by masromao** [comment]
Olá @gemerson74 , obrigado pelo apontamento.
Por enquanto a melhor forma de fazer isso é salvar separadamente, uma página de cada vez (e os certificados ficarão sempre disponíveis para você fazer isso quando precisar).

Abraços e bons estudos!

**Comment by mandrade1stf** [comment]
Salvar separadamente não é o ideal, se  precisar enviar são pelo menos 2 arquivos, pior se for para concorrer em alguma vaga, mostra uma certa desorganização do candidato e por tabela a Alura.
Outro detalhe é colocar as mesmas informações que tem no certificado formal (dados da Alura por exemplo)

**Comment by designernatan** [comment]
@mandrade1stf otimo ponto!

nesse quesito um caminho interessante é usar o certificado completo para esses casos, já resume bem a informação sobre quais cursos foram cursados e adianta o lado da pessoa que vai filtrar os currículos

---


fechando a issue, mas ela continua aberta para comentários futuros!
