### ISSUE TITLE
Favoritar e deletar novidades

### ISSUE THREAD

**Issue by kleber-smartdev** [caelum/alura-funcionalidades#683]
Sou novo por aqui e gostei muito da secão novidades, porém acho que deveria ter a função tanto no app como no site de favoritar ou cancelar no modelo swap de tinder. No meu perfil teria uma seção de favoritos que eu podria consultar sempre que quiser, assim meu novidades ficaria apenas os meus interesses.

Quem perder ou apagar sem querer pode ir até o novidades global do site e favoritar de lá também.

Espero ter contribuido

Kleber

**Comment by andradeisadora** [comment]
oi @kleber-smartdev 
Infelizmente não temos planos de fazer uma feature assim mas obrigada pela sugestão!
hoje você já pode favoritar na tela do curso clicando no botão <outras ações>
![image](https://user-images.githubusercontent.com/84100505/177885199-c4d8fde3-54da-4d1f-8ec3-be6b6083597a.png)
e desfavoritar no mesmo lugar. Assim ele vai pra sua dashboard nos cursos em andamento.

Abraço e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
