### ISSUE TITLE
Retornar com a visualização de todos os cursos

### ISSUE THREAD

**Issue by LucasMend0n** [caelum/alura-funcionalidades#684]
Na boa pessoal, essa parada de tirar a visualização da totalidade dos cursos eh muito ruim. As escolas limitam muito o que a gente pode achar nao consegui nem achar os cursos de Django que eu tava fazendo

**Comment by designernatan** [comment]
@LucasMend0n valeu pela sugestao!

acabamos atualizando uma parte da alura antes de atualizar outra

na nova pagina de escolas será possivel ver todos os cursos igual a atual

aproveitando esse ponto sobre django, vc tem estudando pela formação ou só pelos cursos soltos? https://www.alura.com.br/formacao-django

Abcs!

**Comment by LucasMend0n** [comment]
Opa Natan! 

Valeu pelo esclarecimento, tava estudando só pelos cursos soltos, por isso me perdi na plataforma. Vou seguir pela formação

Obrigado dmais cara!

**Comment by designernatan** [comment]
feshow meu caro! Valeu vc e bons estudos! :)

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, mas podem voltar a comentar se quiserem :)
