### ISSUE TITLE
Pesquisa nos podcast

### ISSUE THREAD

**Issue by marigperton** [caelum/alura-funcionalidades#685]
Olá pessoal! tudo bem?
Gostaria de sugerir pesquisa nos podcasts.
Quando clico em ver todos, tem mais de 20 páginas, seria muito útil ter uma pequena pesquisa pra pesquisar em cada aba assuntos dos podcasts para ir direto em um assunto em específico.
Obrigada!

**Comment by masromao** [comment]
olá @marigperton , valeu pela sugestão!
essa é uma questão super válida, levaremos para o nosso backlog para o futuro, mas por enquanto não temos um prazo para te passar, ok?

abraços e bons estudos!

**Comment by designernatan** [comment]
oi pessoal, fechando a issue mas ela continua aberta para comentários futuros!

edit:
sei que nao é o ideal, mas [na busca tem um filtro de podcasts](https://cursos.alura.com.br/search?query=java&typeFilters=HIPSTERSTECH) que pode ajudar a procurar um assunto específico :)
