### ISSUE TITLE
target="_blank" in "link" Podcast

### ISSUE THREAD

**Issue by rsilvadink** [caelum/alura-funcionalidades#686]
Dentro dos Postcast, os Links não sao target="_blank", ou seja, abre na pagina e para o player...
Isso não ocorre para os link de Participantes, mas sim para os links de referencias...

abraço

**Comment by designernatan** [comment]
@rsilvadink valeu pela sugestao!

testei com esse aqui especificamente, todos estão sem o blank, mas era uma boa pelo menos esses ficarem com ele mesmo para nao interromper a reproducao

enquanto nao pegamos isso, por hora caminho é ir clicando com "ctrl" ou com o scroll do mouse

abcs e bons estudos

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
