### ISSUE TITLE
Criar planos de estudo com duas ou mais formações.

### ISSUE THREAD

**Issue by rpfreitas111** [caelum/alura-funcionalidades#687]
Talvez seja uma função interessante a possibilidade de juntar duas formações dentro de um plano de estudo pessoal.

Exemplo estou estudando programação  e quero aprender também orientação objeto com C#, então como não sei nada de programação acho interessante adicionar a formação logica de programa com a formação programação orientada a objeto C#, desta forma eu estou vendo minha linha de estudo  já sabendo para onde estou indo não vou precisar gastar tempo novamente criando ou  buscando novas formações.

**Comment by designernatan** [comment]
@rpfreitas111 valeu pela sugestao!

hoje vc já consegue adicionar as formações ali no seu PDE normalmente, até fiz um teste aqui pra ver se tava com algum bug mas parece que ta tranquilo

se precisar colocar elas tpo "abertas", ai precisa ser na mao mesmo :/

![image](https://user-images.githubusercontent.com/5431347/177047069-cb5c95d0-3802-44e9-ad20-db3644338c3e.png)

**Comment by designernatan** [comment]
fechando a issue, mas ela continua aberta para comentários futuros!
