### ISSUE TITLE
Criar cronograma de estudo

### ISSUE THREAD

**Issue by edu4ardo** [caelum/alura-funcionalidades#688]
Permitir criar um cronograma de estudo informando a quantidade de horas disponíveis a cada dia da semana após ter selecionado determinada formação.
Isso permite o acompanhamento do cronograma ao longo dos dias, onde o marco fica sendo não um curso/artigo ou podcast concluído, além de deixar a pessoa mais engajada ao ver seu acompanhamento diário no cronograma.
Isso é uma funcionalidade de tem dado muito certo em cursos prepatorórios, principalmente os cursos online.

**Comment by andradeisadora** [comment]
oi @edu4ardo obrigada pela sugestão!
Infelizmente não estamos com planos de fazer uma feature assim no momento mas atualmente você consegue ver a sua pontuação e dias de estudo próximo a sua foto do perfil no menu da alura:
![image](https://user-images.githubusercontent.com/84100505/177890570-d39df3b6-d66b-4ec2-bdf2-d2f2e0425551.png)

Conforme você vai estudando, o grid vai preenchendo com os dias e as cores.
Cada cor é referente a uma pontuação diferente, aqui está da mais baixa (esquerda) pra mais alta (direita):
![image](https://user-images.githubusercontent.com/84100505/177890583-4283916c-7503-4ccd-806f-c21b30d06730.png)

Outra sugestão é que você pode ir marcando no notion ou no excel os dias de estudo e o que você estudou também.

No futuro se pensarmos em alguma feature semelhante a sua sugestão levaremos em consideração suas ideias :)

abraço e bons estudos!

**Comment by designernatan** [comment]
oi pessoal, fechando a issue mas ela continua aberta para comentários futuros!
