### ISSUE TITLE
Criar pesquisa de cursos descontinuados por categoria ou descricao

### ISSUE THREAD

**Issue by edu4ardo** [caelum/alura-funcionalidades#689]
Permitir em determinada tela na plataforma uma forma de consulta de cursos descontinuados, seja a pesquisa pela categoria/descrição ou tipo.
Isso vai permitir o acesso facilitado aos cursos que são muito bons, e hoje estão com o acesso um tanto difícil.
Motivação: Diversas empresas não trabalham somente com tecnologia de ponta, quando precisamos estudar ou revisar uma tecnologia que não esteja em alta para realizar uma manutenção qualquer. Esses cursos que estão descontinuados estão subvalorizados sem uma forma de fazer uma pesquisa decente.

**Comment by andradeisadora** [comment]
oi @edu4ardo 
obrigada pela sugestão :)
a Gi explicou sobre esse assunto nessa [issue aqui](https://github.com/caelum/alura-funcionalidades/issues/675#issuecomment-1147462783)

abraço e bons estudos!

**Comment by designernatan** [comment]
oi pessoal, fechando a issue mas ela continua aberta para comentários futuros!
