### ISSUE TITLE
Flashcards para notas do Caderno

### ISSUE THREAD

**Issue by giorgiobraz** [caelum/alura-funcionalidades#69]
Seria muito útil, para determinados cursos, criar flashcards (usando repetição espaçada) para fixar os conteúdos.

**Comment by designernatan** [comment]
oi @giorgiobraz valeu pela sugestao!

pode elaborar mais por favor?
Acho que entendi mas quero evitar viés confirmatório 

aproveitando, me fala como você está usando o caderno atualmente

abcs!

**Comment by giorgiobraz** [comment]
Aah legal, então vamos lá…

O que pensei foi numa feature opcional (fazer parte do _Caderno_, mas que eu possa escolher usá-la ou não). Os flashcards seriam no estilo Anki ou mesmo aqueles da Alura Línguas, que te lembram periodicamente, de acordo com o seu nível de acertos, para revisar determinado conteúdo.

**Sobre a funcionalidade:** usarei um exemplo para explicar melhor. Fazendo o curso de Estatística da Alura, quero me lembrar a definição e fórmula para o cálculo da mediana, então vou até meu _Caderno_ e crio um flashcard com a pergunta: ‘O que é mediana e como se calcula?’ (Eu posso criar essa pergunta ou o sistema poderia usar o banco de dados dos exercícios dos instrutores e criar os flashcards). Então, depois de responder mentalmente, exibo a resposta e seleciono uma opção que corresponde ao meu nível de acerto (fácil, médio, difícil…) e o algoritmo determina qual a próxima vez que me mostrará a pergunta novamente.

**Sobre meu uso atual do Caderno:** no momento, estou apenas tomando notas que considero mais importantes. Já fazia isso antes em aplicativo externo, mas ter isso integrado é muuuito bom. Parabéns pela ideia e implementação de vocês!!

**Comment by designernatan** [comment]
opa valeu pela descrição giorgio, isso ajuda bastante aqui! Anotei aqui para discutirmos isso no futuro, por hora, sem previsão para algo próximo disso (apesar de eu achar que pelo sistema já existir na alura lingua deve ser meio caminho andado também)

opa valeu pelo feedback! Passando para o time envolvido no caderno aqui. 😀

fechando a issue aqui mas pode dar reply anytime aqui

abcs!
