### ISSUE TITLE
Certificado Formação

### ISSUE THREAD

**Issue by pedrocarvalhoit** [caelum/alura-funcionalidades#690]
Olá, não seria interessante gerarem também certificados das formações?
Da mesma forma que a cada curso tenho acesso à um certificado, seria legal ter um certificado único para as formações que englobam vários cursos.
Muito obrigado pela atenção.

**Comment by masromao** [comment]
olá @pedroduartept , muito obrigado pelo contato!
atualmente a plataforma oferece sim os certificados para as Formações, olha que legal!
basta finalizar todos os cursos daquela Formação específica e os conteúdos extras, que assim que terminar a Formação, seu certificado estará lá em Perfil & Certificados.

abraços e bons estudos!
