### ISSUE TITLE
 Criação de opção para favoritar (Artigo, Podcast, Alura+) 

### ISSUE THREAD

**Issue by maicon1980** [caelum/alura-funcionalidades#691]
Prezados,

Poderiam analisar a possibilidade de implantar uma forma de colocar um [artigo, podcast, alura+] como conteúdo favorito ou algo do tipo para ser visto posteriormente. EX: Assistir mais tarde do Youtube ou uma playlist.

Obrigado.

**Comment by andradeisadora** [comment]
oi @maicon1980, obrigada pela sugestão :)
faz sentido mesmo poder favoritar mas infelizmente não estamos com planos pra essa feature nesses tipos de conteúdos :(
você pode criar um plano de estudos e ir adicionando esses conteúdos para poder ver mais tarde, assim não perde o link

abraço e bons estudos!

**Comment by designernatan** [comment]
oi pessoal, fechando a issue mas ela continua aberta para comentários futuros!
