### ISSUE TITLE
feat: Criação de favoritação para podcast

### ISSUE THREAD

**Issue by CaioCesarP** [caelum/alura-funcionalidades#692]
Descreva a funcionalidade que você gostaria que tivesse na plataforma:
- Quando o usuário entra no site e se depara com um podcast interessante ele gosta de ir verificar e ficar ligado, entretanto normalmente os podcast, por serem ricos de informação, são longos e nem sempre a pessoa tem tempo para escutar todo, mesmo bastante interessada em entender todo o programa. Portanto, é interessante a criação de um botão, provavelmente estrelinha, ou um marcador que deixasse no perfil do usuário a listagem de seus podcast. É similar a um assista mais tarde de outras plataformas ou apenas algo para favoritar mesmo. 

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos:
- Implementada uma página ou painel de visualização com esses "marcados" ou "favoritados".
- Criação do botão necessário para adicionar podcast aos favoritos.

Extra: 
-Criação de um relacionados, no painel ou página criada para colocar os favoritados ou marcados, de acordo com tema ou tipo de podcast escutado, buscando expandir ainda mais outros podcast para o público.

**Comment by guilhermelombardi** [comment]
Olá, Caio, Tudo bem?
Obrigado pela sugestão, realmente achei bem interessante, levarei para o time discutir a viabilidade da feature.

Abraços e bons estudos.

**Comment by guilhermelombardi** [comment]
fechei a issue, mas podem voltar a comentar se quiserem.
