### ISSUE TITLE
Alura kut commons arquivo com vários warns e um erro

### ISSUE THREAD

**Issue by ilsochrist** [caelum/alura-funcionalidades#693]
![image](https://user-images.githubusercontent.com/100448527/178274661-2d8e81c8-9e4d-4c1e-b286-e32abc16371e.png)

**Comment by guilhermelombardi** [comment]
Olá, Ilson, tudo bem?
Acredito que essa seja uma dúvida referente a aula, nesses casos você pode usar o fórum ou trazer a dúvida pra discutir com outros alunos e alunas pelo nosso Discord. Espero ter ajudado! :)
Qualquer dúvida ficamos a disposição.

Abraços.

**Comment by ilsochrist** [comment]
Boa tarde, então desculpa a palavra mas você só pode estar de sacanagem?
O código está quebrado, o erro está ai, e você me vem falar de fórum? Vergonha não ser refatorado e a preguiça de querer olhar.

**Comment by guilhermelombardi** [comment]
Ilso, entendo sua frustração, erro nos arquivos de um curso complicam bastante pois adiam nossos estudos.

São milhares de cursos na Alura hoje, infelizmente aqui no time de UX não conseguimos reconhecer trechos de código de todos.

O caminho ideal para casos assim realmente é o [fórum](https://cursos.alura.com.br/forum/todos/1) ou mesmo o Discord da Alura, onde o time de Scuba consegue diagnosticar, direcionar você e corrigir os erros para ajudar outros alunos e alunas que estão tendo o mesmo problema. 

Inclusive já tinha pingado o time de Scuba (antes do reply aqui) para dar uma atenção para isso quando for postado no fórum ou no Discord.

**Comment by ilsochrist** [comment]
Po cara, bagunça demais. Isso é React não é UX, sei lá, bizarro isso.
