### ISSUE TITLE
Tentei clonar e instalar as dependências, mais erros no Alurakut

### ISSUE THREAD

**Issue by ilsochrist** [caelum/alura-funcionalidades#694]
![image](https://user-images.githubusercontent.com/100448527/178275099-4c642f46-395a-427f-9107-bb4cd240266c.png)

**Comment by guilhermelombardi** [comment]
Olá, Ilson, tudo bem?
Acredito que essa seja uma dúvida referente a aula, nesses casos você pode usar o fórum ou trazer a dúvida pra discutir com outros alunos e alunas pelo nosso Discord.
Qualquer dúvida ficamos a disposição.

Abraços.

**Comment by ilsochrist** [comment]
Boa tarde, então desculpa a palavra mas você só pode estar de sacanagem?
O código está quebrado, o erro está ai, e você me vem falar de fórum? Vergonha não ser refatorado e a preguiça de querer olhar um código de uma imersão que está jogado e estão nem ai. Arrependimento imenso de ter assinado a Alura. Vou postar o tratamento aos alunos nos fóruns por ai e que ainda está pagando.

**Comment by guilhermelombardi** [comment]
fechando essa issue pq estamos tocando o mesmo assunto na outra.
