### ISSUE TITLE
Resetar progresso do curso

### ISSUE THREAD

**Issue by ghost** [caelum/alura-funcionalidades#695]
Uma funcionalidade para restar o progresso do curso. Pois eu estou querendo rever alguns cursos. Mas ao voltar para continuar o curso que estou fazendo por vezes fico perdido. Pois quando o curso esta terminado ele vai de volta para a primeira aula. Independente de eu ter estado la por ultimo ou não. Ou se isso for muito complexo/caro ao menos não tirar do capitulo aonde estou estudando após completar o curso.

**Comment by guilhermelombardi** [comment]
oi, Paulo, tudo bem?
obrigado pela sugestão, tem uma issue [igual a essa aqui](https://github.com/caelum/alura-funcionalidades/issues/11)

infelizmente por hora não temos planos para resetar cursos ou formações, de qualquer forma sempre discutimos formas de melhorar essa experiência para os alunos e alunas.

abraços.

**Comment by guilhermelombardi** [comment]
fechei a issue mas podem voltar a comentar se quiserem.
