### ISSUE TITLE
Pausar reprodução pelo botão de fone de ouvido - App Mobile

### ISSUE THREAD

**Issue by Moscarde** [caelum/alura-funcionalidades#696]
A funcionalidade seria: durante os vídeos do aplicativo móvel, fosse possível parar ou continuar a reprodução de acordo com botões de fone de ouvido / caixas de som.

Não pude testar se isso só acontece no meu aparelho ou em todos. Mas quando estou estudando por ele e preciso fazer uma pausa rápida, ao apertar o botão do fone, o vídeo continua e é inciado uma musica no spotify ou outro reprodutor que estiver aberto.

**Comment by felipetorres** [comment]
Oi @Moscarde, se o Spotify estiver fechado e vc apertar o botão do fone, o vídeo da Alura é pausado? Talvez seja algo relacionado a alguma prioridade: o último app de mídia a ser aberto "rouba" o controle do Bluetooth, sabe?

**Comment by guilhermelombardi** [comment]
fechei a issue, mas podem voltar a comentar se quiserem.
