### ISSUE TITLE
Cases de ux/ui design e, também, cases de produto

### ISSUE THREAD

**Issue by Julis01** [caelum/alura-funcionalidades#697]
Cases de ux/ui deign e de produto, assim como encontramos cases para os devs.

**Comment by guilhermelombardi** [comment]
opa @Julis01, a gente como time de produto aqui da Alura acha a ideia excelente também, mas infelizmente no momento não temos nada no radar.

**Comment by guilhermelombardi** [comment]
fechei a issue, mas podem voltar a comentar se quiserem.
