### ISSUE TITLE
Legendas ao invés de transcrição

### ISSUE THREAD

**Issue by MauricioMaurente** [caelum/alura-funcionalidades#699]
Sugiro que os vídeos tenham legendas, ao invés de transcrição em separado. Para pessoas com surdez e TDHA, é quase inviável assistir os cursos da Alura.

**Comment by guilhermelombardi** [comment]
oi @MauricioMaurente, valeu pela sugestão.
internamente já começamos testar legendas em alguns cursos, por se tratar de um trabalho mto grande infelizmente não consigo te passar um prazo pra implementação.

**Comment by designernatan** [comment]
oi pessoal, fechando a issue mas ela continua aberta para comentários futuros!
