### ISSUE TITLE
Remoção de cursos da tela do dashboard

### ISSUE THREAD

**Issue by aleroxac** [caelum/alura-funcionalidades#7]
Criação de funcionalidade que permita ao usuário remover um curso da tela "Meus Cursos", esteja ele em andamento ou em pausa.
URL da tela em questão: https://cursos.alura.com.br/courses/mine#all

**Comment by designernatan** [comment]
Oi @aleroxac, tudo certo?

A exclusão do curso por enquanto não está nos planos, mas pensando nessa issue de separar o que não estamos mais estudando hoje do que estamos que há um tempo criamos a feature de **pausar o curso**. Só ir no curso e clicar em 'Pausar'.

Pode me dar mais detalhes sobre o motivo que o pausar não mata o problema? Quero entender melhor o seu uso (do ponto de vista de UX).

Em 'Meus cursos' os cursos em pausa ficam bem isolados no fim da lista. E no perfil público do aluno **somente** estão os cursos concluídos. 

Abcs e obrigado pela sugestão!

**Comment by aleroxac** [comment]
Organização + TOC

Além das formações e dos guias de estudo que podemos criar, como forma de agrupar interesses, também costumo acessar alguns cursos e assistir as primeiras aulas para ver se o conteúdo vale a pena.
Procuro seguir um plano de estudos e só voltar nesse curso(curso visitado por curiosidade) quando me sento seguro com outros temas, há tambpém os casos em que o curso não me chama tanto a atenção. O recurso de pausa é bacana, mas e em casos em que não pretendo retomar o curso?

Se imaginássemos a tela do dashboard como um kanban, diria que crio algumas tasks que me arrependo ou que simplesmeste eram para ser pontuais e/ou temporárias e não devem fazer parte da sprint.

**Comment by designernatan** [comment]
excelente, muito obrigado augusto!

---

se alguém tiver outra consideração sobre esse ponto só comentar aqui também

**Comment by bjverde** [comment]
@designernatan para mim a funcionalidade de remover está ligada com a funcionalidade [Resetar progresso nos cursos e formações](https://github.com/caelum/alura-funcionalidades/issues/11).

As duas podem ajudar muito tendo um DashBorad mais limpa e/ou organizada.

**Comment by aleroxac** [comment]
Ontem estava mexendo na plataforma e descobri uma maneira de resetar e deletar cursos dadashboard: com o curso pausado, basta favoritar e desafavoritar que ele reseta seu progresso e remove da dashboard.

**Comment by bjverde** [comment]
@aleroxac 
> Ontem estava mexendo na plataforma e descobri uma maneira de resetar e deletar cursos dadashboard: com o curso pausado, basta favoritar e desafavoritar que ele reseta seu progresso e remove da dashboard.

Obrigado pela dica ! De certa forma resolveu meu problema
