### ISSUE TITLE
Pequena correção

### ISSUE THREAD

**Issue by ZupC** [caelum/alura-funcionalidades#70]
Descreva a funcionalidade que você gostaria que tivesse na plataforma. Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

Estava analisando os cursos front-end e me deparo com essa duplicidade
![image](https://user-images.githubusercontent.com/59620167/74374019-5b597080-4dbc-11ea-9bc6-806f139f71a8.png)
(O mesmo ocorre com a parte 1 e 2)
O conteúdo dos cursos são diferentes mas o nome deles estão idênticos.

**Comment by designernatan** [comment]
oi @ZupC valeu pelo toque!

 num futuro proximo isso vai ser consertado com a desativação dos cursos mais antigos (do instrutor alberto)
