### ISSUE TITLE
Filtro para a área de cursos concluídos.

### ISSUE THREAD

**Issue by brenascimento** [caelum/alura-funcionalidades#700]
Parecido com a issue #675 - Porém em vez de cursos descontinuados, para cursos concluídos no próprio perfil do aluno.

Motivação: As vezes estamos cadastrando novos currículos em que é necessário a adição das nossas certificações, e um filtro por categoria do curso concluído no perfil ajudaria a selecionar melhor quais certificações adicionar para uma determinada vaga de emprego.

Edit1: Uma Sugestão seria:

- Adicionar um botão entre os filtros "Data de Inicio", "Data de Finalização", um botão de filtros em que ao clicar, teria uma "div" que poderiamos selecionar checkboxes por Área de Estudo(DevOps, Data Science, ...)
- O números de curso finalizados dessa determinada área de estudo ao lado da label do filtro
- E no filtro somente aqueles tipos de cursos em que o aluno estudou, economizando assim espaço em áreas que o aluno sequer teve contato.

**Comment by guilhermelombardi** [comment]
oi @brenascimento, valeu pela sugestão.
realmente é uma melhoria interessante pro perfil do aluno, vou conversar com o time pra entender a viabilidade, de qualquer forma agora não consigo te passar um prazo para execução, ok?

**Comment by designernatan** [comment]
oi pessoal, fechando a issue mas ela continua aberta para comentários futuros!
