### ISSUE TITLE
Conta corporativa vinculada a conta pessoal

### ISSUE THREAD

**Issue by rodsonnazario** [caelum/alura-funcionalidades#701]
Para os alunos com conta corporativa, criar uma opção de email secundário, onde seria possível vincular com uma conta pessoal. Dessa forma, os alunos teriam a opção de logar informando email corporativo ou usando a funcionalidade de "entrar com facebook" ou "entrar com google".

A organização onde trabalho nos oferece a Alura e outra plataforma do mercado, e nessa plataforma tem essa opção. Nela podemos usar tanto o email corporativo como o pessoal, e a senha é a mesma pra ambos.

**Comment by andradeisadora** [comment]
oi @rodsonnazario 
obrigada pela sugestão!
infelizmente hoje em dia não é possível fazer algo assim pq a conta do aluno corporativo fica vinculada ao email que o gestor coloca no momento do cadastro do aluno

vc pode me contar um pouco do pq vc pensou nesses botões?

**Comment by rodsonnazario** [comment]
Ola @andradeisadora, a ideia era só facilitar o login mesmo.
Na empresa onde trabalho, por exemplo, usamos nossa conta pessoal pra gerenciar os favoritos do navegador e, no meu caso, isso facilitaria o acesso com o botão do google. Como não podemos salvar as senhas no navegador, que é administrado pela organização, toda vez que acesso o portal da Alura preciso digitar meu login corporativo.

Mas agradeço pela resposta, e não é por isso que vou deixar de estudar pelo Alura.

**Comment by andradeisadora** [comment]
obrigada pelo retorno @rodsonnazario :)

abraço e bons estudos!
