### ISSUE TITLE
erro "por: Aluno"

### ISSUE THREAD

**Issue by chipbb** [caelum/alura-funcionalidades#702]
Vários posts no forum mostram "por: Aluno" em vez de mostrar o nome da pessoa. E se você clicar em "Aluno" cai em "page not found".

![image](https://user-images.githubusercontent.com/52798495/180670409-52aa28c3-feff-4e4a-b138-155786e4b1bb.png)

![image](https://user-images.githubusercontent.com/52798495/180670549-a1eaabf9-0d5d-4195-aa08-82e518b9360b.png)

**Comment by andradeisadora** [comment]
oi @chipbb :)
esses alunos alteraram a privacidade do perfil para privado por isso o nome não aparece. Você consegue clicar no tópico mas não consegue clicar no nome.
você conseguiu pq ta rolando um bug que vamos consertar, inclusive obrigada por avisar haha 

abraço e bons estudos!
