### ISSUE TITLE
Pausar vídeo ou podcast com o fone de ouvido 

### ISSUE THREAD

**Issue by Alisonais** [caelum/alura-funcionalidades#703]
Olá pessoal! 

Quando estamos vendo um vídeo ou um podcast precisamos pausar no vídeo ou player seria interessante conseguir pausar pelo fone de ouvido com fio ou Bluetooth, seria ainda melhor se conseguir avançar ou retroceder usando os comandos do fone.

**Comment by andradeisadora** [comment]
oi @Alisonais 
infelizmente hoje em dia não é possivel fazer essas ações pelo fone e não estamos com planos de implementar essa feature mas você consegue fazer isso tudo pelo teclado:
- pausar e dar play no video: espaço e tecla K
- aumentar o volume: ↑ (seta p/ cima)
- baixar o volume: ↓ (seta p/ baixo)

[aqui nessa issue](https://github.com/caelum/alura-funcionalidades/issues/507#issuecomment-891210545) tem outros atalhos do teclado pra vc dar uma olhadinha :)
abraço e bons estudos!

**Comment by designernatan** [comment]
oi pessoal, fechando a issue mas ela continua aberta para comentários futuros!
