### ISSUE TITLE
Certficados em Inglês 

### ISSUE THREAD

**Issue by Patrickalvares** [caelum/alura-funcionalidades#704]
Seria bacana se no link que temos acesso aos certificados dos cursos concluidos, além do certificado formal, tivessemos ele traduzido para inglês, para facilitar na divulgação de vagas ao exterior.

**Comment by andradeisadora** [comment]
oi @Patrickalvares 
já pensamos em novas versões de certificado pro futuro e está mapeado os certificados em inglês e espanhol mas não tenho prazo pra te dar

enquanto isso você pode adicionar o parâmetro lang=en (ou es) na URL do certificado que ele gera o certificado no idioma :)

um exemplo aqui:
https://cursos.alura.com.br/certificate/natan-souza/acessibilidade-web-front-end?lang=en

abraço e bons estudos!

**Comment by designernatan** [comment]
oi pessoal, fechando a issue mas ela continua aberta para comentários futuros!
