### ISSUE TITLE
Avançar / Retroceder nos podCast

### ISSUE THREAD

**Issue by RogerioLacerdaPeres** [caelum/alura-funcionalidades#705]
Gostaria que tivesse uma tecla e/ou botão para retroceder ou avançar só um pouquinho ao ouvir um podcast.

**Comment by RogerioLacerdaPeres** [comment]
Percebi que existe, com as setas para direita e esquerda, mas primeiro tem que clicar com o mouse na bolinha de progressBar e só depois teclar. Já foi um alívio, mas se puder funcionar as teclas sem ter que clicar com o mouse antes seria melhor.

**Comment by designernatan** [comment]
@RogerioLacerdaPeres valeu pela sugestao!

Era uma otima mesmo! Algo até próximo do que temos na tela de aula em si né? Vamos dar uma olhada no futuro se é tranquilo reaproveitar para os podcasts 

Enquanto isso, sei que não é o ideal, mas você pode usar uma plataforma específica de podcasts como o [Google Podcasts](https://podcasts.google.com/feed/aHR0cHM6Ly9oaXBzdGVycy50ZWNoL2ZlZWQvcG9kY2FzdC8/episode/aHR0cHM6Ly93d3cuaGlwc3RlcnMudGVjaC8_cD0xNzg1?hl=pt-BR&ved=2ahUKEwizq5L4xfP5AhX7qpUCHeuPAbMQjrkEegQIAhAF&ep=6)

Abcs!

--

edit:
fechando a issue, mas ela continua aberta para comentários futuros!

**Comment by RogerioLacerdaPeres** [comment]
Obrigado, eu percebi que tinha no google podcast e foi exatamente isso que
eu fiz. Valeu

Em qui., 1 de set. de 2022 às 09:03, Natan Souza ***@***.***>
escreveu:
