### ISSUE TITLE
Erro de login

### ISSUE THREAD

**Issue by alvaroBar** [caelum/alura-funcionalidades#706]
Olá!

Gostaria de sugerir uma alteração na tela de login. Acontece que, quando vamos logar com e-mail, e por algum motivo logamos no gmail apenas com um e-mail, que não é o utilizado na alura, não retorna para o usuário a possiblidade de logar com um novo email, apensa dizendo que está incorreto e entrega ao usuário a possibilidade de entrar em contato.

Não acontece a mesma coisa se você estiver logado com mais de um e-mail. Nesse caso o direcionamento ocorre normalmente, do mesmo modo se o usuário não tiver logado nenhuma conta ainda.

Tentei trazer aqui o print da tela, mas não tenho certeza se vai aparecer corretamente.

![alura](https://user-images.githubusercontent.com/95434595/185153548-1e05448b-c63a-4696-b408-8b430ab5658e.jpg)

**Comment by laiscavalcanti** [comment]
Oi, Alvaro, tudo bem?

Interessante essa questão que você trouxe. Irei testar assim como você fez e levar para melhorarmos essa mensagem de erro de login.

Obrigada!

**Comment by designernatan** [comment]
oi pessoal, vou fechar a issue, mas podem voltar a comentar se quiserem :)
