### ISSUE TITLE
Bug no menu mobile

### ISSUE THREAD

**Issue by ThomasMoraes02** [caelum/alura-funcionalidades#707]
No menu mobile na aba de notificações está sobreposição de itens. 
Note no print que eu cliquei em Notificações e ele abriu mas manteve os links principais sobrepostos aos links de notificação.

![Screenshot_2022-08-17-22-39-44-204_com android chrome](https://user-images.githubusercontent.com/63357718/185273867-e8e0050d-aedb-402d-8f0f-f2dc35b6ae55.jpg)

**Comment by designernatan** [comment]
opa thomas, obrigado por reportar, vamos dar uma olhada num futuro próximo

abcs!
