### ISSUE TITLE
Adicionar botão para salvar artigos e vídeos nos planos de estudos

### ISSUE THREAD

**Issue by fabianodellano** [caelum/alura-funcionalidades#708]
Boa noite pessoal,

Seria interessante adicionar ou habilitar alguma funcionalidade como um botão que permitisse adicionar ou salvar direto os artigos e vídeos nos planos de estudos.
Já me deparei com diversos materiais interessantes que eu gostaria de categorizar nos planos de estudos, mas sou obrigado a ficar favoritando no navegador, pois revirei as páginas de artigos e vídeos e o único botão disponível e intuitivo é o dos 3 pontinhos no canto superior direito, mas ele é apenas para relatar problemas com o material ou mostrar as teclas de atalho no teclado. Nem tecla de atalho para salvar tem.
Obrigado pela atenção, fico na torcida para adicionarem esta funcionalidade.
![Captura de Tela 2022-08-17 às 23 09 47](https://user-images.githubusercontent.com/111474935/185277912-cb44896a-099e-476f-bb2d-5024e0c86c1d.png)

**Comment by laiscavalcanti** [comment]
Oi, Fabiano, tudo bem?

Legal esse ponto de trazer uma facilidade maior em adicionar conteúdos aos planos de estudo. Vamos estudar a viabilidade :}

Obrigada

**Comment by fernandaherculano** [comment]
Olá!! Também estou sentindo muita falta disso. Gostaria de reforçar a sugestão do colega. Abs!

**Comment by designernatan** [comment]
@fernandaherculano sei que não é o ideal, mas por hora o caminho hoje pra resolver isso é pegar o link desse conteúdo (alura+, artigo, etc) e adicionar manualmente lá no seu plano de estudos

como lais disse, no futuro quando pegarmor esse fluxo para melhorarmos vamos considerar e estudar a viabilidade :)

---


vou fechar a issue, mas podem voltar a comentar se quiserem :)
