### ISSUE TITLE
Possibilitar responder qualquer tópico do Forum.

### ISSUE THREAD

**Issue by 10diieggos** [caelum/alura-funcionalidades#709]
Olá, sempre que concluo uma atividade clico no convite de interagir no Forum do curso. Meu intuito é procurar alguma dúvida que eu consiga responder ou se alguém acrescentou algo interessante. Essa é uma excelente técnica para praticar e expandir a visão. Infelizmente, quase sempre, não é possível acrescentar respostas porque o tópico é considerado antigo.

> Meu pedido é: Permitam adicionar respostas a qualquer tópico.

Segue um exemplo da minha frustração:

A poucos minutos encerrei uma atividade e cliquei no botão 'DISCUTIR NO FÓRUM'

![image](https://user-images.githubusercontent.com/68875677/185758503-55e53307-2bc7-4280-a94c-661e9e5b6c43.png)

Dei de cara com o tópico da Daniele:

![image](https://user-images.githubusercontent.com/68875677/185758593-dd2eca4b-1bf4-448b-b617-bd9f446f191d.png)

O tópico já tem uma resposta correta, mas eu tenho uma diferente que gostaria de compartilhar. É uma oportunidade para praticar e mais um aprendizado para a Daniele e outros que se interessaram pelo problema dela.
Infelizmente, como mostrado na imagem abaixo, a opção para responder não está disponível.

![image](https://user-images.githubusercontent.com/68875677/185758925-3b01fc0b-6741-49cf-abac-635fb50aacc6.png)

Não quero abrir um novo tópico. Quero interagir com a Daniele e com quem tenha contribuído com ela.

É claro que pratiquei por ter resolvido o problema mesmo sem poder transformar em uma resposta. Porém é desmotivador, e ainda fico me perguntando quantas respostas vou perder caso eu venha a abrir um tópico ou quantas a Daniele já perdeu.

Se isso é importante para um tópico nível iniciante como o deste exemplo, a importância de mais respostas aumenta quando a complexidade vai aumentando.

Obrigado por utilizarem tão bem o recurso das issues e parabéns pelo bom trabalho.

**Comment by designernatan** [comment]
@10diieggos valeu pela sugestao!

a gente tranca o tópico nesse tempo pois puxamos alguns números e era +- o tempo ideal, entendo que há momentos que queremos trocar mais ideia com outras pessoas, por isso que puxamos o Discord exclusivo da Alura

pode ficar meio longe o tópico do fórum, mas é uma boa opção para discutir e interagir com colegas da área

e obrigado pelo elogio, vamos melhorando :)

abracao!

**Comment by designernatan** [comment]
vou fechar a issue, mas podem voltar a comentar se quiserem :)
