### ISSUE TITLE
Visualizar os meus cursos em andamento por progresso

### ISSUE THREAD

**Issue by maisonsouza** [caelum/alura-funcionalidades#71]
Ao acessar a url https://cursos.alura.com.br/courses/mine
Meus cursos sou apresentado a 3 categorias de cursos:

* Cursos salvos para mais tarde
* Cursos em andamento
* Cursos em pausa

Atualmente a visualização dos curso mostra por data mais eu gostaria de ter essa visualização por progresso porque sempre que entro nessa página não me interesso pelos últimos cursos e sim por aqueles que só faltam um pouco pra terminar então concluo logo.

![meuscursos](https://user-images.githubusercontent.com/11163368/74569417-bde37580-4f50-11ea-8fd9-c4d2f38d5c6b.png)

Por exemplo na imagem acima gostaria de ver o Curso de Fotografia que tem o maior progresso por primeiro e o de mysql em segundo e assim sucessivamente, acredito que seria mais atrativo ver os cursos dessa forma.

**Comment by designernatan** [comment]
oi @maisonsouza valeu pela sugestao

organizamos assim pois muitas pessoas na época se organizavam melhor indo pela ordem do último contato com os cursos

para mim um "order by" por progresso faz todo sentido de qualquer forma
anotei aqui para quando repensarmos essa tela, td bem?

abcs!

**Comment by maisonsouza** [comment]
Ok. Obrigado @designernatan
