### ISSUE TITLE
Melhoria do ranking

### ISSUE THREAD

**Issue by fredprada** [caelum/alura-funcionalidades#710]
Habilitar botões para ordenar os participantes, top 100, pois não conseguimos ver quem está no topo do ranking e suas pontuações.

Segmentar os participantes em "ligas" de acordo com suas pontuações, por exemplo, bronze, prata, ouro e assim por diante.
Quando o participante fica dentro dos 25% melhores da liga, ele sobre no ranking, e o mesmo acontece com quem ficou lá para baixo.

**Comment by designernatan** [comment]
@fredprada valeu pelas sugestoes! Gostei dessa organização por ligas, me lembra um jogo que eu jogava chamado overwatch

precisamos melhorar essa parte do ranking/gamefication, por hora sem previsão

caso isso mude no futuro, pingamos aqui!

**Comment by designernatan** [comment]
vou fechar a issue, mas podem voltar a comentar se quiserem :)
