### ISSUE TITLE
Nova Feature

### ISSUE THREAD

**Issue by tuliipa** [caelum/alura-funcionalidades#711]
Gostaria que tivesse um programa de estágio na plataforma.
Existe uma demanda muito grande para tal na comunidade, eu mesmo quero largar a minha escola para entrar na comunidade alura, e quero encaminhamento depois de fazer meus cursos e me formar.

**Comment by designernatan** [comment]
@tuliipa valeu pela sugestao!

essa parece realmente mais um programa como vc disse do que uma única feature

estagio é bem bacana e importante, mas recomendo não sair da escola, seja colegio ou faculdade), ideal (na minha opiniao) é terminar os estudos e aí sim pensar e refletir sobre esses pontos :)

em algumas semanas vamos ter uma novidade na alura que envolve criação de portfolio: a vitrine.dev! Paulo deu uns spoilers aqui nesse vídeo nesse minuto específico: https://youtu.be/8dFeeSCGExg?t=2372

a gente tá sempre de olho em integrar e aproximar mais a comunidade alura com essa parte de empregabilidade

abracao e bons estudos!

**Comment by designernatan** [comment]
vou fechar a issue, mas podem voltar a comentar se quiserem :)
