### ISSUE TITLE
Melhoria Certificado Completo

### ISSUE THREAD

**Issue by DaunSimone** [caelum/alura-funcionalidades#712]
Seria interessante no certificado completo incluir também o agrupamento por **Plano de Estudo** como já acontece com as formações.
Facilitaria o acompanhamento, principalmente para os plano de estudo criados pela empresa empregadora.

**Comment by designernatan** [comment]
@DaunSimone opa valeu pela sugestao!

o plano de estudos a gente optou por nao ter certificado nem constar no certificado completo pois não passa pela nossa curadoria direta

entendi que você acompanha o engajamento do seu time na alura, é isso? Hoje qual a principal dificuldade que o time traz com relação aos certificados?

abcs e bons estudos!

**Comment by DaunSimone** [comment]
@designernatan 

Seria apenas para questão de apurar nossas metas, por exemplo, ter feito 10h do plano de estudos "X". Se tivesse essa consulta consolidada seria mais simples de acompanhar.

**Comment by designernatan** [comment]
daunsimone

pensando nisso que a gente tem um relatório específico para planos de estudos no alura corp

você pode pingar direto no corporativo@alura.com.br que o time especialista pode te ajudar com mais eficiência, td bem? Pode inclusive mandar o link desta issue para ajudar com a contextualização que você me trouxe aqui :)

abcs e bons estudos!

edit:
opa esqueci de comentar: o time vai poder te mostrar como funciona esse relatório, o que ele inclui, o que não inclui, casos que fazem sentido etc

**Comment by designernatan** [comment]
vou fechar a issue, mas podem voltar a comentar se quiserem :)
