### ISSUE TITLE
Melhoria no menu de formações

### ISSUE THREAD

**Issue by viniciusmoreira** [caelum/alura-funcionalidades#713]
No site da Alura é exibida a opção de formações e o conteúdo é bem massa, porém quando se é assinante ao clicar em formações navegamos para a lista dos cursos apenas separados por tópicos, fica bem confuso.

Sugiro ajustar pra que ao clicar em formações mostre apenas os temas e a pessoa já acesse direto a tela que hoje, tem que acessar clicando em "VER ESCOLA".

O link atual poderia ser um "CURSOS".

**Comment by designernatan** [comment]
@viniciusmoreira me desculpa, nao entendi bem aqui

> No site da Alura é exibida a opção de formações e o conteúdo é bem massa

Vc diz [tipo esta pagina da formação java](https://www.alura.com.br/formacao-java)?

---

> porém quando se é assinante ao clicar em formações navegamos para a lista dos cursos apenas separados por tópicos

1. Você clicou onde exatamente? Ali em cima no menu principal do site ou no breadcrumb?
2. [Esta lista?](https://www.alura.com.br/formacoes)

---

> Sugiro ajustar pra que ao clicar em formações mostre apenas os temas e a pessoa já acesse direto a tela que hoje, tem que acessar clicando em "VER ESCOLA".

Por ex, você está na [formação Java OO,](https://www.alura.com.br/formacao-java) clicou ali no breadcrumb, foi para [esta página já com o link âncora](https://www.alura.com.br/formacoes#programacao)?

**Comment by designernatan** [comment]
@viniciusmoreira desculpa, nao entendi bem

quando vc clicou em 'formacoes' a partir de uma pagina de [formacao java por ex,](https://www.alura.com.br/formacao-java) voce clicou no menu principal do site ou no breadcrumb?
![image](https://user-images.githubusercontent.com/5431347/187907326-f1023c45-d595-4556-974a-53b992fa92e4.png)

uma URL /formacoes ja com o link ancora da escola correspondente acha que resolveria, [algo assim?](https://www.alura.com.br/formacoes#programacao)

**Comment by viniciusmoreira** [comment]
@designernatan consegui entender melhor o funcionamento lá.

Tem as separações das áreas e dentro as formações.

Podemos fechar esta issue.

Obrigado
