### ISSUE TITLE
Definir tamanho máximo do player

### ISSUE THREAD

**Issue by daniloribeiro00** [caelum/alura-funcionalidades#714]
Seria legal definir um tamanho máximo do player, pois ele se espande demais em telas ultrawide e é necessário reduzir o zoom ou ajustar o scroll meticulosamente para deixá-lo inteiramente visível.

Prints abaixo:
![image](https://user-images.githubusercontent.com/68981163/188233925-8ff5be70-5c0f-4b1f-a911-b665621b3e77.png)

![image](https://user-images.githubusercontent.com/68981163/188233963-6b787dba-29a6-430f-99ae-b2c46026cad7.png)

É possível perceber que, na primeira image, a barra do player não aparece pois está mais abaixo.

Já na segunda imagem, a barra de menus do macOS no vídeo também fica oculta pois está muito acima.

Creio que um pouquinho de CSS já resolve o problema 😁

**Comment by masromao** [comment]
Olá @daniloribeiro00, tudo bem?
Obrigado pela sugestão! Muito legal esse ponto que você levantou sobre o tamanho do player. Vamos estudar a viabilidade de aplicar em futuras atualizações, mas por hora não consigo te passar um prazo para execução, ok?
:)

abcs e bons estudos!

**Comment by masromao** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
