### ISSUE TITLE
Respostas no HTML!

### ISSUE THREAD

**Issue by AlexseySilva** [caelum/alura-funcionalidades#715]
### Gostaria de propor a correção do HTML da Alura, pois ainda podemos usar o INSPECT para obter as respostas do site!
#
![entrada](https://user-images.githubusercontent.com/83961167/188315327-1941848b-9c08-4fe6-a16e-292e70122ee7.png)
![tela2](https://user-images.githubusercontent.com/83961167/188315329-1a0a50ef-01f6-42fb-8445-57e5f1404d1e.png)
![tela3](https://user-images.githubusercontent.com/83961167/188315330-61369e56-0d57-4d8b-b938-e5299f723853.png)
![tela4](https://user-images.githubusercontent.com/83961167/188315331-baf72e11-a095-4885-a1a7-86ef874afa21.png)
**Segue o primeiro passo para entrar no modo desenvolvedor!**
![tela5](https://user-images.githubusercontent.com/83961167/188315412-6f375046-c46a-4d04-a355-ae430f6ae336.png)
Agora procure pela classe de provas task-menu-nav-item-svg
![tela6](https://user-images.githubusercontent.com/83961167/188315477-b24f1147-f9c4-4265-9f35-a520696e40f9.png)
Aqui nesse print podemos ver que as respostas estão relacionadas em  Boolean onde é só localizar a resposta com a data-correct="true" e responder!
![tela7](https://user-images.githubusercontent.com/83961167/188315557-00adf869-fd13-4bd7-a468-803e4c61e2d7.png)

**Comment by synnkfps** [comment]
up

**Comment by designernatan** [comment]
Oi Alexsey,

Poxa mas aí você entrega o jogo! Não são muitos alunos que fazem isso, mas com certeza é uma falha nos exercícios.

De qualquer maneira evitaria usá-la, justamente para sentir o progresso no aprendizado.

Espero ter ajudado e bons estudos,

Abcs!

**Comment by AlexseySilva** [comment]
> Oi Alexsey,
> 
> Poxa mas aí você entrega o jogo! Não são muitos alunos que fazem isso, mas com certeza é uma falha nos exercícios.
> 
> De qualquer maneira evitaria usá-la, justamente para sentir o progresso no aprendizado.
> 
> Espero ter ajudado e bons estudos,
> 
> Abcs!

Olá Natan
Tudo bem?
Sabendo que isso é possível, não seria melhor uma atualização no site?

**Comment by designernatan** [comment]
Oi Alexsey, tudo certo e contigo?

Com certeza! Em contrapartida tenho certeza que vocês evitam usar esse tipo de recurso pois acabaria sendo uma auto-sabotagem, ainda mais que hoje não exibimos ou salvamos a % de acertos nos exercícios, faz sentido?

Ao mesmo tempo estamos focando em algumas coisas com um impacto bem maior e direto nos estudos de vocês como a [Vitrine.Dev.](https://cursos.alura.com.br/vitrinedev)

Abração!

**Comment by AlexseySilva** [comment]
Bom dia/tarde/noite, Tudo ótimo, E você como está?

Infelizmente a parte da auto-sabotagem só entendi agora!


Você poderia me indicar algo sobre essa área de segurança?

**Comment by designernatan** [comment]
tranquilo!

olha, nao sou dev, mas sei que tem uma formação de segurança aqui:
https://cursos.alura.com.br/escolas/devops

e sei que o akita comenta bastante sobre temas em geral, deve ter algo sobre segurança tb:
https://www.youtube.com/c/FabioAkita1990/playlists

**Comment by designernatan** [comment]
vou fechar a issue, mas podem voltar a comentar no futuro se quiserem :)
