### ISSUE TITLE
Escolha a qualidade do video

### ISSUE THREAD

**Issue by SetimoCristian** [caelum/alura-funcionalidades#716]
Colocar a escolha de qualidade de video nos cursos, assim como no youtube e Udemy, ter qualidade de video automática, mas também a opção de escolher a  qualidade de video em avançado. 

A qualidade do video é boa para Celular mas, as na grande parte do tempo os vídeos estão todos em 720p, ficando difícil a visualização em Desktop.

**Comment by masromao** [comment]
Oi @SetimoCristian , tudo bem? 

Hoje nossos vídeos não possuem mais opções de resolução porque a maior parte dos instrutores grava em computadores acessíveis a alunos e alunas, que possuem uma resolução de 1368*768.  Também priorizamos a transmissão de dados com vídeos leves que não exigem uma internet muito rápida nem vão ocupar muito espaço no celular de quem faz download no aplicativo. Por isso por enquanto não oferecemos o que você sugeriu.

Mas de qualquer forma, muito obrigado pela sugestão! Legal esse ponto que você levantou sobre a qualidade dos vídeos. Vamos estudar a viabilidade de aplicar em futuras atualizações, mas por hora não consigo te passar um prazo para execução, ok?
:)

abcs e bons estudos!

**Comment by masromao** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
