### ISSUE TITLE
Acesso facilitado aos Certificados por via Mobile

### ISSUE THREAD

**Issue by SetimoCristian** [caelum/alura-funcionalidades#717]
Percebi que não existe acesso facilitado aos certificados por via mobile, seria interessante adicionarem essa função de forma mais facilitada.

**Comment by masromao** [comment]
Olá @SetimoCristian, tudo bem?
Obrigado pela sugestão! Legal esse ponto que você levantou sobre os certificados no mobile. Vamos estudar a viabilidade de aplicar em futuras atualizações, mas por hora não consigo te passar um prazo para execução, ok?
:)

abcs e bons estudos!

**Comment by masromao** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
