### ISSUE TITLE
Botão para download dos certificados

### ISSUE THREAD

**Issue by AlexseySilva** [caelum/alura-funcionalidades#718]
Botão para download dos certificados (Podendo ser um botão para cada certificado ) + ( Um botão para fazer o download de todos já concluídos )
 
Em baixo está a imagem do certificado

[Alexsey Batista Da Silva - Curso - Alura.pdf](https://github.com/caelum/alura-funcionalidades/files/9542153/Alexsey.Batista.Da.Silva.-.Curso.-.Alura.pdf)

**Comment by masromao** [comment]
Oi, Alexey, tudo bem?
Obrigado pela sugestão! Legal esse ponto que você levantou sobre o download dos certificados. Vamos estudar a viabilidade de aplicar em futuras atualizações, mas por hora não consigo te passar um prazo para execução, ok?
:)

abcs e bons estudos!

**Comment by masromao** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
