### ISSUE TITLE
Ajustar o tamanho da fonte da transcrição.

### ISSUE THREAD

**Issue by herminio-gurgel** [caelum/alura-funcionalidades#719]
Acredito que todos os vídeos da alura têm transcrição completa abaixo do vídeo.
Porém a fonte está em tamanho fixo, pra quem prefere, use uma tela pequena ou precise por questões de acessibilidade, é preciso ficar aumentando o zoom da página no navegador para que fique mais legível. Esse zoom via navegador não é o ideal e particularmente causa um bug no menu lateral que não vem ao caso.

A minha ideia é simples, adicionar um menu que permita ajustar o tamanho dessa fonte, pelas questões que mencionei:

- Pessoas que prefiram ler a transcrição.
- Telas muito pequenas.
- Acessibilidade.

**Comment by masromao** [comment]
Olá @HerminioGurgel, tudo bem?
Uma sugestão que indicamos para esse caso é dar o zoom no navegador + ativar o modo teatro no player do vídeo dessa forma o container com o vídeo aumenta a largura e ocupa um espaço maior ajudando no layout da página como um todo, como no exemplo:

![image](https://user-images.githubusercontent.com/86667938/190184373-247046f0-8130-4e49-9bcf-6343690450ec.png)

Mas de qualquer forma, obrigado pela sugestão! Legal esse ponto que você levantou sobre acessibilidade. Vamos estudar a viabilidade de aplicar em futuras atualizações, mas por hora não consigo te passar um prazo para execução, ok?
:)

abcs e bons estudos!

**Comment by masromao** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
