### ISSUE TITLE
Tela de Cursos na Área logada

### ISSUE THREAD

**Issue by pablo-vicente** [caelum/alura-funcionalidades#72]
Hoje quando está na área logada, caso quera visualizar os cursos tem que acessar está pagina: https://cursos.alura.com.br/category/programacao (que por sinal não é fácil). Está tela não filtro é uma lista corrida com todos os cursos disponíveis. 
Quando não se está logado no sistema tem-se está tela : https://www.alura.com.br/cursos-online-programacao, que ao meu ver é muito mais interessante, pois é possível filtrar os cursos e exibe o nível do curso. 

Minha sugestão seria ter a página de acesso não logado mais a barra de progresso do curso. 
Outra sugestão seria ter um botão de acesso direto a todos o curso na área logada, pois para acessado é necessário entrar em uma formação depois clicar no botão "é um formação de", então é listado todos os curos daquela categoria.

**Comment by designernatan** [comment]
oi @pablo-vicente otimas sugestoes, anotei tudo aqui termos atenção quando formos reestruturar esse fluxo de achar os cursos

valeu mesmo!
