### ISSUE TITLE
Fazer resumo em vídeo do que foi feito por seção

### ISSUE THREAD

**Issue by jpfigueredo** [caelum/alura-funcionalidades#720]
Acredito que a adição de um vídeo ao final de cada seção, mostrando o que foi implementado, junto ao "O que aprendemos?", pode ser uma boa para pessoas que fazem multitask ou tem um intervalo grande entre os vídeos.

**Comment by artnicodemus** [comment]
Olá, @w4sabi , tudo bem?

Muito interessante a sua ideia, ajudaria a fixar mais o conteúdo aula. Levei sua sugestão para o time de conteúdo para estudar a viabilidade dela, mas por hora não consigo te passar um prazo para execução, ok? Muito obrigado pela sugestão!

Abraços e bons estudos!

**Comment by giovana-armidoro** [comment]
vou fechar a issue, mas podem voltar a comentar se quiserem :)
