### ISSUE TITLE
Opção de like ou outras emoções nas aulas

### ISSUE THREAD

**Issue by f-mtz** [caelum/alura-funcionalidades#721]
Opção de like ou outras emoções nas aulas

**Comment by artnicodemus** [comment]
Oi, @f-mtz , tudo bem? Obrigado pela sugestão!

Fiquei curioso e gostaria de entender melhor a sua ideia, como você imaginou a utilização desse like/reação na aula?

**Comment by giovana-armidoro** [comment]
vou fechar a issue, mas podem voltar a comentar se quiserem :)
