### ISSUE TITLE
Miniatura de Vídeo ao passar o mouse

### ISSUE THREAD

**Issue by f-mtz** [caelum/alura-funcionalidades#722]
Assim como ocorre no Youtube, Netflix... ver a miniatura do vídeo na barra de progresso é interessante, pois trás produtividade pra ver em que momento do vídeo um slide foi mostrado, ou ver o momento em que o instrutor mexeu em alguma ferramenta... as vezes estamos procurando um momento específico do vídeo e rever o vídeo é cansativo, e ficar clicando em vários momento até achar também é bem improdutivo e cansativo, isso traria conforto e produtividade aos usuários

**Comment by artnicodemus** [comment]
Opa, @f-mtz , tudo certo?

Muito obrigado pela sugestão, nós achamos a ideia bem bacana, a miniatura de vídeo é algo que temos anotado para o dia que mexermos na tela de aula! Porém, ainda está fora dos planos de curto prazo mexer na tela de aula como mencionado [aqui nesta outra issue](https://github.com/caelum/alura-funcionalidades/issues/600) 

Abraços e bons estudos!

**Comment by giovana-armidoro** [comment]
vou fechar a issue, mas podem voltar a comentar se quiserem :)
