### ISSUE TITLE
Adicionar nota em vídeo

### ISSUE THREAD

**Issue by f-mtz** [caelum/alura-funcionalidades#723]
Marcação minutos de vídeos, a Udemy tem esse recurso, podemos adicionar uma marcação no vídeo com uma nota, assim além de poder marcar momentos importantes e de destaque em vídeos, podemos adicionar alguma observação ou comentário vinculado a aquele exato momento, isso é excelente para revisão de conteúdo e pra relembrar detalhes, dicas... , e cada usuário vê as suas notas é claro, eu não vejo notas de outros usuários e vice e versa

**Comment by artnicodemus** [comment]
Oi, @f-mtz, muito obrigado pela sugestão!

No passado nós tínhamos planos para isso, porém acabamos cancelando. Em 2018/19 foi lançado um MVP relativo à essa função de notas mas não bateu nossas expectativas, assim como mencionado [aqui nesta outra issue](https://github.com/caelum/alura-funcionalidades/issues/678)

Abraços e bons estudos!

**Comment by giovana-armidoro** [comment]
vou fechar a issue, mas podem voltar a comentar se quiserem :)
