### ISSUE TITLE
Aviso de mudança em uma aula 

### ISSUE THREAD

**Issue by Matheus404NF** [caelum/alura-funcionalidades#724]
As mudancas que acontecem nas aulas, parece que não há nenhuma notificação ou aviso em algum lugar. Por exemplo, algumas aulas aparentemente mudaram de um formato de exercício prático (um problema a ser resolvido, com a resposta do instrutor depois) para o formato de múltipla escolha, e embora isso não seja ruim, atrapalha um pouco essas mudanças ao fazer revisão de aulas. Inclusive algumas destas aulas estão marcadas paraq mim como não feitas, o que tambem chamou atenção, e me parece que até o forum dessas aulas foram resetadas, embora eu não tenha certeza. 

Uma sugestão é que as aulas com mudanças tenham alguma sinalização de mudança com a data da última atualização, considerando que às vezes há tambem novas atividades no meio das que já existiam, alterando o número da aula.

**Comment by joaovitormarcilio** [comment]
Olá, @Matheus404NF, tudo certo? 

Muito interessante esse ponto que você levantou. Hoje em nossa plataforma existem dois lugares que você pode saber sobre essas atualizações. A primeira é no sininho que fica na parte superior direita da plataforma.

![image](https://user-images.githubusercontent.com/79534177/192044684-68aafadd-1b9b-4b71-bd9e-e17f47ca61b2.png)

(Usei o curso de Facebook Ads como exemplo, ok?)

E o outro lugar é direto na página do curso, tem um card que tem as infos do curso e inclusive de quando que ele foi atualizado.

![image](https://user-images.githubusercontent.com/79534177/192044877-8ccd5568-2b02-46a4-b21d-24cc6b41488c.png)


Vou levar as suas considerações nas próximas reuniões do time e se tivermos alguma novidade eu te aviso por aqui, pode ser?

[]'s

**Comment by Matheus404NF** [comment]
Certo, seria interessante algum aviso na propria aula ou atividade, mas de qualquer forma desde já agradeço o retorno e as imagens que ja indicam alguma mudança num curso, pois nao sabia delas

**Comment by andradeisadora** [comment]
pessoal vou fechar a issue, mas podem voltar a comentar se quiserem :)
