### ISSUE TITLE
Assistir as video-aulas com a tela do celular bloqueada. 

### ISSUE THREAD

**Issue by RogeoProjects** [caelum/alura-funcionalidades#725]
Olá pessoal boa tarde, a funcionalidade que eu gostaria de sugerir e poder assistir as videoaulas do app com a tela do celular bloqueada, isso possibilitaria de as pessoas escutarem a aula e ainda poderem realizar outras atividades, geralmente quando eu quero fazer isso eu preciso deixar a tela do celular aberta e colocar o celular no bolso, e a todo momento acontece alguma coisa, devido a tela ser touchscreen.

Eu escuto as aulas durante o dia, quando estou na rua, e quando chego em casa, reviso e faço os exercícios. 

Acredito que isso ajudaria muitas pessoas não só a mim, espero que gostem.

Obrigado.

**Comment by felipetorres** [comment]
Oi @RogeoProjects, isso já é possível no app. 
Vai ali no menu "configurações" e habilita "tocar videos em segundo plano".

Abraço!
