### ISSUE TITLE
Download de conteúdo 

### ISSUE THREAD

**Issue by Pedrohesomon0** [caelum/alura-funcionalidades#726]
Poderia haver a possibilidade de realizar o download das aulas alura no computador/notebook, assim como ocorre na plataforma mobile

**Comment by giovana-armidoro** [comment]
oii, obrigada pela sugestão! 

vemos muito valor no download dos vídeos no app pq é algo que ajuda muito alunos que precisam estudar fora de casa/sem internet, as vezes até dentro do ônibus ou metrô, e nesses momento normalmente estão com o celular.
no desktop, me parece algo mais atípico de acontecer, mas queria saber um pouco mais sobre sua motivação e como essa funcionalidade poderia te ajudar hoje, poderia me dar mais alguns detalhes?

abraços e bons estudos! :)

**Comment by Pedrohesomon0** [comment]
Olá.
Passo muito tempo fora de casa e com o notebook em mãos, principalmente na
faculdade, onde o wifi quase não pega e quando pega é bem lento, vi no
fórum que mais pessoas se beneficiariam com essa funcionalidade também,
Obrigado pela atenção

Em sex., 30 de set. de 2022 12:04, Giovana ***@***.***>
escreveu:

**Comment by giovana-armidoro** [comment]
entendi, muitos obrigada por trazer mais detalhes
infelizmente no momento não temos planos para implementar essa funcionalidade no desktop, mas qualquer coisa te atualizo por aqui

obrigada por trazer sugestões,
abraços :)

**Comment by andradeisadora** [comment]
pessoal vou fechar a issue mas podem voltar a comentar se quiserem :)
