### ISSUE TITLE
Marcar aula como Não Assistida/Assistir Novamente

### ISSUE THREAD

**Issue by wesleyaip** [caelum/alura-funcionalidades#727]
Senti falta de um recurso para marcar a aula como **Não Assistida** ou **Assistir Novamente**.
Para compreender melhor alguns assuntos, optei por rever algumas aulas, mas as vezes me perdia em qual deveria rever ou não. Acredito que essa opção agregará valor para situações desse tipo.

**Comment by giovana-armidoro** [comment]
oi wesley, valeu pela sugestão!

queremos melhorar a tela de aula no futuro, e com certeza esse vai ser um dos pontos que vamos puxar pras discussões.

por enquanto, tem algumas possibilidades que podem te ajudar: salvar as URLs com o [GetPocket](https://getpocket.com/my-list), organizar esses conteúdos em uma tabela no [Notion](https://notion.com) ou mesmo criar uma pasta de "Aulas para rever" e ir favoritando essas aulas no navegador

por hora, espero ter ajudado! 
abraços e bons estudos :)

**Comment by wesleyaip** [comment]
Olá @giovana-armidoro!
Maravilha!
Obrigado.

**Comment by andradeisadora** [comment]
pessoal vou fechar a issue mas podem voltar a comentar se quiserem :)
