### ISSUE TITLE
Horário de Estudos no Dashboard

### ISSUE THREAD

**Issue by luizavitiello** [caelum/alura-funcionalidades#728]
Acho interessante ter uma opção do aluno organizar melhor o seu horário de estudos , tendo a opção de deixar disponível no seu dashboard

**Comment by giovana-armidoro** [comment]
oi luiza, muito obrigada pela sugestão!

realmente, gerenciar os horários é muito importante pra conseguir ter uma boa organização e desempenho nos estudos, mas não entendi muito bem como isso seria feito dentro da dashboard... poderia me falar um pouco mais sobre o que você pensou e como isso poderia te ajudar hoje?

enquanto isso, deixo a indicação de alguns materiais que podem te ajudar:

- [Alura+ "Ritmo de Estudos - Você sabe como organizar sua rotina de estudos?"](https://cursos.alura.com.br/extra/alura-mais/ritmo-de-estudos-c18)
- [Artigo Alura "O dia a dia de um profissional que aprende: o calendário de estudo"](https://www.alura.com.br/artigos/o-dia-a-dia-de-um-profissional-que-aprende-o-calendario-de-estudo)
- [Vídeo Alura "Como posso estudar melhor?"](https://www.youtube.com/watch?v=Is6c9KSGCbk)
- [Artigo Guia do Estudante "7 aplicativos para organizar seus estudos"](https://guiadoestudante.abril.com.br/estudo/7-aplicativos-para-organizar-seus-estudos/)

abraços e bons estudos!

**Comment by luizavitiello** [comment]
Olá Giovana , por exemplo , organizar os dias da semana (segunda. terça , quarta, quinta e sexta + horários) . Eu sou uma pessoa que tem muita dificuldade em organização de horários de estudos e acabo me enrolando nos estudos, a maioria dos app que são realmente bons , acabam sendo pagos. Além de que , assim como eu , acredito que tem mais pessoas que estão fazendo mais de uma formação ao mesmo tempo, então acredito que seria legal ter algo assim no site da alura para se organizar.

**Comment by giovana-armidoro** [comment]
oi luiza, obrigada por trazer mais detalhes da sugestão
a ideia é muito legal mas infelizmente não temos como priorizar o desenvolvimento de algo assim na plataforma nesse momento

talvez uma ferramenta que pode te ajudar é o [Notion](https://www.notion.so/product), você conhece? ela tem várias possibilidades pra você conseguir se organizar da forma que achar melhor, é bem flexível 
além disso, existem vários templates disponíveis pra você usar e se inspirar, tem alguns disponíveis [aqui](https://www.notion.so/templates/categories/education) e pesquisando um pouco mais você encontra várias outras possibilidades (gratuitas e pagas)
[aqui](https://www.youtube.com/watch?v=py1B5NM3avk) tem um tutorial bem legal que disponibiliza um template em português

espero ter contribuído :)
bons estudos!

**Comment by andradeisadora** [comment]
pessoal vou fechar a issue mas podem voltar a comentar se quiserem :)
