### ISSUE TITLE
novo plano

### ISSUE THREAD

**Issue by rafa95amar** [caelum/alura-funcionalidades#729]
Gostaria que a Alura tivesse um plano mais caro, onde existissem tutores para tirar nossas dúvidas em tempo real. e muito chato você depender de colegas no grupo do discord ou ter que fazer perguntas no forum que levara horas ou dias para serem sanadas. isso acaba me deixando triste e sem vontade de continuar na plataforma.

**Comment by giovana-armidoro** [comment]
oi rafa, muito obrigada pela sugestão!

entendo sua frustração na espera de respostas em momentos de dúvidas mas, como o Natan bem explicou nessa outra [issue](https://github.com/caelum/alura-funcionalidades/issues/610), infelizmente teríamos uma grande dificuldade para fazer isso funcionar para todo mundo e que a experiência fique de uma forma bacana

mas nós sabemos como esse acompanhamento mais de perto é importante e, para contribuir com isso, temos o Scuba Team que é um time dedicado a ajudar os alunos tirando suas dúvidas no fórum e no discord

nós também promovemos alguns eventos no discord como **grupos de estudos** e **monitorias**, nesses eventos os alunos podem tirar dúvidas em **tempo real**, conversando com os Scubas e também com outros alunos, essa pode ser uma boa opção para você

você pode acompanhar a agenda dos nossos eventos pelos discord, clicando em "Eventos" no canto superior esquerdo
![image](https://user-images.githubusercontent.com/92942899/194402814-0f4a7f77-c295-4e49-98f4-1ef10c1c5b31.png)

espero ter contribuído
abraços e bons estudos!

**Comment by andradeisadora** [comment]
pessoal vou fechar a issue mas podem voltar a comentar se quiserem :)
