### ISSUE TITLE
Perfil público de certificados e projetos

### ISSUE THREAD

**Issue by CarlosDiasPP** [caelum/alura-funcionalidades#73]
### **Perfil público de certificados e projetos**

Seria muito bom se houvesse alguma página que os alunos e alunas pudessem compartilhar, mostrando seus certificados e projetos. Como se fosse uma mistura de "portfólio" dos projetos desenvolvidos e histórico de cursos.
Há a possibilidade de colocar o certificado no LinkedIn, porém quando se atinge um grande número de cursos concluídos acaba ficando muito extenso a área de certificados. Seria muito mais vantajoso se o certificado do LinkedIn fosse atribuído a Carreira ou a Formação, ao invés de cursos individuais.

**Comment by designernatan** [comment]
Oi @CarlosDiasPP valeu pela sugestão!

Hoje não estamos com planos para curto e médio prazo para mexermos com o perfil, agora ter algo que some não só os certificados mas os projetos da galera seria algo **muito** bacana.

Alura acabaria virando um Behance+Github, gosto bastante!

---

Sobre ter muito certificado, você pode gerar um certificado completo, que consta todos os cursos. Só ir no seu perfil e descer a página inteira. O texto do link é "Você pode encontrar um certificado completo aqui".

Abcs!
