### ISSUE TITLE
Incluir informações de carga horária no Dashboard

### ISSUE THREAD

**Issue by jabisandrade** [caelum/alura-funcionalidades#730]
Quando criamos um novo plano de estudo com vários cursos a serem realizados, seria interessante que fosse exibido no dashbord o **somatório das cargas horarias dos respectivos cursos** assim como o **somatório com o progresso da carga horária  já realizada.**
Essa informação do total de carga horaria dos cursos e progresso realizada é importante para poder realizar a prestação de contas na empresa.  Pelo menos comigo que o tempo de treinamento é escasso e sempre interrompo e volto dois três meses depois, toda vez que preciso informar quanto tempo ainda falta para terminar os cursos tenho que sair somando a carga horaria individual de cada curso para obter o progresso.

**Comment by giovana-armidoro** [comment]
oie, muito obrigada pela sugestão!

saber a carga horária e o progresso de um plano de estudo faz muito sentido mesmo, parecido com o que temos nos cursos e formações né?
**por enquanto**, não estamos com melhorias futuras planejadas nessa parte da Alura, mas gosto bastante da ideia e assim que puxarmos algo nesse sentido vou levantar essa questão pra discussão também

abraços e bons estudos!

**Comment by andradeisadora** [comment]
pessoal vou fechar a issue mas podem voltar a comentar se quiserem :)
