### ISSUE TITLE
Plano Familia

### ISSUE THREAD

**Issue by darklain** [caelum/alura-funcionalidades#731]
Olá gostaria de sugerir uma funcionalidade, usuário família (Max 2 pessoas), pois assim imagina, que um casal use a mesma conta, mais o certificado da conclusão do curso fica sempre para o usuário principal, e com isso o segundo usuário termina o treinamento mais, não tem direito de pegar certificado. E com este implemento ambos pode ganhar os certificado. Pois a realidade é bem está casal sempre dividem conta =).

**Comment by giovana-armidoro** [comment]
oie, valeu pela sugestão!

já tivemos alguns pedidos semelhantes, mas como o sérgio comentou [aqui](https://github.com/caelum/alura-funcionalidades/issues/179) a plataforma não suporta mais de um usuário em uma mesma conta, por isso o certificado sai em nome de uma pessoa só

mas também vale o reply do sérgio sobre a possibilidade do desconto nessas situações, ok? você pode entrar em contato com nosso atendimento pedindo mais informações

abraços e bons estudos!

**Comment by andradeisadora** [comment]
pessoal vou fechar a issue mas podem voltar a comentar se quiserem :)
