### ISSUE TITLE
Podcasts

### ISSUE THREAD

**Issue by Azenst** [caelum/alura-funcionalidades#732]
Bom dia, queria sugerir uma funcionalidade que, ao meu ver seria de extrema ajuda aos fãs dos Podcasts Alura!

Esta funcionalidade se resume basicamente em poder salvar uma lista/marcar algum podcast específico para "assistir mais tarde" na plataforma Alura (Programa One), pois, ao acessarmos a mesma, só temos a lita dos podcasts em ordem crescente. Como são muitos episódios, creio que esta funcionalidade seria importante para podermos separar os assuntos de maior interesse.

Desde já agradeço a atenção!

![Screenshot_1](https://user-images.githubusercontent.com/107195513/195097034-657a3716-920b-4013-b472-c4350067d148.jpg)

**Comment by giovana-armidoro** [comment]
oie, valeu pela sugestão!

realmente, essa funcionalidade faz sentido e acredito que ajudaria bastante 
no momento não temos planos para mexer nessa parte da Alura, mas quando formos fazer algo nesse sentido vamos estudar essa possibilidade

por enquanto, você pode criar um **plano de estudos** chamado "Assistir mais tarde" e adicionar todos esses podcasts que vc tem interesse, acho que vai funcionar bem para o que você precisa
você pode até criar vários planos de estudos divididos por temas, como preferir

abraços e bons estudos!

**Comment by andradeisadora** [comment]
pessoal vou fechar a issue mas podem voltar a comentar se quiserem :)
