### ISSUE TITLE
Busca dentro do curso

### ISSUE THREAD

**Issue by pedrociarlini** [caelum/alura-funcionalidades#733]
Descreva a funcionalidade que você gostaria que tivesse na plataforma:

Buscar alguma aula do curso textualmente. Se já existe, não está funcionando.

Por exemplo, ao entrar no curso "Flutter: Controller, navegação e estados" e pesquisar por TextField, informa que não obteve resultados, quando o título da Aula 1, Vídeo 4 já possui o texto TextField.
Link do exemplo: https://cursos.alura.com.br/search/course/flutter-controller-navegacao-estados?query=TextField

<img width="373" alt="Alura pesquisa" src="https://user-images.githubusercontent.com/13017622/196355952-c5e5fd8e-bcbb-40f7-8c7b-2d392ce754d2.png">

**Comment by guilhermelombardi** [comment]
oi @pedrociarlini, tudo bem? realmente me parece que a busca está com algum bug, passei pro time responsável e já estamos investigando. Muito obrigado comentário e bons estudos! :)

**Comment by masromao** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
