### ISSUE TITLE
Localização do botão "voltar ao topo"

### ISSUE THREAD

**Issue by jhuan-magno** [caelum/alura-funcionalidades#734]
Em alguns exercícios e abas de explicação quando rolamos a tela pra baixo o botão "Voltar ao topo" aparece em cima do botão "próxima atividade". Gostaria de dar a sugestão de: Colocar o botão à esquerda da tela em vez de em cima do outro botão.
<img width="307" alt="Captura de Tela 2022-10-22 às 14 08 18" src="https://user-images.githubusercontent.com/29186717/197356242-9efefdc9-ef94-4226-b563-c3876750d725.png">

**Comment by guilhermelombardi** [comment]
oi @jhuanzito, tudo bem? muito obrigado pela sugestão!
Vou levar a ideia pro time pra gente analisar.
Abraços e bons estudos.

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
