### ISSUE TITLE
Linkar o tempo com o vídeo.

### ISSUE THREAD

**Issue by jpfigueredo** [caelum/alura-funcionalidades#735]
Quando estou assistindo a uma aula Gostaria que pudesse selecionar o tempo, na parte de transcrição da mesma, e o vídeo voltasse ao momento no qual cliquei.

Exemplo:

![image](https://user-images.githubusercontent.com/63759223/197830021-22b9384b-5f94-4f5a-a626-d11f1ca36e36.png)

Na imagem acima, caso os minutos estivessem hiperlinkados com o vídeo, facilitaria o usuário a voltar para determinado momento.

**Comment by guilhermelombardi** [comment]
Oi @w4sabi, muito obrigado pela sugestão.
Realmente é uma feature bem interessante, por hora não temos nada no radar nesse sentido, mas vou levar sua sugestão pra discutir com o time e entender a viabilidade técnica.

abraços e bons estudos. :)

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
