### ISSUE TITLE
Darkmode para o site pós junção Alura+Fiap. 

### ISSUE THREAD

**Issue by Inoxybel** [caelum/alura-funcionalidades#736]
Telas brancas são cansativas, e usando extensões no navegador que geram uma interface em darkmode (vide: Dark & Night Shift) a composição de cores não fica a ideal...

**Comment by andradeisadora** [comment]
oi @Inoxybel 
sabemos o quanto o dark mode é esperado na Alura por isso estamos com planos de levar pra plataforma mas infelizmente não tenho prazo pra te passar de quando isso vai acontecer :((
o pessoal ta dando umas dicas [nessa issue aqui](https://github.com/caelum/alura-funcionalidades/issues/156#issuecomment-632410492) do que fazer enquanto isso

abraço e bons estudos!

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
