### ISSUE TITLE
Clippings, destaques, marcações e anotações

### ISSUE THREAD

**Issue by MarinaLobao** [caelum/alura-funcionalidades#737]
Já que os videos possuem transcrições e existe também muito conteúdo escrito, creio que uma funcionalidade que seria muito legal seria uma área para clippings, como no kindle. 

Por mais que ao assistir as aulas eu faça anotações, as vezes eu me lembro que naquela mesma aula teve alguma outra coisa que eu acabei nao anotando e que seria util nesse momento. Daí um clipping que levasse diretamente pra página seria uma mão na roda, fora que manteria os alunos na plataforma.

No kindle eu acho meio bagunçado pq sao todas juntas no mesmo lugar e vc tem que basicamente ler tudo até achar a que vc queria, mas se houvesse uma forma de classificar as notas, adicionar observações, como um caderno de estudos mesmo (só que com links).

**Comment by andradeisadora** [comment]
oi @MarinaLobao 
obrigada pela sugestão!
não estamos com planos de fazer uma feature assim no momento mas você pode colocar suar anotações no notion, lá é possível categorizar, linkar e personalizar conforme sua necessidade. Além disso, vc pode usar a busca pra achar com mais facilidade as anotações que colocar em destaque 

abraço e bons estudos :)

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
