### ISSUE TITLE
Opção para salvar os favoritos

### ISSUE THREAD

**Issue by fabriciombr** [caelum/alura-funcionalidades#738]
Senti falta de uma opção para salvar algumas aulas, artigos, etc como favoritos, para que possamos consultar posteriormente.
Obrigado

**Comment by andradeisadora** [comment]
oi @fabriciombr 
obrigada pela sugestão!
hoje vc já pode salvar cursos como favoritos. 
Com os outros conteúdos vc pode criar um plano de estudos e salvar os favoritos dentro dele. Ou outra sugestão é usar o notion, lá vc pode salvar todos seus conteúdos favoritos e as suas anotações conforme for estudando

abraço e bons estudos :)

**Comment by fabriciombr** [comment]
Obrigado pela resposta. 
Na verdade seria uma opção para salvar uma aula específica de um curso... ou um artigo, etc.
A possibilidade de favoritar um curso e adicionar a um plano é boa mas as vezes gostaria de salvar partes de um curso específico que entendo ser mais interessantes que outras.

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
