### ISSUE TITLE
Erro  de escrita no site da alura

### ISSUE THREAD

**Issue by AlexseySilva** [caelum/alura-funcionalidades#739]
Sei que aqui não é o melhor lugar para isso mas, vou deixar registrado para o time arrumar o mais breve possivel.
No site da alura na hora de renovar a assinatura, está com erro de escrita no valor
 ( Até 12x R$ 0.02 (ou R$ 0.2 à vista))

![Alura_Arrumar](https://user-images.githubusercontent.com/83961167/199588534-f387d067-258b-46aa-ae82-ee0b3007f289.png)
![alura_arrumar2](https://user-images.githubusercontent.com/83961167/199588539-a55d3272-f035-46ec-a8a5-0f48d9634ad8.png)
![Alura_arrumar3](https://user-images.githubusercontent.com/83961167/199588540-e0bee96d-9c56-4e5e-a29d-dc17eb6be22c.png)

**Comment by AlexseySilva** [comment]
Esqueci de falar também que tem gente que se apega a esses erros para ganhar vantagens!

**Comment by designernatan** [comment]
@AlexseySilva valeu mesmo pelo report viu 🙏🏽

corrigimos!
