### ISSUE TITLE
Cursos recomendados

### ISSUE THREAD

**Issue by xFairon** [caelum/alura-funcionalidades#74]
Descreva a funcionalidade que você gostaria que tivesse na plataforma. Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

Em cursos recomendados aparece cursos que você já concluiu, filtrar eles para que não apareçam ou ter como marcar como concluído para não aparecer mais nos cursos recomendados.

**Comment by designernatan** [comment]
opa esse parece bug, valeu @xFairon!
