### ISSUE TITLE
Histórico e pontuação

### ISSUE THREAD

**Issue by MarinaLobao** [caelum/alura-funcionalidades#740]
No site existe uma página chamada "Últimas ações de [nome de usuário]" que contém as pontuações referentes aos cursos e exercícios concluídos, porém me parece uma página sem propósito já que ali seria um ótimo lugar para exibir literalmente as "últimas ações" que executei, como QUAIS cursos e exercícios eu concluí e juntamente os pontos.

Supondo que eu esteja acompanhando 2 cursos simultaneamente e passado o final de semana me lembrasse de alguma aula que tenha assistido, mas não soubesse exatamente dentro de qual curso se encontrava, essa página seria útil pra isso. 

Netflix, youtube... todos tem histórico de visualização, mesmo que não seja tão fácil o acesso.

Além disso, sou nova na alura, mas ainda não entendi muito o propósito da pontuação.
Compreendo a gamificação, mas me parece um projeto que não foi terminado. Existe um ranking, mas o que eu ganho com isso? 
Sinto que faltou detalhes como os que encontramos no duolingo pra que isso faça diferença e realmente envolva o usuário.

**Comment by andradeisadora** [comment]
oi @MarinaLobao :)
obrigada pelas sugestões! 
Pois é, faz sentido dar uma melhorada e fazer alguns ajustes no ranking sim. Obrigada por avisar!
Infelizmente no momento não temos planos pra mexer essa feature :(

Vou deixar anotado aqui vermos num futuro mas sem prazo pra isso acontecer, ta?
Abraço e bons estudos :)

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
