### ISSUE TITLE
Links para os cursos quebrados após login

### ISSUE THREAD

**Issue by geisonrodrigo** [caelum/alura-funcionalidades#741]
Sou funcionário do Banco do Brasil. Temos diversos cursos, muito bons por sinal, disponíveis na plataforma da Alura.
Cataloguei vários cursos sobre uma temática específica e os linkei em nosso site do SharePoint. Sempre que o usuário é remetido pela primeira vez para o site da UniBB/Alura, a autenticação é solicitada (como esperado). Porém, o usuário não é direcionado para o link que havia solicitado inicialmente. Ou seja, durante o processo de autenticação, o link para o respectivo curso é perdido.

**Comment by designernatan** [comment]
@geisonrodrigo valeu mesmo pelo report detalhado!

vamos dar uma investigada o que pode ser feito, qualquer novidade pingamos aqui

**Comment by masromao** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!

**Comment by isdrchagas** [comment]
Olá, @geisonrodrigo, tudo bem? será que você consegue me disponibilizar um link como exemplo, por gentileza?
