### ISSUE TITLE
A falta de opção para eliminar tópico do fórum é uma violação à LGPD

### ISSUE THREAD

**Issue by wusuario** [caelum/alura-funcionalidades#742]
O autor de um tópico no fórum da Alura não tem opção para eliminar o tópico que criou.

Na minha opinião, isso é uma violação à Lei Geral de Proteção de Dados Pessoais (LGPD). 

Afinal, a pessoa que escreve um tópico no fórum da Alura é titular de dados pessoais. E de acordo com o art. 18 da LGPD, o titular de dados tem direito a eliminação desses dados.

Por isso, sugiro a criação de um botão para possibilitar que o autor de um tópico no fórum possa eliminar referido tópico.

**Comment by designernatan** [comment]
@wagnerkaba valeu pela sugestao!

era uma boa termos algo assim, facilitaria o fluxo de exclusão que hoje está 100% em cima dos admins do fórum

sobre a lgpd, o titular dos dados pode solicitar a remoção deles a qualquer momento pelo privacidade@alura.com.br, isso está na nossa [Politica de Privacidade](https://www.alura.com.br/politica-de-privacidade) (você pode dar uma [olhada aqui no nosso faq sobre lgdp](https://suporte.alura.com.br/pt-BR/support/solutions/articles/72000565216-quero-remover-meus-dados-da-alura) tbm)

especificamente sobre o fórum, você sempre pode pingar no contato@alura.com.br ou direto no [form de contato](https://www.alura.com.br/contato). Só mandar o link do tópico específico que você quer deletar e sucesso

abcs!

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
