### ISSUE TITLE
Problema na paginação da página de Tópicos Resolvidos

### ISSUE THREAD

**Issue by Alm3ida** [caelum/alura-funcionalidades#743]
Olá, pessoal! Tudo bom? Espero que sim! 

No [Fórum da Alura](https://cursos.alura.com.br/forum/topico-bug-bug-na-paginacao-de-topicos-resolvidos-256574) foi identificado um problema nos botões de paginação na página **tópicos resolvidos**.

Ao acessar os tópicos resolvidos disponibilizados na URL
- https://cursos.alura.com.br/user/<user_name>

O usuário é levado até a página:
- https://cursos.alura.com.br/forum/usuario/<user_name>/resolvidos

E ao clicar nos botões de paginação ao final da página:
![](https://i.imgur.com/vbLLhXa.png)

Resulta em um erro, que leva a essa página https://cursos.alura.com.br/forum/usuario/<user_name>/2:

![](https://i.imgur.com/VODs5V1.png)

## **Possível resolução**: 

1. Provavelmente os botões de paginação deveriam apontar pra uma página:

- https://cursos.alura.com.br/forum/usuario/marcus-almeida2/resolvidos/**<numero_pagina>**

Essas funcionam perfeitamente como paginação.

2. O problema deve ser resolvido ao enviar o aluno diretamente do perfil do aluno para a página de tópicos que já está com paginação correta, ou seja: 

- https://cursos.alura.com.br/forum/usuario/<user_name>/resolvidos/1

**Comment by designernatan** [comment]
@Alm3ida opa marcus, mto obrigado pelos detalhes nesse bug!

vamos dar uma investigada no futuro, qualquer novidade pingamos aqui :)

**Comment by designernatan** [comment]
marcus, o time é tão rápido que investigou, corrigiu e ja deployou a correção, deu nem tempo de criar um card!

qlq coisa sobre isso só pingar aqui novamente

bom fim de semana!
