### ISSUE TITLE
Switch modo escuro/claro de fácil acesso para o site base

### ISSUE THREAD

**Issue by dvdlv** [caelum/alura-funcionalidades#744]
Um switch para trocar o modo escuro/claro e manter salvo para aquela conta. 

Atualmente eu uso um Navegador que me permite forçar o modo escuro e é okay pra mim. 
Mas pensando adiante, existem usuários que preferem o modo escuro e não conhecem o recurso ou usam navegadores diferentes. 
Utilizando do switch para isso, evita pequenos incômodos, como uma flashbang(Iluminação muito forte do nada) na boca quando se está saindo de um curso no qual você utiliza o modo escuro.

**Comment by designernatan** [comment]
@dvdlv valeu pela sugestao!

vc usa o dark reader tb?

a gente fez recentemente um levantamento de como será o dark mode da alura, ideia é que no futuro de médio prazo a gente consiga priorizar frente as outras iniciativas que estamos tocando

aproveitando aqui: de bate-pronto, onde vc iria no menu pra ligar e desligar o dark mode?


abcs!

**Comment by dvdlv** [comment]
Opa! 
Eu uso o navegador Opera GX que tem esse recurso de darkmode nativo, só clicar com o botão direito em qualquer lugar da tela e seleciono a opção "forçar página escura". 

![image](https://user-images.githubusercontent.com/106926852/205140826-8ab817d4-0f5c-40bd-9b59-8cf421c36d7a.png)

Mas acredito que essa área próxima ao logo da Alura ou a área do canto direito próxima ao menu "Meu aprendizado" seria um local visível e de fácil acesso que, creio eu, não interferiria em nada na estética da página. 

(não sei se a imagem foi de fato, primeira vez usando o github)

**Comment by designernatan** [comment]
show demais, mto obrigado dvdlv!

enfim como te falei, está nos planos! Por hora é continuar usando o opera gx ou o dark reader como solução de contorno

ps: a imagem veio sim
ps²: nosso dark mode vai ficar muito bonito :)

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
