### ISSUE TITLE
Numeração das aulas no app mobile

### ISSUE THREAD

**Issue by rafaelzipaosilva** [caelum/alura-funcionalidades#745]
Na versão web da Alura, cada curso está dividido em aulas, e, cada aula está dividida em capítulos.

Na versão do app não aparece essa divisão, ele aparece apenas como uma lista simples e sequencial. 

Seria muito bom para quem usa a versão do app se tivesse essa facilidade de ver apenas os itens daquela aula específica e não aparecer todas as aulas como uma lista.... se vc já está no final do curso, precisa percorrer todos os capítulos até onde parou.

**Comment by designernatan** [comment]
@rafaelzipaosilva valeu pela sugestao!

vc diz algo parecido com isso aqui da página web de curso?
![image](https://user-images.githubusercontent.com/5431347/205085772-ecce1649-f2ac-41bd-97c8-f8d967a73dff.png)

talvez um "voltar pro topo" resolveria? Igual o que aparece na página de aula?
![image](https://user-images.githubusercontent.com/5431347/205086031-edf42a14-2df3-4e52-b7c6-9d6dcb85a310.png)

**Comment by rafaelzipaosilva** [comment]
@designernatan eu digo algo mais parecido com essa parte aqui:

![image](https://user-images.githubusercontent.com/29807231/205086676-8177a8b8-e86d-4e44-921c-12a4ceeb8040.png)

![image](https://user-images.githubusercontent.com/29807231/205086746-429787ad-efab-4688-9075-da64f72ac6cd.png)

Pois, quando eu entro no meu app pra ver as aulas, ele não aparece com esse formato numérico, vou te mandar aqui um print do app.

<img width="1024" alt="20221201_150417303_iOS" src="https://user-images.githubusercontent.com/29807231/205087420-1685a867-a3c3-41c6-ad74-192ec75b90b6.png">

Essa númeração das aulas em cada um dos módulos ajuda bastante a não se perder e serve até de referencia pra fazer o commit no github sem se perder e/ou saber referente a qual aula é aquele commit.

**Comment by designernatan** [comment]
show, muito obrigado pelos detalhes (e pelo tempo!) rafael

Nao consigo te passar uma data, mas quando pegarmos esse fluxo no app para melhorarmos no futuro vamos debater isso

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
