### ISSUE TITLE
Implantar o "Gerenciamento das Dependências" de cada curso, no nível de aula.

### ISSUE THREAD

**Issue by AlexJBSilva** [caelum/alura-funcionalidades#746]
É evidente que a Alura realiza o "Gerenciamento de Versões" dos seus cursos.
Mas o "Gerenciamento das Dependências" de cada curso é realizado?
Caso afirmativo, com qual granularidade: a nível de curso ou a nível de aula de cada curso?

Caso negativo, minha sugestão é para a Alura criar esse tal de "Gerenciamento das Dependências" de cada curso, com granularidade a nível de aula.

E aí, no rodapé da transcrição de cada aula, ao lado do botão "Discutir no Forum", disponibilizar um botão "Atualizações".
Ao clicar no botão, abre uma página informando "A tecnologia evolui, veja aqui o que mudou nas 'dependências' dessa aula desde que lançamos esse curso".

Vai ajudar bastante na atualização dos alunos com a tecnologia, melhorar o entendimento das aulas e execução correta dos exercícios, além de valorizar o conteúdo da Alura mantendo a relevância dos cursos enquanto uma atualização dos videos não é realizada.

Por exemplo: se página de "Atualizações" exibisse a informação contida na resposta para [essa](https://cursos.alura.com.br/forum/topico-usr-bin-python3-no-module-named-simplehttpserver-89637) pergunta do Forum, provavelmente a pergunta nem seria feita, e quem perguntou em agosto de 2019 teria a informação necessária antes de abril de 2020...

Para ficar mais claro:
"Gerenciamento" no sentido de saber que, na Aula X do Curso Z, o instrutor orienta a execução do módulo (dependência externa) "SimpleHTTPServer" com o Python 3.
E que, do lançamento (ou gravação) do curso até a data atual, o "SimpleHTTPServer" foi mesclado com o "http.server" no Python 3.0.
E, finalmente, que a sugestão de uso atualizado é executar o "python3 -m http.server".

**Comment by designernatan** [comment]
@AlexJBSilva valeu pela sugestao e pelo tempo em detalhá-la tão bem! Nao precisava formalizar nao :)

só dando um copy/paste do que diogo comentou lá no discord tb:

> Realmente é um grande desafio nosso acompanhar todas as atualizações e mudanças de dependências, libs e afins e normalmente o time de Conteúdo usa um artigo ou um Alura+ pra explicar essas principais alterações. Mas achei muito legal a ideia de ter um espacinho específico destacado para isso. Vamos compartilhar com o time e entender a viabilidade de colocar algo assim no ar! Super obrigado pela sugestão e sempre que tiver novas ideias vai mandando pra gente, por favor! Um grande abraço e bons estudos! 😉

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
