### ISSUE TITLE
Sugestão de rede social, chat e busca por recrutamento

### ISSUE THREAD

**Issue by MuriloFurlan80** [caelum/alura-funcionalidades#747]
Boa Noite sugiro uma rede social interna com a conta da Alura, assim imagino que é mais facil encontrar outras pessoas que contem o mesmo interesse do conteúdo e quem sabe não ter uma forma de encontrar recrutadores que buscam talentos como nós.

Agradeço a atenção

Att,

Murilo.

**Comment by laiscavalcanti** [comment]
Oi, Murilo, tudo bem?

Os pontos que você levantou são bem interessantes, sobre a rede social nós temos o nosso canal no discord que cumpre essa função de unir pessoas com a mesmo interesse e compartilhamento de conteúdo interno, segue o link: https://discord.com/invite/Q35hcA5EFG

Sobre os recrutadores, nós temos uma plataforma que é a Vitrine.Dev: https://cursos.alura.com.br/vitrinedev que é justamente um local para ser compartilhado os projetos feitos nos cursos e formações para que os recrutadores achem os alunos que mais se adequam as vagas.

Espero te ter ajudado!

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
