### ISSUE TITLE
Nome nos certificados

### ISSUE THREAD

**Issue by danilocdesousa** [caelum/alura-funcionalidades#748]
Na página "Seu perfil", seção "Dados gerais", estou tendo um problema para atualizar meu nome no campo "Nome nos certificados". Aparentemente, está programado para que cada palavra comece com uma inicial maiúscula, incluindo partículas tais como: da, de, dos.

Meu sobrenome, por exemplo, é Cardoso de Sousa, mas no campo aparece Cardoso De Sousa. Eu tentei mudar o "De" para "de", mas embora tenha recebido a confirmação de que os dados foram atualizados, a partícula ainda permanece capitalizada, ou seja, "De". Sei que isto parece bobagem, mas me incomoda um pouco.

Obrigado por este espaço para sugestões.

**Comment by laiscavalcanti** [comment]
Oi, Danilo, tudo bem?

Entendo perfeitamente seu incomodo. Irei levar para o time responsável. Quando estiver certinho, volto aqui para te falar.
Obrigada!

**Comment by giovana-armidoro** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
