### ISSUE TITLE
Baixar podcasts no aplicativo para mobile

### ISSUE THREAD

**Issue by italomded** [caelum/alura-funcionalidades#749]
O aplicativo da Alura tem ficado cada vez melhor, e entre indas e vindas da faculdade no ônibus, sem estar com conexão de internet, eu tenho acompanhado alguns materiais através do aplicativo. E uma das coisas que gosto bastante é os podcasts. No entanto, os podcasts não podem ser baixados, diferente dos cursos, para você ouvi-los de forma offline.

Então minha sugestão é basicamente isso: poder baixar podcasts através do aplicativo da Alura para mobile e poder ouvi-los de forma offline.

**Comment by laiscavalcanti** [comment]
Oi, Italo, tudo bem?

Sugestão bastante pertinente, de fato, pode facilitar o acesso aos episódios. Iremos levar para equipe responsável.
Obrigada!

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
