### ISSUE TITLE
Mostrar se os exercícios estão completos na lista de vídeos e exercícios do App

### ISSUE THREAD

**Issue by pedrofernandesfilho** [caelum/alura-funcionalidades#75]
No aplicativo de celular seria de grande ajuda se na lsita de vídeos e exercícios mostrar se os exercícios já foram feitos, assim como mostra que o vídeo já foi assistido.

**Comment by felipetorres** [comment]
Oi Pedro, temos algumas ideias para modificar essa parte dos exercícios para justamente exibir os exercícios feitos, por hora estamos focando nossos esforços em outras tarefas mais pedidas, mas em algum momento pegaremos essa parte dos exercícios, beleza?
