### ISSUE TITLE
Opção para zerar progresso em um curso/formação

### ISSUE THREAD

**Issue by mkydouglas** [caelum/alura-funcionalidades#750]
Olá pessoal!

Quero sugerir que implementem uma opção para zerar o progresso de um curso ou de uma formação.

Mas por quê?

No meu caso, as vezes começo algum curso/formação e acabo não concluindo e quando retomo depois de algum tempo já não me recordo de todo assunto e preciso recomer. Mas sem zerar o progresso sempre preciso ficar lembrando qual foi a última aula que fiz e os exercícios já respondidos anteriormente continuam respondidos, o que atrapalha nessa retomada.
E também é uma funcionalidade que serve para quem quer refazer um curso depois de algum tempo para rever o conteúdo.

Desde já, obrigado!

**Comment by designernatan** [comment]
@mkydouglas valeu pela sugestao!

sem planos por hora para reset de cursos, na verdade desenvolvemos o 'sair do curso' a fim de melhorar a organização da dashboard do aluno, mas o progresso é para continuar ali mesmo 

abracão!

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
