### ISSUE TITLE
Botão Logout que deslogue de todas as maquinas.

### ISSUE THREAD

**Issue by michelwesley** [caelum/alura-funcionalidades#751]
Acho bastante interessante que dentro da área do aluno haja um botão que deslogue de todas as maquinas que eu esteja logado.

Hoje recebi uma mensagem após o login informando que minha conta estava logada em outra maquina. Logo de cara, solicitei troca de senha, mas o erro persiste.

Acho que um botão que deslogue, ou até mesmo que na troca de senha, isso ja seja realizado automaticamente, seria bem interessante.

Obs.: minha licença foi dada pela empresa que trabalho.

**Comment by designernatan** [comment]
@michelwesley valeu pela sugestao!

a gente tinha alguns problemas com isso ha uns anos, aí colocamos como regra que só pode ter uma session aberta por usuário

talvez vc logou em algum outro browser ou note/pc

de qualquer forma, sempre vale colocar uma senha forte pra evitar problema tbm, recomendo o lastpass pra ajudar nisso tbm

abracao!

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
