### ISSUE TITLE
O que aconteceu com o indicador de concluído dos cursos?

### ISSUE THREAD

**Issue by rodrigoslayertech** [caelum/alura-funcionalidades#752]
![image](https://user-images.githubusercontent.com/9668277/207055553-a7ac6f85-2bac-4ea5-9750-5bdb6b26703d.png)
Antes ficava assim verdinho.

![image](https://user-images.githubusercontent.com/9668277/207055600-0c872069-3c40-4786-8937-e81bb5ea2979.png)
Agora fica assim como se não tivesse feito o curso!!

**Comment by designernatan** [comment]
@rodrigoslayertech valeu pela sugestao!

estranho, aqui aparece assim:
![image](https://user-images.githubusercontent.com/5431347/208144003-a3b770fe-f158-42a2-99c5-c6b56710d54d.png)

dps manda seu usuario? Testa também se tem alguma extensao bloqueando a visualizacao normal da pagina

**Comment by designernatan** [comment]
opa rodrigo, achei qual pagina que vc tava falando, é a que mostra todos os cursos da escola X né?

vamos dar uma olhada no futuro, ai pingamos de volta aqui

**Comment by andradeoromulo** [comment]
Olá, @rodrigoslayertech. Voltamos a barra de progresso para a página indicada por você.

Obrigado por entrar em contato e por enviar sua sugestão.

**Comment by rodrigoslayertech** [comment]
@andradeoromulo Obrigado, bem melhor agora para separar visualmente quais cursos estão concluídos e quais faltam fazer!

Só uma dica de design, eu removeria esses indicadores verdes (a barra e o ícone) somente na lista de cursos concluídos lá no perfil do aluno porque assim fica menos poluído o visual:

![image](https://user-images.githubusercontent.com/9668277/209149765-4a4633b7-af37-4fe2-b31a-04ba553aa5df.png)

**Comment by andradeoromulo** [comment]
Opa, @rodrigoslayertech. Realmente esses cards da página do perfil não têm essa barra. Entrou ontem junto com a volta da barra na página de categoria, mas não foi de propósito. Ontem mesmo já percebemos e criamos uma correção. Deve ir para produção hoje. Obrigado, mais uma vez, por avisar.
