### ISSUE TITLE
Reagir a uma resposta no fórum sem ser dono da pergunta

### ISSUE THREAD

**Issue by RedONe06** [caelum/alura-funcionalidades#753]
Seria interessante se pudéssemos reagir positivamente às soluções do fórum que nos ajudaram no problema. Assim como acontece no StackOverflow.

**Comment by designernatan** [comment]
@RedONe06 valeu pela sugestao!

O Paulo sugeriu [algo semelhante aqui](https://github.com/caelum/alura-funcionalidades/issues/2)

comenta lá depois o que você acha? Por hora sem planos de mexer no fórum, mas estamos otimizando bastante coisa aqui :)

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
