### ISSUE TITLE
Aumentar o tempo de resposta para perguntas no fórum

### ISSUE THREAD

**Issue by RedONe06** [caelum/alura-funcionalidades#754]
Existem questões publicadas e visíveis no fórum que variam entre tempo de publicações, e somente aquelas publicadas em questão de meses podem ser respondidas pela comunidade. As questões que não foram resolvidas a tempo acabam sendo esquecidas e sem resoluções, assim, quando caímos no mesmo problema (que poderia ter sido resolvido a meses atrás por alguém) não sabemos a resposta. Se tivesse a funcionalidade de responder as questões mesmo depois de um grande período de tempo, poderíamos ajudar as pessoas a resolverem seu futuros problemas e dar mais oportunidades de interação no fórum.

**Comment by designernatan** [comment]
@RedONe06 valeu pela sugestao!

tem [uma sugestão semelhante aqui](https://github.com/caelum/alura-funcionalidades/issues/660)

em resumo, já fizemos alguns testes e o tempo atual é o ideal para evitar os problemas que [mencionei aqui](https://github.com/caelum/alura-funcionalidades/issues/660#issuecomment-1194333438)

hoje estamos bem focados no discord também

abcs e ótimo natal!

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
