### ISSUE TITLE
Filtro de categoria no item conferir todas as novidades

### ISSUE THREAD

**Issue by DeniseCastroUOL** [caelum/alura-funcionalidades#755]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

No **_Dashboard_**, onde tem o item **"Conferir todas as novidades"** eu gostaria que tivesse um filtro onde fosse possível visualizar as novidades de cada categoria, por exemplo: novidades _android_, novidades programação, novidades artigos, etc. As novidades estão todas, independente da categoria, em uma lista e, sinceramente, acho um pouco confuso. Eu leio toda a lista para encontrar o assunto que quero ver.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

Aqui tem imagem do local onde se encontra o item Conferir todas as novidades...
![Captura de Tela 2022-12-15 às 13 44 45](https://user-images.githubusercontent.com/82236516/207918662-87fe507f-0f4e-449b-9096-9526bda054c5.png)

Aqui, como a listagem de novidades aparece: a listagem é grande... se os assuntos puderem ser filtrados fica bem melhor para saber quais as novidades do android. Não importa o tipo da novidade, se é curso, se é alura+, se é artigo, o importante é que possamos ver separadamente todas as novidades do android, de devops e assim por diante. Não sei se ficou claro, mas, qualquer dúvida pode me perguntar. Agradeço desde já. 

<img width="808" alt="Captura de Tela 2022-12-15 às 13 51 49" src="https://user-images.githubusercontent.com/82236516/207920215-c8bfaaae-b533-4614-a5a6-6a448ebf9230.png">

**Comment by designernatan** [comment]
@DeniseCastroUOL valeu pela sugestao!

quando pegarmos essa parte de novidades para a melhorarmos no futuro vamos considerar um filtro, tudo bem?

por hora, recomendaria algumas saídas:

1. Ali em/explore, dá para fazer um filtro via console, algo assim:
```
const timelineList = document.querySelectorAll('.timeline__list li');

timelineList.forEach(item => {
  const tag = item.querySelector('.timeline__tag');
  if (tag && tag.innerText === 'UX & Design') {
    item.style.display = 'block';
  } else {
    item.style.display = 'none';
  }
});
```

2. Usar o [Aluraflix](https://cursos.alura.com.br/aluraflix) (que já tem separado) e as [Páginas das Escolas](https://cursos.alura.com.br/escolas/front-end)

abcs e um ótimo natal! 🎄

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
