### ISSUE TITLE
Bloco anotações aula

### ISSUE THREAD

**Issue by rbkrebs** [caelum/alura-funcionalidades#756]
Atualmente estou trilhando React com Typescript e sinto falta da possibilidade de marcar trechos da aula para fazer algumas anotações. Costumo rever algumas aulas para relembrar algum detalhe e muitas vezes preciso assistir diversas aulas até achar o detalhe que procuro.

Penso que um item Anotações no menu do perfil do usuário levaria para uma tela onde listaria todas as aulas que possuem anotações. Nessa tela seria possível buscar por termos que estariam nas anotações e assim aplicar um filtro nas aulas.

<img width="174" alt="menu_perfil_alura" src="https://user-images.githubusercontent.com/17108676/208257424-8d3db7d5-99b9-4bf1-bf38-5281bb534a84.png">

**Comment by designernatan** [comment]
@rbkrebs valeu pela sugestao!

nós tínhamos algo assim há uns tempos, mas acabamos abortando pois não atingiu nossa expectativa (não só em engajamento como em outros pontos) o que esperávamos quando lançamos o MVP em 2018/19

em geral, indico bastante o Notion pra fazer anotações e o [Pocket](https://getpocket.com) para salvar os links das aulas certinho

abcs e ótimo natal!

**Comment by designernatan** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
