### ISSUE TITLE
Certificado ao Concluir uma Formação

### ISSUE THREAD

**Issue by lee22br** [caelum/alura-funcionalidades#757]
Primordial ter a emissão de um Certificado ao concluir uma Formação. Acabei de concluir a formação [Certificação Java](https://cursos.alura.com.br/formacao-certificacao-java) com 9 cursos , foram emitidos 9 certificados. Mas eu preciso de UM (único) certificado contendo o total de horas (somando as horas dos 9 cursos).

**Comment by designernatan** [comment]
@lee22br opa já temos!

fica no 'perfil e certificados'

se não tiver aparecendo me manda o link do seu perfil pra gente investigar oq pode ter sido?

**Comment by masromao** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
