### ISSUE TITLE
Plano de Estudo - Inclusão de seções

### ISSUE THREAD

**Issue by andreaguiar-br** [caelum/alura-funcionalidades#758]
Implementar inclusão de textboxes ou possibilidade de criar seções nas listas de cursos, links e sites quando montamos plano de treinamento, para deixar mais organizado, a exemplo da estruturação de formações e dos planos capacitação institucionais.

Assim, possibilita separar por seções como (Introdução, básico, avançado) ou (cursos frontend, backend, infraestrutura, BD..)

**Comment by designernatan** [comment]
@andreaguiar-br valeu pela sugestao (e feliz 2023!)

gosto e acho que alguem ja sugeriu algo assim também

quando pegarmos a parte de plano de estudos para melhorarmos vamos considerar isso, ok?

abracao!


edit:
não é o ideal, mas por hora o que faria é criar vários PDEs (planos de estudos), algo assim:

Front-end básico
Front-end avançado
Front-end com Sass

**Comment by masromao** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
