### ISSUE TITLE
Salvar Artigos Na Dashboard

### ISSUE THREAD

**Issue by h-hyolou** [caelum/alura-funcionalidades#759]
Quando no curso vêm como sugestão de "estudos extras", a leitura de algum artigo da própria plataforma, por vezes, gostaria de reler aquele artigo, mas todas às vezes tenho que seguir um dos 2 caminhos: 1° ir em pesquisar > digitar o título e/ou a categoria > navegar entre as páginas para achar aquele artigo em específico; 2° procurar dentro do curso a página com o link para o artigo, e geralmente leva tempo para encontrar devido aos vários "módulos" que o curso possui quando o interessante, séria ter a possibilidade de salvar o artigo para "ler depois" ou na própria dashboard ter um espacinho com a parte de _artigos salvos_ , sei que existe a opção de favoritar a página no próprio navegador, mas quando passam a ser um número relevantes de artigos fica inviável só ficar favoritando.

**Comment by designernatan** [comment]
@hyolouLB valeu pela sugestao e feliz 2023!

por hora não temos planos para algo assim no futuro médio, ia comentar justamente do favoritar do browser, mas tem umas opções mais bacanas:
- [getpocket](https://getpocket.com)
- [readwise](https://readwise.io/read)

o legal é que com um clique você salva online os artigos, consegue taguear tudo e até ler offline!

abracao

**Comment by masromao** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros!
