### ISSUE TITLE
Card da aula com sinalização de legenda

### ISSUE THREAD

**Issue by LeandroMohrMCWB** [caelum/alura-funcionalidades#760]
Olá pessoa tudo na paz?
Verifiquei nas issues fechadas que já existe um trabalho de inclusão de legendas para melhorar a acessibilidade e leitura dos alunos.
Porém até o momento não me deparei com nenhuma aula que tenha isso, e não encontrei nenhuma sinalização que "esse" curso está adaptado ou não...

Acho que seria de grande ajuda ter essa informação/sinalização de fácil visualização.

**Comment by masromao** [comment]
Olá Leandro, tudo certinho? Muito obrigado pela sugestão!

Temos [essa outra issue aqui](https://github.com/caelum/alura-funcionalidades/issues/10) comentando um pouquinho mais sobre a inclusão das legendas e estamos estudando como podemos fazer da forma mais eficiente o possível.

Muito boa a sua ideia de trazer um elemento de fácil visualização para informar se um curso já está ou não legendado.

Internamente já começamos testar legendas em alguns cursos e por se tratar de um trabalho extenso infelizmente não consigo te passar um prazo pra implementação geral dessa funcionalidade, mas com certeza levaremos em consideração sua sugestão.

Abraços e bons estudos!

**Comment by giovana-armidoro** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros! :)
