### ISSUE TITLE
Botão de "favoritar"

### ISSUE THREAD

**Issue by livfonseca** [caelum/alura-funcionalidades#761]
Estou estudando uma matéria dentro da plataforma e em alguns momentos sinto que vou ter dificuldade de lembrar certos assuntos no futuro. Gostaria de poder "favoritar" uma página dentro de um módulo, pra depois não precisar ficar caçando aquela página específica.

Seria interessante se os favoritos ficassem guardados em uma aba "favoritos" dentro e fora do módulo específico, e lá ter guardados todos os favoritos de vários cursos feitos. 

Se desse para colocar título e descrição, melhor ainda. Igual quando vamos salvar alguma página web em favoritos e pede pra colocar um título, descrição e se quer guardar em uma pasta específica ou não.

Outra coisa interessante seria poder grifar certas partes de texto e ficarem guardadas em uma pasta separada. Como o favoritos para páginas inteiras, mas para trechos de texto. Mas sinto que o de salvar a página toda é bem mais essencial.

Espero ter conseguido ser clara na explicação. 😊

**Comment by masromao** [comment]
Olá @livfonseca , obrigado pela sugestão!

Você foi clara sim na explicação, deu pra entender bem a ideia.
Muito boa essa ideia de favoritar páginas dentro de um módulo e também a de grifar certas partes de texto.

Infelizmente como ainda não temos essas features na plataforma, o caminho para salvar as páginas mais próximo do que você sugeriu teria que ser utilizando o Favoritar do browser mesmo por hora, mas com certeza as ideias serão avaliadas quando formos atualizar a plataforma futuramente. Como ainda não temos previsão, ainda não consigo te passar um prazo, ok?

Obrigado novamente pela sugestão.
Abraços e bons estudos.

**Comment by giovana-armidoro** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros! :)
