### ISSUE TITLE
Preview de cursos/formações em edição ou planejados no dashboard

### ISSUE THREAD

**Issue by dandore** [caelum/alura-funcionalidades#762]
Seria interessante que houvesse abaixo/ao lado do quadro Novidades do Dashboard da Alura um quadro com uma prévia do que será lançado pela escola.

Talvez o mesmo conteúdo que venha a ser lançado no novidades mesmo, mas um estágio antes - algo do Tipo Curso tal/ formação tal
em gravação//em edição, previsão para release, etc.

Às vezes esperamos que saia alguma continuação de um curso/formação e ele demora mais que o esperado, então essa fila de releases pode ajudar no planejamento de estudos

**Comment by masromao** [comment]
Olá @dandore , obrigado pelo contato!

Muito interessante essa sua ideia do preview de material planejado na dashboard, respondemos há algum tempo uma [questão parecida no nosso Fórum.](https://cursos.alura.com.br/forum/topico-cursos-que-serao-lancados-59837)

Como citado na resposta: "O problema é que um curso sendo desenvolvido pode ser lançado em 1 mês ou demorar 4 meses depois das revisões, edições, regravações ou até cancelamento. Bem no começo da Alura testamos isso e gerava uma ansiedade ainda maior entre os alunos."

Mas a ideia de deixar isso aparente de uma forma intuitiva na Dashboard é muito legal, com certeza quando formos pensar numa atualização da página levaremos isso em consideração. Só não consigo te passar um prazo pois não temos previsão por enquanto sobre isso.

Obrigado novamente pela sugestão.
Abraços e bons estudos!

**Comment by giovana-armidoro** [comment]
Fechando a issue, mas ela continua aberta para comentários futuros! :)
