### ISSUE TITLE
Acessibilidade nos cursos para cegos

### ISSUE THREAD

**Issue by rhanielfarias** [caelum/alura-funcionalidades#763]
Olá, sou deficiente visual(cego) e assinei a Alura por conta da acessibilidade nas transcrições. Pois, como faço o uso de leitor de telas(NVDA), e também não consigo visualizar os vídeos, a melhor forma de eu conseguir acompanhar o conteúdo é através da transcrição com os trechos dos códigos utilizados no momento, como era feito no início, por exemplo, nos cursos iniciais de Java. Contudo, nos últimos cursos na transcrição só tem a fala e nada de código e, mesmo tendo a opção para baixar no Github, para quem não está vendo o vídeo fica perdido e muito difícil de compreender. Então por isso é necessário durante a transcrição ter o trecho do código usado, ou quando for um curso de plataformas, deixar bem descrito o que está sendo feito e os passos necessários a seguir

**Comment by gui-lirasilva** [comment]
Olá @rhanielfarias, tudo bem?
Como foi conversado com o instrutor Rodrigo Ferreira e repassou os feedbacks, estaremos fechando a issue.
