### ISSUE TITLE
Versão do framework / linguagem destacados na página do curso

### ISSUE THREAD

**Issue by mikedpsm** [caelum/alura-funcionalidades#764]
Já não é a primeira vez que me deparo com um curso que supostamente está defasado, e só percebo isso quando já estou com 25% de conclusão do curso. É frustrante e uma tremenda perca de tempo, visto que os arquivos disponibilizados para download também não batem com o projeto apresentado em vídeo. Uma grande ajuda seria ter em destaque em todo curso de programação a versão da linguagem ou do framework sendo utilizado, assim, evitando que nós, alunos, iniciemos cursos que não estão atualizados.

**Comment by masromao** [comment]
Olá @mikedpsm , obrigado pelo envio!

Lamentamos por isso ter acontecido com você, com certeza vamos considerar a sua ideia de dar destaque na versão da linguagem/framework utilizada no curso quando pegarmos a tela para fazer melhorias futuramente. Inclusive, idealmente essas informações entrariam no FAQ do curso do lado direito da página, mas por enquanto não consigo de dar um prazo de quando iremos pegar isso.

Me fala o curso que você citou que identificou esse problema, que eu vou passar o feedback diretamente para o time de conteúdo.

Abraços e bons estudos!

**Comment by mikedpsm** [comment]
Boa noite,

Foi no curso "SOLID com C#: princípios da programação orientada a objetos" do instrutor Daniel Portugal.

**Comment by masromao** [comment]
Obrigado @mikedpsm , vou levar seu feedback para o time de conteúdo!

Vou fechar a issue por aqui, mas fique a vontade pra voltar a comentar qualquer coisa que achar necessário.
Abraços e bons estudos!
