### ISSUE TITLE
Dark mode na pagina do course

### ISSUE THREAD

**Issue by munhoesrc** [caelum/alura-funcionalidades#765]
Acredito que poderia ser implementada o dark mode no course, facilitando as pessoas que como eu sofrem com a luminosidade das telas claras.

**Comment by artnicodemus** [comment]
Oi @munhoesrc obrigado pela sugestão!

Recentemente fizemos um planejamento de como será o darkmode da Alura. A ideia é que num futuro de médio prazo a gente consiga priorizar isso frente as outras iniciativas que estamos tocando.

Aproveitando o momento: em qual parte do menu da Alura você iria para ligar/desligar o darkmode?

Abraços e bons estudos!

**Comment by munhoesrc** [comment]
Olá @artnicodemus, obrigado pelo retorno! Minha sugestão é do dashboard do aluno como um todo na navegação pelas rotas do mesmo.

DASHBOARD:
![Captura de tela de 2023-01-25 15-23-20](https://user-images.githubusercontent.com/106607259/214650185-2ed6f115-c508-4b01-94f8-ad9cc3670bbc.png)

PAINEL DE FORMAÇÃO:
![Captura de tela de 2023-01-25 15-22-55](https://user-images.githubusercontent.com/106607259/214650458-2ea1ee77-5493-40df-b376-bda817920697.png)


Atenciosamente,
Renan.

**Comment by artnicodemus** [comment]
Interessante, muito obrigado pela atenção @munhoesrc !
Vamos levar em consideração quando essa iniciativa acontecer, abraços e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, mas podem voltar a comentar se quiserem :)
