### ISSUE TITLE
Inclusão de exercícios práticos entre as aulas

### ISSUE THREAD

**Issue by Andrez0s** [caelum/alura-funcionalidades#766]
Olá a todos!

Senti essa necessidade de ter exercícios práticos entre as aulas ou entre os vídeos, as perguntas entre as aulas eu não considero como exercicios pois não executamos nada, simplesmente respondemos sobre um conteúdo que acabamos de ver. E acabo saindo do curso com a sensação de que não fixei o conteúdo e preciso buscar fora da Alura, seja exercícios para praticar ou explicações do mesmo conteúdo visto nas aulas.

Esses exercícios seriam em cima do conteúdo passado nas aulas e com correção do instrutor ou por texto mesmo (como exemplo a seção de "Opinião do instrutor", a ideia seria tentar fazer mais coisas sozinhos, sem o acompanhamento do instrutor e posteriormente ter a correção.

Essa foi minha experiência nos cursos que fiz até agora, e teve pouquíssimos "desafios" que o instrutor deixava pra gente.

**Comment by artnicodemus** [comment]
Muito obrigado pela sugestão @Andrez0s !

Pensando nesse desafio de deixar os exercícios mais práticos e empolgantes, criamos o Alura Challenges. Pra saber mais é só ir no menu da Alura em 'Conteúdo > Challenges'.
Por enquanto temos challenges de back-end e front-end e há troca de ideias sobre os desafios no discord da Alura.

Abraços e bons estudos!

**Comment by Andrez0s** [comment]
Olá!

Pelo que vi nos challenges, são mais complexos e projetos maiores, é excelente para praticar sem dúvida, mas acredito que praticar as pequenas funções que aprendemos dentro dos cursos seja bem importante pois vamos fixando partes do conteúdo aos poucos, mas é isso fica a sugestão, Obrigado.

**Comment by artnicodemus** [comment]
Entendi!
Muito obrigado pelas sugestões @Andrez0s , iremos levar essas ideias em consideração quando acontecer alguma iniciativa relativa à exercícios.

Abraços e bons estudos (:

**Comment by artnicodemus** [comment]
Lembrei de mais uma opção que temos pra você praticar os estudos @Andrez0s , se chama 7 Days of Code.
https://7daysofcode.io/
São desafios de diversas áreas de tecnologia que você pode praticar. É uma opção mais simples e fácil de acompanhar do que os Challenges!

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, mas podem voltar a comentar se quiserem :)
