### ISSUE TITLE
Movimentar Plano de Estudos

### ISSUE THREAD

**Issue by edelyviana** [caelum/alura-funcionalidades#767]
Tentei de várias formas organizar o meu dashboard de planos de estudos por mim criados e não achei como fazer e por isso veio a ideia de sugerir essa funcionalidade.... 

Por exemplo eu criei 3 planos de estudos plano 1, plano 2 e antes de criar o plano 3 eu criei outros dois planos: liderança e Alta Gestão e assim ficou: plano 1, plano 2, liderança, alta gestão e plano 3...

Eu queria movimentar o plano 3 para logo em seguida ao plano 2 e assim por diante.

Espero ter sido claro na ideia e caso já exista essa funcionalidade, peço imensas desculpas.
Grato e até a próxima.

**Comment by giovana-armidoro** [comment]
oi Edely muito obrigada pela sugestão!

essa é uma sugestão bem legal, por hora não temos planos de mexer nessa tela de planos de estudos mas quando a gente pegar isso vamos discutir a possibilidade de implementar algo assim, beleza?

qualquer atualização te aviso por aqui

abraços e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, mas podem voltar a comentar se quiserem :)
