### ISSUE TITLE
Anotando e salvando artigos.

### ISSUE THREAD

**Issue by falcettijr** [caelum/alura-funcionalidades#768]
Olá! Tudo bem!

Meu nome é Sergio e sou aluno de vocês e estou adorando a plataforma!

Eu gostaria de fazer duas sugestões:

1) Durante as aulas eu senti muita falta de ter um espaço dentro da própria plataforma para fazer anotações, enquanto assistimos aula, a Udemy tem esse recurso, vocês podem conferir: É uma caixa de texto simples embaixo do vídeo, onde podemos guardar as anotações e depois ter essas anotações com fácil acesso separadas por aulas. Então quando tiver dúvidas sobre algum tópico ficaria fácil e os alunos não precisariam de usar outras ferramentas como o Notion.

2) Eu gosto muito dos artigos da Alura porém também não temos a opção de "salvar" para ler depois ou fazermos uma coleção de favoritos dos melhores artigos, separados por categoria. Isso facilitaria muito quando tivermos dúvidas em algum tópico e teríamos todos os artigos salvos para rápida consulta e não precisamos ficar salvando nos favoritos do navegador..

Espero ter ajudado!

**Comment by giovana-armidoro** [comment]
oi Sergio muito obrigada pela sugestão!

que bom que está gostando da plataforma, a gente fica muito feliz em saber disso!

1. tivemos algo assim, mas acabamos abortando pq não atingiu a expectativa (não só em engajamento como em outros pontos) que esperávamos quando lançamos o MVP. Temos planos futuros de voltar a pensar em algo voltado a esse sentido mas não temos um prazo planejado pra isso acontecer. Mas, se puder me contar, queria saber como vc faz essas anotações hoje em dia e o que você costuma anotar das aulas.

2. muito legal a sugestão! por hora não temos planos pra fazer algo assim mas, caso você use o Chrome, você pode adicionar a guia do artigo à lista de leitura do navegador, já por dentro da plataforma você poderia criar um plano de estudos chamado “Artigos favoritos” e ir adicionando os artigos lá ou tem também algumas sugestões que o Natan deixou nessa issue [aqui](https://github.com/caelum/alura-funcionalidades/issues/759)

qualquer atualização aviso aqui, espero ter ajudado

abraços e bons estudos!

**Comment by falcettijr** [comment]
Muito obrigado pelo feedback! Vou dar uma olhada nas sugestões! Obrigado!
