### ISSUE TITLE
Adicionar data de início do curso no certificado do "Formações concluídas"

### ISSUE THREAD

**Issue by rafaaleluia** [caelum/alura-funcionalidades#769]
Na página principal do certificado do "Formações concluídas" e logo a cima do "Finalizado em ...", colocar a data de início do primeiro curso da trilha de formação.

**Comment by giovana-armidoro** [comment]
oi Rafa, valeu pela sugestão!

em uma versão anterior do certificado já tivemos a data de início da formação/curso mas depois que o certificado passou por uma atualização, a partir de pesquisas e discussões, decidimos por deixar no certificado normal apenas a data de finalização por considerarmos ser a informação mais relevante nesse contexto, você pode acompanhar alguns pensamentos sobre isso nessa [issue](https://github.com/caelum/alura-funcionalidades/issues/183)

mas, caso você precise de um certificado que contenha a data de início, você pode optar por pegar o certificado formal, é só clicar no botão “Certificado formal” abaixo do certificado, nele contém o período de início e fim de estudos

espero ter ajudado

abraços e bons estudos!

**Comment by rafaaleluia** [comment]
Oi, @giovana-armidoro. 
Então, no certificado de "Formações concluídas", não aparece a opção "Certificado formal". 
Essa alternativa está apenas nos certificados dos cursos individuais.

Outra coisa que senti falta e tinha nos certificados antigos, foi o código de validação do certificado. Isso poderia voltar tb.

**Comment by andradeisadora** [comment]
oi @rafaaleluia 
faz sentido termos um certificado formal pras formações mesmo, assim podemos colocar essas informações que faltam
vou levar a ideia pro time pra conversarmos sobre o assunto

abraço e bons estudos!

**Comment by oArthurCandido** [comment]
Olá. Não sei se essa sugestão se encaixa como um reforço nessa issue, mas seria legal ter a possibilidade de gerar uma matriz integralizada com os cursos realizados em uma área de formação, hoje quando vejo a lista de cursos que realizei, tenho a opção de gerar um "Certificado completo" que apresenta todos os cursos de todas as formações realizadas em um único comprovante com o total de horas. Eu preciso cumprir um volume de horas em atividades para minha universidade e o sistema limita cada envio de comprovação em 50 horas em um máximo de 10 envios. Para cumprir as 200 horas exigidas, eu precisaria de 10 comprovantes de pelo menos 20 horas ou 4 comprovantes de pelo menos 50 horas (ou o que a matemática permitir nesse intervalo). Um certificado formal da formação seria uma solução, uma vez que a formação tem carga horária que integra os cursos nela realizados.

**Comment by andradeisadora** [comment]
oi @oArthurCandido 
colocamos no nosso backlog pra fazermos o certificado formal de formações, mas não tenho prazo pra te passar ta?
qualquer coisa avisamos aqui :)

abraço e bons estudos!

**Comment by masromao** [comment]
Pessoal, fechando a issue,  mas podem voltar a comentar se quiserem :)
