### ISSUE TITLE
Separar os cursos por nível de conhecimento

### ISSUE THREAD

**Issue by DeniseLeandroDeCastro** [caelum/alura-funcionalidades#770]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Vou falar em relação ao Android, por ser a minha área de atuação, porém, essa funcionalidade se adapta a todos os cursos/conteúdos...

Onde tem... **Descubra novos cursos ** -> são listados: programação, frontend, etc..., quando a pessoa clicar em Mobile, por exemplo... Tem a separação de React... Android.. Seria interessante em cada categoria, os cursos serem listados por nível de conhecimento, porque a pessoa que está iniciando não tem a menor noção de qual curso seria interessante para iniciar, só é possível ver isso quando assiste ou lê o conteúdo e mesmo assim ainda podem ficar dúvidas. Se for dividido por nível de conhecimento, cada um já saberá como seguir. 

Ex.:
**Android - Java**
**Iniciante**
    Aqui devem ser listados em sequência a partir do mais básico

**Intermediário**
   Aqui devem ser listados em sequência a partir do mais básico

**Avançado**
    Aqui devem ser listados em sequência a partir do mais básico

**Android - Kotlin**
**Iniciante**
    Aqui devem ser listados em sequência a partir do mais básico

**Intermediário**
    Aqui devem ser listados em sequência a partir do mais básico

**Avançado**
    Aqui devem ser listados em sequência a partir do mais básico

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

**Comment by giovana-armidoro** [comment]
oi Denise, muito obrigada pela sugestão!

essa é uma questão super válida, a categorização dos conteúdos como iniciante, intermediário e avançado é algo mais complexo por diversos pontos como a quantidade de cursos que temos e quantidade de times que precisariam ser envolvidos nessa tarefa

no entanto, temos pensado em estratégias e soluções que poderiam ajudar nisso, para que os alunos consigam encontrar conteúdos relevantes para estudar, alguns exemplos: onboarding com recomendação de conteúdo, organização dos pré-requisitos de conteúdo, melhorias na busca, melhorias no menu…

temos planos de continuar buscando mais estratégias para a melhoria da descoberta de conteúdo na plataforma nesse ano, esperamos que essas soluções auxiliem nessa questão, mas também vamos levar sua sugestão para discussão para pensarmos em mais possibilidades

obrigada, abraços e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, mas podem voltar a comentar se quiserem :)
