### ISSUE TITLE
Agrupamento das transcrições dos cursos

### ISSUE THREAD

**Issue by AndyinTheNW** [caelum/alura-funcionalidades#771]
Atualmente, cada aula conta com uma transcrição em texto, então notei que seria ótimo ter um arquivo consolidado com todas as transcrições de cada curso. Isso permitiria aos alunos ter uma visão geral do conteúdo do curso em formato de texto e seria útil como uma espécie de apostila.

Com essa funcionalidade, os alunos poderiam revisar o conteúdo do curso com mais facilidade e ter uma referência escrita do que foi aprendido em cada aula. Além disso, seria uma ótima opção para quem prefere ler ao invés de assistir aulas de vídeo.

Acredito que não seria uma implementação extremamente difícil, visto que as transcrições já estão todas lá. 

De inicio, não precisaria ser muito robusto, talvez uma aba ao final do curso contento todas as transcrições do curso agrupadas já seria fenomenal.

**Comment by giovana-armidoro** [comment]
oii Anderson valeu pela sugestão!

faz sentido, essa é uma sugestão bem legal, temos planos futuros de melhorar a tela de aula e quando a gente pegar isso vamos discutir a possibilidade de implementar algo assim, beleza?

por hora, você pode usar a busca que fica na tela de aula para encontrar e rever os conceitos com mais facilidade

abraços e bons estudos! :)

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, mas podem voltar a comentar se quiserem :)
