### ISSUE TITLE
Marcadores de minutagem com link

### ISSUE THREAD

**Issue by noobandrew** [caelum/alura-funcionalidades#772]
Como todos sabem, a Alura possui ótimas transcrições com as respectivas minutagens marcadas abaixo de cada vídeo. Minha sugestão é só um upgrade dessa funcionalidade, fazendo com que essas minutagens tornem-se clicáveis, como as que temos na descrição ou nos comentários de vídeos no Youtube, em que ao clicar, vamos para o minuto escrito no vídeo em questão.

**Comment by giovana-armidoro** [comment]
oii Andrew, muito obrigada pela sugestão!

bem legal a sua proposta, a [issue anterior](https://github.com/caelum/alura-funcionalidades/issues/771) também trouxe uma sugestão de melhoria para a transcrição das aulas e, assim como eu comentei ali, temos planos de melhorar a tela de aula e, assim que a gente pegar isso, vamos discutir a possibilidade de implementar essas melhorias na transcrição, ok?

não tenho uma prazo para dar, mas qualquer atualização aviso vocês por aqui

abraços e bons estudos! :)

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, mas podem voltar a comentar se quiserem :)
