### ISSUE TITLE
QRCODE ou link de validação do curso individual e impressão dupla página

### ISSUE THREAD

**Issue by talentgc** [caelum/alura-funcionalidades#773]
1) Os certificados deveriam ter um QRCode ou link de validação por certificado (individual) . Dessa forma, terceiros poderão validar a veracidade do curso.
2) Os certificados não permitem impressão dos dois lados simultaneamente. Seria interessante ao clicar em imprimir vir frente-verso da página para impressão, junto com o lik ou QRCode de validação individual por curso concluído.

**Comment by guilhermelombardi** [comment]
Olá, tudo bem? Valeu pela sugestão!

Sobre o ponto 1: ao acessar o certificado, você tem algumas opções de compartilhamento, dentre elas, temos a opção de "copiar link" - onde terceiros podem ter acesso ao seu certificado, com a validação individual. De qualquer forma acrescentar o QRCode me parece uma boa ideia também.

Do ponto 2: vou levar a sugestão pro time e entender a viabilidade técnica.

Por hora, não conseguimos passar um prazo pra retorno.

Espero ter ajudado!
Abraços e bons estudos. :)

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, mas podem voltar a comentar se quiserem :)
