### ISSUE TITLE
Legenda e acessibilidade

### ISSUE THREAD

**Issue by gagura** [caelum/alura-funcionalidades#774]
Tenho dificuldades no processamento auditivo e neste curso "Japa Polimorfismo: entenda herança  e interfaces." ficou ainda pior", na maioria dos cursos estou ouvindo as aulas repetidas vezes para certificar a audição, porém a cada troca de professor tenho muita dificuldade novamente em ouvir ou entender, mesmo com fones com cancelamento de ruído  e colocando na velocidade que meu cérebro TDAH capta informações melhor, que já são parte dos meus meios de acomodações. 

Não entendo o porque da falta de acessibilidade em muitos dos vídeos, alguns cursos tem leganda, outros mesmo com anos de existência, não. A transcrição é uma aliada, com certeza, mas em vídeos que o instrutor está  ativamente mostrando exemplos e ensinando códigos fica inviável ler transcrição e acompanhar o vídeo  ao mesmo tempo e acaba sendo um trabalho dobrado/triplicado para captar os ensinamentos.

Mesmo quando é auto gerada, ter a opção de ligar a legenda é extremamente útil para algumas pessoas com imparidades auditivas ou do neurodesenvolvimento poderem acompanhar os cursos com maior tranquilidade, menos ansiedade e ter mais fácil entendimento.

Agradeço desde já!

**Comment by guilhermelombardi** [comment]
Oi @gagura, tudo bem?
Entendemos muito o que você comentou, nós estamos buscando sempre deixar a plataforma mais acessível, antigamente os cursos eram lançados sem transcrição, buscamos melhorar nossos processos e isso hoje já não acontece mais.

Sobre as legendas, a falta delas sempre foi algo que também nos incomodou, e de um tempo pra cá começamos a investir energia nisso, o cenário ideal são que todos os cursos tenham legendas, sabemos que ainda estamos longe mas caminhando forte nesse sentido.

se tiver mais alguma dúvida ou sugestão, estamos aqui :)

abraços e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, mas podem voltar a comentar se quiserem :)
