### ISSUE TITLE
Opacidade na descrição de resposta correta nas tarefas

### ISSUE THREAD

**Issue by rsramos1** [caelum/alura-funcionalidades#776]
Em alguns monitores de baixa qualidade de imagem (ou também imagino que seja um caso para quem tem baixa visão) a descrição da resposta correta se torna quase ilegível por conta da opacidade.
Observei que existe uma chamada no css que muda essa opacidade:

.alternativeList-item--active .alternativeList-item-alternative {
    opacity: .5;
}

minha sugestão é ter ao menos um hover que torne a opacidade mais forte, ou então não reduzir a opacidade.

**Comment by guilhermelombardi** [comment]
oi @rsramos1, tudo bem?
agradecemos sua sugestão, nós já tínhamos identificado esse problema, vamos retirar a opacidade.
por hora não consigo te passar um prazo do ajuste implementado, ok?

abraços e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, mas podem voltar a comentar se quiserem :)
