### ISSUE TITLE
Melhorias para telas de curso e fórum

### ISSUE THREAD

**Issue by alexandreJazara** [caelum/alura-funcionalidades#777]
Eu sei que é muito complicado manter tantas aulas em dia, mas a própria comunidade pode ajudar com estes detalhes, então por que não ter um espaço com cada aula para postagem dos alunos, servindo para documentação e correção de erro.

Na hotmart tenho um curso que faço lá e cada aula tem este recurso e por vezes a aula está defasada em algum detalhes e tanto os organizadores colocam anotações importantes, quanto os alunos perguntam e ajudam em solucionar o que é muito mais eficiente que "1 milhão de posts" sobre o mesmo assunto/dúvida.

Falando em fórum, também senti falta da opção de excluir postagem, fiz um post e depois achei as respostas e não tinha como apagar, acabei reeditando com minhas soluções.

Contexto das idéias:

"Estou dando continuidade na aula sobre electron

https://cursos.alura.com.br/course/electron/task/25535

Mas esta é a segunda aula que pede para abrir nova janela, porém pelo que parece ela está bem desatualizada e seguindo os passos de instalação ele baixa a versão recente de tudo.

Isso causa uma série de erros, incluindo não abrir a sub janela sobre.

Eu acredito que deveria ter uma anotação na aula informando que o sistema funciona diferente, fui buscar uma solução no fórum e tem um monte de material sobre o mesmo erro, o que não é interessante para a credibilidade da Alura, no meu ponto de vista.

Eu acredito que deveria ter um botão em cada aula para notificar o erro, ou para ter um espaço para que alunos tirem dúvidas, mesmo que sejam outros respondendo, isso daria uma atualização melhor ao curso até que ele possa ser atualizado/regravado.

Veja que no main.js para funcionar o ipcMain precisa colocar estas informações

   let mainWindow = new BrowserWindow({

        width: 600,

        height: 400,

        webPreferences: {

            nodeIntegration: true,

            contextIsolation: false,

            enableRemoteModule: true,

        }

        });

Já que os navegadores agora obrigam a ter um nível de segurança, o Chrome não abre mais links sem ssl, então imagina isso. Na própria documentação do Electron fala sobre isso, porém o tempo todo relacionado a links externos, o que para nós iniciantes é algo complicado.

No arquivo render.js temos outro problema, a função de click da aula não funciona, mas se você chamar via function ele abre...

NÃO FUNCIONA

let linkSobre = document.querySelector('#link-sobre');

linkSobre.addEventListener('click', function() {

    ipcRenderer.send('abrir-janela-sobre');

});

FUNCIONA

function openWin(){

    ipcRenderer.send('abrir-janela-sobre');

}

No index eu usei assim:

<a href="#" id="link-sobre">Sobre 1</a>

<a href="#" id="link-sobre2" onclick="openWin()">Sobre 2</a>

Só o "sobre 2" funciona."

**Comment by guilhermelombardi** [comment]
Oi @alexandreJazara, tudo bem?
Muito obrigado pelas sugestões.

Em relação a manter as aulas atualizadas, nós temos feito um trabalho árduo de acompanhamento de cursos já lançados, tanto para atualização de algumas aulas/revisões pontuais de algum tópico, podendo os cursos serem eles regravados por inteiros, em muitos casos onde notamos que o curso ficou desatualizado e já não faz mas sentido pro momento atual do mercado, eles são até mesmos retirados, claro que ainda temos muita margem para melhoria nesse sentido, e gostamos muito da ideia de ter a comunidade colaborando pro nosso ecossistema.

Em relação ao fórum, fui buscar respostas do porque não conseguimos deletar um tópico (até o motivo de ter demorado uns dias pra responder sua sugestão), mas basicamente os tópicos/respostas/interações do fórum impactam em diversas outras coisas na plataforma - uma delas é nosso sistema de pontos por exemplo - então é algo que hoje, inviabiliza a exclusão de tópicos. Por hora, está fora do nosso radar fazer alguma ação nesse sentido, mas nada que não possamos repensar num futuro.

Esperto ter esclarecido, se tiver mais sugestões, é só enviar.

Abraços e bons estudos! :)

**Comment by alexandreJazara** [comment]
Ok, obrigado e espero que as coisas se encaixem e que algo que disse possa
contribuir

Em ter, 28 de fev de 2023 18:49, Guilherme Lombardi <
***@***.***> escreveu:

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, mas podem voltar a comentar se quiserem :)
