### ISSUE TITLE
Botão Salvar

### ISSUE THREAD

**Issue by luyum** [caelum/alura-funcionalidades#778]
Olá, enquanto estudo e acompanho os vídeos, eu sinto a necessidade de termos um botão "Salvar" vídeo para ver mais tarde.. as vezes, vemos algum ponto muito importante que teremos que relembrar no futuro para implementar em nossas programações, e seria muito bom ter um repositório pessoal na Alura com os atalhos para os vídeos que marquei para ver mais tarde! 
Se houvessem tags atreladas a esses vídeos então, seria show de bola!

**Comment by guilhermelombardi** [comment]
oi @luyum , tudo bem?
muito obrigado pela sugestão.
me parece ser uma feature com relevância.
eu vou levar sua sugestão pro time pra gente entender a viabilidade técnica, mas não consigo te passar um prazo pra retorno, tudo bem?

abraços e bons estudos! :)

**Comment by guilhermelombardi** [comment]
oi @luyum estava pensando na sua sugestão de feature, e talvez pra resolver momentaneamente sua necessidade, o plugin [GetPocket](https://getpocket.com/pt/) pode ser útil pra você, por lá você consegue salvar links dos vídeos, colocar tags, etc.
Claro que está longe do ideal mas pode ser que facilite seus estudos.

**Comment by luyum** [comment]
Eba! Que legal Guilherme, vou testar este plugin

Obrigada pelo retorno e fico muito feliz em poder fazer sugestões para
Alura, que eu amo tanto e me ajuda tanto no meu aprendizado! Valeu!!

Em ter., 28 de fev. de 2023 às 16:13, Guilherme Lombardi <
***@***.***> escreveu:

**Comment by guilhermelombardi** [comment]
poxa, legal luciana! :)
espero ter ajudado.
nós ficamos muito felizes também quando as alunas e alunos trazem sugestões e ideias pra gente.

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, mas podem voltar a comentar se quiserem :)
