### ISSUE TITLE
Confirmação de "avanço" de atividade.

### ISSUE THREAD

**Issue by FerriLucas** [caelum/alura-funcionalidades#779]
Quando estamos respondendo uma atividade de forma dissertativa e ao finalizarmos a digitação de nossa resposta e avançarmos para a "próxima atividade", caso não tenha confirmado o envio da resposta, exibir um alerta de confirmação, para que não avance para a "próxima atividade" sem ter de fato "salvo"/enviado sua resposta!
Eu pessoalmente, após formulado e digitado toda minha resposta, já avancei para a próxima atividade sem ter enviado e salvo de fato ela. Necessitando retornar para a atividade anterior, retomar toda a linha de raciocínio e formular novamente a resposta.
Intuitivamente avançamos para a próxima atividade ao finalizarmos nossa resposta e não nos atentamos quanto a necessidade de "salvar" a mesma antes.
Por favor. Desde já, agradeço!

**Comment by guilhermelombardi** [comment]
oi @FerriLucas, tudo bem?
muito obrigado pela sugestão.
realmente me parece ser uma feature relevante, fez bastante sentido pra mim o exemplo que você comentou.
eu vou levar essa questão pro time pra gente entender a viabilidade técnica, mas não consigo te passar um prazo pra implementação, tudo bem?

abraços e bons estudos! :)

**Comment by guilhermelombardi** [comment]
oi @FerriLucas, vc lembra qual(is) curso(s) você fez com esse tipo de exercício com resposta aberta?

obrigado.

**Comment by masromao** [comment]
Pessoal, fechando a issue,  mas podem voltar a comentar se quiserem :)
