### ISSUE TITLE
Guia de Empresas

### ISSUE THREAD

**Issue by maisamaximo** [caelum/alura-funcionalidades#78]
Eu, como aluna, sinto falta de conseguir buscar no perfil o guia de empresas. Inclusive poderiam fazer os cursos de guia de empresa como uma formação. Mais fácil de acompanhar no seu dashboard se você tem o foco de entrar em determinada empresa.

O Guia de empresas só aparece quando não estou logada na conta. Caso contrario ele não aparece de forma alguma (nem por busca, nem no footer nem nada)

**Comment by designernatan** [comment]
oi @maisamaximo valeu pela sugestão!

de fato é um fluxo estranho hoje, passei isso para o time daqui da Alura, ok?

abcs e bom feriado!
