### ISSUE TITLE
Funcionalidade: CONFIRMAR ou RESPONDER nos questionários.

### ISSUE THREAD

**Issue by Helaniajesus** [caelum/alura-funcionalidades#780]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.
Funcionalidade: CONFIRMAR ou RESPONDER nos questionários.
Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.
Quando clicamos em uma alternativa nos questionários já seleciona como se fosse a resposta, as vezes só queremos copiar o código para testar antes e acaba selecionando, também já aconteceu por várias vezes de clicar sem querer e acaba sendo a alternativa errada, poderia colocar uma opção de confirmar resposta para evitar esse tipo de erro, assim confirmamos se é aquela resposta mesmo que queremos marcar.

**Comment by Helaniajesus** [comment]
é uma sujestão, não sei se alguem já reclamou disso.

**Comment by andradeisadora** [comment]
oi @Helaniajesus 
obrigada pela sugestão! faz todo sentido.. vou deixar anotado aqui pra conversarmos sobre mas não posso te confirmar nada nem dar prazo ta?

abraço e bons estudos :)

**Comment by masromao** [comment]
Pessoal, fechando a issue,  mas podem voltar a comentar se quiserem :)
