### ISSUE TITLE
Inserção do gitlab para vitrine dev

### ISSUE THREAD

**Issue by brogliato** [caelum/alura-funcionalidades#781]
Acharia interessante ter também o gitLab na vitrine dev, pois algumas empresas também  o utilizam como repositório

**Comment by andradeisadora** [comment]
oi @brogliato 
obrigada pela sugestão :)
no momento não estamos com planos pra fazer algo assim na vitrine, mas vou deixar anotada tua sugestão

abraço e bons estudos!

**Comment by masromao** [comment]
Pessoal, fechando a issue,  mas podem voltar a comentar se quiserem :)
