### ISSUE TITLE
Falta o modo Dark

### ISSUE THREAD

**Issue by larisrcha** [caelum/alura-funcionalidades#782]
Boa tarde. 

Sou PCD, tenho baixa visão, sinto falta da opção **modo noturno** na plataforma (exceto nas salas de aula que tem a opção). Peçam uma "diquinha" ao professor **Natan Souza** (_ele manda bem demais!_). No modo claro acaba cansando minha visão muito rapidamente, dói meus olhos, os textos acabam se fundindo com o fundo branco e é estressante ao ponto de dar dor de cabeça. Tenho ceratocone, monocular, astigmatismo, miopia e por ai vai (_pacote completo kkkk_), tenho essa sensibilidade maior, se quiserem opiniões após aplicação do modo noturno eu vou estar disponível.

**Comment by larisrcha** [comment]
Obs.: Acabei de ver que já tem um requerimento sobre o modo noturno, é exatamente o que ele falou. Espero que consigam trazer essa ferramenta em breve.

**Comment by andradeisadora** [comment]
oi @larisrcha 
obrigada pela sugestão!
estamos com planos de trazer o dark mode pra outras páginas também :D mas não tenho prazo pra te passar 
enquanto isso, o Natan fala um pouco sobre o [dark mode aqui](https://github.com/caelum/alura-funcionalidades/issues/116#issuecomment-611513554)

abraço e bons estudos!

**Comment by masromao** [comment]
Pessoal, fechando a issue,  mas podem voltar a comentar se quiserem :)
