### ISSUE TITLE
Certificado de Formação Formal

### ISSUE THREAD

**Issue by nestorsquiba** [caelum/alura-funcionalidades#783]
Olá! Tudo bem?

Seria ótimo se conseguíssemos baixar e imprimir as nossas formações em modelo formal, no momento infelizmente o modelo formal só está disponível para cursos concluídos, mas não para formações concluídas.

O modelo formal é ótimo pois além de gastar menos tinta para expormos nossas formações também deixa todas as informações necessárias em apenas uma folha, já o modelo normal é dividido em duas folhas, o conteúdo fica "escondido" e cá entre nós, gasta bastante tinta, especialmente para os que tem muita formações concluídas XD

Seria um prazer se atendessem esse pedido! Um abraço, vocês são demais!

**Comment by andradeisadora** [comment]
oi @nestorsquiba 
faz sentido sim termos um certificado formal pras formações, obrigada pela sugestão!
vou levar a ideia pro time pra conversarmos sobre, mas sem prazo, ta?

abraço e bons estudos :)

**Comment by masromao** [comment]
Pessoal, fechando a issue,  mas podem voltar a comentar se quiserem :)

**Comment by masromao** [comment]
Pessoal, fechando a issue,  mas podem voltar a comentar se quiserem :)
