### ISSUE TITLE
Indicação de resposta correta

### ISSUE THREAD

**Issue by mayaracaldas** [caelum/alura-funcionalidades#784]
Atualmente, quando respondemos uma tarefa do curso, se escolhemos a resposta incorreta ela fica vermelha e não temos mais a opção de clicar. Porém, não há nenhuma indicação de qual seria a resposta correta. É necessário clicar em cada "olhinho" para ler todo o comentário do instrutor e descobrir qual era a correta. Algumas vezes, mesmo lendo a descrição, é difícil ter certeza de que era aquela resposta mesmo a correta.

Gostaria de sugerir que a resposta correta (que não foi assinalada pelo aluno), tivesse algum destaque diferente, como um outline verde na resposta correta, assim fica rápido de identificar e assimilar o que erramos.

Fiz um exemplo simples do que quis dizer em imagem:
![sugestao](https://user-images.githubusercontent.com/15111360/224582129-2a9272f7-066b-4e07-884a-5420455209a3.jpg)

Obrigada!

**Comment by andradeisadora** [comment]
oi @mayaracaldas 
faz sentido mesmo deixar a resposta correta mais destacada, obrigada pela sugestão!
vou levar pro time pra conversarmos sobre a sua sugestão, mas não posso te prometer prazo ta?

abraço e bons estudos :)

**Comment by masromao** [comment]
Pessoal, fechando a issue,  mas podem voltar a comentar se quiserem :)
