### ISSUE TITLE
Reprodução automática

### ISSUE THREAD

**Issue by danielpossebon** [caelum/alura-funcionalidades#785]
Ao invés de ter que clicar no botão para o próximo vídeo, pular automaticamente para o próximo tópico do curso/vídeo após 5 segundos do término do vídeo anterior.
Eu gosto de assistir os vídeos em tela cheia e tenho que ficar saindo desse modo para avançar com o curso.

**Comment by andradeisadora** [comment]
oi @danielpossebon 
hoje o próximo vídeo já carrega em 7 segundos

![image](https://user-images.githubusercontent.com/84100505/225638403-4fc946a3-8e12-4502-8265-e5ed0c658d9c.png)

você pode me dar mais detalhes de como está aparecendo pra você?

**Comment by danielpossebon** [comment]
Ola Isadora tudo bem?
Não notei isso no Chrome do Mac, vou ver novamente e te retorno.

Obrigado pelo retorno!!

Em qui., 16 de mar. de 2023 às 10:53, andradeisadora <
***@***.***> escreveu:

**Comment by masromao** [comment]
Pessoal, fechando a issue,  mas podem voltar a comentar se quiserem :)
