### ISSUE TITLE
[BUG] Forum mobile

### ISSUE THREAD

**Issue by diogo2m** [caelum/alura-funcionalidades#786]
Opa devs, tudo jóia?

Estou enfrentando problemas frequentes na tentativa de responder fóruns pelo aplicativo mobile. Em certo momento a tela trava, não consigo scrollar, nem editar o texto, voltar, nem dar refresh(dá pra ver que a pagina é recarregada  pela barra de loading, porém a pagina continua travada). A única solução é sair do fórum, abri-lo novamente e digitar tudo de novo.

**Comment by laiscavalcanti** [comment]
Oi, Diogo, tudo bem?

Fiz uns testes aqui no app do alura e não obtive problemas. As vezes pode ser limpeza de cache do app, memória ram muito cheia do celular. Tenta ver esses postos e testar novamente para vê se melhora e nos fala se deu certo.

**Comment by masromao** [comment]
Pessoal, fechando a issue,  mas podem voltar a comentar se quiserem :)
