### ISSUE TITLE
Faltam opções para fechar o Pop UP "Incluir novo passo" na página de Plano de Estudos

### ISSUE THREAD

**Issue by i-otsuka** [caelum/alura-funcionalidades#787]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

Olá!

Sou Isac, 
Faltam opções para fechar a janela pop-up "Incluir novo passo" na página de  criação e edição do "Plano de Estudos".
Não aparece nenhum botão  [fechar] [x] para fechar a janela pop-up e nem a opção de clicar fora da janela fecha o pop-up.
A única forma de fechar a janela é teclar ESC.

![image](https://user-images.githubusercontent.com/97365076/226203172-1719b6bc-b617-41b0-8338-0dc5d65c4a80.png)

Fica o apontamento e pedido!

**Comment by laiscavalcanti** [comment]
Oi, Isac, tudo bem?

Legal essa sua sugestão, bem apontado. Vou levar para o time e avaliarmos a sua sugestão.
Obrigada

**Comment by masromao** [comment]
Pessoal, fechando a issue,  mas podem voltar a comentar se quiserem :)
