### ISSUE TITLE
Exportação em massa de certificados selecionados

### ISSUE THREAD

**Issue by psjjonathan** [caelum/alura-funcionalidades#788]
A criação de uma funcionalidade para exportar certificados em massa mas de forma seleta pelo usuário seria bom.

Sugiro a adição de um botão para realizar uma exportação na tela de "perfil e certificados" na sessão de "certificados". A funcionalidade seria uma melhora da funcionalidade já existente no canto inferior esquerdo, como na imagem abaixo, em "Você pode encontrar um certificado completo **aqui**". 

![image](https://user-images.githubusercontent.com/38404158/227411799-b2d7cdff-d101-48d9-8aab-65deffcc1be5.png)

Ao entrar nesta função o usuário deveria selecionar, através de checkbox, quais certificados ele gostaria de incluir no export. Se possível, a funcionalidade poderia dar a opção de realizar uma exportação assim como temos atualmente na funcionalidade supracitada, onde são citados todos os certificados em uma mesma página, mas também permitir que o usuário receba cada certificado separadamente, se assim for seu desejo.

Enquanto Product Designer acho que essa funcionalidade seria útil para diversos usuários e, enquanto usuário sei que me seria útil para que assim eu pudesse exportar apenas os certificados gerados dentro de um certo período de tempo para que a minha faculdade aceite como horas extra curriculares.

**Comment by laiscavalcanti** [comment]
Oi, Jonathan, tudo bem?

Legal essa sua ideia, pode trazer mais agilidade para quem quer baixar vários certificados ao mesmo tempo. Vou levar para o time e iremos estudar essa possibilidade.

Obrigada por nos trazer a ideia.

**Comment by masromao** [comment]
Pessoal, fechando a issue,  mas podem voltar a comentar se quiserem :)
