### ISSUE TITLE
Opção de marcar video aula ou tarefa como não vista/respondida 

### ISSUE THREAD

**Issue by RomuloKennedy** [caelum/alura-funcionalidades#789]
Várias vezes já cliquei sem querer pra avançar pro próximo video e simplesmente não tem como " desver " o conteúdo kkk, também seria interessante uma opção de poder responder as questões já respondidas sem ver as respostas com o intuito de praticar o conteúdo visto novamente (lógico que teria que zerar o xp das questões).

**Comment by laiscavalcanti** [comment]
Oi, Romulo, tudo bem?

Esse ponto vem de resetar aulas e exercícios tem sido debatido aqui pelo nosso time. Mas é algo que precisamos analisar com tempo.

Obrigada pela sugestão

**Comment by masromao** [comment]
Pessoal, fechando a issue,  mas podem voltar a comentar se quiserem :)
