### ISSUE TITLE
Alura - HipsTers - aplicar ordem crescente e decrescente -  filtros 

### ISSUE THREAD

**Issue by Ssds2006** [caelum/alura-funcionalidades#790]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

Olá boa tarde! 

A funcionalidade que eu acredito ser muito útil para o podcats é colocar uma opção para colocar em ordem crescente ou decrescente a lista  ... tenho vontade de ouvir os primeiros podcats  que foram lançados pela Alura porém são muitos . o último que foi lançado é #350 -  se fosse possível colocar em ordem crescente e decrescente ajudaria muito.  

Seria uma ótima ideia colocar também filtro de podcast igual o de cursos - programação (php/ java/ c# e etc) - font-end (HTML-CSS e etc) ou até mesmo filtro por palavras chaves. 

Seria uma ótima ideia também mostrar qual o último podcast que a pessoa ouviu - igual do cursos . onde apresenta o nome do curso e continuar onde parou - acho muito valido para o podcast também

E se possível adaptar também para o mobile - gosto de ouvir podcast quando estou no ônibus, carro, trem e etc. 

Mas senti dificuldades em utilizar essa plataforma da alura!

**Comment by laiscavalcanti** [comment]
Oi, Sara, tudo bem?

Esse apontamento é bem interessante, de fato, mas, pra agora,  no campo de busca se você por o número do podcast, como #001 ou #012, você terá o resultado esperado.

A ideia das tags é interessante também pois ajudaria mais a filtrar, como você disse, e achar conteúdos por tema.

Sobre mostrar os eps já ouvidos precisaria estar atrelado uma conta, assim como acontece na netflix, e nesse caso, o acesso independe de uma conta na alura.


Sobre adaptação ao celular, eu testei e consegui usar. O que exatamente não tá dando certo no celular?

**Comment by Ssds2006** [comment]
![WhatsApp Image 2023-04-04 at 16 47 09](https://user-images.githubusercontent.com/91677917/229903469-21e2b92d-66ba-4ede-a0c4-099e6bb2d4c1.jpeg)

 Olá boa tarde novamente!

então falo de uma barra de pesquisa aqui não tem... fica um pouco sem recursos para a busca! Até uma pessoa perceber que é para usar a barra de pesquisa na tela da AluraFlix serve para pesquisar qualquer arquivo ela já desistiu de assistir ou ouvir qualquer coisa.... perdão pelo meu modo de falar... mas foi uma expressão que eu consegui descrever melhor a situação.



![WhatsApp Image 2023-04-04 at 16 50 12](https://user-images.githubusercontent.com/91677917/229904981-1c404896-f6f0-474b-955f-e361d529216f.jpeg)

**Comment by designernatan** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
