### ISSUE TITLE
Avisar curso concluído

### ISSUE THREAD

**Issue by FernandoLink** [caelum/alura-funcionalidades#791]
Quanto um curso ou formação que você já finalizou foi atualizado, receber um email.

**Comment by artnicodemus** [comment]
Oi Fernando, tudo bom?

Quando uma formação é atualizada, é mostrado um aviso no topo do dashboard com algumas opções de ação.
Quanto aos cursos, nós não realizamos avisos de atualização pois geraria spam (pequenas alterações acontecem com frequência nos cursos).

Abraços e bons estudos!

**Comment by masromao** [comment]
Pessoal, fechando a issue,  mas podem voltar a comentar se quiserem :)
