### ISSUE TITLE
Indicar sequência cronológica de cursos e formações

### ISSUE THREAD

**Issue by AshileySabah** [caelum/alura-funcionalidades#792]
Quando vou estudar uma nova tecnologia, tem várias formações e cursos dessa tecnologia, mas não é indicado por qual curso de formação começar.

**Comment by artnicodemus** [comment]
Oi Ashiley, tudo bom?

Falando das formações em si, nós já organizamos os cursos dentro delas numa cronologia que faz sentido, então pode realizar os cursos na sequencia que a formação mostra!

Outro detalhe é que quando uma formação/curso precisa de conhecimento prévio para ser realizada, é mostrado um card de "pré-requisitos" na página do conteúdo, onde mostramos qual outra formação/curso você precisa estudar antes. Vou por aqui prints pra ficar mais claro:

- Quando uma Formação tem pré-requisito
![image](https://user-images.githubusercontent.com/114259460/230957070-d646bc77-ea91-4fa2-be4d-a7cc9d68cd17.png)

- Quando um Curso tem pré-requisito:
![image](https://user-images.githubusercontent.com/114259460/230957230-adff5c6e-f4c3-480d-832e-6811a39437c1.png)

Esperto ter ajudado, vou manter a issue aberta pra caso você tenha mais dúvidas.
Bons estudos!

**Comment by designernatan** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
