### ISSUE TITLE
Botão de voltar para dashboard na tela de vídeo

### ISSUE THREAD

**Issue by AshileySabah** [caelum/alura-funcionalidades#793]
Falta um botão de voltar para o dashboard quando estamos assistindo a um curso. É muito chato ter que voltar pro dash pela url...

**Comment by artnicodemus** [comment]
Oi Ashiley, tudo bom?

Na tela de aula ao assistir um curso, temos um botão para voltar ao dashboard, fica na parte de baixo da sidebar:
![image](https://user-images.githubusercontent.com/114259460/230961046-814ec093-8958-49ea-a15b-b2e746290643.png)

Abraços e bons estudos!

**Comment by designernatan** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
