### ISSUE TITLE
pontuações nos artigos

### ISSUE THREAD

**Issue by madukisp** [caelum/alura-funcionalidades#794]
Sugiro que no final dos artigos fosse colocado algumas perguntas sobre o artigo como nos exercícios dos cursos, e essas respostas valessem pontos como nos exercícios dos cursos.
Dessa forma, faz com que o aluno compreenda se entendeu mesmo o que leu.
Eu mesma começo lendo prestando bastante atenção mas em alguns momentos acabo perdendo o foco e preciso reler algumas coisas.

**Comment by artnicodemus** [comment]
Oi @madukisp , tudo bom? 

Muito obrigado pela sugestão!
A ideia é que tentamos focar a aplicação de exercícios no momento da aula, dentro da plataforma.
Mas iremos levar sua sugestão para análise quando acontecer algum projeto envolvendo os artigos.

Abraços e bons estudos!

**Comment by designernatan** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
