### ISSUE TITLE
Problema ao adicionar cursos ao plano de estudo (mobile)

### ISSUE THREAD

**Issue by gabrielgiordana** [caelum/alura-funcionalidades#795]
Não consigo editar meu plano de estudos no celular. Ao clicar em "adicionar novo passo" eu consigo escolher facilmente os itens que eu pretendo adicionar ao meu plano de estudos. Porém, não é possível fechar essa pop-up de busca, seja clicando fora dela ou até mesmo clicando em algum ícone pra fechar essa janela. Sendo assim, sou obrigado a voltar à página anterior e a página é recarregada, qualquer alteração que eu fiz não é salva. Assim, é impossível alterar meu plano de estudos.

**Comment by artnicodemus** [comment]
Oi @gabrielgiordana , tudo bom?

Tentei reproduzir esse bug aqui no meu celular, porém está funcionando.
Pode me falar qual é o modelo do seu celular e o browser utilizado? Assim conseguimos analisar melhor por aqui!
Também é interessante tentar já testar em outro browser no seu celular.

**Comment by gabrielgiordana** [comment]
Olá! Meu celular é um Samsung Galaxy S20FE (modelo SM-G780G/DS)

Meu navegador é o Google Chrome. Eu não lembro se eu anexei um vídeo
demonstrando o bug. Caso não tenha anexado, esse é o bug:

https://drive.google.com/file/d/1haXzItjT25qiPtKJv5uc86n6bgPWT7Hm/view?usp=drivesdk



Em seg., 10 de abr. de 2023 17:09, Arthur Nicodemus <
***@***.***> escreveu:

**Comment by artnicodemus** [comment]
No vídeo que você mandou não consegui visualizar o modal de buscar conteúdos que você havia comentado, será se mandou a gravação errada?

Estava simulando com o seu modelo de celular e ficou assim pra mim:
![image](https://user-images.githubusercontent.com/114259460/231267184-9c69e021-ef45-44fe-96d1-3c51e1488512.png)
Ambos botão de fechar e salvar alterações do plano estão aparecendo.

Reparei na sua gravação que você estava tentando usar o drag'n'drop dos conteúdos do plano (ícone de 6 pontinhos) para alterar a ordem. Essa funcionalidade de arrastar infelizmente não funciona em celulares ):

**Comment by gabrielgiordana** [comment]
Eu enviei a gravação errada, esse é outro bug que eu também gravei. Essa é
a gravação do problema em em questão:

https://drive.google.com/file/d/1hXcYWc4XQnxZaqcY85hvMsIuzobpiFLf/view?usp=drivesdk

Esse ícone de fechar que você circulou não aparece pra mim

Em ter., 11 de abr. de 2023 16:24, Arthur Nicodemus <
***@***.***> escreveu:

**Comment by artnicodemus** [comment]
Agora entendi!
Conversei com uma pessoa do dev e aparentemente esse bug foi ajustado recentemente. Poderia por gentileza testar se ainda ocorre? É interessante limpar o cache da página também.

**Comment by gabrielgiordana** [comment]
Sim! O "X" agora apareceu pra mim, testei e tá tudo funcionando como
deveria. Muito obrigado pelo suporte!

Em ter., 11 de abr. de 2023 18:16, Arthur Nicodemus <
***@***.***> escreveu:

**Comment by designernatan** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
