### ISSUE TITLE
botão 'apagar' quando editar Tópico em fórum

### ISSUE THREAD

**Issue by nobregao** [caelum/alura-funcionalidades#796]
gostaria que fosse possível deletar um tópico quando editado em fórum de perguntas nos cursos.

exemplo de quando fui editar um tópico
![edição de tópico](https://user-images.githubusercontent.com/8739782/229517122-610df383-7c92-4893-950b-b766bf123bf2.png)

**Comment by artnicodemus** [comment]
Oi @renataoalves, tudo bom?

Muito obrigado pela sugestão!
Nós temos o botão de deletar ("Fechar tópico") logo na página anterior, a mesma onde tem o botão de editar:
![image](https://user-images.githubusercontent.com/114259460/231254570-ed4b157c-a240-49a8-b1c6-307b926d30a5.png)

Abraços e bons estudos!

**Comment by nobregao** [comment]
Entendi, porém, não aparece essas opções para mim.

**Comment by artnicodemus** [comment]
Opa, desculpa, erro meu! Acabei me enganando, pois ali no print é a minha visão como administrador.

Nós realmente não temos uma opção para alunos apagarem o tópico. Precisamos analisar aqui do nosso lado possibilidades, quando acontecer algum projeto envolvendo os tópicos iremos levar em consideração sua sugestão! Porém não temos um prazo pra isso.

Muito obrigado e bons estudos!

**Comment by designernatan** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
