### ISSUE TITLE
Configurar a página da alura para modo noturno

### ISSUE THREAD

**Issue by Ssds2006** [caelum/alura-funcionalidades#797]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.
Prezados bom dia, tudo bem?

Sugiro uma configuração da página da alura para o modo noturno!

Acredito que é muito valido essa configuração disponível para os estudantes alura que tenham algum problema de visão e também que não tenham. Caso não seja possível.

Poderia ser mudado para cores não tão claras ... Um tom de cinza onde não agride muito a visão dos estudantes. 

![Captura de tela de 2023-04-03 12-31-00](https://user-images.githubusercontent.com/91677917/229557012-b3738b4e-542b-42d3-bd19-f43b815ac1de.png)

**Comment by artnicodemus** [comment]
Oi @Ssds2006 , tudo bom?

Muito obrigado pela sugestão! O modo noturno é bastante pedido e recentemente analisamos a possibilidade de finalmente implementar ele. Infelizmente não temos um prazo pra passar, pois ainda temos desafios técnicos no caminho.

Uma dica para quebrar galho seria usar a extensão do Chrome "dark reader", que força o dark mode nas páginas. O navegador Opera tem essa opção já nativa.

Abraços e bons estudos!

**Comment by Ssds2006** [comment]
Olá boa tarde tudo bem?

Rsrs então o meu navegador está no modo drack... Mas quando abro a página da alura principal... Ele não consegue fazer isso!

E o navegador opera é meio que proibido o uso no computador da empresa! 

Mas aguardo ansiosamente por esse modo noturno... Muito obrigada!

**Comment by designernatan** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
