### ISSUE TITLE
Notificações e opção seguir

### ISSUE THREAD

**Issue by alienmatias** [caelum/alura-funcionalidades#798]
Eu acho que seria interessante sermos **notificados por e-mail** quando alguma **interação no fórum** fosse respondida. Ter a opção de ativar as notificações das interações de outras pessoas também, que gostaríamos de acompanhar. 

Além disso, por que posts com **mais de duas semanas** não solucionados não podem ser respondidos? Acho que essas coisas **limitam muito o entrosamento entre os alunos**. Mesmo os solucionados, poderia haver a possibilidade de ainda interagir com eles, às vezes queremos discutir o assunto ali abordado, mesmo já tendo havido uma resposta. 

Poderia ter também a opção de **ativar para ser seguido** por outros alunos, já que podemos ter perfil público. Seria legal poder seguir outras pessoas, sem ter que necessariamente buscar nas redes sociais.

**Comment by artnicodemus** [comment]
Opa @alienmatias, tudo bom?
Muito obrigado pelas sugestões!

Hoje já temos a opção deter notificação de tópicos que você está acompanhando. É só clicar neste lugar:
![image](https://user-images.githubusercontent.com/114259460/231263417-d0e18433-2528-428f-91fc-29c8cdfb981c.png)

Quanto ao limite de tempo de respostas nos tópicos, atualmente esse limite é de quatro semanas. Em resumo, já fizemos alguns estudos e o tempo atual é o ideal para evitar os problemas que são [mencionados aqui](https://github.com/caelum/alura-funcionalidades/issues/660#issuecomment-1194333438).
Entendo que há momentos que queremos trocar mais ideias com outras pessoas, por isso que puxamos o Discord exclusivo da Alura onde acontece bastante disso!

Não temos planos pra uma feature de seguir perfis dentro da plataforma mas você pode trocar ideia com o pessoal na comunidade do Discord e adicionar os seus amigos da Alura por lá :)

Abraços e bons estudos!

**Comment by designernatan** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
