### ISSUE TITLE
Modal "Como funciona a pontuação".

### ISSUE THREAD

**Issue by zeemaarciio** [caelum/alura-funcionalidades#799]
Na página de pontuações, ao clicar no link "Como funciona a pontuação" é aberto uma modal explicando o funcionamento das pontuações e não existe um botão "X" para que seja possível fechar a modal.
Só é possível fechar se atualizar a página.

![image](https://user-images.githubusercontent.com/18116845/230237932-256970a3-48e2-46de-be24-d903987a18d7.png)

**Comment by artnicodemus** [comment]
Oi @zeemaarciio , obrigado pela sugestão!

Realmente é um bug, vou encaminhar pra a fila para que possa ser ajustado.
Abraços e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue, pessoal
podem voltar a comentar se quiserem :)
