### ISSUE TITLE
Organizar as atividades no app da mesma forma que são organizadas no site.

### ISSUE THREAD

**Issue by brunagcr** [caelum/alura-funcionalidades#8]
Seria legal se a ordem das atividades do curso no app fosse igual à ordem das atividades no site. Ou seja, intercaladas com o video. As atividades agrupadas, como acontece no app, ficam fora de contexto algumas vezes.

**Comment by taisbatuira** [comment]
Olá @brunagcr , os vídeos e atividades estão separados pois são tratados de formas diferentes: os vídeos podem ser baixados e assistidos offline enquanto os exercícios só podem ser feitos online, por isso estão agrupados. 
Por hora, não temos planos de colocá-los offline, o que impede a alteração da ordem de exibição. Mas vamos manter a sugestão registrada para o futuro ok?
