### ISSUE TITLE
Botão do miniplayer

### ISSUE THREAD

**Issue by mautoz** [caelum/alura-funcionalidades#80]
Olá, gente!
Gostei bastante das novas funcionalidades, entre elas o miniplayer (picture-in-picture), mas acho que faltou consistência na interface. O botão ficou no lugar do Fullscreen, acredito que muitos estão apertando errado toda hora e para quem utiliza o recurso no youtube, tb deve estranahr a posição do botão. Minhas sugestão seria jogar para esquerda e deixar do lado direito das configurações.

**Comment by designernatan** [comment]
oi @mautoz valeu pelo feedback e sugestão!

notamos isso depois de ir pra produção (ops...), semana que vem ou na outra deve subir um fix disso :)

não esqueça de dar upvotes em outras issues aqui no Alura Funcionalidades, ok?

abração e bom carnaval!

**Comment by designernatan** [comment]
avisando por aqui também: time de desenvolvimento da alura inverteu as posições dos botões e agora o PiP está na esquerda e o fullscreen é a ultima opcao no player

![image](https://user-images.githubusercontent.com/5431347/75554204-a0b2aa80-5a18-11ea-9c8d-b5e34f8c0171.png)
