### ISSUE TITLE
Modo escuro.

### ISSUE THREAD

**Issue by kalebzaki4** [caelum/alura-funcionalidades#800]
O modo escuro é uma opção de design que inverte as cores padrão de um site, substituindo o fundo branco e o texto preto por um fundo escuro e o texto claro. Essa funcionalidade tem sido cada vez mais comum em sites e aplicativos, e muitos usuários estão optando por usá-la em suas configurações.

O modo escuro tem se tornado popular por uma série de motivos. Em primeiro lugar, ele é considerado menos agressivo aos olhos, especialmente em ambientes com pouca luz. O brilho excessivo do fundo branco pode causar fadiga visual e até mesmo dor de cabeça, enquanto o fundo escuro é mais suave e agradável aos olhos.

Além disso, o modo escuro pode economizar bateria em dispositivos móveis, uma vez que os pixels pretos requerem menos energia para serem exibidos do que os brancos. Isso pode ser especialmente útil para aqueles que passam muito tempo navegando na web em seus smartphones.

O modo escuro também pode ser útil para aqueles que sofrem de condições médicas que afetam a visão, como a sensibilidade à luz ou a cegueira noturna. Com o modo escuro, o contraste é reduzido, tornando o texto mais legível e a navegação mais fácil.

Por fim, muitos usuários simplesmente preferem o visual do modo escuro, que pode transmitir uma sensação de sofisticação e modernidade. Além disso, em ambientes de trabalho, o modo escuro pode ser mais discreto e menos chamativo, o que pode ser útil para evitar distrações e manter a produtividade.

Em resumo, o modo escuro é uma funcionalidade cada vez mais popular nos sites e aplicativos, oferecendo aos usuários uma alternativa mais suave e agradável aos olhos para o design padrão. Seja por questões de saúde visual, economia de bateria ou preferência estética, o modo escuro é uma ótima opção para aqueles que buscam uma experiência de navegação mais confortável e personalizada.

**Comment by artnicodemus** [comment]
Oi @kalebzaki4 , muito obrigado pela sugestão!

Realmente o darkmode na Alura é algo muito pedido. Recentemente analisamos a possibilidade de implementar darkmode em toda a Alura, mas infelizmente não temos um prazo de quando isso será disponibilizado ):

Uma dica para quebrar galho seria usar a extensão do Chrome "dark reader", que força o dark mode nas páginas. O navegador Opera tem essa opção já nativa.

Abraços e bons estudos!

**Comment by masromao** [comment]
Pessoal, fechando a issue,  mas podem voltar a comentar se quiserem :)
