### ISSUE TITLE
Ícone de fechar modal na listagem de Ranking

### ISSUE THREAD

**Issue by fakefatlu** [caelum/alura-funcionalidades#801]
Olá! 

Segue o breadcrumb do fluxo de navegação que foi encontrado o problema: 

**Perfil e Certificados > no ranking nos últimos 30 dias > Como funciona a pontuação** 

Ao clicar, não possibilita fechar o modal, simplesmente trava na tela. Para sair, é necessário recarregar a página (Para que não tem familiaridade com a tecnologia, isso é muito ruim) ou clicando no botão "esc" do teclado. Aqui temos um problema de usabilidade, já que temos que adivinhar como fechar o Pop-up. Não sei se tem esse tipo de problema em outras parte do site, mas seria interessante verificar.

**Comment by artnicodemus** [comment]
Oi @fakefatlu , tudo bom?
Recentemente respondi sobre esse bug [aqui nessa issue](https://github.com/caelum/alura-funcionalidades/issues/799).
Resumindo, é um bug e em breve será ajustado!

Muito obrigado pela sugestão e bons estudos.

**Comment by andradeisadora** [comment]
vou fechar a issue, pessoal
podem voltar a comentar se quiserem :)
