### ISSUE TITLE
Zerar ou Reiniciar progresso de curso

### ISSUE THREAD

**Issue by Paulo-H-M-Machado** [caelum/alura-funcionalidades#802]
Olá, sou professor da rede estadual de educação,

Gostaria de solicitar um botão para reiniciar o progresso das respostas do curso. O motivo:

Quando eu entro com meu login para trabalhar em sala de aula, especialmente quando estou trabalhando como resolver as questões, eu precisaria de uma forma de enviar e validar a mesma questão para cada turma em que eu for trabalhar por dois motivos: O primeiro é para que os alunos não possam ver as minhas respostas antes de tentarem resolver; O segundo é para eu poder trabalhar e demonstrar em diversas salas de aula como algumas questões tem que ser resolvidas.

Eu trabalho com turmas de oitavo e nono ano, são crianças, eles cometem erros, se frustram com facilidade, caso eu não possa mostrar com calma o passo a passo de resolver cada questão, alguns dos alunos simplesmente desistem de tentar, ao verem as minhas questões já resolvidas, fica um pouco mais complicado, eles vêem como uma injustiça, alguns deles estão aprendendo a mexer no mouse ainda. 

Vejam bem que eu consigo trabalhar em laboratório de informática, em alguns casos, apenas uma ou duas vezes por mês, dependendo da turma, então o pedido pode parecer estranho, mas para mim tenho plena certeza que tornaria muito melhor o andamento das minhas aulas.

Grato,
Paulo Henrique Maia Machado

**Comment by designernatan** [comment]
@Paulo-H-M-Machado valeu pela sugestão!

via de regra, sem planos para implementar algo assim para os alunos (pessoa física, que se matricula diretamente na alura), mas vamos analisar e estudar possíveis alternativas para que no futuro essa experiência na rede estadual seja melhorada

qualquer dúvida ou detalhe a mais, pode mandar diretamente aqui, tudo bem?

abraços
