### ISSUE TITLE
Nota 

### ISSUE THREAD

**Issue by EduFloripa** [caelum/alura-funcionalidades#803]
Poderiam dar a opção de colocar a nota de um curso quando da desistencia do mesmo. Pode acontecer de um curso ser tão ruim que o cliente não consegue nem terminar o curso para dar uma nota.

**Comment by designernatan** [comment]
@EduFloripa valeu pela sugestão!

faz todo sentido algo assim! Em geral ficamos de olho na desistência de cursos

inclusive, se quiser me mandar o(s) curso(s) que você sentiu que não estão legais, já encaminho para o time de conteúdo aqui da alura, ok?

abcs!

**Comment by designernatan** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
