### ISSUE TITLE
Botão para fechar a modal de "Como funciona a pontuação" na tela de  user/id/rank/monthly

### ISSUE THREAD

**Issue by MauricioRFilho** [caelum/alura-funcionalidades#804]
Aparentemente essa modal só é fechada com o botão 'esc', poderia existir a funcionalidade de clicar fora da modal para fechar ou o botão 'x' para fechar.

![image](https://user-images.githubusercontent.com/51759836/232889850-5359fdc3-589c-43eb-9dbe-eb84ef09df41.png)

**Comment by designernatan** [comment]
@MauricioRFilho valeu por reportar o bug! Nao era pra estar assim

quando arrumarmos pingamos aqui

abcs!

**Comment by andradeisadora** [comment]
foi ajustado já :)

vou fechar a issue, pessoal
podem voltar a comentar se quiserem
