### ISSUE TITLE
Disponibilizar na tela um atalho para acessar o proximo curso da minha formação.

### ISSUE THREAD

**Issue by leoneDuarte** [caelum/alura-funcionalidades#805]
Acabei o primeiro curso da formação que to fazendo dai sou redirecionado para meus cursos, porem la tem varios cursos menos o próximo da proxima formação, e se eu ir em minhas formações aparece as que finalizei mas não mostra a que estou fazendo, e mostra mais um monte para escolher. Para achar a formação atual, tenho que praticamente fazer uma varredura no site, ter esse atalho ajudaria muito. PS: Ainda não achei a formação do primeiro curso que fiz kk para dar continuidade

* Poderia também redirecionar automaticamente, assim que avaliamos o curso, poderia ja iniciar o próximo, da formação.

**Comment by masromao** [comment]
Olá @leoneDuarte tudo bem?
Muito obrigado por entrar em contato para falar sobre a sua dificuldade.

Um caminho rápido para conseguir seguir com a sua Formação é acompanhá-la pela sua Dashboard.
Clicando em Dashboard no menu principal da plataforma você chega lá:

![image](https://user-images.githubusercontent.com/86667938/234697306-832427f3-2698-4478-9ca8-fceb9d566133.png)

Uma vez na Dashboard, você pode acompanhar o progresso da sua última Formação do lado direito da tela, em Progresso  em Formação:

![image](https://user-images.githubusercontent.com/86667938/234697489-cf23269a-167a-481b-a5f6-cfc9cb6e33b5.png)

Espero ter conseguido ajudar na sua dúvida. Qualquer dúvida, só comentar aqui!
Abraços e bons estudos : )

**Comment by leoneDuarte** [comment]
Sim, porém se você tiver terminado uma formação recentemente aparece outra coisa nesse local, e não aparece essa informação fica por bastante tempo.

**Comment by masromao** [comment]
Hmm, entendi, você pode por favor enviar um print ou dar mais alguns detalhes pra gente entender melhor o seu problema?

**Comment by leoneDuarte** [comment]
![formaçãoFinalizada](https://user-images.githubusercontent.com/40296852/236870571-78be4d3a-f10f-4e02-9da3-5c1412f492f0.PNG)
Sim segue o exemplo de quando eu termino, eu tenho outra formação em andamento porem ela não aparece no dashboard, fica por um tempo consideravel essa parte de finalização, dai tenho que caçar a outra formação em outras partes do sistema, seria legal se as formações em andamento ficassem ali para escolher qual dar continuidade. Enfim acredito que ajudaria bastante nesses momentos que a tela fica assim.

**Comment by masromao** [comment]
Obrigado pelo envio, @leoneDuarte , entendi seu ponto.
Realmente é uma sugestão muito interessante trazer outras Formações em andamento para visualização rápida na Dashboard.

Com certeza quando formos redesenhar e acrescentar melhorias para a plataforma levaremos em consideração o que você trouxe, mas por enquanto ainda não consigo te passar um prazo de quando iremos priorizar isso.

Muito obrigado novamente pela sugestão.

Abraço e bons estudos : )

**Comment by giovana-armidoro** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
