### ISSUE TITLE
Fechar janela de "como funciona a pontuação".

### ISSUE THREAD

**Issue by fefr7** [caelum/alura-funcionalidades#806]
Após abrir a janela de "como funciona a pontuação" na pagina de ranking, não encontrei nenhum botão na janela para fecha-la, sendo necessário voltar a pagina anterior, poderia existir um potão na janela para fecha-la.

**Comment by masromao** [comment]
@fefr7  Obrigado por nos avisar desse bug, realmente não era pra estar assim.

Vamos levar para o time e priorizar para consertar.

Abraços e bons estudos : )

**Comment by andradeisadora** [comment]
já foi corrigido :)

vou fechar a issue, pessoal
podem voltar a comentar se quiserem
