### ISSUE TITLE
Horas completas na página do perfil

### ISSUE THREAD

**Issue by lbresteves** [caelum/alura-funcionalidades#807]
Na página do perfil gostaria que tivessem dispostas todas as horas estudadas em todos os cursos.

**Comment by masromao** [comment]
Olá @lbresteves , legal essa sugestão de um contador de horas na plataforma.

Vamos estudar a viabilidade de aplicar em futuras atualizações, mas por hora não consigo te passar um prazo para execução, ok?
:)

abcs e bons estudos!

**Comment by designernatan** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
