### ISSUE TITLE
Certificados - Impressão

### ISSUE THREAD

**Issue by Juliana-E-P-Lopes** [caelum/alura-funcionalidades#808]
Conseguir imprimir e/ou baixar em frente e verso os certificados.
Atualmente, para conseguir fazer isso, tenho que salvar e depois ir no "ILovePDF.com" e juntar os arquivos.

**Comment by masromao** [comment]
Olá @Juliana-E-P-Lopes  , obrigado pela sugestão!
Por enquanto a melhor forma de fazer isso é salvar separadamente, uma página de cada vez mesmo e depois juntar os arquivos, como você tem feito.

Vou levar a sugestão pro time para entendermos a viabilidade técnica, mas por hora, não conseguimos passar um prazo pra retorno.

Espero ter ajudado!
Abraços e bons estudos. :)

**Comment by designernatan** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
