### ISSUE TITLE
Ordenação dos Cursos.

### ISSUE THREAD

**Issue by magdeson** [caelum/alura-funcionalidades#809]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.
Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

Exemplo, estou fazendo a formação completa de excel, mas na guia dessa formação mostra todos cursos e vizualmente não para saber por onde começar, tipo do zero ao avançado.
Seria legal se tivesse um ordenação nos cursos por formação, um ordem a seguir.

**Comment by masromao** [comment]
Olá @magdeson , tudo bem?

Obrigado por nos informar dessa dificuldade que você tem passado.

Na nossa página de Formações a disposição dos cursos e conteúdos já está numa ordem que favorece o aprendizado daquele tema, ordenado de cima para baixo, então é só ir seguindo a lista na ordem para aproveitá-lo da melhor forma.

Como nessa imagem de exemplo (a ordem está destacada com a seta roxa e os números):

![image](https://user-images.githubusercontent.com/86667938/234695336-18242802-5586-4b6c-a487-ea1d7faef145.png)

Seguindo a lista de de cima para baixo, no sentido da seta é possível seguir o caminho que desenhamos para essa Formação.

Espero que tenha conseguido te ajudar, mas qualquer coisa, só comentar por aqui!
Abraços e bons estudos : )

**Comment by designernatan** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
