### ISSUE TITLE
Clareza na data de lançamento ou atualização dos Cursos

### ISSUE THREAD

**Issue by william-sobreira** [caelum/alura-funcionalidades#81]
Descreva a funcionalidade que você gostaria que tivesse na plataforma. Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

Colocar dentro do container da class="course-header-headline-info" uma 4ª coluna informando a data de lançamento do curso, ou, data da última atualização do curso. 
Acredito que seria uma "funcionalidade" trivial, mas que acredito que faria total diferença para os alunos da plataforma, uma vez que a Alura é uma plataforma de cursos de tecnologia, sendo que a tecnologia está em constante transformação, ou seja, o que há 2~3 anos era comum, hoje já não é mais usual. Portanto, acredito que, colocando explícita a data de lançamento/atualização faria total diferença para os alunos decidirem se aquele curso condiz com a expectativa de aprendizado para ele(a) no momento de decisão.

**Comment by peas** [comment]
william, no site externo ou interno do aluno? me da um link? eu achava q tinha a ultima atualizacao ja

**Comment by william-sobreira** [comment]
No site interno versão Desktop não aparece a data do curso. Já na versão mobile interna aparece a data da última atualização. 
Na versão externa o mobile não aparece como pode ver na imagem que anexei. E, se não me engano na Desktop externa também não 
(Não anexei a versão Desktop, apenas a mobile)
![Screenshot_20200227-233826](https://user-images.githubusercontent.com/60292132/75505615-7205e700-59ba-11ea-90c9-7e2a70281add.png)
![Screenshot_20200227-233740](https://user-images.githubusercontent.com/60292132/75505621-73cfaa80-59ba-11ea-9835-e886a5990af5.png)

**Comment by peas** [comment]
@william-sobreira obrigado william! fiz o push, entra no ar em um proximo deploy. aparecera abaixo do publico alvo e nivel
