### ISSUE TITLE
Assistir mais tarde os vídeos do Alura+

### ISSUE THREAD

**Issue by RedONe06** [caelum/alura-funcionalidades#810]
Fui escolher alguns vídeos para reforçar alguns conhecimentos e acabei achando alguns materiais legais para assistir de outras matérias. Por isso, acho que seria interessante ter algum tipo de botão/função que permitisse salvar os vídeos do Alura+ em alguma lista de "assistir mais tarde" ou que permitisse adicionar diretamente dentro de algum plano de estudos que já tenho montado.

Atualmente não temos nada para salvar os vídeos para assistir depois:
![image](https://user-images.githubusercontent.com/98191980/234882232-d23a6d38-d6db-4050-bb8a-2cb6da9ab99c.png)

E ao procurar nas opções, não existia nenhum tipo de funcionalidade:
![image](https://user-images.githubusercontent.com/98191980/234882439-9dc303ce-7438-4a26-9edd-777e52959493.png)

**Comment by designernatan** [comment]
@RedONe06 valeu pela sugestao!

eu gosto bastante de algo nessa linha que você sugeriu, mesmo nao estando nos planos para o futuro próximo

para tentar resolver esse ponto que você trouxe, recomendo dois caminhos:

- Usar o favoritos do browser, criando uma pasta chamada 'Estudos Alura' ou 'Alura'
- Usar a extensão [GetPocket.](https://getpocket.com/) Dá para salvar qualquer link direto do computador ou no celular, além de deixar offline quando é só texto também

pessoalmente, uso bastante o pocket há anos, é bem bom

---

e para os planos de estudos, ainda o caminho mais direto é pegar o link do conteúdo e colocar diretamente lá, ok?

abcs e bons estudos!

**Comment by giovana-armidoro** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
