### ISSUE TITLE
Legenda

### ISSUE THREAD

**Issue by manupantoja** [caelum/alura-funcionalidades#811]
Seria muito legal se também tivesse uma legenda na tela do vídeo. No meu trabalho tenho acesso a computador eu posso estudar se nao houver ninguem pra atender porem nao tenho acesso a audio. seria legal demais se eu pudesse estudar só lendo a legenda e assistindo o video

**Comment by designernatan** [comment]
@manupantoja valeu pela sugestao!

estamos testando algumas coisas nesse sentido, ok? Não tenho uma ideia de prazo pra te passar, mas com certeza está nos planos

**Comment by giovana-armidoro** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
