### ISSUE TITLE
"Você quer ver:" R: Filtros melhores

### ISSUE THREAD

**Issue by psjjonathan** [caelum/alura-funcionalidades#812]
Novamente, eu compartilhando dores minhas em busca de oferecer uma oportunidade de melhoras para vocês.

Um problema que eu sempre tive utilizando Alura é encontrar de forma mais fácil entre os cursos dentro de uma categoria/escola. O porque eu acho nunca me encontrei bem na plataforma dentro de uma categoria/escola? Parte desse problema certamente é a ordenação das tags para filtro e como os cursos estão categorizados com as tags. 

Hoje, na Alura, a partir de uma tela de categoria/escola, temos a seção para filtragem por tags chamada "Você quer ver:". O fato de que as tags estão ordenadas por mais relevantes, ou por tags com mais cursos, não sei dizer qual é o quesito para ordenação aqui, mas sempre que eu preciso procurar um curso nas tags, eu preciso usar o _CTRL + F_ ou a searchbar. Creio que se as tags atuais fossem ordenadas por ordem alfabética, ou se pelo menos existisse uma opção de ordenar por ordem alfabética, com certeza eu acharia mais fácil.

![image](https://user-images.githubusercontent.com/38404158/235152485-c9191593-22f1-4717-b067-472a03c4a309.png)

O segundo problema que eu citei é como os cursos estão "tagueados". Hoje, dando exemplo da categoria/escola de design, as ferramentas como Figma, Sketch, AdobeXD, etc, estão dentro da tag UI Design, e se eu tivesse como filtrar pela ferramenta que eu busco aprender, novamente, não teria que recorrer ao _CTRL + F_ ou search.

Espero ter colaborado com este feedback ;)

**Comment by designernatan** [comment]
@psjjonathan valeu pelas sugestoes! :))

eu podia jurar que a gente tinha colocado essas subcategs em ordem alfabética. De qualquer forma pinguei o time aqui pois parece bom pra UX e fácil de ser implementado

sobre a segunda, queremos melhorar a forma que vocês buscam conteúdo na alura, primeiro passo foi a v3 que fizemos na [busca](https://cursos.alura.com.br/search/1?query=figma)

brigadao e bons estudos! :D

**Comment by giovana-armidoro** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
