### ISSUE TITLE
Exercício de cursos já realizados.

### ISSUE THREAD

**Issue by Lucas-Macedo-Oliveira** [caelum/alura-funcionalidades#813]
A minha sugestão é que tenha exercícios de acesso fácil de cursos já realizados uma espécie de duolingo para programação onde você responde exercício de cursos que você já realizou, também seria ótimo caso tivesse uma opção de quais cursos você queria resolver os exercício. Assim fazendo com que caso eu já esteja em um patamar mais avançado que eu não "perca tempo" respondendo exercício de cursos realizados a muito tempo quando ainda havia pouco conhecimento.
O Alura poderia também sugerir exercícios de cursos realizados a um tempo que acredita que seja bom fazer uma revisão através dos próprios exercícios.
Eu acredito que essa funcionalidade é útil porque os exercício dos cursos do Alura são legais e a pratica faz com que você fixe melhor o seu conhecimento, e praticar coisas que você já aprendeu é importante para que você não as esqueça.
O que eu imagino seriam task diarias como já citado como o duolingo, só para pratica rápida, desenvolvendo desse ponto poderiam também  trazer exercícios dos cursos de uma maneira mais fácil de acessar, como uma pagina de exercício podendo ter como inspirações beecrowed e hackerank, porem acredito que minha primeira sugestão seja "fácil" de desenvolver comparado a sugerida nos últimos parágrafos, acredito que outros alunos não somente eu gostariam dessa funcionalidade.

**Comment by designernatan** [comment]
@Sakhul valeu pela sugestao!

algo tipo os flash cards né? 

estamos trabalhando em algo bacana que acredito que vai te ajudar nesse quesito de exercícios, espere novidades na alura num futuro próximo :))

enquanto isso, daria uma testada nessa [extensão Wisdolia.](https://www.wisdolia.com) Ela promete fazer flash cards de qualquer página, parece que tem potencial.

abcs e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
