### ISSUE TITLE
VIsão geral de certificado

### ISSUE THREAD

**Issue by Arielsonsantana** [caelum/alura-funcionalidades#814]
Visão geral de certificados

No aplicativo, após concluir um curso, não existe local para visualizar o certificado do curso. 

Seria interessante uma aba em "Meus cursos" para poder visualziar os Certificado de conclusão. Assim facilitaria mostrar o certificado quando está com o celular em mãos, pois hoje depende de acessar pelo Desktop.

**Comment by designernatan** [comment]
@Arielsonsantana valeu pela sugestao!

estamos vendo isso para que no futuro de médio prazo role pegar os certificados via app também!

**Comment by allexrm** [comment]
Quando muda a linguagem do certificado ( para inglês, por exemplo) e clica para ver a parte de trás, os nomes dos módulos do curso continuam em português. O ideal seria que todo o conteúdo do certificado fosse traduzido.

**Comment by designernatan** [comment]
opa @allexrm

provavelmente nao traduzimos as aulas dos cursos que você está vendo

depois dá uma pingada no [atendimento](https://www.alura.com.br/contato) com os cursos que não estão traduzidos? Ai ja vai pro time que fará a tradução certinha e dão seguimento com isso :))

desculpe por isso inclusive


---

fechando a issue, mas ela continua aberto para comentários futuros
