### ISSUE TITLE
Sistema de âncora

### ISSUE THREAD

**Issue by Arielsonsantana** [caelum/alura-funcionalidades#815]
Seria interessante um sitema de Ancora na tela de FORMAÇÔES. 

Deixar classificado as categorias das formações ja no topo da tela agiliza a navegabilidade dentro das informações, tanto no desktop ou mobile. 

Segue um exemplo de botões âncoras, ao clicar neles existe uma rolagem automática para a respectiva sessçao.

![Modelo de funcionalidade](https://user-images.githubusercontent.com/132298459/235520099-2fd6953e-a07c-4c65-be8c-39834d9426de.jpg)

**Comment by designernatan** [comment]
@Arielsonsantana valeu pela sugestao!

gosto bastante! Facil de implementar tambem!

vamos tentar puxar essa no futuro :))

**Comment by andradeisadora** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
