### ISSUE TITLE
Tela de login - Mostrar senha

### ISSUE THREAD

**Issue by gesalamanca** [caelum/alura-funcionalidades#816]
Na página de login poderia ter um ícone de olho para visualizar a senha.

![image](https://user-images.githubusercontent.com/65085890/235553099-d8734e26-8149-4163-a22d-f1988d6a5154.png)

Exemplo:
![image](https://user-images.githubusercontent.com/65085890/235553255-6a0e06c3-dab3-4100-8c9d-650205cfb1aa.png)

**Comment by designernatan** [comment]
@gesalamanca valeu pela sugestao!

esse padrão começou a fazer todo sentido, né? Vamos dar uma olhada nisso no futuro e caso vá pra frente você vai ver essa melhoria direto por na tela de login

abcs!

edit:
acabei de me lembrar de um ponto rápido aqui é que pode ser interessante usar um gerenciador de senhas, lastpass/1pass/bitwarden ou mesmo o do próprio browser. Pode ajudar hoje com isso e com outras coisas também

**Comment by andradeisadora** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
