### ISSUE TITLE
[PLANO DE ESTUDOS] Criar sub-seções nos planos de estudo

### ISSUE THREAD

**Issue by jeffersondesouza** [caelum/alura-funcionalidades#818]
Como aluno que está criando um plano de estudo
gostaria de
Criar sub-seções nos planos de estudos para com isso organizar melhor os conteúdos dos planos de estudo.

Exemplo: supondo que me utilizei do Dev em T para criar uma sequência de estudos, na forma atual temos algo como como
## Meu Plano de Estudos 
Curso HTML 1
Curso HTML 2
Curso CSS 1
Curso CSS 2

**_Com seções teríamos algo como_**
### HTML Fundamentals
Curso HTML 1
Curso HTML 2
### CSS Fundamentals
Curso CSS 1
Curso CSS 2

Isso ajudaria bastante na organização e visualização dos progressos

**Comment by designernatan** [comment]
@jeffersondesouza valeu pela sugestao!

gosto e acho que alguem ja sugeriu algo assim por aqui também

quando pegarmos a parte de plano de estudos para melhorarmos vamos considerar isso, ok?

por hora, mesmo não sendo o ideal, o que faria é criar vários PDEs (planos de estudos)

abcs!

**Comment by andradeisadora** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
