### ISSUE TITLE
Opção de scrollar a página enquanto em tela cheia

### ISSUE THREAD

**Issue by gaeiki** [caelum/alura-funcionalidades#819]
Seria interessante a opção de scrollar a página enquanto está em tela cheia do vídeo, assim como acontece no Youtube. Dessa forma, o aluno pode ter acesso mais facilmente ao conteúdo da transcrição que, algumas vezes, envolve copiar um trecho de código.
Um exemplo de uma captura do Youtube. Enquanto está em tela cheia é possível descer a página para interagir com o restante do conteúdo.

![Anotação 2023-05-05 093630](https://user-images.githubusercontent.com/64814663/236459169-9dab5c2c-5368-46fe-99b1-57cde9052b5d.png)

**Comment by designernatan** [comment]
@gaeiki valeu pela sugestão!

no futuro de longo prazo queremos (precisamos!) mexer na tela de aula

vamos considerar isso nas discussões, ok?

abcs!

**Comment by andradeisadora** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
