### ISSUE TITLE
Sugestão de curso de groovy e pirâmide de testes 

### ISSUE THREAD

**Issue by bperboni** [caelum/alura-funcionalidades#82]
Estou com necessidade de aprimorar meu conhecimento em groovy para execução de testes. Não encontrei nada sobre groovy no alura. Também não encontrei nada sobre pirâmide de testes. 
Há alguma iniciativa de inclusão de cursos sobre esses conteúdos? Tem alguma previsão de quando estarão disponíveis? 
Obrigada.

**Comment by designernatan** [comment]
oi @bperboni , vc pode mandar depois sua sugestao direto no [Sugestões de Cursos](https://docs.google.com/forms/d/e/1FAIpQLScwKyaSvuFXK9SmMJoLPuYAS2qD_XAAnZPxMZij9qVeflbhBg/viewform)?

la vai direto para o time que pensa e prioriza o backlog dos cursos

por hora sei que esses não estão no roadmap por hora viu

abcs!

---

depois da uma olhada nas outras issues aqui no github com sugestões de funcionalidades de outras alunas e alunos!
