### ISSUE TITLE
Salvar cursos e formações que desejo ver e Alura+

### ISSUE THREAD

**Issue by 2711Leticia** [caelum/alura-funcionalidades#820]
Eu sufiro que tenha uma funcionalidade para salvar os cursos que gostariamos de fazer e os Aluras+, pois assim não precisariamos ficar procurando algo que talvez venhamos a esquecer ou nos perder no que gostariamos de ver
Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

**Comment by designernatan** [comment]
@2711Leticia valeu pela sugestao!

respondi a uma [issue semelhante aqui](https://github.com/caelum/alura-funcionalidades/issues/810#issuecomment-1533056155)

em resumo: não está nos planos por hora e tentaria usar o browser ou o getpocket para suprir isso, não é o ideal mas resolveria hoje

abcs!

**Comment by andradeisadora** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
