### ISSUE TITLE
Sugestão em 'planos de estudo'

### ISSUE THREAD

**Issue by paulorohdenjr** [caelum/alura-funcionalidades#821]
Olá, tudo bem? 

A ferramenta **planos de estudos** é uma ótima opção de organização para nós alunos. Uma funcionalidade interessante seria poder organizar a sequência dos planos de estudos publicados, por exemplo: 

- HTML e CSS
- JavaScript
- Lógica de Programação

**_Agora com a nova ordem_** 

- HTML e CSS
- Lógica de Programação
- JavaScript

Dentro de um plano de ação, é possível organizar a ordem dos cursos, seria a mesma lógica pro dashboard dos planos de estudos. 

Enfim, apenas uma sugestão. Abraços!

**Comment by designernatan** [comment]
@paulorohdenjr valeu pela sugestao!

nao entendi bem, você diz reordenar os conteúdos dentro de um PDE (plano de estudos)? Se for isso dá para editar e arrastar o card de baixo e soltá-lo mais pra cima
![image](https://github.com/caelum/alura-funcionalidades/assets/5431347/67440db5-21d4-4fde-9e86-a196bcd376a8)

**Comment by paulorohdenjr** [comment]
Seria nessa tela aqui:

![image](https://github.com/caelum/alura-funcionalidades/assets/132000262/ddfdfe38-026f-4a71-b148-8e26cb74a04d)

**Comment by designernatan** [comment]
ahhhhhh agora entendi! Valeu por mandar o print!

por hora não estamos com planos de no futuro próximo mexer nessa tela, mas sem dúvida é algo bacana para discutirmos quando esse momento chegar

estamos focados numas novidades **bem legais** que vao pintar num futuro bem próximo 👀

abcs!

**Comment by andradeisadora** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
