### ISSUE TITLE
Opção de reset no progresso do curso após concluído

### ISSUE THREAD

**Issue by papaidilda** [caelum/alura-funcionalidades#822]
Após concluir o curso ele sai da lista de cursos em andamento no Dashboard.
No meu caso, eu comecei refazer um curso para relembrar alguns tópicos e toda vez que iniciava uma aula tinha que procurar o curso e lembrar onde parei.
Se houvesse a possibilidade de resetar o andamento do curso já finalizado e a inclusão na lista de cursos em andamento facilitaria encontrar o curso e acompanhá-lo de onde parou novamente.
O curso continuaria como concluído no meu histórico, com as notas e tudo mais.

**Comment by designernatan** [comment]
@papaidilda valeu pela sugestao!

sem planos por hora para reset de cursos, desenvolvemos o 'sair do curso' a fim de melhorar a organização da dashboard do aluno, mas o progresso é para continuar ali mesmo

agora sobre um curso concluído permanecer na dashboard é algo que não pensamos, vamos discutir em torno disso quando a melhorarmos no futuro, ok?

abcs!

**Comment by andradeisadora** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
