### ISSUE TITLE
Alura Empresas - Ranking dentro dos membros da empresa [Gamificação]

### ISSUE THREAD

**Issue by Speell** [caelum/alura-funcionalidades#823]
Prezados, bom dia.

Faço parte de uma empresa que possui contratação da Alura para todos os funcionários (o acesso é via e-mail corporativo).
É comum dentro do nosso setor a competição através da pontuação do Ranking da Alura.
No caso de Alura Empresas, gostaria de sugerir um ranking ou uma forma de filtrar a pontuação dos membros da sua empresa, de forma a exibir um ranking de toda a empresa.

**Comment by designernatan** [comment]
@Speell valeu pela sugestao thiago!

precisamos melhorar essa parte do ranking/gamefication como um todo, por hora sem previsão

caso isso mude no futuro, pingamos aqui!

outro ponto: dependendo da contratação, há um painel de acompanhamento disponível para os(as) gestores(as), você pode pingar a pessoa gestora de contas da Alura para talvez já ter essa informação

abcs e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
