### ISSUE TITLE
Botão para direcionar para cursos descontinuados (ou que não constam mais na grade oficial)

### ISSUE THREAD

**Issue by RenanSilveira94** [caelum/alura-funcionalidades#824]
Estava navegando pelos cursos, usando a lupa de pesquisa, e vi que tem diversos cursos que foram descontinuados como unreal engine, zbrush... Seria interessante se o site tivesse um botão que levasse a esses cursos, pois, por mais que estejam descontinuados,continuam sendo bons conteúdos, e os alunos que tiverem interesse poderiam encontra-los com mais facilidade.

**Comment by designernatan** [comment]
@RenanSilveira94 valeu pela sugestao!

Entendo perfeitamente seu ponto. Como nosso foco é sempre deixar conteúdos atualizados e que estão casando com o que enxergamos como um conteúdo bacana, direcionamos a plataforma inteira apenas para os conteúdos que estão ok com nossa curadoria de qualidade

de qualquer forma, sua sugestão vai ser legal para discutirmos numa possível melhora da busca no futuro

acabamos de mexer nela, acredito que próximas melhorias serão no futuro de longo prazo

abcs e bons estudos!

**Comment by masromao** [comment]
pessoal, fechando a issue por aqui

podem voltar a comentar se quiserem :)

**Comment by masromao** [comment]
pessoal, fechando a issue por aqui

podem voltar a comentar se quiserem :)
