### ISSUE TITLE
Aviso de dúvida respondida

### ISSUE THREAD

**Issue by 2711Leticia** [caelum/alura-funcionalidades#825]
Olá, com os estudos frequêntes na Alura e com as dúvidas que surgem ao longo do caminho de aprendizagem, tenho percebido que não existe (até onde eu sei) um aviso ou notificação de dúvida respondida.
Na minha opinião seria muito interessante existir essa funcionalidade , traz uma grande experiência de navegação e facilita a usabilidade do usuário em ter sua dúvida respondida. Um grande exemplo que acontece comigo é postar uma dúvida no forúm e acabar me esquecendo de verificar se foi respondida, pois normalmente são respondidas em até 24h. Mas se tivesse uma função assim evitaria o esquecimento e ajudaria muito quem está com urgência na dúvida.

**Comment by designernatan** [comment]
@2711Leticia valeu pela sugestao!

essa já temos, vai um e-mail falando quando respondem o tópico que você está acompanhando/criou

se o e-mail nao tiver chegando me passa seu usuario pra pedir para o time aqui investigar? Pode ser um bug

abcs!

**Comment by 2711Leticia** [comment]
Olá Natan, que bom que já existe esse meio de notificação. Realmente eu não
sabia, e não recebo nenhum e-mail para notificar que minha dúvida foi
respondida. Segue abaixo meu usuário: Leticia Marcela Pimentel Fonseca

Em sex., 12 de mai. de 2023 às 15:19, Natan Souza ***@***.***>
escreveu:

**Comment by designernatan** [comment]
oi leticia, acabei vendo aqui e users com contrato corporativo não tem essa feature :/

desculpe pela confusão

**Comment by 2711Leticia** [comment]
Sem problemas Natan. Muito obrigado pela atenção e disponibilidade.

Em seg., 15 de mai. de 2023 às 14:35, Natan Souza ***@***.***>
escreveu:

**Comment by masromao** [comment]
pessoal, fechando a issue por aqui

podem voltar a comentar se quiserem :)
