### ISSUE TITLE
Botão de ocultar cursos com outra versão nova

### ISSUE THREAD

**Issue by ntimesgurgel** [caelum/alura-funcionalidades#826]
A proposta é que na lista de cursos disponíveis em cursos.alura.com.br/category/<categoria> tenha um toggle que oculte os cursos que tenha uma versão nova, mantendo a página limpa.

**Comment by giovana-armidoro** [comment]
oi nathan, valeu pela sugestão!
poderia trazer mais algumas informações pra eu te possa te orientar melhor? se puder me dar mais alguns detalhes do que aconteceu ou até mesmo um print da tela, seria ótimo :)

obrigada e abcs!

**Comment by ntimesgurgel** [comment]
Na imagem abaixo, a gente vê que tem dois cursos marcados de Java JDBC, sendo que o da esquerda recebeu uma versão nova (o da direita), seria interessante que tivesse um botão para remover da visualização esses que já receberam versão nova. Pode aproveitar e adicionar uma funcionalidade que remova da visualização os cursos já concluídos também.

![Captura de Tela (34)](https://github.com/caelum/alura-funcionalidades/assets/64473126/e600dd5d-cdc3-4e6d-8a9a-e9403eed6e03)

**Comment by giovana-armidoro** [comment]
obrigada por trazer mais informações!
não estamos com planos de mexer nessa tela por hora, mas vou levar para a equipe e sua sugestão vai ser legal para discutirmos quando formos fazer melhorias em algo relacionado a isso

abraços e bons estudos!

**Comment by masromao** [comment]
pessoal, fechando a issue por aqui

podem voltar a comentar se quiserem :)
