### ISSUE TITLE
Ver cursos arquivados da plataforma.

### ISSUE THREAD

**Issue by italomded** [caelum/alura-funcionalidades#827]
A Alura atualiza os cursos da plataforma com bastante frequência, e isto é ótimo, ao manter a plataforma relevante. No entanto, a abordagem de retirar os cursos “depreciados” das buscas e algo que não considero uma boa abordagem, irei explicar com exemplos práticos.

Atualmente está em lançamentos a nova formação de Angular da Alura, com a versão mais nova, e isto é ótimo para quem irá iniciar um novo projeto e trabalhar com projetos novos. No entanto, existe uma galera interessada em aprender as versões dos cursos antigos, porque é a versão que essa galera pode estar usando na empresa que trabalha. Mas, atualmente, como os cursos da versão antigas foram “depreciados” não é possível encontrá-los.

Qual o remédio para está situação? Essa galera irá estudar com matérias alternativos pela internet afora, sendo que existe um conteúdo de qualidade já produzido na plataforma, porém inacessível (a menos que você tenha salvado em um plano de estudos antes dele ter sido “depreciado”).

Isto acontece comigo, a pouco tempo fiz um curso de novidades sobre o Java 8, uma versão antiga até, foi um curso muito útil para mim, e pouco tempo depois de telo terminado ele foi “depreciado”. Se eu tivesse demorado por mais um pouco não conseguiria acessar o curso e aprender com ele.

Outro exemplo, estou trabalhando com código legado na empresa, queria um conteúdo bacana de JSF para aprender. Fiquei com a dúvida: “Será que a Alura tem um conteúdo muito massa de JSF só que eu não consigo encontrar porque foi 'depreciado'?”.

Enfim, enrolei bastante, mas minha sugestão é: ter uma forma de acessar esse conteúdo que não é mais atual, mas que pode ser bastante relevante ainda para uma galera. Espero que estudem essa ideia com carinho!

**Comment by giovana-armidoro** [comment]
oi Ítalo, valeu por trazer essa sugestão!

atualmente você consegue ter acesso a esses conteúdos por essa página [aqui](https://cursos.alura.com.br/conteudos-descontinuados/cursos), ela tem a listagem de todos os cursos e formações da plataforma que foram descontinuados
esse link também está disponível na página de formações (bem lá no finalzinho da página)

mas, como o natan comentou nessa [issue](https://github.com/caelum/alura-funcionalidades/issues/824), essa seria uma sugestão legal para discutirmos numa possível melhora da busca da plataforma no futuro

abraços e bons estudos :)

**Comment by masromao** [comment]
pessoal, fechando a issue por aqui

podem voltar a comentar se quiserem :)
