### ISSUE TITLE
APP para IOS, logo eu tenho iphone e IPAD  e suporte da Alura me informou que somente tem para Android, poderiam informar quando  teremos para o app ios?

### ISSUE THREAD

**Issue by ricardolelis49** [caelum/alura-funcionalidades#829]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

**Comment by giovana-armidoro** [comment]
oi Ricardo, atualmente o app da Alura está disponível para [Android](https://play.google.com/store/apps/details?id=br.com.alura.mobi&hl=pt_BR&gl=US) e [iOS](https://apps.apple.com/br/app/alura-cursos-online/id1225776635). O app da Alura Língua hoje realmente só temos disponível para [Android](https://play.google.com/store/apps/details?id=br.com.alura.lingua&hl=pt_BR&gl=US) mas em breve pretendemos ter para iOS também, só não consigo te dar um prazo ainda, mas qualquer novidade te atualizo por aqui :)

Abraços e bons estudos!

**Comment by felipetorres** [comment]
Só atualizando aqui: agora temos o [app da Alura Lingua para iOS](https://apps.apple.com/gb/app/alura-l%C3%ADngua/id6449951647).
