### ISSUE TITLE
Modo escuro 

### ISSUE THREAD

**Issue by diegobarbosasena** [caelum/alura-funcionalidades#83]
o Modo escuro na plataforma é um pouco estranho acho até escuro de mais, uma solução seria colocar a  cor cinza #222 ao invés da cor preta.

nos exercícios colocar o cinza claro #bababa nos textos, nos botões de escolha (A , B, C ... )  com o fundo de azul mais escuro  #486473 e os textos com cinza claro #bababa também 
    
![image](https://user-images.githubusercontent.com/20647459/75307429-74393b80-582a-11ea-8e9c-e7d03b4a9db1.png)

antes

![image](https://user-images.githubusercontent.com/20647459/75308615-af893980-582d-11ea-9d4f-9e0f02ad5d82.png)

depois 

![image](https://user-images.githubusercontent.com/20647459/75308630-ba43ce80-582d-11ea-82e8-8df7bd1485f8.png)

**Comment by designernatan** [comment]
oi @diegobarbosasena valeu pelo feedback! Legal saber que você está usando o dark mode!

na época testamos com algumas pessoas da alura e chegamos nesse nivel de dark do background, apesar de ter ficado muito escuro para algumas pessoas (eu por exemplo prefiro um [modo noturno mais puxado para o azul como no twitter](https://www.techradar.com/how-to/twitter-dark-mode))

a cor dos botões foi uma falha mesmo, acabamos esquecendo deles! Registrei aqui para alterarmos asap!

---

sei que vc usa firefox, mas no [chrome tem a possibilidade de sobrescrever os estilos do site](https://www.trysmudford.com/blog/chrome-local-overrides/) por locais (provavel que o firefox tenha algo assim tbm)
