### ISSUE TITLE
Alura access log API

### ISSUE THREAD

**Issue by oraffdev** [caelum/alura-funcionalidades#830]
Olá, tenho uma conta da alura, e estava mexendo e percebi a parte dos logs de acesso a conta, não achei nenhuma forma de receber esses dados para monitoramento da conta para saber os ultimos logins e verificar possiveis invasões a conta, se ja existe algo assim gostaria de saber como posso implementar, obrigado pela atenção

**Comment by giovana-armidoro** [comment]
oie,
verifiquei aqui com a equipe e infelizmente não temos nenhuma API com essa finalidade :( 
caso tenha alguma novidade comento aqui

abraços e bons estudos!

**Comment by masromao** [comment]
pessoal, fechando a issue por aqui

podem voltar a comentar se quiserem :)
