### ISSUE TITLE
Poder favoritar uma videoaula

### ISSUE THREAD

**Issue by AshileySabah** [caelum/alura-funcionalidades#831]
Poder favoritar uma videoaula e adicionar descrição que identifique o porquê de eu querer favoritar.
Exemplo: gostei dessa aula https://cursos.alura.com.br/course/algoritmos-javascript-i-algoritmos-ordenacao/task/98082 e queria poder salvá-la numa pasta de favoritos e adicionar o título de "Verificar processamento do computador".

**Comment by giovana-armidoro** [comment]
oi Ashiley, valeu pela sugestão!

Faz bastante sentido. Estamos com planos de melhorar a tela de aula e vou levar essa feature para entrar nas discussões. Não tenho como te dar um prazo, mas qualquer novidade atualizo aqui.

Uma sugestão é utilizar uma ferramenta chamada [Get Pocket,](https://getpocket.com/pt/?ep=1). ela salva links e vídeos para ver mais tarde. Dá para colocar tags em cada link, facilitando estudar depois. Acho que pode te ajudar hoje!

Abraços e bons estudos!

**Comment by masromao** [comment]
pessoal, fechando a issue por aqui

podem voltar a comentar se quiserem :)
