### ISSUE TITLE
[CORREÇÃO DE BUG] - Formações de programas encerrados ficam fixadas para sempre na dashboard

### ISSUE THREAD

**Issue by AndyinTheNW** [caelum/alura-funcionalidades#832]
# [CORREÇÃO DE BUG] - Formações de programas encerrados ficam fixadas para sempre na dashboard

## Descrição do Problema
Formações descontinuadas fixadas na 'dashboard' são impossíveis de remover. 

Quando o programa Oracle Next Education foi encerrado, perdemos acesso para as formações do programa. No entanto, as formações não concluídas ficam fixadas na dashboard sem possibilidade de remoção. Ao clicar nela, a página é apenas recarregada.

## Impacto
Isso é bastante incômodo, pois atrapalha na organização do que realmente queremos estudar, sem mencionar a poluição visual gerada por uma formação que não mais interessa o aluno. Isso é ainda mais problemático para pessoas com TOC. 

## Solução Proposta
Uma maneira de acessar essas formações para poder clicar em 'Não exibir no dashboard' ou uma lógica para que quando a formação seja descontinuada ou um programa como o do ONE se encerre, as formações em aberto não concluidas sejam automaticamente finalizadas, como se fosse a função 'Sair do curso', removendo automaticamente da dashboard dos alunos.

**Comment by giovana-armidoro** [comment]
oi Anderson, obrigada por reportar!
repassei essa questão para a equipe e te retorno quando tivermos novidades - não posso te dar um prazo ainda, ok?.
para facilitar a resolução do problema, pode me passar o e-mail que utiliza na Alura?

**Comment by AndyinTheNW** [comment]
Perdão, acredito que abrí tickets duplicados, já me responderam. Obrigado!

Em seg., 29 de mai. de 2023 15:46, Giovana ***@***.***>
escreveu:

**Comment by AndyinTheNW** [comment]
> oi Anderson, obrigada por reportar!
> repassei essa questão para a equipe e te retorno quando tivermos novidades - não posso te dar um prazo ainda, ok?.
> para facilitar a resolução do problema, pode me passar o e-mail que utiliza na Alura?

andersonalmeida1008@gmail.com

Já me responderam individualmente sobre como remover pontualmente do meu perfil, obrigado!

**Comment by andradeisadora** [comment]
vou fechar a issue, pessoal

podem voltar a comentar se quiserem :)
