### ISSUE TITLE
Possibilidade de Categorizar Formações

### ISSUE THREAD

**Issue by hernandemonteiro** [caelum/alura-funcionalidades#833]
Olá!

Poderia existir uma forma do usuário poder catálogar as formações na página "/learning-guide/mine";

Por exemplo eu gostaria de separar em:

Desenvolvimento Pessoal

Design

Web

Mobile

Acredito que isso seria libertador se usado como um guia de estudo, e ainda mais se permitisse anotações por catálogo.

**Comment by andradeisadora** [comment]
oi @hernandemonteiro 
obrigada pela sugestão :)
você pode criar planos de estudos com os nomes das categorias e colocar as formações que se encaixam lá
também é possível usar o notion para criar esses catálogos e adicionar anotações sobre cada um

abraço e bons estudos!
