### ISSUE TITLE
Salvar páginas de cursos

### ISSUE THREAD

**Issue by alexvp4** [caelum/alura-funcionalidades#834]
Olá, gostaria de sugerir a ferramenta para salvar páginas específicas dos cursos que estamos navegando, seja vídeo ou conteúdo (ou até mesmo artigos).

Alguns assuntos nos cursos são chaves (funcionalidades, bibliotecas, links externos) e gostaria de acessar em outros momentos. Hoje estou salvando as páginas nos favoritos do navegador, mas se pudesse ter um local na Dashboard para acessar as páginas salvas e classificá-las, seria excelente. 

O Instagram possui este recurso em publicações, por exemplo. O twitter recentemente também implementou. Acredito que seria interessante.
Obrigado pela atenção.

**Comment by laiscavalcanti** [comment]
Oi, Alex, tudo bem?

Muito legal mesmo essa ideia. De fato quando estamos fazendo os cursos às sentimos a necessidade de salvar um conteúdo. Vou levar pro nosso time a sugestão. Obrigadão

**Comment by masromao** [comment]
pessoal, fechando a issue por aqui

podem voltar a comentar se quiserem :)
