### ISSUE TITLE
Permitir descontos conforme atividade em fórum

### ISSUE THREAD

**Issue by danielnetcvb** [caelum/alura-funcionalidades#835]
Seria interessante ter algum tipo de retribuição/desconto para alunos que são engajados no fórum. 
Vocês já possuem um sistema de pontuação, poderiam segregar a pontuação originada de "Melhores respostas" e assim fornecer descontos na renovação para alunos que estão constantemente ajudando outros nos fóruns. 

Poderia haver um sistema de range:

100-300 melhores respostas no último ano - desconto na renovação de x %
300-500 melhores respostas no último ano - desconto na renovação de y %

Para evitar problema com fraudes, como um grupo de alunos combinar de ficar perguntando e respondendo entre eles para ganhar a melhor resposta, poderiam criar alguma lógica em que só seria válido as melhores respostas do mesmo perguntador nas duas primeiras vezes na semana ou algo assim. Talvez também ter algum serviço por fora para reconhecer possíveis padrões de trapaça.

Estou dando essa ideia porque as vezes pode ser desestimulante você dedicar um pouco do seu tempo para ajudar um colega que está precisando, saber que está enriquecendo a comunidade, dando um suporte para os instrutores que não precisarão dedicar o tempo deles para responder aquela pergunta - até dando um pouco mais de visibilidade, porque as respostas no fórum estão indexadas no google - e mesmo assim, no fim de tudo, estar pagando integralmente para estar numa comunidade que você está contribuindo para se tornar melhor.
Até pelo fato de que dar incentivos para que uma pessoa engajada no fórum continue na plataforma também seria benefíco para a Alura.

**Comment by laiscavalcanti** [comment]
Oi, Daniel, tudo bem?

É uma ideia legal de incentivo mas precisa ser bem estudada justamente pelo ponto que você trouxe de ter fraudes e isso gerar uma queda na qualidade no fórum. 

Obrigada pela sugestão!

**Comment by masromao** [comment]
pessoal, fechando a issue por aqui

podem voltar a comentar se quiserem :)
