### ISSUE TITLE
Sugestão de cursos ao finalizar o curso atual

### ISSUE THREAD

**Issue by JoaoVictor-DataEng** [caelum/alura-funcionalidades#836]
Sempre que estou aprendendo uma nova tecnologia, acabo ficando perdido em quais cursos fazer primeiro, pois cada um solicita um nível de conhecimento prévio do usuário. Sendo assim, acho que seria muito proveitoso se ao finalizar qualquer curso, o sistema desse sugestões de quais cursos fazer adiante. Isso facilitaria muito, pois é comum eu acabar fazendo cursos que não são pra mim naquele momento, ou então não saber qual curso fazer ao concluir o atual. Acabo perdendo muito tempo com isso. Seria legal também ter estruturado em alguma página a ordem dos cursos para se fazer, pro caso de alunos iniciantes em alguma tecnologia.

**Comment by laiscavalcanti** [comment]
Oi, jvlsking, tudo bem?

Nós temos essas informações sobre pré-requisitos e sobre quais cursos fazer depois nas páginas dos cursos e se você seguir formações, já tem toda a linha de cursos sugeridas. Pro exemplo, nesse curso de Java (https://cursos.alura.com.br/course/certificacao-java-basico), 
![Screenshot 2023-06-23 at 15-55-35 Certificação Java SE 7 Programmer I Alura - Cursos online de tecnologia](https://github.com/caelum/alura-funcionalidades/assets/23513957/8f8442af-81d3-4879-a470-f2e57be5a3dd)

E na  própria formação: https://cursos.alura.com.br/formacao-certificacao-java

Sugiro que siga pra uma formação sempre que estiver com dúvidas, pois temos um time de especialistas focados na criação dos conteúdos, como por onde você começa a estudar e pra onde seguir depois de acabar com um curso ou formação.

Qualquer outra dúvida, é só falar!

**Comment by masromao** [comment]
pessoal, fechando a issue por aqui

podem voltar a comentar se quiserem :)
