### ISSUE TITLE
Botão de início

### ISSUE THREAD

**Issue by Arielsonsantana** [caelum/alura-funcionalidades#837]
Olá, 

Fiquei bem feliz por ter participado da implementação de um novo recurso na página de formações. 

Mas vou sugerir outra função, que é até que simples mas fundamental para melhorar a experiência. 

Como foi inserido recentemente o modelo "âncora" seria interessante colocar também o botão de rolagem para o início. 
Isso melhora a experiência de quem quer voltar no topo do da página. Acredito que apenas uma seta indicando voltar ao topo ja é o suficiente para entender. 

Enfim. 

Até mais, Obrigado

Atenciosamente

Arielson Santana 
![image](https://github.com/caelum/alura-funcionalidades/assets/132298459/d119f4fe-a997-466b-b4b0-9a4041b1fb59)

**Comment by designernatan** [comment]
oi arielson, era algo bacana e simples de implementar, então puxamos, valeu mesmo :))

o voltar pra cima faz sentido mesmo, inclusive ja temos na tela de aula

valeu pela sugestao!

**Comment by masromao** [comment]
pessoal, fechando a issue por aqui

podem voltar a comentar se quiserem :)

**Comment by masromao** [comment]
pessoal, fechando a issue por aqui

podem voltar a comentar se quiserem :)
