### ISSUE TITLE
botão de lido

### ISSUE THREAD

**Issue by J1R429** [caelum/alura-funcionalidades#838]
sinto falta de um botão para marca lido ou assisitido nos itens do palno d eestudo que não são os videos do curso (e que já tem a regua de porcentagem)
ficaria mais facil de acompanhar onde parou e esse o mesmo link de video ou texto for usado em outros planos de estudo não perderia tempo

**Comment by designernatan** [comment]
@jessicacanela valeu pela sugestao!

em teoria nos planos de estudo ja aparece um ícone indicando que você clicou naquele conteúdo:
![image](https://github.com/caelum/alura-funcionalidades/assets/5431347/e619a4b0-b79e-4e1c-8d47-c16da553183a)

se nao tiver rolando no seu usuario pode ser bug nosso tbm

**Comment by masromao** [comment]
pessoal, fechando a issue por aqui

podem voltar a comentar se quiserem :)
