### ISSUE TITLE
Link de indicação/convite para amigos

### ISSUE THREAD

**Issue by hugosilvaferrari** [caelum/alura-funcionalidades#839]
Estou indicando a plataforma para alguns amigos e seria interessante ter algo direto na plataforma para mandar um convite, ter algum desconto caso seja convidado por algum aluno, descontos na rematrícula para convites aceitos, etc.

**Comment by designernatan** [comment]
@hugosilvaferrari valeu pela sugestao e por indicar a alura para seus colegas :))

a gente faz algo assim nas black fridays, aí tem um ranking de indicações

se nao me engano primeiro premio da de 2022 foi um PS5 ou um switch, nao lembro de cabeça

talvez fazer algo assim direto na plataforma poderia ser uma boa mesmo para discutirmos aqui

abcs!

**Comment by masromao** [comment]
pessoal, fechando a issue por aqui

podem voltar a comentar se quiserem :)
