### ISSUE TITLE
Minhas Atividades

### ISSUE THREAD

**Issue by teonett** [caelum/alura-funcionalidades#84]
Na tela onde exibe as informações de minhas atividades poderia exibir informações referente ao modulo, podendo haver um filtro indicando se foi finalizado ou não, seria algo complementar ao de cursos concluídos.

** Minha sugestão e baseada na procura que fiz no site, e somente depois de muito tempo achei pro um acaso quando cliquei em Perfil & Certificados.

**Comment by designernatan** [comment]
valeu pela sugestao @teonett 

essa tela precisa de uma repaginada no futuro, linkar para o curso concluido e o topico respondido faz todo sentido
