### ISSUE TITLE
Fale com a administração

### ISSUE THREAD

**Issue by ronaldokiiller** [caelum/alura-funcionalidades#840]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.
Para falar de duvidas referentes a questões administrativas, de matriculas em cursos e/ou emissão de certificados.
Poderia ser um botão ou link que levasse a uma página com um formulário específico ou mostrasse um link do whatsapp ou outro aplicativo de mensagens, ou um número de SAC (call center da Alura).
Se a opção fosse por um formulário, poderia haver no topo do formulário uma caixa de combinação com assuntos específicos que poderiam ser tratados por este canal, sendo de preenchimento obrigatório.
Caso não fosse selecionada a opção ou a seleção fosse "escolha uma opção", seria exibida a seguinte mensagem: "se o assunto que deseja tratar não está listado na caixa de seleção, é porque provavelmente sua dúvida deve ser tratada por outro canal... (e concluí a mensagem com a explicação sobre qual canal é adequado para cada tipo de dúvida) "

**Comment by masromao** [comment]
Olá @ronaldokiiller , tudo bem?
Para esse tipo de contato, [temos essa página aqui](https://www.alura.com.br/contato) onde você pode encontrar alguns canais onde pode falar com a gente!

Fique a vontade para conversar com nosso time e tirar suas dúvidas, ficaremos felizes em te ajudar! 🌟 
Abraços e bons estudos!

**Comment by ronaldokiiller** [comment]
Oi @masromao 
Que ótimo! Então sugiro que link essa página de contato em algum lugar na página principal, pode ser no rodapé ou em algum menu

**Comment by masromao** [comment]
Muito obrigado pela sugestão @ronaldokiiller , vamos estudar a possibilidade de inclusão em alguma atualização futura da plataforma.

Bons estudos!

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
