### ISSUE TITLE
lista de participações em fóruns

### ISSUE THREAD

**Issue by ronaldokiiller** [caelum/alura-funcionalidades#841]
Um link no perfil para listar as participações nos fóruns e as respectivas respostas

**Comment by masromao** [comment]
Olá @ronaldokiiller boa tarde!
Você consegue acessar suas participações no fórum clicando em:

Menu Comunidade -> Minhas Interações

![Captura de tela 2023-07-18 182921fff](https://github.com/caelum/alura-funcionalidades/assets/86667938/ab1d43ee-7a65-4722-b594-23c48e421aee)

Você pode também acessar essa página com a listagem das suas interações pelo link:
https://cursos.alura.com.br/forum/participacao

Qualquer dúvida adicional, estamos a disposição.
Abraços e bons estudos 🌟

**Comment by ronaldokiiller** [comment]
No meu ambiente de aprendizagem só aparecem 2 menus Dashboard e plano de estudos

**Comment by masromao** [comment]
Entendi @ronaldokiiller , demos uma olhada por aqui, realmente as licenças do Seed Paraná ainda não possuem esse feature.
Já conversamos sobre sua sugestão e vamos estudar a viabilidade de implementá-la posteriormente.

Como não temos previsão a curto prazo, ainda não consigo te passar uma data específica, tudo bem?
Obrigado novamente pela sugestão!

Abraços e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
