### ISSUE TITLE
Gerar certificado em outras línguas

### ISSUE THREAD

**Issue by fxdevuk** [caelum/alura-funcionalidades#843]
Quando clicamos "Você pode encontrar um certificado completo [aqui](https://cursos.alura.com.br/user/xavierfax/fullCertificate/b5620fccbedc7e2f0658fb9742b2f565)", poderia ter uma opção para gerar o certificado em Inglês, além de outras línguas.

**Comment by masromao** [comment]
Olá @fxdevuk 
Muito interessante essa sugestão sobre o certificado formal em outros idiomas.
Conversei internamente com o pessoal e quando formos repensar essa página vamos analisar a viabilidade de implementação.

Como ainda não temos previsão para pegar isso no curto prazo, não consigo te passar uma data para isso, infelizmente, mas você pode entrar [aqui em contato](https://www.alura.com.br/contato) para que nosso time possa tentar te ajudar de alguma forma. 

Uma outra forma de conseguir visualizar o Certificado em outro idioma seria entrar aqui no [Tradutor do Google](https://translate.google.com.br/?hl=pt-BR&sl=auto&tl=pt&op=websites) e colocar o link do certificado ali no campo "Site" 
![image](https://github.com/caelum/alura-funcionalidades/assets/86667938/09e6f647-1545-422f-bf51-492e9e211cf5)

Com isso feito, é possível alterar o idioma para tradução e com isso alterar as informações do certificado para o idioma escolhido:
![image](https://github.com/caelum/alura-funcionalidades/assets/86667938/ede0447a-0a51-4cba-8631-9c40fe9dd8fe)

Não é a solução definitiva, mas acredito que possa ajudar na visualização das informações no idioma desejado.

Qualquer dúvida, fica a vontade pra entrar em contato com a gente.
Abraços e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
