### ISSUE TITLE
Exibir o número de perguntas do forum associadas a uma atividade na página da atividade. 

### ISSUE THREAD

**Issue by AlexJBSilva** [caelum/alura-funcionalidades#844]
Na página de cada atividade existe o botão "Discutir no Forum" que direciona para a página do forum associada àquela atividade. 

Sugiro que o número de questões postadas no forum associadas à atividade seja exibido próximo ao botão "Discutir no Forum".

Isso vai:
* Estimular os alunos a visualizarem páginas do forum onde exista algum item postado.
* Poupar o trabalho de alunos proativos (que sabem a importância do forum na ampliação do aprendizado) acabarem clicando no "Discutir no Forum" de atividades sem itens postados.

Exemplo:
![Botao com número de posts associados a atividade.](https://github.com/caelum/alura-funcionalidades/assets/104526833/14905a98-7523-4274-ae8e-07eacc4d9ca0)

https://cursos.alura.com.br/forum/curso-csharp-criando-distribuindo-bibliotecas-dotnet/exercicio-bibliotecas-externas/114915/

**Comment by masromao** [comment]
Olá @AlexJBSilva, obrigado pela sugestão!

Realmente é uma ideia interessante essa de sinalizar externamente quantas interações aquele tópico apresenta no fórum.
Quando formos mexer na tela de aula como um todo certamente ideias como essa vão nos ajudar bastante.
Por enquanto não consigo te passar um prazo para essa feature, mas com certeza vamos pensar a respeito quando fomos priorizar essa tela no futuro.

Obrigado novamente pela sugestão.
Abraços e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
