### ISSUE TITLE
Calendário para planejamento de cursos

### ISSUE THREAD

**Issue by KarolineSendrete** [caelum/alura-funcionalidades#845]
**Problemática:** Quero ter acesso a um calendário no próprio Alura para poder planejar os cursos que vou fazer durante a semana.

**Possíveis Soluções:**
- Uma aba com o nome "Meu calendário", nele só tenho acesso a um calendário simples parecido com a do Google;
- O diferencial está na praticidade de colocar _**o curso**_ que se deseja fazer _**no dia**_ que foi "selecionado" pela seta do PC (como mostra a imagem abaixo - no dia 12/julho)
- Para o curso aparecer como opção na agenda, antes o usuário precisa colocar o curso no seu Dashboard, ou seja, só os cursos no Dashboard poderá ser planejado. (Acho que isso faz sentido porque esses cursos são os que importam para o usuário.
- Ao invés do usuário escrever o nome do curso da maneira dele, na primeira letra que colocar - estará linkado o curso que se relaciona com a letra (Exemplo: eu coloco a **letra F** e me retorna o curso **"Foco: trazendo mais resultados para o dia a dia"** que está no meu Dashboard)
- Além dos nomes do curso, seria interessante aparecer a logo do curso, pois fica visualmente mais atrativo.

![Captura de Tela (46)](https://github.com/caelum/alura-funcionalidades/assets/139411892/54de0bb5-6340-4d98-a6e1-9e6e2c3c2b4c)

**Comment by artnicodemus** [comment]
Oi @KarolineSendrete , muito obrigado pela sugestão tão detalhada!
Recentemente estudamos possibilidades nesse sentido de organizar uma agenda de estudos dentro da plataforma. Por enquanto não temos a possibilidade de ter um calendar da Alura, devido a complexidade de implementação e outros fatores.

Porém, temos vários conteúdos de apoio a esse contexto que podem lhe ajudar:

- [Artigo Alura "O calendário de estudo"](https://www.alura.com.br/artigos/o-dia-a-dia-de-um-profissional-que-aprende-o-calendario-de-estudo)
- [Artigo Alura "Planejando meus estudos"](https://www.alura.com.br/artigos/planejando-meus-estudos)
- [Alura+ "Ritmo de estudos"](https://cursos.alura.com.br/extra/alura-mais/ritmo-de-estudos-c18)
- [Alura Youtube "Como posso estudar melhor?"](https://www.youtube.com/watch?v=Is6c9KSGCbk)

Muito obrigado e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
