### ISSUE TITLE
Atualização de cursos

### ISSUE THREAD

**Issue by manucamarggo** [caelum/alura-funcionalidades#846]
Estou fazendo a formação em Adobe XD "Adobe XD: design visual de um site mobile", chega um momento do curso que o professor vai ensinar o Sitemap através do mockflow, até aí tudo bem. Eu comecei a aula, acessei o site, me cadastrei e não conseguia realizar as atividades, até que nas aulas seguintes aparece um aviso que a ferramenta não estava mais disponível de forma gratuita. Gostaria que este aviso viesse antes de dar inicio as aulas, se ocorreu alguma atualização nas ferramentas que o curso utiliza e a plataforma não tem a intenção de regravar a aula, seria legal observar a ordem dos avisos para que os alunos consigam acompanhar a aula. Obrigada!

"Recentemente, o Mockflow está com uma assinatura paga para criar sitemaps. Mas uma ótima ferramenta gratuita para fazer sitemaps é o [Octopus](https://octopus.do/)"

**Comment by masromao** [comment]
Olá @manucamarggo bom dia!
Obrigado pela sugestão, realmente faz sentido avisar esse tipo de coisa antes das aulas relacionadas.
Por enquanto ainda não consigo te passar um prazo de quando podemos mexer nisso, mas de qualquer forma, sua sugestão vai ser legal para discutirmos futuramente nosso conteúdo.

Abraços e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
