### ISSUE TITLE
App Alura 

### ISSUE THREAD

**Issue by ingriddelima** [caelum/alura-funcionalidades#847]
Pelo app da Alura não esta sendo possível fazer qualquer curso completo. Sempre que preciso fazer os exercícios propostos, ver artigos, podcast, ativar legendas, entre outros, ele sinaliza error 404. Eu apenas consigo assistir os vídeos e acelerar velocidade. Uso app baixado pela Play Store.

Também faltou um botão de suporte ao usuário dentro do app.

**Comment by felipetorres** [comment]
Oi Ingrid,

me manda mais detalhes (como: seu usuário, versão do app e versão do seu Android) para aplicativos@alura.com.br e a gente continua a conversa por lá, só pra não expor aqui os seus dados, tá?

Te espero no email,
Abraço!

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
