### ISSUE TITLE
Sugestão na plataforma da Alura

### ISSUE THREAD

**Issue by LawrenceMiranda** [caelum/alura-funcionalidades#848]
Olá, gostaria de sugerir que a plataforma tivesse (se tem, eu não achei) algum botão para usar tema preto, com background preto e diminuindo assim a iluminação geral, reduzindo a quantidade de luz (princ/te azul) para os olhos. Obrigado.

**Comment by AlexseySilva** [comment]
Já tem essa ideia.
Vou deixar o link para você ver
https://github.com/caelum/alura-funcionalidades/issues/58

**Comment by giovana-armidoro** [comment]
oi gente, realmente o modo escuro é algo bem pedido pelos alunos mas, como o Arthur comentou nessa [issue](https://github.com/caelum/alura-funcionalidades/issues/800) nós já analisamos essa possibilidade mas infelizmente ainda não conseguimos dar um prazo para essa demanda

Por enquanto podem tentar usar a extensão do Chrome "dark reader", que força o dark mode nas páginas.

abraços e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
