### ISSUE TITLE
Tema Escuro

### ISSUE THREAD

**Issue by lucasvinicios** [caelum/alura-funcionalidades#849]
Sugiro que a plataforma tenha a opção de habilitar o tema escuro não somente na página de acesso aos vídeos mas também em toda a plataforma!

**Comment by artnicodemus** [comment]
Olá @lucasvinicios tudo bom? Muito obrigado pela sugestão!

Recentemente analisamos a possibilidade de implementar darkmode em toda a Alura, mas infelizmente não temos um prazo de quando isso será disponibilizado ):
Uma dica para quebrar galho seria usar a extensão do Chrome "dark reader", que força o dark mode nas páginas. O navegador Opera tem essa opção já nativa.

Abraços e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
