### ISSUE TITLE
possiveis caminhos ao terminar um curso

### ISSUE THREAD

**Issue by gafdot** [caelum/alura-funcionalidades#85]
quando vou fazer um curso existem os pre-requisitos para se chegar àquele tema. poderia ter uma funcionalidade inversa, que quando eu terminar um curso me mostre possiveis caminhos que posso trilhar a partir daquilo que foi aprendido. nao necessariamente sugestoes de cursos que eu possa me interessar, mas sequencias diretas do que foi estudado. sugiro isso porque, aparentemente, nem todos os cursos estao inseridos em uma formaçao.

**Comment by designernatan** [comment]
@gafdot valeu pela sugestão!

de fato a maioria dos cursos hoje está fora das formações, e entendo seu ponto aqui pois no término desses cursos "soltos" a pessoa pode ficar meio perdida sobre o passo seguinte (as Formações foram criadas para ajudar nisso)

temos que melhorar essas recomendações no término dos cursos e na plataforma como um todo também!
