### ISSUE TITLE
Baixar todos os certificados de uma vez

### ISSUE THREAD

**Issue by AshileySabah** [caelum/alura-funcionalidades#850]
Desenvolver funcionalidade para baixar todos os certificados. Hoje, os certificados tem a opção de ser em outros idiomas, além do português. Então o ideal, seria ter um um select com checkbox dos certificados que quero baixar e o idioma, daí dando um ok, ele baixa todos os que eu escolhi.

**Comment by jpgercc** [comment]
Ótima ideia, poderia ter a mesma funcionalidade para colocar no linkedin talvez, mas não sei se na prática funcionaria ou caso já tivesse algum adicionado iria duplicar no site.

**Comment by giovana-armidoro** [comment]
oi Ashiley, obrigada pela sugestão!
faz sentido algo assim, poderia trazer mais agilidade no download dos certificados
por hora não temos planos para mexer nos certificados, mas vou levar a ideia para o time para analisarmos a possibilidade, ok?

abraços e bons estudos! :)

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
