### ISSUE TITLE
Chat Forum na Pagina do curso 

### ISSUE THREAD

**Issue by jpgercc** [caelum/alura-funcionalidades#851]
Gostaria de colocar o chat do fórum na página de cada vídeo do curso. Por exemplo, se eu abro um vídeo sobre cmd, poderia haver uma aba, botão ou algo do tipo onde os participantes comentassem APENAS sobre aquele vídeo e isso poderia ser linkado ao fórum geral. No entanto, se você acessar a página do vídeo, verá apenas a discussão sobre o vídeo. Acho que ficaria mais prático e os participantes usariam e conversariam mais no fórum.

Abraço e obrigado pela atenção!

**Comment by giovana-armidoro** [comment]
oi João, obrigada pela sugestão!
faz bastante sentido pra facilitar a experiência no fórum mesmo
por hora não temos planos de mexer no fórum, mas quando formos fazer isso vamos levar em consideração a sua ideia

abraços e bons estudos!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
