### ISSUE TITLE
Biblioteca Tech

### ISSUE THREAD

**Issue by rodrigobcunha** [caelum/alura-funcionalidades#852]
Algumas pessoas como eu, gostam de aprofundar os conhecimentos através de livros. Então seria interessante no menu da Alura ter uma espécie de biblioteca tech, onde teria vários livros relacionados as escolas da plataforma (Programação, UX, Data Science e etc). 

Talvez se fosse possivel, até uma junção da Alura com a **Casa do Código**, onde os alunos pudessem desfrutar de alguns livros.
Nem que fosse feito por meio de empréstimo, como uma biblioteca, e os alunos tivessem direito a X livros por mês ou apenas alunos do plano Pro tivessem acesso a biblioteca digital.  

O menu, como eu imaginei seria mais ou menos assim: 

![exemplo](https://github.com/caelum/alura-funcionalidades/assets/62352751/b45d9d30-979d-4d78-8fa8-a1b1fa44ac4b)

**Comment by giovana-armidoro** [comment]
oi Rodrigo, obrigada pela sugestão, bem legal a sua ideia!
poderia me contar um pouco mais de como pensou ser a experiência? por exemplo, o que aconteceria após clicar no menu "Biblioteca Tech?"

abraços e bons estudos!

**Comment by rodrigobcunha** [comment]
Ao clicar na aba da 'Biblioteca Tech' abriria uma página, como acontece com o Alura+ por exemplo, onde mostraria as escolas da Alura e os livros disponíveis para os alunos escolherem. 

No exemplo usei livros da 'Casa do Código' mas poderia ser qualquer tipo de conteúdo literário que envolva tecnologia e conteúdos relacionados aos cursos da Alura. 

![bbl tech](https://github.com/caelum/alura-funcionalidades/assets/62352751/7dd329b6-c137-42a6-9486-65311091fbbb)

O aluno poderia adicionar os livros em sua estante digital - que ficaria no dashboard ou no perfil - para que pudesse ler sempre que necessário, seja em casa, na pausa do almoço ou no caminho do trabalho.

**Comment by giovana-armidoro** [comment]
oi Rodrigo, valeu por trazer mais detalhes!
vou levar sua ideia para o time de produto para analisarmos a possibilidade
caso tenha alguma novidade relacionada sobre isso pingo aqui

obrigada novamente pela sugestão
abraços :)

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
