### ISSUE TITLE
Chat Box

### ISSUE THREAD

**Issue by vanessaneves-dev** [caelum/alura-funcionalidades#853]
De onde surgiu a ideia de um chatbox em meio as aulas dos cursos? Que coisa horrível, tenho que ficar inspecionando e excluindo esse ícone péssimo acima de tudo.

**Comment by vanessaneves-dev** [comment]
De onde surgiu a ideia de um chatbox em meio às aulas dos cursos? Que coisa horrível, tenho que ficar inspecionando e excluí esse ícone terrivelmente acima de tudo.


No mínimo deve haver uma opção visível para fechar isso

**Comment by vanessaneves-dev** [comment]
![image](https://github.com/caelum/alura-funcionalidades/assets/113128675/147aa368-9283-488f-b25f-14d890720d0b)

**Comment by giovana-armidoro** [comment]
oi Vanessa, obrigada por trazer seu feedback
sentimos muito que sua experiência não tenha sido agradável 

a Luri é a nova IA da Alura e foi desenvolvida para ajudar os alunos e alunas nas dúvidas durante as aulas, ela ainda está na versão Beta e estamos coletando feedbacks para sabermos os pontos que podemos melhorar
vamos analisar a possibilidade de disponibilizar a opção de não exibir o ícone da Luri
qualquer novidade te atualizo por aqui, ok?

abraços e bons estudos!

**Comment by giovana-armidoro** [comment]
Vanessa,

enquanto não conseguimos resolver, uma dica que me deram aqui é usar uma extensão chamada [Stylebot.](https://stylebot.dev/)

com ela habilitada, colocar um "display: none" no elemento HTML da Luri pegando pela classe (.chatbot-cta-action).

sei que não é o ideal, mas assim rolaria resolver imediatamente.

me fala se conseguiu depois?

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
