### ISSUE TITLE
Sugerir Alteração abranger as opções dos quizzes

### ISSUE THREAD

**Issue by Levieber** [caelum/alura-funcionalidades#854]
- Não encontrei algum lugar mais específico para sugerir alterações em opções.
- Pode ser uma forma fácil de sugerir alterações para as opções de quizzes, tanto da explicação quanto da opção em si.

**Comment by designernatan** [comment]
@Levieber valeu pela sugestão!

vamos dar uma olhada no futuro de médio prazo, ideal é ter essa opção mesmo

abcs!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
