### ISSUE TITLE
Adicionar linguagem para certificado de curso

### ISSUE THREAD

**Issue by dccouto280** [caelum/alura-funcionalidades#855]
Olá!

Sou de Portugal, e gostaria que os idiomas que os certificados têm, como Pt Br, Inglês e Espanhol, tivesse em Português Portugal também!

Dado que as empresas aqui, levam mais a sério se tiver em Português Portugal.

Continuação de um excelente trabalho!

Com os melhores cumprimentos, 
Diogo Couto

**Comment by designernatan** [comment]
@dccouto280 valeu pela sugestão!

hoje temos apenas nesses 3 idiomas mesmo por conta do volume que temos exatamente nesses 3 idiomas específicos

um caminho é tentar pingar no [contato da alura](https://www.alura.com.br/contato) para verificar se algo pode ser feito, mesmo em caráter de exceção

abcs!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
