### ISSUE TITLE
Modo escuro em todo o site Alura

### ISSUE THREAD

**Issue by rishardson** [caelum/alura-funcionalidades#856]
Deveria ter um modo escuro para todo o site, inclusive para a área de dashboard.

**Comment by designernatan** [comment]
@rishardson valeu pela sugestão!

tudo bom? Muito obrigado pela sugestão!

há uns meses analisamos a possibilidade de implementar darkmode em toda a Alura, mas infelizmente não temos um prazo de quando isso será disponibilizado :/

Uma dica para resolver hoje seria usar a extensão do Chrome "dark reader", que força o dark mode nas páginas. O navegador Opera tem essa opção já nativa

abcs!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
