### ISSUE TITLE
Dar "likes" e comentar postagens no forum. 

### ISSUE THREAD

**Issue by GuilhermeABRoncari** [caelum/alura-funcionalidades#857]
Dar likes ou upvotes, reações, etc... em postagens que ja foram resolvidas no forum, e também ter a possibilidades de adicionar comentários pequenos sobre a postagem depois de ela já ter sido marcada como concluída!

Por exemplo, achei uma postagem que me ajudou a corrigir parcialmente meu problema, tive de fazer algumas adaptações e talvez outras pessoas tivessem com o mesmo problema que eu mas como ela já estava marcada como resolvido não pude contribuir de nenhuma maneira com a minha solução na mesma postagem no forum. Então minha sugestão é bem simples, mesmo que a postagem no forum ja esteja resolvida, dar a possibilidade de fazer comentários pequenos complementando a resposta e também uma forma de agregar aquela interação com um feedback qualquer, seja ele um like, upvote, etc.

Aqui segue o exemplo que comentei: https://cursos.alura.com.br/forum/topico-sugestao-aplicacao-nao-se-registra-no-eureka-server-spring-boot-3-306057

Nessa postagem, meu problema foi parcialmente corrigido com essa resposta, então tive de adapta-la! Seria interessante deixar a minha adaptação como um comentário para agregar mais possibilidades de ajudar as pessoas!

Isso é tudo! Muito obrigado pela atenção e até a próxima!

**Comment by designernatan** [comment]
@GuilhermeABRoncari valeu pela sugestao!

o [Paulo sugeriu algo assim](https://github.com/caelum/alura-funcionalidades/issues/2) tbm há uns anos, mas nunca conseguimos parar para puxar algo assim

casa bem com a situação que você passou!

caso priorizemos isso no futuro de longo prazo, pingamos aqui :))

abcs!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
