### ISSUE TITLE
acessibilidade para pessoas com deficiência auditiva 

### ISSUE THREAD

**Issue by gabswyl** [caelum/alura-funcionalidades#858]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

somente o curso de JavaScript e HTML: desenvolva um jogo e pratique lógica de programação possui legenda automatica, e outros cursos de front end, programação, ux design etc não possui legenda automatica, e isso é ruim para pessoas que possuem deficiência auditiva. 

por favor, poderiam implementar legenda automática em todos cursos da alura? 

grato, 
gabriel vilarino

**Comment by designernatan** [comment]
@gabswyl valeu pela sugestao!

Nós estamos buscando sempre deixar a plataforma mais acessível, antigamente os cursos eram lançados sem transcrição, buscamos melhorar nossos processos e isso hoje já não acontece mais

Sobre as legendas, a falta delas sempre foi algo que também nos incomodou, e de um tempo pra cá começamos a investir mais energia nisso, o cenário ideal seria que todos os cursos tivessem legendas, sabemos que ainda estamos longe mas caminhando forte nesse sentido

abcs!

**Comment by gabswyl** [comment]
showw de bola natan! poderia me dizer até que prazo esse implementacao vai
ficar disponivel na plataforma?

Em ter., 29 de ago. de 2023 às 14:25, Natan Souza ***@***.***>
escreveu:

**Comment by designernatan** [comment]
opa gabriel, infelizmente nao consigo te passar um prazo, mas temos times olhando isso bem de perto :))

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
