### ISSUE TITLE
Reset dos cursos já concluídos. 

### ISSUE THREAD

**Issue by luiscarvalhojr** [caelum/alura-funcionalidades#859]
Possibilidade de resetar cursos já concluídos.

**Comment by designernatan** [comment]
@luiscarvalhojr valeu pela sugestao!

sem planos por hora para reset de cursos, desenvolvemos o 'sair do curso' a fim de melhorar a organização da dashboard do aluno, mas o progresso é para continuar ali mesmo

abcs!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
