### ISSUE TITLE
Avançar automaticamente para o próximo Tópico do curso

### ISSUE THREAD

**Issue by sergioduartedba** [caelum/alura-funcionalidades#86]
Gostaria de sugerir algo que faz falta e existe em alguma outras plataformas de estudo, que é iniciar automaticamente o próximo tópico do curso ( o aluno marca uma opção ), sem precisar clicar no play toda vez que termina um vídeo; parece uma bobagem, mas clicar para ir para o próximo tópico, principalmente em cursos de formação que tem uma quantidade enorme de vídeos curtos, além de ser muito chato, atrapalha a concentração e rendimento nos estudos; além do mais, muitas vezes você quer estudar um pouco mais afastado do PC ou notebook, e da forma como é hoje, você precisa estar sempre bem próximo

**Comment by designernatan** [comment]
oi @sergioduartedba valeu pela sugestao, esse é um que as vezes o pessoal pede mesmo

vc pode [entrar na discussao aqui nessa issue?](https://github.com/caelum/alura-funcionalidades/issues/46)

tem alguns pontos de reflexão tbm
