### ISSUE TITLE
Espaçamento entre o ícone e o texto do botão "PRÓXIMA ATIVIDADE"

### ISSUE THREAD

**Issue by Leonardo-AD** [caelum/alura-funcionalidades#860]
O botão "PRÓXIMA ATIVIDADE" no **topo do vídeo** está sem espaço entre o ícone e o texto "➡PRÓXIMA ATIVIDADE" este mesmo botão abaixo da seção de Transcrição está com o espaçamento **correto** "➡ PRÓXIMA ATIVIDADE". 

Este comportamento só é visto **apenas** no topo dos **vídeos**.

**Comment by designernatan** [comment]
valeu leonardo, pegamos essa aqui essa semana :))

n precisava ter fechado a issue n <3

valeu mesmo! Otimo feriado!

**Comment by Leonardo-AD** [comment]
Fechei a issue porque vi que estava tudo corrigido 😄

Agradeço pelo feedback. Ótimo feriado pra você também!
