### ISSUE TITLE
Possibilidade de gerar um certificado com cursos específicos

### ISSUE THREAD

**Issue by RDiter** [caelum/alura-funcionalidades#861]
Como tenho cursos em áreas diferentes, seria interessante poder gerar um certificado com um conjunto de cursos. Por exemplo, quero colocar no meu portfólio um certificado completo com todos os cursos que fiz em HTML e CSS, separado dos que tenho em JAVA, pois fica visualmente ruim deixar um certificado para cada curso, e tem informações demais para juntar todos meus certificados da Alura.

**Comment by laiscavalcanti** [comment]
Olá, @RDiter , nesse caso, você pode compartilhar seus certificados de formações, nesses certificados os cursos ficam juntos e não precisa que você compartilhe de um a um.

Abraço!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
