### ISSUE TITLE
Markdown na bibliografia

### ISSUE THREAD

**Issue by Lucas-Dino** [caelum/alura-funcionalidades#862]
Galerinha da alura, ajudem nos ai por favor, usar `markdown` na bibliografia seria _pra lá de muito bom_ para a estilização e o texto não ficar sendo traduzido para código de caracteres quando entra na edição da bibliografia, caso isto não seja viável, ai esta dois problemas, texto não fica com as **quebras de linhas para estilização** e fica sendo traduzido ao utilizar **caracteres especiais**

**Comment by andradeisadora** [comment]
oi @Lucas-Dino 
pode me explicar melhor sobre a sugestão? onde fica esse ajuste sugerido?

**Comment by andradeisadora** [comment]
vou fechar a issue, mas pode voltar a comentar se quiser :)
