### ISSUE TITLE
Baixar certificado com frente e verso

### ISSUE THREAD

**Issue by prof-phmm-paulo** [caelum/alura-funcionalidades#863]
Olá, gostaria de sugerir que o botão para baixar o diploma entregue a frente e o verso do diploma no mesmo arquivo.

Na presente data o botão "baixar certificado" em "perfil & certificados" entrega apenas uma das partes conforme imagem:
![image](https://github.com/caelum/alura-funcionalidades/assets/107412780/3cc86656-d4ed-4967-9290-a301d2a00713)

**Comment by masromao** [comment]
Olá @prof-phmm-paulo , obrigado pela sugestão!

Por enquanto a melhor forma de fazer isso é salvar separadamente, uma página de cada vez mesmo e depois juntar os arquivos em alguma plataforma, como por exemplo o ILovePDF.com, ou no próprio Adobe Acrobat.

Vou levar a sugestão pro time para entendermos a viabilidade técnica, mas por hora, não conseguimos passar um prazo pra retorno dessa atualização.

Espero ter ajudado!
Abraços e bons estudos. :)

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, mas podem voltar a comentar se quiserem :)
