### ISSUE TITLE
Acesso a todos os certificados dos times

### ISSUE THREAD

**Issue by prof-phmm-paulo** [caelum/alura-funcionalidades#864]
Olá, gostaria de sugerir um campo para acesso a todos os certificados de um ou de todos os times, em bulk.
Algo como um pdf contendo os certificados, em sequência, de um time específico ou dos times selecionados.

O objetivo é imprimir os certificados para entregar para os meus times.

**Comment by masromao** [comment]
Olá @prof-phmm-paulo , muito obrigado pela ótima sugestão!

Realmente seria interessante essa opção de acessar todos os certificados em bulk.

Vou levar a sugestão pro time da plataforma para entendermos a viabilidade técnica dessa feature, mas por hora, não conseguimos passar um prazo pra retorno.

Abraços e bons estudos. :)

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, mas podem voltar a comentar se quiserem :)
