### ISSUE TITLE
Reprodução automática nos videos

### ISSUE THREAD

**Issue by MarceloMFreitas** [caelum/alura-funcionalidades#865]
Os vídeos poderiam iniciar automaticamente e passar para a próxima atividade assim que o video terminar, essa função pode ser habilitada e desabilitado pelo usuário

**Comment by masromao** [comment]
Olá @MarceloMFreitas , obrigado pela sugestão!

Já é possível fazer isso dentro do ambiente de aulas! Abrindo um vídeo qualquer do curso, você ativa o modo de reprodução automático e seleciona se quer apenas os vídeos ou inclui as atividades também (ver imagem do print).

Essa opção ficará gravada ao longo do curso. Você pode alterar ou desativar quando quiser usando o mesmo caminho.

![Screenshot 2023-09-28 at 12 26 26](https://github.com/caelum/alura-funcionalidades/assets/86667938/9cc0b037-65d9-41ea-baf7-8504bee2ca2d)

**Por enquanto essa funcionalidade está habilitada apenas para pessoa física, alunos e alunas de empresas ainda não possuem acesso a essa feature!

Espero ter ajudado!
Abraço e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, mas podem voltar a comentar se quiserem :)
