### ISSUE TITLE
Mudança nos cards com atualização na formação 

### ISSUE THREAD

**Issue by vkhydra** [caelum/alura-funcionalidades#866]
Conforme a imagem podemos ver os cards com novas formações, deveria haver a possibilidade de limpar esses cards ou ocultá-los, pois eles se acumulam, dificultando com o aumento da paginação.

![image](https://github.com/caelum/alura-funcionalidades/assets/25714058/905c60c6-fb1f-4f12-bce5-622dbb8d0076)

**Comment by giovana-armidoro** [comment]
Oi, Victor. Obrigada pela sugestão!
Realmente faz sentido, esses cards não estão com uma experiência muito legal né?
Levei essa sugestão para discutirmos aqui no time, não tenho uma previsão para mudanças, mas qualquer atualização aviso aqui, ok?

Abraços e bons estudos!

**Comment by andradeisadora** [comment]
vou fechar a issue pessoal, mas podem voltar a comentar se quiserem :)
