### ISSUE TITLE
Login UniBB

### ISSUE THREAD

**Issue by DaltonSoffiatti** [caelum/alura-funcionalidades#867]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.
Cursos sugeridos que solicitam login e não oferecem opção para contas corporativas.
Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.
Assim como existem opções de login com Facebook e Google, poderia haver uma opção para alunos da UniBB que são direcionados para páginas de Login | Alura - Cursos online de tecnologia...

**Comment by giovana-armidoro** [comment]
Oi Dalton, obrigada pela sugestão!
Alunos de contas corporativas tem acesso a conteúdos determinados que são liberados pela empresa, por isso você faz login por um local diferente, que é o login específico da sua empresa. Provavelmente foi por isso que foi solicitado login quando você tentou acessar outros conteúdos.
Então, como o login é feito em um outro lugar específico, não temos planos no momento de colocar uma opção de acesso corporativo no login geral.

Obrigada, abraços e bons estudos! :)

**Comment by andradeisadora** [comment]
oi pessoal :) vou fechar a issue mas podem vontar a comentar se quiserem
