### ISSUE TITLE
Refazer curso do zero com atualização da data do certificado

### ISSUE THREAD

**Issue by sergiopel** [caelum/alura-funcionalidades#868]
Assim como eu, tenho quase certeza que vários outros assinantes estejam passando pela mesma dificuldade que eu, tendo que acionar o suporte de vocês para que seja analisado e talvez atendido como "extrema exceção". A implementação dessa funcionalidade eu tenho que certeza que seria muito útil para a Alura e principalmente para os assinantes.
Essa dificuldade hoje, é a de refazer um curso que já foi realizado, mas o certificado continuar com a data de término antiga. Pensa bem, se eu estou refazendo um curso, nada mais justo que a data de término também seja atualizada ou que gere outro certificado com essa data do término atualizada. Assim eu posso postar novamente esse certificado no Linkedin e provar que eu fiz esse curso recentemente e não há 2 ou 3 anos atrás, por exemplo.
Imagine que o treinamento seja presencial na Caelum (sou ex-aluno). Eu cheguei a fazer um treinamento de Java com OO presencialmente e depois de alguns anos eu refiz esse treinamento também na forma presencial. A Caelum por sua vez, de forma correta, emitiu um novo certificado com a data do término atualizada.
Então se na forma presencial isso funciona bem, na forma online também deveria ser considerado normal. A minha sugestão seria armazenar um segundo, terceiro, quarto certificado, de acordo com o início e o término da conclusão do curso, não importando quantas vezes o assinante refez o curso.
Outra funcionalidade é que ao refazer um curso já finalizado, que pudesse zerar todas as atividades e exercícios já concluídos anteriormente, para que pudéssemos treinar novamente o que aprendemos ou que estamos reaprendendo.

**Comment by giovana-armidoro** [comment]
Oi Sérgio, obrigada pela sugestão!

Não temos planos no momento para fazer uma funcionalidade de resetar o curso ou mudar a data de finalização do certificado, mas de qualquer forma vou levar sua sugestão para discussão na equipe.

Abraços e bons estudos!

**Comment by sergiopel** [comment]
Ok Giovana, espero que a equipe implemente essa funcionalidade, pois será muito importante para quem pretende refazer um curso que já fez anteriormente.

**Comment by andradeisadora** [comment]
oi pessoal :) vou fechar a issue mas podem vontar a comentar se quiserem
