### ISSUE TITLE
Filtros de busca para os cursos descontinuados

### ISSUE THREAD

**Issue by legendaryredfox** [caelum/alura-funcionalidades#869]
Na Alura, existem cursos descontinuados que podem vir a ser interessantes para alguns assinantes. Quando eu perguntei no suporte onde acessá-los, me passaram um link (https://cursos.alura.com.br/conteudos-descontinuados/formacoes). No entanto, não há um jeito de filtrar os cursos por área (front-end, back-end, etc), e é necessário carregar as páginas uma a uma e usar ctrl+F para procurar os conteúdos. Seria interessante que houvesse um jeito melhor de acessar esse conteúdo, que pode ainda ser relevente para muitos assinantes.

**Comment by giovana-armidoro** [comment]
Oii, obrigada pela sugestão!

Faz sentido seu ponto. Mas temos o foco de deixar disponíveis conteúdos atualizados e que estão ok com nossa curadoria de qualidade. Mas ainda assim sua sugestão vai ser legal para discutirmos numa possível melhora da busca no futuro.

Mexemos na busca a pouco tempo, então acredito que próximas melhorias serão no futuro de mais longo prazo.

Abraços e bons estudos!

**Comment by andradeisadora** [comment]
oi pessoal :) vou fechar a issue mas podem vontar a comentar se quiserem
