### ISSUE TITLE
Executar vídeos automaticamente

### ISSUE THREAD

**Issue by thiagopaschoal** [caelum/alura-funcionalidades#87]
Gostaria que durante ao finalizar um vídeo o próximo já executasse automaticamente. Um exemplo disso é a própria Udemy.

**Comment by designernatan** [comment]
oi @thiagopaschoal  valeu pela sugestao, esse é um que as vezes o pessoal pede mesmo

vc pode [entrar na discussao aqui nessa issue?](https://github.com/caelum/alura-funcionalidades/issues/46)

tem alguns pontos de reflexão tbm
