### ISSUE TITLE
Melhorar o certificado para ser utilizado em órgãos públicos para progressão de carreira

### ISSUE THREAD

**Issue by umarley** [caelum/alura-funcionalidades#870]
Hoje o certificado da formação não possui CNPJ e nem data inicio e final do de realização da formação, uma vez que para progressão por capacitação em órgãos públicos é exigido CNPJ, data inicio e final da realização do curso/formação, conteúdo programático e carga horária total, conforme imagem abaixo.

Sendo assim, é importante que seja adicionado o CNPJ da instituição bem como a data inicio e final da realização.

![image](https://github.com/caelum/alura-funcionalidades/assets/8119489/85d0ea86-5d53-4b73-8bee-2558a16f438c)

**Comment by lgfvarella** [comment]
Essas informações são cruciais para a apresentação de progressões na carreira pública. A Alura poderia fazer essa alteração, o que seria muito útil, já que o certificado completo costuma gerar dúvidas no RH e eles precisam refazer os cálculos para verificar se a carga horária foi cumprida.

**Comment by giovana-armidoro** [comment]
Oii, obrigada pela sugestão!

Hoje você consegue pegar o certificado formal de um curso clicando em um botão que fica logo abaixo do certificado. O certificado formal contém o CNPJ, carga horária, data de início e fim e conteúdos que foram abordados. Assim, você conseguiria pegar o certificado formal de cada curso da formação.
Ou você consegue também entrar em contato com o suporte e solicitar o Certificado de Licença Capacitação, que é um certificado que contém essas informações também, ele viria em um certificado só as informações de todos os cursos que você solicitar, com a carga horária total.

Espero que isso possa ajudar.

Abraços e bons estudos!

**Comment by andradeisadora** [comment]
oi pessoal :) vou fechar a issue mas podem vontar a comentar se quiserem
