### ISSUE TITLE
Navegação na aba formações 

### ISSUE THREAD

**Issue by RobervanSouza** [caelum/alura-funcionalidades#871]
Quando estou logado e clicar em formações,  faz a navegação normal e continuo logado,  porém quando clico na opção " confira aqui dicas por onde começar ", abri uma nova aba, mas eu já não estou logado, nas opções de curso que tem nessa aba, quando clicar em um deles eu já tenho que logar novamente.

**Comment by andradeisadora** [comment]
oi @RobervanSouza obrigada pela sugestão :)
pois é, seria mais interessante continuar logado mesmo. Vou levar a ideia pro time pra gente pensar um pouco sobre esse fluxo mas não consigo te prometer prazo :(

abraço e bons estudos!

**Comment by RobervanSouza** [comment]
Obrigado,  caso  tenha algum retorno compartilhar comigo para eu saber se deu certo!

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
