### ISSUE TITLE
Melhoria na qualidade do áudio das aulas e regulação do volume

### ISSUE THREAD

**Issue by jheorgenes** [caelum/alura-funcionalidades#872]
Em todas as vídeo aulas existentes na Alura, existe o controle de volume. Isso é bem útil inclusive, mas o que deixa a desejar é o máximo do volume. Não tenho nenhum problema de audição, nem problemas técnicos com fones, etc. Qualquer outra plataforma em vídeo que utilizo no meu navegador, a máxima é espetacular.  Mas considero o máximo de volume das aulas da Alura muito baixo. Pode ser que preferiram fazer assim para não agravar a audição de alguém, porém poderiam ter regulado isso no controle de volume. Talvez a ferramenta que utilizam para reprodução dos vídeos possa ser o problema. Enfim. 
As vezes trabalhamos em ambientes com muito barulho e ruídos externos acabam surgindo e atrapalhando, consequentemente.
Essa pode ser uma sugestão pessoal minha, mas é um ponto de melhoria que acho que seria muito interessante se houvesse uma forma de implementar.

**Comment by juliagodinhoo** [comment]
Oi @jheorgenes, obrigado pela sua sugestão!

No momento não estamos planejando ajustes em áudio, mas levarei seu pontos para discutirmos internamente. Caso no futuro a gente venha fazer melhorias nesses pontos, levaremos sua sugestão em consideração.

Abraços e bons estudos! 😄

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
