### ISSUE TITLE
Download do material

### ISSUE THREAD

**Issue by mrojrti** [caelum/alura-funcionalidades#873]
Minha sugestão é uma maneira de baixar todo o conteúdo do curso após a conclusão do mesmo.
Por exemplo, eu tenho costume de assistir todo o conteúdo primeiro no modo acelerado para ter uma boa visão.
Depois volto do início para assistir na velocidade normal e fazer os exercícios e anotações, mas o ideal seria fazer as anotações no material baixado.

É cansativo ter que ficar copiando e colando boa parte das coisas.

Sei que vocês precisam evitar o download excessivo até por conta de contas trial e tudo mais, por isso a ideia de deixar baixar apenas depois de o curso for concluído pelo menos uma vez.

**Comment by juliagodinhoo** [comment]
Olá @mrojrti, muito obrigado pela sua sugestão!

Atualmente, não temos planos para incluir a opção de baixar os conteúdos do curso, mas que tal experimentar o Notion? Ele é uma ótima ferramenta para fazer anotações durante as aulas. Além disso, criar suas próprias anotações pode ser muito útil para a memorização, sem falar que você pode escrever do jeito que for mais confortável e legível para você. O que acha dessa ideia?

Abraços e bons estudos 😄

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
