### ISSUE TITLE
Melhora na UX de apresentação do curso

### ISSUE THREAD

**Issue by mthquevedo** [caelum/alura-funcionalidades#874]
Hoje quando vamos conhecer um curso novo assistimos seu primeiro vídeo para saber mais sobre o que ele oferece, mas nesse momento somos **bombardeados com pop-ups** de "Você não está inscrito no curso" e temos que fechá-los para continuar o vídeo de introdução. Além disso, temos **2 faixas agressivas** em cima e embaixo do player "gritando" que não nos inscrevemos ainda.

Essa experiência podia ser mais tranquila, afinal de contas o usuário está apenas conhecendo o curso para saber se faz sentido começa-lo de fato, esse esforço de clicar em vários "x" apenas para assistir a introdução torna esse processo muito moroso.

**Comment by andradeisadora** [comment]
oi @mthquevedo 
realmente, é meio agressivo mesmo
mas a ideia é que seja bem perceptivel que a pessoa não se matriculou no curso pra não correr o risco de assistir o curso inteiro sem se matricular

obrigada pela sugestão! abraço e bons estudos 🙂

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
