### ISSUE TITLE
Verificação em duas etapas

### ISSUE THREAD

**Issue by DAUUX** [caelum/alura-funcionalidades#875]
Um dos modos encontrados para tornar as contas mais seguras foi a verificação em duas etapas. Esse sistema é um mecanismo extra de defesa. O seu objetivo é ter mais uma etapa de verificação, para bloquear invasões de pessoas má intencionadas às contas dos usuários. 
O nome é “verificação em duas etapas” por precisar de dois códigos de verificação diferentes. O primeiro é, geralmente, a senha do usuário, precisando de um segundo código de segurança para acessar a conta.

Na plataforma da alura atualmente, quando faço a modificação de senha, deveria pelo menos mandar um email avisando que senha foi alterada, desta forma para uma melhor segurança pelo uma autenticação de dois fatores faz-se necessario. varias plataforma oferece essa função não entendo o por que na alura não tem.

**Comment by andradeisadora** [comment]
oi @DAUUX 🙂 
obrigada pela sugestão! não estamos com planos no momento de fazer ajustes na recuperação de senha mas vou deixar a ideia salva pra levarmos em consideração
abraço e bons estudos!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
