### ISSUE TITLE
Melhorias na plataforma

### ISSUE THREAD

**Issue by romerofartura** [caelum/alura-funcionalidades#876]
Acertar o cadastro para emissão da nota fiscal ao entrar na plataforma..
O CEP é logo depois do telefone, para não ter que digitar parte do endereço e depois ele ser apagado.
Após digitar o CEP o logradouro é só o logradouro, o endereço não vai a cidade nem o bairro.
Ao salvar não muda de aba, não dá mensagem, parece que não gravou.
Pra quem trabalha com tecnologia e adquire o curso para evoluir isso não dá uma boa impressão.

**Comment by designernatan** [comment]
@romerofartura valeu pela sugestao!

estamos para dar uma atenção maior no futuro próximo a essa parte da plataforma

abcs

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
