### ISSUE TITLE
Plano Duo 

### ISSUE THREAD

**Issue by welington2001** [caelum/alura-funcionalidades#877]
Esse plano seria otimo para quem e deixa baxa renda e que possa dividir com seus colegas, mas ai funcionaria como um "analise de credito" só para quem recebe menos que um salario e meio.

**Comment by andradeisadora** [comment]
oi @welington2001 
obrigada pela sugestão! no momento não está no nosso planejamento criar um novo plano :( mas vou deixar salva sua sugestão para considerarmos no futuro

abraço e bons estudos!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
