### ISSUE TITLE
Legenda nas aulas ao vivo

### ISSUE THREAD

**Issue by welington2001** [caelum/alura-funcionalidades#878]
As legendas seria ótimo para a Alura pois assim ela possa atender os deficientes auditivo com mais eficiência

**Comment by andradeisadora** [comment]
oi @welington2001 
obrigada pela sugestão! realmente, seria ótimo termos legendas, já está no nosso radar :)
Queremos trazer essa opção no futuro, mas não tenho prazo de quando isso acontecerá

abraço e bons estudos!

**Comment by eduardoluiz1** [comment]
Alem de ajudar na acessibilidade tambem possibilita realizar o curso sem ter que ligar o som ou usar fones em ambientes menos propícios para fazer o curso (tipo alguém que quer fazer isso no horário de trabalho de forma discreta. Não me julguem, quero entrar na area e tenho que aproveitar todas as oportunidades para aprender)

**Comment by welington2001** [comment]
Boa sugestão Eduardo!

Em qua., 27 de dez. de 2023 às 14:43, eduardoluiz1 ***@***.***>
escreveu:

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
