### ISSUE TITLE
Plano PCD

### ISSUE THREAD

**Issue by welington2001** [caelum/alura-funcionalidades#879]
Esse plano seria para motivar a inclusão e diversidade na área da tecnologia

**Comment by andradeisadora** [comment]
oii @welington2001 
obrigada pela sugestão! no momento não está no nosso planejamento criar um novo plano :( mas vou deixar salva sua sugestão para considerarmos no futuro

abraço e bons estudos!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
