### ISSUE TITLE
Navegabilidade do Fórum(na versão web)

### ISSUE THREAD

**Issue by alanbritodossantos** [caelum/alura-funcionalidades#88]
Olá, eu gostaria de dar uma dica de navegabilidade sobre um ponto que não sei se já existe aqui no fórum. Todas as vezes que vou clicar em alguma dúvida existem no mesmo(fórum), eu consigo acessar normalmente, mas senti falta de um botão que tivesse a função de voltar para página anterior.

**Comment by designernatan** [comment]
oi @alanbritodossantos 

pode elaborar mais? Nao entendi exatamente o fluxo aqui

acesso via desktop? Onde voce cai no forum exatamente?

abcs!

**Comment by alanbritodossantos** [comment]
Olá @designernatan 
Imagina que agora você esta com o notebook e esta na pagina do fórum do curso, ex:(https://cursos.alura.com.br/forum/categoria-programacao/todos/1)
nesse pagina informada logo acima tem dúvidas de vários alunos da alura... bom  agora vamos clicar na primeira duvida por exemplo(https://cursos.alura.com.br/forum/topico-updatecadastro-104543).. nesse momento tudo ocorreu bem.. mas se se agora eu quero voltar para a pagina anterior como eu faço? 
O único botão que existe é o botão "Fórum" que não volta para a pagina anterior, mas sim para a pagina Fórum onde lá tem todas as duvidas de todos os cursos...

**Comment by designernatan** [comment]
ahhhhhhhhhh que falha nossa! Valeu @alanbritodossantos 

não sei se tem algum "SEO reaons" aqui mas vamos discutir isso aqui, ok?

recentemente subiu um _breadcrumb_ nas categorias, mas nao foi para a pergunta

valeu mesmo pela sugestao!

**Comment by peas** [comment]
pessoal, o botao verde "programacao" nao volta exatamente ai? 
![Screen Shot 2020-03-05 at 11 25 23](https://user-images.githubusercontent.com/71636/75990726-15cc2700-5ed4-11ea-869c-7d56cb95bd0b.png)
