### ISSUE TITLE
PLANO DE ESTUDO

### ISSUE THREAD

**Issue by milenacm** [caelum/alura-funcionalidades#881]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quando estiver pesquisando cursos pra fazer se tiver um curso que já tenha incluído no plano de estudo, apontar com um "P" ou outra legenda que o curso já foi incluído no plano de estudos

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

**Comment by andradeisadora** [comment]
oi @milenacm 
obrigada pela sugestão! no momento não está nos nossos planos mexer na busca de cursos :( mas vou deixar salva sua sugestão para considerarmos no futuro

abraço e bons estudos!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
