### ISSUE TITLE
Status curso

### ISSUE THREAD

**Issue by milenacm** [caelum/alura-funcionalidades#882]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quando estiver pesquisando curso, indicar com uma cor diferente se o curso está "parado" no plano de estudos, em andamento ou concluído.

Imaginei essa "cor" no preenchimento do retângulo que informa o nome do curso, descrição e duração.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

**Comment by andradeisadora** [comment]
oi @milenacm 
obrigada pela sugestão! recentemente fizemos ajustes na busca de conteudos e não planejamos mexer em breve :( vou deixar salva sua sugestão para considerarmos no futuro

abraço e bons estudos!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
