### ISSUE TITLE
Competências adquiridas com a realização o curso ou formação.

### ISSUE THREAD

**Issue by avena** [caelum/alura-funcionalidades#883]
Sei que possível clicar no curso ou formação e vai abrir o LinkedIn para incluir. 

Mas os campos de competências fica em branco.

![image](https://github.com/caelum/alura-funcionalidades/assets/633254/d4ce93dd-aad9-4af5-aeb9-c2c40576cd04)

Se não for possível já preencher, que nos cursos ou formações tenha algo que incluía algo que ao concluir vai ter  Ex: Competências: javascript, typescript, aws

o Coursera por exemplo tem algo chamado: **Habilidades que você terá**

![image](https://github.com/caelum/alura-funcionalidades/assets/633254/34984055-0010-46f3-a414-9b655e921842)

**Comment by juliagodinhoo** [comment]
Oi @avena, obrigado pela sugestão!

No momento não temos planos de melhorias nesses pontos, mas levarei o que disse para discutirmos internamente.

Abraços e bons estudos! 😄

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
