### ISSUE TITLE
Status de atividade/aula concluída

### ISSUE THREAD

**Issue by emeath** [caelum/alura-funcionalidades#884]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

Atualmente existe a marcação automática de atividade concluída quando terminamos de assistir uma aula. Essa funcionalidade é ótima. Porém sinto falta da possibilidade de eu marcar ou desmarcar manualmente uma atividade como concluída.

Caso eu esteja na metade de um curso e por algum motivo pare, mas eu nao pretendo reiniciar do zero, e sim algumas aulas anteriores. Seria legal poder desmarcar algumas atividades como concluídas para que eu consiga manter o track de onde eu estou recomeçando no curso.

Por exemplo, iniciei o curso X e assisti ate o seguinte ponto:

Aula 01
- [x]  Atividade 01
- [x]  Atividade 02
- [x]  Atividade 03
- [x]  Atividade 04

Aula 02
- [x]  Atividade 01
- [x]  Atividade 02
- [x]  Atividade 03
- [x]  Atividade 04

Aula 03
- [x]  Atividade 01
- [ ]  Atividade 02
- [x]  Atividade 03
- [ ]  Atividade 04

Porem parei o curso e depois de 4 meses retornei nele. Nao pretendo reiniciar do 0 e sim da Aula 02, atividade 02. Entao gostaria de desmarcar manualmente obtendo o seguinte:

Aula 01
- [x]  Atividade 01
- [x]  Atividade 02
- [x]  Atividade 03
- [x]  Atividade 04

Aula 02
- [x]  Atividade 01
- [ ]  Atividade 02
- [ ]  Atividade 03
- [ ]  Atividade 04

Aula 03
- [ ]  Atividade 01
- [ ]  Atividade 02
- [ ]  Atividade 03
- [ ]  Atividade 04

A partir desse ponto nessa situação hipotetica, eu iria assistindo as atividades e a funcionalidade existente de concluir atividades assim que termino de ver o video iria marcando as atividades e dessa maneira conseguirei manter o tracking como se eu estivesse vendo o curso pela primeira vez de forma contínua

**Comment by juliagodinhoo** [comment]
Obrigada pela sugestão, @emeath!

Estamos realizando algumas melhorias na tela de aula e certamente levantaremos esse ponto nas discussões. Não podemos garantir a implementação da funcionalidade, mas ela será discutida com o time. 

Abraços e bons estudos! 😃

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
