### ISSUE TITLE
Remover foto do certificado

### ISSUE THREAD

**Issue by victorwss** [caelum/alura-funcionalidades#885]
Os certificados dos cursos incluem a foto de perfil do usuário. Minha foto é obtida a partir do github, que é essa figura abstrata e sem significado algum que está ao lado do meu nome.

Eu não tenho e não quero ter foto nenhuma, nem no github, nem nos certificados, nem no linkedin e nem em lugar nenhum. No momento, não há forma de se remover a foto do certificado e essa figurinha chata, sem graça e sem significado está aparecendo em todos os meus certificados.

Sugiro que coloquem uma opção "não tenho foto" ou "não quero ter foto", que remova a foto dos certificados.

**Comment by juliagodinhoo** [comment]
Oi @victorwss, entendo totalmente os seus pontos, mas neste momento não estamos com planos de alteração do layout ou outras funcionalidades ligado ao certificado, mas uma possível solução seria você salvar o certificado formal, que não possui foto alguma. Abaixo anexarei o passo a passo de como salvar o certificado formal em formato PDF. 

Espero que tenha conseguido ajudar. Qualquer outra dúvida ou comentário, só falar aqui!

Abraços e bons estudos :)

![Certificado formal](https://github.com/caelum/alura-funcionalidades/assets/150740761/c0366905-dbd2-421c-868b-23e288a78d82)

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
