### ISSUE TITLE
Aceitar caracteres especiais no depoimento de final de curso sem achar que isso é um código malicioso

### ISSUE THREAD

**Issue by victorwss** [caelum/alura-funcionalidades#886]
Ao terminar o curso e escrever nele um depoimento que contenha algo assim:

> `A classe Foobar seria melhor se fosse genérica como Foobar<T>`

Eu recebo uma mensagem de que o depoimento contém código malicioso, pois por alguma razão, o servidor da Alura acredita que o genérico `<T>` é um código malicioso. Penso que isso se deve ao fato de que a funcionalidade acha que estou a tentar um ataque de XSS ao postar algo com os símbolos `<` ou `>`.

Não tentei colocar exemplos em HTML no depoimento, mas acredito que o mesmo comportamento seria disparado.

Assim sendo, a seção de depoimento tem que ser imune a XSS ao mesmo tempo em que aceita que caracteres especiais estejam presentes no depoimento. Mesmo se eu incluir código em Java, JavaScript, C++ ou HTML no depoimento, o depoimento tem que ser aceito e recebido normalmente sem que nada de estranho aconteça nem com quem está postando o depoimento e nem com quem for lê-lo dentro da Alura posteriormente.

**Comment by juliagodinhoo** [comment]
Oi @victorwss!

Hoje temos uma validação para tags HTML, em que algumas passam nessa validação e outras não. Nesse caso, como o <T> não faz parte desse grupo de tags, a gente acaba "recusando" o envio do mesmo. No entanto, no futuro, quando pegarmos essa tela para a melhorarmos, vamos repensar quais tags entram e quais saem.

Muito obrigado por nos ter reportado, abraços!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
