### ISSUE TITLE
[Correção] - Bug Visual.

### ISSUE THREAD

**Issue by oecarvalho** [caelum/alura-funcionalidades#887]
Olá pessoal, essa issue é apenas para sugerir uma correção bem sutil em uma tela que identifiquei recentemente. 

Na tela quando o usuário que já expirou o plano acessa, aparece esse pequeno bug na listagem das novidades da alura:
![image](https://github.com/caelum/alura-funcionalidades/assets/52979989/19f8b645-0f0a-4fb2-aed5-83b8f13ff81e)

notem que as bolinhas que representam lista das formações fica como se estivesse sobrepondo a listagem das novidades.

**Comment by juliagodinhoo** [comment]
Opa @FelipeCarv, muitíssimo obrigado por reportar o bug pra gente 💟 já fizemos o reporte pro time responsável pela plataforma e agora fica com eles o momento de priorizar o bug.

Abraços e bons estudos!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
