### ISSUE TITLE
Bloco de notas

### ISSUE THREAD

**Issue by Anjosgiu** [caelum/alura-funcionalidades#888]
Seria interessante pensar em um bloco de notas para deixar anotado pontos importantes ou informações que julgo necessárias, ás vezes gostaria de anotar algo, alguma funcionalidade, pedaço de código, no meio de uma aula e seria bom armazenar isso sem sair da plataforma para poder ver depois.

**Comment by juliagodinhoo** [comment]
Oi @Anjosgiu, obrigada pela sugestão!

Pensamos em funcionalidade similar a esta há certo tempo, mas ela foi cancelada vez que não atingiu as expectativas esperadas, não apenas em engajamento, como também em outros pontos. Uma possibilidade externa atual seria o uso do Notion para fazer anotações, sendo um ótimo lugar para organizá-las e geri-las em um só lugar.

Abraços e bons estudos! 😄

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
