### ISSUE TITLE
Permitir zoom no video da aula ao assistir no celular, como pode ser feito no YouTube

### ISSUE THREAD

**Issue by carlosasolla** [caelum/alura-funcionalidades#889]
As vezes quando estou assistindo no celular alguns cursos mostram trechos de código que eu gostaria de conseguir ver, mas não consigo, pois a letra acaba ficando muito pequena; Seria bem útil o recurso que tem no Youtube que permite dar zoom no video.

**Comment by juliagodinhoo** [comment]
Oi @carlosasolla, muito obrigado pela sugestão!

De fato faz bastante sentido o que você disse e levarei o seu ponto pro time para fomentar essa discussão, só não consigo te dar um prazo ou uma certeza da implementação da funcionalidade.

Abraços e bons estudos! 😄

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
