### ISSUE TITLE
Reiniciar curso já iniciado

### ISSUE THREAD

**Issue by brennogb** [caelum/alura-funcionalidades#89]
Gostaria de ter a funcionalidade de reiniciar um curso já iniciado, pois, em alguns casos deixo um curso parado e quando vou voltar a assistir, poderia clicar em um botão para que o progresso seja reiniciado. Isso pode acontecer por que o curso foi pausado por muito tempo e eu desejo rever todo o conteúdo.

**Comment by designernatan** [comment]
@brennogb valeu pela sugestao!

tem uma [issue igual a essa aqui](https://github.com/caelum/alura-funcionalidades/issues/11)

vou fechar essa por conta disso, mas em suma estamos vendo de como melhorar a experiência de vocês na hora de refazer um curso

1. Pode me mandar o link do seu perfil da alura dps?
2. Qual curso **hoje** você precisaria resetar (pergunto mais por pesquisa mesmo)

abcs!

**Comment by GuilhermeCesar** [comment]
Acho top também essa funcionalidade
