### ISSUE TITLE
Permitir preencher a tela nos videos do Alura+

### ISSUE THREAD

**Issue by carlosasolla** [caelum/alura-funcionalidades#890]
Quando assisto videos do Alura+ no celular, o vídeo não preenche a tela do celular. Teria que ficar no modo paisagem e preencher a tela toda, mas não faz isso e fica muito pequeno.

**Comment by juliagodinhoo** [comment]
Oi @carlosasolla!

Acabei de testar no aplicativo e de fato o vídeo não preenche horizontalmente por padrão como nos vídeos dos cursos e formações, mas é possível sim deixá-lo em modo paisagem. Para isso, basta **desbloquear o giro da tela** _nas próprias configurações do celular_. Uma vez desbloqueado, coloque seu celular na horizontal que o vídeo ficará em modo paisagem. Acrescento, ainda, que no Alura+ é possível dar zoom no vídeo, como citado por você [aqui ](https://github.com/caelum/alura-funcionalidades/issues/889). Testa e vê se consegue. 

Espero ter te ajudado. Qualquer dúvida ou dificuldade, só comentar aqui! Abraços

**Comment by carlosasolla** [comment]
No meu celular que é um Android motorola one hyper, mesmo com o giro desbloqueado, não preenche a tela toda, ao girar o video continua do mesmo tamanho. Já quanto ao zoom, realmente funcionou no Alura+, isso é bom!

No print de tela abaixo, o celular estava na horizontal (com o giro automatico ativado), mas o vídeo continua na vertical:
![O celular estava na horizontal , mas o video não acompanhou](https://github.com/caelum/alura-funcionalidades/assets/19391283/25b0fb86-020b-444e-a168-5cd882efdabe)

**Comment by juliagodinhoo** [comment]
@carlosasolla verifiquei internamente com o time e, a princípio, não sabemos dizer o que pode ser, ressaltando, inclusive, que testamos em outro celular com o desbloqueio de giro de tela e funcionou perfeitamente. Sendo assim, precisaremos de uma investigação mais aprofundada para entender exatamente o porquê deste comportamento.

Assim como dito nas demais sugestões trazidas, já reportamos a situação e a mesma será investigada e monitorada para ver se isso é um comportamento padrão.

Do mais, agradecemos toda atenção dada reportando e nos respondendo por aqui. 

Abraços e boas festas de fim de ano! 😄

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
