### ISSUE TITLE
Marcar os PodCasts do Alura+ como já ouvidos

### ISSUE THREAD

**Issue by carlosasolla** [caelum/alura-funcionalidades#891]
Poderia ter uma opçao na lista de PodCasts para marcar que determinado podcast já foi ouvido; ocorreu várias vezes de eu só perceber que já ouvi determinado podcast após ouvir um trecho do mesmo.

**Comment by juliagodinhoo** [comment]
Olá @carlosasolla, poderia me explicar um pouco melhor sobre os Podcasts do Alura+? Acredito que você quis dizer sobre os podcasts que existem na plataforma, que não necessariamente estão ligados ao Alura+, seria isso? Além disso, esse ponto que trouxe está ligado ao seu uso no aplicativo ou na plataforma pelo computador? Só pra eu entender melhor e te ajudar de maneira mais certeira

**Comment by carlosasolla** [comment]
Oi Júlia, obrigado por responder.
Quanto eu ouço os podcasts pelo próprio aplicativo da Alura, mesmo que eu já tenha ouvido determinado episódio, não tem nada no aplicativo que demonstre ou filtre os já ouvidos. Seria útil uma indicação de que o episódio já foi ouvido, assim como nas aulas, que tem a indicação de que a aula já foi concluída.

**Comment by juliagodinhoo** [comment]
Imaginei que fosse sobre o mobile, mas perguntei pra ter certeza e não ficar na suposição hahah :)

De fato não tem feedback, diferentemente da plataforma que, ao dar play em algum podcast (seja pelo app, seja pela plataforma), fica com um **ícone de fone azul**. Uma solução momentânea que te dou agora é: toda vez que quiser ouvir algum podcast, verifique na plataforma se o podcast já está marcado com esse ícone. Quando falo plataforma, me refiro aquela que acessa no alura.com.br, em que pode logar no computador ou no browser no celular.

Uma outra opção seria utilizar os apps de streaming de música e podcasts, como spotify e deezer. O único ponto dessa opção é que não temos integração com esses apps, então caso escute por eles, não conseguimos identificar e dar check de que esses podcasts foram ouvidos.

De qualquer forma, levei esse ponto pro time, pois de fato é importante ter um feedback no app para os podcasts já ouvidos, só não podemos garantir prazo, como comentei em outra sugestão levantada.

Agradecemos demais a sua sugestão! Esses levantamentos são muito importantes para que possamos discutir, rever e melhorar cada vez mais nossa plataforma e aplicativo. Conte conosco e bons estudos pra ti 😃 

Abaixo deixo a imagem de dois podcasts visualizados pela plataforma, um com o ícone citado e outro sem:

![image](https://github.com/caelum/alura-funcionalidades/assets/150740761/c3908b5d-69f6-4859-b0c0-89b876adc02e)

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
