### ISSUE TITLE
Adicionar opções para compartilhar ou baixar certificados diretamente após a conclusão do curso

### ISSUE THREAD

**Issue by rafaelswitek** [caelum/alura-funcionalidades#892]
**Descrição do Problema:**
Atualmente, para baixar ou compartilhar um certificado no LinkedIn, é necessário navegar até o perfil e procurar manualmente pelo curso para ter acesso a essas opções. Seria muito mais conveniente e prático se essas funcionalidades estivessem imediatamente disponíveis após a conclusão do curso.

**Benefícios:**
- Melhoraria significativamente a experiência do usuário ao facilitar o compartilhamento e download do certificado.
- Economizaria tempo ao eliminar a necessidade de navegar por várias telas para acessar essas opções.
- Aumentaria a praticidade e usabilidade da plataforma.

**Comment by juliagodinhoo** [comment]
Oi @rafaelswitek,

Concordamos totalmente você! Realmente não está um fluxo muito legal e temos planos futuros de realizar melhorias nele, só não consigo te dar um prazo para isso.

Muito obrigado pela sua sugestão!

Abraços, bons estudos e boas festas de fim de ano 😄

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
