### ISSUE TITLE
Formatação do texto pode bugar com múltiplos asteriscos.

### ISSUE THREAD

**Issue by victorwss** [caelum/alura-funcionalidades#893]
Fui sugerir uma correção de formatação num texto de uma aula, e percebi que a formatação apresentada não é a mesma que aparece na tela de edição. Trata-se de algum pequeno bug um tanto obscuro ao processar múltiplos asteriscos de formatação próximos no texto.

Eis o que aparece na tela de sugestão:

![image](https://github.com/caelum/alura-funcionalidades/assets/4574568/803b8f56-7cb7-4577-88c8-1311c8de005a)

Eis o que aparece no texto apresentado ao aluno:

![image](https://github.com/caelum/alura-funcionalidades/assets/4574568/5c0bd75d-14a1-4598-9f95-fb95e362633e)

Observe que o texto `**J**ava **AR**chive` é renderizado corretamente no preview, mas incorretamente no apresentado ao aluno.

**Comment by designernatan** [comment]
@victorwss valeu pela sugestao!

vamos dar uma olhada dps

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
