### ISSUE TITLE
Equivalência de Cursos

### ISSUE THREAD

**Issue by TulioPintoNeto** [caelum/alura-funcionalidades#894]
## A dor

Sou aluno da Alura desde 2016 e sempre que decido retornar meus estudos com a Alura, me deparo com atualizações de cursos que já fiz. Isto é uma coisa boa, entretanto algumas funcionalidades como `pré-requisitos` acabam por não serem úteis, pois os cursos que fiz no passado não são os atuais utilizados nos `pré-requisitos`. Outra coisa é que se quero fazer uma formação mais atualizada, ou retomar a antiga numa versão mais nova, fica difícil entender quais partes da formação antiga já fiz que são aplicáveis na nova.

Deixe me dar alguns exemplos, no passado, fiz alguns cursos da [formação java 142134](https://cursos.alura.com.br/formacao-java-v142134), quando fui retomar, achei o curso desatualizado mesmo, e quis fazer a [versão nova](https://cursos.alura.com.br/formacao-java). Entretanto, já havia feito cursos como básico de Java e OO, e isso não se refletia na nova formação, ou seja, o progresso era completamente 0%. Decidi refazer os cursos em uma velocidade elevada, mas após todos os cursos da nova versão feitos, conclui que poderia muito bem ter deixado eles em branco sem me preocupar (apesar de que isso prejudicaria meu certificado no futuro, o que é outro problema).

## Equivalência - Solução (proposta de feature)

Uma das formas que enxergo que poderia ser lidado com isto, seria que os cursos antigos de alguma forma marcassem os novos como "equivalência", ou seja, você não concluiu, mas o curso antigo que você já fez é suficiente para você progredir neste `curso` ou `formação` sem precisar realizar a versão atualizada.

Ainda nesta dinâmica, caso o curso da versão nova possua um conteúdo diferente, pode-se indicar isto de alguma forma, idealmente ainda indicaria que este novo conteúdo é indispensável pra seguir os estudos no curso/formação em que está se visualizando. Este segundo parágrafo poderia ser uma feature secundária da principal (primeiro parágrafo), visando uma ideia de melhoria contínua, a primeira já entrega valor.

Indo além, poderíamos em determinado momento dar equivalência em OO Java x OO Flutter (ou coisas semelhantes). Ou mesmo dar a equivalência, mas mantendo uma aula X que aborde as diferenças.

A ideia de equivalência vem um pouco do que vi no meu curso de Engenharia na UFRGS, que possui a mesma ideia, onde um curso atualizado às vezes não precisa ser refeito por alunos que já fizeram a versão antiga dele, ou seja, os alunos não fizeram o curso novo, mas tem a equivalência.

Dando minha opinião sincera de como enxergo o negócio, acredito que este tipo de funcionalidade pode agregar muito para desenvolvedores com mais anos de carreira (como é o meu caso).

**Comment by designernatan** [comment]
@TulioPintoNeto valeu pela sugestão e pelo seu tempo em descrever tão bem a dor e a sugestão em si

De bate-pronto vejo que algo assim poderia ser ruim **dependendo** da situação. OO Java x OO Flutter por ex, apesar do foco ser OO em si, o background do curso (linguagem no caso) vai ser diferente. Nessa situação teríamos que bolar regras específicas de equivalência caso a caso, dificultando bastante intuitividade pro aluno final e chuto que até a implementação em si.

Um outro ponto é que os pré-requisitos de um curso e/ou de uma Formação, via de regra, não são obrigatórios, mas indicações nossas.

Dito isso, é uma dor real e lembro de já ter algum relato assim aqui no alura-funcs. Precisamos pensar no futuro algo que melhore essa UX e sem dúvida vamos pegar sua sugestão para estudarmos.

Abração!

**Comment by TulioPintoNeto** [comment]
Hey @designernatan obrigado por dedicar atenção a esta sugestão!

Concordo, especialmente sobre a dificuldade de implementação, pra quando fizesse entre cursos.

Minha sugestão pessoal seria fazer só a equivalência entre cursos que receberam atualização (Java OO equivale a Java aprendendo Orientação a Objetos). Isto já facilitaria muito a vida.

Aposto que depois de já ter este MVP, ver implementada e ver como são as reações dos alunos, já fica mais fácil em pensar em próximos passos.

Enfim, se precisarem de qualquer apoio em estudar a funcionalidade, teste de usabilidade, ou qualquer coisa, não hesitem em me contatar.

Abração!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
