### ISSUE TITLE
novos guias de carreira

### ISSUE THREAD

**Issue by eduardoluiz1** [caelum/alura-funcionalidades#895]
Ola. Sou novo na area e minha sugestão é um guia de carreira em mobile multiplataforma, ou dentro do guia, acrescentar os caminhos para react native e afins. 

Sei que existe um guia para react que esta dentro do guia front end mas como não sou da area, não sei se são semelhantes ou se um tem as caracteristicas do outro. (no caso react para react native).

Ainda nas guias de carreira, quando abrimos, ja olhamos para um caminho, mas não há um texto, apresentação, um local explicando que esse guia é para, por exemplo, mobile, mas em que area de mobile? se eu seguir esse guia vou desenvolver qualquer coisa da area ou é para algo especifico da area mobile? Vou aprender a fazer o que na pratica, quais produtos de mobile eu vou poder gerar, aplicativos de desempenho, jogos? Esse guia de carreira tem algum foco nesse sentido ou é geral daquela area?

Como sou novo na area não sei se o questionamento é correto mas no momento eu queria muito aprender focando em no futuro desenvolver algo nessa area de mobile multiplataforma. Vi que existem algumas formações para isso mas isso quer dizer que não é uma carreira, ja que não tem um guia de carreira?

Obrigado pelo espaço e pelo conteúdo.

**Comment by designernatan** [comment]
@eduardoluiz1 valeu pela sugestao e desculpe o delay!

a gente tem concentrado energia em fazer o [techguide](https://techguide.sh), mas parece que **ainda** não surgiu demanda suficiente para o time desenvolver algo para mobile multiplataforma

mais próximo de algo assim, tem essas Formações:
- [Formação React Native](https://cursos.alura.com.br/formacao-react-native)
- [Formação React Native e Redux](https://cursos.alura.com.br/formacao-react-native-aplicacoes-redux)

pelo que você comentou sobre ser novo na área, essa primeira parece um bom caminho

---

sobre guia VS formação, na prática são bem parecidas, mas os Guias foram desenvolvidos em parceria com algumas empresas (de cabeça lembro da magalu, itaú, idwall)

as Formações são cursos e conteúdos em uma sequência pensada 100% pela Alura

---

lembrando que você pode usar o discord exclusivo de alunos da Alura para papear com outros alunos e alunas sobre carreira, cursos, etc :))

abração e novamente desculpe pelo delay

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
