### ISSUE TITLE
Mecanismo de busca na sessao de cursos/formacoes descontinuadas.

### ISSUE THREAD

**Issue by GuiMedeirox** [caelum/alura-funcionalidades#896]
Fui buscar um curso que foi descontinuado, e infelizmente, não consigo achar ele através da página de conteúdos descontinuados [Conteúdos Descontinuados](https://cursos.alura.com.br/conteudos-descontinuados/formacoes)

![image](https://github.com/caelum/alura-funcionalidades/assets/50681750/86bccdc8-f464-4ebb-993d-e7701356eed6)
![image](https://github.com/caelum/alura-funcionalidades/assets/50681750/8fb606a7-6702-41b7-8441-e0852e613a21)

Buscar o curso "na unha" fica complicado demais, levando em consideração o tanto de conteúdo que tem nessa lista. 

(uns cursos de java que foram descontinuados são MUITO bons)

**Comment by GuiMedeirox** [comment]
PS: isso daqui entraria como um plus, mas poder filtrar os cursos descontinuados pela tecnologia tambem seria algo muito maneiro. 

(se colocar esse tipo de filtragem, pode ate descartar a busca pelo nome)

![image](https://github.com/caelum/alura-funcionalidades/assets/50681750/98a267b4-2896-41eb-a6e6-848746901a73)

**Comment by masromao** [comment]
Olá @GuiMedeirox , obrigado pelo envio.
Muito legal essa ideia de filtro na página de cursos descontinuados.
Por enquanto não temos previsão para atualizar essa página, mas quando formos redesenhá-la, com certeza levaremos essa ideia em consideração.

Abraços e bons estudos!

**Comment by giovana-armidoro** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
