### ISSUE TITLE
Estruturação de um plano de estudos

### ISSUE THREAD

**Issue by leandro-d-santos** [caelum/alura-funcionalidades#897]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.
Olá, gostaria de poder estar detalhando melhor um plano de estudos com sessões e um descritivo de cada sessão. Muito semelhante as formações da própria Alura. Acredito que tanto pessoalmente quanto para empresas seria muito interessante poder estar detalhando e separando melhor os cursos de um plano de estudos. Acredito que o problema poderia ser sanado apenas criando um monte de plano de estudo. Mas pensando que poderia ter um plano de estudo de uma única linguagem, eu poder "categorizar" os cursos dentro de um mesmo plano de estudo, seria muito interessante.
Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

**Comment by masromao** [comment]
Olá @leandro-d-santos muito obrigado pelo envio!
Interessante as ideias que você trouxe para melhorar os planos de estudo.
No momento não estamos com planos de mexer nessa parte da plataforma, mas quando formos olhar pra isso, com certeza levaremos essas ideias em consideração.

Abraços e bons estudos!

**Comment by giovana-armidoro** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
