### ISSUE TITLE
Review Mode

### ISSUE THREAD

**Issue by JonasAX** [caelum/alura-funcionalidades#898]
Assim como tem um Dark Mode eu sugiro um modo de revisão aplicado por curso. 

Um MVP disso seria um botão para abrir uma página com uma cópia de todas as questões (somente), mas sem estarem respondidas. Implementado por curso. O aluno apenas responderia do mesmo jeito e tendo o mesmo funcionamento de mostrar gabarito. Isso poderia ser implementado de modo stateless, sem salvar nada. Apenas com o objetivo de testar conhecimento / revisar.

Em um segundo momento, saindo do cenário MVP. Sugiro a possibilidade do aluno aplicar uma customização (por curso) do Review Mode. Onde o indivíduo adicionaria parágrafos/frases das transcrições, e/ou removeria questões que considerasse muito básicas/inadequadas.

**Comment by masromao** [comment]
Olá @JonasAX , obrigado pelo envio.
Muito legal essa sua ideia do Review Mode.
Por enquanto não temos planos de mexer com esse tipo de alteração, mas quando formos mexer na estrutura da plataforma, com certeza levaremos essa ideia em consideração.

Obrigado pelo envio e bons estudos!

**Comment by giovana-armidoro** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
