### ISSUE TITLE
Compartilhamento de cursos e formações via aplicativo

### ISSUE THREAD

**Issue by estevamdf2** [caelum/alura-funcionalidades#899]
Disponibilizar um botão para compartilhamento via aplicativo de um curso e/ou formação.

![WhatsApp Image 2024-01-08 at 14 01 05](https://github.com/caelum/alura-funcionalidades/assets/217245/b613b257-e3c9-4ad1-9771-7086919a6738)

Atualmente só temos as opções: 

- Pausar;
- Concluir,
- Fórum e;
- Apagar

**Comment by designernatan** [comment]
@estevamdf2 valeu pela sugestao!

pode me explicar um pouco mais por favor? Acho que entendi mas queria confirmar :))

abcs

**Comment by estevamdf2** [comment]
Tranquilo @designernatan 

Quando quero compartilhar um curso com algum amigo. Tenho que abri-lo no navegador e copiar o link do curso:

https://cursos.alura.com.br/course/comunicacao-se-expressar-bem-ser-compreendido

![Screenshot_2024-01-09-19-07-42-155_com android chrome](https://github.com/caelum/alura-funcionalidades/assets/217245/46d73a59-9d5f-4624-9d30-eb69c346026d)
![Screenshot_2024-01-09-19-07-48-636_com android chrome](https://github.com/caelum/alura-funcionalidades/assets/217245/863e2eb4-76a1-4377-8ffc-1853c794b729)

A ideia e inserir um botão para compartilhar o curso via aplicativo e ele encaminhar a url para acesso ao curso.

![IMG_20240109_190458](https://github.com/caelum/alura-funcionalidades/assets/217245/eab66a29-d212-4f81-9937-bed645d47879)

Um plus seria caso o usuário tenha o aplicativo da Alura instalado ele desse a opção de abrir pelo navegador ou aplicativo .


No exemplo que eu dei tive que remover da url a parte referente a task. Ela vem geralmente assim: https://cursos.alura.com.br/course/comunicacao-se-expressar-bem-ser-compreendido/tasks/1212/xpto

**Comment by giovana-armidoro** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
