### ISSUE TITLE
Reforço de atividades para refazer exercícios

### ISSUE THREAD

**Issue by GuilhermeTavares-py** [caelum/alura-funcionalidades#9]
A funcionalidade que sugiro é de criar um tipo algoritmo destinado a usuários revisitarem exercícios anteriormente feitos, no intuito de relembrar as funcionalidades apresentadas no curso em questão.

Como funcionaria:
1 - O usuário terminaria o curso normalmente;
2 - Após um tempo, podendo ser de um mês ou três meses (dependendo do nível de dificuldade do exercício), o algoritmo falaria para o usuário para refazer tal exercício.
3 - Daí apareciam duas opções, refazer ou não refazer (para aqueles que lembram da função)
4 - Caso o usuário escolher refazer, ele apenas fará o exercício exigido. Caso erre, ele saberá que deve revisar o conteúdo.

**Comment by designernatan** [comment]
@GuilhermeTavares-py gosto bastante para reforço de conteúdo, ainda mais puxando aquela ideia de refazer algo de tempos em tempos para fixação de longo prazo

valeu pela sugestão!
