### ISSUE TITLE
Funcionalidade que inicia o vídeo do lugar da última parada

### ISSUE THREAD

**Issue by RodolfoBredoff** [caelum/alura-funcionalidades#90]
Descreva a funcionalidade que você gostaria que tivesse na plataforma. Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

A minha sugestão é fazer algo semelhante ao Youtube, onde caso o vídeo seja pausado por algum motivo, no próximo acesso ele volta do mesmo lugar que parou, sem a necessidade de reiniciar o vídeo do inicio.

**Comment by designernatan** [comment]
oi @RodolfoBredoff valeu pela sugestao!

essa eh uma das que faz todo sentido, me parece simples algo assim (se bem que se fosse simples provavelmente a galera ja tinha codado isso há um tempo)

qnd pegarmos a tela de aula para melhorarmos vamos considerar isso!

**Comment by designernatan** [comment]
comentando aqui, [sugestao ja feita aqui](https://github.com/caelum/alura-funcionalidades/issues/4)
