### ISSUE TITLE
"Continuar de onde parou" / "Continuar curso" do próximo vídeo

### ISSUE THREAD

**Issue by vanderlei-dev** [caelum/alura-funcionalidades#900]
O botão "Continuar de onde parou" no app Android e o correspondente "Continuar curso" na web atualmente direcionam para o último vídeo assistido, mesmo que este tenha sido assistido até o final. Isso é um pouco problemático para a experiência do usuário na minha opinião, principalmente no aplicativo pois temos que sair do vídeo, voltar para a listagem das aulas e procurar o vídeo seguinte manualmente. Isso deixa o botão sem nenhuma utilidade. Acredito que isso possa ser classificado como um bug inclusive.

Minha sugestão é que o botão "Continuar de onde parou" direcione para a próxima aula quando o último vídeo já tiver sido concluído (assistido completamente). Ou que seja criado um outro botão com essa funcionalidade.

Exemplo prático:
- Minha última aula concluída (assistida até o final) no print abaixo foi "Utilizando useLocation". Hoje se eu usar o botão "Continuar curso" vou ser direcionado para o início deste mesmo vídeo. O ideal na minha opinião seria o botão redirecionar para a próxima atividade ("Para saber mais: useLocation e hooks" neste caso).

![image](https://github.com/caelum/alura-funcionalidades/assets/31932302/ffe6c281-2b7e-4baf-84fe-921e937052d0)

**Comment by masromao** [comment]
Olá @vanderlei-dev muito obrigado pelo envio : )
Muito válida essa observação sobre o fluxo dos vídeos da tela de aula.
No momento não temos previsão, mas quando formos redesenhar e repensar no fluxo da tela de aula com certeza levaremos essa sugestão em consideração.

Muito obrigado e bons estudos!

**Comment by giovana-armidoro** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
