### ISSUE TITLE
Baixar certificado de uma formação completa

### ISSUE THREAD

**Issue by Anjosgiu** [caelum/alura-funcionalidades#901]
Consigo baixar apenas o certificado de cada curso individualmente e, em algumas formações, são exigidos diversos cursos para sua conclusão, seria legal ter um certificado geral também.

**Comment by masromao** [comment]
Olá @Anjosgiu boa tarde!
Muito obrigado pela sugestão, quando formos repensar o fluxo dos certificados levaremos essa ideia em consideração.
Infelizmente ainda não temos previsão pra isso, ok?

Obrigado e bons estudos!

**Comment by giovana-armidoro** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
