### ISSUE TITLE
Filtro Nível de curso

### ISSUE THREAD

**Issue by lanmeb** [caelum/alura-funcionalidades#902]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.
Ao selecionar  o curso por categoria, há vários cursos. Sinto a necessidade de escolher o curso pelo nível( Básico, Intermediário , etc) uma sequência que indique o grau de dificuldade. Por exemplo em "Data Science" há o curso* de "Excel" com 20 cursos. Por qual eu deveria começar? Pensando numa sequência lógica de dificuldades. Acredito que um filtro indicando o grau de dificuldade, me ajudaria a escolher qual curso fazer primeiro.

**Comment by masromao** [comment]
Olá @lanmeb boa tarde!
Muito legal sua ideia de separar os cursos por nível.
Não estamos com planos de mexer nessa parte da plataforma por enquanto, mas quando formos mexer com certeza levaremos essa ideia em consideração.

Obrigado e bons estudos : )

**Comment by giovana-armidoro** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
