### ISSUE TITLE
Bug no grid de pontos

### ISSUE THREAD

**Issue by edupmon** [caelum/alura-funcionalidades#903]
O grid de pontos não está indicando os pontos ganhos no trigésimo dia. (o trigésimo dia não está trazendo os dados, está sempre zerado, incorretamente)

**Comment by masromao** [comment]
Olá @edupmon , tudo bem?
Pode me detalhar um pouco mais sobre o problema, por favor?
Eu acho que entendi, mas vou pegar mais detalhes para conseguir levar para o time responsável dar uma olhadinha nisso.

Obrigado!

**Comment by edupmon** [comment]
Oi @masromao  tudo bem! E por aí?
Inclui uma captura de tela. O espaço no círculo vermelho está informando de maneira incorreta que não tem pontos marcados neste dia. 
Acredito que houve alguma atualização, relativamente recente que introduziu este bug.
Qualquer dúvida, ou algo adicional que puder ajudar, só chamar novamente! ;)

<img width="1239" alt="Screenshot 2024-01-17 at 07 28 18" src="https://github.com/caelum/alura-funcionalidades/assets/11300449/0a1608fb-71e2-4013-8262-78adb54d2856">

**Comment by masromao** [comment]
Olá @edupmon muito obrigado pelo envio!
Levei seu apontamento para o time responsável e estão de olho no que pode ter acontecido.
Infelizmente não tenho um prazo pra te passar sobre essa questão, mas o time já está de olho e priorizando internamente para investigar o ocorrido.

Muito obrigado, abraço e bons estudos!

**Comment by masromao** [comment]
Opa @edupmon passando pra informar que o time conseguiu pegar e em breve os ajustes estarão no ar :)

**Comment by edupmon** [comment]
@masromao Bug corrigido ;)

**Comment by giovana-armidoro** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
