### ISSUE TITLE
Botão voltar ao topo e um índice acompanhando o conteúdo.

### ISSUE THREAD

**Issue by davidwilliamx** [caelum/alura-funcionalidades#904]
Boa tarde, gostaria de sugerir duas funcionalidades que podem melhorar a leitura dos artigos grandes como o "CSS: o que é, como usar no HTML e um Guia para iniciar".

1. Que os artigos tenham o botão voltar ao topo.
2. Que o índice encontrado no começo do artigo do lado esquerdo siga a rolagem da página durante a leitura ou que todo o conteúdo da página. 

![exemplo](https://github.com/caelum/alura-funcionalidades/assets/13040427/58ffe63b-22f5-4dac-9c43-ce5c9dd45aca)

Obrigado.

**Comment by artnicodemus** [comment]
Opa @davidwilliamx , muito obrigado pela ideia!
Realmente faz sentido e acredito que ajudaria na usabilidade. 
Não tenho um prazo de quando isso pode ser implementado, mas vou deixar anotado aqui para quando alguém for mexer nos artigos.
Bons estudos!

**Comment by giovana-armidoro** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
