### ISSUE TITLE
Melhora na Usabilidade ao Assistir Vídeo pelo Celular

### ISSUE THREAD

**Issue by gustavoguedess** [caelum/alura-funcionalidades#905]
Gostaria de pontuar 3 melhorias ao assistir aulas pelo app do Android:
1. Alternar estado do player de vídeo quando clicado na tela;
2. Avançar 10s ou 15s quando clica duas vezes para a direita;
3. Quando finalizado o vídeo, voltar para o curso, não para a dashboard inicial do app da Alura;

Para explicar melhor o primeiro ponto, vou tentar descrever como está hoje: enquanto vc assiste a aula, se clicar no player, vai aparecer os botões de pausa, avançar, configurações e timeline, como está abaixo. Se clicar novamente na tela, onde não tem botão, o timer para o player sumir recomeça, ao invés do player sumir. Sugiro mudarem para o click no vídeo alternar a aparição dos botões do player. Assim posso controlar quando vejo o player ou não, antes de ter que esperar o tempo para desaparecer sozinho.
![player](https://github.com/caelum/alura-funcionalidades/assets/27167768/6f7f26c4-7853-436a-b6c8-818373141ef1)

O segundo ponto é similar ao usado do youtube, dando dois clicks rápido para a direita, avança o vídeo em x segundos, se for dois clicks rápidos para a esquerda retrocede o vídeo.

O terceiro eu achei bem chatinho do app. Quando termino de ver uma aula, automaticamente vai para a tela inicial do discord, nem ao menos vai pra página do curso. Algumas vezes vejo a página do curso aparecendo rapidamente antes de ir pra principal. Dá uma sensação de bug. Eu acredito que seria melhor se fosse pra página do curso, pra continuarmos o curso sem muito impedimento.

**Comment by artnicodemus** [comment]
Oi @gustavoguedess , obrigado pelas sugestões!

Referente aos pontos **1 e 2**, anotei suas ideias e vamos estudar a possibilidade de ter esses atalhos no plater, só não consigo te falar um prazo no momento.

Agora quanto ao **ponto 3**, fiquei com algumas dúvidas. Provavelmente é um bug, você pode responder umas perguntinhas pra ajudar a gente a entender o que está acontecendo?
1. Quando você diz terminar uma aula, é terminar de ver um vídeo ou uma sessão inteira do curso?
2. Qual email do seu usuário?
3. Você está assistindo num aparelho android ou iOS? Qual versão?
4. Qual versão do app você está usando?

**Comment by gustavoguedess** [comment]
1. Quando termino um vídeo
2. gustavoipguedes@gmail.com
3. android 12
4. v4.3.3+150

**Comment by taisbatuira** [comment]
Oi Gustavo,

Sou Tais do time de desenvolvimento dos aplicativos e vim dar um Feedback para você. Estamos colocando uma nova versão do app no ar e acredito que ela já contemple algumas das solicitações enviadas. 

1. Na nova versão implementamos o zoom no player de vídeo e uma das funcionalidades é o toque imediato para "sumir" os botões do player sem o timer que você mencionou. 
2. Já estamos com um card nas nossas tarefas futuras para implementar o duplo toque na tela do player para avançar e retroceder 10 segundos do vídeo, mas é uma tarefa futura e não temos previsão de quando será implementada. 
3. É um bug conhecido nosso que também já corrigimos para essa nova versão que colocaremos no ar. 

A atualização será enviada entre hoje e amanhã, mas o release é gradual e depende das lojas, portanto fique atento que em até 7 dias a nova versão estará disponível para download no seu celular. 
Peço que, ao atualizar, teste os itens 1 e 3 que já estão implementados. 

No mais, estamos a disposição. Muito obrigada pelo Feedback!!! 

Bons estudos!!!!

Tais Batuira

**Comment by gustavoguedess** [comment]
Atualizei, os itens 1 e 3 estão funcionando corretamente!
