### ISSUE TITLE
Inclusão de ícone com Indicador de Formações Completa na página de formação

### ISSUE THREAD

**Issue by granadeiro** [caelum/alura-funcionalidades#906]
Hoje quando acessamos a página de cursos dentro de uma categoria por exemplo https://cursos.alura.com.br/category/inovacao-gestao
é possível saber quais cursos já fiz. Tem ícones indicando oque foi feito e se tem versão nova.

![image](https://github.com/caelum/alura-funcionalidades/assets/16483442/46a5e182-6c1c-4939-9d69-06d4bf46af4c)

Na página de formações poderia também ter uma indicação da formação que já fiz  https://cursos.alura.com.br/formacoes
Olhando a imagem abaixo, para escolher uma nova formação, eu preciso ficar entrando para saber se foi feito ou não. Bastaria o mesmo ícone do curso

![image](https://github.com/caelum/alura-funcionalidades/assets/16483442/b087348d-9e94-486f-9fa5-91f8ac6ddedd)

**Comment by artnicodemus** [comment]
Oi @granadeiro , obrigado pelo feedback!
Realmente existem algumas melhorias a serem feitas na página de formações, sua ideia é super válida e deixei anotada aqui para quando a gente for mexer na tela.
Obrigado e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
