### ISSUE TITLE
Métrica de Engajamento - Períodos Consecutivos

### ISSUE THREAD

**Issue by edupmon** [caelum/alura-funcionalidades#907]
Imaginei que seria interessante, um indicador que mostrasse quantos períodos seguidos de interação tenho com a plataforma.

Interação: Um video assistido, artigo lido, podcast assistido, tópico criado ou respondido no fórum ou exercício respondido.

Período: Dia ou Semana (definido pelo usuário, se meu compromisso de estudo será, por exemplo, 3 vezes por semana, este é o período.) 

Com estes dados, exibir algo do tipo:

<img width="503" alt="Screenshot 2024-01-26 at 7 41 47 AM" src="https://github.com/caelum/alura-funcionalidades/assets/11300449/eeb68157-6791-4226-9da7-e47750a090b0">

Caso o usuário da plataforma atualize seu período/compromisso, por exemplo de 3 para duas vezes por semana, por simplicidade de implantação do recurso, estes indicadores podem ser reiniciados, iniciando uma nova contagem, para esta nova configuração.

O que acham?

Aqui, do meu lado, isso seria um incentivo, para manter a constância e sempre tentar quebrar meu próprio recorde de engajamento. ;)

**Comment by artnicodemus** [comment]
Opa @edupmon , interessante a sua ideia (: 
Recentemente temos analisado possibilidades em torno desse tema de engajamento e gamificação e anotamos aqui sua ideia também. Porém no momento temos alguns impeditivos, então novidades sobre o tema vão ficar mais pro futuro ):
Muito obrigado pelo empenho de ter feito o esquema visual da sua ideia, bons estudos!

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
