### ISSUE TITLE
Anotacoes nos videos

### ISSUE THREAD

**Issue by MateusRSdev** [caelum/alura-funcionalidades#908]
gosto muito da alura acho os cursos incríveis mas sinto falta de uma funcionalidade que tinha na udemy quando eu estudava por lá que vc podia fazer anotações em um momento especifico do vídeo e depois vc tinha acesso a todas as anotações que vc podia clicar e ir direto pro determinado vídeo no determinado ponto em  que vc fez a anotação que era muito útil quando o professor explicava um determinado assunto e vc queria revisar ou relembrar. inclusive era legal que vc podia ver quantas pessoas anotaram naquele mesmo ponto do vídeo que vc tinha uma noção de "nossa esse ponto foi algo importante".

eu sei que isso não deve ser algo fácil de implementar mas a esperança é a ultima que morre né kkkk

**Comment by artnicodemus** [comment]
Olá @MateusRSdev , muito obrigado pela sugestão!
Um tempo atrás a gente tinha algo similar na plataforma, mas foi descontinuado por não ter batido expectativas de engajamento e alguns outros detalhes importantes ):
Recomendamos utilizar o Notion para salvar e organizar as anotações dos estudos na plataforma.
Abraços e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
