### ISSUE TITLE
Notificações de novos cursos: Separar por Escola.

### ISSUE THREAD

**Issue by gstvortiz** [caelum/alura-funcionalidades#909]
Olá.

Periodicamente eu entro na plataforma pra estudar um assunto novo, e as vezes alguns cursos são descontinuados e outros são incluídos. As notificações podem ser acessadas no canto superior direto da plataforma, mas são todas ao mesmo tempo.

Gostaria de saber se existe algum recurso pra separar essas notificações por escola (por exemplo, só as novidades em Data Science). Se não tiver, acho que seria excelente.

Valeu!

**Comment by artnicodemus** [comment]
Oi @gstvortiz , obrigado pela sugestão!

Atualmente não existe uma maneira de filtrar as novidades no sininho.
Porém, na página da Escola você consegue visualizar as novidades dela. Exemplo de data: https://cursos.alura.com.br/escolas/data-science
Logo no começo da página tem um carrossel com os últimos conteúdos lançados (Novidades).

Qualquer coisa é só dar reply aqui novamente, bons estudos!

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
