### ISSUE TITLE
Ensinar os atalhos do VScode para os alunos durante as aulas

### ISSUE THREAD

**Issue by RicardoZanandrea** [caelum/alura-funcionalidades#910]
Olá, gostaria de deixar a sugestão, de os instrutores de cursos tanto como iniciais ou até mesmo avançados, ensinarem mais aos alunos sobre os atalhos de comando do VScode, acho uma boa ideia, pois durante as aulas fazemos muitas coisas que podem ser ensinadas através destes atalhos, utilizando o teclado e podendo deixar o mouse mais de lado, são comandos bons de saber e que muitas vezes podem poupar um tempo, tenho escrito um documento falando mais sobre esses atalhos que podemos utilizar para deixar o trabalho mais fácil. E eu mesmo gostaria de me voluntariar para escrever um artigo para ser publicado dentro da Alura sobre esses atalhos, não busco nenhuma remuneração com isso, apenas gostaria de ajudar e adquirir experiência!! Se gostarem da ideia, podem me retornar no meu email ricardinhodev@gmail.com que eu escrevo este artigo para publicar na plataforma!! É algo que gostaria muito de fazer e acho que pode ajudar muita gente que está começando na área, ou até mesmos pessoas experientes que não conhecem ou não utilizam destes atalhos para um trabalho mais fácil.

**Comment by artnicodemus** [comment]
Olá @RicardoZanandrea , muito obrigado pela sugestão!
Um artigo do tipo ajudaria mesmo. Entrei em contato com o time de comunicação pra mostrar sua ideia de artigo e eles também gostaram!
Atualmente o time está estruturando um processo para artigos escritos por alunos, assim que avançarem com isso irão entrar em contato com você (:
Abraços e bons estudos, valeu!

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
