### ISSUE TITLE
Listar o nome completo da formação

### ISSUE THREAD

**Issue by cleytonscherer** [caelum/alura-funcionalidades#911]
Na listagem das formações, quando o nome da formação é extenso, não é possivel ler o nome completo da formação

![image](https://github.com/caelum/alura-funcionalidades/assets/81915739/d84251f6-645e-4fd8-a56b-f353d1783352)

![formação_alura](https://github.com/caelum/alura-funcionalidades/assets/81915739/3683f479-cb7d-44de-ad21-51c14cbd00d9)

**Comment by artnicodemus** [comment]
Opa @cleytonscherer , obrigado pela sugestão!
Na página de Formações (https://cursos.alura.com.br/formacoes) tem a lista de todas formações com seus nomes completos e mais informações, é mais fácil de visualizar por lá!
A listagem de Formações que fica na dashboard (seu print) é mais limitada devido ao pouco espaço na tela.
Abraços e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
