### ISSUE TITLE
APOSTILAS EM PDF E EPUB

### ISSUE THREAD

**Issue by matheusfsanna** [caelum/alura-funcionalidades#912]
No trabalho não posso usar o celular, mas posso usar um Kindle para estudar e gostaria que fosse fornecido material em texto digital de maneira com que seja possível eu estudar no meu tempo ocioso no trabalho. Se fosse só a transcrição da aula de vídeo já ficaria feliz.

**Comment by giovana-armidoro** [comment]
oi Matheus, obrigada pela sugestão!

hoje ainda não disponibilizamos apostilas ou a transcrição dos vídeos em pdf ou epub, mas guardei aqui a sua sugestão.
o que posso te indicar no momento são nossos artigos, que você pode conferir [aqui](https://www.alura.com.br/artigos?_gl=1*bt2scl*_ga*MjI3NDE2OTU5LjE2MDE1NjUyMzk.*_ga_1EPWSW3PCS*MTcwNzkyOTQ0NS42OC4xLjE3MDc5MzA0MDMuMC4wLjA.*_fplc*VWlBalI2aU85RmhmY0ZaUWtOTFhPJTJGSlZkWXQ5TGhUbmVvclROUkZkblFhZSUyQmh2S3dVSHJ0T2IzcSUyQjhLVlNhJTJGMmNFSGptRUc1Z2RZdlNBUjc0bUslMkJOVW40RjRTMjB0ZE1maFhIZ01jU3dHMWNwOCUzRA..), dando um CTRL+P na página vc consegue salvar como pdf para ler depois, acho que é uma boa  opção para ler nos intervalos do trabalho.

espero que ajude. abraços e bons estudos!

**Comment by Rubferreira** [comment]
Olá!
Adorei a sugestão do Matheus, porque pensei da mesma forma e uma forma de revisão, de reforço de estudo, e também ocorre que muitas vezes somos obrigados a fazer uma "pausa", como ficar doente; o que ocorreu comigo.

Quero aqui reforçar a sugestão, poie é a mais completa para qualquer curso.
Obrigado!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
