### ISSUE TITLE
IDE integrada ao site

### ISSUE THREAD

**Issue by marceloboy1** [caelum/alura-funcionalidades#913]
Seria ótimo que tivesse uma IDE com terminal integrada ao site, para que pudéssemos treinar os conteúdos do curso sem muita instalação de diversos computadores diferentes. Assim como o CS50 utiliza uma IDE online do VS Code, com diversos recursos integrados por exemplo, usando a IDE do CS50, vc envia seu código para correção, baixa os arquivos do curso, entre outra facilidades.

**Comment by giovana-armidoro** [comment]
oi Marcelo, obrigada pela sugestão!

entendo que seria algo bem legal, mas temos um ponto que é algo que o Paulo comentou lá atrás em uma [outra issue](https://github.com/caelum/alura-funcionalidades/issues/108) que é, futuramente na construção do setup e no uso da linguagem essa facilitação pode acabar sendo uma barreira na aprendizagem do todo, o que acaba complicando ao invés de ajudar
então, no momento, não pensamos em implementar isso mas vamos deixar mapeado para analisar novamente a possibilidade

abraços e bons estudos!

**Comment by designernatan** [comment]
fechando a issue, pessoal

podem voltar a comentar se quiserem :)
