### ISSUE TITLE
Bug ao adicionar formação a plano de estudos

### ISSUE THREAD

**Issue by ricardopires** [caelum/alura-funcionalidades#914]
Ao adicionar a formação "Inovação para líderes" a um plano de estudo, salvar as alterações e visitar o plano de estudo, a formação aparece como "site" e o link fica quebrado:
<img width="456" alt="Captura de tela 2024-02-08 105030" src="https://github.com/caelum/alura-funcionalidades/assets/6654492/fdfc9824-dba7-41a8-9666-9a012bbafe1b">
<img width="611" alt="Captura de tela 2024-02-08 105136" src="https://github.com/caelum/alura-funcionalidades/assets/6654492/f3b5883e-5ba1-42a0-a1d9-bfee37ac3371">
<img width="580" alt="Captura de tela 2024-02-08 105150" src="https://github.com/caelum/alura-funcionalidades/assets/6654492/a425a35e-02b6-4c6d-9856-d25cc13b32b5">

**Comment by giovana-armidoro** [comment]
oi Ricardo, obrigada por reportar esse bug
fiz o teste aqui e aconteceu o mesmo comigo, também apareceu como site e deu em uma página 404
abri uma solicitação aqui pra equipe pra solucionar o bug, quando tivermos alguma novidade avisamos aqui

abraços e bons estudos!

**Comment by juliagodinhoo** [comment]
Fechando a issue por aqui, pessoal!

Podem voltar a comentar se quiserem :)
