### ISSUE TITLE
Filtro por Nível de Dificuldade

### ISSUE THREAD

**Issue by eversonestrela** [caelum/alura-funcionalidades#915]
Uma funcionalidade de filtro por nível de dificuldade em uma plataforma de cursos online permite aos usuários refinar a lista de cursos disponíveis com base na dificuldade, facilitando a busca por cursos que melhor se encaixam em suas habilidades e necessidades de aprendizado. Aqui está uma descrição detalhada de como essa funcionalidade pode ser implementada e usada:

### Descrição da Funcionalidade

**Nome da Funcionalidade:** Filtro por Nível de Dificuldade

**Objetivo:** Permitir que os usuários filtrem os cursos disponíveis na plataforma com base em seu nível de dificuldade, como Iniciante, Intermediário e Avançado.

**Como Funciona:**

1. **Opções de Filtro:** A interface do usuário apresenta opções (geralmente como botões de rádio, caixas de seleção ou um menu dropdown) para selecionar um ou mais níveis de dificuldade. As opções típicas incluem:
   - Iniciante
   - Intermediário
   - Avançado

2. **Seleção do Filtro:** O usuário seleciona o nível de dificuldade desejado. A seleção pode ser única, permitindo escolher apenas um nível de dificuldade por vez, ou múltipla, permitindo filtrar cursos que correspondam a qualquer uma das dificuldades selecionadas.

3. **Aplicação do Filtro:** Após a seleção, a plataforma filtra a lista de cursos, exibindo apenas aqueles que correspondem ao(s) nível(is) de dificuldade selecionado(s). Isso é geralmente alcançado enviando uma solicitação ao servidor com os critérios de filtro ou aplicando o filtro diretamente no lado do cliente, se todos os dados do curso estiverem disponíveis.

4. **Visualização dos Resultados:** Os cursos filtrados são exibidos na interface do usuário. Cada curso listado inclui informações básicas como o título do curso, breve descrição, nível de dificuldade e talvez a avaliação média dos usuários.

5. **Remoção ou Ajuste do Filtro:** Os usuários podem modificar sua seleção de filtro a qualquer momento para refinar ainda mais os resultados ou remover o filtro para voltar à lista completa de cursos.

### Implementação Técnica

- **Front-end:** No lado do cliente, a implementação pode usar HTML para os controles de filtro (como `<select>` para dropdown ou `<input type="checkbox">` para seleções múltiplas) e JavaScript para manipular a seleção do usuário e atualizar dinamicamente a lista de cursos. Frameworks como React, Angular ou Vue podem ser utilizados para uma experiência de usuário mais interativa e responsiva.

- **Back-end:** No servidor, a lógica para filtrar cursos por dificuldade pode ser implementada em linguagens como Python (usando frameworks como Django ou Flask), JavaScript (Node.js com Express), entre outras. A seleção de filtro do usuário é usada para consultar o banco de dados (SQL ou NoSQL) e retornar apenas os cursos que correspondem aos critérios de filtro.

- **Banco de Dados:** Os cursos precisam ter um campo ou atributo que denote seu nível de dificuldade. Isso permite consultas eficientes para filtrar cursos com base nesse critério.

### Experiência do Usuário

A funcionalidade de filtro por nível de dificuldade é projetada para ser intuitiva e fácil de usar, melhorando significativamente a capacidade do usuário de encontrar cursos que correspondam ao seu nível de experiência e objetivos de aprendizado. Ao fornecer essa opção de filtro, a plataforma pode aumentar a satisfação do usuário e a eficácia do processo de aprendizagem, garantindo que os usuários não se sintam sobrecarregados por cursos muito avançados ou entediados por cursos muito básicos.

**Comment by giovana-armidoro** [comment]
oii Everson, obrigada pela sugestão e por todas as informações que trouxe!
esse é um ótimo ponto de melhoria, estamos em busca de melhorar a descoberta de cursos na plataforma e esse é um ponto interessante que vou levar para discussão com a equipe

enquanto isso você pode explorar alguns [planos de estudos públicos](https://cursos.alura.com.br/planos-estudos-publicos) feitos pela comunidade Alura, várias pessoas criam planos iniciantes, intermediários e avançados em todas as áreas com uma sequência de conteúdo que você pode aproveitar

abraços e bons estudos!

**Comment by juliagodinhoo** [comment]
Fechando a issue por aqui, pessoal!

Podem voltar a comentar se quiserem :)
