### ISSUE TITLE
Sinal de Visto ou Concluído - Linha de tempo

### ISSUE THREAD

**Issue by kdecamar** [caelum/alura-funcionalidades#916]
Boa tarde.

Sugiro que seja adicionado um ícone de visto nos links dos cursos já concluídos pelos alunos, em exemplo como na figura abaixo.

![Alura_Cursos](https://github.com/caelum/alura-funcionalidades/assets/159817581/655e1410-1bb5-4c79-9d19-b30a7e7910af)

Queria sugerir também, que tivesse tipo uma linha do tempo junto aos cursos concluídos, ou nas busca de novos cursos, quais seriam os próximos cursos a serem feitos em ordem mais correta de estudo sequencial.

**Comment by giovana-armidoro** [comment]
olá, obrigada pela sugestão!

faz muito sentido o que você trouxe, estamos em busca de melhorar a experiência de descoberta de conteúdos na plataforma e vamos trazer soluções para isso assim que possível

hoje como você faz para lidar com esse problema e escolher qual é o próximo conteúdo que você vai estudar?

**Comment by kdecamar** [comment]
Olá Giovana, boa tarde... 

No momento, eu vou na busca mesmo, por exemplo curso de Linux, até achei como se fosse o que sugeri, nos pré-requisitos pra fazer determinado curso. Me baseio nos desenhos dos ícones dos cursos pra achar....

Obrigado pelo feedback.

**Comment by juliagodinhoo** [comment]
Fechando a issue por aqui, pessoal!

Podem voltar a comentar se quiserem :)
