### ISSUE TITLE
Adicionar link de mastodon e/ou redes federadas no perfil

### ISSUE THREAD

**Issue by muriloloffi** [caelum/alura-funcionalidades#918]
Atualmente, as redes sociais que um usuário da Alura pode adicionar são: LinkedIn, Twitter, Github e o Link personalizado. As redes sociais federadas, por outro lado, são mais recentes que a plataforma da Alura e não possuem um campo dedicado.
![Screenshot from 2024-02-22 15-20-02](https://github.com/caelum/alura-funcionalidades/assets/19322082/d3a6f20e-1bf9-4533-9f87-7e8ccc22bbc2)
Embora seja possível adicionar uma rede como o Mastodon ou outra rede federada no campo de link personalizado, isto implica em Users terem que fazer uma concessão entre esta opção mencionada e outro link personalizado que já possua. Portanto, eu gostaria que houvesse um campo para adicionar redes federadas ao perfil, por exemplo: https://mastodon.social/@muriloloffi

**Comment by andradeisadora** [comment]
oi @muriloloffi :)
obrigada pela sugestão! 
pois é, por enquanto temos só a opção do link personalizado mesmo :( 
não estamos com planos de mexer no perfil no momento, mas vou deixar tua sugestão salva pro dia que revermos essa tela

abraço e bons estudos!

**Comment by muriloloffi** [comment]
oi @andradeisadora, obrigado pelo retorno! Relendo aqui, me veio mais uma ideia: Quem sabe não rola uma rede federada da Alura? :) Tem bastante gente da área de TI no fediverso, seria legal marcar presença. O username ficaria "[at]fulano[at]alura.social". :smile:

Ps. Sei que isso não depende só de vc e provavelmente alguém já pensou nisso. Só queria deixar meus 2 centavos. rsrs

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
