### ISSUE TITLE
Maior interação entre os estudantes da plataforma

### ISSUE THREAD

**Issue by mtpontes** [caelum/alura-funcionalidades#919]
A plataforma não conta com nenhuma forma direta de contato com outros estudantes. Tem bastante gente que é muito engajada no fórum, tem gente que sempre tá lá ajudando ou pedindo ajuda e, às vezes, depender de um fórum pra ajudar a pessoa não a forma mais eficiente de fazer. É útil, funciona, mas também distancia essas pessoas de certa forma.

Fazer amizades no meio, se cercar de gente com o mesmo interesse que o seu, com conhecimentos diferentes e/ou a mais que você é um grande impulsionador de crescimento. Isso é desenvolvimento de network, possibilitado e impulsionado por uma função simples. A plataforma fornecer essa ponto de partida pro aluno formar conexões com gente que está na mesma jornada que ele seria de grande valor.

Essa função de direct pode vir por padrão ativada, dando a oportunidade do usuário ativar ou desativar o recebimento de mensagens diretas e todos os recursos básicos de interação de usuário-usuário. O importante é que seja uma função vísivel, pra ninguém esquecer que ela existe.

**Comment by andradeisadora** [comment]
oi @mateuspontess 
obrigada pela sugestão! 
Vc já conhece a nossa comunidade no discord? Por la, vc vai conhecer varios alunos e ainda pode fazer chamadas de audio pra estudarem juntos :)
Pra ter acesso a comunidade é só clicar no menu 'Comunidade' e 'Discord'

Abraço e bons estudos!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
