### ISSUE TITLE
Nova modalidade de cursos

### ISSUE THREAD

**Issue by limacaiquelg** [caelum/alura-funcionalidades#92]
Atualmente os cursos são organizados através das formações sobre os diversos assuntos. Desta forma, ao concluirmos a formação de Front-end, por exemplo, adquirimos conhecimentos sobre HTML, CSS, JavaScript, pré-processadores, etc. No entanto, qualquer outra tecnologia que seja necessária durante as aulas, mas que não seja foco do curso, normalmente é disponibilizada aos alunos e não é explicada (ou explicada com pouca profundidade).

Exemplo disso, nesta mesma formação, é a utilização de uma aplicação com servidor rodando em NodeJS nas aulas de JQuery. Gostaria de salientar que isso não é um problema, já que o foco do curso de JQuery é ensinar JQuery.

Porém, gostaria de sugerir a criação de uma área com cursos onde sejam determinados projetos e durante as aulas estes projetos sejam desenvolvidos em sua totalidade, utilizando tecnologias de front-end, back-end, sistemas de controle de versão, testes unitários, deploy em serviços na nuvem, etc. 

Assim, os alunos poderiam ter a experiência de utilizar diversas tecnologias requeridas pelo mercado, aprender como integrá-las e construir aplicações completas. Esta área poderia até mesmo estar separada dos cursos regulares (como o Alura+ e os projetos) ou até mesmo do site principal da Alura (algo como o Alura Start).

**Comment by designernatan** [comment]
oi @limacaiquelg valeu pela sugestao!

fazer alem da formacao front, fazer a de Node ou back-end nao resolveria essa dor? Imagino que tem pessoas que vao atuar apenas como front-enders nunca vao precisar desenvolver uma api, apenas consumir, faz sentido? 

uma feature que lançamos é o [Plano de Estudos](https://cursos.alura.com.br/user/natan-souza/planos-de-estudo) justamente para organizar esse conteúdo que casaria melhor com cada aluno(a)

**Comment by limacaiquelg** [comment]
Olá @designernatan, obrigado por responder! 

Então, acho que a base da minha sugestão é focar na integração entre as diversas tecnologias pois nem sempre isso é intuitivo. Além do mais, seria legal pra aprendermos na prática coisas mais avançadas como testes unitários, cobertura de testes, integração contínua, gerenciamento de dependências, etc. Por mais que as pessoas sejam especialistas em uma área, hoje é bem comum que se exija diversos conhecimentos e esta sugestão poderia ajudar muita gente.

Eu imagino que produzir esse tipo de conteúdo seja difícil e demorado, mas acho que pode ser uma grande adição pra plataforma. 

Ah, essa feature de Plano de Estudos é bem legal, mas acho que ela demanda que o aluno saiba o que ele precisa estudar pra conhecer bem sobre todo o "ecossistema" de uma tecnologia.
