### ISSUE TITLE
Dark Mode no dashboard

### ISSUE THREAD

**Issue by PinheiroJuliano** [caelum/alura-funcionalidades#920]
Olá, gostaria de que fosse possível personalizar o dashboard para acompanhar o dark mode (modo escuro) do sistema ou alto-contraste etc. A razão disso é o contraste que ocorre de quando estou nas aulas e desenvolvendo para quando volto ao dashboard o que gera grande desconforto visual, acredito que assim como eu outras pessoas também tenham passado por essa experiência, não consegui encontrar nenhum local interno ao site onde posso ativar esta opção. Sei que é uma sugestão simples mas acredito que seria uma grande melhoria na experiência dos usuários.

Abaixo, segue imagem ilustrativa rs..
![image](https://github.com/caelum/alura-funcionalidades/assets/128725679/52361cdf-200c-4ed5-8aa7-645a9d5af4d9)

**Comment by andradeisadora** [comment]
oi @PinheiroJuliano 
obrigada pela sugestão!
pois é, tem esse contraste grande mesmo. O Natan fala um pouquinho sobre o dark mode e dicas do que fazer [aqui nessa issue](https://github.com/caelum/alura-funcionalidades/issues/856#issuecomment-1697851340) 

abraço e bons estudos!

**Comment by T-pl** [comment]
Eu iria sugerir a mesma coisa! Que bom que já fez. É realmente muito ruim não ter um dark mode no dashboard. Espero que essa sugestão seja aceita e implementada o quanto antes.

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
