### ISSUE TITLE
Remover plano de estudo que não está mais na grade oficial

### ISSUE THREAD

**Issue by pedrotxc** [caelum/alura-funcionalidades#921]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

Tenho uma formação "Implemente aplicações web com Angular", nas formações que sigo, só que, essa formação não está mais na grade oficial da alura, mas mesmo assim ela continua aparecendo para mim. Eu tento clicar nela, mas sou redirecionado para a tela inicial, e também não consigo remover ela. Minha sugestão é que possibilitem que a formação seja removida de forma manual caso ela não esteja mais na grade.

<img width="960" alt="Screenshot_1" src="https://github.com/caelum/alura-funcionalidades/assets/46935579/58a75959-ecd9-4c24-9bd7-e718101467a3">

**Comment by andradeisadora** [comment]
oi @pedrotxc 
passei para o time responsavel e avisamos aqui assim que tivermos atualizações :)
