### ISSUE TITLE
Campo 'total de horas certificadas'

### ISSUE THREAD

**Issue by pedro-schabarum** [caelum/alura-funcionalidades#922]
Penso que seria interessante ter um local indicando o total de horas que foram cursadas, talvez na página 'Perfil & Certificados' ou mesmo indicando no certificado completo. 

![image](https://github.com/caelum/alura-funcionalidades/assets/146556225/7fe61e81-6d53-4f56-a03a-d0f35b4b9936)
![image](https://github.com/caelum/alura-funcionalidades/assets/146556225/aa7d313e-a7b6-4431-b8ea-f70a0996ea20)

Como aparece o total de horas da formação e da escola dos cursos avulsos, penso que poderia ter uma coisa semelhante no topo da certificação indicando a soma de todas as horas dos cursos e formações.

**Comment by laiscavalcanti** [comment]
Oi, Pedro, tudo bem?

Legal a sua sugestão. É uma informação que pode ser útil. Vou passar para o time responsável. E traremos mais atualizações no futuro. Obrigada pela sugestão.

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
