### ISSUE TITLE
Favoritar paginas dentro dos cursos.

### ISSUE THREAD

**Issue by pedrohcferri** [caelum/alura-funcionalidades#923]
Primeiramente gostaria de parabenizar a plataforma e toda a equipe por trás dos bastidores. Atualmente tenho estudado alguns conteúdos dentro dos cursos e algumas páginas contém algum conteúdo especifico ou com exemplos de códigos, acontece que as vezes me lembro do que estudei e acabo tendo que voltar, abrir o curso e procurar a página em que está o que eu estava buscando.
   Acredito que favoritar as páginas seria um processo trabalhoso, mas nada impossível para essa equipe maravilhosa, poder salvar as páginas em categorias facilitaria muito o estudo de alguns usuários e seria uma ótima forma de poupar tempo e uma busca minuciosa.
 Um forte abraço a todos, Pedro Ferri.

**Comment by laiscavalcanti** [comment]
Oi, Pedro, tudo bem?

Obrigada pelo apreço ao nosso trabalho :) É uma ideia interessante de fato pois ajuda a se organizar no meio de muitas paginas. Mas como você já destacou é algo trabalhoso e não está na nossa organização de tarefas desse semestre. 
Numa outra oportunidade iremos pontuar essa ideia.

Obrigada pela sugestão

**Comment by pedrohcferri** [comment]
Entendo perfeitamente, agradeço pelo feedback, bom trabalho a todos!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
