### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by magnata19** [caelum/alura-funcionalidades#924]
Gostaria de sugerir a adição de um botão para colocar a página em dark mode, não apenas na hora de ver o curso, mas na plataforma em si, na área da dashboard, na procura de cursos. Pode parecer algo simples, mas iria fazer uma diferença danada! Obrigado.

**Comment by designernatan** [comment]
opa @magnata19 valeu pela sugestao!

pois é, tem esse contraste grande mesmo. Falei um pouquinho sobre o dark mode e dicas do que fazer pra economizar sua retina HOJE: https://github.com/caelum/alura-funcionalidades/issues/856#issuecomment-1697851340

sei que não é o ideal, mas é um jeito de amenizar a situação

abcs e bons estudos!

**Comment by magnata19** [comment]
@designernatan opa, obrigado, não tinha visto o post, ajudou muito! =)

**Comment by designernatan** [comment]
tmj davidson!

outra dica é caçar um browser tipo o opera que tem uma feature que faz isso tbm
![image](https://github.com/caelum/alura-funcionalidades/assets/5431347/49af4369-1ba0-4834-b474-52db36702835)

**Comment by magnata19** [comment]
show de bola! Mais uma vez, fico imensamente grato pois a extensão ao qual me indicou funcionou e ficou top demais!!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
