### ISSUE TITLE
Legenda

### ISSUE THREAD

**Issue by Mtmozart** [caelum/alura-funcionalidades#925]
Olá, sei que talvez não faça muito sentido, mas seria muito interessante ter legenda, pois é melhor você ler  com a pessoa falando e codando. 

Não tenho nenhum problema auditivo, mas, as vezes minhas orelhas estão cansadas de tanto usar phone ou estou sem, imagino que nestas situações, legendas seriam muito bom, por exemplo:

Estou acompnhando minha avó que estão doente e dormindo de noite, não posso por um volume alto, estou sem phone, além disso, não fica prático ficar indo e voltando e lendo o que o professor fala. 

Não me entenda mal, a parte de trancrever o código e falas abaixo pe muito boa, mas acho que adicionar legenda seria muito melho, inclusive inclusivo.

**Comment by designernatan** [comment]
@Mtmozart valeu pela sugestão!

Nós estamos buscando sempre deixar a plataforma mais acessível, antigamente os cursos eram lançados sem transcrição, buscamos melhorar nossos processos e isso hoje já não acontece mais

Sobre as legendas, a falta delas sempre foi algo que também nos incomodou, e de um tempo pra cá começamos a investir mais energia nisso, o cenário ideal seria que todos os cursos tivessem legendas, sabemos que ainda estamos longe mas caminhando forte nesse sentido

Inclusive hoje temos pessoas com foco nisso!

Abcs!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
