### ISSUE TITLE
Criar uma nova aba de cursos em alta

### ISSUE THREAD

**Issue by rodrigo0o0** [caelum/alura-funcionalidades#926]
Ordenar os cursos baseando com a nota de cada curso, popularidade (mais acessos nos ultimos tempos), alunos(total de alunos inscritos no curso).
Acredito que as pessoas são muito influenciadas pela opnião de outras pessoas que já fizeram aquele curso.

**Comment by designernatan** [comment]
@rodrigo0o0 valeu pela sugestao!

gosto da ideia viu, comportamento de grupo influencia mesmo

tínhamos algo assim no finado aluraflix, mas ele como produto não se provou como gostaríamos

no futuro de médio prazo vamos considerar algo assim novamente :))

abcs!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
