### ISSUE TITLE
Certificado normal com frente e verso na mesma impressão

### ISSUE THREAD

**Issue by rickdemarte** [caelum/alura-funcionalidades#927]
Ao gerar um #certificado, é possível gerar o certificado formal, com todos os dados do curso.
Porém, não é possível gerar um PDF com o certificado normal (com a estética mais bonita) com frente e verso.
Para ter o certificado, é necessário "imprimir" a frente, depois o verso e então usar alguma ferramenta, como adobe ou ilovepdf para juntar ambos.

**Comment by designernatan** [comment]
@rickdemarte valeu por trazer essa dor!

temos ciencia dessa quebra de expectativa ali no download do certificado e no futuro vamos precisar resolver nativamente

pra resovler o problema hoje, além dessas ferramentas mencionadas por vc, sugiro o [pdfsam,](https://github.com/torakiki/pdfsam) opensource 

interface bem tranquila de mexer e já me ajudou com umas coisas pessoais

sei que não é o ideal, mas assim já da pra resolver hoje o problema

abcs!

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)

**Comment by masromao** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
