### ISSUE TITLE
Espaço para artigos dos alunos.

### ISSUE THREAD

**Issue by faovieira** [caelum/alura-funcionalidades#928]
Um espaço onde alunos possam postar artigos referentes aos conhecimentos adquiridos. Com esta plataforma ele não precisa buscar este recurso em uma ferramenta externa. Ele pode compartilhar os post dos artigos dele nas redes sociais, redirecionando mais e mais pessoas para conhecer a Alura.

**Comment by masromao** [comment]
olá @faovieira , tudo certo?
muito boa a sugestão de um espaço de artigos de estudantes!
por enquanto não consigo te passar um prazo para uma a criação de um espaço desse tipo, mas quando formos mexer em algo nesse sentido, com certeza lembraremos da sua ideia!

muito obrigado novamente

abraços e bons estudos : )

**Comment by giovana-armidoro** [comment]
fechando a issue, pessoal

mas podem voltar a comentar se quiserem :)
