### ISSUE TITLE
Material - Curso - Didática

### ISSUE THREAD

**Issue by luizmw** [caelum/alura-funcionalidades#929]
A intercalação entre videoaulas e questionários é uma boa estratégia de fixar a aprendizagem do estudante.
Porém, uma coisa que notei já em alguns cursos, da Alura, é que, embora cada video possua um resumo e descrição do conteúdo abordado, acho que seria bom se ao final do curso fosse disponibilizado um arquivo .pdf com um resumão de tudo que foi visto. Sem dúvida, seria muito útil, algo como um guia para não precisar futuramente rever videos e material na íntegra.
Ademais, deixo minhas saudações e agradecimentos ao instrutor Daniel Artine e toda a equipe envolvida no curso. 
Grande abraço!

**Comment by masromao** [comment]
Olá, @luizmw , obrigado pela sugestão!
Muito interessante a sua ideia de um pdf com o resumo do conteúdo ao final do curso.

Infelizmente não tenho uma previsão para mudanças desse tipo na plataforma, mas qualquer atualização em relação a isso, levaremos sua ideia em consideração, ok?

Abraços e bons estudos!

**Comment by giovana-armidoro** [comment]
fechando a issue, pessoal

mas podem voltar a comentar se quiserem :)
