### ISSUE TITLE
App para TV ou Ps4

### ISSUE THREAD

**Issue by Micheltpd** [caelum/alura-funcionalidades#93]
Já pensaram em fazer o app da alura para TVs ou PS4?
Sempre que me pego nesses aparelhos lembro,  puxa, se tivesse apurar fazia por aqui.

**Comment by felipetorres** [comment]
Oi @Micheltpd, já pensamos em fazer um app para smart TVs, mas a logística é meio complicada.

Então, fizemos diferente: fizemos os apps mobile compatíveis com o Chromecast, para quem quiser acompanhar as aulas numa tela maior.
