### ISSUE TITLE
Opção de abrir tickets de suporte de dentro da própria conta Alura - Já logado e autenticado na conta

### ISSUE THREAD

**Issue by gmcordeiro** [caelum/alura-funcionalidades#930]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.
Estou tentando trocar o e-mail da minha conta e para isso preciso abrir um ticket, por não ter mais acesso ao e-mail antigo eu preciso abrir esse ticket pelo novo e estou encontrando muita dificuldade em provar que eu... sou eu. Sempre cai em um bot que não consegue identificar as informação e acabo tendo que começar tudo de novo. Se eu pudesse abrir o ticket já logado na minha conta Alura com um formulário onde eu poderia inserir as informações necessárias, cada qual em seu próprio campo, seria muito mais fácil o contato, tanto para o bot, que não teria que ficar analisando texto pra achar as informações pois cada uma teria o seu próprio campo (como cpf, etc.), quanto por mim, cliente. Além disso, por já estar logado na minha conta, não precisaria provar minha identidade, já que as informações que estão lá fui eu mesmo quem colocou. Inclusive o link dela para essa conta do github.

 - Por e-mail estou caindo nessa situação: eu insiro as informações e o bot não consegue entender que elas estão lá e me solicita as mesmas informações de novo.

**Comment by artnicodemus** [comment]
Olá @gmcordeiro , obrigado por trazer a situação com todos detalhes! Realmente é um corner case raro de acontecer, mas muito importante pra gente ficar de olho por aqui e entender mais a fundo.
Verifiquei aqui e parece que nesse momento a sua conta já consta com o novo email, correto? Então alguém do atendimento conseguiu te ajudar?

**Comment by BrazAlice** [comment]
Olá pessoal, estou fechando a issue. Qualquer coisa podem reabrir!
