### ISSUE TITLE
Inclusão de Campo para Patentear Ideias

### ISSUE THREAD

**Issue by rom-355ai** [caelum/alura-funcionalidades#931]
Olá equipe da plataforma,

Gostaria de sugerir uma melhoria que pode beneficiar tanto os usuários quanto a própria plataforma. Atualmente, percebo que muitas pessoas podem se sentir inibidas em compartilhar suas novas ideias por receio de que possam ser utilizadas sem sua permissão ou reconhecimento.

Uma maneira de encorajar os usuários a compartilharem suas ideias com mais confiança e proteção seria a inclusão de um campo para patentear novas ideias. Esse recurso permitiria que os usuários registrassem suas ideias de forma mais segura e com um nível de proteção legal.

Acredito que ao implementar esse campo, a plataforma demonstraria um compromisso com a proteção da propriedade intelectual dos seus usuários, incentivando a inovação e a criatividade na comunidade.

Espero que minha sugestão seja considerada e que possamos juntos tornar a plataforma um ambiente ainda mais acolhedor para o compartilhamento de ideias inovadoras.

Obrigado pela atenção e aguardo ansiosamente por possíveis atualizações nesse sentido.

Atenciosamente,
__________________
Rômulo C Santos

**Comment by artnicodemus** [comment]
Olá, muito obrigado pelo feedback @rom-355ai , bem interessante a sua ideia!

Infelizmente não é possível aplicar esse framework neste nosso contexto de sugestão de funcionalidades.
Pelo que checamos na LPI (Lei de Propriedade Industrial), não é possível patentear uma feature de produto digital. 
Segundo consta lá: "é excluído de proteção como invenção ou como modelo de utilidade uma série de ações, criações, ideias abstratas, atividades intelectuais, descobertas científicas, métodos ou inventos que não possam ser industrializados.".
Outro ponto também é que, mesmo se possível, no momento não conseguimos realizar os esforços necessários que demandaria esse framework de sugestões patenteadas.

Mas agradecemos por trazer a ideia! Abraços e bons estudos!

**Comment by juliagodinhoo** [comment]
Fala, pessoal!

Vou fechar a issue, mas podem voltar a comentar se quiserem :)

**Comment by rom-355ai** [comment]
Olá, e quanto o certificado, não foi enviado respondi ao questionario ario, assisti as aulas pela plataforma mais de uma vez.
Poderia verificar no pra mim, se possível!?

Obrigado,

Rômulo C Santos
1198327-2288

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
