### ISSUE TITLE
Cursos finalizados nos cursos em andamento

### ISSUE THREAD

**Issue by rafarodcor** [caelum/alura-funcionalidades#932]
Permitir que cursos já finalizados possam ser vistos novamente nos cursos em andamento.
Às vezes é necessário reassistir cursos ou até formações na plataforma e a navegação não ajuda muito.
Considere como um Replay Mode. =D

**Comment by giovana-armidoro** [comment]
oii, obrigada pela sugestão!

não temos planos de implementar algo como reset de cursos, a ideia é que o progresso continue sempre ali
agora, sobre um curso concluído permanecer nos cursos em andamento na dashboard é algo que não pensamos, vamos discutir em torno disso quando a dashboard passar por melhorias, ok?

abraços e bons estudos!

**Comment by juliagodinhoo** [comment]
Vou fechar a issue aqui, pessoal!

Podem voltar a comentar, se quiserem :))
