### ISSUE TITLE
Funcionalidades para a tela Imersão | Alura

### ISSUE THREAD

**Issue by bruneltz** [caelum/alura-funcionalidades#933]
**Descreva a funcionalidade que você gostaria que tivesse na plataforma.**

Recentemente abri a tela da [Imersão da Alura](https://cursos.alura.com.br/imersoes/) e tive o sentimento que poderia ter mais funcionalidades.

Sugiro que a tela de Imersões tivesse algumas mudanças:
- Filtros de assunto, como `Python`, `Back-end`, `Front-end`, `IA`, para dar mais "poder" ao usuário
- Identificar a Data da Imersão, para que o usuário tenha noção de quão ultrapassado pode estar o conteúdo
- Identificar a Popularidade da Imersão, para incentivar o usuário de alguma forma
- Adicionar imagens aos cards que estão faltando, pois isso pode causar estranheza ao usuário pela falta de padrão  

<img width="588" alt="image" src="https://github.com/caelum/alura-funcionalidades/assets/49597629/12a6587a-fe03-453d-8ea9-49bb1a912d8d">

Obrigado

**Comment by giovana-armidoro** [comment]
oii Bruno, muito obrigada por trazer as sugestões!
os pontos que vc levantou fazem muito sentido para melhorar a experiência dos alunos
vou levar isso para o time para levar em consideração quando essa página for passar por melhorias

abraços e bons estudos! :)
