### ISSUE TITLE
Alguns cursos não estão dentro das Formações, deveria ter um lugar agrupando eles para que os alunos possam encontrar mais facilmente. 

### ISSUE THREAD

**Issue by thisvic** [caelum/alura-funcionalidades#934]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

**Comment by giovana-armidoro** [comment]
oii, obrigada pela sugestão!

na página [Todos os Cursos](https://cursos.alura.com.br/courses) você consegue conferir uma listagem de todos os cursos da Alura, até mesmo aqueles que não estão em Formações. Menu Estudar -> Todos os cursos
espero que isso ajude!

abraços e bons estudos! :)

**Comment by juliagodinhoo** [comment]
Vou fechar a issue aqui, pessoal!

Podem voltar a comentar, se quiserem :))
