### ISSUE TITLE
Possibilidade de se criar perfis de estudo, para amigos ou casais que compartilham conta

### ISSUE THREAD

**Issue by MarceloRyujji** [caelum/alura-funcionalidades#935]
Ola time, agradeco este espaco para poder sugerir uma nova funcionalidade a escola Alura, para mim uma coisa que falta seria a possibilidade de criar perfis, eu nao me importaria de pagar um pouco a mais na assinatura para ter o direto a criar perfis, com certificados sairiam nos nomes dos perfis. obrigado pelo espaco e tenham uma otima semana.

**Comment by giovana-armidoro** [comment]
oii, obrigada pela sugestão!
não estamos com planos de criar novos tipos de assinaturas no momento :( mas vou deixar salva sua sugestão para considerarmos no futuro

abraço e bons estudos!

**Comment by juliagodinhoo** [comment]
Vou fechar a issue aqui, pessoal!

Podem voltar a comentar, se quiserem :))
