### ISSUE TITLE
Caderno virtual

### ISSUE THREAD

**Issue by jpnunes90** [caelum/alura-funcionalidades#936]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

Acho interessante a implementação de um caderno virtual onde eu possa adicionar anotações das aulas, separar por assuntos, fazer resumos e etc. Algo onde eu possa voltar a qualquer momento para relembrar de algum detalhe das aulas que já fiz, anotações que achei pertinente naquele momento e etc. ate mesmo para anotar vários links e sugestões de sites que são passados durantes as aulas

**Comment by giovana-armidoro** [comment]
oii, obrigada por sua sugestão!

sabemos que as anotações ajudam muito nos estudos, lançamos uma feature de caderno a um tempo atrás, mas ela não atingiu a expectativa (não só em engajamento como em outros pontos) que esperávamos quando lançamos o MVP em 2018/19
não temos planos para uma feature relacionada a isso no momento, como alternativa sugiro o uso do Notion, tem muitas possibilidades para organizar suas anotações, eu uso bastante :)

abraços e bons estudos!

**Comment by BrazAlice** [comment]
Ei pessoal, estou fechando a issue. Se for preciso, podem reabrir.
