### ISSUE TITLE
CURSOS / FORMAÇÕES EMITIDOS NO CERTIFICADO

### ISSUE THREAD

**Issue by Coonduta** [caelum/alura-funcionalidades#937]
Conclui a mesma formação, porque teve atualização de um único curso, realizando a substituição de um pelo outro. Nesse sentido, no certificado, seria interessante a formação também atualizar, somente substituindo o curso, não deixando duas registradas no certificado. No sentido de que o curso substituído, mas concluído pelo aluno, fosse direcionado ao campo de Cursos, sendo contabilizado junto aos demais cursos realizados. Isso porque, possibilitaria a melhor visualização das informações no certificado, sem que houvesse repetição, também diminuindo o número de páginas, por exemplo. Por fim, os complementos poderiam ser indicados abaixo do campo curso, caso houvesse substituição, podendo ser: "Conteúdo Complementares Concluídos"

Resumindo: Acredito que não precisava ser registrada a mesma Formação no certificado, somente deveria ser ajustadas as informações de acordo com a atualização, colocando o curso ou conteúdo substituído no campo indicado, facilitando a visualização das informações do certificado. 

![Captura de tela 2024-05-16 135706](https://github.com/caelum/alura-funcionalidades/assets/170029552/59ae99a7-451a-4ae2-93a8-72aaea5839d2)

**Comment by giovana-armidoro** [comment]
oii, obrigada pela sugestão!
o ponto que você trouxe faz sentido, progresso e certificados é um assunto complexo que precisa ser bastante analisado antes de mudanças, não temos planos no momento de mexer nessa configuração de certificados, mas vou levar essa questão para o time para discutirmos o que poderia ser feito.

enquanto isso, o que você pode fazer é ocultar a Formação que você não quer que apareça no certificado
clicando no botão "Ocultar Formação", a Formação não aparecerá ao imprimir ou fazer download do certificado
![image](https://github.com/caelum/alura-funcionalidades/assets/92942899/bc92984e-131d-40bb-9d3e-a9ea3c92f669)

abraços e bons estudos!

**Comment by juliagodinhoo** [comment]
Vou fechar a issue aqui, pessoal!

Podem voltar a comentar, se quiserem :))
