### ISSUE TITLE
Ranking por empresa

### ISSUE THREAD

**Issue by lrobertodaldegan** [caelum/alura-funcionalidades#938]
Atualmente acesso a plataforma Alura via e-mail da empresa onde atuo. Sei que há um ranking geral da ferramenta atuamente, mas seria interessante um ranking entre os colaboradores da mesma empresa (quando o tipo de licença estiver atrelado a empresa).

**Comment by giovana-armidoro** [comment]
oi Lucas, valeu pela sugestão!

essa parte de ranking da plataforma precisa de melhorias, mas não temos planos para mexer nisso no momento

agora, sobre o ranking específico da empresa, você pode verificar com seu gestor(a) a viabilidade de disponibilizar essa informação
dependendo da contratação, existe um painel de acompanhamento para a gestão onde estão disponibilizadas informações sobre os colaboradores, com isso é possível planejar um rankin/gamificação entre a empresa

abraços e bons estudos!

**Comment by juliagodinhoo** [comment]
Vou fechar a issue aqui, pessoal!

Podem voltar a comentar, se quiserem :))
