### ISSUE TITLE
Permitir que os alunos consumam seus dados de cursos e formações concluídos através da API da Alura

### ISSUE THREAD

**Issue by mtpontes** [caelum/alura-funcionalidades#939]
Para consumir dados vinculados ao próprio usuário a API da Alura só possui o endpoint /dashboard, que apenas retorna dados do dashboard, como os planos de estudo que ele segue e quais cursos está fazendo. 

Gostaria que essa API retornasse dados mais úteis sobre o usuário na plataforma, como os cursos e formações que ele concluiu. Isso permitiria aos alunos consumir esses dados da API para utiliza-los em um projeto de site pessoal, tendo fácil acesso aos dados de cursos que concluímos.

No endpoint https://cursos.alura.com.br/user/nomeDoUsuario/fullCertificate/tokenDoUsuario vocês tem a implementação desse recurso, mas ele retorna um HTML. Então bastaria usar essa lógica para retornar um JSON, facilitando assim o consumo desses dados.

**Comment by juliagodinhoo** [comment]
Oi @mateuspontess!

Agradecemos demais a sua sugestão! Iremos colocar sua proposta em nosso backlog, mas não podemos garantir a implementação, certo?

Tenha um ótimo dia e bons estudos pra você 😄

**Comment by BrazAlice** [comment]
Ei pessoal, estou fechando a issue. Se for preciso, podem reabrir.
