### ISSUE TITLE
Compartilhar plano de estudo

### ISSUE THREAD

**Issue by pedrofernandesfilho** [caelum/alura-funcionalidades#94]
Ter a possibilidade de compartilhar um plano de estudo apenas com pessoas específicas ou até mesmo com um time (empresa por exemplo).

**Comment by designernatan** [comment]
@pedrofernandesfilho valeu pela sugestao

hoje vc consegue fazer isso deixando o PDE público e mandando o link para essas pessoas

---

no plano empresarial Corp Plus hoje tem esse controle para deixar o mesmo PDE para um time ou uma pessoa específica

dá um toque na pessoa de gestão da sua empresa sobre :)

**Comment by pedrofernandesfilho** [comment]
Se o plano de estudo estiver público qualquer pessoa pode encontrar e ver?

**Comment by designernatan** [comment]
@pedrofernandesfilho exatamente, ele fica Visível para qualquer pessoa na web

**Comment by pedrofernandesfilho** [comment]
Entendi.
A minha ideia é poder criar um plano de estudo deixar ele visível apenas para pessoas de minha escolha. Então teria que ser um plano de estudo privado e implementar numa forma de permitir que pessoas que eu escolha vejam esse plano de estudo.

**Comment by designernatan** [comment]
Saquei pedro! Por hora para aluno(a) não temos essa feature.

Se sua conta for empresarial, conversa com a gestão para ver a possibilidade do plano Corp Plus pois aí sim rola fazer isso. Inclusive Planos privados para pessoas específicas.
