### ISSUE TITLE
Recomendação de próxima formação

### ISSUE THREAD

**Issue by LuanHSL** [caelum/alura-funcionalidades#940]
No final da formação apresentar algo como "Veja também" ou "Próximos passos", para direcionar aos próximos estudos, algo parecido com:
![Screenshot_1](https://github.com/caelum/alura-funcionalidades/assets/61790737/e5c81d42-9854-41cc-8b90-ee6ae2bd0a74)
porém aqui: 
![Screenshot_2](https://github.com/caelum/alura-funcionalidades/assets/61790737/b7b7c69c-0734-4a70-b8f2-42fae999d55d)

**Comment by juliagodinhoo** [comment]
Oi @LuanHSL!

De fato é muito interessante dermos mais um direcionamento de próximos passos e isso casa muito com os planos e estratégias que estamos adotando esse ano para melhorar a descoberta de conteúdo na plataforma.

Muito obrigado pela sua sugestão! 

Abraços e bons estudos :)

**Comment by BrazAlice** [comment]
Vou fechar a issue aqui, pessoal!

Podem voltar a comentar, se quiserem :)
