### ISSUE TITLE
Arquivo CSV

### ISSUE THREAD

**Issue by danicalves** [caelum/alura-funcionalidades#941]
Uma possibilidade de download de todos os cursos disponíveis, com tema, duração do curso entre outras informações que acharem relevantes num arquivo CSV direto pela plataforma.

**Comment by designernatan** [comment]
@danicalves valeu pela sugestao!

entendo o valor da proposta, penso que seria complicado priorizar algo que possivelmente pouquissimas pessoas estudantes usariam. De curiosidade, por qual motivo vc tem essa necessidade hoje?


---

MAS VOU DEIXAR UM DESAFIO...

você pode tentar fazer exatamente isso via webscrapping, sei que antigamente tínhamos uns cursos disso na alura, mas talvez eles foram desativados

sei que nao eh o ideal, mas tem uma pagina que tem pelo menos o titulo dos cursos
https://cursos.alura.com.br/courses

outra ideia é pegar essa pagina e ir tentando montar o excel com ajuda do GPT

enfim... ideias :)) 

abcs e bons estudos!

**Comment by giovana-armidoro** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
