### ISSUE TITLE
Reiniciar o progresso no curso 

### ISSUE THREAD

**Issue by BrunoSoneca86** [caelum/alura-funcionalidades#942]
Olá uma coisa que acharia interessante incrementar na plataforma seria reiniciar o progresso no curso. De tal forma que se a pessoa desejasse seria mais fácil e motivador pois as respostas estariam ocultas e esse reset seria uma motivação. Isso é algo fácil e que agradaria as pessoas

**Comment by juliagodinhoo** [comment]
Oi @BrunoSoneca86, muito obrigado pela sua sugestão!

Falamos um pouco sobre isso nessa [issue aqui ](https://github.com/caelum/alura-funcionalidades/issues/635)

Abraços e bons estudos 😄

**Comment by BrunoSoneca86** [comment]
Pelo que entendi não tem como reiniciar o progresso né?

**Comment by juliagodinhoo** [comment]
Isso! Por enquanto estamos sem planos de mexer com essa funcionalidade

**Comment by giovana-armidoro** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
