### ISSUE TITLE
Play automático nos vídeos de um curso

### ISSUE THREAD

**Issue by israelsantiago** [caelum/alura-funcionalidades#943]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.
 - Possibilitar a configuração, em um curso, de play automático de vídeos.

**Comment by designernatan** [comment]
@israelsantiago valeu pela sugestao!

hoje temos essa opção apenas para alunos diretos, ou seja, que não são de contratos corporativos

[o romão aqui do time explicou nesta issue sobre](https://github.com/caelum/alura-funcionalidades/issues/865#issuecomment-1739559942)

abcs e bons estudos!

**Comment by giovana-armidoro** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
