### ISSUE TITLE
Issue Report: Buscar do Fórum - Sem funcionar

### ISSUE THREAD

**Issue by Lu1zEduard0** [caelum/alura-funcionalidades#945]
# Problema:
A funcionalidade de busca no fórum da Alura não está retornando resultados, mesmo quando são realizadas pesquisas por títulos, palavras-chave dentro dos artigos, ou termos em maiúsculas e minúsculas.

# Testes Realizados

## Pesquisa pelo Título:

**Título específico: Pesquisei o título completo de um artigo existente no fórum.**

Resultado esperado: O artigo correspondente deveria aparecer nos resultados da busca.
Resultado observado: Nenhum resultado foi retornado.
Pesquisa por Palavras dentro do Artigo:

**Palavras-chave específicas: Pesquisei termos específicos que estão presentes no corpo de vários artigos.**

Resultado esperado: Todos os artigos contendo essas palavras-chave deveriam aparecer nos resultados.
Resultado observado: Nenhum resultado foi retornado.
Pesquisa com Variantes de Maiúsculas e Minúsculas:

**Termos em maiúsculas: Pesquisei termos em letras maiúsculas que estão presentes nos artigos.**

Termos em minúsculas: Realizei a mesma pesquisa utilizando letras minúsculas.
Resultado esperado: Resultados relevantes deveriam aparecer independentemente da capitalização dos termos.
Resultado observado: Nenhum resultado foi retornado para ambas as variantes.
Pesquisa em Diferentes Fóruns:

**Fórum DevOps: Realizei pesquisas específicas no fórum DevOps.**

Outros fóruns: Realizei pesquisas em outros fóruns da Alura para verificar se o problema é generalizado.
Resultado esperado: Resultados relevantes para as pesquisas realizadas em cada fórum específico.
Resultado observado: Nenhum resultado foi retornado em todos os casos.

**Testes em Navegadores Diferentes:**

Google Chrome: Realizei as pesquisas usando o navegador Google Chrome.
Mozilla Firefox: Realizei as mesmas pesquisas usando o navegador Mozilla Firefox.
Microsoft Edge: Repeti os testes no navegador Microsoft Edge.
Safari: Testei a busca no navegador Safari (caso aplicável).

Resultado esperado: Resultados relevantes para as pesquisas realizadas em cada navegador.
Resultado observado: Nenhum resultado foi retornado em todos os navegadores testados.

# **Conclusão**

A funcionalidade de busca no fórum da Alura não está funcionando corretamente, pois falha em retornar resultados para pesquisas básicas e específicas. Este problema persiste independentemente do fórum selecionado, dos termos pesquisados, da capitalização das palavras, e do navegador utilizado. Este comportamento sugere que pode haver um bug no sistema de busca do fórum, necessitando de uma investigação e correção por parte da equipe técnica da Alura.

![Insira aqui a descrição dessa imagem para ajudar na acessibilidade](https://cdn1.gnarususercontent.com.br/1/6008254/eab4fee7-87c5-4328-a434-eca82ac6281b.png)  

![Insira aqui a descrição dessa imagem para ajudar na acessibilidade](https://cdn1.gnarususercontent.com.br/1/6008254/4638dc0a-f039-4ded-a837-8b561ec9eac7.png)  

![Insira aqui a descrição dessa imagem para ajudar na acessibilidade](https://cdn1.gnarususercontent.com.br/1/6008254/884ec758-77e1-4dbd-8f1e-32d105349598.png) 
![Insira aqui a descrição dessa imagem para ajudar na acessibilidade](https://cdn1.gnarususercontent.com.br/1/6008254/25021152-19cd-4f54-ae83-9d05631935c0.png)

**Comment by juliagodinhoo** [comment]
Oi @Lu1zEduard0, muito obrigado pelo report! 

Realmente testei e a busca não está funcionando corretamente. Passei pro time responsável e, assim que possível, irão ver o que está acontecendo

Abraços e bons estudos :)

**Comment by giovana-armidoro** [comment]
oi, pessoal! retornando pra avisar que esse bug foi corrigido \o/
caso tenha algum problema pode avisar a gente por aqui

vou fechar a issue mas podem voltar a comentar se quiserem :)
