### ISSUE TITLE
Alerta: Data de conclusão do curso 

### ISSUE THREAD

**Issue by wilkernel** [caelum/alura-funcionalidades#946]
Seria interessante que a Alura enviasse alertas das datas limites de conclusão das formações, se possível ao whatsapp ou email do aluno.

**Comment by juliagodinhoo** [comment]
Oi @Wil-JC-Pimenta, agradeço a sua sugestão!

No momento não temos planos de acrescentar a funcionalidade de colocar data limite para conclusão de uma formação, mas qualquer mudança em relação a isso, iremos levar seus pontos em consideração, tá bom?

Abraços e bons estudos 😄

**Comment by giovana-armidoro** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
