### ISSUE TITLE
Filtro de cursos e formações concluídos

### ISSUE THREAD

**Issue by fpadias** [caelum/alura-funcionalidades#947]
Pela enorme quantidade de cursos e formações (maravilhoso), encontro muita dificuldade e ,perco muito tempo, buscando novidades e cursos que não tenha feito, porque não há a marcação de cursos e formaçoes não concluídas e, melhor ainda, um filtro de matriculados e concluídos.

Isso no menu ESTUDAR nas opções Cursos e Formações.

Adjunto duas imagens para mostrar como imagino.
![formacoes](https://github.com/caelum/alura-funcionalidades/assets/79057814/05d346e0-82d0-4e1f-b1c2-b2fbcf73c0ab)
![cursos](https://github.com/caelum/alura-funcionalidades/assets/79057814/8f292bb1-9b34-47d7-9f57-3a643d1bb0c4)
As imagens fiz com botão de formações concluídas e a ideia é que oculte as concluídas...

Mjuito obrigado.

Parabéns pelo trabalho, sou fã da Alura, mudou a minha carreira... 

Abraços

**Comment by artnicodemus** [comment]
Opa @fpadias , muito obrigado pelo feedback!
Realmente faz sentido ter filtros e marcadores de progresso nessas páginas, inclusive estamos tocando algumas frentes que mexem em páginas de conteúdo como estas, porém ainda não temos um prazo pra ter novidades no ar.
O que pode te ajudar por enquanto é a página de 'Meus cursos' (no menu estudar), que apresenta seus cursos concluídos ou com progresso!

Muito obrigado, abraços e bons estudos!

**Comment by giovana-armidoro** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
