### ISSUE TITLE
Automatização de fim de curso.

### ISSUE THREAD

**Issue by DevXJ** [caelum/alura-funcionalidades#948]
Eu gostaria que ao final do curso, ter a opção de linkar o curso nas plataformas automaticamente,

por exemplo:

linkar o linkedin com a alura, e assim que terminar um curso ser postado lá.

**Comment by artnicodemus** [comment]
Opa, obrigado pelo feedback @DevXJ !
Muito legal a sua ideia, a gente vem planejando mudanças para essa parte de finalização de cursos para tornar mais fácil de compartilhar conquistas e descobrir novos conteúdos. Porém, ainda não temos um prazo pra ter atualizações disso no ar.

Abraços e bons estudos!

**Comment by juliagodinhoo** [comment]
Oi pessoal!

Tô fechando a issue aqui, mas podem voltar a comentar, se quiserem :)
