### ISSUE TITLE
Reiniciar curso 

### ISSUE THREAD

**Issue by CiVcitorio** [caelum/alura-funcionalidades#949]
Qual a Funcionalidade? 
Botão com a função de reiniciar um cruso ou refazer curso.

Qual o problema de hoje.
ao refazer um curso as aulas estão marcadas como concluídas o que dificulta a identificação de onde estamos, com isso temos que ficar marcando onde estamos, por exemplo estou refazendo o curso de java e como já tinha concluído um trecho, fica complicado saber onde estou porque as aulas estão como já realizadas.

Qual o benefício?
poder controlar as aulas que precisamos refazer e marcar novamente como concluída ou não e / ou refazer um curso inteiro.

Cordialmente, Cibele Victorio

**Comment by giovana-armidoro** [comment]
oi, muito obrigada pela sugestão!

infelizmente por hora não temos planos para trabalhar em algo como reiniciar/resetar cursos ou formações, mas de qualquer forma vou levar sua sugestão para discussão na equipe.

abraços e bons estudos :)

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
