### ISSUE TITLE
Área de arquivos por Aula.

### ISSUE THREAD

**Issue by felipmarinho** [caelum/alura-funcionalidades#95]
Acho que poderia ter uma área destina somente aos arquivos/link necessários para fazer download por Aula e relacionar a qual atividade ele se refere. Tendo em vista que os arquivos ou links as vezes ficam na transcrição abaixo dos videos ou nos exercícios na sequência dos videos.

**Comment by designernatan** [comment]
valeu pela sugestao @felipmarinho 

identificamos essa issue e ideia é tentar seguir um padrão (talvez um botão específico para isso), problema maior hoje são os cursos mais antigos ou com baixa demanda que acabamos operando mais no modo reativo

se você tiver com dificuldade para achar os arquivos de um curso, já manda direto uma sugestão de alteração no próprio curso 

aí os times de revisão e transcrição já conseguem atuar diretamente no curso que está fora desse padrão
![print mostrando o menu na aula da alura com um circulo vermelho em volta do sugerir alteração](https://user-images.githubusercontent.com/5431347/76771290-e47a1380-677d-11ea-9e96-e6e6c72575b4.png)
