### ISSUE TITLE
Issue Report

### ISSUE THREAD

**Issue by mulliru** [caelum/alura-funcionalidades#950]
**Descrição do Problema**
Durante a nova atualização do header, observei um problema estético relacionado à imagem da FIAP que aparece para os alunos FIAP/Alura. A imagem tem um fundo branco que interfere na estética do site. Seria necessário remover o fundo da logo da FIAP para corrigir este problema.

**Imagem do Problema**
![image](https://github.com/user-attachments/assets/790e2740-d7d1-476c-bdcf-8bf35f286f8e)

**Passos para Reproduzir**

- Acesse o site da Alura.
- Faça login como aluno FIAP/Alura.
- Observe o header e a imagem da logo FIAP com o fundo branco.

**Comportamento Esperado**
A imagem da logo FIAP deveria aparecer sem fundo branco, mantendo a estética do site harmoniosa.

**Comment by giovana-armidoro** [comment]
oi Murillo, muito obrigada pela sugestão!

essa variação de header aparece para os alunos que acessam vinculados a uma empresa (como essa caso a FIAP)
no primeiro lançamento dessa atualização do header precisamos adicionar esse box branco para que o logo das várias empresas diferentes se encaixassem
nossa intenção é que as próximas versão tragam melhorias, inclusive para essa questão
já levei isso para o time levar em consideração nas próximas mudanças

abraços e bons estudos!
