### ISSUE TITLE
Melhoria na Plataforma Alura: Destaque das Atualizações de Cursos

### ISSUE THREAD

**Issue by NatoFernandes** [caelum/alura-funcionalidades#951]
Gostaria de sugerir uma melhoria na plataforma Alura que pode facilitar ainda mais o aprendizado contínuo dos alunos. Sempre que um curso existente for atualizado, seria interessante que a plataforma comparasse e sinalizasse as novidades, destacando o que há de novo no conteúdo revisado. Essa funcionalidade ajudaria os alunos a identificar rapidamente as mudanças e atualizações, garantindo que estejam sempre a par das informações mais recentes e das melhores práticas do mercado.

Exemplo: 
Fiz um curso de Cypress ano passado e fou uma instrutora, depois disso surgiu um novo com outra instrutora e essa semana percebi que já tem uma outra atualização com outra instrutura. Farei o curso novamente, mas seria interessante que as novidades do curso atual fossem destacadas.

**Comment by giovana-armidoro** [comment]
oii, obrigada pela sugestão!

faz muito sentido esse ponto que levantou! vou levar essa questão para discutir com o time e, quando formos fazer alguma atualização na experiência dos cursos, levaremos isso em consideração.

abraços e bons estudos! :)

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente! 
Podem voltar a comentar, se quiserem ;)
