### ISSUE TITLE
Tirando dúvidas durante os cursos

### ISSUE THREAD

**Issue by Lipedev300** [caelum/alura-funcionalidades#953]
Durante qualquer curso da Alura, mesmo os cursos sendo em vídeo, a gente podia ter como tirar as dúvidas com os tutores e professores daquele respectivo curso, ou por texto ou por voz mesmo, mas deveria ter esse recurso na própria página de cada curso na plataforma.

**Comment by juliagodinhoo** [comment]
Oi @Lipedev300, excelente a sua sugestão!

Pensando exatamente nisso, hoje temos 3 possibilidades de você conseguir tirar as suas dúvidas com tutores:

1. Através do nosso **[canal do discord](https://discord.com/invite/QeBdgAjXnn)**

**Comment by juliagodinhoo** [comment]
Oi @Lipedev300 , excelente a sua sugestão:

Pensando exatamente nisso, hoje temos 3 possibilidades de tirar suas dúvidas com os nosso tutores:

1. Através do nosso **[canal do discord](https://discord.com/invite/SK9bj7hEYD)**
Ao entrar, você pode selecionar a(s) escola(s) que está estudando e ter acesso a uma série de conteúdos que podem te auxiliar no seu processo de aprendizado, além de poder tirar suas dúvidas com o instrutor, claro :)

2. Através do **[fórum](https://cursos.alura.com.br/forum/todos/1)**
É possível você não apenas deixar as suas dúvidas, como pode procurar por dúvidas de seus colegas que pode coincidir com as suas, aprendendo com elas.
Buscando facilitar ainda mais, dentro na própria tela de aula, existe um link de "fórum do curso" que te encaminhará para o fórum específico desse curso com todas suas respectivas dúvidas. Segue imagem mostrando o link localizado no **_menu lateral da tela de aula_**:
![image](https://github.com/user-attachments/assets/75f95d8b-9186-4018-bf0e-a2c9b4a46ca8)

3. Através da **Luri**, nossa inteligência artificial
Por fim, e não menos importante, pensando numa forma de tirar a dúvida de nossos alunos _**em tempo real**_, desenvolvemos a Luri, nossa IA munida especificamente com nossos conteúdos Alura. Ela fica localizada na própria tela de tela e está disponível a partir do plano PRO. Caso tenha interesse, pode conhecer um pouco mais através de [nosso site](https://www.alura.com.br/luri-inteligencia-artificial) ou [central de ajuda](https://suporte.alura.com.br/support/solutions/articles/72000606593-conheca-a-luri-nossa-intelig%C3%AAncia-artificial)

Espero que tenha conseguido te ajudar!

Abraços e bons estudos 😄

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
