### ISSUE TITLE
[Melhoria/Acessibilidade]: Contraste das novidades

### ISSUE THREAD

**Issue by Noriller** [caelum/alura-funcionalidades#954]
Ao abrir as novidades, eu não consigo diferenciar o que já foi visto do que não foi por causa do contraste e falta de qualquer outra indicação que já foi me mostrado essas novidades ou não

![image](https://github.com/user-attachments/assets/279befd4-2119-49e3-a452-f2c26f41b450)

Eu tenho que me concentrar muito e mudar de lugar pra luz ambiente não atrapalhar o que estou vendo pra conseguir ver a diferença, mas comparado com como era antes, a diferença de cores e contraste é tão pequena que dificulta muito ver o que é "novidade" do que já "foi visto".

Por causa disso, sinto também falta de alguma indicação que não seja por cor de background para identificar o que é "novo" do que não é.

**Comment by juliagodinhoo** [comment]
Oi @Noriller, muito obrigado pelo feedback!

Concordo super com você! De fato a falta de contraste e feedback sobre o que já foi visto não está legal. Levarei seus pontos para discutirmos com a equipe, só não consigo te prometer prazo.

Abraços e bons estudos :)

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
