### ISSUE TITLE
resetar Curso

### ISSUE THREAD

**Issue by nickzvlr** [caelum/alura-funcionalidades#955]
Seria ótimo uma função de resetar o progresso de um curso e começa-lo do zero.

**Comment by juliagodinhoo** [comment]
Oi @nickzvlr !

Entendemos sua sugestão, mas como apontamos [nessa issue](https://github.com/caelum/alura-funcionalidades/issues/859#issuecomment-1701897454), por ora estamos sem planos em possibilitar o reset de cursos.

Agradecemos sua sugestão!

Abraços e bons estudos :)

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
