### ISSUE TITLE
Monitorias nos cursos

### ISSUE THREAD

**Issue by Lipedev300** [caelum/alura-funcionalidades#956]
Uma funcionalidade que considero muito importante para a plataforma são as monitorias ao vivo durante os cursos. Mesmo os cursos sendo gravados, seria muito bom se pudéssemos fazer contato ao vivo com os instrutores do curso para tirar dúvidas dos assuntos abordados. Claro que a comunidade pode ajudar muito, mas considero as monitorias com os instrutores muito importantes para o aprendizado. Além disso, não sei se essa função já existe, mas o bom também seria implementar exercícios práticos obrigatórios para conseguirmos finalizar o curso, para que assim todos nos sintamos cada vez mais motivados a fazer até o final, e também para facilitar o aprendizado. Talvez os exercícios até com prazos pra gente se manter firme e praticar.

**Comment by juliagodinhoo** [comment]
Oi @Lipedev300, muito obrigado pelas sugestões!

Quanto as **mentorias ao vivo**, elas existem e você pode acompanhar as próximas através do nosso [canal do discord](https://discord.com/invite/SK9bj7hEYD). Recomendo fortemente sua participação, pois para além das mentorias, é possível tirar dúvidas e se conectar com pessoas que está estudando o mesmo que você. Para acessar o local onde informa sobre as próximas mentorias no discord, clique em "eventos", localizado no menu lateral, que aparecerá um modal com as informações. Segue fluxo abaixo:
![Onde visualizar os eventos](https://github.com/user-attachments/assets/9391eae1-d083-4ca0-99c1-65fd62917808)
 
 
 Para os **exercícios práticos**, te sugiro explorar: "[7 days of code](https://7daysofcode.io/)", os "[challenges](https://www.alura.com.br/challenges?host=https://cursos.alura.com.br%22)" e as "[imersões](https://www.alura.com.br/challenges?host=https://cursos.alura.com.br%22)". Além disso, visando trazer exercícios mais desafiadores, implementamos os exercícios abertos, que estão disponíveis em alguns cursos, com expansão pra mais. Esses exercícios estão disponíveis a partir do nosso plano PRO,  vez que são corrigidos pela Luri, nossa IA. Para manter a motivação, sugiro acessar [nossa planilha ](https://docs.google.com/spreadsheets/d/1PcGAiy2XvXh8wBmzTn6g4TPMj0S60TEVh4Uk4Hq_eck/edit?_hsenc=p2ANqtz-9UlG_n7mKsqI8cmBAJSjLw2J63WnifmZaNT8n0hYswV5tLiIpPTPTcQMHQxY9lQv32Hdt3rnU8ZfkOk-E9SzuoxP4RFhMIroAJdU2PJwBtiN3zSyY&_hsmi=303146892&gid=0#gid=0)para sua organização pessoal, onde é possível você escrever seus objetivos, organizar seu processo de aprendizagem e estabelecer prazos, de acordo com sua realidade pessoal.
 
 Espero que tenha ajudado! Abraços 🤗

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
