### ISSUE TITLE
Acessibilidade da aba de atividades dos cursos 

### ISSUE THREAD

**Issue by Rodrigues-19** [caelum/alura-funcionalidades#957]
Olá! Estou estudando na A
![alura](https://github.com/user-attachments/assets/a9018b51-f70c-4cbf-8c9d-2b290b7c74f1)
lura alguns cursos de front-end esses meses. Me chamou atenção que não apenas nos cursos que fiz e estou frequentando que no campo de atividades, onde tem os títulos das aulas e as atividades do curso não tem a possibilidade de fazer um scroll apenas na aba de atividades, fazendo com que os usuários tenham que descer a página inteira caso queiram acessar um conteúdo específico da sessão que está observando. Vocês poderiam implementar essa funcionalidade?

**Comment by Rodrigues-19** [comment]
Acho que seria interessante essa funcionalidade, assim o usuário não perde a visão das informações principais (me refiro ao vídeo da aula). e consegue ver os outros conteúdos. Caso seja alguém que já possua experiência e queira acessar partes específicas do curso, isso facilitaria bastante. Além disso, poderia exibir os módulos para a direita, ao invés de para baixo ao clicar no retângulo, assim também não tamparia a visão dos componentes do curso. Espero que minha sugestão os encontre bem! Seria incrível observar a implementação

**Comment by juliagodinhoo** [comment]
Oi @Rodrigues-19, muito obrigado pela sugestão!

Estamos trabalhando em alguns pontos da plataforma e, inclusive, visando a tela de aula futuramente. Levarei seus pontos para discussão com time, só não posso garantir a implementação ou prazo.

Abraços e bons estudos 😄

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
