### ISSUE TITLE
Classificação por níveis

### ISSUE THREAD

**Issue by yuri-weasley** [caelum/alura-funcionalidades#958]
Não sei se há na plataforma, se há, ainda não achei (assinei há pouco mais de 2 meses e, ainda estou meio que "descobrindo a Alura"). 

Mas sinto falta de uma "classificação" por níveis de conhecimentos dos cursos e formações. Meio que uma divisão de cursos que estão no nível de estudantes "iniciantes", outros de estudantes "intermediários" e outros de estudantes mais "avançados". 

Também sinto falta de algo que "guie" - não sei se posso chamar assim - o aprendizado, por exemplo: Sou um estudante que nunca teve contato com TypeScript, mas quero aprender sobre a linguagem e fazer todos os cursos que a plataforma dispõe, qual a formação/formações ou curso/cursos ideal para isso? Tipo: do zero mesmo... algo que me fale: De onde começo e, por níveis, me leve a aprofundar na linguagem, até o nível do curso que pode ser considerado como mais "avançado" que a plataforma fornece, sabe?

Como falei, não sei se já existe na plataforma essa "divisão" - se existir, pfvr, me falem onde está hehe. Mas acho que seria de uma grande ajuda, principalmente para os que estudam por conta própria na Alura. No mais, meus parabéns a toda equipe que desenvolve e mantém essa plataforma fenomenal!

**Comment by juliagodinhoo** [comment]
Oi @yuri-weasley, seja-bem vindo a Alura! Espero que esteja gostando dos conteúdos e todas as demais funcionalidades pra auxiliar no seu processo de aprendizado 😄 

De fato não temos uma classificação por níveis e entendo ser bem importante para descoberta de conteúdos na plataforma. Atualmente estamos em busca de melhorar esse fluxo e levaremos esse seu ponto para discussão. 


De antemão, posso te sugerir algumas estratégias que temos aqui para solucionar esse problema:

1. Explorar os [planos de estudo públicos](https://cursos.alura.com.br/planos-estudos-publicos)
2. Fazer o [onboarding](https://cursos.alura.com.br/onboarding/goal)
3. Entrar no nosso [discord ](https://discord.com/invite/QeBdgAjXnn)e tirar suas dúvidas, como recomendação de passo-a-passo, com um instrutor
4. Explorar o [techguide ](https://techguide.sh/) com um passo-a-passo para se tornar um profissional em T
5. Explorar as formações que foram criadas com o propósito de ser esse "guia" num determinado conhecimento (exemplo desse [aqui](https://cursos.alura.com.br/formacao-typescript) em typescript)


Espero que tenha conseguido te ajudar!

Abraços e bons estudos!

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
