### ISSUE TITLE
Notificações específicas aos meus interesses

### ISSUE THREAD

**Issue by matheusvazdata** [caelum/alura-funcionalidades#959]
As notificações de cursos e formações recebidas diariamente poderiam ser específicas em relações aos conteúdos que sigo, sabe? Às vezes chega muita coisa num curto espaço de tempo e o que é, de fato, relevante para mim, vai lá para baixo.

**Comment by juliagodinhoo** [comment]
Oi @matheusvazdata, muito obrigada pela sugestão!

Realmente faz bastante sentido ter algo mais direcionado aos seus objetivos. Levarei os pontos para discussão com o time, só não posso garantir a implementação ou prazo.

Abraços e bons estudos 😃

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
