### ISSUE TITLE
Filtro do Fórum

### ISSUE THREAD

**Issue by heron03** [caelum/alura-funcionalidades#96]
Eu estava com uma duvida em um curso expecifico no fórum e só depois de um ano eu descobri que dava para fazer isto com o filtro por curso, porém os nomes dos cursos são muito grande para o campo do filtro ai acaba que tenho que ficar chutando se aquele é o curso que eu estou procurando.

![Captura de Tela (63)](https://user-images.githubusercontent.com/35074726/76618970-97d9d280-6508-11ea-801a-17232ad2a7a5.png)

**Comment by wandersonmaceds** [comment]
Oi @heron03 tudo bem?

Realmente, o nome do curso aparecer incompleto dificulta a seleção da opção correta. Precisamos ajustar isso de alguma forma a facilitar o uso dos filtros. 

Porém, tem um atalho para ir até o fórum com o filtro correto selecionado, você pode ir direto na página do curso e usar o link "fórum do curso" localizado na parte inferior direita, logo abaixo das informações do instrutor. 

Exemplo: https://cursos.alura.com.br/course/laravel-produtividade-desenvolvimento-web

Clica em "forum do curso", você via direto para as dúvidas desse curso.

**Comment by luciano-souza** [comment]
Dentro do busque por assunto, mesmo com o filtro do curso selecionado retorna respostas referentes a outros foruns. 

Não sei se isso é intencional, mas achei que atrapalha pois fiz algumas buscas e não apareceram respostas que eu queria dentro do curso (aparecia uma lista enorme com conteúdos de outros cursos) e tive que ir olhando de uma em uma as perguntas dentro do curso pra achar o que eu queria.

**Comment by wandersonmaceds** [comment]
Oi @luciano-souza me descreve o processo que vocẽ fez só para que eu consiga fazer aqui também e ter um resultado parecido para entender o que está acontecendo de fato, por favor.

**Comment by luciano-souza** [comment]
Por exemplo, estou nessa página do fórum de um curso. Como vc pode reparar todos os filtros estão selecinados específicamente para esse curso. 

Se eu tive uma dúvida em uma parte específica desse curso irei lá no campo de busque por assunto e digitarei minha dúvida.

![image](https://user-images.githubusercontent.com/41630391/78025678-d0631400-7330-11ea-8a42-0ff6eb457d73.png)

Os resultados da busca não me mostram as dúvidas relacionadas a esse fórum, mas sim a vários outros cursos (o que atrapalha muito).

Se o comportamento desejado for, mesmo com os filtros selecionados para esse curso em específico, mostrar resultados de busca que incluam outros cursos, acredito que pelo menos os primeiros resultados retornados deveriam ser relativos a dúvidas postadas no fórum do curso específico.

![image](https://user-images.githubusercontent.com/41630391/78025948-3e0f4000-7331-11ea-9f0c-390fda69279e.png)

Como vc pode ver na imagem, vieram vários outros resultados que não considero relevante para a dúvida que eu tinha que era um erro que aconteceu em uma etapa específica do curso.

Acabei abrindo uma nova pergunta no fórum.

Depois pesquisando pelo google achei a resposta para minha dúvida no mesmo fórum do curso.

Então considero que essa resultado da pesquisa não está muito amigável a nós alunos da forma que está.

Espero que tenha conseguido deixar claro.

**Comment by wandersonmaceds** [comment]
Opa @luciano-souza a pesquisa realmente não é das melhores, mas veja que ela não possui os filtros de curso etc. Então não é de se esperar que ela considere o filtro. Quando você usa a busca por termos, é uma busca mais geral e você precisa sim colocar o flutter como termo. Igual pesquisaria no Google.

**Comment by luciano-souza** [comment]
@wandersonmaceds mas no momento que eu faço a pesquisa estou numa tela que tem o filtro de curso. Então a experiência de usuário que eu espero é que levasse em consideração o filtro.
Acredito que vcs pode melhorar isso pois acredito que tem um impacto muito grande na procura de informações no forum e evitaria uma quantidade de perguntas duplicadas pois a pessoa conseguiria achar aquilo que procura com maior facilidade.
