### ISSUE TITLE
Certificado de plano de estudo - empresa

### ISSUE THREAD

**Issue by danilosrocha** [caelum/alura-funcionalidades#960]
Eu, como funcionário de uma empresa que possui vínculo com a Alura, gostaria de ter a possibilidade de emitir um certificado de um plano de estudos criado pela minha empresa. Por exemplo, em minha empresa, tenho um plano de estudos com 19 cursos, totalizando 196h, para que eu não precise publicar curso por curso no linkedin, gostaria de publicar apenas uma vez, assim como acontece com a publicação das formações, mas agora a publicação de um plano de estudos.

**Comment by maraishioka** [comment]
Oii, @danilosrocha 
Obrigada pela sugestão! 

Nós optamos por não incluir certificados por plano de estudos, pois eles não passam diretamente pela nossa curadoria. 

**Gerar certificado completo**
Você pode gerar um certificado com tudo o que você já concluiu na Alura. 
Basta ir ao Menu -> Perfil e certificados -> descer até o final da página e encontrar essa opção: 
![image](https://github.com/user-attachments/assets/1f92dc8b-693e-4a69-8621-0ec50cb2a2fe)

É possível ocultar o que preferir e, em seguida, baixar o certificado com todos os cursos do PDE. Depois, é só adicionar o título do PDE no seu LinkedIn!


Espero que isso possa ajudar! 
Abraços e bons estudos!

**Comment by danilosrocha** [comment]
Do modo que está funcionando atualmente não atende minha necessidade, já que não teria a credencial dos cursos selecionados, apenas seria um arquivo pdf gerado.

Como sugestão de melhoria desta funcionalidade, seria interessante que ao ocultar as formações, ou cursos concluídos, fosse gerado um novo link, de apenas visualização (sem aparecer a funcionalidade de ocultar os cursos) para acesso a este certificado completo.

Já que o certificado gerado com os cursos selecionados, ao final, apresenta um link de acesso, e este ainda redireciona para a página que apresenta todos cursos e formações, inclusive com as funcionalidade de ocultar ou não, o que proporciona uma visualização ruim para apresentação no linkedin.

**Comment by maraishioka** [comment]
Entendi, Danilo. Obrigada por esse relato!
Realmente, esse é um problema no fluxo, e ficaremos atentos a isso quando formos discutir atualizações para os certificados.

Obrigada novamente!
Abraços e bons estudos!

**Comment by designernatan** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
