### ISSUE TITLE
Resetar curso

### ISSUE THREAD

**Issue by gac360** [caelum/alura-funcionalidades#961]
Sugiro a possibilidade de resetar os cursos para que possamos refazer as questões novamente. Às vezes após fixar o conteúdo acho interessante revisitar questões para concluir o aprendizado, mas com as respostas já marcadas fico sem poder fazer isso.

**Comment by flavio-santos-ti** [comment]
Eu também gostaria da possibilidade de resetar a progressividade dos cursos, e com isso se manter e compravar a atualização do curso.

**Comment by maraishioka** [comment]
Oioi, @gac360 @flavio-santos-ti  !

Agradecemos a sugestão de vocês!
Entendemos as motivações, mas como apontamos nessa issue https://github.com/caelum/alura-funcionalidades/issues/859#issuecomment-1701897454, por ora estamos sem planos em possibilitar o reset de cursos.

Abraços e bons estudos :)

**Comment by designernatan** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
