### ISSUE TITLE
Retomar com criação de planos de estudo

### ISSUE THREAD

**Issue by pedro-schabarum** [caelum/alura-funcionalidades#962]
Olá! Gostei muito da nova atualização, mas está difícil ou pouco intuitivo criar novos planos de estudo.

**Comment by maraishioka** [comment]
Oioi, @pedro-schabarum! 
Ficamos super felizes que você tenha gostado da nova atualização! Nessa fase, estamos bem atentos e feedbacks como o seu são sempre muito bem-vindos.

Para criar um novo plano de estudo, o caminho é o seguinte: **Descobrir > Meus Planos de Estudo > Novo plano**. 
Se você encontrou alguma dificuldade específica nesse processo, ou em qualquer outro ponto, compartilha com a gente! Queremos garantir que a experiência seja a mais intuitiva e fluida possível.

Obrigada novamente pelo seu feedback!

**Comment by designernatan** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
