### ISSUE TITLE
[Bug] Sobreposição de elementos no header usando Alura + Pos Tech

### ISSUE THREAD

**Issue by Karyah** [caelum/alura-funcionalidades#963]
O logo e o campo de busca da Alura Pos Tech estão sobrepondo outros elementos.
Resolução da minha tela: 1366 x 768 

![image](https://github.com/user-attachments/assets/f883bc56-c9bc-41cb-aaf1-5b7e78564532)

**Comment by maraishioka** [comment]
Oioi, @Karyah! Muito obrigada pelo report!

Realmente o campo de busca esta sobrepondo os outros menus. Passei pro time responsável e, assim que possível, irão ver o que está acontecendo. Obrigada novamente!! 

Abraços e bons estudos :)

**Comment by designernatan** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
