### ISSUE TITLE
Alura PRO - DIVIDE AÊ - Íons xp

### ISSUE THREAD

**Issue by JoaoPauloPinheiroM** [caelum/alura-funcionalidades#964]
**_Alura PRO - DIVIDE AÊ:_**

Já imaginou na acessibilidade dos cursos? Já pensou na democratização da tecnologia e conhecimento para todos?

Pois bem, a criação de novos planos especiais para Universitários, com descontos ou outras funcionalidades, seria Incivilmente perfeito.

Falamos de uma coisa nossa, "Brasileiro" que é dividir.... Sim! Dividir.

Criar um plano de usuários, onde é possível criar um plano onde pode ter dois, ou três usuários dentro da plataforma, onde cada um terá seu perfil, e seus certificados, seria mais ainda incrível. 

Estudem as possibilidades, pensem sobre como poderiam se adaptar para pessoas que precisam de um ensino de qualidade.

---------------------------------------------------------------------------------------------------------------------------------------------------

 **_Íons xp:_**
 Gerar uma lojinha de ícones, emojis onde o aluno pode desbloquear dependendo do nível de xp e moedas conquistadas, irá motivar mais ainda os alunos!

**Comment by MarceloRyujji** [comment]
Fiz a mesma sugestao algum tempo atras, Alura por favor traga a possibilidade de se criar perfis :)

**Comment by maraishioka** [comment]
Oi, pessoal! Muito obrigada pelas sugestões! 

@JoaoDev01001, assim como o @MarceloRyujji mencionou, temos essa issue respondida com o tema semelhante: https://github.com/caelum/alura-funcionalidades/issues/935
A sugestão dos perfis está salva para ser considerada quando for discutido o tema futuramente! 

Vou levar a sugestão "Íons xp" para o discutirmos na parte de engajamento! 

Obrigada novamente! Bons estudos! :)

**Comment by JoaoDev01001** [comment]
> Oi, pessoal! Muito obrigada pelas sugestões!
> 
> @JoaoDev01001, assim como o @MarceloRyujji mencionou, temos essa issue respondida com o tema semelhante: #935 A sugestão dos perfis está salva para ser considerada quando for discutido o tema futuramente!
>  íons era pra ser Ícones, mas fico grato pelo retorno 
> Vou levar a sugestão "Íons xp" para o discutirmos na parte de engajamento!
> 
> Obrigada novamente! Bons estudos! :)

**Comment by JoaoPauloPinheiroM** [comment]
Ícones*** eu errei na digitação kk

**Comment by maraishioka** [comment]
Ta tranquilo kkkkk
o importante é que deu pra entender a ideia! ;)

**Comment by designernatan** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
