### ISSUE TITLE
Exercícios práticos durante os cursos e formações

### ISSUE THREAD

**Issue by Lipedev300** [caelum/alura-funcionalidades#965]
Olá equipe Alura! Luiz Felipe falando.

Uma função que considero muito importante na plataforma são exercícios práticos durante os cursos e formações. Não basta a gente só ter um desafio no final de uma formação pra efetivá-la. Precisamos ter exercícios práticos durante cada curso, e que sejam corrigidos e que tenhamos feedback sobre nosso desempenho neles.
Eu vou ser sincero: Já vi comentários um pouco negativos sobre a Alura em outros cantos da internet falando justamente disso: Falta de exercícios pra gente treinar o que estamos aprendendo.
E que esses exercícios sejam obrigatórios para continuarmos no curso ou formação.

Estou ciente que isso também envolveria mais profissionais pra poderem corrigir tantos exercícios, mas o esforço valeria muito a pena, assim a gente poderia muito mais treinar o que estamos aprendendo, e assim melhoraria nosso aprendizado com a Alura.
Eu sei que ali já tem os chalenges e 7 days of code, mas ali o pessoal só faz se quiser. Precisamos de exercícios obrigatórios nos cursos.
É isso por hoje, obrigado.

**Comment by designernatan** [comment]
@Lipedev300 valeu pela sugestão e tempo em escrevê-la!

Algo assim seria bem interessante. Concordo contigo sobre o downside sobre a escalabilidade de algo assim e com certeza o 7DOC é algo que parte bastante da disciplina da pessoa em focar no desafio.

Tínhamos algo assim há uns anos, chamado "Projetos", mas o problema de escala (como você comentou em cima da sua sugestão) foi um desafio maior do que estávamos esperando, nos levando a dropar o projeto.

Hoje, além do 7DOC, temos são os [Challenges](https://www.alura.com.br/challenges), num tom mais async mas bem focado em vocês construírem portfolio e colocarem a mão na massa. Fica minha sugestão para você dar uma olhada.

Abração e bons estudos!

**Comment by BrazAlice** [comment]
Vou fechar a issue aqui, pessoal!

Podem voltar a comentar, se quiserem 😊

**Comment by Lipedev300** [comment]
Realmente. Como o processo de correção dos exercícios é trabalhoso, talvez uma boa ideia seria vocês construírem listas de exercícios (principalmente de programação, para criarmos programas de simples até avançados) para que possamos praticar, e talvez a Luri possa ajudar a corrigir, o que acham?

**Comment by Lipedev300** [comment]
Uma sugestão pra vocês: A Luri poderia funcionar também como um corretor, nos informando o que a gente pode melhorar, ou se o código já está bom, só bastando a gente postar o arquivo com o código para a Luri analisar.
Estou atualmente estudando programação e o que me falta mesmo é a prática. Recomendo a adição de listas grandes de exercícios pra gente praticar várias linguagens de forma independente, dividindo também os exercícios por nível de dificuldade, do básico ao pós-avançado. Sei que o desafio de vocês foi, e ainda seria grande em corrigir tudo, então vocês talvez nem precisem. Do jeito que a IA pode nos ajudar, ela com certeza pode nos auxiliar a construir códigos melhores conforme o que a gente mostrar à ela. O Coursera já possui uma ferramenta semelhante implementada, é como um corretor automático que analisa e retorna feedback dos exercícios postados na plataforma. Fica a sugestão, pois acredito que a prática é o melhor jeito da gente evoluir, principalmente em programação. É só isso que tá faltando pra o estudo se consolidar. Funcionalidade urgente a ser implementada.
