### ISSUE TITLE
Adicionar seção de formações

### ISSUE THREAD

**Issue by igorleonel** [caelum/alura-funcionalidades#966]
Olá,

sempre tenho dificuldades em encontrar todas as formações do Alura depois das novas atualizações, creio que um seção nova sobre as formações que existem, tornariam a visibilidade de todos os cursos mais ágeis.

**Comment by designernatan** [comment]
@igorleonel valeu pela sugestao!

estamos bem de olho nos feedbacks que vocês tem enviado pra gente depois da nova atualização da plataforma

pode deixar que estamos considerando opções de como melhorar a encontrabilidade [dessa tela de Formações](https://cursos.alura.com.br/formacoes)

abcs e bons estudos!

**Comment by BrazAlice** [comment]
Fechando a issue aqui, pessoal!

Podem voltar a comentar, se quiserem 😊
