### ISSUE TITLE
Flashcards para retomada de conteudos

### ISSUE THREAD

**Issue by diegodc1** [caelum/alura-funcionalidades#967]
Olá equipe Alura!

Acho que seria interessante uma área na plataforma onde os alunos pudessem "relembrar" os conteúdos estudados nos cursos realizados pelo aluno.

Isso poderia ser feito em um formato de perguntas e respostas, ou em "flashcards", ou algo semelhante, sempre com perguntas relacionadas aos cursos que o aluno já realizou.

Isso ajudaria a relembrar conceitos, sintaxe de linguagens, etc. Como alguns conteúdos são bastante extensos, é comum que parte das informações seja esquecida com o tempo, então ter uma forma de "revisar" e "relembrar" seria muito útil durante o estudo.

**Comment by designernatan** [comment]
@diegodc1 valeu pela sugestão!

lembro de já termos discutido algo assim há um tempo (inclusive, por sugestão de outros alunos aqui nesse repositório)

tem algo assim no alura língua, mas na época o que pesamos era o custo/tempo para pegar a feature de lá e puxar pra alura. Na época a conta não fechou :(

não sei se você recomenda alguma ferramenta externa, mas encontrei uma galera falando bem desse [Quizlet](https://quizlet.com/br), que deve suprir, ao menos em partes, essa dor

abcs e bons estudos!

**Comment by BrazAlice** [comment]
Ei pessoal, vou fechar a issue aqui!

Podem voltar a comentar, se quiserem 😊
