### ISSUE TITLE
O portal perde a sessão.

### ISSUE THREAD

**Issue by cardoso-mateus** [caelum/alura-funcionalidades#968]
Tem algo que acontece há muito tempo já, se é algo que já foi abordado me desculpe mas eu não achei nenhuma issue aberta relacionada.

Algumas vezes, não tão raramente, eu estou navegando nas formações e quando eu abro uma página eu sou direcionado pra versão da página sem sessão ativa, por exemplo, o link "https://cursos.alura.com.br/formacao-react-jsx-hooks" leva a página da formação listando os cursos e tudo mais, porém, há vezes em que eu sou direcionado para "https://www.alura.com.br/formacao-react-jsx-hooks" e esse link leva para a página da formação disponível para quem não fez o login, por conta disso eu tenho que ficar dando voltas no site só pra voltar pra página onde eu já estava, seja de alguma formação ou de algum curso.

**Comment by designernatan** [comment]
@cardoso-mateus valeu por reportar!

pinguei o time aqui e geralmente esse redirect "cursos.alura -> alura.com.br" é **provavelmente** pq vc deslogou. Pode ser que tenha dado timeout da session (se for conta de empresa com SSO, por ex) ou de modo geral só deslogou mesmo

talvez outro browser, app, chromecast etc? Vale trocar a senha da conta também, _just in case_

se nao for nada disso e ainda assim persistir, caminho é pingar [direto no contato da alura](https://www.alura.com.br/contato), explicando o passo a passo pra chegar no problema pra tentarmos identificar algum padrão não mapeado

abcs e bons estudos!

**Comment by BrazAlice** [comment]
Ei pessoal, fechando a issue por aqui.

Podem voltar a comentar se quiserem! 😃
