### ISSUE TITLE
Incluir Opção "Adicionar a um Plano de Estudos" para formações

### ISSUE THREAD

**Issue by claubernascimento** [caelum/alura-funcionalidades#969]
Prezados bom dia

Gostaria que a opção "Adicionar a um Plano de Estudos" esteja disponível também para Formações. Verificado que atualmente esta opção está disponível somente na pagina dos cursos.

Essa melhoria facilitaria muito pois atualmente ao se deparar com uma formação interessante temos que copiar o nome da mesma, em seguida abrir uma nova aba, acessar os nossos planos de estudos, selecionar e editar o mais adequado para aquela formação e em seguida fazer uma busca pela mesma e só aí adicionamos e salvamos o plano de estudo.

Espero que ajude. Obrigado

**Comment by designernatan** [comment]
@claubernascimento valeu pela sugestão!

estamos com umas melhorias mapeadas para essa página que você citou, então aguarde novidades no futuro de médio prazo :))

abração e bons estudos!

**Comment by BrazAlice** [comment]
Ei pessoal, vou fechar a issue aqui!

Podem voltar a comentar, se quiserem 😊
