### ISSUE TITLE
Poder responder uma duvida no forum depois de um tempo sem resposta

### ISSUE THREAD

**Issue by heron03** [caelum/alura-funcionalidades#97]
Eu estava fazendo um curso de test unitário no flutter e no forum desse curso tem poucas pessoas respondendo e uma das duvidas que tem nele eu sei a resposta mas não posso responder pois passou 2 semanas e com isto não mostra um campo de escrita e sugere que eu crie uma nova dúvida mas eu não tenho dúvida, poderia deixar habilitado sempre para quem quiser responder.
![Captura de Tela (64)](https://user-images.githubusercontent.com/35074726/76779404-11ccbe80-678a-11ea-9f7d-13afb1ab599e.png)
![Captura de Tela (65)](https://user-images.githubusercontent.com/35074726/76779481-2f018d00-678a-11ea-8829-552020385c87.png)

**Comment by castrohs** [comment]
O autor deve clicar em solucionado, sua pergunta então não é possivel adicionar novas respostas, exemplo stack over flow.
Tópico podem ser encerrados por um administrador ou pelo autor.
Mas tópicos sem resposta, mesmo após 3 anos, alguem uma hora vai conseguir entender a criatura, se o dono do post não tiver mais como olhar o post por que seu status for igual a (¬aluno) então você fecha o tópico a este aluno voltar a ser membro, ou seja você só vai ter tópicos abertos a resposta de membros ativos da plataforma.
Se eu voltar a pagar daqui um tempo é meu dever fechar os meus tópicos, ou se eu não pagar mais eles estão impedidos de serem respondidos.
Vocês podem colocar um sistema de pontos na pergunta.
Vocês podem colocar um sistema de pontos nas resposta util + 2 , inutil - 1 (algo assim) ai a pessoa teria um rank dentro da comunidade.
Deem uma olhada no stack pode ser de ajuda.
A pessoa que reabrir um tópico antigo para dizer que tem a mesma duvida poderia ter como um administrador promover o pedido a uma nova pergunta .
**Outra opção é deixar a duvida aberta por um período maior de tempo ao invés de 2 semanas, 2 meses e ai fechar sozinho**
Por que eu sei varias coisas de uns tópicos e podia ter respondido tópicos vazios como os sobre codeigniter, mas o que eu fiz, não deu eu vim questionar.
Este é o ponto ou aumenta-se o tempo ou deixa aberto.
