### ISSUE TITLE
Correção na acessibilidade do campo de busca

### ISSUE THREAD

**Issue by gabriel-ribeiro-dev** [caelum/alura-funcionalidades#970]
Olá, boa tarde!
  Agora, reparei que no campo de busca, depois que foi corrigido o bug que não era possível achar o campo navegando com tabe e setaas, também foi incluso uma aria-label com o Texto "Campo de pesquisa para buscar o termo desejado", e o label normal, "O que você quer aprender"?
  Essa ária-label é muito grande e desnecessária, uma vez que a partir que vem escrito o que você quer aprender sendo um form, é possível entender que é um campo de busca.
  Talvez seja interessante diminuir o texto, como usuário de leitor de tela, me atrapalha um pouco.
  O mesmo vale pro botão "Realizar busca pelo termo digitado", pra que isso?
  Buscar já bastava.
  Atenciosamente.
  Gabriel.

**Comment by designernatan** [comment]
@gabriel-ribeiro-dev valeu pelo feedback de a11y!

comentei com o time aqui para considerar no próximo update da tela, ok?

abração e bons estudos!

**Comment by BrazAlice** [comment]
Ei pessoal, vou fechar a issue aqui!

Podem voltar a comentar, se quiserem 😊
