### ISSUE TITLE
Issue Report

### ISSUE THREAD

**Issue by mulliru** [caelum/alura-funcionalidades#971]
**Descrição do Problema**
Ao logar na Alura hoje pela manhã notei que na aba de notificações foi lançada uma notificação com o nome provavelmente com defeito relacionada à um vídeo postado no canal do Youtube da Alura.

**Imagem do Problema**
![image](https://github.com/user-attachments/assets/51f8b4f3-b8ea-48f4-877b-02b6d8e99310)

**Passos para Reproduzir**

- Acesse o site da Alura.
- Faça login no portal da Alura
- No header clique na aba de novidades
- Desça a pagina até encontrar a notificação em questão

**Comportamento Esperado**
A notificação do vídeo provavelmente ter outro nome

**Comment by masromao** [comment]
Fala @mulliru , tudo certo?
Muito obrigado pelo report sobre esse conteúdo nas notificações.
Conversei com o time responsável, a notificação já foi encontrada e atualizada para o nome correto, agora tá certinho!

Obrigado novamente, abraços e bons estudos!
: )
