### ISSUE TITLE
[Sugestão] Salvar Formações para mais tarde

### ISSUE THREAD

**Issue by jaumzitz** [caelum/alura-funcionalidades#973]
Olá.

Desde que eu iniciei na Alura 2 anos atrás, sempre senti muita falta de um recurso que me possibilitasse **salvar** uma formação para faze-la mais tarde.

Atualmente só é possível acompanhar o progresso no Dashboard de uma Formação por vez.

Seria um recurso similar ao de Plano de Estudos, mas que possibilitasse não somente a inclusão de Cursos, mas também permitisse manter no radar a próxima Formação que desejo estudar.

Obrigado!

**Comment by masromao** [comment]
Olá @jaumzitz , tudo bem?
Interessante sua ideia de lista de Formações, pode me falar um pouco mais sobre como funcionaria esse recurso?

Por hora minha recomendação seria:
1 - Dentro da pág da Formação desejada, clicar em EXIBIR NO MEU DASHBOARD
2 - Após isso, clicando no link Formações e Planos de Estudon do menu lateral, você consegue acompanhar o progresso de todas as Formações que iniciou na lista dessa página.

Obrigado novamente pela sugestão enviada.
Abraços e bons estudos : )

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
