### ISSUE TITLE
Tela de Formações

### ISSUE THREAD

**Issue by Ceilton** [caelum/alura-funcionalidades#974]
Essa tela do site da Alura:

https://cursos.alura.com.br/formacoes

Deveria estar mais explicita no site. Sugiro que tenha um botão para esse link ao lado do botão "Dashboard".
Como sou um estudante voraz, estou sempre pensando no que farei a seguir. 
Eu acesso muito essa tela.

**Comment by masromao** [comment]
Olá @Ceilton , tudo bem?
Muito obrigado pela sugestão de trazer esse botão com a tela de Formações mais evidente.

Estamos redesenhando a experiência da plataforma gradativamente e com certeza feedbacks como o seu são muito importantes para nós. Quando formos atualizar seções da plataforma futuramente com certeza levaremos sua ideia em consideração.

Muito obrigado novamente.
Abraços e bons estudos : )

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
