### ISSUE TITLE
[Sugestão de melhoria] Link de perfis

### ISSUE THREAD

**Issue by vitorabujamra** [caelum/alura-funcionalidades#975]
Atualmente tenho criados 3 perfis de acesso ao portal devido mudança de empregos anteriores.
por exemplo:

***@empresa1.com.br
***@empresa2.com.br
***@gmail.com

Seria muito interessante se fosse possível a união de todos esses perfis através do CPF. 
Ao invés de cada mudança de empresa eu precisar vincular um novo e-mail, a empresa faria a inclusão do meu perfil no plano através do CPF, garantindo e facilitando o acesso a todos os certificados obtidos anteriormente e até mesmo a consulta de um histórico do colaborador em outras datas.

**Comment by masromao** [comment]
Olá @vitorabujamra , tudo bem?
Temos um caso muito parecido com o que você descreveu [aqui nessa issue](https://github.com/caelum/alura-funcionalidades/issues/665).

A orientação que trazemos nela é:

"Faz um tempo que paramos de dar essa unificada (mesmo manualmente) pois acabava dando alguns problemas internos

ideal é entrar em contato direto por e-mail com a gente no [contato](https://www.alura.com.br/contato), explicar a situacao (empresa, perfil, etc) e ver se há essa possibilidade por lá"

Só reforçando aqui que é uma possibilidade, não conseguimos garantir que consigam, infelizmente.

De qualquer forma, obrigado pela sugestão de unir os perfis pelo CPF.
Abraços e bons estudos!

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
