### ISSUE TITLE
Reorganização da plataforma, com mais intuitividade e assistência em trilhas e temas de estudos

### ISSUE THREAD

**Issue by agrygonis** [caelum/alura-funcionalidades#976]
Tenho utilizado e indicado a plataforma nos últimos anos, inclusive para uso corporativo, porém a usabilidade tem piorado muito. A plataforma tem virado uma bagunça. Em tempos de IA Generativa e a experiência comprovada com os assistentes pessoais, sugiro que analisem um dos maiores valores da plataforma, que é ser o assistente na trilha de estudos dos Alunos, de forma a otimizar e organizar de forma mais aderente ao mercado e de valor para especialização profissional, com a montagem de formações mais clássicas voltadas aos perfis mais concretos e especializados de mercado, com por exemplo, formação em Java ou formação em Desenvolvimento Android, visando atender as organizações das áreas de tecnologia das empresas de fim a fim como também os modelos aderentes as as tendências para autônomos. Até pensar nas formações versionadas por anos como por exemplo Formação Java 2024, com no novo release a cada ano. Enfim, ser uma plataforma que além dos milhares de conteúdos importantes e de muita qualidade, seja focado em UX moderno sem perder o valor no facilitar a vida na formação de seus alunos. Ser uma plataforma que contribua com os alunos que acham que as universidades são muito pequenas para eles, com a liberdade de se aprimorem no seu tempo, velocidade e vontade e quem sabe em um futuro ser uma plataforma que graduem os alunos por inercia através de créditos conquistados. Me parece que se perderam na missão, visão, valores e princípios, renovei este ano, mas muto triste com essa bagunça e usabilidade perdida.

**Comment by HatPaTrick** [comment]
Concordo, a UI antiga era até mais intuitiva que a atual, parece que simplificaram demais em questão pra se adequarem ao mobile... Em vez de terem uma UI pro Mobile e outra pra Web, eles podem resolver...

**Comment by masromao** [comment]
Olá @agrygonis e @HatPaTrick , muito obrigado pelas mensagens enviadas.

Achamos muito interessantes os pontos trazidos em relação a usabilidade da plataforma e os conteúdos, e de como traria mais valor para os estudantes a união dessas experiências num caminho mais intuitivo e mesclado com o desejo de estudar das pessoas em suas experiências individuais. Acredito que os pontos levantados tem bastante sentido e gostaria de trazer que estamos num momento exatamente de olhar para insights como esse, para irmos melhorando a experiência geral da plataforma para os usuários. 

Estamos movimentando a plataforma e testando abordagens com foco na evolução e melhora de experiência no geral, então sugestões como essas são muito válidas para entendermos pontos de melhoria. 

Obrigado novamente pelos pontos, com certeza levaremos em conta quando formos priorizar novos ajustes e melhorias da plataforma.

Abraços e bons estudos :)

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
