### ISSUE TITLE
Reiniciar o registro de progresso do curso

### ISSUE THREAD

**Issue by Ac-Franko** [caelum/alura-funcionalidades#977]
**Ao finalizar o curso**, seria viável ter a opção de **reiniciar todo o registro de progresso**? 
Por "reiniciar" quero dizer apagar o registro de todas as respostas e pontuações anteriores, de modo a ter um novo registro, "zerado" novamente, do (re)início. 
Isso seria bastante atrativo e conveniente a quem desejar refazer os cursos já concluídos.

**Comment by masromao** [comment]
Olá @Ac-Franko , tudo bem?
Muito obrigado pela sugestão! Como discutimos [nessa issue aqui](https://github.com/caelum/alura-funcionalidades/issues/635), por hora não temos planos para adicionar o reset de progresso de cursos na plataforma.

Muito obrigado novamente pelo contato.
Abraços e bons estudos : )

**Comment by HatPaTrick** [comment]
Olá, em vez de apenas colocarem pra reiniciar o curso, poderiam pelo menos colocar a função de Marcar a Aula como Concluída, e podermos desmarcar a hora que quisermos... como várias das outras plataformas de cursos fazem, isso ajudaria bastante a rever o curso, mesmo que manualmente, eu indo lá e desmarcando as aulas, módulo por módulo, ajudaria a rever o Curso, pois tem cursos avançados que os iniciantes se perdem e é melhor rever o curso por completo.

**Comment by masromao** [comment]
Olá @HatPaTrick !
Muito obrigado pelo complemento na sugestão da @Ac-Franko .
Interessante sua ideia de desmarcar a Aula Concluída. 

Realmente por hora não temos planos para adicionar features relacionadas ao progresso de cursos na plataforma.
Mas com certeza levaremos essa ideia em consideração se formos mexer em algo relacionado.

Muito obrigado novamente pelo contato.
Abraços e bons estudos : )

**Comment by Ac-Franko** [comment]
Obrigada pelo retorno, @masromao.
Muito boa a ideia de @HatPaTrick, eu a endosso.

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
