### ISSUE TITLE
Marcar Aula como Concluida.

### ISSUE THREAD

**Issue by HatPaTrick** [caelum/alura-funcionalidades#978]
Poderiam adicionar uma função que pode se marcar a aula como concluída, tão quanto tirar o concluído da Aula, como em outras plataformas de cursos, acho que a maioria das plataformas tem essa funcionalidade que ajuda demais a rever cursos já concluídos, podendo manualmente tirar os progressos da aulas já salvas... Ajudaria a galera que está revendo cursos, ou apenas quer rever um módulo de um curso, sem ter que reiniciar... Não sei porque ainda não tem, sendo que é uma função de fácil implementação, e com vários sites e cursos tendo essa função...

**Comment by BrazAlice** [comment]
Muito obrigada pela sugestão @HatPaTrick!

Estamos realizando algumas melhorias na tela de aula e certamente levantaremos esse ponto nas discussões. Não podemos garantir a implementação da funcionalidade no momento, mas com certeza ela será discutida com o time. Acredito que os pontos levantados tem bastante sentido e gostaria de trazer que estamos num momento exatamente de olhar para insights como esse, para irmos melhorando a experiência geral da plataforma para os usuários.

Abraços e bons estudos! 😃

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
