### ISSUE TITLE
O alura não está abrindo 

### ISSUE THREAD

**Issue by silvanascimento760** [caelum/alura-funcionalidades#979]
Descreva a funcionalidade que você gostaria que tivesse na plataforma.

Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

**Comment by BrazAlice** [comment]
Olá @silvanascimento760 vi que você abriu outra [issue](https://github.com/caelum/alura-funcionalidades/issues/980), eu já dei um retorno por lá, OK?

Vou fechar essa issue aqui. Abraços 😃
