### ISSUE TITLE
Reprodução automática

### ISSUE THREAD

**Issue by douglasalvesnunes** [caelum/alura-funcionalidades#98]
Olá. Estou aprendendo vários cursos da Alura principalmente da área de programação. Gosto da forma como é produzido o conteúdo e principalmente dos vídeos. Porém, algo que me incomoda, é a falta de passagem automática de lição quando estou reproduzindo um vídeo em tela cheia. Acredito que seria interessante quando assistimos um video em tela cheia ter a opção de passar para a próxima atividade sem ter que minimizar a tela para escolher a opção de próxima atividade.

**Comment by designernatan** [comment]
oi @douglasalvesnunes [tem essa issue](https://github.com/caelum/alura-funcionalidades/issues/46) criada sobre esse auto-play, pode comentar lá depois?

inclusive um debate é se esse auto-play funcionaria apenas para vídeos ou exercício tbm

valeu!

**Comment by sahslima** [comment]
@douglasalvesnunes, tudo bem?

Não sei se já viu, mas finalmente **lançamos a reprodução automática**! Haha

[Este artigo](https://www.alura.com.br/artigos/novidades-de-janeiro-na-alura) explica rapidamente a funcionalidade.

Depois conta pra gente o que achou. ;)

Um abraço!

**Comment by douglasalvesnunes-zz** [comment]
Olá,
designernatan, obrigado pela resposta e desculpe a demora.
sahslima, obrigado pela resposta.
Fico feliz pela implementação e atenção à sujestão. Já estou testando e está muito bom.
