### ISSUE TITLE
O alura não abre 

### ISSUE THREAD

**Issue by silvanascimento760** [caelum/alura-funcionalidades#980]
O alura não está abrindo para terminar o curso

**Comment by BrazAlice** [comment]
Ei @silvanascimento760 :)

No momento em que escrevo, a Plataforma está funcionando OK por aqui. Como sugestão, envie mais informações direto no contato, pois o time de sucesso do aluno vai conseguir guiar você melhor: https://www.alura.com.br/contato

Espero que consiga resolver logo logo... Abraços e bons estudos 😃

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
