### ISSUE TITLE
Modo noturno para o dashboard

### ISSUE THREAD

**Issue by Drey-cf** [caelum/alura-funcionalidades#982]
Acredito que um dashboard como modo noturno seria muito agradável, assim como é para as aulas com fundo noturno.
Penso que tem um grande potencial se fizerem no mesmo estilo que está a nova cara do dashboard,

**Comment by BrazAlice** [comment]
Eii @Drey-cf tudo bom? Muito obrigada pela sugestão!

Há uns meses analisamos a possibilidade de implementar darkmode em toda a Alura, mas infelizmente não temos um prazo de quando isso será disponibilizado :/

Uma dica para utilizar o modo noturno hoje seria usar a extensão do Chrome "dark reader", que força o dark mode nas páginas. O navegador Opera tem essa opção já nativa.

Abraços e bons estudos!

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
