### ISSUE TITLE
Bug visual com a Aula atual dos cursos

### ISSUE THREAD

**Issue by feMoraes0** [caelum/alura-funcionalidades#983]
Quando se favorita um novo curso sem fazer alguma aula ou se inscrever, ele mostra como "Aula atual" a aula que está sendo feita no último curso que acessou.

Explicando mais detalhadamente e com imagens:

Estou fazendo o curso "Single SPA" que é mostrado na minha tela "Home"
![Captura de Tela 2024-10-01 às 10 13 59](https://github.com/user-attachments/assets/57e552c0-0e68-444d-a7a0-156e28cb63e7)
Na imagem mostra "Aula atual: Estilizando a Navbar - 29min" que é exatamente a aula que parei neste curso.

Quando favoritei um curso de Testes com TypeScript, passou a aparecer na tela "Descobrir", conforme imagem:
![Captura de Tela 2024-10-01 às 10 12 02](https://github.com/user-attachments/assets/3458b37e-faf8-4377-9ef8-d402080f1ec5)

O problema: No card deste curso (Testes com TypeScript) também aparece "Aula atual: Estilizando a Navbar - 29min", só que esse curso não tem essa aula e nem foi iniciado ou inscrito, eu apenas favoritei ele.

**Comment by artnicodemus** [comment]
Opa, muito obrigado pelo detalhamento do bug @feMoraes0 !
Encaminhei para o time responsável investigar.
Abraço e bons estudos!

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
