### ISSUE TITLE
Gerar certificados agrupados por formação ou grupo de estudos

### ISSUE THREAD

**Issue by diogogyn** [caelum/alura-funcionalidades#984]
Atualmente a plataforma permite que realize o download dos certificados individuais  ou completo (listando todos de uma vez).
Sugiro criar a possibilidade de baixar os certificados agrupados por formações, uma vez que o aluno tiver finalizado todas os cursos de uma determinada formação. Assim o certificado acumula as horas em um único lugar.
Sugiro pois alguns processos seletivos e/ou concursos, contabilizam pontos por cursos realizados, porém somente aqueles com carga horaria superior a 20 horas.

**Comment by artnicodemus** [comment]
Boa tarde @diogogyn , obrigado pelo feedback!
Hoje quando você finaliza uma Formação, já fica disponível o certificado dela, onde mostramos a soma de horas dos cursos que fazem parte dela.
A Formação que você terminou não está aparecendo desta forma lá no perfil?
![image](https://github.com/user-attachments/assets/ce31d387-f269-406c-a4cb-05548803204e)
![image](https://github.com/user-attachments/assets/5c3c2ad0-de9f-4955-a582-751f8aae49ad)

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
