### ISSUE TITLE
Erro no layout da navbar

### ISSUE THREAD

**Issue by IgorKoppen** [caelum/alura-funcionalidades#985]
O layout apresenta um erro de sobreposição na navbar, onde os elementos de navegação estão posicionados abaixo onde input de pesquisa fica acima da navegação do dashboard. provavelmente relacionado com maxwidth da navbar.
![imagem_2024-10-06_223447689](https://github.com/user-attachments/assets/a89e916e-6b51-40f5-b912-59da3b646325)

**Comment by artnicodemus** [comment]
Opa, obrigado pelo feedback @IgorKoppen !
Vou encaminhar para o time responsável entender o que está acontecendo.
Poderia me falar qual tamanho de resolução que você está usando no navegador/monitor?
Por acaso você esta usando algum zoom na página? Ou utilizando o navegador em um espaço menor da tela?

**Comment by IgorKoppen** [comment]
Oi, @artnicodemus! Aparentemente, o problema acontece em qualquer tela maior que HD. Estou usando um monitor Full HD (1920x1080) e outro Ultrawide, e o comportamento se repete em ambos. Não utilizei zoom na página e já testei no Chrome e no Opera.

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
