### ISSUE TITLE
Link de pequenas correções nos artigos

### ISSUE THREAD

**Issue by cedugenio** [caelum/alura-funcionalidades#986]
Gosto muito dos artigos da Alura e tutoriais e seria muito bacana ter uma opção de sugerir correções em artigos 
Por exemplo no artigo : https://www.alura.com.br/artigos/get-dummies-vs-onehotencoder-qual-metodo-escolher

Essa linha tem um pequeno erro : 
de: modelo_one_hot = pd.read_**picke**('modelo_onehotenc.pkl')
para: modelo_one_hot = pd.read_**pickle**('modelo_onehotenc.pkl')

Com essa "caixa de correções" diretamente no artigo poderíamos interagir e vcs saberiam em que ponto iriam interagir e ajudar os alunos. 

Alguns sites de notícias usam essa técnica que ajuda muito em pequenas correções.

Espero que tenha ajudado em algo

**Comment by designernatan** [comment]
@cedugenio brigadao pela sugestao! E pela correção também hahah

acabou passando essa e uma feature assim seria interessante mesmo

queremos refazer alguns pontos ali no blog no futuro de médio prazo, ai vamos jogar essa ideia na roda de conversa

obrigado novamente e otimo fds! :))

edit:
ja corrigi o artigo aqui também, deve atualizar em algumas horas no máximo

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)
