### ISSUE TITLE
Adicionar Tela

### ISSUE THREAD

**Issue by GustavoM8** [caelum/alura-funcionalidades#987]
Adicionar umas outra tela com botão para direcionar somente para a pagina para cursos que foram selecionados como favorito,
acho que fica mais interessante e interativo com o usuario.

**Comment by juliagodinhoo** [comment]
Oi @GustavoM8, muito obrigado pelo seu feedback! Realmente estamos revisitando vários fluxos da plataforma e feedback como esses são essenciais para entendermos as necessidades dos nossos usuários.

Caso te ajude, atualmente temos um fluxo que leva para todos os cursos favoritos. A partir da dash, no card de curso "em andamento", tem um link abaixo escrito "ver todos os cursos em andamento". Ao clicar, será levado p/ a pág "meus cursos", onde os favoritos estarão logo no topo na página. Para facilitar, deixo uma imagem mostrando o fluxo.

![Cursos favoritos](https://github.com/user-attachments/assets/0037da9e-b3ce-4d50-9d71-9d70c8033fd2)


Para nos ajudarmos ainda mais a compreender suas necessidades, poderia me dizer:

- Como você utiliza, no dia-a-dia e fluxo de estudo, os "cursos favoritos"? 
- O atual formato e organização dos seus cursos em andamento na plataforma tem ajudado no seu fluxo de estudo e a acessar mais rapidamente o curso que precisa? Por que? 
- Se pudesse mudar algo na organização dos cursos, o que seria e por que?

**Comment by maraishioka** [comment]
Vou fechar a issue aqui, gente!
Podem voltar a comentar, se quiserem ;)

**Comment by designernatan** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
