### ISSUE TITLE
Download de projetos

### ISSUE THREAD

**Issue by MaykRhenderson** [caelum/alura-funcionalidades#988]
Poderia haver uma função de fácil acesso no dashboard para fazer o download dos projetos finais dos cursos ou formações já concluídos/as. No momento, temos que sair procurando curso por curso e adentrar em cada um para chegar até a última etapa, onde fica o download final. Seria mais conveniente tê-los diretamente no dashboard, no mesmo ambiente onde vejo meus cursos e formações concluídos/as, facilitando o acesso aos projetos específicos sempre que necessário.

**Comment by juliagodinhoo** [comment]
Oi @MaykRhenderson, muito obrigado pelo seu feedback!

Estamos num momento de rever vários fluxos da plataforma e irei levar sua proposta pra discussão com o time, só não consigo te garantir a implementação :)
 
 Abraços, bons estudos e uma ótima semana!

**Comment by designernatan** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
