### ISSUE TITLE
Tela de seleção de cursos com filtros e mais detalhes

### ISSUE THREAD

**Issue by lucasriechelmann** [caelum/alura-funcionalidades#99]
Na tela inicial do site exemplo https://www.alura.com.br/cursos-online-programacao é possível clicar nos filtros "Todos os Cursos", "Lógica de Programação", "Python", etc isso facilita bastante, e também no card do curso tem as informações se é básico, intermediário ou avançado e carga horária

![alura 1](https://user-images.githubusercontent.com/10465626/77008314-d5ea5280-695d-11ea-89f4-ec74820f8da5.png)

Já na tela de cursos quando vou escolher um curso novo não existe a opção de filtro, como estou maratonando os cursos por estar de quarentena e estou fazendo em média um ou dois por dia, eu tenho que ir rolando a página até o final para selecionar os de dotnet e nos cards não tem as mesmas informações.

![alura 2](https://user-images.githubusercontent.com/10465626/77008517-34afcc00-695e-11ea-98cc-6b980c36550b.png)

**Comment by designernatan** [comment]
oi @lucasriechelmann valeu pela sugestao!

faz total sentido, quando pegarmos essa tela para mudar vou levantar esse ponto, uma vez que o código já está pronto deve facilitar na hora de codar

abcs!
