### ISSUE TITLE
exibição de cursos , e formações 

### ISSUE THREAD

**Issue by Ltbs1981** [caelum/alura-funcionalidades#990]
Pelo amor de Deus, voltem com o menu de antes, quando estamos buscando novas formações e dentro dessas formações, vocês tinham os cursos, agora está bem complicado achar qualquer coisa, ainda mais para quem é deficiente visual. 
Quanto mais detalhada e focada for a descrição, melhor de priorizarmos, debatermos e de implementarmos.

**Comment by maraishioka** [comment]
Olá, @Ltbs1981 !
Agradecemos muito por compartilhar esse relato. Sentimos em saber que a navegação ficou pior, tenha certeza que nunca foi a ideia. Já encaminhei seu feedback ao nosso time de desenvolvimento para que possamos discutir e buscar melhorias na acessibilidade e navegação da plataforma.

Você poderia nos relatar com mais detalhes os problemas enfrentados? Isso nos ajudaria bastante. 
Você usa o NVDA, especificamente?

Novamente, muito obrigada pelo seu relato e pelo seu tempo.

**Comment by Ltbs1981** [comment]
Boa tarde, não precisa se preocupar, achei o que eu estava procurando, você só mudaram de lugar, e sim, eu uso esse software para ler telas, o caso não foi nem acessibilidade, só esse novo menu que vocês colocaram, é que a gente usa leitores de tela, toda vez que tem uma mudança assim em sites, temos que nos adaptar toda vez com o novo caminho, mas isso não tem problema, faz parte do processo, mais uma vez obrigado pela atenção, não precisam se incomodarLuciano TadeuEm 14 de nov. de 2024, à(s) 11:53, Mara Ishioka ***@***.***> escreveu:﻿
Olá, @Ltbs1981 !
Agradecemos muito por compartilhar esse relato. Sentimos em saber que a navegação ficou pior, tenha certeza que nunca foi a ideia. Já encaminhei seu feedback ao nosso time de desenvolvimento para que possamos discutir e buscar melhorias na acessibilidade e navegação da plataforma.
Você poderia nos relatar com mais detalhes os problemas enfrentados? Isso nos ajudaria bastante.
Você usa o NVDA, especificamente?
Novamente, muito obrigada pelo seu relato e pelo seu tempo.

**Comment by maraishioka** [comment]
@Ltbs1981, não foi incômodo algum! Precisamos estar atentos a essas questões, e seu relato é super bem-vindo. 
Estamos sempre buscando melhorar a plataforma como um todo, e a participação dos alunos é essencial nesse processo.

Fico feliz que você conseguiu encontrar o que procurava. Estamos aqui para ajudar sempre que precisar! Mais uma vez, muito obrigada por compartilhar sua experiência com a gente!

Bons estudos! 😊

**Comment by designernatan** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
