### ISSUE TITLE
Integrar techguide com a alura

### ISSUE THREAD

**Issue by oviniciusfarias** [caelum/alura-funcionalidades#991]
O Techguide.sh, porém é muito trabalhoso e confuso ficar acessando ele para ver quais cursos/formações são necessárias para dominar uma tecnologia.

Seria muito legal ter uma versão dentro da alura, somente com os cursos/formações para determinada tecnologia.

Hoje é muito confuso escolher as formações/cursos para progredir em uma especialização dentro da plataforma. Essa integração entre Techguide.sh e a plataforma da Alura ajudaria muito a guiar o aprendizado.

**Comment by maraishioka** [comment]
Olá, @oviniciusfarias ! Obrigada por trazer essa sugestão! 
Ter o Techguide.sh integrado à plataforma seria realmente útil na organização do aprendizado! 
Ainda não temos previsão para isso, mas agradecemos muito pela sugestão e assim podemos considerar essa ideia no futuro! 😊 

💡 Uma ideia que pode te ajudar é usar o Notion para organizar e acompanhar seu progresso na área de interesse, utilizando os conteúdos do Techguide! O Notion tem uns templates bem legais! 
https://www.notion.so/pt/templates/category/school

**Comment by oviniciusfarias** [comment]
Olá, @maraishioka! Obrigado pelo retorno.
Tentei utilizar o Notion, mas como não há uma forma "fácil" de mandar os cards pra lá acabei optando pela velha e boa planilha hehe.

Vou ficar atento caso essa funcionalidade seja implementada, realmente ajudaria bastante e seria muito utilizada.

**Comment by designernatan** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
