### ISSUE TITLE
Manter a velocidade nos vídeos

### ISSUE THREAD

**Issue by AshileySabah** [caelum/alura-funcionalidades#992]
Estou usando o chrome. Antes, quando eu mudava a velocidade dos vídeos, os próximos vídeos mantinham a velocidade, agora sempre retorna à velocidade x1.

**Comment by maraishioka** [comment]
Olá, @AshileySabah ! Como você está?  
Fiz o teste agora na plataforma, e a velocidade alterada está sendo mantida entre os vídeos. 

Tem algumas coisas que você pode fazer pra tentar solucionar o problema:
1. Dá uma conferida se o seu navegador (Google Chrome) está atualizado.
2. Se estiver tudo atualizado certinho, pode ser algo relacionado ao cache ou extensões no navegador. 
-> Experimenta **limpar o cache do navegador** e/ou **desativar extensões temporariamente** para verificar se está gerando algum conflito.

Caso o problema persista, me avisa! Vamos ajudar você a resolver. 😊

**Comment by designernatan** [comment]
fechando a issue por aqui, pessoal

podem voltar a comentar se quiserem :)
