### ISSUE TITLE
Barra de progresso do vídeo

### ISSUE THREAD

**Issue by danilobatistaqueiroz** [caelum/alura-funcionalidades#994]
Eu fico ansioso em saber se o vídeo está no meio ou já no fim e preciso passar o mouse sobre a tela para saber.

Aposto que todo mundo sente isso.

Isso tira o foco, reduz a concentração, pois é necessário ir com o mouse na tela.

Creio que colocar uma barra de progresso contante num canto do vídeo mesmo que bem pequenininha irá melhorar o desempenho dos alunos, sinto que perco desempenho na absorvição do conteúdo da aula por estar preocupado em ver o progresso do vídeo.

Uma sugestão é um relógio redondo no canto que vai girando o marcador e no finalzinho fique vermelho.

**Comment by designernatan** [comment]
@danilobatistaqueiroz valeu pela sugestao!

recebemos feedbacks exatamente do contrário viu, em limpar mais a tela de aula pra conseguir ter mais foco no estudo

a gente quer mexer na tela de aula no futuro, mas pra tentar resolver seu problema hoje, o que recomendo:

1. instala a extensão [Stylebot](https://stylebot.dev/), ela é bem boa pra customizar CSS de páginas
2. cadastrar o cursos.alura.com.br no Stylebot e coloca o seguinte CSS:
```
.vjs-has-started.vjs-user-inactive.vjs-playing .vjs-control-bar {
  opacity: 1;
}
```

com isso, sempre que você tiver estudando, os controles do player vão ficar sempre visíveis

abcs e bons estudos!

**Comment by danilobatistaqueiroz** [comment]
Que dica fantástica, eu penso diferente, preciso da barra de progresso para me acalmar, obrigado.
